### ISSUE TITLE
`run_examples.sh` could use wrong python executable

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#1022]
On systems with different Python versions installed there is a problem when using `share/doc/nest/run_examples.sh`. With `runner=python` in line 70 only the standard Python version of the system is used, but if NEST was built with a different one, this could end in an error. 

Isn't it better to use something like that:

    PYRUNNER=$($NEST_INSTALL_DIR/bin/nest-config --python-executable)

and then:

    runner=$PYRUNNER

**Comment by jougs** [comment]
I like this suggestion. Can you please review #1024?
