### ISSUE TITLE
Rename `get_delay` -> `get_delay_steps` in `Event`?

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#1025]
As far as I can see, `get_delay()` of events (https://github.com/nest/nest-simulator/blob/master/nestkernel/event.h#L170) returns a delay in steps. For consistency, shouldn't this function be called `get_delay_steps()`? if so, I can create a PR. @suku248 @heplesser @jougs

**Comment by heplesser** [comment]
@jakobj A good point. We have here
```c++
void set_delay( delay );
delay get_delay() const;
long get_rel_delivery_steps( const Time& t ) const;
```
I think the original logic was that the data type `delay` would indicate that values were in steps, so one would not need the `steps` in the method name. This holds for the first two. The third method then has the `steps` in the name and uses the generic `long` as return type.

When reading code that uses these methods, the return and argument types are usually not visible (and moving to C++11 with its wonderful `auto` they will be even less), so I would tend to `_steps` in the name. The question then is if we want to retain our NEST-specific types such as `delay`.

Should we discuss this in the next ONDVC?

**Comment by jakobj** [comment]
yes, i feel like using nest specific types to indicate in which form the time is represented is not optimal style. i have found myself looking up the implementation again and again to figure out what exactly these functions return, so more descriptive and coherent naming seems necessary.

regarding nest-specific types in general: my feeling is we should remove all of them, since i've found them always more confusing than helpful. let's discuss it in the next VC.

**Comment by heplesser** [comment]
VC on 17 Sep 2018 agreed with suggestion to add `_steps` to `{get,set}_delay()`.
