### ISSUE TITLE
Factor out MyModule as a standalone repository

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1028]
We promote `MyModule` as a way to extend NEST without requiring the NEST sources around, I propose to go the full length and make it it's own repository under the roof of the NEST Initiative. This would have the following advantages:
* `MyModule` documentation disentangled from NEST documentation
* better discoverability for `MyModule` code and documentation
* natural way of enabling CI for the code
* ability to see who forked the module 

See also #56 (for a request to revise the built setup of `MyModule` and #805 (for a request to enable CI for `MyModule`).

**Comment by clinssen** [comment]
The fate of ConnPlotter, a contribution by @heplesser and one of his students, might also be relevant for this discussion. ConnPlotter is a perfectly self-contained package, with documentation and a good file layout (it is currently in `extras/`), and as such, it is also a good candidate for being spun off into its own repository (e.g. github.com/nest/ConnPlotter).

As for the documentation: writing a user extension module is currently described in the "Developer Space". For things like ConnPlotter, it would be nice to have a "Contributions" page in the Developer Space, where we could place a link to it. We currently have these on the GitHub wiki (https://github.com/nest/nest-simulator/wiki/NEST-Modules). I would propose to remove this wiki page entirely (it is one of only two wiki pages not pertaining to the VC), and file a PR against the gh-pages branch to include this information in the Developer Space.
