### ISSUE TITLE
`get_K_value()` can return 0 erroneously in edge case

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1034]
To compute the postsynaptic trace, the function `Archiving_Node::get_K_value(double t)` finds the last known spike in the history, and decays exponentially from that point on (https://github.com/nest/nest-simulator/blob/0c993abc963c709e7632b9cb5fc701d155d8ab40/nestkernel/archiving_node.cpp#L98).

An edge case can arise when presynaptic spike times precisely coincide with postsynaptic spike times. To replicate the issue, generate a list of pre and a list of post spike times, e.g.:

    pre_st = [  2.   5.   7.   8.  10.  11.  15.  17.  20.  21.  22.  23.  26.  28.]
    post_st = [  3.   7.   8.  10.  12.  13.  14.  16.  17.  18.  19.  20.  21.  22.]

Note that there are no duplicates in each individual list. (I'm not sure if this is something that should be supported--note that the SpikeGenerator supports this behaviour.) 

Hook up an STDP synapse between two parrot neurons which are parroting SpikeGenerators with the above spike times.

Log shows the returned value by `get_K_value()`. The fall-through case (https://github.com/nest/nest-simulator/blob/0c993abc963c709e7632b9cb5fc701d155d8ab40/nestkernel/archiving_node.cpp#L115) is marked by asterisks ("*** 0 ***"):

    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 2) = 0
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 5) = 0.951229
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 7) = 0.860708
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 8) = *** 0 ***
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 10) = 2.59689
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 11) = 2.47023
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 15) = 4.69725
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 17) = *** 0 ***
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 20) = 7.1538
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 21) = *** 0 ***
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 22) = *** 0 ***
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 23) = *** 0 ***
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 26) = 9.40356
    * In Archiving_Node(this = 0x5641c062dac0)::get_K_value(t = 28) = 8.50869

Regardless of whether we take the trace value just before or just after the incoming pre spike, the value returned should not be a flat zero.

If I comment out the increment of the history access counter (https://github.com/nest/nest-simulator/blob/0c993abc963c709e7632b9cb5fc701d155d8ab40/nestkernel/archiving_node.cpp#L174), the issue disappears:

    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 2) = 0
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 5) = 0.951229
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 7) = 0.860708
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 8) = 0.818731
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 10) = 2.59689
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 11) = 2.47023
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 15) = 4.69725
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 17) = 5.15509
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 20) = 7.1538
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 21) = 7.75613
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 22) = 8.32909
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 23) = 8.87411
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 26) = 8.49872
    * In Archiving_Node(this = 0x5601aad15340)::get_K_value(t = 28) = 7.68996

I am not yet sure what the best way to address this would look like.

**Comment by heplesser** [comment]
@clinssen Nice catch! We recently changed `get_history()` (in bd82afdd3e86e1e3b40d61f86309e988bb80ab65). Could you check if this effect also occurs for the parent of that change (0edf474)?

Although I assume the true culprit is probably the fact that we require time differences strictly larger than a user-defined eps in

https://github.com/nest/nest-simulator/blame/0c993abc963c709e7632b9cb5fc701d155d8ab40/nestkernel/archiving_node.cpp#L108

I am not certain how to solve this, but when the history is empty, we return `Kminus_`, not zero.

@abigailm Could you comment?

**Comment by clinssen** [comment]
I checked whether the bug was present in the 2.14 (4g) release, and this is indeed the case.

**Comment by clinssen** [comment]
Work-in-progress: https://github.com/nest/nest-simulator/compare/master...clinssen:traces-refactor

I added a cached version of the postsynaptic trace to the Archiving_Node so that the value can be queried by GetStatus(). Although the added code is very lightweight, it would be ideal to wrap this around an "#ifdef DEBUG" or something similar.

![traces](https://user-images.githubusercontent.com/41159823/49177128-bb493000-f34c-11e8-9784-dc9d2f320539.png)

The testbench will assert_almost_equal when comparing the value returned via GetStatus() and a reference value which is computed in the Python testbench script.

**Comment by clinssen** [comment]
Following discussion with @abigailm, I adapted the unit test to include coverage for multiple pre- and post-spikes occurring within one (d_min) timestep. The figure shows the results as they ought to be, i.e., match between Python-computed reference (cyan trace) and NEST values obtained via GetStatus() (orange dots). In NEST, the trace values are sampled at regular intervals, namely, at each simulation (d_min) timestep. However, this actually samples a cached trace value, that was [last updated](https://github.com/clinssen/nest-simulator/blob/2ca0a857a282c8044174977fb94a4d5df4d9e47e/nestkernel/archiving_node.cpp#L130) when the last presynaptic spike arrived. Thus, the orange dots are projected back onto the time that the previous presynaptic spike arrived, yielding the green circles. If all is well, all of the lines connecting the orange and green dots are perfectly horizontal, indicating a correspondence in value. (If a presynaptic spike arrived precisely at a multiple of d_min, the orange and green markers overlap; this is also good.)

Note, however, that these results rely on disabling the access counter increment in Archiving_Node::get_history(), and are therefore not a long-term solution.

![traces_](https://user-images.githubusercontent.com/41159823/51023049-30339a80-1586-11e9-99ba-7c2f24b3a80a.png)

**Comment by suku248** [comment]
@clinssen Instead of not incrementing the access counter, could you try and make the `1` in [this line](https://github.com/nest/nest-simulator/blob/386fb6ed77615a197d6c16fa39c738d10804a484/nestkernel/archiving_node.cpp#L191) a `2` and check whether this also solves the problem?

**Comment by clinssen** [comment]
> @clinssen Instead of not incrementing the access counter, could you try and make the `1` in [this line](https://github.com/nest/nest-simulator/blob/386fb6ed77615a197d6c16fa39c738d10804a484/nestkernel/archiving_node.cpp#L191) a `2` and check whether this also solves the problem?

Thanks for your suggestion. Unfortunately this does not solve the issue. Let's put this on our agenda for tomorrow for further discussion.
