### ISSUE TITLE
Document how to create C++-level unit tests

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1045]
With NEST 2.16.0, we added the framework for C++ unit tests, but this is not documented yet (in `testsuite/README.md` or `testsuite/cpptests/README.md`). 

Add documentation for this possibility!

**Comment by tammoippen** [comment]
As discussed on friday, I think boost unittest is a quite large dependency:

>  The UTF is comparatively complicated component and is implemented in close to hundred header and source files, so for long term usage the preferable solution is to build the UTF as a reusable standalone library. 
https://www.boost.org/doc/libs/1_44_0/libs/test/doc/html/utf/compilation.html

And I want to suggest some different C++ unittest frameworks, I personally used:

- [Catch2](https://github.com/catchorg/Catch2): header only unittesting framework; can be packed with nest (no issues with installed versions / version conflicts); same license as boost.
- [googletest](https://github.com/google/googletest): CMake project - hence can be also packed with nest and compiled by another `subdir` command.

Both are similar powerful to the boost testing.
