### ISSUE TITLE
NEST 2.6.0 crashes when using different synapse parameters with a large number of connections

### ISSUE THREAD

**Issue by jafyvilla** [nest/nest-simulator#105]
When using NEST v2.6.0 - together with Music- to run one of our simulations, on some occasion we get this error, and the simulation crashes:

python: ../nestkernel/scheduler.h:789: static nest::delay nest::Scheduler::get_modulo(nest::delay): Assertion `static_cast::size_type>(d) < moduli_.size()' failed. 

With version 2.4.2 there are no problems.
After digging into the problem, and testing different cases, it seems that it only happens when running simulations with a large number of connections and different parameters for each of them (e.g. delay and weight change from one to another). And even in this case, it's not consistent.
It could be worth to check if it's related to the new rounding strategy introduced in 2.6, because in one of my tests, filtering the synapses with a delay below a certain threshold (i.e. 0.1) seemed to fix the issue.

**Comment by heplesser** [comment]
@jafyvilla Thank you for your bug report. I have some questions that should help me to understand the problem better.

1. You write that the behavior is not consistent. Is it inconsistent between identical simulations (freshly started kernel, identical random number seeds), or is it only inconsistent between simulations with different random number seeds?
1. I assume you set the different delays and weights by randomizing delay and weight values. Is that correct?
1. Does the problem persist if you randomize only the delay values, but not the weights?
1. Roughly, how big is the number of neurons and synapses in the simulations that crash?

**Comment by jafyvilla** [comment]
@heplesser Sorry for taking such a long time to reply, but these past weeks have been a bit hectic. I'll try to give more details about the test setup.

1. From my tests, I would say that the behavior is consistent between identical simulations (see next answer).
2. No, the delays and weights are not random, they are already established for the circuit that we are using, I was just applying them. The values are based on different parameters and experiments, e.g. the delays depend on the axon lengths, etc. In any case, the important part here is that for a determined set of cells, the values don't change from one simulation to another.
3. Manually modifying the delay values seemed to fix the problem, but so far I haven't been able to find a common pattern.
4. Neurons: ~5k; synapses: ~3M

If you need me to test further, changing some other parameters, please let me know. Also, I still didn't try the latest NEST v2.8.0.

Thanks!
Jafet

**Comment by heplesser** [comment]
@jafyvilla Thank you for your update. Unfortunately, I still cannot pinpoint any possible cause of the problem. I would very much appreciate if you could give NEST 2.8.0 a try. If the error persist there, I'll be happy to investigate, but debugging 2.6 at this point makes little sense.

If the problem persists, could you provide me with a script that causes the problem, and an example of edited delays that avoid the problem? Could you also provide me with info on the Music version you are using, and on your OS and compiler? Feel free to send me your script directly by mail.

**Comment by jafyvilla** [comment]
@heplesser I have been trying to debug this issue with version 2.8.0 as well. The error is still there. Unfortunately I cannot provide a script to reproduce it because I have realized that the problem is not consistent, even using a fixed set of parameters (weight and delays) for the connectivities across  different simulations, which makes me think it could be some kind of race condition. For example, using 140 cells and ~5k synapses, it fails around 10% of the times I run it.

When it appears, it's always the same error, when starting to simulate:
python3: ../nestkernel/scheduler.h:784: static nest::delay nest::Scheduler::get_modulo(nest::delay): Assertion `static_cast< vector< delay >::size_type >( d ) < moduli_.size()' failed.

We are using Music 1.0.7, gcc 4.8.3 as compiler, and we saw the problem both in Ubuntu 14.04 and RHEL 6.6. I can send you a file with the parameters I'm using now, so you can give it a try if you want. It might just be a problem in our environment though, as no one else reported anything similar. If that's the case don't worry, we'll find the way to work around it.

Thanks a lot.

**Comment by heplesser** [comment]
@jafyvilla Thanks for testing under 2.8.0! Just one more question: You observe the problem only when using NEST with Music, don't you? This may help us to narrow down the cause. That only you observe the problem is no excuse for us as developers---it might simply be that your use case is exercising parts of the simulator that others don't.

**Comment by jafyvilla** [comment]
I just tested it without the Music component (just the NEST simulation), and the problem persists: it fails some times when starting the simulation. So I guess we can take Music out of the equation...
I just sent you in an email the parameters I am using. Hope that helps.

**Comment by heplesser** [comment]
@jafyvilla I finally got back to this ticket and have been able to confirm and localize the error. If NEST creates a connection with a delay that is not a multiple of the time resolution, then the minimum delay is not set correctly. E.g., simulating with resolution 0.1 and creating a connection with delay 0.82 will result in a connection with delay 0.8, while the minimum delay is 0.9. This causes the crash you observed.

We will fix this with high priority.
