### ISSUE TITLE
"Simple simulation" example on website does not work

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#106]
As reported on NEST_USER, the "simple simulation" example on http://www.nest-simulator.org/neural_simulations/ does not work, because the `interval` property of the `voltmeter` is set after the voltmeter has been connected to a neuron.

We need to reverse the order of operations and explain the need to set the interval first. We also need to check the remainder of the example.

**Comment by jakobj** [comment]
i now changed the order of the commands and cleaned up the example in general a bit. could someone else please add the explanation of this required order of SetStatus & Connect? i was wondering about the part about subnets. is someone using them? do we want to keep them as a feature and if not, could we remove that part from the example?

**Comment by jougs** [comment]
As already often discussed, subnets will go away at one point (at least in their current form). This means they should not be advertised prominently in the documentation. Could you please remove them from the documentation? Many thanks for spotting and fixing!

**Comment by jakobj** [comment]
alright. the subnet part is now removed from that page.

**Comment by jakobj** [comment]
i think this issue can be closed!

**Comment by heplesser** [comment]
I just updated the page so that the output actually looks like nest-2.8.0 output (GID shown by default, integer values shown without trailing .0) and changed the input current a little so that one actually sees the return from refactoriness. Updated the explanation a bit as well.

With that, I am happy, but I think someone else should proofread before closing.

**Comment by jougs** [comment]
I've read the page and generally find it nice. I'm thus closing this issue.
