### ISSUE TITLE
improve documentation of pynest get_verbosity() and set_verbosity() docstrings

### ISSUE THREAD

**Issue by jessica-mitchell** [nest/nest-simulator#1061]
In python, the return value for _get_verbosity()_ is an integer, which itself isn't very self-explanatory
And the docstring isn't much help either:
```
 Return verbosity level of NEST's messages.
    
    Returns
    -------
    int:
        The current verbosity level
```
 The confusion is also compounded by the fact that _set_verbosity()_ asks for a string, and neither docstring for _set_ or _get_ provides a correlation between the integer and string
```
set_verbosity(level)
    Change verbosity level for NEST's messages.
    
    Parameters
    ----------
    level : str
        Can be one of 'M_FATAL', 'M_ERROR', 'M_WARNING', 'M_DEPRECATED',
        'M_INFO' or 'M_ALL'.
```
I presume that the integer and string have a 1 to 1 correlation with that of the SLI version (with a few choices omitted):
 
```
setverbosity - Set verbosity level for message 
M_ALL=0,  display all messages 
M_DEBUG=5,  display debugging messages and above 
M_STATUS=7,  display status messages and above 
M_INFO=10, display information messages and above 
M_DEPRECATED=18, display deprecation warnings and above 
M_WARNING=20, display warning messages and above 
M_ERROR=30, display error messages and above 
M_FATAL=40, display failure messages and above 
M_QUIET=100, suppress all messages 
```

I would propose including the matching integer-string info in both docstrings.

**Comment by heplesser** [comment]
@jessica-mitchell Good idea, could you provide a PR?
