### ISSUE TITLE
Problem with NEST 2.16.0 installation

### ISSUE THREAD

**Issue by Vaurien96** [nest/nest-simulator#1066]
Hi! I'm encountering difficulties to install NEST:

I installed the required packages then used this command `cmake -DCMAKE_INSTALL_PREFIX:PATH=</install/path> -Dwith-python=2 
 </path/to/nest/source>`

and `make`. At the end of `make` I get this error:

[ 99%] Compiling Cython CXX source for pynestkernel...

Error compiling Cython file:
------------------------------------------------------------
...

    return arr

cdef inline object sli_vector_to_object(sli_vector_ptr_t dat, vector_value_t _ = 0):

    cdef vector_value_t* array_data = NULL
   ^
------------------------------------------------------------

/home/ubuntu/Téléchargements/nest-simulator-2.16.0/pynest/pynestkernel.pyx:475:4: Compiler crash in RemoveUnreachableCode

ModuleNode.body = StatListNode(pynestkernel.pyx:25:0)
StatListNode.stats[41] = StatListNode(pynestkernel.pyx:473:5)
StatListNode.stats[0] = FusedCFuncDefNode(pynestkernel.pyx:473:5,
    fused_compound_types = [...]/2,
    match = "dest_sig[{{dest_sig_idx}}] = '{{specialized_type_name}}'",
    no_match = 'dest_sig[{{dest_sig_idx}}] = None',
    nodes = [...]/4)
FusedCFuncDefNode.stats[1] = CFuncDefNode(pynestkernel.pyx:473:5,
    args = [...]/2,
    modifiers = [...]/1,
    visibility = u'private')
CFuncDefNode.body = StatListNode(pynestkernel.pyx:475:4,
    is_terminator = True)

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
    return handler_method(obj)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/ParseTreeTransforms.py", line 2494, in visit_StatListNode
    warning(node.stats[idx].pos, "Unreachable code", 2)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Errors.py", line 206, in warning
    line = "warning: %s\n" % warn
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 14: ordinal not in range(128)
pynest/CMakeFiles/pynestkernel.dir/build.make:62 : la recette pour la cible « pynest/pynestkernel.cxx » a échouée
make[2]: *** [pynest/pynestkernel.cxx] Erreur 1
make[2]: *** Suppression du fichier « pynest/pynestkernel.cxx »
CMakeFiles/Makefile2:1152 : la recette pour la cible « pynest/CMakeFiles/pynestkernel.dir/all » a échouée
make[1]: *** [pynest/CMakeFiles/pynestkernel.dir/all] Erreur 2
Makefile:160 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

____________________________________________

I have seen some issues with UnicodeDecodeErrors but none with encoding errors...

**Comment by hakonsbm** [comment]
Looks like "Téléchargements" (specifically the "é"s) in your path causes some issues with Cython, or rather, with Python2. The simplest solution is to use another directory with a path without any non-ascii characters. Alternatively you can try to use Python3, which has better Unicode support.

**Comment by Vaurien96** [comment]
> Looks like "Téléchargements" (specifically the "é"s) in your path causes some issues with Cython, or rather, with Python2. The simplest solution is to use another directory with a path without any non-ascii characters. Alternatively you can try to use Python3, which has better Unicode support.

Thanks, it worked!
