### ISSUE TITLE
Duplicate include of libnestutil.a if 'nest' is linked statically

### ISSUE THREAD

**Issue by gtrensch** [nest/nest-simulator#1072]
If NEST ist statically build, CMake generates a duplicate include for libnestutil.a.
(.../CMakeFiles/nest.dir/link.txt)

**Comment by gtrensch** [comment]
I've looked into this a little more closely. It also applies to other libraries.  The reason is how CMake `target_link_libraries` work. It obviously includes the libraries from `target_link_libraries` CMake functions in the hierarchy. For example:

For the `nest` module `nestutil.a` and `nestkernel.a` is needed:

> /nest/CMakeLists.txt
> target_link_libraries( **nest**
>     **nestutil nestkernel** random sli_lib sli_readline
>     ${SLI_MODULES} ${EXTERNAL_MODULE_LIBRARIES} OpenMP::OpenMP_CXX )
> 
`nestkernel` itself also requires `nestutil.a`.

> /nestkernel/CMakeLists.txt
> target_link_libraries( **nestkernel**
>     **nestutil** random sli_lib
>     ${LTDL_LIBRARIES} ${MPI_CXX_LIBRARIES} ${MUSIC_LIBRARIES} ${SIONLIB_LIBRARIES} )
> 

It would be possible to avoid this by rewriting the CMake statements. But this would hide what happens with dynamic and static linking. Technically, they are linked once, although duplicates are specified in the linker options. As this does not cause any technical problems, I suggest to leave it as it is and close this issue.

**Comment by terhorstd** [comment]
Discussed in [Open Dev VC](https://github.com/nest/nest-simulator/wiki/2020-07-06-Open-NEST-Developer-Video-Conference/) and decided to close.
