### ISSUE TITLE
PyNEST test failed

### ISSUE THREAD

**Issue by piewchee** [nest/nest-simulator#1075]
Hi
My apology for creating a new issue for this as i m not sure if issue #866 which has been closed will be noticed.

I am facing similar error with "no module named nest" 
however the error is slightly different.
nest: 2.16.0
OS: Ubuntu 16.04
python version: 2.7.12 
cmake version: 3.5.1
cython: 0.29

in virtualenv:venv
After 
After running make installcheck
PyNEST test failed =2
Please see attached reports/

Rgds
Del
[reports.tar.gz](https://github.com/nest/nest-simulator/files/2588218/reports.tar.gz)
[nest.X15UE.tar.gz](https://github.com/nest/nest-simulator/files/2588220/nest.X15UE.tar.gz)

**Comment by stinebuu** [comment]
Hi @piewchee, are you still having this problem?

**Comment by piewchee** [comment]
I think it has been resolved. 
Forgot how I resolved it.

Rgds
