### ISSUE TITLE
Create up-to-date and complete Bioconda recipe for NEST

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1077]
Bioconda provides recipes for NEST at

https://bioconda.github.io/recipes/nest/README.html

for easy installation via Conda. Currently, the recipes only cover 2.12 and 2.14, and support Linux only (see also #1041). We should create recipes for newer versions, possibly one for github master, and support for OSX.

**Comment by steffengraber** [comment]
Hi @heplesser  I think master builds are not allowed for bioconda:
„While supported by conda, git_url and git_rev are not as stable as a git tarball. Ideally a github repo should have tagged releases that are accessible as tarballs from the “releases” section of the github repo.“
https://bioconda.github.io/guidelines.html
What do you think?

In general this is not a problem. But how and where should we store such a master recipe?   
Do you have an conda environmenl for OSX and NEST?

**Comment by steffengraber** [comment]
The topic belongs to #210

**Comment by heplesser** [comment]
We decided 9 April to not support a recipe in Bioconda, instead focusing on conda-forge. Thus closing.

**Comment by bgruening** [comment]
Bioconda had the advantage to build automatic and minimal containers (https://quay.io/repository/biocontainers/nest?tab=tags). Please ping me if you want to have those containers for conda-forge as well.

Thanks!
