### ISSUE TITLE
FindLibNeurosim must be updated to take py2/py3 into account

### ISSUE THREAD

**Issue by sanjayankur31** [nest/nest-simulator#1080]
Now that libneurosim provides:

- libpy2neurosim and libneurosim for py2
- libpy3neurosim for py3

the FindLibNeurosim.cmake file would need to be modified to take the python version into account. If we're building with py2, it should look for the first ones, otherwise the second one.

**Comment by jougs** [comment]
@sanjayankur31: would you be able to provide a PR fixing this? Thanks!

**Comment by sanjayankur31** [comment]
Sure, please assign it to me. It'll take me 2--3 weeks to get this done with my current task-load, though. I hope that's OK.

**Comment by jougs** [comment]
It would take me even much longer atm ;-) Thanks for your support!
