### ISSUE TITLE
Errors detected during the run of the NEST test suite

### ISSUE THREAD

**Issue by ricardomurphy** [nest/nest-simulator#1083]
[reports.zip](https://github.com/nest/nest-simulator/files/2628146/reports.zip)
Hello,
I am trying to install NEST on the Abel cluster at the University of Oslo. Things seemed to be going more-or-less OK but I received this message at the end (error report attached):

NEST Testsuite Summary
----------------------
  NEST Executable: /usit/abel/u1/ricardom/nest-2.16.0/bin/nest
  SLI Executable : /usit/abel/u1/ricardom/nest-2.16.0/bin/sli
  Total number of tests: 296
     Passed: 287
     Skipped: 1 (0 PyNEST)
     Failed: 8 (2 PyNEST)

***
*** There were errors detected during the run of the NEST test suite!
***
*** Please report the problem at
***     https://github.com/nest/nest-simulator/issues
***
*** To help us diagnose the problem, please attach the archived conten
*** of these directories to the issue:
***     - '/usit/abel/u1/ricardom/nest-simulator-2.16.0/build/reports'
***     - '/usit/abel/u1/ricardom/nest-simulator-2.16.0/build/reports/
***

make[3]: *** [CMakeFiles/installcheck] Error 1
make[2]: *** [CMakeFiles/installcheck.dir/all] Error 2
make[1]: *** [CMakeFiles/installcheck.dir/rule] Error 2
make: *** [installcheck] Error 2

**Comment by ricardomurphy** [comment]
Hello Hans Ekkehard.
Thanks for your response. Yes I'm using an Intel compiler so I'll try
again with -Dwith-optimize="-O3 -fp-model strict". Actually I already
have -Dwith-python=3, here's my script:
module purge
module load python3/3.5.0
module load gsl/2.2
module load intel/2018.1
module load libtool/2.4.6-foss-2016b
module load cmake/3.7.1
module list
cmake -DCMAKE_INSTALL_PREFIX=$HOME/nest-2.16.0 \
-Dwith-readline=OFF \
-Dwith-python=3 \
..
make -j
make install
make installcheck

So I don't know why python 2 was being used. I'll try again.
Best,
Ricardo
___________________________________

Dr. Ricardo Murphy,
University of Oslo,
Department of Molecular Medicine,
Physiology Section,
Pb. 1103, Blindern,
0317 Oslo

Tel:   95333157
Fax: 22851249
Email: ricardo.murphy@medisin.uio.no


On Thu, Nov 29, 2018, at 09:23, Hans Ekkehard Plesser wrote:
> Hi Ricardo!


> The failing SLI tests are both tests checking numerical accuracy.
> Which compiler are you using to build NEST? If you use an Intel
> compiler, you need to add -Dwith-optimize="-O3 -fp-model strict"(-O2
> is also fine) in order to ensure that the compiler creates code
> consistent with IEEE754 floating point rules.> The failing python tests seem to point to a problem with setup/paths:


> Traceback (most recent call last): File "/cluster/software/VERSIONS/python_packages-
> 3.5_1/cluster/software/VERSIONS/python3-3.5.0/lib/python3.5/site-
> packages/nose/failure.py", line 42, in runTest raise
> self.exc_class(self.exc_val) OSError: No such file /cluster/home/ricardom/nest-2.16.0/lib64/python2.6/site-
> packages/nest/tests
>> Note the mix of Python 3 and 2. It seems NEST is built with Python
> 2.6. Could you try building with -Dwith-python=3?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/nest/nest-simulator/issues/1083#issuecomment-442746107

**Comment by ricardomurphy** [comment]
Hello again Hans.
NEST seems to be working on Abel. Just to let you know, I tried 
the "-O3-fp-model strict" but I got lots of messages about 
an unrecognised option (or words to that effect; also with "-O2".
So I tried omitting the "-O#", i.e.:

module purge
module load python3/3.5.0
module load gsl/2.2
module load intel/2018.1
module load libtool/2.4.6-foss-2016b
module load cmake/3.7.1
module list
cmake -DCMAKE_INSTALL_PREFIX=$HOME/nest-2.16.0 \
-Dwith-optimize="-fp-model strict" \
-Dwith-readline=OFF \
-Dwith-python=3 \
 ..
make -j
make install
make installcheck

And that produced a much better result:

NEST Testsuite Summary
----------------------
  NEST Executable: /usit/abel/u1/ricardom/nest-2.16.0/bin/nest
  SLI Executable : /usit/abel/u1/ricardom/nest-2.16.0/bin/sli
  Total number of tests: 831
     Passed: 819
     Skipped: 12 (11 PyNEST)
     Failed: 0 (0 PyNEST)

Built target installcheck

although as you can see some tests were skipped (report 
attached, just in case). 

When I tried to import NEST I got a message about a missing file, 
but I eventually figured out that I need to load libtool if I 
want to use NEST. I've now run a simulation (just a single cell 
for the moment) and got identical results to those obtained with 
our hp workstation. Thanks for your help.
Best,
Ricardo


[reports-2.zip](https://github.com/nest/nest-simulator/files/2633482/reports-2.zip)

**Comment by ricardomurphy** [comment]
Sorry Hans! I just realized that I (probably) omitted the space between -O3 and -fp. So to be on the safe side perhaps I'd better compile again.
Ricardo

**Comment by ricardomurphy** [comment]
Hellolo again.
The -Dwith-optimize="-O3 -fp-model strict" option (with the space!)
worked fine and I was again able to reproduce our earlier single-cell
results (yet to try a network).Thanks a lot.
Ricardo

___________________________________

Dr. Ricardo Murphy,
University of Oslo,
Department of Molecular Medicine,
Physiology Section,
Pb. 1103, Blindern,
0317 Oslo

Tel:   95333157
Fax: 22851249
Email: ricardo.murphy@medisin.uio.no


On Thu, Nov 29, 2018, at 09:54, Ricardo Murphy wrote:
> Hello Hans Ekkehard.
> Thanks for your response. Yes I'm using an Intel compiler so I'll try
> again with -Dwith-optimize="-O3 -fp-model strict". Actually I already
> have -Dwith-python=3, here's my script:> 
> module purge
> module load python3/3.5.0
> module load gsl/2.2
> module load intel/2018.1
> module load libtool/2.4.6-foss-2016b
> module load cmake/3.7.1
> module list
> cmake -DCMAKE_INSTALL_PREFIX=$HOME/nest-2.16.0 \
> -Dwith-readline=OFF \
> -Dwith-python=3 \
> ..
> make -j
> make install
> make installcheck
> 
> So I don't know why python 2 was being used. I'll try again.
> Best,
> Ricardo
> ___________________________________
> 
> Dr. Ricardo Murphy,
> University of Oslo,
> Department of Molecular Medicine,
> Physiology Section,
> Pb. 1103, Blindern,
> 0317 Oslo
> 
> Tel:   95333157
> Fax: 22851249
> Email: ricardo.murphy@medisin.uio.no
> 
> 
> On Thu, Nov 29, 2018, at 09:23, Hans Ekkehard Plesser wrote:
>> Hi Ricardo!


>> The failing SLI tests are both tests checking numerical accuracy.
>> Which compiler are you using to build NEST? If you use an Intel
>> compiler, you need to add -Dwith-optimize="-O3 -fp-model strict"(-O2
>> is also fine) in order to ensure that the compiler creates code
>> consistent with IEEE754 floating point rules.>> The failing python tests seem to point to a problem with setup/paths:


>> Traceback (most recent call last): File "/cluster/software/VERSIONS/python_packages-
>> 3.5_1/cluster/software/VERSIONS/python3-3.5.0/lib/python3.5/site-
>> packages/nose/failure.py", line 42, in runTest raise
>> self.exc_class(self.exc_val) OSError: No such file /cluster/home/ricardom/nest-2.16.0/lib64/python2.6/site-
>> packages/nest/tests
>>>> Note the mix of Python 3 and 2. It seems NEST is built with Python
>> 2.6. Could you try building with -Dwith-python=3?>> — You are receiving this because you authored the thread. Reply to
>> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/nest/nest-simulator/issues/1083#issuecomment-442746107

**Comment by heplesser** [comment]
@ricardomurphy As all seems fine, I will close this one.
