### ISSUE TITLE
Distributed inhibitory weights

### ISSUE THREAD

**Issue by AlexVanMeegen** [nest/nest-simulator#1090]
Dear all,

this is a follow up on existing but closed issues (#459 and #835): To the best of my knowledge, it is not possible to have inhibitory weights distributed according to a distribution with positive support (e.g. lognormal or exponential).

As a quick hack, I used the `sigma` parameter of the lognormal distribution to enable lognormally distributed inhibitory weights (similar to #835). I could prepare a PR, but honestly it is a quite awkward solution.

Cheers,
Alex

PS: #459 led me here: https://github.com/compneuronmbu/nest-simulator/issues/4

**Comment by heplesser** [comment]
This will be addressed in a general way in NEST 3.
