### ISSUE TITLE
Strange performances of nest.GetConnections()  

### ISSUE THREAD

**Issue by alberto-antonietti** [nest/nest-simulator#1096]
_Originally posted by @alberto-antonietti in https://github.com/nest/nest-simulator/pull/920#issuecomment-409323965_

Follow-up of my comment on #920

**Comment by alberto-antonietti** [comment]
I have explored more systematically the performances of `GetConnections`, comparing NEST 2.14.0 and the current `master` (version `ad5ef5c`).

I have done three different tests, with the following code:

```
import nest
import time

def tic():
    global startTime_for_tictoc
    startTime_for_tictoc = time.time()

def toc():
    if 'startTime_for_tictoc' in globals():
        tempo = float(time.time()) - float(startTime_for_tictoc)
        print ("Elapsed time is %.3f seconds" % tempo)
    else:
        print "Toc: start time not set"


A=nest.Create('iaf_cond_exp',PRE)
B=nest.Create('iaf_cond_exp',POST)

nest.Connect(A,B,'all_to_all','static_synapse')

tic()
C = nest.GetConnections(A,B)
toc()
```
in three conditions:
1) PRE = 5k, POST = 5k, Total synapses: 25 M
2) PRE = 50, POST = 50k, Total synapses: 2.5 M
3) PRE = 50k, POST = 50,  Total synapses: 2.5 M

on an HPC node with 36 cores.

These are the results obtained

1)
| CONNECTIONS                 | #Threads | Time (s) | Time (s) | Ratio |
|-----------------------------|----------|----------|----------|-------|
|               25.000.000    |          | ad5ef5c  | 2.14.0   |       |
| 5000->5000                  | 32       | 21       | 12       | 1,75  |
| 5000->5000                  | 16       | 41       | 10       | 4,10  |
| 5000->5000                  | 8        | 81       | 26       | 3,12  |
| 5000->5000                  | 4        | 226      | 57       | 3,96  |
| 5000->5000                  | 2        | 319      | 163      | 1,96  |
| 5000->5000                  | 1        | 600+     | 415      | -     |

2)

| CONNECTIONS                   | #Threads | Time (s) | Time (s) | Ratio |
|-------------------------------|----------|----------|----------|-------|
|                  2.500.000    |          | ad5ef5c  | 2.14.0   |       |
| 50->50000                     | 32       | 25       | 18       | 1,39  |
| 50->50000                     | 16       | 39       | 23       | 1,70  |
| 50->50000                     | 8        | 81       | 53       | 1,53  |
| 50->50000                     | 4        | 155      | 102      | 1,52  |
| 50->50000                     | 2        | 298      | 198      | 1,51  |
| 50->50000                     | 1        | 590      | 461      | 1,28  |

3)
| CONNECTIONS                   | #Threads | Time (s) | Time (s) | Ratio |
|-------------------------------|----------|----------|----------|-------|
|                  2.500.000   |          | ad5ef5c  | 2.14.0   |       |
| 50000->50                    | 32       | 6        | 0,3      | 20,00 |
| 50000->50                    | 16       | 21       | 0,25     | 84,00 |
| 50000->50                    | 8        | 1,1      | 0,4      | 2,75  |
| 50000->50                    | 4        | 5,5      | 0,6      | 9,17  |
| 50000->50                    | 2        | 3,3      | 1        | 3,30  |
| 50000->50                    | 1        | 3,3      | 1,9      | 1,74  |

## Considerations
In case 1) and 2), the performances of `GetConnections` have been decreased by the `5g` kernel, in case 2) independently from the number of threads used, in case 3) without a precise dependence from the number of threads, but with higher values (the `5g` kernel was 2-4 times slower than NEST 2.14.0). The performance decrease problem has been already seen and mitigated by @hakonsbm in https://github.com/jakobj/nest-simulator/pull/104#issue-194815934. In my case, the impact of the performance loss seems more important.

In case 3) the times with `2.14` generally decreases with an increase of the number of threads, while with `5g`  the behavior seems not predictable. For this reason, I have done additional tests only for case 3)

| CONNECTIONS        | #Threads | Time (s) | Time (s) | Ratio |
|--------------------|----------|----------|----------|-------|
|  Additional tests  |          | ad5ef5c  | 2.14.0   |       |
| 50000->50          | 25       | 17       | 0,8      | 21,25 |
| 50000->50          | 17       | 6        | 0,25     | 24,00 |
| 50000->50          | 15       | 20       | 0,26     | 76,92 |
| 50000->50          | 14       | 10,6     | 0,25     | 42,40 |
| 50000->50          | 13       | 8,9      | 0,33     | 26,97 |
| 50000->50          | 12       | 8,9      | 0,31     | 28,71 |
| 50000->50          | 11       | 11       | 0,37     | 29,73 |
| 50000->50          | 10       | 0,5      | 0,34     | 1,47  |
| 50000->50          | 9        | 1,3      | 0,37     | 3,51  |
| 50000->50          | 7        | 0,9      | 0,4      | 2,25  |
| 50000->50          | 6        | 1        | 0,5      | 2,00  |
| 50000->50          | 5        | 0,9      | 0,55     | 1,64  |
| 50000->50          | 3        | 1,7      | 0,8      | 2,13  |

Again, these results seem quite strange to me (I have done multiple tests, but the times were more or less the same). I can understand the better results with 5 or 10 threads, because the 50 post-synaptic nodes should be homogeneously distributed on the different threads, but that is not the case with 25 threads.

Are those results reproducible on your machines?
Should I change my scripts to limit the use of `GetConnections() `as much as possible?

**Comment by alberto-antonietti** [comment]
I just tried to repeat some of those tests with `nest-3@c7ca105` (https://github.com/compneuronmbu/nest-simulator/tree/nest-3) and the times needed increased again  (roughly doubled the ones with `ad5ef5c`). Maybe this could be useful for developers workin on NEST-3.

**Comment by hakonsbm** [comment]
@alberto-antonietti Thank you for the benchmarks! I have created a PR (#1099) which should fix the performance issue.

**Comment by alberto-antonietti** [comment]
Thank everyone for the PR.
Just as a follow-up, these are the performances after the merging of the PR.
There is a considerable improvement for condition 1 (except using 4 threads) and condition 2.

Condition 1) PRE = 5k, POST = 5k, Total synapses: 25 M
Condition 2) PRE = 50, POST = 50k, Total synapses: 2.5 M
Condition 3) PRE = 50k, POST = 50, Total synapses: 2.5 M

1)
| CONNECTIONS                 | #Threads | Time      | Time    | Time   |
|-----------------------------|----------|-----------|---------|--------|
|               25.000.000    |          | **57b254c** | ad5ef5c | 2.14.0 |
| 5000->5000                  | 32       | **2**         | 21      | 12     |
| 5000->5000                  | 16       | **4**         | 41      | 10     |
| 5000->5000                  | 8        | **7**         | 81      | 26     |
| 5000->5000                  | 4        | **80**        | 226     | 57     |
| 5000->5000                  | 2        | **34**        | 319     | 163    |
| 5000->5000                  | 1        | **44**        | 600+    | 415    |

2)
| CONNECTIONS                   | #Threads | Time      | Time    | Time   |
|-------------------------------|----------|-----------|---------|--------|
|                  2.500.000    |          |**57b254c** | ad5ef5c | 2.14.0 |
| 50->50000                     | 32       | **1**         | 25      | 18     |
| 50->50000                     | 16       | **2**         | 39      | 23     |
| 50->50000                     | 8        | **3**         | 81      | 53     |
| 50->50000                     | 4        | **7**         | 155     | 102    |
| 50->50000                     | 2        | **13**        | 298     | 198    |
| 50->50000                     | 1        | **24**        | 590     | 461    |


3)
| CONNECTIONS                   | #Threads | Time      | Time    | Time   |
|-------------------------------|----------|-----------|---------|--------|
|                  2.500.000    |          | **57b254c** | ad5ef5c | 2.14.0 |
| 50000->50                     | 32       | **5**         | 6       | 0,3    |
| 50000->50                     | 16       | **21**        | 21      | 0,25   |
| 50000->50                     | 8        | **1,1**       | 1,1     | 0,4    |
| 50000->50                     | 4        | **5,2**       | 5,5     | 0,6    |
| 50000->50                     | 2        | **3**         | 3,3     | 1      |
| 50000->50                     | 1        | **2,8**       | 3,3     | 1,9    |
