### ISSUE TITLE
upgrade licence to GPL v3

### ISSUE THREAD

**Issue by albada** [nest/nest-simulator#1106]
For the Potjans & Diesmann model in OpenSourceBrain, Padraig Gleeson suggested bringing the different versions (PyNN, NEST) under a common licence, namely GPL v3. This would thus require NEST to be under GPL v3. For information about this new version of the licence, see: https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by heplesser** [comment]
NEST is under GPL v2 *or later*, where the "or later" decision is a the discretion of the user. So if you would like to use NEST under GPL v3, your are most welcome to do so.

**Comment by albada** [comment]
Okay!
