### ISSUE TITLE
pass kwargs to plotting function in raster_plot.py

### ISSUE THREAD

**Issue by A13k2** [nest/nest-simulator#1110]
I was trying to find a solution for outputting smaller pdf files for raster_plot and rasterized=True does so, but it didn't get passed to the actual plot function.
Passing args to pylab.plot(...) in _make_plot does the trick for me.
Hope this helps :)

**Comment by heplesser** [comment]
Closing this issue as it is not directly related to NEST. Other users will still be able to find the solution suggested among the closed issues.
