### ISSUE TITLE
Remove pylab from pynest

### ISSUE THREAD

**Issue by EricThomson** [nest/nest-simulator#1124]
I'm curiouis how people would feel about removing `pylab` from the docs/examples. It's a bit of a namespace wrecker, and teaches new programmers bad habits (under the hood, it includes `from numpy import *` and `from matplotlib import *`). It is officially deprecated and discouraged by the Matplotlib developers. For instance, in the [matplotlib usage guide](https://matplotlib.org/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py):

>  pylab is deprecated and its use is strongly discouraged because of namespace pollution. Use pyplot instead.

How do people feel about starting to replace `import pylab` with more Pythonic, explicit references to `numpy` and `matplotlib`? It is a pretty easy fix. I'm working through the tutorials/examples and replacing pylab every time it comes up. I'd be happy to help with this cleansing if people support it.

**Comment by ikitayama** [comment]
👍

**Comment by jessica-mitchell** [comment]
Thank you for bringing this to our attention. We would happily accept a pull request implementing these changes!  Do you want to work on this?

**Comment by EricThomson** [comment]
Sure: I will reference this issue when I make the pull request(s).

**Comment by heplesser** [comment]
@EricThomson I am a bit surprised you closed this issue already. Usually, we keep issues open until the pull request solving the issue has been merged. I reopen, feel free to close again if I got it wrong.

**Comment by EricThomson** [comment]
helplesser sorry I am sort of new to how to do this kind of thing. :)

**Comment by jougs** [comment]
@EricThomson: Can you please tell us about the status of your PR? Thanks!

**Comment by Silmathoron** [comment]
Could we at the same time remove all calls to

    import matplotlib.pyplot as plt

and move them into plotting functions?
Otherwise it forces users who need to change the default matplotlib backend to do it before calling NEST and they may no no, neither understand that...
I can do both it if we agree that it's a good idea, since the previous PR seems closed anyway.

**Comment by jougs** [comment]
I think this is a good idea. Could you please create a PR? Many thanks!
