### ISSUE TITLE
'regressiontests/ticket-659-copyright.py'... Failed: error in test script

### ISSUE THREAD

**Issue by hanke** [nest/nest-simulator#113]
Observed when running the test of the current master HEAD.

**Comment by jougs** [comment]
Thanks for reporting. Could you please attach `reports/installcheck.log`, so we can see what file actually failed? Thanks!

**Comment by hanke** [comment]
Thanks for the pointer. Non-issue. I wrongly assumed that it would assume me to run the tests from the root of the source dir. Needs an explicit specification and work ... Closing.
