### ISSUE TITLE
Replace pep8 by pycodestyle in static code analysis

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1132]
The `pep8` tool has been renamed to `pycodestyle`:
```
pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.
```
We should update our static code analysis scripts.

**Comment by heplesser** [comment]
Instead of using pycodestyle directly, we might want to use flake8, which is a wrapper with more flexibility.

**Comment by clinssen** [comment]
Not necessarily opposed, but this is feature creep, and raises additional questions like which things do we want to check for. flake8 for example also checks "cyclometric code complexity". pep8→pycodestyle is just a rename, whereas pep8→flake8 is a feature change.

**Comment by heplesser** [comment]
@clinssen You are right, we should keep it simple, so let's move to pycodestyle.
