### ISSUE TITLE
NEST version information is inconsistent

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1134]
External tools (e.g. NESTML) should be able to query the version number of the current NEST build/install on a machine. Currently, the returned version numbers are inconsistent.

E.g. when running on my local branch, which was forked from master a few weeks ago:

    $ ~/nest-simulator-build/bin/nest

                  -- N E S T --
      Copyright (C) 2004 The NEST Initiative

     Version: traces-refactor@abea27a5
     Built: Feb  4 2019 13:02:18

The version (hash) and local branch name are correctly identified.

But when running nest-config:

    $ ~/nest-simulator-build/bin/nest-config --version
    2.16.0

And when running PyNEST:

    $ ipython3
    In [1]: import nest

                  -- N E S T --
      Copyright (C) 2004 The NEST Initiative

     Version: traces-refactor@abea27a5
     Built: Feb  4 2019 13:02:18

    In [2]: nest.version()                                                                                                                 
    Out[2]: 'NEST 2.16.0'

It looks like the first of these can be fixed by inserting the proper references to `rcsinfo.sli` in `pynest/nest/lib/hl_api_info.py`; for the second I'm not sure what the best course of action would be (the `NEST_VERSION_VERSION` variable from `CMakeLists.txt` is used there).

Also note some potentially dangerous redundancy between `nest-simulator/extras/create_rcsinfo.sh`:

    version="v2.16.0"

and the definitions in `nest-simulator/CMakeLists.txt`:

    # VERSION exported to libnestutil/config.h, pynest/setup.py
    set( NEST_VERSION_MAJOR 2 )
    set( NEST_VERSION_MINOR 16 )
    set( NEST_VERSION_PATCHLEVEL 0 )

**Comment by terhorstd** [comment]
This should also go into 2.18.
