### ISSUE TITLE
Inconsistent naming of protected variables/functions (with or without trailing underscore)

### ISSUE THREAD

**Issue by janhahne** [nest/nest-simulator#1136]
From the [NEST coding guidelines](https://nest.github.io/nest-simulator/coding_guidelines_c++#variables-and-class-members) it is not clear if `protected` functions and members should have a trailing underscore. So far the handling of protected variables/functions seems to be inconsistent, see e.g., https://github.com/nest/nest-simulator/blob/master/nestkernel/archiving_node.h#L181 and https://github.com/nest/nest-simulator/blob/master/nestkernel/conn_builder.h#L129.

**Comment by heplesser** [comment]
@janhahne Thank you for pointing this out! I think all methods that are not part of the public interface of a class should carry the `_` in their name to indicate that they are an implementation detail.

**Comment by terhorstd** [comment]
This is a symptom of #1173 and should probably be addressed there. Basically, refactoring to not need protected. If this still remains, please open a new issue to fix the coding guidelines first.
