### ISSUE TITLE
`run_examples.sh` can not find examples

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#1138]
This is just a smaller issue.

If you want to run `run_examples.sh` in an installation of NEST in `NEST_INSTALL_DIR/share/doc/nest/` it fails, because it can not find `../examples`.

You might be able to change this by adjusting `NEST_SOURCE/examples/CMakeLists.txt` in line 20, or changing `run_examples.sh` in line 50 - the latter would cause other problems again.

**Comment by stinebuu** [comment]
Is this fixed with #1117 ?

**Comment by steffengraber** [comment]
@stinebuu No, unfortunately not. I left my comment at #1117.

**Comment by gtrensch** [comment]
I have corrected this in PR #1117 and waiting for review.

**Comment by steffengraber** [comment]
Just tried and it works with #1117! I Think it is ok to close this issue.
