### ISSUE TITLE
Restore PyNEST functions to the top level module

### ISSUE THREAD

**Issue by hakonsbm** [nest/nest-simulator#1141]
With the restructuring of PyNEST in #1058, some low-level functions are no longer available from the top level `nest` module, but hidden in either `hl_api` or `ll_api`, which is great.

However, there are some functions that are not in the top level which could belong there:
- `PrintNetwork`
- `message`
- `set_verbosity`
- `get_verbosity`

Most of these functions are used in examples, so if we decide to not make these functions accessible from the top level `nest` module all examples using them have to be changed.

**Comment by babsey** [comment]
Thank you for this assignment. I will take care of the issue. 

Before I work on I would like to know your thoughts of Hakon's concerning.
