### ISSUE TITLE
Support current versions of clang-format

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#1152]
nest requires clang-format in the exact version 3.6. the current release version in 7. the configuration file should be updated to work with the more recent versions to make life easier for people who are not stuck with, e.g., ubuntu 16.04 lts (https://www.howtoinstall.co/en/ubuntu/xenial/clang-format-3.6).

**Comment by terhorstd** [comment]
This seems to be an intended upstream design decision: https://lists.llvm.org/pipermail/cfe-dev/2017-June/054351.html.
Seems like the only option is to fix the required version...

**Comment by heplesser** [comment]
Closing, since there is no general solution for this due to the nature of clang-format, as pointed out [above](https://github.com/nest/nest-simulator/issues/1152#issuecomment-481333599).

**Comment by Silmathoron** [comment]
@heplesser shouldn't we at least update it to the latest version so that people don't have to download and install a super old llvm and clang but just use one that is directly available on most systems (between 3.9 and 7)?
As somebody who just had to wait for everything to compile, I must say this is quite annoying...

**Comment by Silmathoron** [comment]
We don't have to change the file, just decide that starting 2.18+ we use it with cland-format-X (X>=3.9)

**Comment by heplesser** [comment]
@Silmathoron Version 6 seems sensible, since it is the default on a number of current Ubuntu versions. But we will always be tied to a specific version, since part of the formatting is hard-wired in clang-format. A PR would be welcome, but other issues seem more important.

**Comment by Silmathoron** [comment]
@heplesser it's just that using a version which is not available anywhere anymore is a bit annoying... at least version 6 would let us breathe for a few additional months or years.
The pull request is pretty straightforward: just change a number in the file and run it, but it would mean that all other PRs should be updated accordingly.
