### ISSUE TITLE
Configuring NEST with the XL option -static doesn't work on JURON  

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#1156]
@gtrensch at al.,
As only dynamically linked applications are supported on JURON, simply passing -static onto XL compiler does build a non-runnable binary (-Dstatic-libraries=ON).

In my quick glance at cmake/ProcessOptions, when it gets executed JURON specific variables are not visible yet, so I'm not sure how we should tell the build system to use -qstaticlink=xllibs instead.

For now, I'm editing the file above directly, but it is better to be addressed in a proper way.

**Comment by heplesser** [comment]
@ikitayama Have you tried to modify the relevant `cmake/Platform/JURON_*` files to make sure the correct flags are used?

**Comment by ikitayama** [comment]
@heplesser not yet, OK then I need to detect the -static and replace it with -qstaticlink=xllibs in CMAKE_CXX_FLAGS.

**Comment by heplesser** [comment]
Since a work-around exists and this only seems to concern one specific system, I close this issue. Please re-open if necessary.
