### ISSUE TITLE
Revise test_post_trace notebook

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1168]
The `model_details/test_post_trace.ipynb` notebook should be revised to become more of a tutorial exposition. It should also be linked from `guides/index.rst`.

**Comment by clinssen** [comment]
Dear @heplesser, could you elaborate on how you would like the format of the notebook to change? Right now there is already a good amount of explanatory text inbetween the code, but perhaps this is not what you are referring to.

Right now the notebook is linked to from ``test_regression_issue-1034.py``; this is akin to how all the other notebooks in ``doc/model_details`` are linked: not from the ReadTheDocs documentation directly, but from comments (and API documentation comment blocks) in the code.

**Comment by heplesser** [comment]
@clinssen I have a few suggestions:
- To keep with the style of the other notebooks in `doc/model_details`, the notebook should begin with a text cell providing an introduction, before any Python code follows. 
- There should be a brief explanation of the synapse models we are checking.
- The plots at the end all come in one huge cell, all with the same plot title. It would be much more readable if we had one figure at a time with explanations before or below.
- The notebook currently does not run due to changes in NEST3 (will create separate issue for it).

**Comment by heplesser** [comment]
I also wonder if we should change the name of this notebook, the "test" gives limited meaning. If we do so, documentation links would need to be updated, see #1949.

**Comment by heplesser** [comment]
One decision to make about this notebook is if it should just illustrate what happens in the `testsuite/regressiontests/issue-1034.py` test or if we want to use it to provide more background on pre- and post-synaptic traces in STDP synapses. If it only illustrates the test, we could even wonder if one could not add that to the test itself and to delete the notebook, to avoid duplicity; if we keep it, I'd link it from the test document. If it is turned into a tutorial on pre/post traces, it should be linked from the STDP synapse model documentation.

In any case, the links should be created as part of the PR for this issue.
