### ISSUE TITLE
Dot displays in examples on nest simulator web site broken

### ISSUE THREAD

**Issue by diesmann** [nest/nest-simulator#117]
the panels that should contain dot displays appear but seem to be empty, at least on my screen.

**Comment by steffengraber** [comment]
Hi Markus, 
could you please send me an example screenshot.
Steffen

**Comment by jougs** [comment]
http://www.nest-simulator.org/wp-content/uploads/2015/09/repeated_stimulation.png
http://www.nest-simulator.org/wp-content/uploads/2015/09/brunel_alpha_numpy.png

**Comment by jougs** [comment]
Executed locally, the scripts give the desired result. I assume that the problem is related to the marker-size or such in the style script that is used to generate the plots for the homepage.

**Comment by steffengraber** [comment]
There are some problems with the color scheme for matplotlib. Better to use the the standard.

**Comment by steffengraber** [comment]
I did a complete new build.
For example:
http://www.nest-simulator.org/wp-content/uploads/2015/10/brunel_alpha_numpy.png

**Comment by jougs** [comment]
Thanks. This is OK for now, but I really would like to have the old color scheme back. Could you please attach your script here, so I can test what the underlying problem is?

**Comment by steffengraber** [comment]
I used this fantastic script: https://gist.github.com/huyng/816622.
It worked some time ago but after a few improvements of my system ...




On 02.10.2015 11:02, Jochen Martin Eppler wrote:
> Thanks. This is OK for now, but I really would like to have the old
> color scheme back. Could you please attach your script here, so I can
> test what the underlying problem is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nest/nest-simulator/issues/117#issuecomment-144963875>.
>

--
Steffen Graber

Simulation Lab Neuroscience
Division HPC in Neuroscience         Phone:  +49 2461 61 8930
Jülich Supercomputing Centre         E-mail: s.graber@fz-juelich.de
Institute for Advanced Simulation
Forschungszentrum Jülich GmbH
http://www.fz-juelich.de/ias/jsc

Institute of Neuroscience and Medicine (INM-6)
Computational and Systems Neuroscience &
Institute for Advanced Simulation (IAS-6)
Theoretical Neuroscience
Jülich Research Centre and JARA
Jülich, Germany
http://www.csn.fz-juelich.de


------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Dr. Karl Eugen Huthmacher
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr.-Ing. Harald Bolt,
Prof. Dr. Sebastian M. Schmidt
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------

**Comment by steffengraber** [comment]
Find the problem: changing the default backend to GTKAgg solves it.

**Comment by jougs** [comment]
Nice investigation! Thanks for solving it.
