### ISSUE TITLE
Source directory layout reorganisation

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1175]
As discussed during the Jülich NEST Hackathon of April 2019.

- [ ] Create a new `/src` directory and move all C++ and sli source files into here. E.g. `/nestkernel`, `/sli`, etc. are moved to `/src/nestkernel`, `/src/sli`, etc.
- [ ] PyNEST/SLI/C++ examples should be combined in `/examples`
- [ ] Create new subdirectories in the `/src/models` directory according to:
  - `stimulating_devices`
  - `recording_devices`
  - `spiking_neurons` (including precise variants)
  - `synapses` (maybe we need this also with `spiking_`, `rate_`, `binary_`)
  - `binary_neurons`
  - `rate_neurons`
  - gap junctions? dopamine? structural platicity 
- [ ] PyNEST test suite should not be part of NEST module

**Comment by jougs** [comment]
This is closely related to #291.

**Comment by jougs** [comment]
In addition to cleaning things up, this also needs to take into account the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) and commonly respected practice in the major distributions.

**Comment by heplesser** [comment]
I generally consider this proposal sensible sensible, although I can never decide if I really like the `src` directory. Most of our examples are also code of a kind. Topology is going to disappear as a separate entity in NEST3.

**Comment by clinssen** [comment]
Removed topology module from the list.

**Comment by hakonsbm** [comment]
Wait until #1282 is merged!

**Comment by gtrensch** [comment]
@clinssen #1282 is merged.

**Comment by gtrensch** [comment]
@clinssen Are there any updates on this?

**Comment by jougs** [comment]
After recent discussions with @terhorstd and others, I am not sure anymore if the first and third point actually have a majority of the developers on their side. We should definitely bring this up again in one of the video conferences. I have a working prototype of the fourth point and the second should also be relatively easy to fix. As I'm working on this already, I'm re-assigning to myself.

**Comment by jougs** [comment]
The fourth point is now [described as the solution](https://github.com/nest/nest-simulator/issues/1130#issuecomment-679318588) to #1130.

**Comment by jougs** [comment]
As this is more controversial than expected and several points were/are addressed in separate issues, I'm closing this ad *wontfix*.
