### ISSUE TITLE
Make installcheck error

### ISSUE THREAD

**Issue by hedyehrezaei** [nest/nest-simulator#1179]
Dear all,

I confronted an error while trying to install nest 2.16.0 on ubuntu:

$ make installcheck
Execute NEST's testsuite....

Phase 1: Testing if SLI can execute scripts and report errors
-------------------------------------------------------------
  Running test 'selftests/test_pass.sli'... Running  Apr 15 10:46:45 stop [Error]: No stopped context was found! Apr 15 10:46:45 Start [Error]: Something went wrong during initialization of NEST or one of its modules. Probably there is a bug in the startup scripts. Please report the output of NEST at https://github.com/nest/nest-simulator/issues . You can try to find the bug by starting NEST with the option --debug
/home/hedyeh/bin/nest_serial: 20: /home/hedyeh/bin/nest_serial: Apr: not found
Failed: unexpected exit code 127

Running  Apr 15 10:46:45 stop [Error]: No stopped context was found! Apr 15 10:46:45 Start [Error]: Something went wrong during initialization of NEST or one of its modules. Probably there is a bug in the startup scripts. Please report the output of NEST at https://github.com/nest/nest-simulator/issues . You can try to find the bug by starting NEST with the option --debug
/home/hedyeh/bin/nest_serial: 20: /home/hedyeh/bin/nest_serial: Apr: not found

***
*** An unexpected exit code usually hints at a bug in the test suite!
***
*** Please report the problem at
***     https://github.com/nest/nest-simulator/issues
***
*** To help us diagnose the problem, please attach the archived content
*** of these directories to the issue:
***     - '/home/hedyeh/nest-simulator-2.16.0-build/reports'
***     - '/home/hedyeh/nest-simulator-2.16.0-build/reports/nest.p2dFF'
***

CMakeFiles/installcheck.dir/build.make:57: recipe for target 'CMakeFiles/installcheck' failed
make[3]: *** [CMakeFiles/installcheck] Error 2
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/installcheck.dir/all' failed
make[2]: *** [CMakeFiles/installcheck.dir/all] Error 2
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/installcheck.dir/rule' failed
make[1]: *** [CMakeFiles/installcheck.dir/rule] Error 2
Makefile:210: recipe for target 'installcheck' failed
make: *** [installcheck] Error 2

Hope you can help me.
Thanks

**Comment by terhorstd** [comment]
There seems to be something wrong in the setup of your paths, which is not a bug in NEST.
This is generally a discussion that is easier on the user [mailing list](https://nest-simulator.org/mailinglist), please subscribe there.
