### ISSUE TITLE
Module import error in Python Regression test issue-1034.py 

### ISSUE THREAD

**Issue by lekshmideepu** [nest/nest-simulator#1180]
I came across the following error in a Travis OSX [build](https://travis-ci.org/lekshmideepu/nest-simulator/jobs/520817252#L5891) where Python was OFF.
```
Running test 'regressiontests/issue-1034.py'... Traceback (most recent call last):
  File "/Users/travis/build/lekshmideepu/nest-simulator/result/share/doc/nest/regressiontests/issue-1034.py", line 26, in <module>
    import nest
ImportError: No module named nest
Failed: missed SLI assertion
```

Obviously this test must not be run in a non-Python environment.

Surprisingly, as you could see [here](https://travis-ci.org/nest/nest-simulator/jobs/517258036#L5461), this test was a success in other Travis builds (and also ran successfully in all pull requests against master ever since).

Although this test is a regression test technically, it uses PyNEST and should thus not be located in the SLI testsuite, but belongs into the PyNEST testsuite (which already now contains at least one other regression test).

If there is a strong will to keep it in the SLI testsuite, it has to be guarded by something along these lines:
```python
import sys
EXIT_SKIPPED = 200
try:
    import nest
except ImportError:
    sys.exit(EXIT_SKIPPED)
```
However, as that would have to be repeated for each PyNEST test that is added to the SLI testsuite it does not seem to be a very sustainable solution.

**Comment by lekshmideepu** [comment]
Expect comments from @jougs , @clinssen , @heplesser

**Comment by jougs** [comment]
@lekshmideepu: I've extended and modified the description to reflect our joint view as I understood it from our F2F meeting earlier today. Feel free to edit if I misunderstood something.

**Comment by clinssen** [comment]
In an offline discussion, @jougs noted that it is possible to have Python test scripts in the `regressiontests` directory that do not rely on the PyNEST API, including the existing script `issue-779-1016.py`, which uses the Python "subprocess" module to invoke the `nest` binary directly. This makes it hard to distinguish between .py files that should always be run, and those that should only be run when NEST is being built with Python support (`-Dwith-python`/`"$xPYTHON" = "1"`).

Our suggestion is therefore to rename the script `test_regression_issue-1034.py` and move it into the same directory as the other PyNEST test files (`pynest/nest/tests`, which @jougs is presently refactoring into `pynest/tests`).
