### ISSUE TITLE
handles_test_event should return whether the target node can handle the event not raise a exception

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#1185]
as the name of the function suggests i would expect `handles_test_event` to return whether the target node can handle the event, i.e., a boolean value, not raise a exception (e.g., https://github.com/nest/nest-simulator/blob/master/nestkernel/node.cpp#L250). exceptions should then be raised on the node initiating the test, based on the return value. for nodes sending multiple event types this would simplify the connection test  (see e.g. the currently necessary `try...catch` in https://github.com/nest/nest-simulator/pull/1160/files#diff-0d5cdfc29172ee1805df4e31e2b75a38R404).

@suku248 what do you think about this? would this be possible to implement?

**Comment by heplesser** [comment]
@suku248 Ping

**Comment by heplesser** [comment]
Closing due to lack of interest.
