### ISSUE TITLE
Updating the docs regarding the MacOS installation

### ISSUE THREAD

**Issue by lekshmideepu** [nest/nest-simulator#1186]
As we soon have MacOS Mojave builds on Travis, we need to update our current documentation [page ](https://nest-simulator.readthedocs.io/en/latest/installation/mac_install.html) for OSX

**Comment by jessica-mitchell** [comment]
@lekshmideepu What exactly needs to be updated?

**Comment by jougs** [comment]
@lekshmideepu: ping!

**Comment by lekshmideepu** [comment]
Oh sorry, I missed it. Meanwhile I saw that the docs has been updated with Mojave and it looks fine.
