### ISSUE TITLE
Nest Topology: Recording Devices

### ISSUE THREAD

**Issue by yslahoti** [nest/nest-simulator#1187]
Is there any way to use devices that are connected in a layer? I generated a 30 x 30 grid and connected a device to the center neuron but am unable to extract the voltage information after simulation.

**Comment by heplesser** [comment]
@yslahoti This type of question is usually more appropriate for the NEST User mailing list (https://www.nest-simulator.org/community/). 

To be sure that I understand you correctly: You created a 30 x 30 grid of some model neurons, and then connected a `voltmeter` to the neuron in the center? What output do you get when you call `GetStatus` on the `voltmeter` after the simulation? The `events` dictionary in the dictionary returned by `GetStatus` should contain time stamps and voltages.

I would suggest to continue the discussion on the user mailing list.

**Comment by terhorstd** [comment]
Continued on mailing list
