### ISSUE TITLE
Data types in model parameters (discussion)

### ISSUE THREAD

**Issue by jessica-mitchell** [nest/nest-simulator#1188]
It was noted during discussion of PR #1143 that the parameter data types of models (nest-simulator/models/*.h) are perhaps confusing to users in a python environment. E.g. the current models show the parameter data types as 'double'  rather than float:
![image](https://user-images.githubusercontent.com/3313313/57222097-af4f5180-7001-11e9-8bfd-969f4f854544.png)

How can we best clarify the correct data types users will need to use? Is it important to specify the data type in the model docs or can it be left out? Can we improve the error messages?

**Comment by jessica-mitchell** [comment]
@jougs @heplesser Based on the brief chat at the open dev meeting this Monday, should I go ahead and remove the column for data type in the models file (for PR #1143) altogether?

**Comment by jougs** [comment]
@jessica-mitchell, @clinssen, @steffengraber: should we have a f2f meeting next week to discuss the several open issues regarding model documentation? I think we'd gain more from looking more with a bird-view style instead of discussing each detail separately.

**Comment by jessica-mitchell** [comment]
Closing this issue because resolved in PR #1143
