### ISSUE TITLE
Activation particles for NaP and T in ht_neuron

### ISSUE THREAD

**Issue by ricardomurphy** [nest/nest-simulator#1189]
In setting up a network of ht_neuron neurons I've found it necessary to change the number of activation particles for the NaP and T currents. I've done this by altering the code for ht_neuron as shown in the attached file, where both currents now have just one activation particle. But more generally it would be convenient if the number of activation particles for these currents could be made settable.

[ht_neuron_sh_DKhep.cpp.txt](https://github.com/nest/nest-simulator/files/3151380/ht_neuron_sh_DKhep.cpp.txt)

**Comment by clinssen** [comment]
Hi, thanks for the report! Sorry, I am not an expert on the ht_neuron model, and the file you attached is quite big. Could you highlight (perhaps in a comment on this thread) the parts of the code that you would suggest to change? Could you also mention a reference to the literature so we can add it as a citation to the model documentation?

**Comment by ricardomurphy** [comment]
Hello
There are only two differences between the standard ht_neuron 
and ht_neuron_sh_DKhep:

ht_neuron line 113:
node.S_.I_NaP_ = -node.P_.g_peak_NaP * std::pow( m_inf_NaP, 3.0 )
ht_neuron_sh_DKhep line 113: 
node.S_.I_NaP_ = -node.P_.g_peak_NaP * std::pow( m_inf_NaP, 1.0 )

So it would be good if this line could read something like:
node.S_.I_NaP_ = -node.P_.g_peak_NaP * std::pow( m_inf_NaP, p_NaP )
with p_NaP a settable parameter (e.g. so it can be set to 1.0 or 
3.0). I guess p_NaP could then just be included in the list of 
settables (g_peak_NaP etc.).


ht_neuron line 123:
node.S_.I_T_ = -node.P_.g_peak_T * y[ S::m_IT ] * y[ S::m_IT ] * y[ S::h_IT ]
ht_neuron_sh_DKhep line 123:
node.S_.I_T_ = -node.P_.g_peak_T * y[ S::m_IT ] * y[ S::h_IT ]

So line 123 it would be good if y[ S::m_IT ] could be raised to 
some settable power (p_T say). I presume this would be done with 
std::pow( y[ S::m_IT ], p_T ) but I'm not a C programmer.

As regards a reference we're writing a paper now. I can let you know when (if) it gets published. Hope that helps.
Regards,
Ricardo
