### ISSUE TITLE
GetConnections() does not work with volume_transmitter as target

### ISSUE THREAD

**Issue by alberto-antonietti** [nest/nest-simulator#1190]
When retrieving the connections to a volume_transmitter, `GetConnections()` behaves inconsistently.

```
A=nest.Create("iaf_cond_exp")
VT=nest.Create("volume_transmitter")
nest.Connect(A,VT)
nest.GetConnections(A,VT)
```
returns: ()
```
nest.GetConnections()
```
returns: (array('l', [1, 2, 0, 0, 0]),)

In `788e93e` , with `NEST 2.14` GetConnections() is working fine.

I will try to locate the source of the problem, but maybe someone familiar with the function (e.g., @hakonsbm, who refactored GetConnections in #1099 ) could identify the issue immediately.

**Comment by hakonsbm** [comment]
It works for me with the current master (788e93e3). What version are you on?

**Comment by hakonsbm** [comment]
@alberto-antonietti Sorry, I think I misread your issue. Do you mean the inconsistency between what is returned from `nest.Connect()` and `nest.GetConnections()`?

**Comment by alberto-antonietti** [comment]
Sorry a line in the code was missing.
`nest.GetConnections(A,VT)`
returns () instead of (array('l', [1, 2, 0, 0, 0]),)

**Comment by hakonsbm** [comment]
Ah, that makes more sense, I get the same result as you then. I can try to look into it.
