### ISSUE TITLE
c++: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument] ^

### ISSUE THREAD

**Issue by yurivict** [nest/nest-simulator#1193]
clang-6 prints this warning for every compilation line.

**Comment by jougs** [comment]
Do you have a suggestion on how to fix this or could you even provide a PR? Thanks!

**Comment by yurivict** [comment]
I think this is induced by some external package.

**Comment by jougs** [comment]
Thanks for clearing this up and closing.

**Comment by yurivict** [comment]
You're welcome.
