### ISSUE TITLE
Please don't fail when CMAKE_INSTALL_PREFIX is /usr/local

### ISSUE THREAD

**Issue by yurivict** [nest/nest-simulator#1195]
https://github.com/nest/nest-simulator/blob/master/CMakeLists.txt#L104

There's nothing wrong with installing into ```/usr/local```.
It normally installs into a stage directory when package is built.

**Comment by terhorstd** [comment]
This is something that we should re-discuss in one of the next [NEST VCs](https://github.com/nest/nest-simulator/wiki/Open-NEST-Developer-Video-Conference), probably after the NEST conference.

**Comment by jougs** [comment]
In the [Open NEST VC](https://github.com/nest/nest-simulator/wiki/2019-07-08-Open-NEST-Developer-Video-Conference) We have come to the conclusion that if users decide to install globally they should not be prohibited from doing so. I'll prepare and send a pull request to remove the pertaining code.
