### ISSUE TITLE
pynestkernel.pyx:689:10: Unreachable code

### ISSUE THREAD

**Issue by yurivict** [nest/nest-simulator#1196]
I'm getting this with python-3.6 on FreeBSD:
```
warning: /usr/ports/science/nest/work/nest-simulator-2.14.0-2100-g788e93e3/pynest/pynestkernel.pyx:689:10: Unreachable code
warning: /usr/ports/science/nest/work/nest-simulator-2.14.0-2100-g788e93e3/pynest/pynestkernel.pyx:689:10: Unreachable code
```

**Comment by jougs** [comment]
We all get to see these warnings.

The reason for them is that Cython gets confused by the [`raise` statement in the line above](https://github.com/nest/nest-simulator/blob/master/pynest/pynestkernel.pyx#L687) although that is clearly in an (even unlikely) `else` clause and thus usually not executed. In the generated code in `pynest/pynestkernel.cxx`, you can see that the "unreachable" statement is instantiated just fine (line 11805 in my case). So no need to worry.

I'm closing this issue as "Wont't fix" and "External bug". Probably someone should [file a bug against Cython](https://github.com/cython/cython/issues).
