### ISSUE TITLE
NEST packages for various linux flavors on Open Build Service

### ISSUE THREAD

**Issue by dilawar** [nest/nest-simulator#1202]
I am building NEST packages for various Linux favors using Open Build Service. These are available here https://software.opensuse.org//download.html?project=home%3Adilawar&package=nest 

~These are `python3` only (its easy to make  them for default python but I personally don't see any merit).~ Builds with default python distribution.

I am using my forks to build these packages: some changes were required to build them successfully. I'll submit a PR later when packages are tested. 

The package repository is here: https://build.opensuse.org/package/show/home:dilawar/nest

**Comment by steffengraber** [comment]
I'm sorry for the really late answer. That looks very nice. Are you still taking care of it? From what I can see, you're offering packages for `NEST 2.16.0`.  Currently we are at `v2.20.0`.

**Comment by steffengraber** [comment]
Any news on that?

**Comment by dilawar** [comment]
I fell through cracks at my end. Thanks for the nudge. 

I just updated the build pipeline. Since minimum cmake version required now is 3.12, it is going to build on fewer distros. I'll that latest Ubuntu, Debian, SUSE and Fedora passes. I am low on available time and attention these days, do ping me once in while if you don't hear from me in a while. I'd love to see this PR going through.

**Comment by dilawar** [comment]
Successfully building packages from the master branch for the most recent distros : ubuntu 18.10 onwards, Debian-10 onwards, openSUSE-15.2 onwards, Fedora_30 onwards. 

I had to make one change: rename `debian` directory to `_debian` since files inside `debian` was getting preference over my files while building deb package.
