### ISSUE TITLE
Improve warning messages in pynest microcircuit example, using warnings package

### ISSUE THREAD

**Issue by morales-gregorio** [nest/nest-simulator#1207]
In the current version of the pynest microcircuit (implementation of the Potjans and Diesmann 2014 model) the error/warning messages are directly printed to the terminal.

Using the python warning package should probably be the preferred option.

**Comment by stinebuu** [comment]
@jhnnsnk Did #1444 fix this by any chance?

**Comment by stinebuu** [comment]
@morales-gregorio Sorry for a very long response time! Would you be able to provide a PR for this?

**Comment by heplesser** [comment]
@jasperalbers @ackurth Have you been able to take a look at this?

**Comment by morales-gregorio** [comment]
Hi, I am looking into it now (sorry for the super late response), in general I think that all the documentation improvements from @jhnnsnk already fixed most (if not all the issues) that I was referring to when I wrote this.
