### ISSUE TITLE
Assertion `source_lid < MAX_LID' failed with GetConnections

### ISSUE THREAD

**Issue by alberto-antonietti** [nest/nest-simulator#1211]
Another issue that I encountered with `GetConnections`

When calling nest.GetConnections with "large" networks, NEST terminate because an assertion fails.

> /nestkernel/target_data.h:267: void nest::TargetData::set_source_lid(nest::index): Assertion `source_lid < MAX_LID' failed 

You should reproduce the problem with the following script:
```
import nest

N=530000

A=nest.Create('iaf_cond_exp',N)
B=nest.Create('iaf_cond_exp',1)

nest.Connect(A,B,'all_to_all')
print("CONNECTED")

nest.GetConnections(A,B)
print("GOT CONNECTIONS")
```

the script works fine with N<=2^19-1, since the MAX_LID in my system is defined as 2^19-1 (i.e., 524287). 

@hakonsbm, can be this somehow related to #1190?

**Comment by hakonsbm** [comment]
@alberto-antonietti The assertion fails because you are running out of bits to store the LID, the local id of the presynaptic neuron. The `MAX_LID` is the limit to the number of presynaptic neurons possible per virtual process. You can therefore use multiple threads, or use MPI to avoid going over the `MAX_LID` for each virtual process.

**Comment by alberto-antonietti** [comment]
Hi @hakonsbm! Yes, I get the error when running the network on a Power7 system that does not have MPI, but works with OpenMP only. On this system, I can then run networks with less than $2^19-1$ neurons, right?

**Comment by hakonsbm** [comment]
@alberto-antonietti 2^19-1 neurons per VP, so per thread if you are using OpenMP. I don't know, but it might be possible to tweak this value somehow, maybe @jakobj can give some hints about that.

**Comment by alberto-antonietti** [comment]
You are right, it is just for VP! I am closing the issue. Thanks for the hint!
