### ISSUE TITLE
Add `LD_LIBRARY_PATH` to guide for "writing an extension module"

### ISSUE THREAD

**Issue by mschmidt87** [nest/nest-simulator#1222]
To build an extension module for NEST, I followed the guide on the NEST Developer Space: https://nest.github.io/nest-simulator/extension_modules

However, after following steps 1-5 for installing the example module, I couldn't load it, but received this error: 
```Jun 06 09:23:59 Install [Error]: DynamicModuleManagementError
    Module 'mymodule' could not be opened.
    The dynamic loader returned the following error: 'file not found'.
```

I could easily fix this by adding the NEST lib folder to my `LD_LIBRARY_PATH`, like so:
`export LD_LIBRARY_PATH=~/opt/nest/ins/lib/nest`

Now, perhaps it would be a good idea to add this simple step to the documentation?

**Comment by jougs** [comment]
The correct way to set the module loading path at the moment is to set `NEST_MODULE_PATH`, which is correctly done if you source `nest_vars.sh`. This is, however not documented very prominently.

@sarakonradi, could you please add the information to at least the documentation for installing from source? Thanks!
