### ISSUE TITLE
Compiler errors on K

### ISSUE THREAD

**Issue by janhahne** [nest/nest-simulator#123]
The current nest code produces compiler errors on the K computer. There are simple workarounds for all of them, nevertheless it would be nice to add a configure option similar to "--enable-bluegene" or any other fix.

<h4>When compiling with:
>../nest-simulator/configure --prefix=[...]/nest-simulator.install --with-openmp=-Kopenmp --with-mpi --with-gsl=[...]/gsl-1.15.install --without-python --without-readline --without-pthread CC=mpifccpx CXX=mpiFCCpx --host=sparc64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu CFLAGS="-Nnoline -DUSE_PMA -DIS_K" CXXFLAGS="--alternative_tokens -O3 -Kfast,openmp, -Nnoline, -Nquickdbg -NRtrap -DUSE_PMA -DIS_K"

<h4>The following compiler errors occur:

  in librandom/clipped_randomdev.h:

  >"../../nest-simulator/librandom/clipped_randomdev.h", line 337: error: class member designated by a using-declaration must be visible in a direct base class
      using RandomDev::operator();
      
  in lines 97,204,205,337,446,447

  **simple workaround on K:** "//" this lines
  ________________________________

  in nestkernel/nest.h

 > "../../nest-simulator/nestkernel/nest.h", line 84: error: identifier "LONG_LONG_MAX" is undefined
    const tic_t tic_t_max = LONG_LONG_MAX;

  in lines 84,85 - reason: LONG_LONG_MAX is unknown

   **simple workaround on K:** replace LONG_LONG_MAX with LONG_MAX
  ________________________________

  in nestkernel/connector_model_impl.h

  >"../../nest-simulator/nestkernel/connector_model_impl.h", line 277: error: expected an identifier
      if ( !std::isnan( delay ) )
      
  in several lines - reason: std::isnan is unknown    

  **simple workaround on K:** #include cmath and remove "std::" from lines

**Comment by ikitayama** [comment]
@janhahne With your set of options, I am still fail to build NEST on the frontend. Are you working in one of the old development environments? I'd appreciate your PRs.

**Comment by janhahne** [comment]
@ikitayama If you apply the workarounds mentioned above to the current state of the master branch and use the options from above you should be able to build NEST on the frontend. I added a branch where those workarounds were applied ( https://github.com/janhahne/nest-simulator/tree/Kcomputer ). There is still an error while "make install", which occurs because the executable can not be executed on the front end. But this can be ignored, as the executable are build correctly.

The workarounds are however probably not the best way of fixing this - this is why I opened an issue instead of a pull request.

**Comment by ikitayama** [comment]
@janhahne Thank you for creating the branch. I spent couples of hours and gave up detecting the MPI and worked around by setting SLI_mpi_link_ok to yes. As you said, build still fails.
I will try your branch over the weekend and report back here. Let's see how far I can go.

**Comment by ikitayama** [comment]
@janhahne I've just completed the build of your special branch on the frontend. Thank you.

**Comment by ikitayama** [comment]
@janhahne In the mean time, we need something like below for K computer,
do you have something similar already to send to mainline?

```
$ git diff acinclude.m4 
diff --git a/acinclude.m4 b/acinclude.m4
index d7bbef5..cecf04c 100644
--- a/acinclude.m4
+++ b/acinclude.m4
@@ -71,6 +71,11 @@ echo "Platform: ${host}"
          if test "$SLI_optimize" = "set" -a -z "$SLI_optimizeflags"; then 
            SLI_optimizeflags="-O3 -fp-model precise"
          fi
+       elif test "${compversion:0:5}" = "FCCpx"; then
+        # Fujitsu compiler pretending to be g++
+        SLI_debugflags="-g"
+         SLI_warningflags=""
+         SLI_optimizeflags="-O3"
        else
          #real g++
          echo "Compiler : g++"
@@ -359,6 +364,11 @@ echo "Platform: ${host}"
          if test "$SLI_optimize" = "set" -a -z "$SLI_optimizeflags"; then 
            SLI_optimizeflags="-O3 -fp-model precise"
          fi
+       elif test "${compversion:0:5}" = "fccpx"; then
+         # Fujitsu compiler pretending to be gcc
+         SLI_debugflags="-g"
+         SLI_warningflags=""
+         SLI_optimizeflags="-O3"
        else
          #real g++
          echo "Compiler : gcc"
```

**Comment by ikitayama** [comment]
The third workaround seems to be reasonably acceptable to me and I checked
that FCC doesn't understand the usage yet (C++11 is partially supported).

**Comment by heplesser** [comment]
@janhahne @ikitayama I have a few comments concerning the issues you experience in building NEST on K. We detect K through the `-DIS_K` passed to the configure script. Since there is only a single K in the world, I would leave it at that.

#####  `librandom/clipped_randomdev.h`

I fear the problem here may be a weakness in the compiler. Each of the classes that are used as template argument `BaseRDV` contains the corresponding line `using RandomDev::operator()`, so I believe proper visibility should be given. I would suggest that you change

        #if not defined( HAVE_XLC_ICE_ON_USING )

to 

        #if not defined( HAVE_XLC_ICE_ON_USING ) and not defined( IS_K )

##### `nestkernel/nest.h`

Janne Morén posted the solution on NEST User on March 18, 2015, and I created tickets for it in our old ticketing system (960, 961), but did never get back to them, unfortunately. The main point is that on K, one needs to use `LLONG_MIN` and `LLONG_MAX`, so it should be

```C++
#ifdef HAVE_LONG_LONG
typedef long long tic_t;
#ifdef IS_K
const tic_t tic_t_max = LLONG_MAX;
const tic_t tic_t_min = LLONG_MIN;
#else
const tic_t tic_t_max = LONG_LONG_MAX;
const tic_t tic_t_min = LONG_LONG_MIN;
#else
typedef long tic_t;
const tic_t tic_t_max = LONG_MAX;
const tic_t tic_t_min = LONG_MIN;
#endif
```

##### `nestkernel/connector_model_impl.h` 

Janne Morén reported this problem on 18 March 2015 on NEST User (old ticket 961).

I would suggest to define the following in `libnestutil/numerics.h`:

```C++
inline
bool
is_nan(double x)
{
#ifdef IS_K
  return isnan(x);   // uses C99 macro
#else
  return std::isnan(x);   // uses C++11-compliant function
}
```
and then to call `is_nan()` from `connector_model_impl.h`.  I added the underscore to the function name to distinguish it from anything built-in.

**Comment by janhahne** [comment]
@heplesser Thank you for your explanations and suggestions. I implemented them in a branch and was able to build this version of nest on K. As discussed in the meeting this morning I am now waiting for @tammoippen to send me a small test script to ensure that the new function `is_nan` works properly on K.

**Comment by JanneM** [comment]
Are you going to try building with pynest at some point? I tried recently, but linking to the pynest library during startup fails, likely due to the dlopen() bug on K.

**Comment by ikitayama** [comment]
@hanahne I've confirmed the updated branch can be built without an issue. However,
when I do launch the simulator interactively it fails with an error comes from omp_set_num_threads.
Do you have a simple set of .sli files I can test?

**Comment by ikitayama** [comment]
@janneM I think I've built PyNEST, but it fails at run-time too.

Some notes:
The GNU compatibility flag, -Xg is absolutely needed, and the cythonize part
needs to be done on the compute node. I manually edited the pynest/Makefile
to remove the shared flag from from pynestkernel_la_LDFLAGS.

**Comment by JanneM** [comment]
@ikitayama Did you manage to cross-compile the rest of NEST? That's good news, as having to log in for compilation was very slow and painful. 

How exactly does it fail? Is it the dlopen() call that crashes?

**Comment by ikitayama** [comment]
@janneM No, it's not a pure cross-compilation, I had to log on to the compute node.

I'll report back here about the details of the issue. It could well be that the dlopen() issue,
but not sure yet.

**Comment by ikitayama** [comment]
@janneM 

In my trying  of this:

$ mpirun -np 2 python /[...]/nest-simulator/pynest/examples/CampbellSiegert.py 

Error suggested I need SciPy and other modules.

**Comment by JanneM** [comment]
Scipy and Numpy are available on the compute nodes. Which order do you
import things? I import nest as the very first library and that works.



2015-10-25 23:12 GMT+09:00 Itaru Kitayama <notifications@github.com>:

> @janneM <https://github.com/janneM>
>
> In my trying of this:
>
> $ mpirun -np 2 python
> /[...]/nest-simulator/pynest/examples/CampbellSiegert.py
>
> Error suggested I need SciPy and other modules.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nest/nest-simulator/issues/123#issuecomment-150926773>
> .
>



-- 
Jan Morén
http://sites.google.com/site/janmoren/
http://janneinosaka.blogspot.com

**Comment by ikitayama** [comment]
@JanneM Ah, yes they are. Importing nest first ended up with no such module, even with
the correct PYTHONPATH set.

When you build your own PyNEST, did you do that all while you were on the compute node?
libtool fails to build a shared library if the -shared flag kept in the pynest/Makefile.

**Comment by ikitayama** [comment]
@janhahne I just wanted to know that I've verified that the HEAD of the Kcomputer computer can use OpenMP threads, together with MPI on K computer. Many thanks to @JanneM for providing a .sli script for my testing and useful advices.

**Comment by janhahne** [comment]
@ikitayama Thank your for your help with this issue.

**Comment by janhahne** [comment]
Fixed with PR 127 and 130
