### ISSUE TITLE
boost include path not properly set in NEST 2.18.0

### ISSUE THREAD

**Issue by niltonlk** [nest/nest-simulator#1238]
Make fails with the following error with -Dwith-boost=ON or -Dwith-boost=<PATH_TO_BOOST>, even with the correct boost include path being displayed in the NEST Configuration Summary.

nest-simulator-2.18.0/libnestutil/sort.h(36): catastrophic error: cannot open source file "boost/sort/spreadsort.hpp"

This error can be solved by adding
-Dwith-includes=<PATH_TO_BOOST_INCLUDE_DIR>

**Comment by clinssen** [comment]
It looks like a missing
```
include_directories( ${BOOST_INCLUDE_DIR} )
```
in https://github.com/nest/nest-simulator/blob/0ac2385db24bdf76c43f310ee5f7da10d274c457/cmake/ProcessOptions.cmake#L565

**Comment by gtrensch** [comment]
Unfortunately, I have not been able to reproduce the problem. Everything works as expected (Ubuntu 19.04, CMake version 3.13.4). I could imagine that the problem is probably caused by CMake find_package( Boost ...).  
However, is it possible for you to provide some additional diagnostic information?
- environment, i.e., Mac OS X or Ubuntu version, CMake version, etc.
- the CMake output
- the make log with make VERBOSE=1

Many thanks!

**Comment by niltonlk** [comment]
Sorry I did not give details of the system and for the late reply.

I have re-executed the procedure to post the requested info, and noticed that the warning message has changed from "catastrophic error: cannot open source file" to "fatal error: No such file or directory". This change might be due to update on some packages, but the problem keeps the same.

- Environment
OS: CentOS 7.6.1810
GCC: 8.3.0 (from OpenHPC 1.3.7); previous version was 8.2.0
CMake: 3.13.4 (from OpenHPC 1.3.7); previous version was 3.12.2
boost: 1.69.0 (from OpenHPC 1.3.7); previous version was 1.68.0
- CMake output
[cmake.out.txt](https://github.com/nest/nest-simulator/files/3682204/cmake.out.txt)

- make output with make VERBOSE=1
[make.out.txt](https://github.com/nest/nest-simulator/files/3682206/make.out.txt)

I have tested with nest-2.16.0 and it compiles with no problem. I post the CMake and make output for reference:
- CMake output
[cmake-nest-2.16.0.txt](https://github.com/nest/nest-simulator/files/3682256/cmake-nest-2.16.0.txt)

- make output with make VERBOSE=1
[make-nest2.16.0.txt](https://github.com/nest/nest-simulator/files/3682300/make-nest2.16.0.txt)

Hope this helps,

Best

**Comment by niltonlk** [comment]
Dear all,

This issue still persists on the master branch.
I tried the suggestion by @clinssen, but it did not solve the problem.

> It looks like a missing
> 
> ```
> include_directories( ${BOOST_INCLUDE_DIR} )
> ```
> 
> in
> 
> https://github.com/nest/nest-simulator/blob/0ac2385db24bdf76c43f310ee5f7da10d274c457/cmake/ProcessOptions.cmake#L565

I found that adding

`${BOOST_INCLUDE_DIR}`

on

`target_include_directories( target PRIVATE dirs )`

for the following targets:

- nestkernel
- models
- precise
- topology
- nest
- nest_lib

**WITHOUT** the addition of the `include_directories( ${BOOST_INCLUDE_DIR} )` mentioned by @clinssen above solves it.

I could issue a pull request with this changes if that is OK, and would like to know if I should also make the changes suggested by @clinssen.

Another solution would be to add:

```
if ( HAVE_BOOST )
  include_directories( ${BOOST_INCLUDE_DIR} )
endif ()
```
in:

- nestkernel/CMakeLists.txt
- models/CMakeLists.txt
- topology/CMakeLists.txt
- precise/CMakeLists.txt
- nest/CmakeLists.txt

Note however that make installcheck still fails  #1239

**Comment by niltonlk** [comment]
This problem is present when BOOST is installed in a non-standard path, which would be the case of some HPC systems.

**Comment by niltonlk** [comment]
The solution suggested by @clinssen was actually correct. The only problem with his suggestion was that besides using BOOST_INCLUDE_DIR, it should be Boost_INCLUDE_DIR.

I am closing this and create a PR with the correct code. Please ignore the previously submitted PR (#1461).
