### ISSUE TITLE
Error/typo in nest-simulator.org/connection_management.py

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#124]
In http://www.nest-simulator.org/connection_management/ > inspecting connections

The first line
```GetConnections(source=None, target=None, model=None)``` 
should be changed to
```GetConnections(source=None, target=None, synapse_model=None)```

[see https://github.com/nest/nest-simulator/blob/master/pynest/nest/hl_api.py#L777]

**Comment by jougs** [comment]
Fixed. Thanks for the report.
