### ISSUE TITLE
Static code checks should be run after all other tests

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#1246]
As far as I can see no other test is run if the static code checks fail. This seems suboptimal to me as the more important information early in the review process is whether the changes break existing functionality and not whether some curly brace is on the correct line. Would it be possible to change this order?

@lekshmideepu

**Comment by Silmathoron** [comment]
The reason it is performed like this is to minimize the amount of wasted CPU time, I would strongly advise to keep it that way...

**Comment by jakobj** [comment]
could you elaborate what you mean by "wasted CPU time"? my naive approach would be that code style is the last thing that should be checked before the PR is merged, not the first thing? is the CPU time wasted because travis shows me that my code is leading to unexpected results if my formatting is off?

**Comment by Silmathoron** [comment]
Suppose we change the order and your code is fine:
- Travis runs the tests (CPU1)
- Travis checks the style (CPU2) and breaks
You will fix the style and push.
- Travis runs the tests (CPU1)
- Travis checks the style (CPU2) and validate
So we ran 2*CPU1+2*CPU2 which is roughly 2*CPU1

With our current setup, the first CPU1 goes away so we divide CPU consumption by 2.

**Comment by clinssen** [comment]
At present, a full build of NEST is performed in the "static check" stage. Perhaps it would be possible to dramatically speed things up by eliminating the build from the static checker stage. I cannot see the results from the build being used in this stage, but I could be overlooking something. See https://github.com/nest/nest-simulator/blob/0ac2385db24bdf76c43f310ee5f7da10d274c457/extras/travis_build.sh#L216 

@lekshmideepu : perhaps you can shed some light on this!

**Comment by Silmathoron** [comment]
@clinssen where do you see the build?

**Comment by jakobj** [comment]
@Silmathoron ah, I see now what you mean. i'm not intimately familiar with travis but would it be possible to have two different kinds of modes of operation
1) only the testsuite is run
2) first the style check is run, then the testsuite is run

after creating a PR the first mode would be activated by default, and one of the maintainers could switch to the second mode after the review is complete, as a final verification just before the PR is merged?

**Comment by Silmathoron** [comment]
@jakobj I don't know but it looks pretty complicated... especially compared to its alternative: running a cppcheck before clicking on the PR button ;)

**Comment by clinssen** [comment]
I have experimented a bit with speeding up the static check in my fork/branch https://github.com/nest/nest-simulator/compare/master...clinssen:fast-static-check. Without doing a full NEST-simulator build, the static check takes about 3m30s, against 10m30s before. We could easily make this even faster by not building vera++ from source every time, and not installing many of the NEST-simulator dependencies. 

The first requires a good place to cache the vera++ binaries. Any suggestions (e.g. inside the nest-simulator repo or outside)?

The second requires some more iterating on the .travis.yml file. @lekshmideepu: perhaps we could look at this together when we both have time?

**Comment by lekshmideepu** [comment]
> As far as I can see no other test is run if the static code checks fail. This seems suboptimal to me as the more important information early in the review process is whether the changes break existing functionality and not whether some curly brace is on the correct line. Would it be possible to change this order?
> 
> @lekshmideepu

@jakobj  You are right. Currently the idea is to check the code first and then move on to the further functionality tests. This has been decided in one of our developers meeting. Probably we could discuss it in one of our meeting with all the developers.

**Comment by lekshmideepu** [comment]
> I have experimented a bit with speeding up the static check in my fork/branch [master...clinssen:fast-static-check](https://github.com/nest/nest-simulator/compare/master...clinssen:fast-static-check). Without doing a full NEST-simulator build, the static check takes about 3m30s, against 10m30s before. We could easily make this even faster by not building vera++ from source every time, and not installing many of the NEST-simulator dependencies.
> 
> The first requires a good place to cache the vera++ binaries. Any suggestions (e.g. inside the nest-simulator repo or outside)?
> 
> The second requires some more iterating on the .travis.yml file. @lekshmideepu: perhaps we could look at this together when we both have time?

@clinssen I already tried this sometime back by adding the vera++ and other static check packages  from the travis package white list and the build was faster compared to the present one where we install all static packages from source. AFAIR, @gtrensch  added the static check packages part as he recommended a particulate version of the corresponding package and this version was not available at the travis white list that time.
