### ISSUE TITLE
[stdp_dopamine_synapse] A_plus and A_minus documentation

### ISSUE THREAD

**Issue by gui-miotto** [nest/nest-simulator#1253]
Hi everyone,

The documention for stdp_dopamine_synapse describes the parameters A_plus and A_minus as:

>   A_plus   double	- Amplitude of weight change for **facilitation**  
  A_minus   double	- Amplitude of weight change for **depression**  

Technically that is not true, because this ultimately depends on the value of n-b (actual concentration - baseline) . If n-b is negative, A_plus will control depression and A_minus facilitation.
The reason why that is the case is clear when we examine the equations in section 2.2 of [Potjans et al, 2010](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2996144/). But we can also see that this is in fact NEST's behaviour in the example bellow; it shows that A_plus can cause facilitation or depression depending solely on the baseline value.

My understanding is that A_plus controls weight changes driven by pre-before-post spike pairings and A_minus does the same for post_before_pre. So maybe a bit more accurate description would be be:

>   A_plus   double	- Amplitude of weight change for pre-before-post spike pairings
  A_minus   double	- Amplitude of weight change for post-before-pre spike pairings

``` python
import nest
import numpy as np

def mwe(baseline_shift=0.):
    # timing parameters
    dt = .1
    exp_duration = 20000.

    # kernel configuration
    nest.ResetKernel()
    nest.set_verbosity(20)
    nest.SetKernelStatus({'resolution' : dt})

    # dopamine setup
    DA_spike_times = np.round(np.arange(dt, exp_duration, dt), decimals=1)
    DA_spikes = nest.Create('spike_generator', params={'spike_times' : DA_spike_times})
    vt = nest.Create('volume_transmitter')
    nest.Connect(DA_spikes, vt, syn_spec={'delay' : dt})
    nest.CopyModel('stdp_dopamine_synapse', 'dopa_syn', params={
        'A_minus' : 0., 
        'b' : 1. / dt + baseline_shift,
        'vt' : vt[0],
    })
    
    # neurons
    neuron_spike = nest.Create('spike_generator', params={'spike_times' : [10000.]})
    neurons = nest.Create('parrot_neuron', 2)
    nest.Connect(neuron_spike, neurons[:1])
    nest.Connect(neurons[:1], neurons[1:], syn_spec='dopa_syn')
    synapse = nest.GetConnections(neurons[:1], neurons[1:])
    
    # Simulate 
    print('\nBaseline shift:', baseline_shift)
    print(f'Weight before simulation: {nest.GetStatus(synapse, "weight")[0]:.4f}')
    nest.Simulate(exp_duration)
    print(f'Weight after simulation: {nest.GetStatus(synapse, "weight")[0]:.4f}')

mwe(baseline_shift=0.000)
mwe(baseline_shift=0.001)
mwe(baseline_shift=-.001)
```

For which the output is:

```
Baseline shift: 0.0
Weight before simulation: 1.0000
Weight after simulation: 1.0000

Baseline shift: 0.001
Weight before simulation: 1.0000
Weight after simulation: 0.0952

Baseline shift: -0.001
Weight before simulation: 1.0000
Weight after simulation: 1.9048
```

(Note: I set A_minus to zero just to make clear that the weight changes we observe are dependent only on A_plus. The results are the same regardless of A_minus because there is just a pre-before-post event.)

**Comment by gui-miotto** [comment]
Hi @jougs! I couldn't make to the developers open conference. Could you please update me on this one? In which sense is this a bug?

Have you guys considered splitting A_minus and A_plus into 4 parameters? This would make possible to independently control the plasticity bellow and above the dopamine baseline. I would love to see that flexibility. :-)

**Comment by clinssen** [comment]
@gui-miotto: thanks for bringing this to our attention, and apologies for the long delay! We discussed this issue in today's Open NEST Developer meeting, and would for the moment suggest to stick with an update to the documentation and variable names, rather than splitting the parameters.

Would you like to file a pull request for this yourself? That way you will receive proper accreditation for your contribution.

**Comment by gui-miotto** [comment]
@clinssen : I would be glad to do the PR. Could you please just point me to the file I should edit?

**Comment by clinssen** [comment]
To avoid the risk of feature creep, let's focus on `models/stdp_dopa_connection.h`. The main change would be in the documentation of the model, which is in the comments block near the top of the file (N.B. you can use reStructuredText here for markup). Feel free to be verbose, and maybe point out that *commonly* (and when A_plus and A_minus have the appropriate sign) these correspond to facilitation resp. depression.

Possibly the facilitate_() and depress_() private member functions should be renamed as well, something like update_weight_pre_before_post_(), or some shorter version (probably you have a better idea here!)

**Comment by gui-miotto** [comment]
@clinssen just wanted to let you known that I didn't forget this PR. It is just that I've been very busy.
Until the end of next week it will be done.
