### ISSUE TITLE
Math symbols M_E and M_PI are not found during configuration

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#1258]
When configuring upstream NEST with OpenMP offloading flag enabled,

```
cmake -DCMAKE_CXX_FLAGS="-fopenmp -fopenmp-targets=nvptx64" -Dwith-python=OFF -DCMAKE_INSTALL_PREFIX=/tmp -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang /p/project/cjzam11/kitayama1/projects/nest-simulator/ -Dwith-gsl=OFF
```

math symbols, M_E and M_PI are not found. Configuring without the OpenMP offloading flag detects them both. How do I work around this?

**Comment by ikitayama** [comment]
Update: The LLVM's upstream is aware of this issue and they're working on it.

**Comment by heplesser** [comment]
@ikitayama This seems to be a problem with a very specific version of clang, which breaks all reasonable expectation to what symbols should be provided by headers. I just tested with Clang 8.0 provided through Homebrew for OSX and there the symbols are defined. I suggest to fix this with a local patch.

**Comment by ikitayama** [comment]
Indeed, I have patched locally for my offloading work with trunk Clang, but
upstream says they’ll fix, and given no other folks than myself interested
in GPU offloading let’s not touch the master at all.

**Comment by heplesser** [comment]
Closing this since it is an external problem and a work-around exists.
