### ISSUE TITLE
Unable to install nest

### ISSUE THREAD

**Issue by alex4200** [nest/nest-simulator#1259]
On Ubuntu 16.04.6 I am trying to install `nest` (checked out via `git clone`) via the command `cmake -DCMAKE_INSTALL_PREFIX:PATH=</install/path> </path/to/NEST/src>`. However, I see the following error:

```
CMake Error at cmake/ProcessOptions.cmake:412 (message):
  Your Cython version is too old.  Please install newer version (0.19.2+)
Call Stack (most recent call first):
  CMakeLists.txt:155 (nest_process_with_python)
```

while the version `0.23.4-0ubuntu5` of `cython` is installed. 

How to proceed?

**Comment by Silmathoron** [comment]
Can you show us which version of Python is detected by CMake?
Also check whether you don't have a system-wide Cython installed from apt and in that case uninstall it.
Eventually, check that ``which cython`` and ``cython -V`` give you the same version.

**Comment by alex4200** [comment]
`which cython` -> `/usr/bin/cython`

`cython -V`:

```
Traceback (most recent call last):
  File "/usr/bin/cython", line 7, in <module>
    from Cython.Compiler.Main import main
ModuleNotFoundError: No module named 'Cython'
```

Even after I removed and reinstalled `cython`.

**Comment by Silmathoron** [comment]
@alex4200 that's what I meant: you have a system-wide cython in /usr/bin
You need to uninstall it, then do a ``pip install --user cython`` (or ``pip3`` depending on which python version you're using) so that you are using the latest cython version with a local install associated to the correct python version.
Please also post the part of the CMake summary showing the Python version.

**Comment by alex4200** [comment]
I re-installed the python package `cython` in a virtualenv. But still I get 

```
Traceback (most recent call last):
  File "/usr/bin/cython", line 7, in <module>
    from Cython.Compiler.Main import main
ModuleNotFoundError: No module named 'Cython'
```

`which cython` points to the virtualenv location. 

Also there is no part of the CMake output showing any python references. Complete CMake output:

```
-- Host triple: x86_64-pc-linux
-- Target triple: x86_64-pc-linux
-- Could NOT find Readline (missing: READLINE_LIBRARY READLINE_INCLUDE_DIR) 
-- Could NOT find GSL (missing: GSL_INCLUDE_DIR GSL_LIBRARY) (found version "")
CMake Error at cmake/ProcessOptions.cmake:412 (message):
  Your Cython version is too old.  Please install newer version (0.19.2+)
Call Stack (most recent call first):
  CMakeLists.txt:155 (nest_process_with_python)


-- Configuring incomplete, errors occurred!
See also "/home/adietz/Work/20_BSP/SoftwareTests/CerebellumNestSP10Integration/nest-simulator/CMakeFiles/CMakeOutput.log".
See also "/home/adietz/Work/20_BSP/SoftwareTests/CerebellumNestSP10Integration/nest-simulator/CMakeFiles/CMakeError.log".
```

**Comment by Silmathoron** [comment]
@alex4200 you need to remove ``/usr/bin/cython``. This should have been done automatically when you uninstalled the system-wide cython though... how did you uninstall it?

**Comment by alex4200** [comment]
When I remove `/usr/bin/cython` then I have: 

which cython points to the virtualenv location.

```
$ cython --version
bash: /usr/bin/cython: No such file or directory
```

**Comment by Silmathoron** [comment]
did you reinstall cython locally after removing the system-wide cython? did you activate the virtualenv and are you running the command from the activated env?
This is a path issue, so worst case scenario you just have to add the proper cython bin to your path, but this should not be necessary.
Did you check that you could import cython from your Python interpreter?

**Comment by alex4200** [comment]
did you reinstall cython locally after removing the system-wide cython? 
- yes, but just with `pip`

did you activate the virtualenv and are you running the command from the activated env?
- yes

This is a path issue, so worst case scenario you just have to add the proper cython bin to your path, but this should not be necessary.
Did you check that you could import cython from your Python interpreter?
- yes, that works.

**Comment by Silmathoron** [comment]
Did you reboot?

**Comment by alex4200** [comment]
No not yet. I will try that later.

**Comment by alex4200** [comment]
I did made a reboot of the machine, and the `cmake` command gave the same error message. 

`cython --version` => 0.29.13
`which cython` => /home/adietz/Envs/cereb/bin/cython (the correct environment)
`cython` => works now, I get the help menu

But the `cmake` command still
```
-- Host triple: x86_64-pc-linux
-- Target triple: x86_64-pc-linux
-- Could NOT find Readline (missing: READLINE_LIBRARY READLINE_INCLUDE_DIR) 
-- Could NOT find GSL (missing: GSL_INCLUDE_DIR GSL_LIBRARY) (found version "")
CMake Error at cmake/ProcessOptions.cmake:412 (message):
  Your Cython version is too old.  Please install newer version (0.19.2+)
Call Stack (most recent call first):
  CMakeLists.txt:155 (nest_process_with_python)
```

It looks like that outside the environment no other `cython` is installed.

**Comment by jessica-mitchell** [comment]
Hi @alex4200 

I was able to recreate the error, and maybe found a solution - have you tried to remove the contents of the NEST build folder, and then run cmake? 

If I run cmake in the virtualenv with only a local pip install of cython, I had the same error as you, but after I emptied the build directory and recompiled NEST, cmake found the correct version.

Let us know if that works.

**Comment by alex4200** [comment]
I do not see a build folder anywhere. I can only assume its the folder `nest-simulator/CMakeFile`, and when I remove this folder (or rename it) and run `cmake` again, I get the same error. 

Maybe I am missing something?

**Comment by jessica-mitchell** [comment]
When you used git clone command  the directory for nest-simulator that is created is the _source_ directory.

Then you need a build directory: 

Create a build directory:

`mkdir nest-simulator-x.y.z-build`

**Change to the build directory:**

`cd nest-simulator-x.y.z-build`

**then run from that directory**

`cmake -DCMAKE_INSTALL_PREFIX:PATH=</install/path> </path/to/NEST/src>`


If you have not done this, then your source and build files are likely in the same directory, which is not a good idea.

I would actually recommend that you try our Ubuntu ppa of the latest release (NEST 2.18) - unless you need the master version for some reason. (This PPA is not yet available in the installation instructions but will be soon)

```
sudo add-apt-repository ppa:nest-simulator/nest
sudo apt-get update
sudo apt-install nest
```

With those commands you should be able to run 
`nest`  
OR 
```
python3  
import nest
``` 
 You should see the splash screen:
          ```
    -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: nest-2.18.0
 Built: Jul 12 2019 05:18:40

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.

```

**Comment by jessica-mitchell** [comment]
sorry I made a mistake typing
it's 
`sudo apt-get install nest`

**Comment by alex4200** [comment]
Well, to add the repository I needed to do 

`sudo apt-get install software-properties-common`

and then the command 

`sudo add-apt-repository ppa:nest-simulator/nest`

yields the following error:

```Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 11, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 27, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
```

I guess I am just unable to install `nest`...

**Comment by alex4200** [comment]
I needed to add a symbolic link. So the complete command chain:

```
sudo apt-get install software-properties-common
cd /usr/lib/python3/dist-packages/
sudo ln -s apt_pkg.cpython-{35m,36m}-x86_64-linux-gnu.so
sudo add-apt-repository ppa:nest-simulator/nest
sudo apt-get update
sudo apt-get install python3-dev
sudo apt-get install nest
```

**Comment by jessica-mitchell** [comment]
Ok great, do you now have a working version of nest?

**Comment by alex4200** [comment]
Hm, it looks like there is still a problem. `python -c "import nest"` returns 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nest'
```

**Comment by jessica-mitchell** [comment]
can you try python3?

**Comment by alex4200** [comment]
It is `python3`. I just tried explicitly with `python3`, same error.

**Comment by alex4200** [comment]
There is no `nest` folder in the python3 `site-packages` in the virtualenv.

**Comment by jessica-mitchell** [comment]
ok, that's because nest was installed with  apt-get so it will not be installed in the virtual env (sorry I should've mentioned this).

**Comment by alex4200** [comment]
Yes that was my thought too. 

But is there a way to use it from within a virtualenv? There should be...

**Comment by jessica-mitchell** [comment]
So i have taken a look to see if we can get nest in a virtualenv - and I have found a way - but I do not necessarily think this is an ideal option. I don't normally use virtualenv and there may be consequences I am unaware of. I am going to ask @terhorstd to see what he thinks.

I am following the instructions found here (https://askubuntu.com/questions/581648/install-package-into-virtualenv-using-apt-get) 
First we are going to _download_ the nest package rather than _install_
create a directory
```
mkdir /home/user/tmp_nest/
cd home/user/tmp_nest
apt-get download nest
```

This will download the .deb package to current directory
`dpkg -x nest_2.18.0-0~201907120510~ubuntu18.04.1_amd64.deb .`

If you type `ls` you will see you have usr/ directory and in there is _bin/_ _share/_ _lib/_  _include/_ folders

I then moved the files to the appropriate venv directory

```
mv /usr/lib/python3.6/dist-packages/* /home/user/virtenv/lib/python3.6/site-packages
mv /usr/bin/* /home/user/virtenv/bin/
mv /usr/include/* /home/user/virtenv/include/
```
I had to make a share directory in the virtenv
```
mkdir /home/user/virtenv/share
mv /usr/share/* /home/user/virtenv/share
```

when `which nest`
I got`  /home/user/virtenv/bin/nest`
and running python3
import nest worked

I had the virtualenv activated the whole time.

**Comment by alex4200** [comment]
Thanks a lot, that finally worked. Now I am able to import nest from within the virtualenv!

**Comment by jessica-mitchell** [comment]
Hi @alex4200 ,

I'm glad this solution worked for you. 
I have taken a bit deeper look into this, and want to explain what is actually happening here because, in this case, NEST is not fully encapsulated in the virtualenv. 
Basically, NEST is still using libraries from the system install (i.e., the virtualenv NEST won't work if the system install of NEST is uninstalled). 
Virtualenv  is a python environment and can only handle python dependencies. NEST has non-python dependencies, so there will always be some system dependencies.

Handling system and python dependencies in a single environment can be done, for example, with Conda. 

Your setup should still work, but you won't be able to create multiple virtual environments with different versions of nest.
