### ISSUE TITLE
couldn't install nest-simulator on OSX because of missing PYTHON_LIBRARIES etc.

### ISSUE THREAD

**Issue by ryo12882** [nest/nest-simulator#1264]
I tried to install nest-simulator on OSX. But I faced a problem and tried to solve for an hour but couldn't.
Could you tell me what to do?

`
cmake  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX:PATH=/Users/ryo/NEST/ /Users/ryo/NEST/nest-simulator/
`

got this

-- Host triple: x86_64-apple-darwin
-- Target triple: x86_64-apple-darwin
-- Found LTDL: /usr/local/lib/libltdl.dylib (found version "2.4.6") 
-- Found Readline: /usr/lib/libreadline.dylib (found version "4.2") 
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Found GSL: /usr/local/Cellar/gsl/2.5/include (found version "2.5") 
-- Found PythonInterp: /Users/ryo/.pyenv/shims/python (found version "3.6.8") 
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "3.6.8")
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 

But $PYTHON_LIBRARIES and $PYTHON_INCLUDE_DIRS are installed.
And I install libomp via brew.

Thank you for your time.

**Comment by tammoippen** [comment]
Hello,

`pyenv` makes discovering the python lib and include path difficult, apparently. Please have a look at the INSTALL file line 148ff on how to set the paths for cmake. For pyenv i guess everything is located under `$(pyenv root)/versions/3.6.8/[libs|includes]`.

**Comment by tammoippen** [comment]
Regarding OpenMP: apple `clang` and `clang++` do not support OpenMP. If you want omp in nest, you should go for `gcc`/`g++` compilers (also available via homebrew) or install the latest llvm (see this thread https://stackoverflow.com/questions/43555410/enable-openmp-support-in-clang-in-mac-os-x-sierra-mojave)

**Comment by ryo12882** [comment]
I add these arguments, install llvm and change to clang. And it finally works.
Thank you @tammoippen!
