### ISSUE TITLE
Errors by importing NEST (conda install) in 'jupyter notebook' on MacOSX

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#1265]
There are errors on MacOSX when using conda installed NEST in 'jupyter notebook'.
These errors are reproducible.
If you use NEST in ipython or python, these errors do not occur.
In NEST 2.18.0 the error is every time:
"Assertion failed: (out != NULL), function execute, file /usr/local/miniconda/conda-bld/nest-simulator_1562094389587/work/sli/sli_io.cc, line 422."

In NEST 2.16.0 the error is similar, but with a different line number.

#1210 seems to be the equal. But the solution doesn't work here.

**Comment by steffengraber** [comment]
Sorry, with 'ipython' there are the same errors.

**Comment by jougs** [comment]
The problem is most likely that SLI expects a full working stdout, which it might not get in this special case. I am not sure there is an easy way around this but am willing to investigate.

**Comment by heplesser** [comment]
Just for reference: I have just installed NEST (master@e4f6b3283) manually on my Mac under OSX  10.14.6 using GCC 9 etc from brew and a Miniconda installation with Python 3.7.3 and up-to-date IPython and Jupyter. Works fine from the command line, Python, IPython, Jupyter Notebook and Jupyter Lab. So the problem seems not to be with OSX, NEST or Python/Jupyter per se, but with the brew build.

**Comment by nosratullah** [comment]
I have the same problem wich cause me so many problems including using nest-server. I can use the nest in python itself (in an environment) but I cannot use it in ipython, jupyter notebook or on a local host.

**Comment by heplesser** [comment]
@jougs 
> The problem is most likely that SLI expects a full working stdout, which it might not get in this special case. I am not sure there is an easy way around this but am willing to investigate.

If I read the code correctly, the assertion is triggered while executing SLI's `str` function in [`StrSStreamFunction::execute()`](https://github.com/nest/nest-simulator/blob/ba8feb49570f1118e2896191ebae790e8feca3d8/sli/sli_io.cc#L422) when a dynamic cast fails. I suspect some subtle problems between C++ libraries behind the scenes here that cause the dynamic cast to fail.

**Comment by heplesser** [comment]
@steffengraber Could you try setting `export DYLD_PRINT_LIBRARIES=YES`, then run once `python -c "import nest"` (which I expect to work) and once `ipython -c "import nest"` (expected to crash with the failed assertion) and compare the libraries loaded. If both `libc++` and `libstdc++` are loaded in the `ipython` case, this could point to a cause; see also https://docs.brew.sh/C++-Standard-Libraries.

**Comment by steffengraber** [comment]
As far as I can see, `libstdc++` is not loaded in both cases.

**Comment by steffengraber** [comment]
Closed due to inactivity
