### ISSUE TITLE
nest insert noisy datatype

### ISSUE THREAD

**Issue by nosratullah** [nest/nest-simulator#1269]
I read about the noisy input to a neuron in the documantation. which is here:
`syn_dict_ex = {"weight": 1.2}
syn_dict_in = {"weight": -2.0}
nest.Connect([noise_ex], neuron, syn_spec=syn_dict_ex)
nest.Connect([noise_in], neuron, syn_spec=syn_dict_in)`
but  I get this error 
<img width="730" alt="Screen Shot 2019-08-16 at 18 36 10" src="https://user-images.githubusercontent.com/13776994/63173613-7c334a00-c055-11e9-9c0f-0b1fdb7822d2.png">

However I simply solve the problem by replacing this lines of codes. I think the problem involves datatype and stuff.
`noise_ex = nest.Create("poisson_generator")
noise_in = nest.Create("poisson_generator")
nest.SetStatus(noise_ex, {"rate": 80000.0})
nest.SetStatus(noise_in, {"rate": 15000.0})`

**Comment by stinebuu** [comment]
@nosratullah Thanks for reporting this! Just so I know I am looking the right place in the documentation, did you get your example [here](https://nest-simulator.readthedocs.io/en/latest/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.html#connecting-nodes-with-specific-connections)?

**Comment by nosratullah** [comment]
Thanks for responding. Yes, exactly.
