### ISSUE TITLE
How to install the nest simulator for Python3

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1288]
After following the Ubuntu/Debian installation instructions I can only `import nest` in Python 2.7 but not in Python 3.6/3.7. (If this is not the appropriate channel please point me to the right place)

EDIT: See my SO question https://stackoverflow.com/questions/57909894/how-to-install-nest-in-python3-on-ubuntu-18-04

**Comment by Helveg** [comment]
So, after struggling with some dual boot issues and having to reinstall Ubuntu I still run into an error during the MPI tests:

```
  Running test testWithMPI...
Traceback (most recent call last):
  File "/nest/2.18/lib/python3.6/site-packages/nest/tests/test_sp/mpitest_issue_578_sp.py", line 26, in <module>
    import nest
  File "/nest/2.18/lib/python3.6/site-packages/nest/__init__.py", line 26, in <module>
    from . import ll_api      # noqa
  File "/nest/2.18/lib/python3.6/site-packages/nest/ll_api.py", line 72, in <module>
Traceback (most recent call last):
  File "/nest/2.18/lib/python3.6/site-packages/nest/tests/test_sp/mpitest_issue_578_sp.py", line 26, in <module>
    import nest
  File "/nest/2.18/lib/python3.6/site-packages/nest/__init__.py", line 26, in <module>
    from . import ll_api      # noqa
  File "/nest/2.18/lib/python3.6/site-packages/nest/ll_api.py", line 72, in <module>
    from . import pynestkernel as kernel      # noqa
ImportError: dynamic module does not define init function (initpynestkernel)
    from . import pynestkernel as kernel      # noqa
ImportError: dynamic module does not define init function (initpynestkernel)
```

Steps:
1) Installed Ubuntu, with extra grub options `dis_ucode_ldr`, `nouveau.modeset=0` and `acpi_rev_override=5` to circumvene some booting/hardware issues
2) Downloaded nest2.18 tarball, unpacked
3) Installed dependencies replacing `python-*` packages with `python3-*`
4) `cmake -Dwith-python=3 -Dwith-mpi=ON -DCMAKE_INSTALL_PREFIX:PATH=/nest/2.18 /home/robin/Downloads/nest-simulator-2.18.0/`
5) `make`
6) `make install`
7) `make installcheck` (see Error)

I can in fact import nest into python3, but it doesn't seem to actually load anything?
```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nest
>>> dir(nest)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> nest.Create("model_name")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'nest' has no attribute 'Create'
```

**Comment by Silmathoron** [comment]
Hi @Helveg I'm surprised by your message:

- from the test, it looks like NEST in indeed installed and can be loaded by Python in ``/nest/2.18``
- from the import and the ``dir``, I would expect the folder to be empty and especially I would expect all tests to fail and not just those from MPI

Did you check that the folder contains all the expected files and especially that the lib folder is part of your ``LD_LIBRARY_PATH``?
Can you also check that their are no lingering ``python2.7`` folders in lib?

**Comment by Helveg** [comment]
@Silmathoron, it's a fresh Ubuntu install, so no python2.7 folder in lib. The `/nest/2.18/nest` folder is indeed empty as far as python code is involved.

**Comment by Helveg** [comment]
@Silmathoron So how about the MPI test error, last time you mentioned something about verifying the MPI install, how would I do that?

**Comment by Silmathoron** [comment]
@Helveg forget it, I forgot the tests passed in py2
What about now that you have fixed the environment variables?

> The /nest/2.18/nest folder is indeed empty as far as python code is involved.

Completely empty? Given your test message there should be at least ``ll_api.py``...

**Comment by Helveg** [comment]
> @Helveg forget it, I forgot the tests passed in py2

That was on a previous install of Ubuntu though.

> What about now that you have fixed the environment variables?

Now it correctly loads the nest module in python3, but the MPI test still fails with the same message.

> Completely empty? Given your test message there should be at least `ll_api.py`...

So my install folder is `/nest/2.18`, and from that folder I ran python3, that's why `import nest` resolved to `/nest/2.18/nest` before I fixed the env vars, but that's not the cause of the MPI error.

**Comment by Silmathoron** [comment]
Ok, we're going in all kinds of directions here... let's refocus!

Please do not run the ``import nest; dir(nest)`` from the install folder but from your home directory and tell me what it looks like.
It would also be helpful to have the output from:

- ``ls /nest/2.18/lib/python3.6/site-packages/nest/``
- ``echo $PYTHONPATH``
- ``echo $LD_LIBRARY_PATH``

**Comment by Helveg** [comment]
> Please do not run the `import nest; dir(nest)` from the install folder but from your home directory and tell me what it looks like.

There hasn't been an issue importing the nest module since about an hour ago when I added this line from the installation guide to `~/.bashrc`:
```
source </path/to/nest_install_dir>/bin/nest_vars.sh
```

The only standing issue at the moment are the failing MPI tests.

**Comment by Helveg** [comment]
```
robin@robin-ZenBook-UX533FN:/nest/2.18$ ls /nest/2.18/lib/python3.6/site-packages/nest/
hl_api.py       __init__.pyc  ll_api.pyc       pynestkernel.so  topology
import_libs.py  lib           __pycache__      raster_plot.py   visualization.py
__init__.py     ll_api.py     pynest-init.sli  tests            voltage_trace.py
robin@robin-ZenBook-UX533FN:~$ echo $PYTHONPATH
/nest/2.18/lib/python3.6/site-packages
robin@robin-ZenBook-UX533FN:~$ echo $LD_LIBRARY_PATH
```

**Comment by Helveg** [comment]
I think it's important to mention again that I have completely formatted my hard drive and reinstalled a fresh Ubuntu 18.04.3 this morning. The whole "first compiled to python2 where everything worked" context does not apply anymore, so I'd like to verify whether the MPI installation on this __new__ machine actually works.

**Comment by Silmathoron** [comment]
@Helveg so ``LD_LIBRARY_PATH`` is empty, right?
Could you set it to ``/nest/2.18/lib``?

To check your MPI install, run ``mpiexec -n 5 python -m mpi4py.bench helloworld``

**Comment by Helveg** [comment]
MPI seems to be working:
```
robin@robin-ZenBook-UX533FN:~$ mpiexec -n 5 python3 -m mpi4py.bench helloworld
Hello, World! I am process 0 of 5 on robin-ZenBook-UX533FN.
Hello, World! I am process 1 of 5 on robin-ZenBook-UX533FN.
Hello, World! I am process 2 of 5 on robin-ZenBook-UX533FN.
Hello, World! I am process 3 of 5 on robin-ZenBook-UX533FN.
Hello, World! I am process 4 of 5 on robin-ZenBook-UX533FN.
```

> EDIT2: btw, do you have only /nest/2.18/lib or is there alos a lib64 folder? (should not be but you never know...)

Nop, only lib, libnestutil and librandom

**Comment by Helveg** [comment]
I ran the tests again and the problem persists, same message, here are the reports (didn't notice that before, sorry)
[reports.zip](https://github.com/nest/nest-simulator/files/3610329/reports.zip)

**Comment by Silmathoron** [comment]
OK, this seems to be "proper" failures, and not an install bug.

I just reinstalled on my computer with MPI enabled and I confirm the failure of these two test. Please close this issue and reopen a new one regarding these MPI tests failures.
