### ISSUE TITLE
Review role and use of Events in connection creation and signal transmission

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#129]
We use `Event`s in NEST both during connection creation and during transmission of signals via connections. `Event`s are used differently in both cases, and different subsets of `Event` public functions cater to the different uses. This is not properly documented at present.

As an example, `e.get_sender().get_gid()` and `e.get_sender_gid()` will yield inconsistent results, even though one would expect them to yield the same result. In particular, `e.get_sender_gid()` will trigger an assertion (`sender_gid_>0` fails) when called from `handle_test_event()`.

The reason for this inconsistency is that Event objects are used differently during network construction and network simulation. 

During network construction, we send a pointer to a node of the sender node type. This is not, generally, a pointer to the actual sender: for senders on remote MPI processes, this pointer is not available. Instead, we send a pointer to a proxy node. No GID is set on that proxy node (proxy nodes always have GID 0). 

`send_test_event()` now sets only the `Node* sender_` field on the Event it sends (to `this`), but not the `sender_gid_`, since that is not consistently available (i.e., not for proxy neurons representing remote sources).

When delivering spikes, on the other hand, only the `sender_gid_` field is set in an Event, but not the `sender_`. This because a pointer to sender is not available for remote neurons and passing pointers to proxy neurons would not make sense at this point.

As a further twist, if the target is a recording device, connections will only be created from local sources (the connect mechanism takes care of this), whence the pointer returned by `e.get_sender()` will actually be a pointer to the real sender object (not a proxy), and `e.get_sender().get_gid()` will return the proper GID. `e.get_sender_gid()`, on the other hand, should be used only during spike delivery, not during connection creation.

**Comment by heplesser** [comment]
See also ticket 685 in the old trac,

**Comment by jessica-mitchell** [comment]
@heplesser apologies for leaving this one on the back burner so long. is this something that belongs in developer documentation? how up-to-date is the information, has much changed regarding how events are handled?

**Comment by heplesser** [comment]
@jessica-mitchell I fear this issue really needs more than just better documentation, rather a full code review and refactoring. I will change the title of the issue—it could probably a hackathon topic.

**Comment by terhorstd** [comment]
Is this actually an *issue*, or rather a project or discussion that should be continued somewhere else? What is the actual problem that needs to be solved here to close it?

I'd vote to close it.

**Comment by heplesser** [comment]
Similar to #556, this issue points at a large refactoring we should should consider to achieve cleaner and more maintainable code. As such, it would be a project of its own. To me, the main question is how we see issues: Should issues only represent relatively compact problems or tasks, or also be used to remind us of and collect discussions on larger changes? If we decided to use issues for relatively narrow scopes only, where would we then remind us about and organise discussion around larger efforts?
