### ISSUE TITLE
set/get conductance state

### ISSUE THREAD

**Issue by lepmik** [nest/nest-simulator#1290]
When using conductance based synapses and setting/getting the state of nodes one should also set/get the conductances i.e. `g_ex, g_in`.

**Comment by heplesser** [comment]
@lepmik Sorry for the very long silence! In the not-too-long run, we will support this by replacing hand-written code by NESTML-generated model code. Some models already allow conductance recording, e.g., `aeif_cond_alpha`.  Would you want to add it to the models that interest you based on the [code in aeif_cond_alpha](https://github.com/nest/nest-simulator/blob/aab21a8c4665c8643851eed05471f23307c2231c/models/aeif_cond_alpha.cpp#L66)?

**Comment by lepmik** [comment]
Hi! No problem. I was mainly thinking of a `set_state` function, recording is already implemented in the models I use.
