### ISSUE TITLE
nest-2.2.2 modeule : command not found

### ISSUE THREAD

**Issue by treestreamymw** [nest/nest-simulator#1291]
$ sudo bash ./compile-module.sh module-100725/
./compile-module.sh: line 5: module: command not found
./compile-module.sh: line 6: module: command not found
./compile-module.sh: line 7: module: command not found
current dir: /home/ymw/BCPNN-for-NEST222-MPI-master
Removing old build and bootstrap directories
Source dir: /home/ymw/BCPNN-for-NEST222-MPI-master/module-100725/
Bootstrap dir: /home/ymw/BCPNN-for-NEST222-MPI-master/bootstrap-module-100725/
Build dir: /home/ymw/BCPNN-for-NEST222-MPI-master/build-module-100725/
/home/ymw/BCPNN-for-NEST222-MPI-master
./compile-module.sh: line 44: /home/ymw/BCPNN-for-NEST222-MPI-master/bootstrap-module-100725//bootstrap.sh: Permission denied
Entering /home/ymw/BCPNN-for-NEST222-MPI-master/build-module-100725/
./compile-module.sh: line 55: /home/ymw/BCPNN-for-NEST222-MPI-master/bootstrap-module-100725//configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
It took 0 seconds

**Comment by ikitayama** [comment]
You seem to be using an old release of NEST, would you upgrade the code base up to the latest and see if that works?

**Comment by terhorstd** [comment]
Please open another issue if this issue persists with newer versions of NEST.
