### ISSUE TITLE
PEP8 tests fail on master after merge of #1277

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1293]
While all tests passed on Travis on PR #1277 (https://travis-ci.org/nest/nest-simulator/builds/582569300), the post-merge test on Travis failed (https://travis-ci.org/nest/nest-simulator/jobs/582851006).

The failure is due to PEP8 problems that seem to be caused by empty lines. It seems the merge introduced additional empty lines.

@lekshmideepu Any comments on how this happened and if one could somehow make Github to detect such problems in advance?

**Comment by lekshmideepu** [comment]
@heplesser Only difference I could see with both builds is the PEP8 check has been skipped in the [PR](https://travis-ci.org/nest/nest-simulator/jobs/582569301#L6828) and on the other hand this failed in the merge commit [build](https://travis-ci.org/nest/nest-simulator/jobs/582851006#L8304)

**Comment by Silmathoron** [comment]
Yep, there is this weird

    MSGBLD0305: Skip installcheck.

appearing [here](https://travis-ci.org/nest/nest-simulator/jobs/582569301#L6755)

**Comment by lekshmideepu** [comment]
it is [here](https://travis-ci.org/nest/nest-simulator/jobs/582851006#L7841) too

**Comment by lekshmideepu** [comment]
There was an [issue ](https://travis-ci.org/nest/nest-simulator/jobs/582569301#L1436)in retrieving changed files

**Comment by heplesser** [comment]
Strange! And in the PR build #3417.1, Travis detected problems with copyright headers [here](https://travis-ci.org/nest/nest-simulator/jobs/582569301#L1457) and still the tests pass.

@gtrensch Could you also take a look?

**Comment by clinssen** [comment]
I believe the issue with copyright headers failing, but the test succeeding, is fixed by https://github.com/clinssen/nest-simulator/commit/bb7d429e9ee7cab2432cec4c53b5b81a9cd66403. I still need to properly test this. I have been looking into the Travis CI suite recently as part of #1267, so I'll check out the problem with retrieving changed files as well.

**Comment by clinssen** [comment]
I replicated the command that was failing on Travis locally without a hitch:

```
curl "https://api.github.com/repos/nest/nest-simulator/pulls/1277/files" | jq '.[] | .filename'
```

I suspect this was just a fluke in Travis, the GitHub API, or the web in general. Sometimes things fail and you have to retry the request. Apparently we found an edge case where, if the request fails, the test passes while it should fail. I tried to restart the test on the Travis instance, but apparently getting the PR bits and bobs from the GitHub API no longer works after it is merged.

To address this issue, we should break up the pipes here to check intermediate return values: 

https://github.com/clinssen/nest-simulator/blob/4832e82e9d14879ec4a068ed404f62e7520222cf/extras/travis_build.sh#L169

@gtrensch, how's your bash-fu?

It would be great if the changes could be made against the branch in #1267; thanks!

**Comment by lekshmideepu** [comment]
@heplesser  I had contacted the Travis support team to know if by any chance the merge introduce any changes to the codebase. They confirmed that  *merge*s don't introduce any code changes.

**Comment by jessica-mitchell** [comment]
Closing, not solvable - Travis is informed about issue
