### ISSUE TITLE
Update gcc version in Travis CI

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1309]
While finalising my pull request #1069, I ran into a compiler bug in gcc. When specialising a class template in a different file than the generic class definition, an issue with namespace resolution can arise; see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56480 for more detail.

This requires gcc to be updated to version >= 7 (current being 5.4), because that is where the bug was first fixed. We presently already have a Travis CI stage dedicated to gcc 8.

Are there any preferences (or objections) to specific versions? gcc 9 is out but still seems to require adding a new PPA. The easiest solution would be to use gcc 8 everywhere. This also cuts the Travis CI runtime down a bit (as gcc 8 will no longer need to be a distinct step).

**Comment by heplesser** [comment]
I support @clinssen's suggestion to move to gcc 8, unless @lekshmideepu sees some significant difficulty in doing so. Do we provide any information in our installation documentation about which compiler versions we test with, @jessica-mitchell?

**Comment by lekshmideepu** [comment]
Usually the MacOS image is always updated with latest versions of compilers. I like the idea of having this one build to test against the latest available compiler version on the Travis MacOS image. i.e. GNU 9.2.  But I don't have any objection to use consistent GCC (GCC8) check for all builds.
