### ISSUE TITLE
Sunsetting Python 2

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1313]
Python 2 will officially reach end-of-life on Jan 1st, 2020 (https://www.python.org/doc/sunset-python-2/). We will simultaneously end Python 2 support in NEST Simulator. This involves:

- [x] Remove the Travis stage for Py2
- [x] Remove the Python2 version from Travis OsX build and add a Python3 version instead
        ↪ done in #1335/#1325. 
- [x] Remove `__future__` imports, switches and checks for Py2/3 in `PyNEST/examples/tests`
- [x] Remove the cmake code for switching between Py2/3
- [x] Add a cmake check that ensures that Py3 is available
- [x] Update installation instructions
- [x] Update example iPython notebooks

Will be updated separately (see https://github.com/nest/nest-simulator/issues/1511#issuecomment-616728677 / #1524):
~~- [ ] Update microcircuit documentation ``doc/microcircuit/index.rst``~~
~~- [ ] Update ``examples/nest/Potjans_2014/README.txt``~~

**Comment by heplesser** [comment]
@clinssen This will apply once the nest-3 branch is merged, correct?

**Comment by terhorstd** [comment]
I set this priority high, since many other things depend on this.

**Comment by apeyser** [comment]
It's fine not to change this -- it doesn't break anything to have the py2 checks in, it's just the maintenance hassle.

**Comment by clinssen** [comment]
@steffengraber will check whether orphaned files in `extras/help_generator` (that invoke Py2) can be removed altogether rather than updated.

**Comment by steffengraber** [comment]
@clinssen The following files are not required and can be deleted:
- examples.sh
- make-slider.sh
- webdoc.py

Hope this helps.
In the medium term the whole thing could be replaced by the "User documentation extractor" #1355

**Comment by jougs** [comment]
ping!
