### ISSUE TITLE
PyNN support for NEST 3.0

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1320]
@jstapmanns: This is mainly a tracker issue for the [NEST-3 project](https://github.com/nest/nest-simulator/projects/12) on GitHub, so we don't forget anything important before the release.

You are invited to document any work here and/or link to pull requests and issues against PyNN.

**Comment by Artric** [comment]
Good evening Jougs, Please I need to install NEST on ubuntu 16.04. I have already installed ubuntu on my virtual machine and now I need NEST to be installed and PyNN running as well.
Please I will be expecting your answer and as any suggestions or guidelines will be welcomed.

**Comment by jougs** [comment]
@Artric: Your questions can likely be solved by following the installation instructions for [PyNN](http://neuralensemble.org/docs/PyNN/installation.html) and [NEST](https://nest-simulator.readthedocs.io/en/latest/installation/). Hijacking an unrelated issue on GitHub is not the right way to ask these kind of questions.

If you struggle with the instructions, you can subscribe to the [NEST User Mailing List](https://www.nest-simulator.org/community/) and post a detailed log of what you already did and what was the outcome of that and people will try to help you.

**Comment by jougs** [comment]
@jasperalbers, @hakonsbm: can you please quickly add some information about the current status to this issue? Thanks!

**Comment by jougs** [comment]
@clinssen: could you please give us a quick update on your recent checks?

**Comment by clinssen** [comment]
Hi! I am still working on this; making this update requires some understanding (reverse engineering) of the PyNN code, so it's not a completely trivial exercise. I met Andrew this morning in the HBP T5.3 coordination meeting, and we concluded that we ought to have a meeting between the two of us to speak through the technical details. It stays at the top of my priority list.

**Comment by clinssen** [comment]
See: https://github.com/NeuralEnsemble/PyNN/pull/718

**Comment by stinebuu** [comment]
Merged into PyNN with [NeuralEnsample/PyNN#724](https://github.com/NeuralEnsemble/PyNN/pull/724), still not released.

**Comment by stinebuu** [comment]
Looks like the newest release of PyNN supports NEST 3.1: http://neuralensemble.org/docs/PyNN/releases/0.10.0.html I am thus closing this.
