### ISSUE TITLE
debian/ in master and nest-3 branches

### ISSUE THREAD

**Issue by alexmyczko** [nest/nest-simulator#1321]
let me suggest to drop all debian/ completely and make it the packagers work instead of shipping a heavily outdated/no more working version.

**Comment by jougs** [comment]
@alexmyczko: does your suggestion imply your willingness to take over maintainership of the package in debian?

We think that it would be good if you could join one of the next [Open NEST Developer Video Conferences](https://github.com/nest/nest-simulator/wiki/Open-NEST-Developer-Video-Conference) in order to have a proper discussion about this.

**Comment by alexmyczko** [comment]
@jougs more like, one can't take over maintainership of a package, if it's not even there yet?

following links give me empty results
https://packages.debian.org/search?keywords=nest
https://packages.debian.org/search?keywords=nest-simulator

however i've seen some other people provide binaries:
https://repology.org/project/nest/versions (not debian based)

i might be interested, since i have a building package:
http://phd-sid.ethz.ch/debian/nest/

thanks for the tip on video conference, do you also use irc (internet relay chat) for development/users?

**Comment by jougs** [comment]
I meant of course if you would be willing to be the maintainer, once a package exists. We will discuss this topic internally next Monday and the VC might be a good forum to get things going further.

We don't currently have an IRC channel or such. Most discussions happen either here on GitHub, during our open VC or on the public mailing list.

**Comment by alexmyczko** [comment]
what was the outcome of the discussion?

**Comment by jougs** [comment]
Our current take on it is that since we provide the [PPA for Ubuntu](https://launchpad.net/~nest-simulator/+archive/ubuntu/nest), there is not a lot of pressure to also get it into Debian. If someone is willing to do that and maintain it, we're not against that.

**Comment by jougs** [comment]
I'm closing this now. Feel free to come back in case you want to become the maintainer of an official nest package in Debian.

**Comment by steffengraber** [comment]
@jougs Didn't you want to close the issue?

**Comment by jougs** [comment]
@steffengraber: Yes. Closing!
