### ISSUE TITLE
Update to Python 3 for Osx tests on Travis?

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#1325]
For our Osx tests in Travis, we are using Python 2.7, I think it comes from [here](https://github.com/nest/nest-simulator/blob/master/extras/travis_build.sh#L60). Is there a special reason for this? I was a bit surprised seeing as we have Python 3.6.7 as default.

This will be solved with #1313, but I am currently removing Python 2 testing from Travis for the nest-3 branch, and I thought it might be good to have master test with Python 3 for Osx.

**Comment by lekshmideepu** [comment]
@stinebuu  System python version for OSX images in Travis was only Python2 .

**Comment by stinebuu** [comment]
@lekshmideepu ok! I see that it is not that long ago since #1183 was merged, so then this might still be the case.

**Comment by Silmathoron** [comment]
@stinebuu I think they have support for Py3 now https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems

**Comment by steffengraber** [comment]
... or you can use Hombrew and install python3, if needed.
https://docs.travis-ci.com/user/reference/osx/#homebrew

**Comment by lekshmideepu** [comment]
@stinebuu  I am currently working on a  PR using Python 3 on OSX

**Comment by lekshmideepu** [comment]
Just created #1335

**Comment by jougs** [comment]
This has been resolved by the merge of #1335.
