### ISSUE TITLE
Hike CMake version requirement and use more modern library detection techniques?

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1326]
We currently require CMake Version 3.1 or later, while the current CMake version is 3.15. With version 3.9, CMake introduced improved OpenMP detection, with further improvements for macOS (where OpenMP is more demanding than elsewhere) in version 3.12, see https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html and https://iscinumpy.gitlab.io/post/omp-on-high-sierra/. 

Would there be any objections to hike our CMake requirement to at least version 3.12 and revise test to use more modern approaches? 

@ikitayama @jarsi @stinebuu Would you see any problems on the systems you are working on?

**Comment by ikitayama** [comment]
I'm using CMake version 3.15.3 in a programming environment for FUGAKU, and
OpenMP is discovered with -Dwith-openmp=-Kopenmp
without an issue so please go ahead if no one objects.

**Comment by jarsi** [comment]
All Juelich systems I have access to have cmake version 3.14.0.
Blaustein has version 3.5.2. Blaustein is currently in a maintenance phase and installation of newer packages is planned. Furthermore most users use conda environments where cmake is installed via conda.

**Comment by steffengraber** [comment]
Standard cmake version in Ubuntu Bionic (18.04 LTS) is 3.10.2.  To build NEST 3.0 from source (no conda installation) I had to install cmake via pip. With this, the latest version 3.15.3 was installed.

**Comment by heplesser** [comment]
@steffengraber I assume installing a newer cmake via pip is reasonably straightforward, so as long as we document it properly, would this be feasible for Ubuntu users? The alternative would be to reduce the requirement to 3.10 and tell macOS users that they need to have at least 3.12 if they want to compile with Apple Clang and OpenMP. The latter affects probably fewer users than Ubuntu 18.04 LTS.

**Comment by steffengraber** [comment]
@heplesser I rather consider macOS as the exception and would adapt the documentation for it.  Our documentation for macOS says to install cmake with homebrew. This should be the latest version anyway. 

Or is it possible to set the requirement for version 3.12 in cmake for macOS only?
