### ISSUE TITLE
AttributeError: module 'nest' has no attribute 'll_api

### ISSUE THREAD

**Issue by shirleyatgithub** [nest/nest-simulator#1334]
File "brunel_alpha_evolution_strategies.py", line 181, in LambertWm1
    nest.ll_api.sli_push(x)
AttributeError: module 'nest' has no attribute 'll_api

what might be the solution

**Comment by BSVogler** [comment]
I found no information on the `ll_api` but according to the docs the calls should work on the `nest` object. And in fact replacing calls like `nest.ll_api.sli_pop()` with `nest.sli_pop()` works. So maybe [the documentation](https://nest-simulator.readthedocs.io/en/latest/examples/brunel_alpha_evolution_strategies.html) with this file should be updated?

**Comment by jessica-mitchell** [comment]
Which version of NEST are you using @shirleyatgithub ?
the ll_api  is required for  2.18. Earlier versions did not have this construct.

**Comment by BSVogler** [comment]
Version 2.16 is still listed as the latest release in the docs though 2.18 is released. So I think the [installation doc page ](https://nest-simulator.readthedocs.io/en/latest/download.html) should be updated.

**Comment by jessica-mitchell** [comment]
Yep @BSVogler you're absolutely correct, and this update was stagnating in review phase for far too long. The documentatio now has this info. 
sorry for the long delay
