### ISSUE TITLE
Version is returned as a hash instead of a human readable string in pynest and sli

### ISSUE THREAD

**Issue by morales-gregorio** [nest/nest-simulator#1347]
Hello there!

I am using the following setups:
* Conda installed version 2.18.0 in my personal computer,
* Source installled version (2.16.0?, I cannot find out actually) in the cluster.

My problem is that when I try to retrieve the version number I only get a hash such that:
```
$ nest
```
```
              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: HEAD@2d5dfde
 Built: Nov 20 2019 08:34:11

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'help' to get more information.
 Type 'quit' or press CTRL-D to quit.
```
or
```
$ nest --version
```
```
NEST version HEAD@2d5dfde, built on Nov 20 2019 08:34:11 for x86_64-pc-linux
Copyright (C) 2004 The NEST Initiative
```

Same thing happens when using pynest:
```
>>> nest.version()
```
```
'NEST HEAD@2d5dfde'
```

A similar hash (but with a different sequence) comes out when I try the same with the compiled version in the cluster.

I believe that @rgutzen @AlexVanMeegen  @jarsi experiences similar issues, where it might have even worked for some of them. Maybe they can comment their details of when it was working.

PS As a side note I get inconsistent strings when I call `nest --version` and pynest `nest.version()`. Not sure how issue #1134 was settled, was this agreed upon?

**Comment by clinssen** [comment]
If you download NEST from https://github.com/nest/nest-simulator/releases then the version string returned should be "2.18" (or alike). But when NEST Simulator is obtained by cloning from git, a hash is returned corresponding to the latest commit. This is to distinguish it from official releases: although the master branch still looks a lot like 2.18, there have been changes that distinguish it from the official 2.18 release. We cannot do a release after every commit, so we went with the hash solution.

To read our design discussion about this, please see #1134 (as you already mentioned) and #1223.

In case the 2.18 docker image is returning the hash string instead of "2.18", this is a bug and should be fixed.

**Comment by morales-gregorio** [comment]
This makes sense to me when cloning from Github, which is the case in my cluster version. However, I would still argue in favor of stating something like `master@2hj24j, ahead of 2.18.0`. Or something that indicates the user that his/her version is not the official release, otherwise the user is confused by the commit hash. Maybe there is some standard for this, I don't know.

As for the conda release, I installed it from conda-forge and I indeed still get a hash. Even if I specify that I want the 2.18.0 release in the installation:
```
$ conda install -c conda-forge nest-simulator=2.18.0
...
>>> nest.version()
'NEST HEAD@2d5dfde'
```
This however works properly for version 2.16.0
```
$ conda install -c conda-forge nest-simulator=2.16.0
...
>>> nest.version()
'NEST 2.16.0'
```

**Comment by clinssen** [comment]
cc @steffengraber

**Comment by jougs** [comment]
@terhorstd

**Comment by steffengraber** [comment]
Hi @morales-gregorio 

Thanks for figuring that out.
The conda packages are built from the prefabricated `.tar.gz` packages. This happens in the context of the `conda-forge` `nest-simulator-feedstock` repository (https://github.com/conda-forge/nest-simulator-feedstock).
HEAD@2d5dfde definitely refers to a commit from it.
Why NEST now uses this information as its own version number, I need to investigate.

**Comment by steffengraber** [comment]
This is not only a problem of the conda package. If you create a git repository (`git init`), then make a first commit and  download the file (v2.18.0.tar.gz or master.tar.gz), extract it into a folder in the repository and install it, the NEST version number will be the current branch and the number of the last commit.

**Comment by steffengraber** [comment]
Just for the sake of completeness. The conda package has been patched and now shows the correct version number. @morales-gregorio

**Comment by morales-gregorio** [comment]
Thanks!
