### ISSUE TITLE
Nest install - add-apt-repository fails

### ISSUE THREAD

**Issue by mgiugliano** [nest/nest-simulator#1349]
On Debian, the command indicated in the documentation:

```sudo add-apt-repository ppa:nest-simulator/nest```

fails, returning the error:

gpg: keybox '/tmp/tmp2gyoggo5/pubring.gpg' created
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/tmp2gyoggo5/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr

Moreover, the command add-apt-repository was not immediately available but it had to be first added by 

```sudo apt-get install software-properties-common```

**Comment by steffengraber** [comment]
Hi @mgiugliano 

The Ubuntu ppa packages are initially intended for Ubuntu. We are working on packages to be used for Debian and Ubuntu.
Nevertheless the packages can be used under Debian with a little more effort. 

```
sudo apt install devscripts build-essential software-properties-common dpkg-dev
sudo add-apt-repository --enable-source ppa:nest-simulator/nest
```

This will create a new apt repository entry in` /etc/apt/sources.list.d/pogo-dev-ubuntu-stable-disco.list`.
Disable the binary package repository in the file (comment it out).
Next, you need to import the PPA GPG key and rebuild the packacge

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CF7539642ABD23CBCA8D487F0B8B6C5EC02D7DD
sudo apt update
sudo apt source --build nest
```

If there are dependencies missing, apt will tell you. Please install them.
After the rebuild, there is an debian ready package. Install it with 

`sudo dpkg --install nest_2.18.0-0~201911260924~ubuntu20.04.1_amd64.deb
`
Test it:
```

python3
>>>import nest
```
Of course you have to adapt names and paths to your system.

@jessica-mitchell please note this for the documentation

**Comment by steffengraber** [comment]
@sarakonradi  please note this for the documentation
