### ISSUE TITLE
Connect all-to-all with ommiting zero weights?

### ISSUE THREAD

**Issue by pkoprinkova** [nest/nest-simulator#1353]
I was wandering what if I have generated sparse connectivity matrix W and use it to connect two populations of neurons at once? I am using connect all-to-all but with non-sparse matrix having zeros for missing connections now.

**Comment by alberto-antonietti** [comment]
You could convert your matrix into two lists/arrays of source and target GIDs, then omitting the zero-weights connections, and then call a `nest.Connect `passing the two lists/arrays with `one-to-one` connectivity.

**Comment by pkoprinkova** [comment]
Thank you very much!

    On Monday, December 2, 2019, 11:32:15 AM GMT+2, Alberto Antonietti <notifications@github.com> wrote:  
 
 
You could convert your matrix into two lists/arrays of source and target GIDs, then omitting the zero-weights connections, and then call a nest.Connect passing the two lists/arrays with one-to-one connectivity.

**Comment by jougs** [comment]
@alberto-antonietti: Thanks for pointing out this useful workaround!
@jessica-mitchell: Probably this method for connecting sparse matrices in an efficient manner should be added to the guide for connection management together with an example. I leave this open, so you can contact the people here to request further information and examples if you need support.

**Comment by pkoprinkova** [comment]
Dear NEST support,
We've tried to proceed in the following way:
1. Create array of indexes of in and out neuron populations that have to be connected one-by-one, e.g.:in_indexdes=[0, 0,..., 1, 2,..., N, N,...]out_indexes=[0, 1,..., 5, 6,...., M, M,...]
2. Call: nest.connect(pop1[in_indexes],pop2[out_indexes],'one-by-one',w...). Here pop1 and pop2 are populations of N and M neurons respectively and w is a vector of weights.

Unfortunately this did not work obviously because the object "neurons population" can't be access in such manner. The error massage says:
"Only integer arrays with one element can be converted to an index"
So it is obvious that we should iterate over idexes (that will slow the code) or there is need to designe connectivity routine using sparse matrices.
Best,Petia

    On Wednesday, December 11, 2019, 8:58:52 PM GMT+2, Jochen Martin Eppler <notifications@github.com> wrote:  
 
 
@alberto-antonietti: Thanks for pointing out this useful workaround!
@jessica-mitchell: Probably this method for connecting sparse matrices in an efficient manner should be added to the guide for connection management together with an example. I leave this open, so you can contact the people here to request further information and examples if you need support.

**Comment by alberto-antonietti** [comment]
I suggest converting neuron tuples into arrays. You can try something like:

```
import nest
import numpy as np

# Create pre- and post-synaptic neurons
PRE=nest.Create("iaf_cond_exp",100)
POST=nest.Create("iaf_cond_exp",200)
# Define the indexes of the couples of pre- and post-synaptic neurons that you
# want to connect
pre_index = [0, 77, 33, 1, 40]
post_index = [2, 2, 2, 99, 189]
PRE_arr = np.array(PRE)
POST_arr = np.array(POST)
nest.Connect(PRE_arr[pre_index],POST_arr[post_index],'one_to_one')

# You can check what connection you have created between PRE and POST
print(nest.GetConnections(PRE,POST))
```

**Comment by jougs** [comment]
@stinebuu, @hakonsbm: Can you please check in how far indexing NodeCollections in this way could be supported in NEST 3? I think this is an interesting use case.

**Comment by pkoprinkova** [comment]
Thank you very much. So we have to convert neuron populations first while we tried to connect PRE[pre_index] and POST[post_index] directly.

   On Thursday, December 12, 2019, 5:05:15 PM GMT+2, Alberto Antonietti <notifications@github.com> wrote:  
 
 
I suggest converting neuron tuples into arrays. You can try something like:
import nest
import numpy as np

# Create pre- and post-synaptic neurons
PRE=nest.Create("iaf_cond_exp",100)
POST=nest.Create("iaf_cond_exp",200)
# Define the indexes of the couples of pre- and post-synaptic neurons that you
# want to connect
pre_index = [0, 77, 33, 1, 40]
post_index = [2, 2, 2, 99, 189]
PRE_arr = np.array(PRE)
POST_arr = np.array(POST)
nest.Connect(PRE_arr[pre_index],POST_arr[post_index],'one_to_one')

# You can check what connection you have created between PRE and POST
print(nest.GetConnections(PRE,POST))

**Comment by pkoprinkova** [comment]
We have instlalled NEST 2.18 I think. Probably we have to upgrade.

    On Thursday, December 12, 2019, 5:07:57 PM GMT+2, Jochen Martin Eppler <notifications@github.com> wrote:  
 
 
@stinebuu, @hakonsbm: Can you please check in how far indexing NodeCollections in this way could be supported in NEST 3? I think this is an interesting use case.

**Comment by jougs** [comment]
@pkoprinkova: NEST 3 is not out yet, so no need to upgrade just yet.

However, as the representation of nodes in NEST 3 will change from tuples to a more efficient object (called `NodeCollection`) it might be possible to also include your suggestion for indexing.

**Comment by pkoprinkova** [comment]
We've tried last suggestions. However it appears too complicated to convert the lists to arrays since afterwards they have to be converted again into lists in order to collect spikes via spike detectors etc.
I think that an option to use sparse connectivity matrix or a matrix having NaN elements would be helpful in future.
Best,Petia

    On Friday, December 13, 2019, 10:31:18 AM GMT+2, Jochen Martin Eppler <notifications@github.com> wrote:  
 
 
@pkoprinkova: NEST 3 is not out yet, so no need to upgrade just yet.

However, as the representation of nodes in NEST 3 will change from tuples to a more efficient object (called NodeCollection) it might be possible to also include your suggestion for indexing.

**Comment by alberto-antonietti** [comment]
You can keep both tuple variables (PRE and POST) and numpy array variables (PRE_arr and POST_arr) and use the ones that you need.

Otherwise, you can avoid generating additional array variables and call np.array() directly inside the `nest.Connect` function (`nest.Connect(np.array(PRE)[pre_index], np.array(POST)[post_index],"one_to_one")`). In this way, you can do the connect, but you still have tuple variables PRE and POST.

**Comment by pkoprinkova** [comment]
Thank you. We will implement the last decision.
 

    On Friday, December 13, 2019, 5:45:21 PM GMT+2, Alberto Antonietti <notifications@github.com> wrote:  
 
 
You can keep both tuple variables (PRE and POST) and numpy array variables (PRE_arr and POST_arr) and use the ones that you need.

Otherwise, you can avoid generating additional array variables and call np.array() directly inside the nest.Connect function (nest.Connect(np.array(PRE)[pre_index], np.array(POST)[post_index],"one_to_one")). In this way, you can do the connect, but you still have tuple variables PRE and POST.

**Comment by sarakonradi** [comment]
After discussing this with @hakonsbm, we thought that the "NEST 3.0: What's new?" guide needs an array indexing example, the way we describe NodeCollection slicing and indexing. #1485 contains some examples on how to use array indexing.

@hakonsbm suggested that there should also be an example on how to connect sparse matrices using array indexing. This could be added to Connection Management, as suggested by @jougs.

**Comment by Silmathoron** [comment]
@sarakonradi there are currently some issues with slicing and ``Connect`` that need to be resolved so I would suggest to postpone this until a decision is made on #1539 and #1563.

cc @heplesser

**Comment by stinebuu** [comment]
This is fixed, but needs documentation and some tests. @hakonsbm is responsible.

**Comment by hakonsbm** [comment]
Can also try to see if it's possible to implement `numpy.ma.MaskedArray` as an argument to `connect_arrays()`.
