### ISSUE TITLE
Multi-area model fails with NEST 3 when using more than 40 nodes

### ISSUE THREAD

**Issue by jarsi** [nest/nest-simulator#1357]
Hi all,
I am carrying out a strong scaling experiment of the [multi-area model](https://github.com/INM-6/multi-area-model) on JURECA using NEST 3. I use 6 MPI processes per node and 4 threads per MPI process. I start the experiment on 16 nodes and increase the number of nodes in steps of 4.  The wall-time is set to 1 hour, I use jemalloc as the memory allocator.

This is the NEST3 friendly [multi-area model](https://github.com/jarsi/multi-area-model/tree/benchmarking_nest3) I used. The NEST version is NEST3 @ 716b5056cc770a819bf2f22c98b4ed40fc62283a.

Until 40 nodes everything works nicely and the simulations succeed. Unfortunately I am not able to use more than 40 nodes. The simulations don't produce any error nor do they fail because of any obvious reason. They get killed after they hit the time limit. I have attached the output and error files.

I have observed 2 scenarios. Either the last message is something like (see attached file da940b935e7103aae9b435bb618d8c88.7795603.o.txt):
```
Dec 04 15:33:10 NodeManager::prepare_nodes [Info]: 
    Preparing 14257 nodes for simulation.
```
or (see attached file 9cf686f9c71f97210ff964fc074e13bd.7795596.o.txt)
```
Created cortico-cortical connections in 36.29 seconds.
```
@heplesser has hypothesized that this might be something due to MPI communication, with some process waiting for other processes who are not sending.

> A stale communication would fit with the sudden transition from decent scaling to massive delays. Just some idea on what could go wrong and cause such a sync failure for large numbers of processes
> 
> - no spikes at all during a communication interval on some process
> - a population with no nodes on a given VP, or a synapse type with no connections on a VP

Before we start digging deep into the code, I think it is important that someone else first reproduces this behavior.

[da940b935e7103aae9b435bb618d8c88.7795603.e.txt](https://github.com/nest/nest-simulator/files/3927330/da940b935e7103aae9b435bb618d8c88.7795603.e.txt)
[da940b935e7103aae9b435bb618d8c88.7795603.o.txt](https://github.com/nest/nest-simulator/files/3927331/da940b935e7103aae9b435bb618d8c88.7795603.o.txt)
[9cf686f9c71f97210ff964fc074e13bd.7795596.e.txt](https://github.com/nest/nest-simulator/files/3927332/9cf686f9c71f97210ff964fc074e13bd.7795596.e.txt)
[9cf686f9c71f97210ff964fc074e13bd.7795596.o.txt](https://github.com/nest/nest-simulator/files/3927333/9cf686f9c71f97210ff964fc074e13bd.7795596.o.txt)

**Comment by jarsi** [comment]
Just a short update.

In a related experiment I am profiling the performance of the multi-area model using NEST 2.14 on JURECA. The setup is identical to the one in the NEST3 scalings described above.

So far I have tried to go up to 160 nodes, starting at 12. Here I also move forward in steps of 4 nodes. I have observed similar problems as with NEST 3, but starting at higher numbers of nodes.
The numbers of nodes which fail due to timeout are:

* 112
* 132
* 148
* 152
* 156 

[0f82ec306d3c859108d53513fa32f4af.7798198.e.txt](https://github.com/nest/nest-simulator/files/3931346/0f82ec306d3c859108d53513fa32f4af.7798198.e.txt)
[0f82ec306d3c859108d53513fa32f4af.7798198.o.txt](https://github.com/nest/nest-simulator/files/3931347/0f82ec306d3c859108d53513fa32f4af.7798198.o.txt)

**Comment by jarsi** [comment]
Hi, another update. This does not seem to be a NEST problem, but rather a problem of the newly installed softwarestack on JURECA. Manually loading the older softwarestack magically makes this problem go away.

**Comment by stinebuu** [comment]
Hi! I have now run a strong scale Multi-Area model benchmark on Piz Daint on 32, 48, 64, 80, 92, 112, 128 nodes with 6 mpi processes per node and 6 threads per mpi process, and they all go through. But it is still strange that there are problems with some software stacks, isn't it?

The NEST 3.0 version I used is 47a9175e4.

**Comment by stinebuu** [comment]
@jarsi Do you know if this is still a problem?

**Comment by jarsi** [comment]
I haven't had any issues since. Maybe @jasperalbers has some more insights as he has also run a couple of benchmarks. If not I would consider this as solved. Or more like disappeared...

**Comment by jasperalbers** [comment]
@jarsi @stinebuu  I have carried out several benchmarks of the Multi Area Model on JURECA, including runs with 100+ nodes, and haven’t run into a similar issue.

**Comment by stinebuu** [comment]
@jarsi @jasperalbers Ok, good (and mysterious)! I will close this, feel free to open it again if you run into the same problems.
