### ISSUE TITLE
Refactor model registration in modules other than modelsmodule

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1359]
@clinssen Now that #1069 is merged, could you check if other modules (precise, examples/mymodule) should be refactored as well?

**Comment by clinssen** [comment]
Thanks for bringing this to my attention. When was the last time that MyModule was built? `libnestutil/iterator_pair.h` is missing from `libnestutil/CMakeLists.txt` (and required by MyModule, thus failing the build). There are some further include errors after fixing this. Could someone reproduce? (Do we want the libnestutil .h files in `build-dir/include/libnestutil` or in `build-dir/include`?)

**Comment by clinssen** [comment]
N.B. `register_connection_model()` is only used in modelsmodule and MyModule, not in precisemodule or elsewhere as far as I could see.
