### ISSUE TITLE
SetKernelStatus positional arguments error - bug?

### ISSUE THREAD

**Issue by oscr104** [nest/nest-simulator#1369]
I am trying to run simulations with non-default scheduling parameters, and so am setting the resolution to a lower value as per www.nest-simulator.org/scheduling-and-simulation-flow/

the first lines of my script import other modules, then import nest, then uses the SetKernelStatus command to specify a non-default resolution (using the exact line from the above documentation link):

import nest
nest.SetKernelStatus('resolution', 0.01)
import nest.topology as topp
nest.set_verbosity("M_WARNING")

This results in the following error message after nest initiates:

Traceback (most recent call last):
  File "lc_mods.py", line 13, in <module>
    nest.SetKernelStatus('resolution', 0.1)
  File "/home/nd17878/anaconda3/envs/nestenv/lib/python3.7/site-packages/nest/ll_api.py", line 246, in stack_checker_func
    return f(*args, **kwargs)
TypeError: SetKernelStatus() takes 1 positional argument but 2 were given

Is this a bug, or am I getting something wrong here?

Code is running in a conda environment usign python3, on Ubuntu 16.04 machine.

**Comment by morales-gregorio** [comment]
In the newer Nest versions (which I assume you are using) the SetKernelStatus takes in a dictionary of the keywords. 
```
import nest
nest.SetKernelStatus({'resolution': 0.01})
```
The documentation seems to be outdated. In the newer version of the documentation you also have the same error (https://nest-simulator.readthedocs.io/en/latest/guides/running_simulations.html). But there is a new example setting the random seeds that should work proprerly.

**Comment by oscr104** [comment]
Brilliant. Thanks for the answer, it fixed the issue
