### ISSUE TITLE
Multimeter behaviour after changing interval

### ISSUE THREAD

**Issue by oscr104** [nest/nest-simulator#1378]
Attempting to run multiple neuron simulations using default hodgkin huxley neurons, connected to a multimeter to record Vm.  I tried to change the interval parameter for the multimeter, to get a better resolution readout of spike shape, however this seems to effect the de-interleaving process, and ends up resulting in bizarre traces where occasionally the de-interleaving seems to have worked and sometimes not.

This is visible by running the below code with the multimeter interval as either

"interval": 1.   # default value, plots fine

or

"interval": 0.1  # when zooming in on individual action potential, its obvious that interleaving has failed

Has anyone else encountered this issue? 

import nest
import nest.topology as topp
import pylab
import numpy as np
import pandas as pd
import random
import LC_modfuncs as LC_mf
import matplotlib.pyplot as plt

# functions

def modgen(i_e, neu_num,gj_w, gj_prop):
        #set params & initialise neurons
        lc_dict = {"I_e": i_e}
        nest.SetDefaults('hh_psc_alpha_gap', lc_dict) # use Alvarez et al parameters with NEST HH model
        mod = nest.Create('hh_psc_alpha_gap',neu_num)  # create homogenous modules
        if gj_prop == 1:
            conn_dict_g = {"rule": "all_to_all"}
            syn_dict_g = {'model': 'gap_junction', 'weight': gj_w}
            nest.Connect(mod, mod, conn_dict_g, syn_dict_g)
        return mod

def detgen(type):
    if type == 0:
        det = nest.Create("multimeter")
        nest.SetStatus(det, {"withtime":True, "record_from":['V_m'], "interval":0.1})
    if type == 1:
        det = nest.Create("spike_detector",
                        params={"withgid": True, "withtime": True})
    return det

def get_vtrace(mod, det, n, neu_num):
    dmm = nest.GetStatus(det)[0]
    countr = n-1
    Vm = dmm["events"]["V_m"][countr::neu_num]
    ts = dmm["events"]["times"][countr::neu_num]
    return Vm, ts

def get_spikes(det, neu_num,t1):
    dSD = nest.GetStatus(det,keys="events")[0]
    evs = dSD["senders"]
    ts = dSD["times"]
    fr = (nest.GetStatus(det, "n_events")[0] /neu_num)/t1
    return evs, ts, fr

# scheduling & simulating

#nest.help('kernel')
#nest.ResetKernel()
dt = nest.GetKernelStatus('resolution')
dmin = nest.GetKernelStatus('min_delay')
dmax = nest.GetKernelStatus('max_delay')
nest.SetKernelStatus({'resolution': 0.1})
nest.set_verbosity("M_WARNING")

# neuron/population parameters - some will be overwritten during loops
i_e = 83.5
neu_num = 2 # number of neurons
gj_w = 0.4
gj_prop = 1
pois_w = 0.8
pois_r = 800.

#simulation parameters
t1 = 1 #sim time in seconds
mod1 = modgen(i_e,neu_num, gj_w, gj_prop)
vdet1 = detgen(0)
nest.Connect(vdet1,mod1)
spkdet1 = detgen(1)
nest.Connect(mod1,spkdet1)

nest.Simulate(t1*1000)

f, (ax1, ax2) = pylab.subplots(2, 1, sharex=True)

    #de-interleave and plot voltage traces from simulation results
for n in mod1:
    Vm, ts = get_vtrace(mod1, vdet1, n, neu_num)
    ax1.plot(ts, Vm)
    ax1.set_ylabel('Vm (mV)')
    ax1.set_title('Module 1')

spks1, spk_ts1, fr1 = get_spikes(spkdet1, neu_num, t1)
ax2.plot(spk_ts1, spks1, ".", label='mod. 1')

pylab.show()

**Comment by heplesser** [comment]
@oscr104 Thank you for your report. Could you edit or re-post your Python code once more in a form that preserves indentation, so that we can run your example? You can also upload it as an attachment.

**Comment by oscr104** [comment]
Sorry for the delay, juggling projects at the moment..... 

Code attached
[multimeter_test.py.zip](https://github.com/nest/nest-simulator/files/4185374/multimeter_test.py.zip)

**Comment by heplesser** [comment]
@oscr104 Your code for selecting the data for the voltage traces of different neurons,
```python
    dmm = nest.GetStatus(det)[0]
    countr = n-1
    Vm = dmm["events"]["V_m"][countr::neu_num]
    ts = dmm["events"]["times"][countr::neu_num]
```
is not correct. You cannot generally assume that data from different neurons is interleaved in a fixed order. 

There are two options for separating voltages traces from multiple neurons correctly. You can either have one voltmeter per neuron or you explicitly separate sender IDs:
```python
# obtain voltage trace for neuron gid from voltmeter vm
ev = nest.GetStatus(vm)[0]['events']
ix = ev['senders'] == gid
t = ev['times'][gid]
V = ev['V_m'][gid]
```

Hope this helps!
