### ISSUE TITLE
NEST3 install directory for default nestrc.sli is inconsistent

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1382]
`nestrc.sli` has traditionally been installed to `share/doc/nest/examples`. Per d787f610d747 the install location was changed to `share/doc/nest/extras`, and `sli-init.sli` and `travis_build.sh` adapted correspondingly. Then per 7b63e3d30a02e4 the install location was changed back to `.../examples`, but `sli-init.sli` and `travis_build.sh` were not changed back.

Thus, creating a new `.nestrc` presently fails (and that with a rather meaningless error message). We need to decide on the install location and make all files consistent.

**Comment by stinebuu** [comment]
@heplesser I don't think I have ever created a new `.nestrc` before, could you tell me the commands to do so? I want to make sure I actually solve the problem..

**Comment by heplesser** [comment]
@stinebuu If you do not have `.nestrc` in your home directory when you start nest, the code in `sli-init.sli` will copy `nestrc.sli` from a location in the NEST install directory to `$HOME/.nestrc`.  This does not work because of the directory mix-up described above. To test if the mechanism works, change the name of your `.nestrc` in `$HOME` to something else and then start NEST. This should place a fresh `.nestrc` in your home directory. Once the test is complete, restore your old `.nestrc`.
