### ISSUE TITLE
Link to topology module user manual is outdated

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1388]
On https://www.nest-simulator.org/features/, the link to the topology module is outdated; it should probably point to https://www.nest-simulator.org/wp-content/uploads/2015/04/Topology_UserManual.pdf

@sarakonradi

**Comment by steffengraber** [comment]
Wouldn't it be better to link this page:

https://nest-simulator.readthedocs.io/en/latest/topology/Topology_UserManual.html

**Comment by jougs** [comment]
Mentioning @stinebuu, as she is about to remove the PDF from the repo. Please coordinate appropriately.

**Comment by steffengraber** [comment]
I have changed the link to https://nest-simulator.readthedocs.io/en/latest/topology/Topology_UserManual.html

**Comment by jougs** [comment]
I think the link now (i.e. after the nest-3 merge) should be this one: https://nest-simulator.readthedocs.io/en/latest/topology/index.html

**Comment by steffengraber** [comment]
Therr are both links now: https://www.nest-simulator.org/features/#network-models

**Comment by jougs** [comment]
https://nest-simulator.readthedocs.io/en/latest/topology/Topology_UserManual.html just gives me the readthedocs maze aka not found error. Actually, clicking the links on that feature page, I get a lot of errors. Could you please check and fix? Thanks!

**Comment by steffengraber** [comment]
For v2.20.0 there is the Tolpology page, so I changed the link for NEST 2.x to https://nest-simulator.readthedocs.io/en/v2.20.0/topology/Topology_UserManual.html 
and for NEST 3.0 to  https://nest-simulator.readthedocs.io/en/latest/topology/index.html

**Comment by jougs** [comment]
Great. Thanks!

Could you please also look into the other failing links?
- For the papers, we should generally link the DOI instead of the papers directly. Apparently many journals have meanwhile changed their URL scheme and thus broken our links
- For PyNN, the `trac` component of the URL was removed

**Comment by sarakonradi** [comment]
@steffengraber After the merge of #1468, the user manual has been renamed to ``guide_spatially_structured_networks.rst``.  

All documentation has moved from the ``topology`` folder to ``doc/guides/spatial``: https://github.com/nest/nest-simulator/blob/master/doc/guides/spatial/guide_spatially_structured_networks.rst

The link on https://www.nest-simulator.org/features/ should be changed accordingly.

**Comment by steffengraber** [comment]
I changed the link to https://nest-simulator.readthedocs.io/en/latest/guides/spatial/guide_spatially_structured_networks.html

**Comment by sarakonradi** [comment]
@steffengraber Great, thanks!

**Comment by steffengraber** [comment]
@jougs and @sarakonradi  I have changed the links to the papers. Please check  if I have chosen the right ones.
The link to PyNN has changed.

**Comment by sarakonradi** [comment]
@steffengraber Looks good. I was wondering:
- Is ``Adaptive-exponential integrate and fire neuron model (AdEx) (Brette & Gerstner, 2005)- the standard in the FACETS EU project ([1])`` supposed to be all in one line? Should there be a space before the dash?
- Is ``Tsodyks et al. 2000`` correct, or should it be ``Romani & Tsodyks, 2015``? The latter is specifically about short-term plasticity: https://www.ncbi.nlm.nih.gov/pubmed/25155013
- Based on @jougs's earlier point, should we keep or remove the PDF links on https://www.nest-simulator.org/publications/?

**Comment by steffengraber** [comment]
> * Is `Adaptive-exponential integrate and fire neuron model (AdEx) (Brette & Gerstner, 2005)- the standard in the FACETS EU project ([1])` supposed to be all in one line? Should there be a space before the dash?

Solved.

> 
> * Is `Tsodyks et al. 2000` correct, or should it be `Romani & Tsodyks, 2015`? The latter is specifically about short-term plasticity: https://www.ncbi.nlm.nih.gov/pubmed/25155013
> 
@sarakonradi Could you clarify this, please?

> * Based on @jougs's earlier point, should we keep or remove the PDF links on https://www.nest-simulator.org/publications/?

@jougs @sarakonradi I have removed all pdf links

**Comment by sarakonradi** [comment]
@steffengraber Great, thanks!

> @sarakonradi Could you clarify this, please?

I wasn't sure which Tsodyks paper was intended here. The 2000 paper focuses on synchronization. The well-established Tsodyks–Markram (TM) model is from 1997 and was later extended in 1998. Then there are other newer Tsodyks papers, such as the 2015 one. 

@jougs Do you know which paper was meant to be linked for short-term plasticity?

**Comment by heplesser** [comment]
@steffengraber @sarakonradi Where is the reference to Tsodyks et al (2000) that you are wondering about? I am struggling to find it in the topology documentation.

**Comment by sarakonradi** [comment]
@heplesser We are discussing the "Short-term plasticity" reference under "synapse models": https://www.nest-simulator.org/features/

Is Tsodyks et al. 2000 correct, or should it be a different paper by Tsodyks?

**Comment by heplesser** [comment]
@sarakonradi Tsodyks et al 2000 seems correct, it is he paper cited in the documentation in `tsodyks_connection.h`. Interestingly, though, the `tsodyks_[depressing|facilitating].py` examples cite a 1998 paper, and the `tsodyks2_connection.h` documentation a 1997 paper.

For now I would keep the link, but suggest a follow-up issue to review the contents of the "Synapse models" section: I think it is missing some plasticity models we have now, providing links for some but not all models seems unsystematic and it would be good to clarify in the model documentation the differences between tsodyks and tsodyks2. I hope @mhelias and @abigailm could help on these matters.

**Comment by steffengraber** [comment]
Follow up (#1531) was created. Thus this can be closed.
