### ISSUE TITLE
SIGBUS error at end of simulation

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#139]
I have been trying to run a simulation described in Potjans_2004 on K computer, however almost always
job ends after receiving a SIGBUS error.

```
jwe0019i-u The program was terminated abnormally with signal number SIGBUS.
           signal identifier = BUS_ADRALN, invalid address alignment
 error occurs at _ZN4nest10SpikeEventclEv        loc 0000000000ad3c8c offset 000000000000000c 
 _ZN4nest10SpikeEventclEv            at loc 0000000000ad3c80 called from loc 0000000000272cb4 in _ZN4nest9ConnectorILm3ENS_16StaticConnectionINS_24TargetIdentifierPtrRportEEEE4sendERNS_5EventEiRKSt6vectorIPNS_14ConnectorModelESaIS9_EE      
 _ZN4nest9ConnectorILm3ENS_16StaticConnectionINS_24TargetIdentifierPtrRportEEEE4sendERNS_5EventEiRKSt6vectorIPNS_14ConnectorModelESaIS9_EE     at loc 0000000000272c00 called from loc 0000000000a9b340 in _ZN4nest17ConnectionManager4sendEimRNS_5EventE      
 _ZN4nest17ConnectionManager4sendEimRNS_5EventE     at loc 0000000000a9ae80 called from loc 0000000000bfe124 in _ZN4nest9Scheduler15deliver_events_Ei      
 _ZN4nest9Scheduler15deliver_events_Ei     at loc 0000000000bfd4c0 called from loc 0000000000bf24a4 in _ZN4nest9Scheduler6updateEv._OMP_1      
 _ZN4nest9Scheduler6updateEv._OMP_1     at loc 0000000000bf2240 called from o.s.
```

@janhahne have you encountered this error on K computer? Is there a workaround?

**Comment by janhahne** [comment]
@ikitayama I suppose that you are writing the results of the recording devices to file? In this case you need to set the `fbuffer_size` of the recording devices to `8192` on K.

For example:
```
/spike_detector Create /sd Set
sd
<<
    /to_file true
    /fbuffer_size 8192
>> SetStatus
```

If thats the reason here you just need to add this line in `microcircuit.sli` every time you find a `to_file`.

**Comment by ikitayama** [comment]
@janhahne thank you very much. Actually, @janneM also pointed out to me off the list the other day.
Now I am able to run the simulation and other simulations in the examples/nest.
Below is a profile result from a microcircuit simulation with 1500 nodes, 8 OMP threads per node.
![microcircuit potjans_2014](https://cloud.githubusercontent.com/assets/962791/10877379/07959982-8189-11e5-92f9-cb233839450d.png)

**Comment by ikitayama** [comment]
Please note that in the above, only MPI functions and OMP constructs are profiled.
I will start working on adding annotations in the user-defined functions soon.

**Comment by janhahne** [comment]
@ikitayama Very good. Then I guess this issue can be closed now?

**Comment by ikitayama** [comment]
@janhahne Please go ahead.
