### ISSUE TITLE
Open TODO in `music_cont_in_proxy.cpp`

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#1390]
During review of #1245 we encountered an open TODO in `music_cont_in_proxy.cpp`. This should most likely be fixed or turned into a helpful comment.

Unfortunately the history stops at the move from svn to git. Maybe @mdjurfeldt @jougs remember what this was about?

**Comment by clinssen** [comment]
While looking into this, I noticed the following pattern in most of the ``models/music_*.cpp`` files:

```C++
Parameters_ ptmp = P_; // temporary copy in case of errors
ptmp.set( d, S_ );     // throws if BadProperty

State_ stmp = S_;
stmp.set( d, P_ ); // throws if BadProperty
```

It looks to me like the S_ and P_ are flipped around here (ptmp should be set with P_, and stmp should be set with S_). Could someone confirm? I'll work on a PR.

**Comment by clinssen** [comment]
Suggestion to fix the TODOs (subject of this PR): move this check to set_status().

**Comment by jougs** [comment]
@clinssen: The logic is that `ptmp` is a copy of the original parameters `P_` and then updated with whatever values are in the dictionary `d` in the next line. As there are parameters that depend on state variables from `S_`, we also pass that to the `set()` function. Insofar, I think the code is alright as it is: `ptmp`is updated (that's what `set()` essentially does) with values from `d` and `S_`.
