### ISSUE TITLE
NEST3 triggers warnings when compiled with Clang 9

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1391]
NEST3 triggers a number of warnings when compiled with Clang 9, mainly in `recording_device.h`, but also 

```
/Users/plesser/NEST/code/src_nest3/nestkernel/node_manager.cpp:383:10: warning: local variable 'nodecollection' will be copied despite being returned by name [-Wreturn-std-move]
  return nodecollection;
         ^~~~~~~~~~~~~~
/Users/plesser/NEST/code/src_nest3/nestkernel/node_manager.cpp:383:10: note: call 'std::move' explicitly to avoid copying
  return nodecollection;
         ^~~~~~~~~~~~~~
         std::move(nodecollection)
```

**Comment by ikitayama** [comment]
Could you do the same with trunk? To see they go away?

**Comment by heplesser** [comment]
@ikitayama These warnings were NEST-3 specific.

**Comment by ikitayama** [comment]
I meant that you could try Clang’s development branch called trunk just to
see if they go away.

**Comment by ikitayama** [comment]
With the trunk Clang as of this writing, I don't see the warning @heplesser reported on Arm.

**Comment by ikitayama** [comment]
What about the build time? Quick still on x86?

**Comment by ikitayama** [comment]
> What about the build time? Quick still on x86?

Sorry I take it back, I was using a Debug Clang that I really should've avoided.

**Comment by ikitayama** [comment]
Upstream often likes to fix a bug in trunk, that's why I was suggesting to use the Clang 10 candidate.

**Comment by heplesser** [comment]
@ikitayama I fear I caused some confusion with the way I worded the issue description: The problem was not in Clang, but in the NEST code. Clang pointed out some slight weaknesses in the NEST code which g++ had not warned about.  Sorry for the confusion. The weaknesses are now fixed in the nest-3 branch.
