### ISSUE TITLE
Review -with-openmp cmake flag

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1392]
This is a follow-up to #1326 and #1386. With #1386, the `-with-openmp` flag should work properly when used with `=ON` or  `=OFF`, using auto-detection. But if manual configuration is required, the arguments given are only included in `CFLAGS/CXXFLAGS`, but not considered for the linker. We should either increase flexibility or only allow `ON/OFF`, relying on the powerful autodetection in CMake 3.12+. 

From https://cmake.org/cmake/help/latest/module/FindOpenMP.html, towards the bottom of the page, it appears that `OpenMP_<lang>_INCLUDE_DIR` can be used to inform `FindOpenMP` where to look for OpenMP.

**Comment by ikitayama** [comment]
To me, the autodetection in CMake has always been fragile, but are you
saying in the releases > 3.12 it becomes robust?

**Comment by heplesser** [comment]
Since #1386 was merged eight months ago, there have been no more reports of problems concerning Apple Clang and OpenMP, so I consider this problem solved and close.
