### ISSUE TITLE
Remove pdf versions of Topology User Manual for NEST 3.0?

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#1408]
There are currently two pdf versions of the Topology User Manual in the source code, one in the topology folder: https://github.com/nest/nest-simulator/blob/master/topology/doc/rendered/Topology_UserManual_tex.pdf and one in the doc foler: https://github.com/nest/nest-simulator/blob/master/doc/guides/Topology_UserManual.pdf. The one in the doc folder is for NEST 2.12, while the one in the topology folder is for 2.16.

There is also a rst version of the file, https://github.com/nest/nest-simulator/blob/master/doc/topology/Topology_UserManual.rst, for [ReadTheDocs](https://nest-simulator.readthedocs.io/en/latest/topology/Topology_UserManual.html). For nest-3, we have updated this rst file to fit with the changes ([here](https://github.com/nest/nest-simulator/blob/nest-3/doc/guides/guide_structurally_spatial_networks.rst)).

The Topology folder also has a [rst file](https://github.com/nest/nest-simulator/tree/master/topology/doc/source), as well as a [SnakeFile](https://github.com/nest/nest-simulator/blob/master/topology/doc/Snakefile), which is used to generate the PDF version from the rst file.

In nest-3, we want to move all documentation out of the topology folder. My question is this:

- Do we still want to keep the pdf versions of the Topology User Manual?
- If yes, where should we keep the Snakefile? I think it should be close to the rst file in the doc folder, as the pdf version should be based on that one.

**Comment by jougs** [comment]
@sarakonradi: can you please look into this? Or come back if there are questions? Many thanks!

**Comment by stinebuu** [comment]
After merging the nest-3 branch with master, the rst file for ReadTheDocs is renamed to *guide_structurally_spatial_networks.rst*, and can be found [here](https://github.com/nest/nest-simulator/blob/master/doc/guides/guide_structurally_spatial_networks.rst).

If we keep one pdf version, I don't think it should be called *Topology_UserManual* anymore. Maybe *Structurally_spatially_networks_UserManual*?

**Comment by heplesser** [comment]
@stinebuu @sarakonradi I agree that the PDF version should be renamed. But I think first the name of the RST file should be revised. The title of the document is "Guide to spatially-structured networks", which is fine, but the file name is a strangely juxtaposed version of this. I would suggest to change it to `guide_spatially_structured_networks.rst` and the use the same for the PDF.

**Comment by sarakonradi** [comment]
@stinebuu I agree with @heplesser that the RST and PDF files should be renamed to `guide_spatially_structured_networks.rst`. 

@steffengraber and I were wondering: Will the Snakefile be part of the build process on Read the Docs?

**Comment by stinebuu** [comment]
@sarakonradi @heplesser I agree about the name!

I don't actually know much about the Snakefile, I think it was created by @terhorstd, so maybe he has some thoughts?

**Comment by jougs** [comment]
I seem to have some kind of strange deja vu here, but didn't we discuss this several times before?

My memory goes like this:
- We remove the PDF and only keep the RST, as it is more than likely that the two will go out of sync eventually. If someone needs a PDF, it is easy enough to generate one from the RST.
- We remove the Snakefile, as that was mainly used for converting the Markdown version to RST.

If someone absolutely sees a need for it, we can also add some information somewhere in the documentation for how to generate PDFs from the RST files. In my view, printing the readthedocs page to file provides a good enough PDF. Worst case, we can tweak the corresponding CSS a bit.

**Comment by sarakonradi** [comment]
@jougs If that's the case, then it definitely makes sense to remove the PDF and Snakefile and to keep the RST. I agree with the printing aspect.

@heplesser @steffengraber @terhorstd does everyone agree? If yes, then we can begin cleaning up!

**Comment by heplesser** [comment]
@sarakonradi There is nothing sacred about the PDF. The only reason it exists is that 10+ years ago, when we created it first, there were few other ways to reliably and beautifully combine text, code, equations and figures. But with all the great tools we have today, we can safely drop it.

Given the completely different way in which we now handle spatial connectivity, I assume the content will also change quite a bit?
