### ISSUE TITLE
NESTErrors.DynamicModuleManagementError

### ISSUE THREAD

**Issue by jescab01** [nest/nest-simulator#1413]
I know this issue has been opened before #780. But I'm struggling to solve it, probably my experiments have messed up something. 

I am getting the same error when trying to install the module with nest.Install("modulename"): 

```
`NESTErrors.DynamicModuleManagementError: ("DynamicModuleManagementError in Install: Module 'izhikevich2007module' could not be opened.
The dynamic loader returned the following error: 'file not found'.

Please check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!", 'DynamicModuleManagementError', <SLILiteral: Install>, ": Module 'izhikevich2007module' could not be opened.
The dynamic loader returned the following error: 'file not found'.

Please check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!")`
```

I am working in Ubuntu 18.04.3 LTS, with anaconda3, and I have tried with both nest 2.18.0 and 2.20.0. I am able to mount the model (i.e. izhikevich_psc_alpha.nesml) downloaded from [https://github.com/nest/nestml/tree/master/models](url) with nestml. So I get the following directory [https://github.com/jescab01/ThalamoCortical/tree/master/izhikevich2007module](url).

From there, I tried two approaches: 

First, 
```
cmake -Dwith-nest=/home/jescab01/anaconda3/bin/nest-config .

make all

make install
```

That seems to work correctly, and then in spyder, after import nest: 
`nest.Install("izhikevich2007module")`

Second, 

after installing pynestml:

```
import nest
from pynestml.frontend.pynestml_frontend import to_nest, install_nest

to_nest(input_path="/home/jescab01/Documents/ThalamoCortical/izhikevich_psc_alpha.nestml", target_path="/home/jescab01/Documents/ThalamoCortical/izhikevich2007", module_name="izhikevich2007module")

install_nest("/home/jescab01/Documents/ThalamoCortical/izhikevich2007", "/home/jescab01/anaconda3")

nest.Install("izhikevich2007module")
```

With both approaches I get the same error. 
Could you help me?
Thanks in advance.

**Comment by clinssen** [comment]
Could you please report your value of $LD_LIBRARY_PATH (or $DYLD_LIBRARY_PATH for the mac)?

**Comment by jescab01** [comment]
This was the result:

bash: /home/jescab01/anaconda3/lib/nest: Is a directory

**Comment by clinssen** [comment]
We're seeing some reports that nest-config is returning the wrong directory from within a conda environment, which means that when you run `make install`, it installs the dynamic library (izhikevich2007module.so) to the wrong directory, where NEST subsequently cannot find it. Could you please post the results of running `/home/jescab01/anaconda3/bin/nest-config --prefix`?

**Comment by jescab01** [comment]
Here it is:

/usr

**Comment by clinssen** [comment]
OK, it looks like there are two NEST installation locations: `/usr` and `/home/jescab01/anaconda3`, which are being confused. This issue probably arose already during building/installing NEST Simulator, because the directory names are hard-coded into the nest-config script during the build.

As a workaround, you can try editing the nest-config script to change the directory from `/usr` to `/home/jescab01/anaconda3`. However, probably you should go back to the beginning and do a clean install of NEST inside the conda environment. Make sure that the installation goes into `/home/jescab01/anaconda3` and that the right directories are reported during the cmake configuration stage.

@steffengraber: could you double-check that I'm giving the right instructions here, seeing as I'm not so familiar with anaconda virtual environments myself?

**Comment by steffengraber** [comment]
@jescab01  Hi, since there is a NEST installation in `/usr`, you have most likely installed NEST with `apt-get`. To make sure that there are no problems, it is best to remove this installation with `sudo apt remove nest`.
To make NEST and NESTML work together in conda see this description: https://github.com/nest/nestml/issues/523#issuecomment-554885545

**Comment by jescab01** [comment]
Hi guys, I am still struggling.

To make sure I was doing things right, I reinstalled Ubuntu and started a clean installation of everything (anaconda and nest 2.20.0). But I still get the same result. I followed the guidelines step by step in [https://github.com/nest/nestml/issues/523#issuecomment-554885545](url). 

I checked that now my 

`/home/jescab01/anaconda3/bin/nest-config --prefix`

is ` /home/jescab01/anaconda3/`

And I set LD_LIBRARY_PATH to /home/jescab01/anaconda3/lib/nest .

Files .so are installed in that folder, here a copy-paste of the end of cmake process

```
`[100%] Built target generate_help
Install the project...
-- Install configuration: ""
-- Installing: /home/jescab01/anaconda3/lib/nest/izhikevich2007_module.so
-- Installing: /home/jescab01/anaconda3/lib/nest/libizhikevich2007_module.so
-- Installing: /home/jescab01/anaconda3/include/izhikevich2007_module.h
-- Up-to-date: /home/jescab01/anaconda3/share/nest/sli
-- Installing: /home/jescab01/anaconda3/share/nest/sli/izhikevich2007_module-init.sli
-- Up-to-date: /home/jescab01/anaconda3/share/doc/nest/help
-- Installing: /home/jescab01/anaconda3/share/doc/nest/help/helpindex.html
-- Installing: /home/jescab01/anaconda3/share/doc/nest/help/helpindex.hlp
-- Up-to-date: /home/jescab01/anaconda3/share/doc/nest/help/sli
-- Up-to-date: /home/jescab01/anaconda3/share/doc/nest/help/cc
`
```

And when executing "nest.Install("nestmlmodule"):

```
In [3]: nest.Install("nestmlmodule")                                                        
---------------------------------------------------------------------------
NESTErrors.DynamicModuleManagementError   Traceback (most recent call last)
<ipython-input-3-19a99b8debb3> in <module>
----> 1 nest.Install("nestmlmodule")

~/anaconda3/lib/python3.7/site-packages/nest/ll_api.py in stack_checker_func(*args, **kwargs)
    244     def stack_checker_func(*args, **kwargs):
    245         if not get_debug():
--> 246             return f(*args, **kwargs)
    247         else:
    248             sr('count')

~/anaconda3/lib/python3.7/site-packages/nest/lib/hl_api_simulation.py in Install(module_name)
    316     """
    317 
--> 318     return sr("(%s) Install" % module_name)
    319 
    320 

~/anaconda3/lib/python3.7/site-packages/nest/ll_api.py in catching_sli_run(cmd)
    130 
    131         exceptionCls = getattr(kernel.NESTErrors, errorname)
--> 132         raise exceptionCls(commandname, message)
    133 
    134 sli_run = sr = catching_sli_run

NESTErrors.DynamicModuleManagementError: ("DynamicModuleManagementError in Install: Module 'nestmlmodule' could not be opened.\nThe dynamic loader returned the following error: 'file not found'.\n\nPlease check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!", 'DynamicModuleManagementError', <SLILiteral: Install>, ": Module 'nestmlmodule' could not be opened.\nThe dynamic loader returned the following error: 'file not found'.\n\nPlease check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!")

```

What else could I try or check?

**Comment by clinssen** [comment]
Since you named your module "izhikevich2007_module", try `nest.Install("izhikevich2007_module")`

**Comment by jescab01** [comment]
Same. This is the process I follow:

In terminal:

```
PYTHONPATH=$PYTHONPATH:/home/jescab01/anaconda3/lib/python3.7/site-packages 

LD_LIBRARY_PATH=/home/jescab01/anaconda3/lib/nest

ipython3
```


```
import nest
from pynestml.frontend.pynestml_frontend import to_nest, install_nest

to_nest(input_path="/home/jescab01/ThalamoCortical/izhikevich_psc_alpha.nestml", target_path="/home/jescab01/ThalamoCortical/newModels", module_name="izhikevich2007_module", logging_level="INFO")

install_nest("/home/jescab01/ThalamoCortical/newModels", "/home/jescab01/anaconda3")

nest.Install("izhikevich2007_module")
```

**Comment by clinssen** [comment]
Note that if you type `LD_LIBRARY_PATH=/foo/bar` at the shell prompt, it only applies to that command and will not be stored for subsequent commands. You have to either use the syntax
```bash
export LD_LIBRARY_PATH=/foo/bar
ipython3
```
or
```bash
LD_LIBRARY_PATH=/foo/bar ipython3
```
(assuming you are using the bash shell)

**Comment by jescab01** [comment]
Oh! I need to study some informatics.. xD. Thanks a lot @clinssen @steffengraber for your support. It's solved.
