### ISSUE TITLE
GetConnections function returns empty tuple if only target is specified

### ISSUE THREAD

**Issue by leoTiez** [nest/nest-simulator#1431]
According to the PyNEST documentation the accepted parameters are source nodes, target nodes, synapse model and synapse label. All parameters use None as a default and thus are not required.
`GetConnections()`, `GetConnections(source=source_nodes)` and `GetConnections(source=source_nodes, target=target_nodes)` do all correctly return a tuple with the connections. However, if only the post-synaptic nodes are specified (i.e. `GetConnections(target=target_nodes)`) the function returns an empty tuple, even if connections are set (verified with `GetConnections(source=source_nodes, target=target_nodes)` ). I assume that's not intended or I misunderstand the documentation.

Environment:
NEST: 2.20.0
Python: 3.6
OS: Ubuntu 18.04

**Comment by jakobj** [comment]
thanks for the report @leoTiez! could you please attach a minimal reproducer script? this will make it much easier for us to identify the potential source of the problem

**Comment by leoTiez** [comment]
@jakobj Sorry for the late reply. I struggle myself right now finding a consistent behaviour. It seems that sometimes it works, whereas sometimes it fails when only the target is specified. The other  versions work perfectly tho. I'll try to get some more information and will try to post a testcase as soon as possible.

**Comment by heplesser** [comment]
@jakobj @hakonsbm @stinebuu Given the "sometimes it works" observations by @leoTiez, I wonder if we may have another threading problem here. I therefore escalate to "critical". I also relabel to "kernel", since this probably most certainly is not caused in the PyNEST interface.

**Comment by leoTiez** [comment]
Good morning @jakobj @heplesser,

the more cases I test, the more I'm convinced that the problem was on my side. Although I'm not 100% sure (because I thought that I tested it with the correct parameters) I think I passed a `nest.topology` layer instead of the corresponding nodes.
I feel truly sorry about the trouble I might have caused and close the issue. If I'm facing the problem again, I'll  create a test case and re-open this issue.

All the best!

**Comment by leoTiez** [comment]
@jakobj @heplesser Sorry for reopening, but I faced the same issue again this morning. However, I've the feeling that this only happens if I run it in a debugging environment (this could explain why it's so difficult to replicate). Might there some conflicts with the Nest kernel?

**Comment by hakonsbm** [comment]
@leoTiez Can you please provide a minimal reproducer? And how did you install NEST (ppa/conda/from source/etc.)?

**Comment by zbarni** [comment]
Hello! Sorry for intruding in the issue, but I think I came across a minimal example that consistently reproduces a similar error:

```
import nest
nest.SetKernelStatus({'resolution': 0.1})

neuron1 = nest.Create('iaf_psc_exp', 1)
neuron2 = nest.Create('iaf_psc_exp', 1)

#nest.Connect(neuron1, neuron2)

spike_generator = nest.Create("poisson_generator")
nest.Connect(spike_generator, neuron1, syn_spec={'weight': 100.})
print(nest.GetConnections(target=neuron1))
```
As it is, the script outputs `()`. Curiously, if one uncomments the line 
`#nest.Connect(neuron1, neuron2)`, then it works and we get `(array('l', [3, 1, 0, 15, 0]),)`. Is this the expected behaviour?

I installed NEST 2.20 from source, Python3, Linux Mint 18. NEST 2.18 also has the error.

**Comment by hakonsbm** [comment]
@zbarni Thanks! This is not the expected behaviour. I'll look into it.
