### ISSUE TITLE
The first input (nodes) must be NodeCollection or a SynapseCollection with connection handles 

### ISSUE THREAD

**Issue by pabogdan** [nest/nest-simulator#1437]
The following error occurs when trying to invoke pyNN.nest using master today. 

```
[INFO] [2020.2.19 14:57:4 /nest_dev/nest-simulator/nestkernel/rng_manager.cpp:208 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2020.2.19 14:57:4 /nest_dev/nest-simulator/nestkernel/rng_manager.cpp:251 @ Network::create_grng_] : Creating new default global RNG

              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: master@1cb45ca5a
 Built: Feb 19 2020 14:20:54

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.

Traceback (most recent call last):
  File "experiment.py", line 21, in <module>
    import pyNN.nest as sim
  File "/usr/local/lib/python3.7/site-packages/PyNN-0.9.5.dev0-py3.7.egg/pyNN/nest/__init__.py", line 23, in <module>
    nest.GetStatus([numpy.int32(0)])
  File "/nest_dev/lib/python3.7/site-packages/nest/ll_api.py", line 245, in stack_checker_func
    return f(*args, **kwargs)
  File "/nest_dev/lib/python3.7/site-packages/nest/lib/hl_api_info.py", line 375, in GetStatus
    raise TypeError("The first input (nodes) must be NodeCollection or a SynapseCollection with connection handles")
TypeError: The first input (nodes) must be NodeCollection or a SynapseCollection with connection handles
``` 
I have just tested the latest release -- it works. 

Last known date at which master worked: 27/01/2020  -- everything is run in a docker container that gets rebuilt just before running so this date is also the date at which I pulled the most recent development version.

PyNN is installed from https://github.com/NeuralEnsemble/PyNN/archive/nest-dev.tar.gz (as per https://www.nest-simulator.org/mailinglist/hyperkitty/list/users@nest-simulator.org/thread/VAZMC73JMOFUD7YZVFHYBMM5CXE7CZYK/)

**Comment by heplesser** [comment]
@pabogdan In preparation for the NEST3 release, we recently merged the NEST3 development work into NEST Master. PyNN does not yet support the new NEST3 user interface of NEST (working on it), so at the moment you can only use NEST releases with PyNN.

I will close the issue for now.
