### ISSUE TITLE
Improve visibility of NEST2-to-NEST3 conversion guide

### ISSUE THREAD

**Issue by sarakonradi** [nest/nest-simulator#1450]
There are two NEST2-to-NEST3 conversion guides in the documentation: 
- A general overview in `doc/guides`, which can be found within "Guides" on Read the Docs: https://github.com/nest/nest-simulator/blob/master/doc/guides/from_nest2_to_nest3.rst
- A detailed functions guide in `doc/ref_material`, which is listed in the main table of contents: https://github.com/nest/nest-simulator/blob/master/doc/ref_material/nest2_vs_3.rst 

This may be confusing to a user who visits the documentation website and is interested in the general "What's new?", but who lands on the detailed functions guide instead.

It made me wonder if we could: 
- List both files under "Guides": https://nest-simulator.readthedocs.io/en/latest/guides/index.html
- Use more meaningful titles, e.g. "NEST 2.x to NEST 3.0: What's new?" and "NEST 2.x to NEST 3.0: Changes to functions" 

@heplesser I realize that you already shared the conversion guides' links in your NEST 2.20 announcement (and possibly elsewhere). 

My question is: Would such changes make sense at this stage?

**Comment by sarakonradi** [comment]
@heplesser What are your thoughts on this?

**Comment by heplesser** [comment]
@sarakonradi I like your suggestion. 
- "...: What's new?" is a nice title
- For the detailed guide, how about "...: Detailed transition guide"?
Listing them both in the list of guides and linking to each other seems like a good idea.
