### ISSUE TITLE
Are there interfaces from Python for simulation progression?

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1454]
Question in the title. Couldn't find anything on the docs or Google.

Is there a way to pass a callback that gets executed when the progression changes?

**Comment by BSVogler** [comment]
As a workaround, you could easily split the simulation into many smaller time increments and use a counter for progression tracking. This is what I am doing in an RL environment. It might have some side effects on the total run time though.

**Comment by terhorstd** [comment]
Calling Simulate() with smaller time increments, is a sensible way to go at the moment. A callback from c++ level back to python would leave the parallel context and causes quite some overhead. 

Maybe @jougs can comment on the notion of a "progress_recorder" as nestio backend. I could imagine there it is easily possible to send timestamp packets as a stream without stopping the simulation.

**Comment by Silmathoron** [comment]
This may be a naive question because I might have misunderstood the OP, but aren't you looking for ``nest.SetKernelStatus({"print_time"; True})``?
If I did not get it and simulating small increments is indeed the solution, have a look at the combo ``Prepare``, loop on ``Run``, then ``Cleanup`` functions.

**Comment by Helveg** [comment]
Print time sounds like it will print it to stdout? It's not the most convenient thing to redirect pipe and parse stdout. Both approaches give me good options if I create a child process, but nothing that really allows me to work asynchronously from the same process, right?

**Comment by Silmathoron** [comment]
Ah ok, yeah, read too fast.
Might want to ask @jougs whether this is something he considered for NESTIO...

**Comment by jougs** [comment]
Argh! This somehow made it well off my radar.

As explained in [the guide on running simulations](https://nest-simulator-jougs.readthedocs.io/en/latest/guides/running_simulations.html#splitting-a-simulation-into-multiple-intervals) you shall not call `Simulate()` multiple times if you want to do do repetitive small simulations, but it is much more efficient to call
```
Prepare()
Run()
Run()
...
Cleanup()
```
Alongside the calls to `Run()` you can of course run whatever you want.

What would such a hook look like that you would run on the C++ level?

**Comment by jougs** [comment]
@Helveg, is there anything more we can do here? If not, I would be closing this issue. Thanks!

**Comment by Helveg** [comment]
> What would such a hook look like that you would run on the C++ level?

A generic python function that is passed the progression information such as:

```python
@nest.progress
def report_progress(tick, dt, total, duration):
  print(f"NEST simulated tick {tick} in {duration}s; Simulation is at {tick*dt}/{total}s")
```

**Comment by jougs** [comment]
@Helveg: Thanks for the clarification. In principle, I'm positive to implement a function that can serve as such a decorator. However, I do not yet fully understand what the difference between *total* and *duration* would be. Could you please elaborate? Also, what units would you expect for the individual values?

Technically, I think the decorator could even be implemented fully in "user-space" along these lines:

```python
def progress_listener(func)
    def wrapper():
        tick = nest.GetKernelStatus('time')       # The current simulation time (in ms)
        dt = nest.GetKernelStatus('resolution')   # The resolution of the simulation (in ms)
        total = ...
        duration = ...
        func(tick, dt, total, duration)
    return wrapper 
```
We currently also provide *to_do* in the kernel's status dictionary, which is the number of steps yet to be simulated. I am not 100% sure how to provide access to the total requested simulation time (which is what I suppose your total/duration values are about). In particular in stepped simulations those might not be what the user expects (c.f. 100 calls to `Simulate(10.0)` vs. 10 calls to `Simulate(100.0)`)

**Comment by Helveg** [comment]
Well the point of this would be to have a callback every tick and to be able to perform arbitrary operations and avoid stepped simulations. As you pointed out the `GetKernelStatus` dictionary probably already contains the information one would need at each timestep. But this could be a valuable tool to Python tools to "inject" callbacks on top of a simulation managed by an end user that might not want to use stepped simulations at all.

**Comment by Helveg** [comment]
Wow, yes, that's correct. I need to work on my specification description skills ;p The is ofcourse syntactic sugar but it's an easy win to impress the Python crowd ;)

**Comment by jougs** [comment]
Alright. Then I think this is feasible in principle.

The only thing that worries me a bit is the fact that the grid on which the callback would be evaluated would depend on the minimal delay in the network and that means that it could be different for each run of a simulation if randomized delays were used and seeds were changed inbetween runs. For most users this would probably not be the expected behavior and I'm not sure if the benefits outweigh the effort required to get a more stable tick signal from the simulation kernel.

@Helveg, @Silmathoron: What do you think about this limitation?

**Comment by jougs** [comment]
@babsey: would something like this also be interesting for NEST Desktop or are you stepping the simulation there anyway to display live simulation results?

As @terhorstd already pointed out, this could also be implemented as a combination of a dead stupid `time_recorder` recording device and a streaming recording backend that sends out the heartbeats via UDP or something. However, I don't know how in what ways an async receiver of those packets in the same process would affect performance.

**Comment by Helveg** [comment]
I think that if we make the time information positional arguments of the callback we can avoid people making their own range based on assumptions. The only thing to be avoided is that people expect it to be consistent and that we send people on wild goose chases wondering why it's not. I think that this can be made obvious enough in a couple of ways:

* Prominently mentioned in its documentation
* Staying away from a name that links it to time or implies regularity, making it sound more technical could also avoid associations about it: e.g. `mindelay_callback` rather than 'tick'.

**Comment by jougs** [comment]
@marcelkrueger: could you explain a bit how Insite can help here? Thanks!

**Comment by Helveg** [comment]
I'm no longer requesting this. Stepped simulations cover my current needs, and otherwise I'll monkeypatch the `nest` module ;)
