### ISSUE TITLE
Suggestion nest3: Disconnect with SynapseCollection

### ISSUE THREAD

**Issue by BSVogler** [nest/nest-simulator#1457]
Now with the new SynapseCollection it could make managing connections easier. It should be possible to call `nest.Disconnect(syncoll)` on a SynapseCollection or maybe even `syncoll.disconnect()`

Currently, the code to disconent based on a SynapseCollection looks like this
```python
nest.Disconnect(nest.NodeCollection([conn.source]),
     nest.NodeCollection([conn.target]),
     syn_spec={'synapse_model': model})
```

**Comment by heplesser** [comment]
@hakonsbm Ping
