### ISSUE TITLE
Improve rate-based models documentation

### ISSUE THREAD

**Issue by sarakonradi** [nest/nest-simulator#1467]
This issue addresses the documentation of the rate-based models and is based on @shimoura's feedback from LASCON 2020 and a discussion with @ddahmen.

We have learned that users may find it unclear that the full equations of a specific model (e.g. ``sigmoid_rate``) can be found in the template class. 

Currently, there appear to be three base classes for the rate-based models: 

1. Base class for rate model with input noise
2. Base class for rate model with output noise
3. Transformer 

After discussing this with @ddahmen, we agreed on  the following documentation improvements: 

- Changing the order of the models such that the template classes appear first
- Including clickable links to the relevant differential equations under each model 
- Ensuring all equations are properly displayed on Read the Docs
- Writing descriptions on how to use ``nest.Create()`` with the correct rate function for each model

Open questions:
- Is the equation of the transformer already documented somewhere?

**Comment by heplesser** [comment]
Fixed by #1484.
