### ISSUE TITLE
Build with boost by default

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1469]
**Is your feature request related to a problem? Please describe.**
Currently, the default for NEST builds is `-Dwith-boost=OFF`, so unless users are very observant, they will build without Boost and suffer considerable performance problems.

**Describe the solution you'd like**
Make `-Dwith-boost=ON` the default and provide a warning in the CMake summary if Boost is not available (similar to GSL).

**Additional context**
See also #1461, #1238.

**Comment by ikitayama** [comment]
It’s good that with no boost case it doesn’t bail out.

**Comment by lekshmideepu** [comment]
Travis [builds](https://github.com/nest/nest-simulator/blob/master/extras/travis_build.sh#L111) are with boost except for OSX builds.

**Comment by niltonlk** [comment]
At present, I think it would be better to add that Boost version must also be < 1.69.0 (On ProcessOptions.cmake it is already specified that Boost must be >= 1.58.0), as Boost >= 1.69.0 currently results in installcheck failures (see #1239).
