### ISSUE TITLE
Link to installation instructions for macOS missing

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1486]
**Describe the bug**

In the installation instructions at

https://nest-simulator.readthedocs.io/en/stable/installation/index.html#advanced-install

the reader is referred to the "mac_manual for Macs", see screenshot below, but no link is provided.

**Expected behavior**

A link to the installation instructions for macOS at

https://nest-simulator.readthedocs.io/en/stable/installation/install_options.html#compiling-for-apple-osx-macos

**Screenshots**

![image](https://user-images.githubusercontent.com/1059644/77764618-37d14900-703d-11ea-81fc-0f242855c454.png)

**Comment by sarakonradi** [comment]
@heplesser If you visit the "latest" version of Read the Docs, you should see the link. :)

This issue was described in #1406 and fixed in #1446. 

Here is the link: https://nest-simulator.readthedocs.io/en/latest/installation/index.html#advanced-installation-instructions

**Comment by heplesser** [comment]
@sarakonradi  "Latest" as in "the version already prepared for NEST3"? Should we backport this type of fixes to the "stable" documentation?

**Comment by sarakonradi** [comment]
> @sarakonradi "Latest" as in "the version already prepared for NEST3"? 

Yes, "latest" is the documentation for NEST3. 

> Should we backport this type of fixes to the "stable" documentation?

That is a matter of philosophy. Currently, such fixes are listed in our final documentation checks for the next release (see #1445), so I don't know if we should backport them. What do you think?

**Comment by sarakonradi** [comment]
@heplesser What we can do is to fix that in 2.20.1!

**Comment by steffengraber** [comment]
This is solved with #1472 for 2.20.1.
