### ISSUE TITLE
Unable to store spike_detector output to file for multiple calls to Simulate (master branch)

### ISSUE THREAD

**Issue by niltonlk** [nest/nest-simulator#1487]
**Describe the bug**
Cannot store spike_detector output to file for consecutive calls to Simulate, or if overwrite_files=True, stored data is overwritten.
This behavior is not observed on the default configuration of spike_detector (i.e. record_to=memory).
This bug is present on master branch, which may affect NEST 3.0.
The expected behavior is observed on the released versions of NEST (2.16, 2.18, 2.20)

**To Reproduce**
1. (Minimal) reproducing example
```
import nest
n = nest.Create('iaf_psc_exp', params={'I_e':600.0})
s = nest.Create('spike_detector', params={'record_to':'ascii'})
nest.Connect(n,s)
nest.Simulate(100.0)
nest.Simulate(100.0)
```
> The file 'spike_detector-2-0.dat' already exists and overwriting files is 
    disabled. To overwrite files, set the kernel property overwrite_files to 
    true. To change the name or location of the file, change the kernel 
    properties data_path or data_prefix, or the device property label.
2. Setting overwrite_files to True only keeps the result of the last call to Simulate

**Expected behavior**
Independently to what is set to overwrite_files, consecutive calls to Simulate should be allowed, and all data should be stored. This is what is observed on NEST 2.20!

**Desktop/Environment (please complete the following information):**
 - OS: CentOS 7.7.1908
 - Shell: bash
 - Python-Version: Python 3.6
 - NEST-Version: git hash: 3d110f
 - Installation: with-MPI=ON, with-boost=ON
 - Modules: autotools, prun/1.3, gnu8/8.3.0, ohpc, gsl/2.6, boost/168.0, fftw/3.3.8, openblas/0.3.7, nest/3.0-dev

**Additional context**

**Comment by jougs** [comment]
I'm afraid this is not really a bug, but more a behavioral change between before and after the merge of NESTio. A current workaround is to move the result files away between subsequent calls to `Simulate()`.

Changing this behavior would require some non-trivial changes to the way the ASCII recording backend handles files, which I'm unlikely to find the time for any time soon. I will thus close this as wontfix. Sorry about this.

**Comment by heplesser** [comment]
@jougs Just a question: What happens in this case if one runs
```
with nest.RunManager():
    nest.Run(100)
    nest.Run(100)
```
Would that also overwrite the files? One limitation with that approach is obviously that one cannot make any changes to the network or neuron parameters between the `run()` calls.
