### ISSUE TITLE
Allow specification of start and stop times of a poisson_generator with lists like in step_current_generator or step_rate_generator

### ISSUE THREAD

**Issue by niltonlk** [nest/nest-simulator#1488]
**Is your feature request related to a problem? Please describe.**
When periodic stimulus generated by a poisson_generator is necessary, one has to stop simulation before the start time of the following stimulus starts, change the parameters of the poisson_generator, and resume the simulation. This is currently not currently possible in the master branch when storing spike_detector into file (see #1487).

**Describe the solution you'd like**
Allowing the specification of start and stop times with a list would facilitate such cases by allowing a single call to simulate.

**Comment by Silmathoron** [comment]
Use [``inhomogeneous_poisson_generator``](https://nest-simulator.readthedocs.io/en/stable/models/generator.html#generator-type-devices) instead.

**Comment by niltonlk** [comment]
Yes, it does! Thanks! Closing this then
