### ISSUE TITLE
MyModule example introduces additional non-trivial dependencies

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#1494]
The recording backend example introduces a dependency that is not trivially satisfied on my system (.../recording_backend_soundclick.h:31:10: fatal error: SFML/Audio.hpp: No such file or directory). In my opinion  dependencies of the examples should not go beyond those of NEST, as this confuses and potentially frustrates new users (and developers ;) ).

I would hence suggest to adapt the example to remove this dependency. What do you think @jougs @gtrensch ?

**Comment by heplesser** [comment]
@jakobj I agree.

**Comment by niltonlk** [comment]
In CMakeLists.txt, there is a condition to disable the build of the example backend, however, there was a missing #ifdef in mymodule.cpp to do not include the backend header file when the audio library is not present (see #1479).

**Comment by gtrensch** [comment]
I can confirm that this is a bug and that the HAVE_SMFL_AUDIO check is missing in the code. This is resolved by #1512.
