### ISSUE TITLE
Documentation workflow conda environment

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1496]
**Describe the bug**
The environment introduced in the documentation workflow requires a lot of space and is over-specified for the purpose.

**To Reproduce**
Remove lines or version specifiers from doc/nest_doc_conda_env.yml
Follow documentation workflow. Still works.

**Expected behavior**
environment should be specific for the purpose, and impose restrictions only to the extent required, so the workflow should break when removing lines or restrictions.

**Desktop/Environment (please complete the following information):**
 - OS: Ubuntu-18.04
 - Shell: bash
 - Python-Version: conda installed by environment file
 - NEST-Version: from PR #1439 (72dee38)

**Comment by heplesser** [comment]
@terhorstd I agree with your philosophy of keeping environments minimal. Have you identified any dependencies yet that can be removed safely? 

Looking at [nest_doc_conda_env.yml](https://github.com/nest/nest-simulator/blob/4fb2b1bceded7f3b26f0bb9991cb847433236f08/doc/nest_doc_conda_env.yml#L50), I also wonder why `pynest` here apparently is listed as a dependency via pip, even though `nest-simulator` is already listed as a conda dependency.

**Comment by steffengraber** [comment]
@terhorstd This is solved with #1843 . Can we close it?

**Comment by heplesser** [comment]
Available in NEST 3, thus closing.
