### ISSUE TITLE
documentation generation dependencies

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1498]
**Describe the bug**
the `doc/conf.py` contains dependencies to `recommonmark.parser` and `copybutton.js`, that are probably not needed anymore and were remarked to be removed, see #1355 

**Expected behavior**
No unnecessary dependencies should be required.

**Comment by sarakonradi** [comment]
The updated ``doc/conf.py`` in #1530 will remove ``recommonmark.parser`` and ``copybutton.js``.
