### ISSUE TITLE
Figures are broken on NEST3 transition guide

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1505]
Firgures not loading on https://nest-simulator.readthedocs.io/en/latest/guides/nest2_to_nest3/nest2_to_nest3_overview.html

rST source code (for example):

  .. image:: ../_static/img/NEST3_23_0.png

Resolves to URL: https://nest-simulator.readthedocs.io/en/latest/guides/nest2_to_nest3/guides/_static/img/NEST3_23_0.png

Should be: https://nest-simulator.readthedocs.io/en/latest/_static/img/NEST3_23_0.png

**Comment by sarakonradi** [comment]
Hi @clinssen, well noticed. I addressed those figures in #1501 yesterday. Feel free to have a look.

**Comment by clinssen** [comment]
Thanks, would be happy to be a reviewer on #1501 if you're looking!

**Comment by sarakonradi** [comment]
@clinssen That would be great!
