### ISSUE TITLE
More detailed pynest errors: subclassing the general pynest nest.NESTError class

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#151]
So far the pynest API only throws a single error class, the [NESTError](https://github.com/nest/nest-simulator/blob/master/pynest/pynestkernel.pyx#L79).

In order to catch more detailed errors on the python side, it probably would make sense to subclass this error into a few more python-side error classes, reflecting the [actually raised SLI exceptions](https://github.com/nest/nest-simulator/blob/master/sli/sliexceptions.h).

Any thoughts on this?

**Comment by jougs** [comment]
If I remember correctly, one of the reasons for using only one type of exception was to make it easier for PyNN to know what happened. @apdavison might know more about this. @apeyser might have a more technical perspective on this.

**Comment by apdavison** [comment]
If you subclass `NESTError`, there's no problem either way. PyNN or other libraries using NEST can choose to catch just `NESTError`, or the more specific subtypes (I would probably choose to catch the subtypes).

**Comment by flinz** [comment]
@apdavison Yes, subclassing was the intention - i'll have a look at this.

**Comment by apeyser** [comment]
Agreed that would be the best solution. The next question is implementation and hierarchy. I'll have to look into how the exception is currently constructed and if there's a reasonable automated way to do this.

**Comment by flinz** [comment]
I had a quick look at this, see https://github.com/flinz/nest-simulator/commit/4568d3776f175fc29b02c96b780683813d7a592f

@apeyser I dont know if you had something like this in mind, but its a short proof of principle

- Grab all errors from nestkernel and sli, and create python wrappers (uses get_errors.py which needs to be somehow integrated into the build process) in [hl_api_errors.py](https://github.com/flinz/nest-simulator/blob/4568d3776f175fc29b02c96b780683813d7a592f/pynest/nest/lib/hl_api_errors.py)
- All new errors inherit from NESTError, with Kernel exceptions inheriting additionally from NESTKernelError and SLI exceptions inheriting additionally from NESTSLIError
- Exception propagated from SLI are now looked up against the errors in python, and the [proper python error is raised](https://github.com/flinz/nest-simulator/commit/4568d3776f175fc29b02c96b780683813d7a592f#diff-14ca38d825613569e5bb0ab8ea82e266R91)
- adapted [test_error.py](https://github.com/flinz/nest-simulator/blob/4568d3776f175fc29b02c96b780683813d7a592f/pynest/nest/tests/test_errors.py) to check for the few new errors for demonstration purposes

**Comment by apeyser** [comment]
@flinz: I think it could be done entirely dynamically:
```python
class NestExceptions:
    def __getattr__(self, key):
        c = type(key, (NestKernelError,), {})
        setattr(self, key, c)
        return c
```

and then you just: `except NestExceptions.NESTUnknownModelIDError: handleit`
and on the other hand: `raise getattr(NestExceptions, 'NEST'+errorname)` where `errorname = NESTUnknownModelIDError`

Doing the preprocessing avoids debugging spelling issues and lost classes, however, so it may still be better since the code is clang-formatted now. We could also split the difference and build a dict of errornames out of the preprocessing so that an exception could be thrown at parse time. There'll be much less code, but we can still catch errors at parse time.

And what about module exceptions? I don't know if we have a pattern for that, or if it can be arbitrary.

Here is where it would have been nice to templatize on the exception name (or even better, on exception traits, or to be tricky, use a curiously recurrent template to access the downstream name...), so that SLIException would have know at process init time all the possible exceptions since the name belongs to the class and not the instance of the exception, but the SLIException classes just take the exception name as an instance constructor argument.

**Comment by flinz** [comment]
> We could also split the difference and build a dict of errornames out of the preprocessing so that an exception could be thrown at parse time. There'll be much less code, but we can still catch errors at parse time.

I would also vote for the approach of building a dict of errornames from which the exceptions are dynamically generated at import time. From the user-side it should be clear from pynest at import time which errors can be differentiated. If error classes are created at runtime only as they are raised (as in your example) this would not be possible.

> And what about module exceptions? I don't know if we have a pattern for that, or if it can be arbitrary.

Could you explain a little more what you mean? Sorry, but I couldn't really follow your argument in the last paragraph..

**Comment by apeyser** [comment]
@flinz: I meant that I don't know whether there's a rule regarding subclassing nest exceptions in dynamic libraries load by nest as 'modules'. 

My last paragraph was just thinking about a way that the exception classes could have registered themselves as the were declared, with a structure like (just as an example off the top of my head):
````
class BaseException_ {
  virtual const string& whatami() const = 0;
  static list<string> names;
};

class RegisterException {
  RegisterException(const string& name) {BaseException_::names.push_back(name);}
};

template<class E>
class BaseException: BaseException_ {
  virtual const string& whatami() const {return E::name;}
  static const RegisterException register(E::name);
};

class AnException: BaseException<AnException> {
  static const string name = "AnException";
};
````
but in the current implementation, the names aren't class members but instance members, which makes any sort of registration scheme impossible --- even though they are the same for all instances of a class, they aren't initialized until you actually construct an exception.

**Comment by flinz** [comment]
Should we approach anything final, https://github.com/nest/nest-simulator/issues/406 should be addressed too.

**Comment by jougs** [comment]
@flinz: I know it's been a while, but FWIW, are you still willing to work on this?

**Comment by heplesser** [comment]
@apeyser As you have been heavily involved in the discussion here, could you take care of implementation?

**Comment by apeyser** [comment]
@heplesser Taken care of, see #1035

**Comment by apeyser** [comment]
Issue #1035 merged.
