### ISSUE TITLE
Link .py files in PyNEST microcircuit

### ISSUE THREAD

**Issue by sarakonradi** [nest/nest-simulator#1511]
This issue follows up on #1444. 

If we publish the [README](https://github.com/nest/nest-simulator/blob/master/pynest/examples/Potjans_2014/README.rst) as it currently is on Read the Docs, the user would see the list of ``.py`` files and not know where these are located:

![microcircuit_file_structure](https://user-images.githubusercontent.com/58212853/78783756-6e478600-79a4-11ea-9ebb-b020fd9b8ec9.png)

One solution would be to find a way to automatically add the ``:download:`` role to the ``.py`` files in the README when generating documentation with Sphinx. This would allow the user to download the files on Read the Docs. It would not affect the README itself in ``pynest/examples/Potjans_2014``. 

A simpler option would be to re-edit the README, turning the files listed under ``File structure`` into external links that direct the user to the file links on GitHub. The benefit of this option is that the hyperlinks would be rendered on Read the Docs as well as on GitHub: https://github.com/sarakonradi/nest-simulator/blob/cb8b4325c0045675063121495d1e604bdd01a879/pynest/examples/Potjans_2014/README.rst

Input from @steffengraber and @jhnnsnk is very welcome.

**Comment by jhnnsnk** [comment]
@sarakonradi Great that you start this follow-up!
Option 1: Actually, I do not find it very useful to download files individually. I would prefer either the possibility to inspect individual files directly in the browser (similarly to Option 2) or to download the whole Potjans_2014 example with all files combined.

Option 2: With this option I see the danger that these links will hardcode to, e.g., the master of the nest-simulator repository that might diverge from the repository the documentation is beeing created from. I do not know if this technically doable, but relative links would be best.

Besides, is there the possibility to open the files directly in the documentation as it is done with the one-script examples?
I could also imagine an additional landing page in the documentation with links to all files (including the README) which will then be directly displayed in the documentation when clicking on them. This landing page could duplicate the "File structure" section of the README with proper relative links.

**Comment by sarakonradi** [comment]
@jhnnsnk Thanks for your input! 

> Option 1: Actually, I do not find it very useful to download files individually. I would prefer either the possibility to inspect individual files directly in the browser (similarly to Option 2) or to download the whole Potjans_2014 example with all files combined.

You are right, it would be suitable to inspect the files in the browser. 

> Option 2: With this option I see the danger that these links will hardcode to, e.g., the master of the nest-simulator repository that might diverge from the repository the documentation is beeing created from. I do not know if this technically doable, but relative links would be best.

Yes, I agree with the danger of hardcoding. Relative links in the form of ``[relative link](file)`` would work well on GitHub, but if we publish the very same README on Read the Docs, i.e., a different site, it would break. I am not sure yet what the technical solution to that would look like. 

> Besides, is there the possibility to open the files directly in the documentation as it is done with the one-script examples?

I just tested the ``:download:`` role again, and the name is a bit misleading. What it actually does is create a standard link to the external file (e.g. ``helpers.py``). The user does not automatically "download" the file, but rather "opens" it in the browser.

> I could also imagine an additional landing page in the documentation with links to all files (including the README) which will then be directly displayed in the documentation when clicking on them. This landing page could duplicate the "File structure" section of the README with proper relative links.

This sounds promising. I just tested your idea with the following landing page, and it could look like this: 

![pynest_microcircuit_landing_page](https://user-images.githubusercontent.com/58212853/78925130-33744980-7a9b-11ea-97fd-54cf94454cd1.png)

At the moment, this is my best solution for linking files that are not ``.rst`` documents. What do you think?

**Comment by sarakonradi** [comment]
Hi @clinssen, just bringing you into this. We have begun working on the microcircuit documentation in @steffengraber's ``cp-microcircuit`` branch: https://github.com/steffengraber/nest-simulator/tree/cp-microcircuit

**Comment by clinssen** [comment]
Will you guys take care of updating `doc/microcircuit/index.rst` when you are ready? Then I can omit this in the sunsetting Python 2 PR (#1313).

**Comment by sarakonradi** [comment]
Yes @clinssen, we will take care of it! The files that you see in ``doc/microcircuit`` are outdated, so we are removing those and publishing the new documentation in ``pynest/examples/Potjans_2014`` on Read the Docs.

**Comment by jhnnsnk** [comment]
@sarakonradi 
> At the moment, this is my best solution for linking files that are not `.rst` documents. What do you think?

Please see my first comment to #1526 . The landing page is probably the neatest solution. The links should then just go the auto-generated .html files, right?

**Comment by sarakonradi** [comment]
@jhnnsnk Having discussed this matter with @steffengraber, the conversion of the README list into clickable links works. However, once it lands on Read the Docs, the .py files are converted to HTML and no longer there. Moreover, we still haven't figured out a solution for the ``reference_data``. @steffengraber suggests absolute links to be the best solution we have.
