### ISSUE TITLE
NEST on Windows subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by sepehrmn** [nest/nest-simulator#1520]
**Describe the bug**
I've been trying to use NEST on windows with WSL and Anaconda. It does compile successfully but I get errors when trying to use installcheck to run the unittests. 

**To Reproduce**
1. make install
2. make installcheck

**Desktop/Environment (please complete the following information):**
 - Shell: bash
 - Python-Version: 3.8.2
 - NEST-Version: Current master
 - cmake-version: 3.17.1
   

/home/sepehrmn/code/sepehrmn-github/nest-simulator/opt/share/nest/extras/do_tests.sh: 356: export: Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2020.5.0_x64__79rhkp1fndgsc:/mnt/c/Program: bad variable name
CMakeFiles/installcheck.dir/build.make:77: recipe for target 'CMakeFiles/installcheck' failed
make[3]: *** [CMakeFiles/installcheck] Error 2
CMakeFiles/Makefile2:580: recipe for target 'CMakeFiles/installcheck.dir/all' failed
make[2]: *** [CMakeFiles/installcheck.dir/all] Error 2
CMakeFiles/Makefile2:587: recipe for target 'CMakeFiles/installcheck.dir/rule' failed
make[1]: *** [CMakeFiles/installcheck.dir/rule] Error 2
Makefile:195: recipe for target 'installcheck' failed
make: *** [installcheck] Error 2

**Comment by sepehrmn** [comment]
One of the recent merges seems to have changed some stuff?

Here is what I get now:


NEST Testsuite Summary
----------------------
  NEST Executable: /home/sepehrmn/code/sepehrmn-github/nest-simulator/opt/bin/nest
  SLI Executable : /home/sepehrmn/code/sepehrmn-github/nest-simulator/opt/bin/sli
  Total number of tests: 648
     Passed: 636
     Skipped: 10 (9 PyNEST)
     Failed: 2 (1 PyNEST)

***
*** There were errors detected during the run of the NEST test suite!
***
*** Please report the problem at
***     https://github.com/nest/nest-simulator/issues
***
*** To help us diagnose the problem, please attach the archived content
*** of these directories to the issue:
***     - '/home/sepehrmn/code/sepehrmn-github/nest-simulator/bld/reports'
***     - '/home/sepehrmn/code/sepehrmn-github/nest-simulator/bld/reports/nest.EbuAM'
***

CMakeFiles/installcheck.dir/build.make:77: recipe for target 'CMakeFiles/installcheck' failed
make[3]: *** [CMakeFiles/installcheck] Error 1
CMakeFiles/Makefile2:580: recipe for target 'CMakeFiles/installcheck.dir/all' failed
make[2]: *** [CMakeFiles/installcheck.dir/all] Error 2
CMakeFiles/Makefile2:587: recipe for target 'CMakeFiles/installcheck.dir/rule' failed
make[1]: *** [CMakeFiles/installcheck.dir/rule] Error 2
Makefile:195: recipe for target 'installcheck' failed
make: *** [installcheck] Error 2


Full log: https://github.com/sepehrmn/nest_temp_stuff/blob/master/NEST%20issue%20%231520

**Comment by w-klijn** [comment]
To add to the information collected here:
I also get multiple errors when running make test on WSL. 
75% tests passed, 90 tests failed out of 367
Additionally the test "Start  89: unittests/test_iaf_ps_dc_accuracy.sli" hangs for 90 seconds and then succeeds

Ubuntu 18.04. Clean installation with only the necessary packages installed 

If I look in build/Testing/Temporary/LastTest.log there appear to be a bunch of MPI and "Bad file descriptor" errors.

I additionally saw a windows firewall request. 

This is a complicated challenge.

**Comment by gtrensch** [comment]
@sepehrmn 
In the meantime, some corrections have been applied to NEST that are related to NodeCollection. It is very likely that this resolves the problem. Please, can you rebuild NEST with the current master.
If this does not solve the issue, we additionally need to know:
- what's the exact Git hash,
- and which WSL distribution do you use?

**Comment by sepehrmn** [comment]
@gtrensch 

Git hash: 27dc242f1ebe19cfc916a7bc4f338e3fa3fcdd77
WSL: "Ubuntu 18.04.4 LTS (Bionic Beaver)" 


Here is with the latest master after the following steps:
1. removed bld and opt contents
2. cmake -Dwith-python=3 -DCMAKE_INSTALL_PREFIX:PATH=~/code/sepehrmn-github/nest-simulator/opt/ ~/code/sepehrmn-github/nest-simulator/src/  
3. make install -j12 - you can view the log [here](https://github.com/sepehrmn/nest_temp_stuff/blob/master/Issue_1520_update_1)
4. make installcheck 

sli: error while loading shared libraries: libnestutil.so: cannot open shared object file: No such file or directory

Phase 1: Testing if SLI can execute scripts and report errors
-------------------------------------------------------------
  Running test 'selftests/test_pass.sli'... /home/sepehrmn/code/sepehrmn-github/nest-simulator/opt/bin/sli: error while loading shared libraries: libnestutil.so: cannot open shared object file: No such file or directory

Failed: unexpected exit code 127
==================================================
Following is the full output of the test:
==================================================
/home/sepehrmn/code/sepehrmn-github/nest-simulator/opt/bin/sli: error while loading shared libraries: libnestutil.so: cannot open shared object file: No such file or directory
==================================================
***
*** An unexpected exit code usually hints at a bug in the test suite!
***
*** Please report the problem at
***     https://github.com/nest/nest-simulator/issues
***
*** To help us diagnose the problem, please attach the archived content
*** of these directories to the issue:
***     - '/home/sepehrmn/code/sepehrmn-github/nest-simulator/bld/reports'
***     - '/home/sepehrmn/code/sepehrmn-github/nest-simulator/bld/reports/nest.Gw9Zg'
***

CMakeFiles/installcheck.dir/build.make:77: recipe for target 'CMakeFiles/installcheck' failed
make[3]: *** [CMakeFiles/installcheck] Error 2
CMakeFiles/Makefile2:580: recipe for target 'CMakeFiles/installcheck.dir/all' failed
make[2]: *** [CMakeFiles/installcheck.dir/all] Error 2
CMakeFiles/Makefile2:587: recipe for target 'CMakeFiles/installcheck.dir/rule' failed
make[1]: *** [CMakeFiles/installcheck.dir/rule] Error 2
Makefile:195: recipe for target 'installcheck' failed
make: *** [installcheck] Error 2

**Comment by sepehrmn** [comment]
I did a source bashrc, will post results in a sec.

**Comment by sepehrmn** [comment]
[Here ](https://github.com/sepehrmn/nest_temp_stuff/blob/master/issue_1520_update2_installcheck)is the result of make installcheck.

**Comment by gtrensch** [comment]
@sepehrmn 

That "make installcheck" now terminates with an error is a problem caused by a recent pull request. A correction is being worked on.

Basically, NEST should also run under WSL, even if we are not currently developing and testing for this platform. We are in the process of preparing a new NEST release and the NEST master is currently experiencing many changes.

**Comment by sepehrmn** [comment]
Ah great. Let me know if you need another installcheck.

I think I'll upgrade to WSL2 when it comes out for public (next month?)

**Comment by sepehrmn** [comment]
WSL2 launch version is available to some people now. Happy to say it seems to be working fine.

Windows OS build: 19041.264
Ubuntu 18.04.4 LTS

This is the result:

  PyNEST tests: 754
     Passed: 742
     Skipped: 12
     Failed: 0

Phase 8: Running C++ tests (experimental)
-----------------------------------------
  Not running C++ tests because NEST was compiled without Boost.

NEST Testsuite Summary
----------------------
  NEST Executable: /home/sepehr/code/sepehrmn-github/nest-simulator/opt/bin/nest
  SLI Executable : /home/sepehr/code/sepehrmn-github/nest-simulator/opt/bin/sli
  Total number of tests: 1045
     Passed: 1032
     Skipped: 13 (12 PyNEST)
     Failed: 0 (0 PyNEST)

Do what you will with this issue.

**Comment by terhorstd** [comment]
Thanks a lot!
