### ISSUE TITLE
Full support for numpy arrays and lists in Connect

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#1523]
Following [a discussion](https://github.com/nest/nest-simulator/pull/1429#issuecomment-610761021) in #1429, I am adding an issue here regarding the support of lists and arrays in ``Connect``.

**Is your feature request related to a problem? Please describe.**
Currently, many forms of ``Connect`` are not supported, or require superfluous arguments:
* ``list`` objects are not supported
* using numpy arrays require both inputs to be numpy arrays and the ``syn_spec`` argument

```python
import nest
import numpy as np

# create neurons and devices
neuron = nest.Create("iaf_psc_alpha", 10)

vm = nest.Create("voltmeter", 10)

# set weights
weights = np.ones(len(neuron))
delays = np.ones(len(neuron))

# numpy version
arr_vm  = np.array(vm.tolist(), dtype=int)
arr_nrn = np.array(neuron.tolist(), dtype=int)

# works
nest.Connect(arr_vm, arr_nrn, syn_spec={'weight': weights, 'delay': delays, 'synapse_model': 'static_synapse'})

# does not work (but should)
nest.Connect(arr_vm, neuron.tolist(), syn_spec={'weight': weights, 'delay': delays, 'synapse_model': 'static_synapse'})
nest.Connect(vm.tolist(), neuron.tolist(), syn_spec={'weight': weights, 'delay': delays, 'synapse_model': 'static_synapse'})

nest.Connect(arr_vm, arr_nrn)
nest.Connect(arr_vm, neuron, syn_spec={'weight': weights, 'delay': delays, 'synapse_model': 'static_synapse'})
nest.Connect(arr_vm, neuron)
nest.Connect(vm.tolist(), neuron)
```

**Describe the solution you'd like**
All examples shown above should be accepted.

**Describe alternatives you've considered**
We are currently already checking the type of the input in ``Connect``, thus, the solution to automatically convert to ``NodeCollection`` if the ids are unique would only require a very minor overhead and no additional code complexity (just a ``check_input_nodes`` function that would replace the current test).
I am not sure why ``syn_spec`` is currently required, but, to me, when input nodes are not unique, we should be able to switch to the "data connect" without any additional argument...

**Comment by stinebuu** [comment]
@Silmathoron This is very interesting. Is the reason for

```
nest.Connect(vm.tolist(), neuron.tolist(), syn_spec={'weight': weights, 'delay': delays, 'synapse_model': 'static_synapse'})
```
that you want lists to be supported? Because or else you can just use the NodeCollections.

**Comment by Silmathoron** [comment]
Yes, of course, sorry for the potentially confusing syntax.
All examples are just to show whether the type/combination of types is accepted, so I used ``.tolist()`` for simplicity.
