### ISSUE TITLE
Exponential decay time constant in AIF models

### ISSUE THREAD

**Issue by nosratullah** [nest/nest-simulator#1527]
Dear All,

I am an MS.c. student of Computational Neuroscience and In my master thesis, I need to change the synaptic decay time constant. As I take a look at the current models, for instance in the "iaf_cond_exp" model, there's no way I could change the synaptic decay time constant. The question is, is there such a model exist so I can tune that parameter, or I should create a new model?

Best regards,
Nosratullah

Note: Sorry to ask this question on the Github page. If there's an active community or forum, I would love to let me know.

**Comment by clinssen** [comment]
In many models, there are variables called something like "tau_syn" that should allow you to set the decay time constant of synaptic current or conducatance. For example, in the "iaf_cond_exp" model, there is a "tau_syn_ex" and "tau_syn_in", for inhibitory and excitatory synapses, respectively.

Generally, you would set values for these parameters during instantiation. For example, using PyNEST, you would do something like:
```python
nest.Create("iaf_cond_exp", 42, {"tau_syn_ex" : 2.4})
```
This would create a population of 42 iaf_cond_exp neurons, each with their excitatory time constant set to 2.4 ms.

For further information, please check out our documentation at https://nest-simulator.readthedocs.io/

For further support questions, you are always welcome to contact us. We would suggest to use the NEST Users mailing list for general support (see https://nest-simulator.readthedocs.io/en/stable/contribute/mailing_list_guidelines.html). The GitHub issue system is generally used for bug reports, requests for feature enhancements, etc.

**Comment by nosratullah** [comment]
Thanks for your answer. I forgot to mention that according to documentation, the "tau_syn_ex" and   "tau_syn_in" parameters only act on alpha function. As I don't want it to act like an alpha curve, and rather want an instantaneous rise time and tunable decay time (Or maybe I just misunderstand it). I have to add that this parameter is the same no matter we use "iaf_cond_exp" or any other neuron model.
<img width="654" alt="Screen Shot 2020-04-22 at 14 00 38" src="https://user-images.githubusercontent.com/13776994/79966371-97870c80-84a2-11ea-8377-64bf52d35169.png">

Sorry for continuing this discussion over here, the mailing list gives me this error when I try to ask something:
This list is moderated, please subscribe to it before posting.

**Comment by clinssen** [comment]
That is definitely a mistake in the documentation, and we will fix it in short order. Thank you for pointing this out! The models named "*_exp" definitely have an exponentially decaying synaptic kernel, characterised by a single decay constant tau_syn. (As above it could be that there are two distinct kernels, one for excitatory and one for inhibitory synapses.)

For the mailing list, yes, you will need to subscribe first before you can post. This helps to deflect spambots.

**Comment by nosratullah** [comment]
Again, Thanks for your responses. 
I was thinking about using the beta function and set the rise time to set the rise time very fast and tune the decay time in this model: "iaf_cond_beta"
But now that I know the "*_exp" models are work just as fine, there's no need to use anything else.
Also, I guess there's another mistake in the documentation:
<img width="655" alt="Screen Shot 2020-04-22 at 14 42 57" src="https://user-images.githubusercontent.com/13776994/79970284-ea16f780-84a7-11ea-82e0-df3da5c2d56e.png">
As you see, each description comes with "Rise time" which is not correct.

And thanks for the hint for the mailing list.
