### ISSUE TITLE
Make kernel parameter off_grid_spiking read-only

### ISSUE THREAD

**Issue by morales-gregorio** [nest/nest-simulator#1529]
This issue emerged in PR  #1373 

@heplesser pointed out that the kernel parameter `off_grid_spiking` should in fact be read only, but can currently be overwritten.

**Comment by heplesser** [comment]
@morales-gregorio Could you provide a PR for this?

**Comment by morales-gregorio** [comment]
Yes, looking into it now

**Comment by morales-gregorio** [comment]
Closed by #2089
