### ISSUE TITLE
Add `install-nodoc` target

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#153]
Installation of NEST online help takes an irritating amount of time during development work, when one is frequently recompiling and reinstalling. As long as one only changes C++ code or PyNEST Python code, one can use `make install-exec` to skip installation of documentation, but this also skips installation of SLI libraries, the testsuite and examples. Therefore, we should add an `install-nodoc` target that installs everything except the online documentation.

See also #152 .

**Comment by steffengraber** [comment]
See my comment in #152.

**Comment by heplesser** [comment]
@steffengraber Given that your new solution is blazingly fast, I think we can just drop this ticket to keep complexity within bounds. This issue should be closed when #157 is merged.

**Comment by heplesser** [comment]
After some more experience,  I think we still need this feature. Building and installing the documentation under macOS can be slow, in particular when recompiling often.
