### ISSUE TITLE
Review the Synapse Models section

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#1531]
At https://www.nest-simulator.org/features/ some plasticity models that we now have are missing. Providing links for some, but not all models seems to be unsystematic, and it would be good to clarify the differences between tsodyks and tsodyks2 in the model documentation. 

 @mhelias and @abigailm could help with these questions

This is a follow up from #1388

**Comment by steffengraber** [comment]
@mhelias and @abigailm Would be nice if you could have a look.

**Comment by heplesser** [comment]
@jessica-mitchell Could you review this and consider replacing it with a follow-up issue on how to auto-generated the features lists, including links to features described?

**Comment by heplesser** [comment]
@steffengraber What is the status on this? The page in question is no longer available in the "lastest" documentation.
