### ISSUE TITLE
Neuron storing and setting weights of incoming connections

### ISSUE THREAD

**Issue by sepehrmn** [nest/nest-simulator#1544]
Hi,

In earlier NEST versions that was no good way for a neuron to set weights of its incoming connections online at every defined step. I was wondering if a standard "supported" way has been implemented in the connection and kernel revamp recently or it still requires creative ways to do this.

Much appreciated!

**Comment by sepehrmn** [comment]
Since this has been added to "To do" I presume no "Nest-core-approved" solution has been merged. I'm not up to date with the recent kernel changes and connection revamp. If the solution does not require major time investment, I could have a go at it. @heplesser we discussed this a while ago, any comments?

**Comment by clinssen** [comment]
Just my 2 cents: from the NESTML perspective this would be great, as it would give us a way to generate code for synaptic weight normalisation. For example, a typical normalisation rule would be to divide each weight by the 2-norm of the weights vector. I believe that at the time of writing, implementing this type of weight normalisation in NEST is fairly difficult.

**Comment by clinssen** [comment]
@sepehrmn: there is indeed no elegant way to accomplish this at the time of writing. We have opened an issue to describe an "official" workaround: https://github.com/nest/nest-simulator/issues/1663

If you have an idea about how to implement this in a better way, this is very welcome. However, based on earlier discussions I fear this will be quite involved.

To prevent a lot of stale issues accumulating, do you think it would be best to close this issue for the time being?

**Comment by sepehrmn** [comment]
@clinssen many thanks.

I assume that workaround involves stopping the simulation, doing the computations in python and setting the weights. I guess this issue can be closed and I'll get my stuff merged using an rport trick.
