### ISSUE TITLE
Make kernel parameter documentation in kernel and PyNEST consistent

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1554]
**Describe the flaw**
Kernel parameters are documented both [in C++ code](https://github.com/nest/nest-simulator/blob/3b22045458d9e36db5525606049ac68db0034fbb/nestkernel/kernel_manager.h#L51) and in [PyNEST](https://github.com/nest/nest-simulator/blob/3b22045458d9e36db5525606049ac68db0034fbb/pynest/nest/lib/hl_api_simulation.py#L192). The ordering of sections differs, possibly also the set of parameters documented.

**Suggest an improvement**
Align both documentation sets. Consider if we need this duplication of the same information.

**Comment by sarakonradi** [comment]
@heplesser We can adapt the C++ documentation to the PyNEST sections. I suggest doing so once we have found a solution for #1555, as the discussion regards the PyNEST parameter groupings.

**Comment by heplesser** [comment]
@jessica-mitchell Ping.

**Comment by heplesser** [comment]
> I just started making the documentation consistent and found a difference that I am unsure how to resolve: The parameter _off_grid_spiking_ is marked read-only in PyNest, but was not marked read-only in the kernel yet. I took a look at how the parameter is set and used, and I think the parameter should indeed be declared read-only.

You are right, please go ahead!
