### ISSUE TITLE
Kernel parameter documentation in PyNEST does not render properly

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1555]
**Describe the flaw**
When [kernel parameter documention for PyNEST](https://github.com/nest/nest-simulator/blob/3b22045458d9e36db5525606049ac68db0034fbb/pynest/nest/lib/hl_api_simulation.py#L192)) is rendered by Sphinx, parameter name and data type are not separated, see figure below (the non-rendered math is a user error ;), ignore).
![formatting](https://user-images.githubusercontent.com/1059644/80214741-a3f29d00-863b-11ea-83b2-d3727b9aca00.png)

**Comment by sarakonradi** [comment]
Currently, the paragraph about the keywords, the parameter subheadings ("Time and resolution, "Parallel processing", "MPI buffers") and their underlines are all split into separate items on the list: 

![Screenshot from 2020-05-04 17-51-42](https://user-images.githubusercontent.com/58212853/80985826-0879dd00-8e30-11ea-8da0-b891786a47cd.png)

We can fix the paragraph issue by moving the text into a separate "Notes" section:

![Screenshot from 2020-05-04 17-45-15](https://user-images.githubusercontent.com/58212853/80986055-5262c300-8e30-11ea-86ed-b12e213bc44d.png)
 
The subheading issue can be solved when removing the titles listed below ``Parameters``, including "Time and resolution", "Parallel processing", etc. This will then render into a clean parameter list:

![Screenshot from 2020-05-04 17-46-03](https://user-images.githubusercontent.com/58212853/80986302-ad94b580-8e30-11ea-993b-31818aad98d5.png)

However, we will lose our useful parameter groupings. 

@terhorstd @steffengraber Is there a way we could keep the parameter groupings? And to generate a series of sublists below ``Parameters``?

**Comment by steffengraber** [comment]
@sarakonradi I'll take a closer look.

**Comment by terhorstd** [comment]
What do you think about separating the parameter table from the API documentation? basically every API can set these parameters, because they are kernel parameters. I would expect a kernel documentation that describes these parameters in an interface independent way, that could just be linked from here (and from other pages).
This is of course a big gun to fix a formatting issue, but maybe worth a thought.
