### ISSUE TITLE
Add Arbor test to Travis

### ISSUE THREAD

**Issue by gtrensch** [nest/nest-simulator#1556]
Currently, the Arbor-code in NEST goes completely untested and is not even compiled. #1535 disables it by default. The Travis test matrix should be enhanced to cover Arbor testing, at least a compile of the source code.

**Comment by heplesser** [comment]
@gtrensch Would #2076 solve this?

**Comment by lekshmideepu** [comment]
Probably this is not valid anymore as Travis is closed now?

**Comment by heplesser** [comment]
@lekshmideepu I think testing the Arbor backend is still valid, just that we should do it using Github Actions.

**Comment by lekshmideepu** [comment]
@heplesser Sure. I meant mentioning "Travis" is not valid anymore. :-)
