### ISSUE TITLE
Replace fixed version numbers in documentation by custom RST directive

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1558]
In order to make it easier for users, we introduce more and more version numbers in our documentation (current and previous NEST version, required and suggested CMake version, supported Python versions, ...). These are bound to get outdated and quite a number of documentation-related PRs are actually just fixing these after users report failures with the prescribed versions.

Wouldn't it be possible (and much nicer) to instead have a custom <code>:version *object*:</code> directive for Sphinx replacing the hard-coded numbers? This could probably be implemented without too much effort by a custom Sphinx extension reading from a simple tabular file mapping object names like `cmake_required` and `cmake_suggested` to respective version numbers.

**Comment by steffengraber** [comment]
What exists for us in Sphinx so far is that you can use |version| in .rst to display the NEST version number (now 3.0) in the text.

**Comment by jougs** [comment]
Thanks for the heads up. This is already good to know!

**Comment by steffengraber** [comment]
@jessica-mitchell Would be nice if you could have a look.
