### ISSUE TITLE
Inhomogeneous poisson generator creates the same output across simulations

### ISSUE THREAD

**Issue by jimcost** [nest/nest-simulator#1562]
On separate simulations, the output from 'inhomogeneous_poisson_generator' appears identical. Here is a brief script to display the issue:

```
# -*- coding: utf-8 -*-
import nest
import numpy as np


def generator_tester():

    # Reset Kernel
    nest.ResetKernel()
    # Setup new kernel resolution
    res = 0.01
    nest.SetKernelStatus({"local_num_threads": 4, "resolution": res})

    # Create devices
    pgen = nest.Create('inhomogeneous_poisson_generator', 1, params={'rate_times': np.array([0.01, 500.0, 1000.0]),
                       'rate_values': np.array([10.0, 20.0, 10.0]), "allow_offgrid_times": True})
    sdGenerator = nest.Create("spike_detector")
    nest.Connect(pgen, sdGenerator)

    # Simulate
    nest.Simulate(1000)

    # Inhomo. Poisson generator firing events
    sdg = nest.GetStatus(sdGenerator, keys="events")[0]
    tsg = sdg["times"]
    print('Generator spike times: {}'.format(tsg))

if __name__ == '__main__':
    generator_tester()
```

Output - simulation 1:
`Generator spike times: [ 41.82  62.82 116.   277.61 415.22 492.98 495.26 495.56 561.61 563.83 578.77 612.24 619.35 735.58 825.73 857.67 869.71]`

Output - simulation 2:
`Generator spike times: [ 41.82  62.82 116.   277.61 415.22 492.98 495.26 495.56 561.61 563.83 578.77 612.24 619.35 735.58 825.73 857.67 869.71]`

Output - simulation 3:
`Generator spike times: [ 41.82  62.82 116.   277.61 415.22 492.98 495.26 495.56 561.61 563.83 578.77 612.24 619.35 735.58 825.73 857.67 869.71]`

Also, I played around with setting both `nest.SetKernelStatus({’grng_seed’ : msd+N_vp})` and `nest.SetKernelStatus({’rng_seeds’ : range(msd+N_vp+1, msd+2*N_vp+1)})`, without changing the poisson outputs. And, the latter argument causes an error - leading me to believe 'rng_seeds' no longer exists as an argument (?).

 - OS: Fedora 31
 - Python-Version: 3.7.7
 - NEST-Version: 2.20, installed from source

**Comment by heplesser** [comment]
@jimcost Thank you for providing a complete reproducer!

If a NEST simulation is run multiple times starting from a clean kernel (after `ResetKernel()` or starting nest), it will always use the same random number sequences and will thus produce the same spike times. You need to seed the random number generators explicitly. For me,
```python
    nest.SetKernelStatus({"local_num_threads": 4, "resolution": res,
                          'grng_seed': msd,
                          'rng_seeds': [msd+1+i for i in range(4)]})
```
works: for every value of `msd` I obtain a different sequence of spike times:
```
Generator spike times [msd: 1]:
    [115.75 136.5  195.64 371.96 444.11 460.08 535.36 553.49 597.56 623.08
 764.2  787.55 818.14 888.33 927.2  980.5  981.71]

Generator spike times [msd: 2]:
    [ 14.54 157.68 228.15 370.25 475.   619.19 658.21 675.16 895.59 905.55
 920.35 945.31 966.3 ]

Generator spike times [msd: 3]:
    [399.46 418.48 543.8  555.02 590.28 617.41 618.19 844.92 887.5  905.29
 909.36 941.39 968.5  994.82]

Generator spike times [msd: 4]:
    [181.79 243.55 524.2  545.93 755.02 894.42]
```
(I used `nest.set_verbosity('M_ERROR')` right after `import nest` to suppress some NEST output).

I am surprised that trying to set `rng_seeds` gave you an error. Could you double check and if the error persists post the precise command you used and the error message you received?

**Comment by jimcost** [comment]
The addition of `grng_seed` and `rng_seeds` produce variable output, as you should. Formerly, I was including `grng_seed` and `rng_seeds` separately. `grng_seed` would be acccepting by itself without error, but `rng_seeds` alone would cause an error.

Thank you for your reply :+1:
