### ISSUE TITLE
Link model_details from documentation pages

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1568]
**Describe the flaw**
The notebooks in `doc/model_details` are currently only linked from some comments in code or from Github issues/PRs.

**Suggest an improvement**
Provide a page within the documentation that links these notebooks, so they become more discoverable for users. At least some notebooks are useful for users to understand model behavior.

**Additional context**
See also #1168.

**Comment by clinssen** [comment]
I suggest to link these in the documentation pages of the models for which they are relevant. That is, they should be linked from inside the API documentation comment blocks in the model code.

**Comment by jessica-mitchell** [comment]
@heplesser I started taking a look at this and I have a few questions:

1. The name _model_details_ seems rather vague to me,  could we change the folder name for something more descriptive?
2. It's also not clear to me why we have these particular examples together (what do they have in common  with each other?) We easily could add a section to the PyNEST examples page, listing all the notebooks but it would be good to indicate what they're there for.
3. As for linking the notebooks to the model API as @clinssen mentions, would the _aeif_models_integration.ipynb_ and _iaf_neurons_singularity.ipynb_ need to be linked in all models related to aeif and iaf, respectively?

**Comment by clinssen** [comment]
This organisation stems from wanting to document, for example, the derivation of equations of a model, or other implementation details. This is often too much detail to include in the model documentation itself, and these pieces of documentation are often shared between several models (as you point out in point 3).

I would suggest to link the notebooks in the ``model_details`` from each model documentation page where it is relevant, but not create a separate index page for all the files in ``model_details``. For an example, see the second "Note" panel on https://nest-simulator.readthedocs.io/en/latest/models/iaf_psc_alpha.html (obviously this needs some minor syntactic fixes). I checked previously (although many months ago) that all existing files in ``model_details`` are linked from at least one model.

As for directory organisation, I don't have any ideas for how to improve over ``extras/model_details``. The name is at least somewhat descriptive ("further model details beyond the model documentation itself").

**Comment by heplesser** [comment]
I agree with @clinssen.
