### ISSUE TITLE
Ensure that all doc/model_details notebooks work

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1569]
Before releasing NEST3, ensure that all notebooks in `doc/model_details` are compatible with NEST3. Currently, at least `test_post_trace.ipynb` does not.

See also #1168.

**Comment by stinebuu** [comment]
@heplesser [exact-integration.ipynb](https://github.com/nest/nest-simulator/blob/master/doc/model_details/exact-integration.ipynb) doesn't have any calculations, it is just documentation about *Integrating neural models using exact integration*. Should it stay as a notebook, or should I convert it to a rst file and place it somewhere else, for instance under `doc/models`?

**Comment by heplesser** [comment]
I think I wrote it as a notebook because of all the math in it. If you can port the LaTeX to RST without too much effort, why not? On the other hand, @sarakonradi, this raises also the question if we want to have certain standard formats for certain types of documentation, here rst vs notebook.

**Comment by sarakonradi** [comment]
@heplesser @stinebuu We just discussed this in our doc meeting and think that it makes sense to convert it to a RST file. For that, we need to ensure that we use ``.. math::`` for the math blocks and ``:math:`` inline. 

It can stay at its current location for now. In the future, we suggest moving it to a "notebooks" directory in the ``nest/nest-education`` repository.

**Comment by stinebuu** [comment]
Thanks @sarakonradi, I'll convert using `.. math::` as you suggest and request a review from you once a PR is ready to make sure everything is as it should.

**Comment by sarakonradi** [comment]
@stinebuu Sure! Sounds good.
