### ISSUE TITLE
Rename spike_detector to spike_recorder

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1579]
During the work on the documentation, it became obvious that all our detectors (except the `spike_detector`) are neither derived from the base class `RecordingDevice` nor are they using the recording backend infrastructure brought by NESTio/Output. Instead most of them are derived from `PseudoRecordingDevice` and they rather calculate a measurement of some dimension and report it in their status dictionary.

The `spike_detector` on the other side is actually derived from `RecordingDevice` and using the recording backend framework. I thus propose to rename it to `spike_recorder` in analogy to the `weight_recorder` for easily distinguishing the two concepts in the documentation and get a more consistent grouping by keywords.

It could also make things clearer, if we renamed `PseudoRecordingDevice` to something like `MeasuringDevice` (as `DetectingDevice` sounds weird to me...).

I know that this will lead to further breakage of simulation scripts and examples, but if we don't do this now, when then?

**Comment by heplesser** [comment]
@jougs This is a good point. I wonder if we should think a bit further then. The other "detectors" you mention are all "correl*_detectors" if I am not mistaken, and I assume they were historically named "detectors" inspired by he "spike_detector". But as you point out, they perform analysis on data while the simulation is running. So I wonder if we should not rename them as well? Should we put this on the agenda of the [Open Developer VC on Monday (after the NC/Connect semantics item)](https://github.com/nest/nest-simulator/wiki/2020-05-11-Open-NEST-Developer-Video-Conference)?

**Comment by terhorstd** [comment]
I added this to the agenda of the [next meeting](https://github.com/nest/nest-simulator/wiki/2020-05-25-Open-NEST-Developer-Video-Conference) (25. May)

**Comment by terhorstd** [comment]
sorry, wrong button

**Comment by jougs** [comment]
I wouldn't have minded if you would have resolved the issue even before we discussed it ;-)

**Comment by jougs** [comment]
In a keyword-to-model-assignment meeting today, @abigailm raised the following points:
1. from a language perspective, _recorder_ and _detector_ are pretty much the same thing and these terms should not be used to draw a line between two classes of devices 
1. the suffix _detector_ used for the correlation measurement devices is actually misleading, as it suggests that the devices are just detecting some event, while they are actually collecting events and carry out some form of analysis
1. If it turns out that there is an actual need for these different concepts, devices that only analyze but are unable to write them out via recording backends should rather be called _analyzer_ than _detector_.

@mhelias: can you please remind us a bit on why the `corr*_detector`s are derived from a special `PseudoRecordingDevice` base class and why they are not writing their data out like all other recorders are? What would it take to make them do that? As the initial developer of those devices, you might be able to give us the historical perspective, we can't quite remember anymore. Thanks!

Mentioning @sarakonradi, @steffengraber and @terhorstd as this also pertains to how we present the different devices in the documentation.

**Comment by Silmathoron** [comment]
I agree with @abigailm points and I would not be in favor of renaming ``spike_detector``, the issue of the other special devices seems different and I have no strong opinion on that matter.

**Comment by jougs** [comment]
@mhelias: ping!

**Comment by jougs** [comment]
Here's a short update after we discussed this issue again during the [recent hackathon](https://github.com/nest/nest-simulator/wiki/NEST-Hackathon-01.07---03.07-2020). Our conclusions go like this:
* *Spike detection* in NEST is technically happening inside the neuron model (in the form of a threshold check or something similar). The device currently known as `spike_detector` is really only recording the already detected spike and will thus be renamed to `spike_recorder`.
* The other devices that are currently called `*_detectors` are actually also not detectors, but, as they also are not recording anything, they will be renamed to `*_analyzer`. In the future, these devices should probably be replaced by a solution based on the in situ transfer of data out of NEST and analysis in an external tool like [Elephant](https://neuralensemble.org/elephant/)

Fixing this issue consists of the renaming of the devices and updating all tests, examples and documentation and renaming the `PseudoRecordingDevice` base class to `AnalysisDevice`.

**Comment by stinebuu** [comment]
Fixed with #1697
