### ISSUE TITLE
Documentation on nest and multi-processing / multi-threading

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1581]
**Describe the flaw**
The simulator is built for parallel processing, but having many nodes in a cluster it is tempting to try to use python's multiprocessing package to speed up also other parts of the simulation scirpts. Information on the possible scenarios, relation to Python's multi-processing API, or multi-threading with other communications libraries is missing.

**Suggest an improvement**
References to a conceptual document describing the mpi/threading environment should be in relevant sections of guides and reference docs.

**Supporting materials**
Was [discussed](https://www.nest-simulator.org/mailinglist/hyperkitty/list/users@nest-simulator.org/thread/ZAXHALXHJTUOOX4VGD3T2FIMWNNNTILE/#ZAXHALXHJTUOOX4VGD3T2FIMWNNNTILE) on [NEST mailing list](https://nest-simulator.org/mailinglist)

**Desktop/Environment**
relevant for all users of clusters or multi-core hardware.

**Comment by juanmav** [comment]
@terhorstd I dont know but maybe it could help. Here the sample code that I made to test multiprocessing with nest. https://github.com/juanmav/spiking/blob/master/smalltestcase.py

**Comment by sarakonradi** [comment]
@juanmav Thanks for the sample code!

@heplesser I remember that, in the [mailing list](https://www.nest-simulator.org/mailinglist/hyperkitty/list/users@nest-simulator.org/thread/ZAXHALXHJTUOOX4VGD3T2FIMWNNNTILE/#ZAXHALXHJTUOOX4VGD3T2FIMWNNNTILE), you emphasized the importance of **not** using multiprocessing with NEST and that there are currently no scenarios where it is okay to use Python's multiprocessing API, at least not until we have a careful assessment about the interactions between NEST and multiprocessing. 

Would it be best to add a note on this no-no to the [Guide to parallel computing](https://nest-simulator.readthedocs.io/en/latest/guides/parallel_computing.html#using-multiple-threads)? Or do we also need a conceptual document? Could we make use of @juanmav's sample code?

**Comment by sarakonradi** [comment]
@suku248 Do you happen to know of any already existing conceptual document, where this has been looked into? Input from the kernel team is much appreciated.

**Comment by suku248** [comment]
@sarakonradi I am not aware of any documentation on this topic. I don't think that the publications on PyNEST explicitly discourage users from using Python packages for multiprocessing on top of NEST's internal parallelization based on MPI/OpenMP.

I guess that such optimization attempts by NEST users typically target the network-construction phase (and not the actual simulation phase). Therefore, in the documentation for this issue it might be a good a idea to mention the work of [Ippen et al. (2017)](https://doi.org/10.3389/fninf.2017.00030), which shows that NEST is already good at building a network in parallel.
