### ISSUE TITLE
Remove ability to set custom documentation and library directories

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1585]
As detailed in #972, the ability to change the documentation and library search paths for NEST through the environment variables `NEST_DOC_DIR` and `NEST_DATA_DIR` can lead to problems.

This feature stems from a time, when NEST and its library were not formally installed, but could be located anywhere on the computer of the user. Current versions of NEST install documentation and library into a well-defined location, which is always known to the simulation kernel and thus renders this feature superfluous. The only such variable, I suggest to keep is the `NEST_INSTALL_DIR` variable to allow users to move their installation directory and 

I thus propose to
* express the documentation and library search paths in the kernel relative to the compile time prefix (or `NEST_INSTALL_DIR`, if set)
* provide access to the documentation and library search paths via `GetKernelStatus`
* remove all code handling the environment variables `NEST_DOC_DIR` and `NEST_DATA_DIR` from `SLIStartup`
* remove the setting of `NEST_DOC_DIR`, `NEST_DATA_DIR` and `NEST_INSTALL_DIR` from `nest_vars.sh`
* replace code involving `NEST_DOC_DIR`, `NEST_DATA_DIR` and `NEST_INSTALL_DIR` in  PyNEST by code achieving the same based on the entries in the kernel status dict

**Comment by heplesser** [comment]
@jougs How does this differ from/relate to #1586?

**Comment by jougs** [comment]
I would extend #1586 to actually implement all points mentioned above, not just the "not setting the variables" part it currently implements.

**Comment by jougs** [comment]
Ah, now I inderstand! This is actually a duplicate of #1586 that was apparently created when GitHub told me it can't create the issue, but nonetheless created it. I'm closing this one.
