### ISSUE TITLE
Clean up handling of path-related environment variables

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1586]
As detailed in #972, the ability to change the documentation and library search paths for NEST through the environment variables `NEST_DOC_DIR` and `NEST_DATA_DIR` can lead to problems.

This feature stems from a time, when NEST and its library were not formally installed, but could be located anywhere on the computer of the user. Current versions of NEST install documentation and library into a well-defined location, which is always known to the simulation kernel and thus renders this feature superfluous. The only such variable, I suggest to keep is the `NEST_INSTALL_DIR` variable to allow users to move their installation directory and 

I thus propose to
* express the documentation and library search paths in the kernel relative to the compile time prefix (or `NEST_INSTALL_DIR`, if set)
* provide access to the documentation and library search paths via `GetKernelStatus`
* remove all code handling the environment variables `NEST_DOC_DIR` and `NEST_DATA_DIR` from `SLIStartup`
* remove the setting of `NEST_DOC_DIR`, `NEST_DATA_DIR` and `NEST_INSTALL_DIR` from `nest_vars.sh`
* replace code involving `NEST_DOC_DIR`, `NEST_DATA_DIR` and `NEST_INSTALL_DIR` in  PyNEST by code achieving the same based on the entries in the kernel status dict

**Comment by jougs** [comment]
@heplesser: is this (at least coarsely) what you were asking for in https://github.com/nest/nest-simulator/issues/972#issuecomment-625257374?

@clinssen: is a good description of what #1578 should do, now #1561 solved #972?

**Comment by clinssen** [comment]
Yes, this clears up the intended effects, cheers!
