### ISSUE TITLE
Minimize requirements and optimize debian package

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#1589]
Follow up of #1472 
There was an discussion about using separate boostlibs and some other minimizations, we want to discuss here.
Due to new developments in the installation of Nest this should  also be adjusted.

**Comment by heplesser** [comment]
@steffengraber Ping!

**Comment by steffengraber** [comment]
These adjustments are part of the work on the package. Therefore, the issue can be closed here for the time being. If there is a need, it can be reopened.
