### ISSUE TITLE
CMake doesn't terminate when the requested package is not found in Travis

### ISSUE THREAD

**Issue by lekshmideepu** [nest/nest-simulator#1601]
It looks like CMake doesn't terminate when the requested package like  Python is not found in the Travis build environment.
https://travis-ci.org/github/nest/nest-simulator/jobs/686740291#L904
https://travis-ci.org/github/nest/nest-simulator/jobs/686740291#L1537
https://travis-ci.org/github/nest/nest-simulator/jobs/686740291#L1578
https://travis-ci.org/github/nest/nest-simulator/jobs/686740291#L7736

**Comment by lekshmideepu** [comment]
@heplesser It doesn't look like CMake terminates when [GSL libraries are not found ](https://travis-ci.org/github/lekshmideepu/nest-simulator/jobs/691663150#L1526)although the environment variable is set ON

**Comment by heplesser** [comment]
OK, so the problem is more general and we would need a way to check if NEST has been built with the components we requested. Can we query the results of CMake in a sensible way and compare with our results? Or parse the `config.h` generated?

**Comment by heplesser** [comment]
@lekshmideepu Is this still relevant now that we use Github actions? The general problem, namely that NEST runs a reduced test suite when not finding, e.g., GSL, is probably independent of where we run the tests?

**Comment by heplesser** [comment]
@lekshmideepu Closing for now, please re-open and rename if you still think it relevant.
