### ISSUE TITLE
Get distances from SynapseCollection of spatially structured network

### ISSUE THREAD

**Issue by jhnnsnk** [nest/nest-simulator#1616]
**Is your feature request related to a problem? Please describe.**
I would like to have an easy way to get a list of distances between sources and targets from a `SynapseCollection` of a spatially structured network. Right now there is only the function `Distance()` which requires positions or `NodeCollections` as arguments, but does not accept the sources and targets of a SynapseCollection.

**Describe the solution you'd like**
```
syncoll = nest.GetConnections()
distances = syncoll.get('distance')
```

**Describe alternatives you've considered**
An alternative would be the other way round:
```
distances = nest.Distance(syncoll)
```

**Additional context**
Of course, the distances only need to be computed if required.

**Comment by stinebuu** [comment]
@jhnnsnk should the distance be the distance between the source, target pair, so the `SynapseCollection` has to have the same number of sources and targets, or should it be distance between *every* source and target in the `SynapseCollection`? In the first I guess we would return a list with distances, while in the second a list of list where the inner list is a list of positions between the source in that index and all targets, or something similar.

**Comment by stinebuu** [comment]
`nest.Distance(src, trgt)` returns a list of distances between the src, trgt pair, so maybe do the same for the `SynapseCollection` version for consistency?

**Comment by jhnnsnk** [comment]
@stinebuu Yes, I would be interested in just one list with the distances between source-target pairs, in line with the output of the `Distance()` function. Thanks for the clarification.
