### ISSUE TITLE
Reduce redundancy in the NEST docuverse

### ISSUE THREAD

**Issue by jd41** [nest/nest-simulator#1634]
This issue is complementary to #1635.
By "docuverse", I refer to the extant content that is supposed to describe NEST or adjacent projects (like NEST-Desktop/NestML), i.e. Sphinx documentation, help_generator/Doxygen documentation, websites, developer space, error messages in the program, docstrings... I gathered resources I found in #1633, but have surely missed something.

I currently find lots of places where content that is apparently intended to answer the same question to the same group of people appears several times. Sometimes, content is even copied verbatim. This is bad, because it bloats the documentation (making it harder to get an overview of what exists), makes it harder to maintain, gives more work to a person who wants to exhaustively check the docs before asking their colleague or writing to the mailing list. I think it is generally preferable to document something once, and generously link/refer to it from other places where a user might wonder or should be informed about that question.

Examples I found:

Interested person wants to know what NEST is in the first place:

- nest-simulator.org home page

- readthedocs start page

- README in GitHub

- ...?

New user wants to get an overview over documentation/support resources:

- Message during startup/after import nest in Python

- nest.helpdesk() Python

- NEST HelpDesk local webpage

- "How this documentation is organized" in the Read the Docs main page

- "Getting help" page in Read the Docs

- "Getting help" in README

- section of Part 1 of the NEST+PyNEST tutorial

- ...?

How to cite NEST:

- part of README on GitHub

- https://nest-simulator.readthedocs.io/en/stable/citing-nest.html (doesn't seem to appear in the Read the Docs Toctree - is this an orphan node?)

- section of https://www.nest-simulator.org/

- ...?

Installing NEST:

- INSTALL in GitHub repo

- https://nest-simulator.readthedocs.io/en/stable/installation/index.html (actually, mac_manual can't be clicked there)

- ...?

spike_detector and other detector/recording devices:

- Recording guide

- spike_detector reference doc (but this doesn't contain any reference that more parameters/Status dictionary entries are described in the Recording guide)

Often, many or all of these resources have their flaws (a consequence of the attention being distributed).
I guess that I am only, um, scratching the tip of the iceberg here, so I think a systematic hunt for these issues - and getting an overview over what actually exists in the docuverse right now before trying to organize it - is warranted.

**Comment by jd41** [comment]
How to build documentation:
- doc/README.md
- NEST Documentation Workflow: https://nest-simulator.readthedocs.io/en/latest/documentation_workflow/user_documentation_workflow.html

**Comment by jd41** [comment]
Case in point, a problem that likely wouldn't exist if not for such redundant information: #1783.

**Comment by heplesser** [comment]
Closing, the NEST doc team is on this.
