### ISSUE TITLE
Improve discoverability in the NEST docuverse

### ISSUE THREAD

**Issue by jd41** [nest/nest-simulator#1635]
This issue is complementary to #1634. Again, with "docuverse" I refer to all the extant NEST-related content.

I found several instances in the NEST documentation where a link to other content would be helpful, but was missing. Examples:

- the Read the Docs documentation for spike_detector doesn't link to the Recording device guide, which contains further parameters/instructions.
- The SLI tutorial doesn't reference the SLI vim syntax file
- The SLI tutorial parts don't explicitly mention they are parts of a tutorial/link to the other parts.

A systematic approach to find them would be to generate a list of backlinks for each page, and think about whether that list can be improved.

I will submit a small pull request for the second item later.

I open this issue for people to submit other instances.

**Comment by jd41** [comment]
#1638 is the promised pull request.

**Comment by jd41** [comment]
(updated issue text after seeing I didn't complete it somehow)

**Comment by sarakonradi** [comment]
Closed after discussing this with @jessica-mitchell
