### ISSUE TITLE
unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#1649]
On aarch64 with trunk Clang I see a lot of:

```
[  2%] Linking CXX shared library libnestutil.so
/usr/bin/ld: warning: /home/users/itaru.kitayama/opt/clang/202006161232/bin/../lib/libomp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
[  2%] Built target nestutil
```

Can a building service include trunk Clang as well we those older stable releases?

Here's my CMake config:
```
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -Dwith-python=OFF /tmp/nest-simulator/
```

**Comment by heplesser** [comment]
@ikitayama This seems to be a compiler bug: https://github.com/ClangBuiltLinux/linux/issues/1054

**Comment by ikitayama** [comment]
If I use LLD, that goes away though.

**Comment by ikitayama** [comment]
I’m still not certain as how we can tell CMake about LLD if I want to.

**Comment by nickdesaulniers** [comment]
The issue is using ARMv8.3 Pointer Authentication (PAC) when building with Clang, but using an older version of GNU binutils that doesn't support PAC.  @ikitayama can you use LLD to link?  Virtually all tools in binutils will produce this error, so it may be easier to avoid using PAC until you've upgraded your GNU binutils.

**Comment by ikitayama** [comment]
I will. Do you happen to know The minimal binutil version that supports PAC?

**Comment by nickdesaulniers** [comment]
The kernel commit references GNU binutils 2.33.1: https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?id=4dc9b282bf5f

**Comment by ikitayama** [comment]
@Nick Desaulniers <ndesaulniers@google.com> thanks! I'll ask the local
admin to add it as an Lmod module then.

**Comment by gtrensch** [comment]
@ikitayama  Has this problem been resolved and can it be closed?

**Comment by ikitayama** [comment]
Sure yes please

**Comment by terhorstd** [comment]
Thanks
