### ISSUE TITLE
Broken links "Edit on GitHub" in documentation

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1655]
**Description of the flaw**
On generated pages like the new model directory, the single page edit links do not work. There is a "Edit on GitHub" button in the top right corner, e.g. in https://nest-simulator.readthedocs.io/en/latest/userdocs/iaf_cond_alpha.html that leads to a non-existing GitHub page.

Mainly Model directory entries in current 'latest' build of the documentation on readthedocs are affected, leading to a 404 on GitHub. The 2.x documentation points to a dummy file, which doubtfully is of more use.

**Suggested improvement**
This should point to the file that contains the sources of the documentation, such that it is easy to suggest fixes by users.

**Additional context**
Sphinx would need to know which source file the documentation was extracted from and point to that source file.

**Comment by clinssen** [comment]
This is a problem for NESTML as well, as some of the documentation is automatically generated and/or pre-processed in ``conf.py``, so no backlinks exist.

The "Edit on GitHub" links can only be turned on or off globally. We could consider just turning them off.

Alternatively, I think this could easily be solved upstream by checking the HTTP response for a 404 error code.

**Comment by clinssen** [comment]
See also: https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html
