### ISSUE TITLE
How is voltage_trace supposed to be shown?

### ISSUE THREAD

**Issue by BSVogler** [nest/nest-simulator#1657]
**Describe the flaw**
In this commit 87edd9e4a10aa3524be223a499b03293ac34a579 the show method was removed. It is still included in the documentation in the examples, putting the examples in a non-working state, and making me wonder how to plot the voltages.

Examples:
https://nest-simulator.readthedocs.io/en/latest/auto_examples/one_neuron.html
https://nest-simulator.readthedocs.io/en/latest/auto_examples/twoneurons.html

**Suggest an improvement**
Replace code how the voltage is supposed to be plotted with a working version.

**Comment by BSVogler** [comment]
I figured it out how to plot it. Apparently, this needs to be added
```
import matplotlib.pylab as plt
plt.show()
```

**Comment by jougs** [comment]
I just re-assigned to myself as I'm the original author of the `voltage_trace` submodule (and `raster_plot`, which probably exhibits a similar issue). However, on second thought, I am now a bit unsure if the code should be changed, or if rather just the documentation has to be extended/fixed/clarified.

Two thoughts on this:
* As it right now, we have a hard dependency on matplotlib for the plotting submodules. I think this is fine given that plotting is their only purpose.
* As we don't actually try to show plots, everything also runs nicely on headless machines, which is important for running the examples on Travis CI.

@BSVogler: would it be fine from your perspective if the code was left as it was and the magic lines were added somewhere to the documentation of the examples using `voltage_trace` or `raster_plot`?

**Comment by BSVogler** [comment]
I think there is a misunderstanding. I just meant that this code needs to be added to the documentation because the example code is not compatible. I can fix this by myself in the next weeks (currently busy with my thesis).

Your argument is solid. I suggest that your elaborated considerations should be documented somewhere. Right now the behavior changed and the users (like me) have to guess how to use the library and developers don't know why it works that way.

**Comment by jougs** [comment]
Alright. We usually try to follow the principle of least surprise, which dictates that users don't have to guess.

@sarakonradi: I'm reassigning back to you and trust that you add something reasonable to the corresponding documentation. Feel free to mention me again if you have additional questions.
