### ISSUE TITLE
Integrate Sphinx documentation generation with CMake

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1660]
Currently, the Sphinx documentation is built using a standalone `Makefile` in the `doc` directory. This has several downsides:
1. Running that `Makefile` requires to `cd` into the `doc` directory, which is at least inconvenient.
1. The `Makefile` for the documentation is hard to find, as it is somewhat uncommon to have two parallel build systems.
1. The extracted documentation ends up in the source directory instead of in the build directory, where it should actually be. Here are some points why this is bad:
   - It requires keeping a list of build artifacts in the `.gitignore` file. If that's incomplete or outdated, `git status` and `git checkout` will get confused.
   - It complicates refactorings, as many search matches will be in generated files that should not need to be touched.
   - Although `git clean -dX` will remove the generated files in most cases, it might fail and lead to further confusion.

I thus propose to integrate the documentation extraction workflow under a new `doc` or `sphinx` target in the regular CMake-based build system.

**Comment by jougs** [comment]
@steffengraber: any news on this?

**Comment by jougs** [comment]
@steffengraber: Do you need assistance with this or is there any other way I can help to speed this up? I am usually working on multiple branches concurrently and really find it quite annoying that I can't have the documentation for each of them in the corresponding build directory and that the one in the source directory does oftentimes not reflect the branch I'm actually on. Should we maybe organize a joint session in the hackathon for this?

**Comment by steffengraber** [comment]
@jougs 
> Should we maybe organize a joint session in the hackathon for this?
Yes, sure. When? Tomorrow after 10.00 looks good.

**Comment by jougs** [comment]
Great! I've scheduled a session for tomorrow 11:00 to 12:30.
