### ISSUE TITLE
Make references to NEST installation prefix consistent

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1661]
**Describe the flaw**
The NEST documentation refers to the installation prefix (set using `-DCMAKE_INSTALL_PREFIX:PATH=...` when running CMake) in a lot of places. However, the exact wording used is not very consistent. A quick search reveals (at least) the following ways of saying the same thing:
* `<prefix>/bin/nest`
* `$PREFIX`
* `</install/path>`
* `</path/to/nest_install_dir>`

**Suggest an improvement**
Use one consistent way of talking about the installation prefix and maybe provide a RST template so things can more easily be kept consistent in the future.

**Comment by jougs** [comment]
Just a short update: I actually like the `<prefix>` variant the most, as it does
1. not imply that the prefix is in a shell/environment variable (which the `$` variant does) and
2. does not require the reader to split an unknown path at the right location, which the `/path/to/install` variant does.

**Comment by heplesser** [comment]
> Just a short update: I actually like the `<prefix>` variant the most, as it does
> 
> 1. not imply that the prefix is in a shell/environment variable (which the `$` variant does) and
> 2. does not require the reader to split an unknown path at the right location, which the `/path/to/install` variant does.

I agree almost with Jochen, but wonder a little if `<prefix>` is too unspecific. How about
- `<nest_install_prefix>`
- `<nest_install_dir>`

Which variant would be most intuitive/comprehensible for a user just "nerdy" enough to install NEST from source, but not a developer?
Best,
Hans Ekkehard

**Comment by jougs** [comment]
What about `<cmake_install_prefix>` as that (minus the caps) is also used when running CMake? This way we'd just re-use an existing term instead of introducing yet another one.

**Comment by terhorstd** [comment]
After some discussion @sarakonradi, @steffengraber and I concluded that `<nest_install_dir>` would be most appropriate:
* very general that can also be used in other explanations not related to cmake, e.g. `source <nest_install_dir>/bin/nest_vars.sh`
* it is (minus the caps) also the env variable exported by `nest_vars.sh`, so it
  *  does not introduce a new name
  * it is equal to the name for nest *usage* and not equal to the name used in nest configuration
* `_prefix` may not be as intuitive as `_dir` to novice users
