### ISSUE TITLE
After compiling, I modified the code and recompile NEST. Why did not the modified code take effect?

### ISSUE THREAD

**Issue by jhang-liu** [nest/nest-simulator#1664]
I compiled NEST successfully. But after I modified the code, the new code didn't take effect.

**Comment by clinssen** [comment]
Could you give some more information? Which steps did you take to build NEST? Did you follow the instructions on https://nest-simulator.readthedocs.io/en/nest-2.20.1/installation/linux_install.html? What paths are you installing to? Please post the logs (e.g. cmake output, error message).

Changing code in the source directory, and then running ``make && make install`` should certainly work.
