### ISSUE TITLE
Incorrect connections are returned by GetConnections

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#1670]
**Describe the bug**
When multithreading is used, some additional connections are returned by ``GetConnections`` when using the ``source`` keyword (might occur for other keywords in different circumstances).

**To Reproduce**
```python
import nest

nest.SetKernelStatus({"local_num_threads": 6})

nn = nest.Create("iaf_psc_alpha", 1000)

pg = nest.Create("poisson_generator")

nest.Connect(pg, nn)

sd = nest.Create("spike_detector")
nest.Connect(nn, sd)

conn = nest.GetConnections(source=pg)
print(len(conn))

pg_gid = pg[0]

print([c for c in conn if c[0] != pg_gid])
```
prints ``1004`` and

    [array('l', [998, 1002, 2, 15, 0]), array('l', [999, 1002, 3, 15, 0]), array('l', [1000, 1002, 4, 15, 0]), array('l', [997, 1002, 1, 15, 0])]

**Expected behavior**
Should print ``1000`` and ``[]``.

**Desktop/Environment (please complete the following information):**
 - OS: Manjaro
 - Python-Version: 3.8
 - NEST-Version: 2.20.1 (fbd272e107a69f5df159595ee5b216bb78e4b193)

**Comment by terhorstd** [comment]
If this is confirmed, it should also be added to the tests.

**Comment by terhorstd** [comment]
could be related to #1636

**Comment by hakonsbm** [comment]
I tested, and it seems like the fix in #1636 doesn't seem to fix this issue.

**Comment by stinebuu** [comment]
@jougs, @terhorstd Do you know if anybody is working on this? It should probably be worked on so we can release 2.20.1.

**Comment by jougs** [comment]
I am not working on it and am not aware of anyone who is.
