### ISSUE TITLE
Add first NEST version a model became available to model description

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1681]
In #1530, we removed the `FirstVersion` and `Author` fields from the model documentation because it was mostly outdated, wrong, or useless, as it only contained manually added names and missed all further contributors.

When revisiting this change during the [recent hackathon](https://github.com/nest/nest-simulator/wiki/NEST-Hackathon-01.07---03.07-2020), we concluded that the author information should not be in the documentation, as it can always be gotten from `git log`. The first version information would, however, be useful, but instead of hardcoding it into the documentation, it should rather be added automatically by the doc extractor. The algorithm for this would roughtly be the following:
1. Check the date, when a certain model file was added to the repository
2. Find the first major release after that date
   * if such a release exists, add the version number to the model documentation under a new `Available since` headline
   * else (i.e. it was already there prior to the move to git) add `NEST 2.0` as version number

As the releases contain all contributing authors and the exact commit can be traced from there using the PR number, this also solves the credit assignment problem.

**Comment by heplesser** [comment]
Closing.
