### ISSUE TITLE
ImportError: No module named html

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#1683]
During the execution of install target, I see:

```
[...]
-- Install configuration: "Debug"
Traceback (most recent call last):
  File "generate_help.py", line 32, in <module>
    import html
ImportError: No module named HTML
[...]
```

**Comment by ikitayama** [comment]
Can I use Python 2?

**Comment by clinssen** [comment]
Only Python 3 is supported.

Have you tried: ``sudo pip3 install html`` or ``pip3 install html``?

In case that solves the problem, we should make sure that the "html" Python package is included in the installation dependencies documentation.

**Comment by ikitayama** [comment]
Ah okay. My system HPE Apollo is configured to invoke Python 2 via
/user/bin/python.
Python 3 is called with pyhton3 command.

I’d like to avoid messing around my dev env, thus no pip at this moment.

**Comment by ikitayama** [comment]
As I’ve been using NEST with -Dwith-python=OFF for some time, I’ve never cared about it the 2 and 3 differences. Other than installation do we assume python 3 presence somewhere else?

**Comment by clinssen** [comment]
The default recently changed to turn building of Python bindings on by default, instead of off by default as it was before.

If you don't need Python binding, you can still use ``-Dwith-python=OFF``.

I believe the only other location (besides PyNEST) where Python is used, is in the unit tests (cc @jougs).

**Comment by jougs** [comment]
The testsuite will only use the Python version configured through CMake to run the PyNEST tests. For all "normal" tests written in Python and for auxiliary tasks it uses the plain `python` command, whatever that might be. However, the testsuite will most likely fail unpredictably if that is a Python version < 3.5, as all workarounds for those have been removed from the code.

Please note that Python 2 reached end of life 1st of January 2020 (and 3.4 even already in March 2019) and we're not going to provide any support whatsoever for dead versions.

An easy (albeit untested) workaround should be to `alias` the `python` command to a version >= 3.5 in the local execution environment.

@sarakonradi: can you please take care of documenting the dependency on the `html` module in the appropriate location and close this issue once that is done? Thanks!

**Comment by ikitayama** [comment]
@jougs I just checked in CentOS 8, Python 3 needs to be called with python3, not python. Is this specific to
CentOS and RHEL? Which distribution are you mainly on?

**Comment by ikitayama** [comment]
Ubuntu just installs python3 under /usr/bin, no python binary.

**Comment by ikitayama** [comment]
@jougs confirmation is appreciated as the assumption ```/usr/bin/python``` always calls Python 3 is not obvious to me.

**Comment by jougs** [comment]
@ikitayama: actually, I can't point you to a resource saying that `python` is or should be working on all systems. It's just that no one ever complained and we thus assumed this is the case. However, you might well be right that we should explicitly use `python3` everywhere to be on the safe side.

@terhorstd: what do you think about this? You also tend to have opinions about these kinds of things :wink:

**Comment by jougs** [comment]
After some more research, I've created #1696. All further discussion should go there.
