### ISSUE TITLE
Use python3 instead of python wherever we run (or talk of) a Python interpreter

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#1696]
Triggered by the discussion in #1683, I did some research, and found https://www.python.org/dev/peps/pep-0394, which in essence says that distributions may either install a `python` command (linking to whatever specific Python executable they deem right) or not, but in any case they have to make a specific command (i.e. `python3`) available that should link to a super-specific one (e.g. `python3.8`).

I think this means that we should change all code, comments and documentation to refer to `python3` where we currently say just `python`.

CC: @sarakonradi, @steffengraber, @terhorstd, @clinssen

**Comment by clinssen** [comment]
I would like to provide a contrarian viewpoint. (You might know me from my earlier work on defeating PEP8 line length conformity.) Especially including the minor version number (e.g. the 6 in 3.6) would seem to set us up for documentation that gets outdated fast, and suggests something too specific (that 3.6 is the only version that can be used). If we make it clear in one central place (installation instructions) that only Python 3 is supported, with a minimum version required (e.g. 3.6) there and only there. Then all the example commands could consistently (and unchangingly) say ``python``.

**Comment by clinssen** [comment]
For clarification: I understand that the suggestion is to change mentions of ``python`` to ``python3``, rather than to, say, ``python3.6``. I am OK with this!

**Comment by ikitayama** [comment]
👍
