### ISSUE TITLE
MacOS builds find wrong Python version on Travis

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1701]
Travis fails with the following error message:
```
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "2.7.17", but
  required is at least "3" (found /usr/local/bin/python)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPythonInterp.cmake:160 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/ProcessOptions.cmake:401 (find_package)
  CMakeLists.txt:145 (nest_process_with_python)
```

**To Reproduce**
see https://travis-ci.org/github/nest/nest-simulator/jobs/706434021

**Expected behavior**
Build on Travis should find a suitable Python version and succeed.

**Desktop/Environment (please complete the following information):**
 - OS: MacOS
 - Python-Version: Python 2.7 ?!?
 - NEST-Version: latest
 - Installation: Travis

**Comment by lekshmideepu** [comment]
https://github.com/nest/nest-simulator/pull/1700

**Comment by BSVogler** [comment]
#1700 is merged, but the mac build is still failing.

https://travis-ci.org/github/nest/nest-simulator/builds/710702237
