### ISSUE TITLE
Revise Eclipse workflow

### ISSUE THREAD

**Issue by sarakonradi** [nest/nest-simulator#1719]
This issue addresses the Eclipse workflow, which needs to be updated and moved from the ``gh-pages`` branch to ``doc/contribute`` in ``master``. 

It follows up on the discussion in #1707.

**Comment by terhorstd** [comment]
This can maybe treated consistently with
* PyCharm #1232, #1412
* VScode #1619
and maybe even environment handling discusison in
* Jupyter #1210

**Comment by sarakonradi** [comment]
Closing this as #1941 fixes it.
