### ISSUE TITLE
Failure to install GLIF module

### ISSUE THREAD

**Issue by johnhongyumeng** [nest/nest-simulator#1738]
Dear Contributors,

I'm trying to work on the Allen visual cortex model, which requires the glif module. I'm using Ubuntu 20.02 system and I installed the latest version of NEST by anaconda with python 3.8. I have installed libtools. 

However, when I try to use the following command to install glifmodule

cmake --Dwith-nest=nest-config -Dwith-ltdl=ON [-Dwith-mpi=ON] ../GlifModel

as mentioned in the installation page

https://github.com/AllenInstitute/GLIF2NEST

I got the following error:

-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:75 (project):
The CMAKE_CXX_COMPILER:

/home/conda/feedstock_root/build_artifacts/nest-simulator_1583214391390/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++

is not a full path to an existing compiler tool.

Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/yawntaiyuan/GLIF2NEST/build/CMakeFiles/CMakeOutput.log".
See also "/home/yawntaiyuan/GLIF2NEST/build/CMakeFiles/CMakeError.log".

Could you help me with the problem?

More information: I have tested the CMake, Compiler, NEST simulator. They all works properly by themselves. I have updated all the packages to the newest.

I have checked the passage in the error message:
/home/conda/feedstock_root/build_artifacts/nest-simulator_1583214391390/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++

and indeed I don't have that file at the location. However, I did install c++. Is it possible that I should install other packages before as well?

Best,
John

I could be reached by john.meng@nyu.edu. I'd like to test some of predictions of our rate model by using a point-neuron model. If anyone like to help on this project, I would deeply appreciate it.

**Comment by jougs** [comment]
Is there a specific reason you're compiling the module yourself, instead of relying on the most current version of the models that are built into NEST (as the [GLIF2NEST README](https://github.com/AllenInstitute/GLIF2NEST#update) suggests)? See #1126 for the PR in which they got merged.

**Comment by johnhongyumeng** [comment]
Dear Jochen,

Thanks for replying!

I am trying to run a model for V1 in mice, developed by Allen Institute.
The description of the model is in
https://portal.brain-map.org/explore/models/mv1-all-layers.

The model is based on the GLIF model. I downloaded their data and run the
code based on their description in
https://www.dropbox.com/sh/w5u31m3hq6u2x5m/AACpYpeWnm6s_qJDpmgrYgP7a?dl=0&preview=README.txt

When I run the following command as they suggested

mpirun -np 1 python run_pointnet.py config.json

I got the following error

Traceback (most recent call last):
  File "run_pointnet.py", line 9, in <module>
    nest.Install('glifmodule')
  File "/opt/nest/lib/python3.8/site-packages/nest/ll_api.py", line 246, in
stack_checker_func
    return f(*args, **kwargs)
  File
"/opt/nest/lib/python3.8/site-packages/nest/lib/hl_api_simulation.py", line
318, in Install
    return sr("(%s) Install" % module_name)
  File "/opt/nest/lib/python3.8/site-packages/nest/ll_api.py", line 132, in
catching_sli_run
    raise exceptionCls(commandname, message)
nest.lib.hl_api_exceptions.DynamicModuleManagementError:
("DynamicModuleManagementError in Install: Module 'glifmodule' could not be
opened.\n
The dynamic loader returned the following error: 'file not
found'.\n\nPlease check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!",
'DynamicModuleManagementError', <SLILiteral: Install>, ": Module
'glifmodule' could not be opened.\n
The dynamic loader returned the following error: 'file not
found'.\n\nPlease check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!")

Thus, I thought the problem was that I hadn't installed the glifmodule. I
searched and found the source code. During the installation of the module,
I encountered the problem and reported as in
https://github.com/AllenInstitute/GLIF2NEST/issues/3

For your information, I installed the NEST by compiling the source code in
an anaconda environment, following the blog
http://neurochannels.blogspot.com/2019/02/installing-nest-simulator-for-use-with.html
The default installation method didn't work for me.
The version of NEST is 2.20.0

Do you suggest that I might have installed the glifmodel but I set the
environment wrong? I have searched in my lib, but no file named as
"glifmodule" is found. It's not listed in the results of
$ conda list

Thanks again for your reply! I truly appreciate your help. I have stuck
here for quite a while now.

Best regards,
John Meng

**Comment by jougs** [comment]
What I wanted to say is that you don't need the `glifmodule` anymore, because the neuron models contained in it have been integrated into NEST proper when #1126 was merged. This means that you must not call `nest.Install('glifmodule')` in your simulation script, as that module does not exist. The models should nevertheless be available.

**Comment by johnhongyumeng** [comment]
Thanks so much! I will test that by removing the line. Otherwise I will
contact the authors of the model. As soon as I find out a solution, I will
close the issue on Github.

Best,
John

**Comment by gtrensch** [comment]
Issue closed. Please reopen if this is still a problem.
