### ISSUE TITLE
Remove stray files in models directory

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1742]
In the `models` directory, there are two files named [`script_add_group.sh`](https://github.com/nest/nest-simulator/blob/master/models/script_add_group.sh) and [`sli_examples.txt`](https://github.com/nest/nest-simulator/blob/master/models/sli_examples.txt). These look like they can be removed. If someone (possibly from the docteam) could confirm, I will file a PR removing them.

**Comment by jougs** [comment]
These files were indeed added by accident. Please go ahead and remove them. Thanks!
