### ISSUE TITLE
Development workflow description

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1757]
Currently the developer description explains how to download the sources and coding guidelines, which only is the starting point of development. Just following one of the installation guides is not enough to set up and work in a development environment.

The documentation should also contain descriptions how to do a local test-install and run the tests (also for single tests). It should list the additional development dependencies (testing frameworks, …) and explain how they are supposed to be used. Ideally this should be intermeshed with the documentation generation docs.

**Comment by clinssen** [comment]
See: https://nest.github.io/nest-simulator/development_workflow

Does this document already contain the right material, or is it necessary to modify it?

I noticed there's no separate GitHub Issue for "merging the Developer Space branch into nest-master", should I create one? (Could you remind me of the fork/branch URL where I can find the Developer Space files?)

**Comment by heplesser** [comment]
Workflow information is available on ReadTheDocs.
