### ISSUE TITLE
The install target should not install documents by default

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#1775]
As the install target is the most noticed one for developers, I propose this should not copy lots of documents to
the destination directory.

**Comment by ikitayama** [comment]
One benefit of doing this is that shortening the copy time significantly, without going over lots of Documentation files.

**Comment by Helveg** [comment]
Less build log to scroll through :heart:

**Comment by ikitayama** [comment]
@terhorstd can you comment on this please?

**Comment by terhorstd** [comment]
The build system for the documentation is refactored in #1843 , so the `doc` target is separate from the normal build. We have to look into the dependencies for the `install`.

**Comment by terhorstd** [comment]
There is a separate target `make install-nodoc` that probably already does what you want.

**Comment by ikitayama** [comment]
When developing code, we often install. Wanting to install binary without
docs.
So a instal-doc target should exist and install only install binaries needs
to run simulation was my argument.

Itaru.

**Comment by terhorstd** [comment]
This is also touched by #1843.

**Comment by ikitayama** [comment]
+1

**Comment by heplesser** [comment]
Closing this, further discussion in #1905.
