### ISSUE TITLE
Document extension modules

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1777]
**Describe the flaw**
[This page](https://nest.github.io/nest-simulator/extension_modules) is the only highly ranked search engine result about extension modules and it only covers the steps to building the most basic example. There's no explanation of the interface, possibilities, how extension modules are found or where they're integrated.

**Suggest an improvement**
Create more documentation on the extension modules including how the discovery mechanism works, what the requirements are for a module to be found (all this so that when even the basic example or your own module goes wrong you know what to troubleshoot, is it missing env vars, wrong paths, ... ?). What is possible to achieve with an extension module? What can be registered where, which integrations into the codebase exist?

**Comment by clinssen** [comment]
Suggest to close this as we now have https://nest-extension-module.readthedocs.io/, which is linked from the front page of the main NEST documentation. Please re-open this issue or create a new issue in case there are specific suggestions remaining. Cheers!
