### ISSUE TITLE
Compiling NEST takes a lot of memory at times

### ISSUE THREAD

**Issue by jd41** [nest/nest-simulator#1780]
When I compile NEST, some commands (in particular some cc1 commands) take a huge amount of memory (3 GB or something like that). On my current machine (which only has 4 GB), this is quite painful.

Is there anything one can reasonably do about this?

**Comment by terhorstd** [comment]
This is not an issue of NEST itself, but of the environment. You could for example activate enough swap space to avoid running out of memory.
This is a discussion of your personal setup and should (if at all) discussed on the mailing list. I'll close this here.
