### ISSUE TITLE
Add clang to our Travis setup

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#179]
As shown by, e.g., #178, clang discovers errors in code that gcc does not notice. We should therefore add clang to our test harness on Travis and compile at least one configuration with it. Since clang is open source, that should not be too difficult, I hope.

**Comment by heplesser** [comment]
See also #74.

**Comment by lekshmideepu** [comment]
Started to work on this.

**Comment by heplesser** [comment]
@lekshmideepu Any news on this one?

**Comment by lekshmideepu** [comment]
I had a successful build for  gcc 4.8.4 and clang 5.0.0.  But I have used gcc 5 and clang 3.7 in my .yml file.
For some reason it is not picking the one which I gave. 
https://travis-ci.org/lekshmideepu/nest-simulator/builds/383079868

**Comment by lekshmideepu** [comment]
https://github.com/travis-ci/travis-ci/issues/10288

**Comment by lekshmideepu** [comment]
PR #1057
