### ISSUE TITLE
Main RTD page: "Reference material" can't be clicked

### ISSUE THREAD

**Issue by jd41** [nest/nest-simulator#1794]
On the main page, in the section "Where to find what", the "Reference material" link can't be clicked because the target page doesn't exist anymore. A new user will not find any clear reference to a "reference material" section now, I think. Unfortunately, I can't fix this myself because I don't know what exactly of the reference materials is still current and should continue to exist. The target page was apparently removed in [this commit](https://github.com/nest/nest-simulator/commit/c3a2ee5e9dc2767ab6f23ec8d1b706bec747ac17).

**Comment by terhorstd** [comment]
This is a single broken link. The issue for handling all broken links is #1627, please check if this one appears in the found broken links there. If it is not covered, #1627 needs additional checks.
Closing this one as duplicate / symptom of #1627.
