### ISSUE TITLE
test_connect_arrays_mpi.py fail even though HAVE_MPI4PY is False

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#1799]
**Describe the bug**
The python test `test_connect_arrays_mpi.py` currently fails on my computer, with the error message `NameError: name 'MPI' is not defined`
```
Traceback (most recent call last):
  File "../nest-simulator/pynest/nest/tests/test_connect_arrays_mpi.py", line 54, in <module>
    class ConnectArraysMPICase(unittest.TestCase):
  File "../nest-simulator/pynest/nest/tests/test_connect_arrays_mpi.py", line 64, in ConnectArraysMPICase
    comm = MPI.COMM_WORLD.Clone()
NameError: name 'MPI' is not defined
```

I do not have mpi4py, and `HAVE_MPI4PY` is thus False. So, the test should be skipped, but it isn't.
https://github.com/nest/nest-simulator/blob/1e0ce51e17e48933a95463cc35a5c2c5d99ca366/pynest/nest/tests/test_connect_arrays_mpi.py#L40-L51

I think the problem is that `@unittest.skipIf(not HAVE_MPI4PY, 'mpi4py is not available')` have to be placed before the [individual tests](https://docs.python.org/3/library/unittest.html), and not before the entire test-class? But I am not sure, does anyone know?

**Desktop/Environment (please complete the following information):**
 - OS: Ubuntu-16.04
 - Python-Version: Python 3.7.6
 - NEST-Version: 6997cae6c893470257a0654fe48edb8b799169a0

**Comment by hakonsbm** [comment]
From the unittest documentation:

> Unittest supports skipping individual test methods and even whole classes of tests.

and

> Classes can be skipped just like methods:
>```python
> @unittest.skip("showing class skipping")
> class MySkippedTestCase(unittest.TestCase):
>     def test_not_run(self):
>         pass
> ```

So skipping the whole class should work. Are you sure that `HAVE_MPI4PY` is set to `False`?

**Comment by stinebuu** [comment]
@hakonsbm I clearly did not read far enough down on the page.. But, ok, then that is not the problem!

Yes, I have printed the value of `HAVE_MPI4PY`, and it is definitely `False`.

**Comment by stinebuu** [comment]
@hakonsbm I have tested a new thing, if I put in `False` directly in the `skipIf` and print something directly inside the class, like below, I still enter the class, and the text is printed.
```
@unittest.skipIf(not False, 'mpi4py is not available')
class ConnectArraysMPICase(unittest.TestCase):
    print("here")
```
So this prints `here` for me, and then fails because I don't have `mpi4py.MPI`. Could you check if this is the case with you as well? Of course it won't fail for you, but I am curious if it still enters the class.

**Comment by hakonsbm** [comment]
@stinebuu 

> So maybe the problem is that the `skipIf` before the class will enter the class, but skip all the tests?

I just tested it, this appears to be the problem. So setting `comm` only if `HAVE_MPI4PY` is `True` should fix it.
