### ISSUE TITLE
Python-first CMake installation

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1803]
**Is your feature request related to a problem? Please describe.**
When Python is installed with Python bindings, all the information is available on the location of the executable and where that Python executable will look for packages. NEST also provides a Python package, yet the system wide PYTHONPATH needs to be manipulated for the Python executable to find NEST's Python module. This hinders switching between Python environments without changing the system path and will most likely create race conditions for concurrent execution of different Python versions, or Python scripts that use subprocesses or shell out to start NEST, or just scripts that import nest at different times (all speculative but if required I can try to prove these assumptions).

Imagine 2 python installs `pythonX` and `pythonY`, they run concurrently so the PYTHONPATH will contain both `pythonX`'s and `pythonY`'s nest module; which is chosen over the other? Now imagine that the order in PYTHONPATH remains the same, but you add some `time.sleep` calls to artificially swap the order in which they import nest for the first time. If you use the environment in one of the two cases either `PythonX` will find `PythonY`s nest module or vice versa.

**Describe the solution you'd like**
When Python bindings are installed the default behavior should be that the NEST module is either moved inside of the site-packages or the mechanisms provided by pip to link between the Python's site-packages and the NEST module should be used, so that each Python executable on the system is able to find the NEST installation that installed against this Python executable without depending on an environment that is shared between executables.

This would also allow me to make nest extension modules pip installable as my end users will just `pip install` their dependencies and they won't know (and shouldn't have to know) that they have to set their PYTHONPATH to match the nest of whatever virtualenv they might be in at that point.

In general I don't think that when looking at NEST as a Python dependency that it should do things that break out of the Python encapsulation by using the environment variables to be discovered by it.

The PYTHONPATH workflow could be kept around by specifying a `-DWITHOUT_PYTHON_INSTALL` flag or something.

**Comment by gtrensch** [comment]
We will look at the problem you describe here.

**Comment by Helveg** [comment]
Another issue with using `PYTHONPATH` to force the discovery of some `.py` files rather than going through the Python package installation process is that dependencies are not declared, see #1931

**Comment by heplesser** [comment]
Resolved with NEST 3, therefore closing.
