### ISSUE TITLE
Fast and safe Siegert implementation

### ISSUE THREAD

**Issue by AlexVanMeegen** [nest/nest-simulator#1811]
**Is your feature request related to a problem? Please describe.**
The `siegert_neuron` requires a numerically tricky integration where an `exp(s**2)` and and `1 + erf(s)` interact in the integrand. Currently, this problem is solved using a substitution that leads to an infinite integral which is better behaved but still tricky. The problem and the [currently implemented solution](https://github.com/nest/nest-simulator/blob/ad5549a7aa0dae6d47d38d8898e7652704fda61b/models/siegert_neuron.cpp#L339) is documented [here](https://www.frontiersin.org/articles/10.3389/fninf.2017.00034/full#h10).

**Describe alternatives you've considered**
Instead of the above substitution, one can use the scaled complementary error function to boil down the integrals to a single, well-behaved one. Here are the details: [siegert_numerics.pdf](https://github.com/nest/nest-simulator/files/5421828/siegert_numerics.pdf). In all my tests so far this works pretty well.

**Additional context**
This idea is approve by @mhelias; I also asked @tomtetzlaff for his opinion but his answer is pending. I can provide a fully Python based implementation in case someone wants to test it.

**Comment by clinssen** [comment]
@AlexVanMeegen: this is a very in-depth description, and I'm not sure I understand the implications without further discussing this in detail. Could we ask you to take care of filing a pull request for this, if you (and Tom) indeed decide that this confers sufficient advantages?

**Comment by AlexVanMeegen** [comment]
@clinssen, I am not sure I see why a full PR is needed to understand the implications. Could you be a bit more specific what you are missing? Then I can try to answer before creating a full blown PR.

Nonetheless, I am of course most willing to make the PR if desired!

**Comment by clinssen** [comment]
I don't understand the domain well enough, to see the complete implications. If you are proposing to implement a mathematical re-formulation that yields the same results, but more accurately or with more numerical stability, this would I think be very welcome! And could you also say how it might impact runtime?

**Comment by AlexVanMeegen** [comment]
Yes, precisely: This is all about the numerical evaluation of a tricky integral (Eq. 2 in my notes). My proposal is simply to use a different mathematical reformulation of the integral than the one that is currently used which is, to my best current knowledge, better behaved.

Naively, I think this will also improve runtime without affecting the accuracy, but this of course needs a careful benchmark.

**Comment by AlexVanMeegen** [comment]
Tom also approves this, so I guess it is indeed sensible. I'll prepare a PR, please bug me in case I forget about this!

**Comment by clinssen** [comment]
Great, thank you! Could you please also check whether there is a unit test covering the behaviour of the neuron near the point of numerical instability?

**Comment by AlexVanMeegen** [comment]
Sure, I'll try to keep this in mind!

**Comment by jougs** [comment]
Shouldn't this issue have the word "safe" in the title, rather than "secure"? The same applies for #1849. Thanks!

**Comment by AlexVanMeegen** [comment]
Agreed, my bad!

**Comment by jougs** [comment]
If it were a really aggressive optimization, I'd of course also have accepted *furious* :smiling_imp:

**Comment by AlexVanMeegen** [comment]
"These optimizations were performed by trained professionals, don't try this at home."
