### ISSUE TITLE
Cluster parallel simulation

### ISSUE THREAD

**Issue by jiaduxie** [nest/nest-simulator#1817]
Hi,jarsi,I am now simulating a small network for testing on two machines, and run it with the following command. It seems that the two machines run by themselves without interaction,running your own.

`mpirun.mpich -np 2 -host work0,work1 python ./multi_test.py`

Can nest simulate a network in a multi-node cluster environment? If yes, how do the nodes exchange data?

**Comment by jarsi** [comment]
Yes, NEST is very well capable of simulating networks in a multi-node environment. I guess your question is related to the question you poster in the [multi-area model issues](https://github.com/INM-6/multi-area-model/issues/18).

What you are describing should not happen. NEST should not run two independent copies which do not interact with each other. The copies should interact with each other and distribute the workload. Usually this should work out of the box when installing NEST with mpi support. It would be important to know what job scheduler your system runs. And what is inside the hostfiles?
