### ISSUE TITLE
Configuration of multi-node parallel environment

### ISSUE THREAD

**Issue by jiaduxie** [nest/nest-simulator#1827]
Hi,I am now simulating a small network for testing on two machines, and run it with the following command. It seems that the two machines run by themselves without interaction,running your own.

`mpirun -np 2 -host work0,work1 python ./multi_test.py`

Can nest simulate a network in a multi-node cluster environment? If yes, how do the nodes exchange data?
Do you know about the configuration of a parallel cluster environment? I installed NEST under ANCCONDA? Can anyone share some experience?

**Comment by stinebuu** [comment]
Hi @jiaduxie! This would be a good question for our NEST user mailing list: https://www.nest-simulator.org/mailinglist/postorius/lists/users.nest-simulator.org/

Here you can get help from people who are using NEST, as well as NEST developers.

You might also be able to find some information in our [documentation](https://nest-simulator.readthedocs.io/en/stable/guides/parallel_computing.html).

**Comment by stinebuu** [comment]
See also #1817

**Comment by terhorstd** [comment]
the discussion will be continued on the mailing list, closing here.
