### ISSUE TITLE
The "install-nodoc" target disables a parallel build

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#1833]
`make -j8 install` launches a parallel build, but `make -j8 install-nodoc` becomes a sequence build like below:

``` 
make[4]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[  3%] Built target nestutil
[ 24%] Built target sli_lib
[...]
```

**Comment by terhorstd** [comment]
You may try to split your build and install process:
```
make -j8;
make install-nodoc
```

**Comment by ikitayama** [comment]
Okay.

**Comment by terhorstd** [comment]
Did this resolve the issue?

**Comment by ikitayama** [comment]
I confirm that separating the build and install phases allows me to build in parallel, though I wonder if
the `install-nodoc` target can be written so that it does not prevent the Make running in parallel.

**Comment by terhorstd** [comment]
As the parallel build issue is solved, we can continue to discuss the default setting for installing documentation in #1775. Thanks for the feed-back.
