### ISSUE TITLE
Require nosetest for Python-based testing

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#185]
We currently have to test setups for Python-based testing: unittest and nosetest. Nosetest is used if available, especially on our Travis CI, and unittest serves as a fallback. I believe that this is a recipe for disaster: Developers who have not installed nosetest on their computer will add tests to the unittest testsuite, but these may not be executed by nosetest, if they have unsuitable names. This won't be detected by Travis, because Travis will simply overlook those tests. On the other hand, developers using nosetest may (will) fail to add new tests to the unittest setup, and so the unittest testsuite will end up incomplete.

noestests is a widely available (pure Python) package that is easily installed with `pip` where it should be missing, so I see no reason why we should not make it a requirement and then remove all explicit test suite construction code.

@jougs What to you think?

**Comment by jougs** [comment]
I think your suggestion makes sense. I can't remember exactly why I left the old test harness in there at all. Probably because I did not fully trust the new setup myself ;-)

**Comment by JanneM** [comment]
This would only be a requirement if you actually did try to run the tests, right? It would still be possible to configure and build without it, I hope.

**Comment by heplesser** [comment]
@JanneM Yes, nosetest is only required to run the tests. But you should be able to install nosetest on any system that has Python, so if you can use PyNEST on a system, you should be able to run the tests. For all I can see, nosetest is a pure Python package, so installing it on systems with Python should be straightforward.

**Comment by apeyser** [comment]
I think it worth pointing out for others --- this only affects PyNEST tests, and not SLI tests, so it only affects builds which by definition have python installed.

**Comment by abigailm** [comment]
Decided in the developer meeting on 9.5.2016 that this is a good idea and should be implemented

**Comment by heplesser** [comment]
Closing in favor of #761.
