### ISSUE TITLE
Can't import nest at PyCharm with Anaconda.

### ISSUE THREAD

**Issue by ghost** [nest/nest-simulator#1854]
My OS is Ubuntu 20.04, with Anaconda3.
When I run 'import nest' form file and console, it's seems something wrong happen, but form terminal is fine. 

![2020-11-20 21-25-52 的屏幕截图](https://user-images.githubusercontent.com/48119814/99805461-8f499980-2b77-11eb-9086-92981f39b57d.png)
![2020-11-20 21-26-39 的屏幕截图](https://user-images.githubusercontent.com/48119814/99805470-91abf380-2b77-11eb-8c43-84b9896e23c3.png)
![2020-11-20 21-27-41 的屏幕截图](https://user-images.githubusercontent.com/48119814/99805474-92dd2080-2b77-11eb-8254-2e50e167b844.png)

**Comment by 0xdream** [comment]
And when I run it without Anaconda but use system python interface, everything is ok.

![2020-11-20 21-36-52 的屏幕截图](https://user-images.githubusercontent.com/48119814/99806187-9a50f980-2b78-11eb-9f37-47a2a485d3bf.png)

**Comment by stinebuu** [comment]
See also #1232 and #1412.

**Comment by stinebuu** [comment]
@sarakonradi @terhorstd @steffengraber as this is the third issue on problems with PyCharm, is this something we should document how to do?

**Comment by heplesser** [comment]
@stinebuu I think that would make sense. PyCharm is rather widely used.

**Comment by gtrensch** [comment]
The solution described in https://github.com/nest/nest-simulator/issues/1232#issuecomment-529483291 only works for older PyCharm versions, e.g. Community Edition 2016.3. In newer versions PyCharm seems to come with a built-in virtual environment, see also the PyCharm documentation: [creating-virtual-environment](https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html)

**Comment by Helveg** [comment]
Isn't this again related to the fact that there is environment variable fidgetting required to link Python & NEST together? It seems to be that NEST is mainly used through its Python interface and should behave like a proper Python dependency. When installing with Python bindings NEST should install itself as a proper Python package and leave the rest of the system untouched, allowing for multiple concurrent NEST installs for multiple Python installations and virtual environments.

**Comment by alberto-sibner** [comment]
Using PyCharm CE 2020.2 on MacOS Big Sur, the following worked for me:

1. Under the Run menu, click on "edit configuration" for the file you want to run.
2. On the environment variables line, add the following variables:

![image](https://user-images.githubusercontent.com/49283178/102362415-42a58280-3fac-11eb-9574-78efe5cec073.png)

You can find out the values activating your conda environment from an external Terminal `conda activate myenv`, and running `printenv`.

**Comment by albertofdb** [comment]
Using PyCharm CE 2020.2 on MacOS Big Sur, the following worked for me:

1. Under the Run menu, click on "edit configuration" for the file you want to run.
2. On the environment variables line, add the following variables:

![image](https://user-images.githubusercontent.com/49283178/102362415-42a58280-3fac-11eb-9574-78efe5cec073.png)

You can find out the values activating your conda environment from an external Terminal `conda activate myenv`, and running `printenv`.

**Comment by gtrensch** [comment]
In addition to my December 4th entry: I've switched to PyCharm version 2020.3, which allows you to specify the environment you want to use for your project. This works for both Conda environments and inheriting from your default setting. See the screenshots below. 
![Screenshot from 2021-01-29 08-25-45](https://user-images.githubusercontent.com/19706694/106245956-a22eb900-620d-11eb-87f6-2343869434da.png)
![Screenshot from 2021-01-29 08-26-00](https://user-images.githubusercontent.com/19706694/106245961-a4911300-620d-11eb-94e7-29bc50d8922e.png)

**Comment by steffengraber** [comment]
Setting the environment variables plus picking my NEST conda environment, worked for me. With that terminal and python console work.
I use PyCharm 2020.3

**Comment by terhorstd** [comment]
This seems to be solved from the installation side, so I'll remove it from Installation project. The screenshots and descriptions should go to the corresponding pages in the developer documentation. @sarakonradi, @jessica-mitchell, could you find the right spot for this?

**Comment by jessica-mitchell** [comment]
@terhorstd should this be in developer documentation? users will likely find this information useful

**Comment by heplesser** [comment]
We made a lot of improvements to installation with NEST 3 and assume this will work. Please re-open if not.
