### ISSUE TITLE
Installation NEST on colab

### ISSUE THREAD

**Issue by ConBke** [nest/nest-simulator#1858]
Hi!
     I  am currently trying to NEST to simulate a network and need to choose the parameters for the network, which costs much time with Genetic Algorithms, so I tried to use colab. But after installing anaconda on colab and followed the installation instruction of NEST simulator as: ' conda create --name ENVNAME -c conda-forge nest-simulator=*=mpi_openmpi*' and activating the environment, I still failed importing nest module, as it seems not to exist.
    Can you give me any suggestions? Or what am I missing?
   Thank you very much! Looking forward to your reply!

   Best Wishes!

**Comment by stinebuu** [comment]
@ConBke When you say collab, are you talking about the EBRAINS collab?

@terhorstd have you installed NEST on the collab?

**Comment by ConBke** [comment]
> @ConBke When you say collab, are you talking about the EBRAINS collab?
> 
> @terhorstd have you installed NEST on the collab?

Sorry that I was not clear. I was trying to use NEST on Google Colab, but failed.

**Comment by espenhgn** [comment]
Hi, 
The way to get NEST running on Google Colab is via apt, not conda: 
```
# install NEST (must be run each time a new session is started, or for every "factory reset runtime")
!add-apt-repository -y ppa:nest-simulator/nest
#apt-get update # doesn't seem necessary
!apt install nest # installs NEST as well a bunch of python packages
```
Additional Python dependencies can be installed using `pip`; `!pip install <packagename>`

Then you'd have to restart the kernel/runtime (but no factory reset). 
No reason to utilize MPI, as I don't think can access more than one physical machine anyway using the free resources. Use multiprocessing.

**Comment by ConBke** [comment]
> Hi,
> The way to get NEST running on Google Colab is via apt, not conda:
> 
> ```
> # install NEST (must be run each time a new session is started, or for every "factory reset runtime")
> !add-apt-repository -y ppa:nest-simulator/nest
> #apt-get update # doesn't seem necessary
> !apt install nest # installs NEST as well a bunch of python packages
> ```
> 
> Additional Python dependencies needed by your project can be installed using `pip`; `!pip install <packagename>`
> 
> Then you'd have to restart the kernel/runtime (but no factory reset).
> No reason to utilize MPI, as I don't think you can access more than one physical machine anyway using the free resources. Use multiprocessing.



> Hi,
> The way to get NEST running on Google Colab is via apt, not conda:
> 
> ```
> # install NEST (must be run each time a new session is started, or for every "factory reset runtime")
> !add-apt-repository -y ppa:nest-simulator/nest
> #apt-get update # doesn't seem necessary
> !apt install nest # installs NEST as well a bunch of python packages
> ```
> 
> Additional Python dependencies needed by your project can be installed using `pip`; `!pip install <packagename>`
> 
> Then you'd have to restart the kernel/runtime (but no factory reset).
> No reason to utilize MPI, as I don't think you can access more than one physical machine anyway using the free resources. Use multiprocessing.

Oh, I see. It worked! Thank you very much for your help!!!!

**Comment by ConBke** [comment]
> Hi,
> The way to get NEST running on Google Colab is via apt, not conda:
> 
> ```
> # install NEST (must be run each time a new session is started, or for every "factory reset runtime")
> !add-apt-repository -y ppa:nest-simulator/nest
> #apt-get update # doesn't seem necessary
> !apt install nest # installs NEST as well a bunch of python packages
> ```
> 
> Additional Python dependencies needed by your project can be installed using `pip`; `!pip install <packagename>`
> 
> Then you'd have to restart the kernel/runtime (but no factory reset).
> No reason to utilize MPI, as I don't think you can access more than one physical machine anyway using the free resources. Use multiprocessing.



> Hi,
> The way to get NEST running on Google Colab is via apt, not conda:
> 
> ```
> # install NEST (must be run each time a new session is started, or for every "factory reset runtime")
> !add-apt-repository -y ppa:nest-simulator/nest
> #apt-get update # doesn't seem necessary
> !apt install nest # installs NEST as well a bunch of python packages
> ```
> 
> Additional Python dependencies needed by your project can be installed using `pip`; `!pip install <packagename>`
> 
> Then you'd have to restart the kernel/runtime (but no factory reset).
> No reason to utilize MPI, as I don't think you can access more than one physical machine anyway using the free resources. Use multiprocessing.

Oh, I see. It worked! Thank you very much for your help!!!!
