### ISSUE TITLE
What are the heterogeneity guarantees given by NEST in MPI? 

### ISSUE THREAD

**Issue by apeyser** [nest/nest-simulator#186]
And to what extent are they currently tested?

Issue #181, pull #184 and the proceeding pull #122 introduced code that would break in a non-homogeneous MPI environment. Do we have documented whether or not we support heterogeneous clusters, and if we don't, do we have any runtime tests associated with that?

Have all MPI transfers been properly typed before now, and if so, is that an undocumented feature?

**Comment by heplesser** [comment]
@apeyser We have not paid any attention to heterogeneous MPI environment at all so far. So for now, you should not use NEST on heterogeneous MPI environments.

**Comment by tammoippen** [comment]
I am not sure if this is the right place to ask about this and please correct me if it is off topic:

I am worried about the `pack_pointer` / `validate_pointer` thing in `connector_model.h` that was introduced with #122. I stumbled over this while reviewing the Structural Plasticity PR: From looking at it, I understand that we assume, that the 2 LSB of pointers will always be 0s, hence we can use them for storing the primary / secondary information in the pointer address. But I guess, this assumption is architecture and implementation dependant. Can we be sure, that `new`/`malloc` will return pointers to aligned memory? Was there some discussion on this already, which I missed? Do we have tests for this during configure and should we have an alternative implementation, in the case of this being not the case?

**Comment by janhahne** [comment]
@tammoippen There is a 
```cpp
  // we need to check, if the two lowest bits of the pointer
  // are 0, because we want to use them to encode for the
  // existence of primary and secondary events
  assert( ( reinterpret_cast< unsigned long >( p ) & 3 ) == 0 );
```

in `allocate()` in `connector_model_impl.h` ensuring that it will be detected if the two bits aren't 0. So we cannot run into any strange errors there. The question if we can assume that this will always be the case is however legit. Anyhow I would rather deal with this if this case actually occurs than building an alternative implementation that is not used. So far it worked fine for any system we tested.

**Comment by tammoippen** [comment]
I came across a similar discussion. The check is good and I am happy with the strategy.

**Comment by apeyser** [comment]
By posix: "The malloc() and calloc() functions return a pointer to the allocated
       memory, which is suitably aligned for any built-in type."

So the danger would only be for a posix compliant 16 bit architecture, which wouldn't work for a large number of other reasons -- other than crazy architecture that align +1 or something (which I've never heard of). 

But the code should be commented sufficiently so that the next time @tammoippen like people cross it, they don't have to spend a lot of time searching to find the justification.

**Comment by apeyser** [comment]
But has any one looked carefully at whether the code can be optimized out? Given the malloc promise and this sort of aliasing, a smart compiler (maybe?) could kill the code silently, unless there is a proper union or char* reference to the space.

**Comment by janhahne** [comment]
@apeyser You are right, I opened a minor pull request that improves the documentation (see #195).

Regarding your question: I am not sure if anyone looked at this in-depth. I would assume such an error to be highly unlikely, but if you have any suggestion how to improve `pack_pointer`, `validate_pointer`, `has_primary` and `has_secondary` this would of course be welcome.

**Comment by apeyser** [comment]
@janhahne: we've run across this before, since the compilers are getting smarter and smarter. The trick may be to use unions so that the compiler knows that it can't safely optimize bits or operations away.

**Comment by abigailm** [comment]
Decided in the NEST developer meeting on 9.5.2016 that the documentation of NEST should be adjusted to say that NEST should only be run in a homogeneous MPI environment [and no guarantees if you ignore this ;) ]

**Comment by jakobj** [comment]
since I am now somehow assigned to this: @apeyser could you create a PR that introduces safeguards against overly eager compilers? however, as far as I understand the discussion, this has nothing to do with heterogeneous MPI environments, but with portability in general. to address the MPI issue, I will add a sentence to the documentation, as @abigailm suggested.

**Comment by apeyser** [comment]
@jakobj: that's tricky. I'll think about it.

**Comment by jakobj** [comment]
@apeyser thanks, that's great. I think in the meantime we can close this issue after merging #335.
