### ISSUE TITLE
Add test to protect against use of double_t

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1861]
**Is your feature request related to a problem? Please describe.**
In ancient NEST history, we used `double_t` for most doubles, but dropped this and converted to use of just `double` a long time ago. But there is still a risk for `double_t` creeping in again, see #1859.

**Describe the solution you'd like**
Add a test as part of static code analysis to detect and reject use of `double_t` in NEST code as suggested by @jougs (https://github.com/nest/nest-simulator/pull/1859#issuecomment-736258757)

**Comment by jougs** [comment]
@heplesser: how likely is it that the problem actually resurfaces? Maybe my suggestion war more or less just an academic one and we should close this issue _wontfix_?

**Comment by heplesser** [comment]
The probability is slim, I think I created the issue because I was so surprised that it had happened at all. And a test would be pretty simple. Just run
```
dt_matches=grep double_t -l -R --include '*.[h,cc,cpp]' $NEST_SOURCE_DIR
```
and check that `dt_matches` is empty.

**Comment by jougs** [comment]
I've created a PR fixing this. Please review!
