### ISSUE TITLE
Not all pynest examples are included in Makefile DATA variable

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#187]
Far from all examples in `pynest/examples` are included in the `data_DATA` variable in `pynest/Makefile.am`. The missing files are presumably not included when rolling a distribution tarball.

They need to be added. To make maintenance of the `data_DATA` variable easier, file names should be alphabetically ordered.

**Comment by jougs** [comment]
See trac.609, trac.654 and trac.904 for the corresponding tickets in the old bug tracker.

**Comment by sanjayankur31** [comment]
Is this still a valid ticket after the move to cmake?

**Comment by sanjayankur31** [comment]
@tammoippen - close this one too?
