### ISSUE TITLE
Can the Python install requirements be listed in a seperate command

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1870]
**Describe the flaw**
There are a few Python packages listed in between Linux packages in the Ubuntu [installation instructions](https://nest-simulator.readthedocs.io/en/stable/installation/linux_install.html). Recommending to install Python packages through the distro package manager has some drawbacks: they can be outdated versions, and they install to the system Python rather than the Python installation that the user might configure CMake to use, or that the tests later on might use.

**Suggest an improvement**
List the Python requirements `cython`, `numpy`, `scipy`, `nose` and `matplotlib` seperately using `pip` rather than `apt`.

The `cython` package is a good example: when Python 3.7 was released you couldn't build nest using the Ubuntu `cython` package for around half a year, but the Python `cython` package was up to date after less than a week.

<sub>**Disclaimer:** This issue might partially have been raised because I want to copy paste faster from the install instructions ;)</sub>

**Comment by terhorstd** [comment]
Hey, thanks for noticing this! It is also one point in the context of #1612 . We are looking into this.

**Comment by gtrensch** [comment]
@Helveg with pull request #1965 a solution for the problem you described is provided.

**Comment by Helveg** [comment]
@gtrensch The conda file of that PR is only valid for conda envs I suppose. I don't think Conda follows any PEP so their format is not canon and I won't be able to use it without using conda.

I think my own PR #1959 provides a vanilla solution here as it automatically installs the dependencies listed in nest's setup.py. I will respond to the other PR and ask about setup.py there

**Comment by heplesser** [comment]
With NEST 3 deps are given in setup.py. Closing.
