### ISSUE TITLE
Missing copyright information in Jupyter Notebooks

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1871]
Jupyter Notebooks in the NEST Simulator repository are consistently lacking a copyright header. Actually, for NESTML, I've been in the habit of placing the copyright information at the bottom (in a footer) instead. Docteam: if you are OK with this, I will create a PR doing the same for NEST Simulator.

**Comment by sarakonradi** [comment]
Discussed this with @jessica-mitchell, and it sounds good to us. Thanks!

**Comment by heplesser** [comment]
@jessica-mitchell Could you look into implementing this?
