### ISSUE TITLE
Failing grep of the CI log

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1875]
In the PyNEST unit tests, a grep is done on the log to cull the more detailed debug/info messages, and print only the "summary" lines that end in "... ok|fail|skip|error":

https://github.com/nest/nest-simulator/blob/2869b6364ccd85edf69246deb12c03c05e4a3b49/testsuite/do_tests.sh#L456

However, when a warning or other text is printed inbetween, the grep removes too many lines, and no lines pertaining to the affected unit tests are printed at all. For example in the following case:

```
test_synapse_initialisation_one_to_one (nest.tests.test_sp.test_conn_builder.TestSPBuilder) ... 
 Dec 15 14:38:03 ConnectionManager [Warning]: 
     New connections created, connection descriptors previously obtained using 
     'GetConnections' are now invalid.
 ok
```

After passing through the grep, all of these lines are completely removed from the testsuite log.

@jougs: do you have any suggestions? Should we simply add a ``nest.set_verbosity('M_FATAL')`` in all PyNEST unit tests to suppress the warnings? Or would it be preferable to tweak the grep command itself?

**Comment by jougs** [comment]
In my development branch that moves the PyNEST testsuite from `nosetests` to `pytest`, I have completely removed the output mangling and just let it print in whatever way it wants. The idea is to then not get any information from that output at all, but use `junitparser` to read the XML files created by `pytest` for generating the summary. Unfortunately too much other things piled up and I never found the time to really get that branch into a PR-able state.
