### ISSUE TITLE
Python code should be checked against PEP8

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#188]
We now have powerful and useful code-style checking for our C++ code, but we do not check the style of our Python code. We should add PEP8-conformity checks to our code-style checker.

**Comment by apeyser** [comment]
Seems reasonable to me, much as I find PEP8 to be filled with nonsense, standardization has a lot of value (even when wrong). Shouldn't this become a pull?

**Comment by tammoippen** [comment]
Thank you! :smile: On it.

**Comment by flinz** [comment]
@apeyser Just in general, I would be interested why you're so opposed to PEP8?
I usually lint against PEP8 and find it a quite sensible set of style guidelines..

**Comment by flinz** [comment]
@tammoippen Most of the PyNEST still needs to be formatted to comply to pep8.
Are already in the process of doing this? I couldn't see anything on your issue branch.

If not, I might as well clean it up when I am going over it (while [reformatting the doc strings](https://github.com/nest/nest-simulator/issues/257))

**Comment by tammoippen** [comment]
@flinz I was not planning on reformatting them in that PR. It would be great when you do this. I start the PR as soon as #213 is merged, as I put the changes on top of that code.

**Comment by flinz** [comment]
@tammoippen both pep8 and docs are WIP on https://github.com/flinz/nest-simulator/tree/pynest-docs

**Comment by heplesser** [comment]
@flinz Great work, thanks a lot!

**Comment by heplesser** [comment]
With #337 merged, I will close this issue.
