### ISSUE TITLE
undefined reference to `void nest::ConnectionCreator::connect when building with Intel Parallel Studio XE 2020u4

### ISSUE THREAD

**Issue by niltonlk** [nest/nest-simulator#1882]
**Describe the bug**
When building current master (master@2869b6364) with Intel Parallel Studio XE 2020u4, the following error appears during make process:
```
ld: ../nestkernel/libnestkernel.so: undefined reference to `void nest::ConnectionCreator::connect<3>(nest::Layer<3>&, std::shared_ptr<nest::NodeCollection>, nest::Layer<3>&, std::shared_ptr<nest::NodeCollection>)'
ld: ../nestkernel/libnestkernel.so: undefined reference to `void nest::ConnectionCreator::connect<2>(nest::Layer<2>&, std::shared_ptr<nest::NodeCollection>, nest::Layer<2>&, std::shared_ptr<nest::NodeCollection>)'
make[2]: *** [nest/CMakeFiles/nest.dir/build.make:136: nest/nest] Error 1
make[1]: *** [CMakeFiles/Makefile2:880: nest/CMakeFiles/nest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
warning: /home/nilton/Workspace/git/nest-simulator/src/pynest/pynestkernel.pyx:623:10: Unreachable code
warning: /home/nilton/Workspace/git/nest-simulator/src/pynest/pynestkernel.pyx:623:10: Unreachable code
```
**To Reproduce**
1. (Minimal) reproducing example
Build with Intel Parallel Studio XE 2020u4

2. Used parameters
```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/lib/intel/nest/3.0-dev -Dwith-mpi=ON -Dwith-boost=ON -DCMAKE_C_COMPILER=`which icc` -DCMAKE_CXX_COMPILER=`which icpc` ../src
```

3. Command to run
make

**Expected behavior**
It is expected that make terminates without any error. The same source code results in no error when using gcc 10.2.1 and OpenMPI 4.0.4 (Fedora 33)

**Desktop/Environment (please complete the following information):**
 - Intel Build that results in this error:
 -- OS: Fedora 33, Intel Parallel Studio XE 2020u4, GSL 2.6, BOOST 1.73
 -- Shell: bash
 -- Python-Version: Intel Python 3.7
 -- NEST-Version: master@2869b6364
 -- Installation: from source:
```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/lib/intel/nest/3.0-dev -Dwith-mpi=ON -Dwith-boost=ON -DCMAKE_C_COMPILER=`which icc` -DCMAKE_CXX_COMPILER=`which icpc` ../src
```

 - For the GCC build that resulted in no error:
 -- OS: Feodra 33, gcc 10.2.1, OpenMPI 4.0.4, GSL 2.6, BOOST 1.73
 -- Python-Version: Python 3.9
 -- Installation: from source: 
```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/lib/gcc/nest/3.0-dev -Dwith-mpi=ON -Dwith-boost=ON ../src
```

**Additional context**
- This error dissappeared by including connection_creator_impl.h in layer_impl.h

- diff output
```
diff --git a/nestkernel/layer_impl.h b/nestkernel/layer_impl.h
index 71ab7954c..a62fb14f9 100644
--- a/nestkernel/layer_impl.h
+++ b/nestkernel/layer_impl.h
@@ -29,6 +29,7 @@
 #include "node_collection.h"
 #include "nest_datums.h"
 #include "booldatum.h"
+#include "connection_creator_impl.h"
  
 // Includes from spatial:
 #include "grid_layer.h"
```

Does this addition makes sense?
And how line 125 in the original code 
https://github.com/nest/nest-simulator/blob/2869b6364ccd85edf69246deb12c03c05e4a3b49/nestkernel/layer_impl.h#L125
would access the implementation of connect in connection_createor_impl.h without including it when building with GCC/OpenMPI which builds with no error?

If this is OK, I can create a PR for this issue, as I already have created a branch for this issue.

**Comment by niltonlk** [comment]
### Additional related info:
installcheck results in some MPI failures in both cases, when using Intel Parallel Studio, as well as for OpenMPI.

## Intel Parallel Studio 2020u4 case
The failures have already been discussed in the NEST users mailing-list (Oct 5, 2020, 21:18 UTC-3)
Most of the failures are:
>     Assertion failed: unittest::distributed_collect_assert_or_die: collected 
>     results.
and a few:
>     Assertion failed: unittest::distributed_pass_or_die: collected results.

moreover, these errors doesn't seem to be consistent, as execution of some tests occasionally passes.

As discussed in the mailing list, we (@terhorstd and I) suspect that it is some MPI configuration issue that might be solved by properly defining some environment variables.
For instance, here are the variables I am currently using. The test is being executed in a laptop computer.

- Environment variable to allow oversubscribe #1725 
```
I_MPI_WAIT_MODE=1
I_MPI_THREAD_YIELD=3
```
 - Environment variable to set shared memory as OFI provider
```
I_MPI_OFI_PROVIDER=shm
```

## OpenMPI related installcheck failure
In the case of OpenMPI 4.0.4, some MPI test, unrelated to those listed above, also failed, which could be solved by setting the following environment variables:
- Environment variable to allow oversubscribe #1725
```
OMPI_MCA_rmaps_base_oversubscribe=1
```
- Environment variable do disable ucx error
```
OMPI_MCA_mpl=^ucx
```

**Comment by heplesser** [comment]
@stinebuu @hakonsbm Could one of you look at the problem with the header file?

@niltonlk One potential explanation for the problems with the MPI tests is that NEST's MPI test setup collects data from the various parallel processes through pipes and this can lead to garbled messages. In the tests in the testsuite, we have configured everything so that messages are small enough that they do not get garbled on the systems we have been using so far, but with other MPI libraries, this may look different. I will need to think a bit about how one can manually check whether things are correct. At some point, we will need to update the MPI test framework, therefore I'll add this to the automated testing project.

**Comment by hakonsbm** [comment]
@heplesser When using GCC the implementation of the functions in `connection_createor_impl.h` is found when linking, so there is no need to include it. But apparently the linker doesn't find the functions when using the Intel compiler, which is strange. I can't seem to reproduce the problem though, although I've used the somewhat older Intel Parallel Studio XE 2020u2. Anyway, I don't see any harm in including `connection_creator_impl.h` in `layer_impl.h` (besides a slightly longer compile time), so I think you can go ahead and make the PR, @niltonlk.

**Comment by niltonlk** [comment]
@hakonsbm Thanks for the info. I will recheck on my system, and I will see if I can test it with Intel Parallel Studio XE 2020u2 as well. If the problem persists, I may create a PR.

**Comment by heplesser** [comment]
@niltonlk We did a lot of work on installation with NEST3. Could you check if the problem persists with the current master?

**Comment by niltonlk** [comment]
Sorry for the late reply. My license for Intel Parallel Studio XE 2020 has expired, and we cannot apply for the academic free licence anymore. I will test with the recent Intel OneAPI and report back as soon as I get some results.

**Comment by niltonlk** [comment]
I have just tested with Intel oneAPI 2021.3 HPC Toolkit. Since the provided Python version is 3.7.10, I downgraded the Python requirement to 3.7 in line 395 of `cmake/ProcessOptions.cmake`. The error still persists with the latest master (master@062e2723e)

```
ld: ../nestkernel/libnestkernel.so: undefined reference to `void nest::ConnectionCreator::connect<3>(nest::Layer<3>&, std::shared_ptr<nest::NodeCollection>, nest::Layer<3>&, std::shared_ptr<nest::NodeCollection>)'
ld: ../nestkernel/libnestkernel.so: undefined reference to `void nest::ConnectionCreator::connect<2>(nest::Layer<2>&, std::shared_ptr<nest::NodeCollection>, nest::Layer<2>&, std::shared_ptr<nest::NodeCollection>)'
make[2]: *** [nest/CMakeFiles/nest.dir/build.make:130: nest/nest] Error 1
make[1]: *** [CMakeFiles/Makefile2:760: nest/CMakeFiles/nest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Built target nest_lib
make: *** [Makefile:146: all] Error 2
```

By including connection_creator_impl.h in nestkernel/layer_impl.h as commented above, the build error disappears, but the following cython warning is displayed (there are about 56 warnings diffeiring only in the line number in parenthesis)

```
/home/nilton/Workspace/git/nest-simulator/v3.0-fix_1882/pynest/pynestkernel.cxx(3586): warning #1292: unknown attribute "fallthrough"
          CYTHON_FALLTHROUGH;
```
This could be due to the downgraded Python version (3.7.10), or Cython version (0.29.23), I am not sure.

In addition, installcheck still reports some missed SLI assertion, which could be related to MPI configuration problems.

My expectations in using Intel compiler and Intel MPI was to obtain performance improvements since I use Intel CPU, however, the output of the Potjans_2014 0.1 scaled output shows that GCC shows better performace! (see #2121)
Results of GCC is for NEST 3.0

<table>
  <tr>
    <td></td>
    <td colspan="2">4 MPI 1 OpenMP</td>
    <td colspan="2">1 MPI 4 OpenMP</td>
    <td colspan="2">1 MPI 1 OpenMP</td>
  </tr>
  <tr>
    <td></td>
    <td>GCC</td>     <td>Intel</td>
    <td>GCC</td>     <td>Intel</td>
    <td>GCC</td>     <td>Intel</td>
  </tr>
  <tr>
    <td>Total time:</td>
    <td>6.579</td>     <td>15.911</td>
    <td>19.195</td>     <td>16.702</td>
    <td>14.133</td>     <td>27.850</td>
  </tr>
  <tr>
    <td>Time to initialize:</td>
    <td>0.064</td>     <td>0.051</td>
    <td>0.004</td>     <td>0.006</td>
    <td>0.002</td>     <td>0.003</td>
  </tr>
  <tr>
    <td>Time to create:</td>
    <td>0.074</td>     <td>0.101</td>
    <td>0.138</td>     <td>0.165</td>
    <td>0.129</td>     <td>0.142</td>
  </tr>
  <tr>
    <td>Time to connect:</td>
    <td>0.484</td>     <td>0.914</td>
    <td>1.526</td>     <td>1.125</td>
    <td>1.366</td>     <td>2.567</td>
  </tr>
  <tr>
    <td>Time to presimulate:</td>
    <td>1.559</td>     <td>4.410</td>
    <td>5.615</td>     <td>4.876</td>
    <td>4.028</td>     <td>8.545</td>
  </tr>
  <tr>
    <td>Time to simulate:</td>
    <td>3.344</td>     <td>9.368</td>
    <td>10.965</td>     <td>9.745</td>
    <td>7.648</td>     <td>15.883</td>
  </tr>
  <tr>
    <td>Time to evaluate:</td>
    <td>1.053</td>     <td>1.068</td>
    <td>0.946</td>     <td>0.785</td>
    <td>0.940</td>     <td>0.711</td>
  </tr>
</table>

**Comment by heplesser** [comment]
@niltonlk Thank you for testing and benchmarking. GCC seems to rock indeed :). I will close this issue now.
