### ISSUE TITLE
NEST's MPI transparency at the level of Python multiplicates memory usage per Python process

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1883]
**Is your feature request related to a problem? Please describe.**
When the construction of a network in NEST requires a lot of specific data, such as large connection matrices, or an irregular map of NEST IDs to other IDs all this data is loaded into each MPI node; even tough on average about  `(n - 1)/n` of that data will not pertain to that specific node and will be transparently ignored by NEST. We run into out of memory errors on HPC machines with 72 MPI processes on a single node with 120G memory because it loads our millions of connections 72 times per machine.

**Describe the solution you'd like**
NEST could provide additional functions/callbacks for people who require this memory efficiency where the node calls these functions only for the components that this node actually manages. Alternatively you could also provide a "virtual process aware API" with the standard NEST functions that only affect that node. Anything that allows to work with per node data in the Python processes will do.

```python
def nest_connection_builder(cell_id):
  # Return what to connect this cell to
  return user_function_that_fetches_data_for_one_cell(cell_id)

nest.register_connection_builder(nest_connection_builder)
```
```python
my_ids = nest.VPCreate(7200000, "iaf_cond_alpha") # returns just the ids on this VP
```

This kind of approach switches from "all nodes consume all resources" to "nest asks and gives only the data needed on each node".

**Describe alternatives you've considered**
I've heard about "ConnectionBuilder"s in the context of NEST 3.0, is this something that will do this?

### Example

This example connects all cells on 1 node to the next one on that node; this isn't even the worst case scenario where they might be connected to almost all of the other cells on the same node.

```python
# There are 7200 MPI processes
myIDS = nest.Create(7200000, "iaf_cond_alpha") # 7200000 ids
my_sources = np.arange(0, 7200001)
my_targets = my_sources[:-7200] + 7200
nest.Connect(my_sources, my_targets, {"rule": "one_to_one"})
```

So you see that there is a lot of data generated on each of the 7200 MPI processes that will be ignored by 7199 MPI processes.

**Comment by stinebuu** [comment]
@Helveg Sorry for the very long response time.

I suspect this will be partly fixed with NEST 3.0. For NEST 3.0 we no longer return a list of node id's when we create nodes, we return NodeCollections, a compact object that represent the nodes. So you will no longer need to move large lists of node ids when connecting, you will just need to pass around the node handles.

Though, when connecting with irregular maps of node ids, the problem might still persist, as NodeCollections require the node ids they represent to be unique and sorted. If your node ids are not unique, a list is still needed.

Could you tell me a little more about how your connection matrices look and how they are used?

One small comment about your example, you can index `myIDs` directly, you do not need to convert to numpy arrays:
```
myIDS = nest.Create("iaf_cond_alpha", 7200000) # 7200000 ids
nest.Connect(myIDS, myIDS[7199:], {"rule": "one_to_one"})
```
Your actual simulations are probably more complex than this, so I understand if it is not so easy to use `myIDs` directly, I just wanted to point this out, maybe it can save you some memory.

**Comment by Helveg** [comment]
I actually create `myIDs` as a seperate numpy array to "demonstrate" loading the connection data from an external source,  it's a bit of a shoddy example anyway.

Currently our data format is an HDF5 data set with 2 columns, pre and post ids, because they could be read through in chunks, flattening the memory footprint of reading through our connection data to the size of a chunk, so that's our "in house" solution to the problem.

**Comment by stinebuu** [comment]
@Helveg I suppose your lists can contain the same node ids several times?

One problem I see with having NEST return only nodes on the individual processes is that if your source and target are on different processes, and you pass along lists with only the nodes on the process, you are not sure all connections are created.

@heplesser @jougs @hakonsbm do you have any thoughts on this?

**Comment by Helveg** [comment]
> @Helveg I suppose your lists can contain the same node ids several times?

Yep

I was actually inspired, or let's say emboldened to speak up as a user, by Arbor's recipe approach 😝 In Arbor you're supposed to provide implementations of functions that provide info about nodes, and each Arbor MPI process only calls these functions for the nodes it contains, for example the `connections_on` function in their ring network example:

```python
# (5) Create a recipe that generates a network of connected cells.
class ring_recipe (arbor.recipe):

    # ...

    # (8) Make a ring network. For each gid, provide a list of incoming connections.
    def connections_on(self, gid):
        src = (gid-1)%self.ncells
        w = 0.01
        d = 5
        return [arbor.connection((src,0), (gid,0), w, d)]
```

This function is only called on each GID located on that process. It's not that I want NEST to do exactly this, but to have some sort of alternative to the fully transparent way that NEST handles MPI so that I can "focus" my calculations for what is needed on each MPI process would be nice.

**Comment by heplesser** [comment]
@Helveg We'll take this up in the [Open NEST Developer VC on Monday](https://github.com/nest/nest-simulator/wiki/2021-03-29-Open-NEST-Developer-Video-Conference), I hope you can join!
