### ISSUE TITLE
Segmentation fault when doing benchmarks on Piz Daint - related to Jonke synapse (?)

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#1885]
**Describe the bug**
On Piz Daint, when doing weak scaling, I am getting segmentation fault when I use 36 compute nodes, 1152 virtual processes. The benchmark used to pass without problems. I have done bisectioning to try to find which commit causes the problem, and found it is the merging of PR #1665 into master (commit 6997cae6c893470257a0654fe48edb8b799169a0).

When commenting out `register_connection_model< JonkeConnection >( "jonke_synapse" );` in `modelsmodule.cpp`, the benchmark pass without problems. But, when commenting out one of the other synapse models, and leaving the Jonke synapse in, the benchmark fail again.

In an e-mail correspondence discussing the problem we thought it might be because the PR introduces a new synapse and with it we go over the number of bits available for synapse information. I had at that time only checked what happens if I comment out the Jonke synapse in `modelsmodule.cpp`, and as the benchmark then passed this made sense. It does not fit as well in my opinion now that I have checked what happens when I copy out another synapse instead, but I do not have enough knowledge on the area.

The strange thing is that the exact same benchmarks pass on JUSUF without problems.

**Comment by heplesser** [comment]
@stinebuu This is indeed strange, especially that it is only the `jonke_synapse`.  One more test could be to change the order of synapse registrations, so jonke is registered early. But it could also be that there is a problem in the jonke synapse, maybe?

**Comment by stinebuu** [comment]
@heplesser I agree, very strange. There could be a problem with the jonke synapse, but when I test the last commit in the PR (305511fa11e863ba31e38b553d4d4aebdca451d0), the benchmark pass without problems. Should they not fail then as well if there was a problem with the synapse?

I will test the order of registrations and get back to you with the results.

**Comment by clinssen** [comment]
By coincidence, I worked a bit on the "Jonke" synapse model a few weeks ago. I ran a full cppcheck on the .h file, but no obvious issues (e.g. missing initialisations) were detected. @stinebuu: could you perhaps post a traceback running through valgrind or something similar?

**Comment by stinebuu** [comment]
@heplesser Registering the Jonke synapse earlier did not make  a difference.

@clinssen Will do! I just need to set up valgrind on Piz Daint first.

**Comment by stinebuu** [comment]
A tiny update: With valgrind I get an *out of memory* error for all benchmarks (not only the one with 36 compute nodes). It is not very strange, as valgrind extracts a lot of stuff, but it fails with the *out of memory* error before it seg. faults with the 36 compute nodes. So I have not been able to extract the right information yet. I will work more on this next week!

**Comment by stinebuu** [comment]
I have not been running the benchmarks in a long time, but I just tried again, and it seems to be working fine again. I do not know why, but I am closing this issue now.
