### ISSUE TITLE
bad link in the documentation of poisson_generator : DeviceNode

### ISSUE THREAD

**Issue by lionelkusch** [nest/nest-simulator#1897]
**Describe the flaw**
On this page of the documentation : https://nest-simulator.readthedocs.io/en/nest-2.20.1/models/generator.html
The link following link : http://ken.brainworks.uni-freiburg.de/cgi-bin/mailman/private/nest_developer/2011-January/002977.html
doesn't exist. 

**Suggest an improvement**
Change the link or remove it.

**Comment by heplesser** [comment]
Closed by merging #1920.
