### ISSUE TITLE
Pynest Kminus and triplet-Kminus accesses.

### ISSUE THREAD

**Issue by zifeo** [nest/nest-simulator#191]
Currently `K_minus` and `triplet_K_minus` (archiving node) are not accessible through pynest. This lead to difficulties when testing spiking time-dependent plasticity as described in #150 as post-synaptic variables are involved in this process.

**Comment by heplesser** [comment]
@zifeo Would you be interested in providing a pull request implementing access to th two parameters?

**Comment by zifeo** [comment]
I sadly won't have any time for this in the following months :/.

**Comment by jougs** [comment]
@zifeo: are you still interested in this enhancement? If not, I would consider closing this due to the long inactivity and an apparent lack of users requiring it.
