### ISSUE TITLE
Refactor MPI-dependent Python tests

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1917]
Once #1908 is merged, there will be at least two copies of code for running nosetests under MPI control (`test_connect_all_patterns.py`, `test_mpitests.py`). Both are suboptimal, because they wrap multiple tests in a single nosetest, confusing reporting.

The code should be refactored to
- eliminate code duplication
- create a single helper function running a single test requiring MPI with a user-configurable number of processes
- review if MPI4Py is required and used properly if so

**Comment by jougs** [comment]
Now that we're talking about it, I realize that I did most of what you describe already in the context of #1071, but that part got never merged. I'm thus reassigning to myself and try to look into this soon.

**Comment by heplesser** [comment]
> Now that we're talking about it, I realize that I did most of what you describe already in the context of #1071, but that part got never merged. I'm thus reassigning to myself and try to look into this soon.

Great! Let's discuss this when you get around to it :+1:.
