### ISSUE TITLE
Synaptic triplet variables renaming

### ISSUE THREAD

**Issue by zifeo** [nest/nest-simulator#192]
As for now, triplet variables are following the `triplet_variable-name` pattern. As stated in #150 using triplet as a suffix (`variable-name_triplet`) instead of a prefix might increase the readability a lot and be more coherent with published work. If this change has to be done, I would be happy to help.

**Comment by jougs** [comment]
@heplesser: do you think we should consider this for inclusion in NEST 3? If we decide to not change the  names, we should close this.

**Comment by clinssen** [comment]
N.B. this will break the API because `Archiving_Node::get_triplet_K_value()` will be renamed, hence the NEST 3.0 milestone.

**Comment by terhorstd** [comment]
conclusion from NEST3 video conference: yes, this should be changed.
