### ISSUE TITLE
How to import the NEST CMake project into CLion

### ISSUE THREAD

**Issue by gtrensch** [nest/nest-simulator#1922]
How to import the NEST CMake project into CLion

**Describe the flaw**
A clear description of what the error or weakness in the documentation is.

**Suggest an improvement**
A clear description of what you want to change or add to the documentation.

**Supporting materials**
If applicable, add links or screenshots to help explain the flaw.

**Desktop/Environment**
If applicable, please specify the environment this is relevant for (e.g. "documentation regarding MacOS" or "does not render in Firefox").

**Additional context**
Add any other context about the documentation flaw here.

**Comment by JanVogelsang** [comment]
@gtrensch Is this issue still relevant or did you manage to import NEST into CLion using CMake?

I tried to get it working together with @med-ayssar , but we didn't manage to get it running as we couldn't find a way to tell CMake in CLion which Python environment to use. Did someone find a solution for this already?

You don't need CMake to work to develop for NEST in CLion though. Running CMake from the command line once and then working with Make inside CLion works totally fine. It might make sense to write down the steps to also debug NEST in CLion though, where would be a good place to do that?

**Comment by JanVogelsang** [comment]
@med-ayssar https://github.com/nest/nest-simulator/blob/master/doc/htmldoc/developer_space/workflows/nest_with_ides.rst
Let's add a new entry for CLion there and add the debugging workflow.

**Comment by JanVogelsang** [comment]
I figured out a way to get it working, however I am unsure how clean and universal the solution is.  
In the CMake options add the `-DPython_ROOT_DIR=` option and set it to the `bin` directory of your python environment. This enables CMake's `FindPython` module to locate the python interpreter.
@terhorstd Should this work in most cases or did it just work in my case?

**Comment by heplesser** [comment]
In order to work on this ticket, someone needs a paid-for license for CLion. Educational licenses are for classroom use only and open source licenses are only for volunteer based projects, not for projects funded by organisations or paying their core developers. Unless some NEST developer(s) actively use CLion and therefore have a paid license, I suggest we close this as "won't fix".

**Comment by jessica-mitchell** [comment]
closing as won't fix - please reopen if interested developers want to investigate further.
