### ISSUE TITLE
Overview page for IDE setups

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1923]
**Describe the flaw**
For different development envrionments, the setup is only discussed in the Issues, but no overview page exists.

**Suggest an improvement**
Create an overview page of different development IDEs and descriptions how to set them up for NEST development in in the developer documentation. 

**Supporting materials**
See discussions in
* PyCharm #1854
* vsCode #1619
* CLion #1922
* Eclipse #1719
* vim/emacs …

**Desktop/Environment**
Many IDEs integrate with pyenv or conda flavours, interactions with the build- and test- and doc-system have to be considered.

**Additional context**
Also on the mailing list questions about this setup are recurring.

**Comment by hakonsbm** [comment]
@terhorstd Is this solved now that we have [nest_with_ides.rst](https://github.com/nest/nest-simulator/blob/master/doc/userdoc/contribute/nest_with_ides.rst)?

**Comment by heplesser** [comment]
Has been created, thus closing.
