### ISSUE TITLE
Rename "iaf_tum" neuron model to match the naming conventions

### ISSUE THREAD

**Issue by gewaltig** [nest/nest-simulator#193]
The iaf_tum model is a current based model with adaptive threshold and exponential post-synaptic currents.
It was implemented after the Tsodyks, Uziel, Markram paper, but is actually the model described in Hill (1936)

I suggest renaming the model to
iaf_psc_exp_dyn_th to reflect is main properties.

The suffix dyn_th is for "dynamic threshold" and alternative may be "sfa" for spike-frequency adaptation.

**Comment by jougs** [comment]
@gewaltig: are you (or someone in your team) willing to rename the model? We are currently working on NEST 3, where we again allow these kind of more massive changes.

**Comment by terhorstd** [comment]
conclusion from NEST3 video conference: go with `iaf_psc_exp_htum`.
