### ISSUE TITLE
Running Connect() multithreaded fails when ``receptor_type`` is specified

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1934]
Minimal reproducer:
```Python
import numpy as np
import nest

nest.ResetKernel()
nest.SetKernelStatus({'local_num_threads': 4})
neurons = nest.Create("iaf_psc_exp", 30)
source = 1 + np.arange(30)
target = 1 + np.arange(30)
weights = len(source) * [2.]
nest.Connect(source, target,
            'one_to_one',
#            {'weight': weights})       # WORKS OK
            {'receptor_type': 0, 'weight': weights})   # SEGFAULTS
```
Sometimes works, but usually segfaults. Could not reproduce segfaults when omitting ``receptor_type`` from the parameters dictionary. Could not reproduce segfaults with ``receptor_type`` specified, but number of threads set to 1.

NEST version: nest-master @ 84ea0f7

**Comment by stinebuu** [comment]
@clinssen Is there a reason why you use `source = 1 + np.arange(30)` and the same for `target`? I guess what I am wondering is if you know if it also segfaults when you use the NodeCollection (so just `neurons` instead of `source` and `target`)?

**Comment by heplesser** [comment]
In any case, NEST should either issue an error message or work correctly, not segfault.

**Comment by clinssen** [comment]
Thanks for the suggestion, @stinebuu. Inserting the lines
```Python
source = nest.NodeCollection(source)
target = nest.NodeCollection(target)
```
before the Connect()-call apparently solves the segfault issue. Also using ``neurons`` instead of ``source`` and ``target`` makes the issue go away.

**Comment by stinebuu** [comment]
@clinssen Excellent! This makes it a bit easier to debug I think. I will have a closer look tomorrow.

**Comment by YounesBouhadjar** [comment]
@clinssen @stinebuu  but this breaks if there is a repetitive element in source or target, like having:
```
source = [1,2,3,3]
target = [1,2,3,4] 
source = nest.NodeCollection(source)
target = nest.NodeCollection(target)
```
So, `source = nest.NodeCollection(source)` here throws an error, as node IDs in a NodeCollection must be unique.

**Comment by YounesBouhadjar** [comment]
Just want to say that this can't be a workaround for the moment, but it perhaps helps to debug the issue I guess.
