### ISSUE TITLE
Stabilize test_multiple_synapses_spatial_networks.sli

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1944]
`mpitests/test_multiple_synapses_spatial_networks.sli` fails from time to time during CI testing, both on Travis and Github. Since this only occurs from time to time, I assume that the problem is due to the way our test setup collects data from multiple processes. This process is somewhat fragile if the amount of data communicated becomes too large. 

Could you review the test and see if the amount of data exchanged could be reduced?

**Comment by heplesser** [comment]
NB: It could also be that there is an actual error behind this, but one that occurs only intermittently because it depends in timing between processes. So we need to test systematically.

The test is automatically run only for 1, 2 and 4 MPI processes with `nest_indirect`.  Running it like that for approx 20 times caused no failure on my system. But adding also 6 and 8 processes caused rather strange errors from time to time. (`eof [Error]: ArgumentType` or `A system call failed ...`)

Indeed, running the test directly with
```
mpirun -np 6 nest ../src/testsuite/mpitests/test_multiple_synapses_spatial_networks.sli
```
caused the `A system call failed ...` error occasionally.

**Comment by stinebuu** [comment]
@heplesser I have decreased the amount of data exchanged, but it is a bit difficult to trigger the error as you say. I have now tried running
```
mpirun -np 6 nest ../src/testsuite/mpitests/test_multiple_synapses_spatial_networks.sli
```
both with the old version and my new one, but neither of the two versions seem to fail on my system. Also adding 6 and 8 processes and running `nest_indirect` works for me. So it seems very random.

Should I file a PR with the decreased data, and then you can test with more processes on your computer?

**Comment by stinebuu** [comment]
@heplesser you can also test the branch before a PR is filed: https://github.com/stinebuu/nest-simulator/tree/stabilize_test_multiple_synapses_spatial

**Comment by heplesser** [comment]
Even with the smaller data it fails for me occasionally. Since it seems easier to provoke the errors on my system, I will try myself a bit more to understand what goes wrong.
