### ISSUE TITLE
Add CMake flag for explicit Python installation

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1948]
**Is your feature request related to a problem? Please describe.**
The current CMake approach fails to deliver a functional Python package correctly isolated in the targetted Python environment.

(TL:DR; there's a summary of the problem halfway through and a bullet list of the solution at the bottom)

The best approach Python users - that follow Python best practices and use venvs - with CMake configuration needs have right now is to set `CMAKE_INSTALL_PREFIX` to the root of their virtual env, to set `WITH_PYTHON=ON`, set `PYTHON_EXECUTABLE` and in the worst case (like on Travis CI or when using `pyenv`) also set `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARIES`. An error prone process that often gets one of my collaborators stuck for hours figuring out why the PythonLibs aren't picked up 😛 (it's a typo, it's always a typo)

Using this most optimal configuration we end up with nest installed under our virtual env and a `nest` folder snuck into the `site-packages`, pretending to be a Python package, but actually falling short. It lacks the required metadata (see [PEP314](https://www.python.org/dev/peps/pep-0314/), [PEP345](https://www.python.org/dev/peps/pep-0345/), [PEP566](https://www.python.org/dev/peps/pep-0566/)) and is just a folder with some functional Python code in. However, since that `site-packages` folder is on the Python interpreter's path it will be picked up as an **importable module**, but since it has no package metadata none of Python's stdlib packaging modules such as `distutils`, `setuptools` or `pkg_resources` will pick up on its existence. 

As a downstream consequence the `nest` folder cuckoo is entirely invisible to all Python's packaging tools like `pip`. This is a bad user experience for Python folk. Since nest isn't pip installable yet that doesn't lead to too many problems but it still makes handling the ninja folder difficult. It also complicates building Python tools for nest, for example I can't reliably check if the user of my Python package has nest installed: 
 * Did they just create a folder called nest in `site-packages`?
 * Did they maybe have https://pypi.org/project/nest/ installed?
 * Is their `PYTHONPATH` set incorrectly and will I use the nest module and install of another Python?

This `site-packages` folder is not that well known to all Python users either, and for optimal results it needs to be manually specified **indirectly** as `CMAKE_INSTALL_PREFIX` of the 2nd .. or 3rd parent directory?

I'll summarize the core issues again:

* Too many CMake flags need to be specified (all info can be provided by the Python interpreter's `sysconfig`module and CMake's `FindPython3` module)
* Either `PYTHONPATH` needs to be manipulated, breaking Python env isolation, or
* At best, an importable code folder is produced at the correct `site-packages` location, but no package metadata is produced.
* Determining the correct CMake values is error prone and much too complicated for Python users without CMake experience or building software in general.

**Describe the solution you'd like**
I'm already working on a PR that will:

* Switch to the cmake module `FindPython3` to remove the need to manually specify include dirs, or libs.
* Add a `setup.py` Python package metadata script.
* Add a `WITH_PYTHON_INSTALL` flag that will function as an absolute rockstar and be the only thing required to end up with nest as a fully functional Python package inside of your active Python interpreter's environment. To do so it will:
  * Set `WITH_PYTHON=ON`.
  * Set `CMAKE_INSTALL_PREFIX` to the root of the active Python env
  * Use `python setup.py install_egg_info` to produce and install correct Python package metadata

I've posted about a baker's dozen issues on the Python installation process, not all as coherent I'll admit, but this one is clear and provides a complete solution. I'd like it if there was some actual discussion and action on this one. What do you think @jougs @terhorstd @gtrensch ?

**Comment by Helveg** [comment]
@jougs I know that for example your main complaint was that `CMAKE_INSTALL_PREFIX` had to be respected; this revised solution does that! All nest components will be installed the way they would under the install prefix, but the install prefix is determined by the **active** Python interpreter so that explicit Python users don't have to do a thing. It plays super nice with all forms of Python environments.

**Comment by Helveg** [comment]
Just to compare. This is what a NEST CMake for Python users looks like now:

```
cmake \
  -Dwith-python=3 \
  -DPYTHON_EXECUTABLE=/home/robin/.pyenv/versions/3.8.6/bin/python \
  -DPYTHON_LIBRARY=/home/robin/.pyenv/versions/3.8.6/lib/libpython3.8.so \
  -DPYTHON_INCLUDE_DIR=/home/robin/.pyenv/versions/3.8.6/include/python3.8 \
  -DCMAKE_INSTALL_PREFIX:PATH=/home/robin/.pyenv/versions/3.8.6/envs/nest/ \
  ..
```

Notice that there are 3 different filesystem roots that I have to combine to point to all the right install prefixes, executables, libraries and include dirs.

And with this implemented:

```
cmake -Dwith-python-install=ON`
```

**Comment by heplesser** [comment]
I have added this and #1959 to the agenda of the Open Developer VC on 15 March.

**Comment by jougs** [comment]
Many thanks for the nice write-up :-) This indeed sounds like a cool and complete solution that could simplify life for many users (including myself). I'm very much looking forward to a presentation and discussion during the [Open NEST Developer VC](https://github.com/nest/nest-simulator/wiki/2021-03-15-Open-NEST-Developer-Video-Conference) and naturally also your upcoming PR.

**Comment by Helveg** [comment]
@terhorstd, @jougs, @gtrensch and I had a meeting in which we agreed to go for Python-first as the default workflow, and to allow developers and others to opt-out of it.

Later @jougs, @gtrensch and I continued thinking out the details proposal and concluded:

* Set the `CMAKE_INSTALL_PREFIX` to that of the root of the Python environment.
  * This could lead to dangerous and distro/OS specific problems when the system Python is targetted. This is a bad practice but it can be expected that a part of the Python users will do this anyway, so:
  * To solve this the use of virtual environments are enforced and we error out if there is no virtual env and no explicit `CMAKE_INSTALL_PREFIX` set (indicating that the user does really want to install to this dangerous location).
* The install instructions should be updated to instruct users to create a new virtual environment using Python's own `venv`
  * As a part of Python's stdlib it is available to all users
* Explicitly setting the `CMAKE_INSTALL_PREFIX` equates to opting out of this simplified Python workflow and is nicely backwards compatible with the old style installation.
* The package metadata should be generated and placed alongside NEST's Python module in all cases.

The installation instructions would look like this:

```
python -m venv nest-venv
source nest-venv/bin/activate
git clone https://github.com/nest/nest-simulator
cd nest-simulator
mkdir build
cd build
cmake ..
make install -j
```

And the outcome should be that all of `PYTHON_EXECUTABLE`, `PYTHON_INCLUDE_DIRS`, `PYTHON_LIBRARIES`, ... are detected through CMake's FindPython3 module (already done in https://github.com/nest/nest-simulator/pull/1954) and that `CMAKE_INSTALL_PREFIX` is set to `nest-venv` so that nest is installed to the env's `bin`, `lib`, `include` dirs with the Python module and package metadata ending up naturally under the `site-packages` folder.

Some requirements:
* [ ] Support `venv`, `virtualenv`, `pyenv` and `conda` environments
* [ ] Be able to detect presence of those envs
* [ ] Verify `bin`, `lib` & `include` folder structure of those envs

**Comment by Helveg** [comment]
For the virtualenv detection the following one-liners covers virtual environments of `venv`, `virtualenv`, `pyenv` and `conda`, but does not cover the non virtual `pyenv` Python installs:

```
python -c "import sys, os; print(int(bool(os.environ.get('CONDA_DEFAULT_ENV', False)) or (sys.prefix != sys.base_prefix)))"
```

Prints 0 for system Pythons, 1 for virtualenvs. To cover the non virtual pyenv someone with a bit more shell scripting experience should combine that one liner with a test whether the outcome of `pyenv version` equals `"system"` or not (and if pyenv isn't found as a command the error ofc indicates we're not in a pyenv).
