### ISSUE TITLE
Wrong path and link in user_documentation_workflow

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#1961]
**Describe the flaw**
In the user_documentation_workflow on ReadTheDocs, https://nest-simulator.readthedocs.io/en/latest/documentation_workflow/user_documentation_workflow.html, it says that when you install documentation the rendered text can be found in `<nest_install_dir>/share/doc/nest/html/`

![image](https://user-images.githubusercontent.com/21308850/110089948-06a5e080-7d97-11eb-9016-5b3fbe15205a.png)

This folder is empty for me for newest master (for a clean build, and after doing `make html` and `make install`). I think the documentation can now be found in `<nest_install_dir>/doc/userdoc/html/`? So the path should be updated.

Also, there seems to be a broken link to an image further up on the page:
![image](https://user-images.githubusercontent.com/21308850/110090759-ede9fa80-7d97-11eb-8387-b855ec2349ea.png)

**Comment by jessica-mitchell** [comment]
@stinebuu I think the paths will be correct as of  #1926. When I last built nest from that branch, the install directory path for docs was <install>/share/doc/nest/html/ and in the build directory the path was <build>/doc/userdoc/html/. 
The link though does need to be fixed, thanks!

**Comment by jougs** [comment]
The broken link is fixed by #1926 (commit d7e20064e in particular).
