### ISSUE TITLE
Missing citation in README.md

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1962]
README.md, which is shown on the GitHub repo landing page, is missing the citation entry for NEST 2.20.1.

This list of citations is redundant with ``doc/citing-nest.rst``. Perhaps the citations list in README.md should be replaced with a link to "citing-nest" on ReadTheDocs.

**Comment by stinebuu** [comment]
See also [Github citation files](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files).
We could have a `.bib` file with the main NEST citation, and a link to this [Zenodo page](https://zenodo.org/search?page=1&size=20&q=nest-simulator).
