### ISSUE TITLE
Discrepancy between Github and Travis test results / Static analysis

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1970]
I discovered another discrepancy between Travis and Github results. This time, Travis finds a formatting error with cppcheck, while Github does not, see
- https://github.com/nest/nest-simulator/pull/1969/checks?check_run_id=2055849681
- https://travis-ci.org/github/nest/nest-simulator/jobs/761927469

**Comment by hakonsbm** [comment]
Retrieving changed files is commented out for the GitHub Actions static analysis:

https://github.com/nest/nest-simulator/blob/5650941557797a7b139c5272cfe37832613ab5b1/extras/gha_build.sh#L85-L95

**Comment by heplesser** [comment]
Fixed by #2078, Travis is now decommissioned.
