### ISSUE TITLE
Too many connections to MUSIC output proxies created when NEST runs MPI-parallel

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1974]
The following code should connect each parrot neuron exactly once to the MUSIC output proxy:
```
/nrns /parrot_neuron 2 Create def
/out /music_event_out_proxy << /port_name (out_spikes) >> Create def
nrns out Connect
```
Running the code on a single process, this works fine, and the following code 
```
Rank 0 eq { (                         Src Tgt Prt Rcpt) = } if
(Rank: ) Rank cvs join ( --> Connections: ) join
<< >> GetConnections GetStatus { [[ /source /target /port /receptor ]] get } Map pcvs join =
```
prints this output:
```
                         Src Tgt Prt Rcpt
Rank: 0 --> Connections: [[1 3 0 0] [2 3 0 0]]
```
This is the same output we get if `out` were a spike recorder.

Running on two MPI processes, one would expect that each rank has one connection, from the neuron it holds to the local device. But we get **two** connections on each rank:
```
                         Src Tgt Prt Rcpt
Rank: 0 --> Connections: [[2 3 0 0] [2 3 1 0]]
Rank: 1 --> Connections: [[1 3 0 0] [1 3 1 0]]
```
If `out` is a spike recorder, we get one connection per rank as expected.

The consequence of this is that spikes are sent "double up". The example here leaves out the setting of `music_channel` to keep the reproducer minimal; it only affects the value of `rport`.

This bug must have existed for a while and most likely affects all MUSIC out proxies; I am not sure about MUSIC in proxies.

**Comment by heplesser** [comment]
I believe the problem is located in `ConnectionManager::connection_required()`, specifically at https://github.com/nest/nest-simulator/blob/470e1a4b97459c60e82d3d55e2dfd0db1082aa0b/nestkernel/connection_manager.cpp#L1244-L1253

As a brute-force solution, I have experimented with the following fix:
```c++
  if ( target->local_receiver() )
  {
    if ( target->one_node_per_process() )
    {
      if ( kernel().node_manager.is_local_node( source ))
      {
        return CONNECT_TO_DEVICE;
      }
      else
      {
      return NO_CONNECTION;
      }
    }
```
It seems to solve the problem above, but I have not checked for side effects.

**Comment by heplesser** [comment]
@mdjurfeldt Just an alert about this bug I found, in case MUSIC users contact you about it.

**Comment by jougs** [comment]
Your fix looks reasonable to me and I can't think of a bad side-effect. Could you please send a PR? Thanks!
