### ISSUE TITLE
Create regular grids with jitter

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#1996]
**Is your feature request related to a problem? Please describe.**
Creating regular grids with jitter is currently not possible with NEST 3, but I don't think it should be too difficult to implement. This first came up on the [NEST user mailing list](https://www.nest-initiative.org/mailinglist/hyperkitty/list/users@nest-simulator.org/thread/XHYTY4NJF4FZ3C7O5UCXL5SONKNO2B5A/).

It is possible to create the positions by using a positions vector, but it is then not possible to use NEST's internal random number generators. The vector needs doubles, so it is not even possible to use `nest.random.uniform()` here, we have to use Numpy. It would be better if we could just create a grid with jitter on the NEST level.
```
import numpy as np
import nest
import matplotlib.pyplot as plt

xs = np.arange(-0.5,.501,0.1)
poss = [[x,y] for y in xs for x in xs]

poss = [[p[0]+np.random.uniform(-0.03,0.03),p[1]+np.random.uniform(-0.03,0.03)] for p in poss]
positions = nest.spatial.free(poss)

s_nodes = nest.Create('iaf_psc_alpha', positions=positions)

nest.PlotLayer(s_nodes)
plt.show()
```

**Describe the solution you'd like**
I think it should be possible to add a jitter argument to `nest.spatial.grid()`, so we have something like
```
positions = nest.spatial.grid(shape=[5,7], jitter=nest.random.uniform(0.03))
s_nodes = nest.Create('iaf_psc_alpha', positions=positions)
```

Or we might have to add a random parameter.

At the very least, we should make sure position vectors take `nest.Parameter`. This might be a separate issue, it should be fixed no matter what we choose.

**Comment by heplesser** [comment]
Closing for now due to lack of interest.
