### ISSUE TITLE
K compilation

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#200]
i am trying to compile the current master branch on K. i am using the following configure line:
> ../nest-simulator/configure --prefix=/home/ra000024/a03303/opt/nest-simulator.install/ --with-openmp=-Kopenmp --with-mpi --without-gsl --without-python --without-readline --without-pthread CC=mpifccpx CXX=mpiFCCpx --host=sparc64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu CFLAGS='-Nnoline -DUSE_PMA -DIS_K' CXXFLAGS='--alternative_tokens -O3 -Kfast,openmp, -Nnoline -DUSE_PMA -DIS_K' --enable-ltdl-convenience

it always gets stuck at

> instantiation of "void nest::register_connection_model<ConnectionT>(nest::Network &, const std::string &) [with ConnectionT=nest::STDPDopaConnection<nest::TargetIdentifierIndex>]" at line 455 of "../../nest-simulator/models/modelsmodule.cpp"

restarting compilation does not change much. once it got a bit further and crashed with the following message

> mv -f .deps/libmodelsmodule_la-spike_dilutor.Tpo .deps/libmodelsmodule_la-spike_dilutor.Plo//opt/FJSVtclang/GM-1.2.0-19/bin/../lib/ccpcompx: virtual memory exhausted
gmake[1]: *** [libmodelsmodule_la-modelsmodule.lo] Error 1
gmake[1]: Leaving directory `/volume2/home/ra000024/a03303/opt/nest-simulator.build/models'
make: *** [all-recursive] Error 1

to make sure 2.10 will run smoothly on K, I think we should solve this issue quickly. @janhahne @JanneM @tammoippen do you have any idea what the problem might be? or am I just using the wrong configure line?

**Comment by heplesser** [comment]
@jakobj @jougs  I suppose by "gets stuck" means that nothing happens for a long time? In that case, you just need to wait, even if you have to wait for a *very* long time. The compiler needs to instantiate a lot of templates, and some compilers are rather slow at that.

The "virtual memory exhausted" error message that you got on one try is most likely due to the high demands NEST puts on template instantiation, too. A workaround for this is to comment out neuron models that are not required when compiling on K.

I think this should not delay the release of 2.10.

**Comment by jakobj** [comment]
yes, i meant nothing happens any more. so I'll wait a bit longer and report back as soon as I have run the microcircuit example. thanks for the fast response.

**Comment by JanneM** [comment]
If you don't want to remove synapse models, you can get around the error by removing the "-Kfast" parameter. I haven't yet looked at which optimization is causing it. And yes, building modelsmodule.cpp is very, very slow.

**Comment by jakobj** [comment]
thanks Janne! since commenting out neuron & synapse models did not help (still out of virtual memory), removing the -Kfast finally allowed me to compile the nest-master branch (336e89a) and successfully run the microcircuit example on 72 nodes.
for future reference here is the configure line:
> ../nest-simulator/configure --prefix=/home/ra000024/a03303/opt/nest-simulator.install/ --with-openmp=-Kopenmp --with-mpi --without-gsl --without-python --without-readline --without-pthread CC=mpifccpx CXX=mpiFCCpx --host=sparc64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu CFLAGS='-Nnoline -DUSE_PMA -DIS_K' CXXFLAGS='--alternative_tokens -O3 -Kopenmp, -Nnoline -DUSE_PMA -DIS_K' --enable-ltdl-convenience

running make then took

> real    54m29.890s
user    53m9.455s
sys     0m52.110s

**Comment by jakobj** [comment]
for documentation purposes: here's how to compile NEST 2.10.0 (10e238c), with gsl 2.1
configure gsl
> ../gsl-2.1/configure --prefix=PREFIX/gsl-2.1.install/ CC=mpifccpx CXX=mpiFCCpx CFLAGS="-Nnoline -DUSE_PMA -DIS_K" CXXFLAGS="--alternative_tokens -O3 -Kfast,openmp, -Nnoline, -Nquickdbg -NRtrap -DUSE_PMA -DIS_K" --host=sparc64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu

running make for gsl then took about 4min.

configure NEST
>../nest-simulator/configure --prefix=PREFIX/nest-simulator.install/ --with-openmp=-Kopenmp --with-mpi --with-gsl=PREFIX/gsl-2.1.install --without-python --without-readline --without-pthread CC=mpifccpx CXX=mpiFCCpx --host=sparc64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu CFLAGS='-Nnoline -DUSE_PMA -DIS_K' CXXFLAGS='--alternative_tokens -O3 -Kopenmp, -Nnoline -DUSE_PMA -DIS_K' --enable-ltdl-convenience

running make for NEST then took
> real    65m22.388s
user    62m51.076s
sys     1m55.591s

**Comment by jougs** [comment]
@jakobj: Is this fixed with the merge of #213? If yes, please close this issue. Many thanks!

**Comment by jakobj** [comment]
@jougs yes, this is indeed resolved. closing.
