### ISSUE TITLE
PyNEST's `setup.py` version does not comply with PEP440

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#2003]
**Describe the bug**
The `setup.py` produced by CMake contains invalid version specifiers such as `python-cmake@6b17f32b1` which do not comply with [PEP440](https://www.python.org/dev/peps/pep-0440/) and lead to warnings in #1959 :

```
/home/robin/.pyenv/versions/3.9.0/envs/nest/lib/python3.9/site-packages/setuptools/dist.py:472: UserWarning: The version specified ('python-cmake@6b17f32b1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI.
```

**Comment by heplesser** [comment]
Fixed in NEST 3, closing.

**Comment by Helveg** [comment]
* A sanitized version should be made available to Python
* It should be immediately clear from the Python version that it isn't an official release
  * Append a monotonically increasing `dev` tag, possibly packaging timestamp unless release workflow is ran
* Full version debugging info should be made readily available from the Python API `nest.version_info()`, so that the need for `git-branch@git-commit` is filled in (for profiling, benchmarking, debugging, issue reporting).
