### ISSUE TITLE
Remove undocumented weighted_spikes_{ex,in} recordables?

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2013]
`iaf_psc_alpha` and `iaf_psc_exp` (and only those) offer recordables `weighted_spikes_{ex,in}`. They have been available at least since NEST 2.6.1, but are not documented on illustrated in any example.

These recordables seem problematic to me because they show instantaneous summed spike weights at a given time step. As long as the recording interval of the multimeter is equal to the time step, this is fine, but if, e.g., time step is 0.1 ms and recording interval 1.0 ms, one would only get every 10th value. For recordables such as `V_m` and `I_{ex,in}`, this is less problematic because they are integrated (smoothed) over time. This property is also not documented.

We need to discuss whether to keep this feature.

**Comment by clinssen** [comment]
+1 for keeping the feature and documenting caveats about the resolution.

**Comment by heplesser** [comment]
See also #2027.
