### ISSUE TITLE
Replacing deprecated model `iaf_psc_alpha_canon` with `iaf_psc_alpha_ps` leads to significant time increase

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#2017]
`iaf_psc_alpha_canon` is deprecated, and should thus be removed. It can be replaced with `iaf_psc_alpha_ps`

https://github.com/nest/nest-simulator/blob/f7562a6d457adc83559395839e09b178b03de054/pynest/nest/lib/hl_api_helper.py#L70-L73

`iaf_psc_alpha_canon` is not used much in the code, it is used in one test and two examples, so it's not difficult to remove it. However, when trying to remove the model, I noticed that the two examples (`ArtificialSynchrony.sli` and `brunel_ps.sli`) get quite slow.

With `iaf_psc_alpha_canon` `ArtificialSynchrony.sli` took about 9 minutes to complete, with `iaf_psc_alpha_ps` it took about 18 minutes.
For `brunel_ps.sli` the simulation time with  `iaf_psc_alpha_canon` is 185.63 sec on my computer, but with `iaf_psc_alpha_ps` simulation time is 490.83 sec.

I wanted to create an issue where we can discuss this a bit before actually removing the model, as this is a significant time difference.

**Comment by heplesser** [comment]
@stinebuu Interesting! From a quick look at the code, there are two potential sources of this difference: alpha_ps allows different time constants for E and I synapses, canon has only one. This requires twice as many exponential functions to be evaluated. The other point is that alpha_ps determines threshold crossings precisely with regula falsi, while alpha_ps by default uses linear interpolation.

Could you run one of the examples with a profiling tool to see what takes most time?

I would still suggest to remove _canon, but wonder what @abigailm and @diesmann think?

**Comment by stinebuu** [comment]
@heplesser I will have a look with a profiling tool, yes!

Maybe interesting to also note that you can set the interpolation order for `iaf_psc_alpha_canon`, and for `ArtificialSynchrony.sli` the model use interpolation order 3.

**Comment by stinebuu** [comment]
@heplesser After having a look on VTune it looks like it is indeed the many exponential functions. It is mostly the exponentials in the propagators, `propagator_31` and `propagator_32` that contribute to the time increase.
Just as a test I replaced the exponent functions in the propagators with `std::expm1() + 1`, and this decreased the time a bit (`brunel_ps.sli` then use 325.82).

**Comment by heplesser** [comment]
@stinebuu Thanks for testing this!

> Just as a test I replaced the exponent functions in the propagators with `std::expm1() + 1`, and this decreased the time a bit (`brunel_ps.sli` then use 325.82).

You mean replacing `exp()` by `expm1() + 1` reduces runtime for `brunel_ps.sli` from 491s to 326s? That seems a lot. I think we very carefully explored the precise arithmetic expressions we used, because they have significant consequences for numerics. There are a number of `test_iaf_ps_...accuracy` tests. How do they react to this change?

**Comment by heplesser** [comment]
#2385 provides a solution for this problem, see benchmarks at https://github.com/nest/nest-simulator/pull/2294#issuecomment-1329846733.
