### ISSUE TITLE
DOI on 2.10 seems wrong

### ISSUE THREAD

**Issue by apeyser** [nest/nest-simulator#202]
On zenodo, I find it under 10.5281/zenodo.44222
but on the release page, I see 10.5281/zenodo.91889

I'll try to fix it, if I can find how to update the release web page

**Comment by apeyser** [comment]
Ok, fixed --- @jougs please check that I didn't mess it up.

**Comment by steffengraber** [comment]
Fixed it on web page

**Comment by jougs** [comment]
Many thanks for spotting and fixing this. Apparently the internal Zenodo ID is different from the one used in the DOI.
