### ISSUE TITLE
Move extension module documentation to nest/nest-extension-module repository

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#2021]
- [x] The files marked in #1995 should be moved to the https://github.com/nest/nest-extension-module repository and linked from the NEST ReadTheDocs pages.

- [x] This means that we need to register https://nest-extension-module.readthedocs.org/ 
- [ ] ... and set up intersphinx for linking between our different ReadTheDocs subdomains.

*Edit: now with checkboxes!*

**Comment by jougs** [comment]
My take on this is that we can probably first move the files and add *intersphinx* support in a second step. The extension module and model creation documentation is anyway more or less outdated and needs a serious overhaul.

**Comment by clinssen** [comment]
@jougs: Gotcha. The PR has been updated and a new PR on nest-extension-module has been created.

**Comment by jessica-mitchell** [comment]
@clinssen I think this issue can be closed, correct? Intersphinx is set up as far as I'm aware

**Comment by clinssen** [comment]
Perfect, closing!
