### ISSUE TITLE
Make quantal_stp_synapse support setting n and a via normal set()

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2025]
`quantal_stp_synapse` currently allows setting its integer parameters `n` and `a` only via `SetDefaults`.  This collides with the NEST3-spirit of avoiding `SetDefaults` and `CopyModel`.

According to documentation in the model, this is due to limitations in `Connect()`.

Key questions:
- Do these limitations in connect still exist (@stinebuu, @hakonsbm)?
- Can #2024 help in this context, or would it cause new problems (@jasperalbers, @ackurth)?

Assigned to NEST 3 milestone because of connection to #1534.

**Comment by heplesser** [comment]
@stinebuu It would be nice if you could create a PR for this. For the dopamine synapse, I'd suggest to create a separate issue, that may require some digging. The code printing that error message could definitely become nicer with C++11 features and it does not work as intended: instead of printing the parameter name, it will print `param_arr[ n ]` literally.

**Comment by jougs** [comment]
@heplesser: can you please quickly comment on how critical this is for the release of NEST 3.0?

**Comment by heplesser** [comment]
This is not critical for NEST 3, but a nice to have to ensure consistency, especially to avoid unnecessary `SetDefaults()`. But it should not block the release, so I'll remove it from the milestone.

**Comment by heplesser** [comment]
Once this is fixed, the call to `SetDefaults()` should be removed from the `evaluate_quantal_stp` example. `qsyn_params` should be passed directly to `Connect()` as is done in the `Connect()` call using the `tsodyks2_synapse`.

 https://github.com/nest/nest-simulator/blob/71c5fb568c7295d3f5aebb668dab8c2dae33e2dc/pynest/examples/evaluate_quantal_stp_synapse.py#L156-L163
