### ISSUE TITLE
Remark in iaf_neuron.h not applicable to model?

### ISSUE THREAD

**Issue by sanjayankur31** [nest/nest-simulator#203]
https://github.com/nest/nest-simulator/blob/master/models/iaf_neuron.h#L99

refers to tau_syn_in/tau_syn_ex neither of which seem to be used in the model. Do these remarks apply to this model? Exactly the same remark is found in iaf_psc_exp and other models where these parameters are indeed used, and this is just making me wonder if there's something about the iaf_neuron model that I have missed.

**Comment by heplesser** [comment]
@sanjayankur31 Thanks for pointing this out! `iaf_neuron` has just a single synaptic time constant, `tau_syn`, which applies to excitatory and inhibitory input spikes. The documentation in `iaf_neuron` is incorrect, probably due to a cut-and-paste mistake.

**Comment by sanjayankur31** [comment]
@heplesser Ah! Thank you for confirming this. Should I remove the remark and open a pull request? (I know there's a code freeze in effect at the moment).

**Comment by jougs** [comment]
Fixed by merge of #224.
