### ISSUE TITLE
Synaptic stochasticity in NEST

### ISSUE THREAD

**Issue by YounesBouhadjar** [nest/nest-simulator#2032]
As a first step, I want to implement the following:

During run time, for every presynaptic spike, add noise drawn from normal distribution to the synaptic weight.

**Comment by clinssen** [comment]
Hi, I'm happy to report that this is already supported by the NESTML synapse. Please see the following link for what such a model could look like:
https://github.com/nest/nestml/blob/d29bd07cabfd9c609b4d23b7e5115a52231723fb/models/noisy_synapse.nestml
The unit test can be found here and produces the following figure:
https://github.com/nest/nestml/blob/d29bd07cabfd9c609b4d23b7e5115a52231723fb/tests/nest_tests/noisy_synapse_test.py
![noisy_synapse_synapse_testnoisy_synapse_test_V_m](https://user-images.githubusercontent.com/41159823/117549330-1c0ae580-b03a-11eb-9cf6-a0b34c6ce96e.png)
To run this yourself, you need to check out the "jit" branch on my NESTML fork at https://github.com/clinssen/nestml. Please let me know if this is what you were looking for!

**Comment by YounesBouhadjar** [comment]
Thanks @clinssen, this is exactly what I want. I just tested my model with this synapse model and everything is working as expected. @heplesser what do you think?

**Comment by clinssen** [comment]
Closing due to functionality already being covered by NESTML.
