### ISSUE TITLE
Some `fail_or_die` tests fail because of leftover NEST 2 code, not because of the thing that should fail

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#2034]
When working on #2025, I noticed that we have `fail_or_die` tests that are failing, but they are failing because of leftover NEST 2 code, and not because of the actual thing that should fail.

I noticed this for [issue-737.sli](https://github.com/nest/nest-simulator/blob/master/testsuite/regressiontests/issue-737.sli), but the same might happen other places as well.

The tests in `issue-737.sli` use brackets around the nodes when connecting, like we used to have to do. This is not possible anymore, so the tests fail. However, they should fail because we are connecting with parameters that are not allowed. This is now never tested.

https://github.com/nest/nest-simulator/blob/dafe70e88070a03e18f444e5a02297dfbf6b0cb3/testsuite/regressiontests/issue-737.sli#L43-L50

We have to inspect all the sli test, especially those with `fail_or_die`, and make sure we do not use the brackets anymore. I do not think this is a problem for the PyNEST tests, but we should check that as well.

**Comment by stinebuu** [comment]
Also need to go through all tests with `crash_or_die` as well as checking if there are other exit codes that are similar.

**Comment by heplesser** [comment]
@stinebuu Good you caught this in time. Can you work on this asap, maybe together with @hakonsbm if there are a lot of tests to fix?

@jougs @terhorstd Continue with NEST 3 release preparations, but do not release before all tests are fixed and pass.

**Comment by stinebuu** [comment]
@heplesser Yes, me and @hakonsbm will start working on this later today.
