### ISSUE TITLE
Separation between `Parameters`, `State`, `Buffers` and `Variables`

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#2050]
This is a follow up to #2042.

When working on #2042, the topic of `Parameters`, `State`, `Buffers` and `Variables` where discussed. Particularly if the separation between `Buffers` and `State` is still [needed](https://github.com/nest/nest-simulator/pull/2042#discussion_r634456651).

From [comment](https://github.com/nest/nest-simulator/pull/2042#discussion_r634990767) by @heplesser we have that:

> - Parameters: part of the neuroscientific model, do not change with time during simulation
> - State: part of the neuroscientific model, evolve with time during simulation
> - Buffers: implementation details, persist from one call to Simulate to the next
> - Variables: auxiliary values precomputed for efficiency
>
> When introduced, this separation significantly improved our ability to think systematically about the different parts of the model,  so we should make changes only with great care.

But maybe this is not the case anymore?

**Comment by heplesser** [comment]
The distinction is both of logical advantage and useful in connection with jit.
