### ISSUE TITLE
MPI-3.0 functions in NEST 2.10.0

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#207]
Are there any MPI-3.0 functions used in the new NEST 2.10.0 release? 
I ask because the profiler version we use detects none of those.

**Comment by apeyser** [comment]
I don't think so. We tend to be quite conservative with external APIs, but I don't believe we've made a specific policy about MPI level. In practice though, MPI-2.

**Comment by ikitayama** [comment]
Thanks. So Score-P should be able to detect all of the MPI functions used in the current NEST code then. Good to know.

**Comment by apeyser** [comment]
Should this be a formal decision, that we commit to <=MPI-2 until further notice/discussion, and that goes into the documentation somewhere?

**Comment by jougs** [comment]
@apeyser: yes, I think so. I think it should go into the doxygen documentation block that is in the new `MPIManager` class.

**Comment by heplesser** [comment]
Closed due to inactivity. Future of NEST (from NEST3 may use MPI 3.0 functions).
