### ISSUE TITLE
Ignore delay of gap_junction connection

### ISSUE THREAD

**Issue by janhahne** [nest/nest-simulator#208]
The class `GapJunction` is derived from the class `Connection` and therefore contains a parameter for the delay of the connection. As gap junction connections have no delay our goal was to ignore this delay in the calculation of the `min_delay` and the `max_delay` and to prohibit the user from setting the delay of this connection or at least alarming the user that the value will be ignored.

Therefore we added a parameter `has_delay` to the class `ConnectorModel` with default value `true` and set it to `false` on the registration of the `gap_junction` connection. Then we modified the functions 

```cpp
const Time
ConnectionManager::get_min_delay() const
{
  Time min_delay = Time::pos_inf();

  std::vector< ConnectorModel* >::const_iterator it;
  for ( thread t = 0; t < net_.get_num_threads(); ++t )
    for ( it = prototypes_[ t ].begin(); it != prototypes_[ t ].end(); ++it )
      if ( *it != 0 && ( *it )->get_num_connections() > 0 && ( *it )->has_delay() )
        min_delay = std::min( min_delay, ( *it )->get_min_delay() );

  return min_delay;
}

const Time
ConnectionManager::get_max_delay() const
{
  Time max_delay = Time::get_resolution();

  std::vector< ConnectorModel* >::const_iterator it;
  for ( thread t = 0; t < net_.get_num_threads(); ++t )
    for ( it = prototypes_[ t ].begin(); it != prototypes_[ t ].end(); ++it )
      if ( *it != 0 && ( *it )->get_num_connections() > 0 && ( *it )->has_delay() )
        max_delay = std::max( max_delay, ( *it )->get_max_delay() );

  return max_delay;
}
```

to ignore connections without delay. To prohibit the setting of the `delay` we modified 
```cpp
template < typename targetidentifierT >
void
GapJunction< targetidentifierT >::set_status( const DictionaryDatum& d, ConnectorModel& cm )
{
  // If the delay is set, we throw a BadProperty
  if ( d->known( names::delay ) )
    throw BadProperty( "gap_junction connection has no delay" );

  ConnectionBase::set_status( d, cm );
  updateValue< double_t >( d, names::weight, weight_ );
}
```

I just found out, that both functionalities are not working properly in NEST 2.10 (which is not too bad, but something that should probably be fixed in future versions). For example for the sli code
```
/hh_psc_alpha_gap 2 Create
1 2 2.0 2.0 /gap_junction Connect
```
the `min_delay` and `max_delay` stay unchanged, but no `BadProperty` is thrown. And for

```
/hh_psc_alpha_gap 2 Create
1 2 << /model /gap_junction /delay 3.0 >>  Connect
```
the `min_delay` and `max_delay` are changed and no `BadProperty` is thrown.

I also noticed that the calculation of the delays will be changed in NEST 3.0. @heplesser @tammoippen Do you have any suggestions of how to implement those two functionalities into NEST 3.0 in a way that actually works ;-)?

Another question: Wouldn't this be also interesting for some recording devices like the `voltmeter`? I noticed that the creation of a voltmeter sets the `min_delay` and `max_delay` to 1.0 if no other delay is specified. Is there any influence of this delay parameter on what the `voltmeter` does?

**Comment by tammoippen** [comment]
I guess (for NEST 3.0), we have to implement this checking in the `ConnectorModel`: all delay checking for `min/max_delay` is done in the `DelayChecker`s with the functions `assert_valid_delay_ms` or `assert_two_valid_delays_steps`. They are called in `GenericConnectorModel::add_connection`. If the `ConnectorModel` only performs delay checking, if the model `has_delay_` is `true` then no update to `min/max_delay` will be performed during connect.

I can implement the delay checking, can you write the test?

**Comment by tammoippen** [comment]
BTW:

    SLI ] /hh_psc_alpha_gap 2 Create
    SLI [1] 1 2 << /model /gap_junction /delay 3.0 >>  Connect
Will connect the `/hh_psc_alpha_gap` with a `static_synapse` (default synapse model) (see `lib/sli/nest-ini.sli:340ff`, especially 363-366).

    SLI [1] << >> GetConnections ==
    [<1,2,0,0,0>]
            ^ = syn_id ~ static_synapse

**Comment by janhahne** [comment]
So it is working as it should in NEST 2.10 and my sli code was just wrong. Thank you @tammoippen for pointing that out. I send a PR to your nest3 branch with an updated version of the `test_gap_junction.sli` which now also tests that the delay is ignored for gap junctions. Together with your new commit this should fix this issue.
