### ISSUE TITLE
Error during installation of NEST 3.0

### ISSUE THREAD

**Issue by MaxEngelen** [nest/nest-simulator#2081]
When installing the compiled source code an error occurs while trying to copy nest_simulator.egg-info. However the installation process continues and NEST 3.0 seems to work fine.

1. Download source code from git repo. Compile and run make.
2. Occured with and without parameters on cmake
3. make install
4. Scroll up on the installation log

An error message like this will occur:
Copying nest_simulator.egg-info to /home/max/nest-build/nest-3.0-build/lib/python3.8/site-packages/nest_simulator-3.0.egg-info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nest' distribution was not found and is required by the application

 - OS: Ubuntu 20.04.2 LTS
 - Shell: bash
 - Python-Version: Python 3.8.5
 - NEST-Version: NEST 3.0
 - Installation: compiled from source

**Comment by heplesser** [comment]
@Helveg Could you try to look into this?

**Comment by Helveg** [comment]
Hi @MaxEngelen , could you give a list of the exact commands you executed? I'd like to reproduce this error to figure out what's going on :)

**Comment by Helveg** [comment]
It is probably related to this line:

https://github.com/nest/nest-simulator/blob/34086f8d87c63a85743dd5cde453486060266216/pynest/CMakeLists.txt#L91

We should change `'nest'` to `'nest-simulator'` there. Could you check whether building from https://github.com/Helveg/nest-simulator/tree/fix-pip-requirements fixes the issue?
