### ISSUE TITLE
Eliminate use of float from C++ code

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2092]
In a few dozen locations, data type `float` is used in C++ code in NEST, including NEST kernel. All these cases are likely glitches induced by too much Python programming and should be corrected to `double`. Also, any casts should be written out as explicit static casts, i.e., `static_cast< double >( x )` instead of `(double) x` according to Bjarne Stroustrup.

**Comment by VirenderNayal** [comment]
Hello,
I am new to this repo. Can you assign me this issue and guide me where to make changes,
Thank you.

**Comment by JanVogelsang** [comment]
I could not find any occurrences of float declarations or C-style casts in the code anymore (apart from some code inside the thirdparty directory), therefore I suggest marking this issue as closed.

**Comment by heplesser** [comment]
Thanks for checking, I will close.
