### ISSUE TITLE
Replace our custom `Vose` class with `std::discrete_distribution`

### ISSUE THREAD

**Issue by hakonsbm** [nest/nest-simulator#2097]
Follow-up from #2094. With the modernized RNG setup we may consider to replace the [`Vose`](https://github.com/nest/nest-simulator/blob/bd546f530627137e6280559b4cd2c99dd8569f69/nestkernel/vose.h#L43) class with [`std::discrete_distribution`](https://en.cppreference.com/w/cpp/numeric/random/discrete_distribution), if performance is ok.

**Comment by hakonsbm** [comment]
The `std::discrete_distribution` shows a bit worse performance for high number of weights (i.e. high number of nodes in the mask), but I'm not sure if it's too bad to reject it. The difference is 4.5 seconds with 10 million weights. What do you think @heplesser? 

As an alternative, the [`boost::random::descrete_distribution`](https://www.boost.org/doc/libs/release/libs/compute/doc/html/boost/compute/discrete_distribution.html) performs better than `Vose` for high number of weights.

![result](https://user-images.githubusercontent.com/8554349/124770726-db94ee80-df3a-11eb-99c0-8268f867bbd5.png)

**Comment by heplesser** [comment]
@hakonsbm I find it surprising that there is such a big difference between the std and boost version. I though the std random lib was mostly taken from boost. In most models, we probably have no more than a few thousand neurons in a mask, but we might get larger in some cases. Masks with just 10 elements seem unlikely. So is appears that the std-implementation is 20%–40% slower than our Vose implementation for relevant numbers of neurons in the mask. I would therefore suggest that we stick to our Vose implementation.

**Comment by hakonsbm** [comment]
@heplesser Because the benchmark above was performed by only drawing numbers, I have also done a benchmark in NEST where I replaced the `Vose` class. In this benchmark I connect a number of presynaptic nodes to a single node, with fixed indegree and an indegree of 1. 

![result_nest](https://user-images.githubusercontent.com/8554349/129159054-21858687-e142-4dff-8040-5815f4d388d2.png)

The results show that the difference between `nest::Vose` and `std::discrete_distribution` is diluted in this more realistic benchmark, and `std::discrete_distribution` is only 1%–5% slower here. Numbers for the relative difference and wallclock time difference of `std::discrete_distribution` compared to `nest::Vose` is given in the table below.
| Num. nodes | relative diff. | wallclock diff. [s] | 
|------------------:|:--------------:|----:|
| 10000 | 0.051 | 0.06 |
| 20000 | 0.050 | 0.26 |
| 50000 | 0.013 | 0.44 |
| 100000 | 0.015 | 2.10 |

Interestingly, in the more realistic benchmark boost performs much worse. This may be because of the indirect way we call the distributions, causing the compiler to fail to optimize it to the same degree as in the previous benchmark.

**Comment by heplesser** [comment]
@hakonsbm Thank you for the updated benchmark! This looks indeed much better. But I am surprised that you write "indegree of 1"—this seems to be a very unrealistic case. Or did I get something wrong? What happens with large indegrees? And what distance-dependence do you use?

**Comment by hakonsbm** [comment]
@heplesser There is no distance-dependence. 

I've run the benchmark again, now with indegree equal to 10 % of the presynaptic neurons. I also fixed a bug in the benchmark script, so now it's actually using 1 postsynaptic neuron, and not the same as the presynaptic neurons. I've therefore increased the number of presynaptic neurons.

![result_nest](https://user-images.githubusercontent.com/8554349/129344848-3dc936fa-88ff-480a-a4fc-e356c4d19a12.png)

With this higher indegree it looks even better for `std::discrete_distribution`, and it's even faster than the Vose implementation in some cases. The boost implementation is also a lot better, beating both Vose and the `std::discrete_distribution`. Perhaps, to be more efficient, the boost implementation has a slightly higher overhead, which became dominant when picking only a single value.

**Comment by heplesser** [comment]
@hakonsbm Interesting. What kernel are you using, i.e., what does the distribution look like? I had a look into the respective codes: Boost uses an alias method (but maybe not Vose's—no information in the code and it is a bit difficult to read, while the GCC and Clang libraries use binary search on the cumulative distribution. So the latter should show a log_2 n dependence (but on very straightforward code), while Boost and our Vose should have O(1) generating times (using more complex code). Setup for Boost and Vose is more complex, the GCC/Clang versions only compute cumulative probability tables.
