### ISSUE TITLE
difference between iaf_neuron and iaf_psc_alpha unclear

### ISSUE THREAD

**Issue by albada** [nest/nest-simulator#21]
Both iaf_neuron and iaf_psc_alpha are implementations of a leaky integrate-and-fire model with alpha-function shaped synaptic currents, but the documentation differs between these and does not explain why both models are needed.

https://trac.nest-initiative.org/trac/wiki/CodeReorganisationJune2006 states: "iaf_neuron has been retired. Use iaf_psc_alpha instead."

**Comment by aklawy** [comment]
There is actually a difference in some parameters. 

The synaptic time constant is described by one parameter (tau_syn) in the 'iaf_neuron' model, and by two parameters (tau_syn_ex & tau_syn_in) in the 'iaf_psc_alpha' model.
Additionally, the 'iaf_psc_alpha" model contains the parameter V_min which is the absolute lower value for the membrane potential.

**Comment by heplesser** [comment]
I have started to look at this. I noticed that we rather freely vary between using `iaf_neuron` and `iaf_psc_alpha` in the testsuite, in `test_iaf_1to2.sli`, e.g., we have one `iaf_neuron` and one `iaf_psc_alpha`, while the documentation claims both to be `iaf_neuron`. Test files mentioning both models (dumb grep) are

- manualtests/test_hh_phaseplane.sli
- unittests/test_getnodes.sli
- unittests/test_iaf_1to2.sli
- unittests/test_iaf_1to2_default_delay.sli
- unittests/test_iaf_min_delay_simblocks.sli
- unittests/test_iaf_ps_dc_t_accuracy.sli
- unittests/test_iaf_ps_psp_accuracy.sli
- unittests/test_multimeter_freeze_thaw.sli

At the same time, I fear that we have no test ascertaining the both models actually give identical results when run with identical parameters. I will look at this.

**Comment by jougs** [comment]
In the NEST Core Meeting on Monday we decided that we're going to remove the plain `iaf_neuron` and replace all uses of it in favor of `iaf_psc_alpha`. I'm currently working on this and will create a corresponding pull request.

**Comment by heplesser** [comment]
Since this issue will go away once #526 is solved, I close this issue to reduce issue-clutter.
