### ISSUE TITLE
Nest 3.0 nest-server-mpi crashes after /api/GetKernelStatus request

### ISSUE THREAD

**Issue by EloyRC** [nest/nest-simulator#2104]
nest-server crashes after receiving a `/api/GetKernelStatus` request. It happens only when using `nest-server-mpi` executed with mpirun

**How to reproduce:**

Start nest-server:
```mpirun -np 2 nest-server-mpi```

Send a request for `GetKernelStatus`. Examples:

* get full kernel status:

request:

```curl --header "Content-Type: application/json" http://localhost:5000/api/GetKernelStatus```

output on nest-server:

```127.0.0.1 - - [05/Jul/2021 12:10:07] "GET /api/GetKernelStatus HTTP/1.1" 400 -```

* get "resolution" parameter:

request:

```curl --header "Content-Type: application/json" -d "[\"resolution\"]" http://localhost:5001/api/GetKernelStatus```

output on nest-server:

```
==> MASTER 0/1625479725.5422375 (GetKernelStatus): sending call bcast
==> WORKER 1/1625479725.5423644 (GetKernelStatus): received call bcast, waiting for data bcast
==> MASTER 0/1625479725.5423470 (GetKernelStatus): sending data bcast, data=(['resolution'], {})
==> WORKER 1/1625479725.5423944 (GetKernelStatus): received data bcast, data=(['resolution'], {})
==> MASTER 0/1625479725.5424674 (GetKernelStatus): local call, args=['resolution'], kwargs={}
==> WORKER 1/1625479725.5424831 (GetKernelStatus): local call, args=['resolution'], kwargs={}
==> MASTER 0/1625479725.5426826 (GetKernelStatus): waiting for response gather
==> WORKER 1/1625479725.5426676 (GetKernelStatus): sending reponse gather, data=0.1
==> WORKER 1/1625479725.5426936 (spinwait): waiting for call bcast
==> MASTER 0/1625479725.5427415 (GetKernelStatus): received response gather, data=[None, 0.1]
Traceback (most recent call last):

  File "/home/eloy/.local/nrp/lib/python3.8/site-packages/nest/server/hl_api_server.py", line 264, in func_wrapper
    return func(call, args, kwargs)

  File "/home/eloy/.local/nrp/lib/python3.8/site-packages/nest/server/hl_api_server.py", line 374, in api_client
    response = do_call(call_name, args, kwargs)

  File "/home/eloy/.local/nrp/lib/python3.8/site-packages/nest/server/hl_api_server.py", line 155, in do_call
    return combine(call_name, response)

  File "/home/eloy/.local/nrp/lib/python3.8/site-packages/nest/server/hl_api_server.py", line 428, in combine
    if all(type(v[0]) is dict for v in response):

  File "/home/eloy/.local/nrp/lib/python3.8/site-packages/nest/server/hl_api_server.py", line 428, in <genexpr>
    if all(type(v[0]) is dict for v in response):

TypeError: 'float' object is not subscriptable

127.0.0.1 - - [05/Jul/2021 12:08:45] "POST /api/GetKernelStatus HTTP/1.1" 400 -
```

Cheers!
Eloy

**Comment by stinebuu** [comment]
@babsey Would you be able to take a look at this?

**Comment by babsey** [comment]
It seems that the last merged (#2103) of @jougs in nest-server causes this issue.

Please assign this to @jougs, too.

We need to test it ASAP.

**Comment by jougs** [comment]
@EloyRC: is this with the latest master? #2103 was meant to address exactly the problem you are observing...

The problem I see with the new version is rather a totally silent hang instead of a crash.

I will investigate next week.

**Comment by EloyRC** [comment]
Hi @jougs, no, I tested with tag `v3.0`, I should have tried with last master though... I will give a try to the commit you linked and wait for your investigations.

thanks!

**Comment by jougs** [comment]
I have investigated further and am pretty convinced that the current commits in master should resolve the issues you're seeing. I'm thus closing this issue.

Please re-open in case the issue persists with the new version.

**Comment by EloyRC** [comment]
Confirmed, the crash disappears with the latest commit in master.

I can successfully request different parameters of the kernel. Eg:

```curl --header "Content-Type: application/json" -d "[\"biological_time\"]" http://localhost:5000/api/GetKernelStatus```

Thanks!
