### ISSUE TITLE
Report major (+ minor) NEST version even when cloned from git

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#2116]
#1223 changed the way NEST reports its version when it is cloned from git. Originally, the version consisted of hard-coded major, minor and patch numbers; afterwards, the git hash of the repository at time of cloning was reported.

An issue has emerged where, if NEST was installed from the git repository, NESTML is unable to query the NEST installation for its major version. In this case, only the hash is reported, and it cannot be determined whether the installed version was _based on_ NEST 2, or _based on_ NEST 3. (Due to API changes, NESTML needs to generate different code for them.)

By comparison, to version NESTML itself, we do a release under a major.minor number (for instance, "3.1"), and immediately after releasing, we update the version string on git to "3.1-post-dev". Perhaps a similar major.minor.patch prefix could be used by NEST, followed by the hash as a suffix.

See the template https://github.com/nest/nest-simulator/blob/master/libnestutil/config.h.in — for a relatively recent install, this gets rendered as

```C
#define NEST_VERSION_STRING "master@aa0095a22"
#define NEST_VERSION_BRANCH "master"
#define NEST_VERSION_SUFFIX ""
#define NEST_VERSION "master"
#define NEST_VERSION_GITHASH "aa0095a22"
```

The offending line is probably https://github.com/nest/nest-simulator/blob/b6c1e538610ca5746a0068dd0ac985aeda7787bb/cmake/NestVersionInfo.cmake#L71

Note that this seems to be inconsistent with the comment at https://github.com/nest/nest-simulator/blob/b6c1e538610ca5746a0068dd0ac985aeda7787bb/cmake/NestVersionInfo.cmake#L27
... which is closer to what we're after.

Ideally, these version numbers would also be queriable via ``nest-config``.

**Comment by jougs** [comment]
For me, this boils down to the fact that NESTML (and possibly other external tools) need a way to query NEST version information in a nice way. As different parts of NEST are moving at a different pace, I would even suggest that we introduce different version numbers for the different parts, e.g. the module API, the model API, the PyNEST API, the NEST C++ API, and possibly others.

@sanjayankur31, can you please quickly comment here in how far #2250 can help here or relates to this? Thanks!

**Comment by sanjayankur31** [comment]
The changes we've made in #2250 do allow the different shared objects to be versioned independently of each other and of the nest release value, ideally following the scheme recommended by the libtool documentation:

https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

This only affects other software that links against the NEST shared objects at build/compile time, though. I think stuff that uses NEST at "runtime" via the PyNEST API will need to continue checking the version from there. (I don't think the Python ecosystem differentiates between software release version and the API/ABI version in this way anyway)

**Comment by clinssen** [comment]
I understand the rationale for a separate API version numbering system, but this also adds another layer of complexity and a potential source of confusion to end users. Instead, our versioning policy could potentially be amended to say that any API change requires incrementing the minor NEST version number. This would hold for the external API as well as the internal API. Internal API changes are relevant for NESTML as they might require changing the templates (with respect to, say, the names of private member functions). Possibly, the latter could also be made to require only an increment in the patch version number.

The simplest solution for the issue in the OP is to have a hard-coded NEST version number. I lost track of when ``create_release.sh.in`` was removed; it contained some NEST_VERSION_MAJOR, MINOR and PATCHLEVEL defines. Ideally these values (or the version string as a whole) would be made queryable by invoking ``nest-config``, and additionally via the Python API. Apart from choosing names for these variables, importantly, the doing-a-release process would need to be updated.

**Comment by heplesser** [comment]
I agree with @clinssen that additional version numbering schemes would induce more complexity with limited benefits. If we stick to semantic versioning logic for NEST (https://semver.org), backward-incompatible changes should only be introduced with major version number changes. Would that constrain us too much? I like the idea by mentioned by @clinssen to number non-releases like `nest-3.0-pre@dd47c39ce`, although I would then suggest a form like `nest-MAJOR.MINOR-BRANCH.HASH`

**Comment by heplesser** [comment]
Decision at Hackathon 28 Nov 2022:

1. Use semantic versioning at the NEST level
    1. We use major.minor level
    2. At regular intervals (weekly?) create `rcX` releases (Github only, not Zenodo)
    3. Reconsider if not to use three-level `major.minor.patch[-rcX]` to ensure [compatibility with semver tools](https://pypi.org/project/semver/) even if `patch==0` in all cases
1. Revise the `I:` labels to be more informative and use them systematically
    1. Drop `Behavior changes`
    2. Introduce labels distinguishing changes 
        1. at `C++` and `PyNEST` level
        2. extending vs breaking
    3. Instruct code reviewers to carefully check this
