### ISSUE TITLE
Will nest support GPU?

### ISSUE THREAD

**Issue by iniwap** [nest/nest-simulator#2117]
cpu simulate so slowly，will nest support GPU?

**Comment by heplesser** [comment]
@iniwap For general questions about NEST like yours, the NEST User Mailing List is a much better forum (see https://www.nest-simulator.org/community/).  For a GPU-based simulator with a NEST-like interface see

Golosio B (@golosio), Tiddia G, De Luca C, Pastorelli E, Simula F and Paolucci PS (2021) 
Fast Simulations of Highly-Connected Spiking Cortical Models Using GPUs. 
Front. Comput. Neurosci. 15:627620. 
doi: 10.3389/fncom.2021.627620

I will close this issue now.
