### ISSUE TITLE
Potjans_2014 example in NEST 3.0 gives different output under different MPI-process/thread splits with fixed VP number

### ISSUE THREAD

**Issue by niltonlk** [nest/nest-simulator#2119]
**Describe the bug**
Simulation of the Potjans_2014 microcircuit from pynest/example/Potjans_2014 using 4 MPI-processes and 1 thread per MPI process (total of 4 VP) and 1 MPI-process with 4 threads per MPI process (total of 4 VP) gave different results. Other parameters were kept constant, including the seed witch was the default 55.

**To Reproduce**
1. (Minimal) reproducing example
1.1. 4 MPI processes with 1 thread per MPI process:
- Copy the Potjans_2014 code located in pynest/example/Potjans_2014
- simulate using 4 MPI processes (nothing was changed)
 -- mpirun -np 4 python3 ./run_microcircuit.py
- Output:
>$ mpirun -np 4 python3 ./run_microcircuit.py 
> 
>              -- N E S T --
>  Copyright (C) 2004 The NEST Initiative
>
> Version: nest-3.0
> ...
>Neuron numbers are scaled by a factor of 0.100.
>Indegrees are scaled by a factor of 0.100.
>  Weights and DC input are adjusted to compensate.
>
>RNG seed: 55 
> ...
>  Total number of virtual processes: 4
> ...
>Creating neuronal populations.
>Creating recording devices.
>  Creating spike recorders.
>Creating Poisson generators for background input.
>Connecting neuronal populations recurrently.
>Connecting Poisson generators for background input.
>
>Aug 14 15:56:37 NodeManager::prepare_nodes [Info]: 
>    Preparing 1945 nodes for simulation.
> ...
>Simulating 500.0 ms.
> ...
>    Simulation time (ms): 500
>    Number of OpenMP threads: 1
>    Number of MPI processes: 4
> ...
>Simulating 1000.0 ms.
> ...
>    Simulation time (ms): 1000
>    Number of OpenMP threads: 1
>    Number of MPI processes: 4
> ...
>    Simulation finished.
> ...
>Interval to compute firing rates: [ 500. 1500.] ms
>Mean rates: [0.419 1.997 3.979 4.909 6.449 7.66  0.775 6.953] spikes/s
>Standard deviation of rates: [0.733 1.688 2.75  3.306 4.056 4.412 1.082 3.679] spikes/s
> ...

1.2. 1 MPI processes with 4 thread per MPI process:
- Copy the Potjans_2014 code located in pynest/example/Potjans_2014
- Edit line 49 in sim_params.py to `'local_num_threads': 4,` 
- simulate using 1 MPI processes (everything else was kept unchanged)
 -- mpirun -np 1 python3 ./run_microcircuit.py
- Output:
>$ mpirun -np 1 python3 ./run_microcircuit.py 
>
>              -- N E S T --
>  Copyright (C) 2004 The NEST Initiative
>
> Version: nest-3.0
> ...
>Neuron numbers are scaled by a factor of 0.100.
>Indegrees are scaled by a factor of 0.100.
>  Weights and DC input are adjusted to compensate.
>
>RNG seed: 55 
>  Total number of virtual processes: 4
> ...
>Creating neuronal populations.
>Creating recording devices.
 > Creating spike recorders.
>Creating Poisson generators for background input.
><
>Connecting neuronal populations recurrently.
>Connecting Poisson generators for background input.
>
>Aug 14 15:56:06 NodeManager::prepare_nodes [Info]: 
>    Preparing 7781 nodes for simulation.
>Simulating 500.0 ms.
>
>Aug 14 15:56:07 NodeManager::prepare_nodes [Info]: 
>    Preparing 7781 nodes for simulation.
>
>Aug 14 15:56:07 SimulationManager::start_updating_ [Info]: 
>    Number of local nodes: 7781
>    Simulation time (ms): 500
>    Number of OpenMP threads: 4
>    Number of MPI processes: 1
> ...
>Simulating 1000.0 ms.
>
>Aug 14 15:56:14 NodeManager::prepare_nodes [Info]: 
>    Preparing 7781 nodes for simulation.
>
>Aug 14 15:56:14 SimulationManager::start_updating_ [Info]: 
>    Number of local nodes: 7781
>    Simulation time (ms): 1000
>    Number of OpenMP threads: 4
>    Number of MPI processes: 1
> ...
>    Simulation finished.
>Interval to plot spikes: [600. 800.] ms
>Interval to compute firing rates: [ 500. 1500.] ms
>Mean rates: [0.414 2.019 4.064 4.956 6.534 7.679 0.759 7.01 ] spikes/s
>Standard deviation of rates: [0.745 1.73  2.843 3.452 4.033 4.02  1.1   4.073] spikes/s
> ...

- 
2. Used parameters
Only local_num_threads was changed

3. Command to run
3.1 `$ mpirun -np 4 python3 ./run_microcircuit.py`
3.2 `$ mpirun -np 1 python3 ./run_microcircuit.py`
local_num_threads was changed from 1 to 4 in line 49 of sim_params.py
4. How to see error
Compare mean rates and Standard deviation of rates reported by the above command
**Expected behavior**
Since the total number of virtual processes (VP) are the same, and all other parameters, including seed, are unchanged, both runs should result in equal outputs, including spike times which also differed.
**Screenshots**

**Desktop/Environment (please complete the following information):**
 - OS: Fedora 34
 - Shell: bash
 - Python-Version: Python 3.9
 - NEST-Version: nest-3.0
 - Installation: 
>--------------------------------------------------------------------------------
>NEST Configuration Summary
>--------------------------------------------------------------------------------
>
>Build type          : 
>Target System       : Linux
>Cross Compiling     : FALSE
>C compiler          : GNU 11.1.1 (/usr/bin/cc)
>C compiler flags    :  -O2 -Wall -fopenmp   -pthread -fdiagnostics-color=auto
>C++ compiler        : GNU 11.1.1 (/usr/bin/c++)
>C++ compiler flags  :  -std=c++11 -O2 -Wall -fopenmp -pthread -fdiagnostics-color=auto
>Build dynamic       : ON
>
>Built-in modules    : models
>User modules        : None
>Python bindings     : Yes (Python 3.9.6: /usr/bin/python3.9)
>       Includes     : /usr/include/python3.9
>       Libraries    : /usr/lib64/libpython3.9.so
>
>Cython bindings     : Yes (Cython 0.29.21: /usr/bin/cython)
>MPI4PY header	    : Yes (/usr/lib64/python3.9/site-packages/openmpi/mpi4py/include)
>Use threading       : Yes (OpenMP: -fopenmp)
>Use GSL             : Yes (GSL 2.6)
>    Includes        : /usr/include
>    Libraries       : /usr/lib64/libgsl.so;/usr/lib64/libgslcblas.so
>
>Use Readline        : Yes (GNU Readline 8.1)
>    Includes        : /usr/include
>    Libraries       : /lib64/libreadline.so;/lib64/libncurses.so
>
>Use libltdl         : Yes (LTDL )
>    Includes        : /usr/include
>    Libraries       : /lib64/libltdl.so
>
>Use doxygen         : Yes (/usr/bin/doxygen)
>                    : target `doc` available
>    `dot` available : Yes (/usr/bin/dot)
>                    : target `fulldoc` available
>Use MPI             : Yes (MPI: /usr/lib64/openmpi/bin/mpicxx)
>    FLAGS           : -pthread
>    Includes        : /usr/include/openmpi-x86_64
>    Link Flags      : -Wl,-rpath -Wl,/usr/lib64/openmpi/lib -Wl,--enable-new-dtags -pthread
>    Libraries       : /usr/lib64/openmpi/lib/libmpi_cxx.so;/usr/lib64/openmpi/lib/libmpi.so
>
>Detailed timers     : No
>
>Use MUSIC           : No
>Use libneurosim     : No
>Use Boost           : Yes (Boost 1.75.0)
>    Includes        : /usr/include
>    Libraries       : 
>
>Use recording backend Arbor   : No
>Use SIONlib         : No
>
>--------------------------------------------------------------------------------

**Additional context**
Same results were obtained in current master:
1. 4 MPI processes with 1 thread per MPI
>$ mpirun -np 4 python3 ./run_microcircuit.py 
> ...
> Version: master@c4a0daab5
> ...
>Interval to compute firing rates: [ 500. 1500.] ms
>Mean rates: [0.419 1.997 3.979 4.909 6.449 7.66  0.775 6.953] spikes/s
>Standard deviation of rates: [0.733 1.688 2.75  3.306 4.056 4.412 1.082 3.679] spikes/s

2. 1 MPI process with 4 threads per MPI
>$ mpirun -np 1 python3 ./run_microcircuit.py 
> ...
> Version: master@c4a0daab5
> ...
>Interval to compute firing rates: [ 500. 1500.] ms
>Mean rates: [0.414 2.019 4.064 4.956 6.534 7.679 0.759 7.01 ] spikes/s
>Standard deviation of rates: [0.745 1.73  2.843 3.452 4.033 4.02  1.1   4.073] spikes/s

**Comment by niltonlk** [comment]
It seems that in MPI parallelization, only nodes local to each MPI process are considered for connecting. That is, each MPI process forms independent networks. This information was obtained by obtaining the following code just after `nest.Connect` in line 468 of network.py:
>                    nest.hl_api.SyncProcesses()
>                    conn = nest.GetConnections(source=source_pop, target=target_pop)
>                    tgt_list = conn.get('target')
>                    if len(tgt_list):
>                        conn_local = np.array(target_pop.get('local'))[np.array(tgt_list)-target_pop.get('global_id')[0]].sum()
>                        tgt_local = np.array(target_pop.get('local'))[np.unique(tgt_list)-target_pop.get('global_id')[0]].sum()
>                        print('Rank:{}, pre_ID:{}, post_ID:{}, total_num_synapses:{}, len(conn):{}, num_local_conn:{}, num_target_pop:{}, num_local_target:{}'.format(nest.Rank(),j,i,self.num_synapses[i][j], len(conn), conn_local, len(target_pop), tgt_local))
>                    else:
>                        print('Rank:{}, pre_ID:{}, post_ID:{}, total_num_synapses:{}, len(conn):{}'.format(nest.Rank(),j,i,self.num_synapses[i][j], len(conn)))
which gives the following output (displayed only for pre_ID=0 and post_ID=0):
>Rank:0, pre_ID:0, post_ID:0, total_num_synapses:454998, len(conn):113826, num_local_conn:113826, num_target_pop:2068, num_local_target:517
>Rank:1, pre_ID:0, post_ID:0, total_num_synapses:454998, len(conn):113355, num_local_conn:113355, num_target_pop:2068, num_local_target:517
>Rank:2, pre_ID:0, post_ID:0, total_num_synapses:454998, len(conn):113805, num_local_conn:113805, num_target_pop:2068, num_local_target:517
>Rank:3, pre_ID:0, post_ID:0, total_num_synapses:454998, len(conn):114012, num_local_conn:114012, num_target_pop:2068, num_local_target:517

In this example, connections between L23e and itself (L23e) in the 0.1 scaled network would result in a total of 454998 synapses. If we sum all the number of connections (len(conn)) from each rank, we obtain the total 454998 synapses, however, the output above also shows that the target nodes of all the connections in each rank are only local. 

This results indicate that, when paralellizing using MPI into N MPI processes, N small independent microcircuits are created and simulated, which is not the expected behaviour.

Is this a bug, or is this behaviour specified by a flag restricting connections to local nodes only? And what is the bahaviour in OpenMP based VP?

**Comment by hakonsbm** [comment]
We have understood the problem, and I'll create a fix shortly.
