### ISSUE TITLE
SPBuilder::connect hiding

### ISSUE THREAD

**Issue by tammoippen** [nest/nest-simulator#212]
In #205 @heplesser found, that `SPBuilder::connect(GIDCollection, GIDCollection)` is hiding `ConnBuilder::connect()` ([comment](https://github.com/nest/nest-simulator/pull/205#issuecomment-175907923)):

> @sdiazpier Clang points out (correctly) that SPBuilder::connect(GIDCollection, GIDCollection) shadows ConnBuilder::connect(). Both appear to be rather different functions, since one takes two arguments and the other none. The two-argument version is apparently only called from SPManager::create_synapses(). So I think the function in SPBuilder should probably get a different name. A positive side effect would be that it is no longer virtual, making it (likely) faster.

@sdiazpier, can you please look into this?

**Comment by sdiazpier** [comment]
Dear @heplesser, thanks for detecting this, I will work on it right away.

**Comment by sanjayankur31** [comment]
@tammoippen - this seems fixed already - needs to be closed :)

**Comment by jougs** [comment]
@sanjayankur31: thanks for noticing.
