### ISSUE TITLE
Remove blanket and dynamic Python module importing

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#2134]
There are some problems with how NEST loads its Python modules. To dynamically import all Python files found in `pynest/nest/lib` as modules into the `nest.hl_api` module a file `import_libs.py` was created which relies on the `ast` module and `compile` to create the `module` objects. The `ast` module is however volatile (see discussion in https://bugs.python.org/issue35894, mentioned also in the source code of `import_libs.py`)

The `ast`/`compile` sequence that nest uses sidesteps large parts of the default Python import machinery and causes for example issues with circular imports to become undetectable. This sequence is executed right in the middle of factorizing the new `nest` module of https://github.com/nest/nest-simulator/pull/2114 and causes 2 different instances of `nest` to go around in the codebase.

The historical reason for this dynamic loading was to allow the build to place optional Python files in the libdir and for them to be picked up automatically. Currently these optional modules don't seem to be around anymore. I'd propose to statically import all default modules, so that the import order of nest's module is explicitly visible at the header of each file and issues with these dynamic imports dissapear.

I propose to replace dynamic importing with `try/except` blocks:

```python
try:
  from .lib import optional
except ImportError:
  optional = None
```

(Even better, make a descriptor for it and on `.optional` attribute access throw an error that explains the optional module wasn't installed)

Because of `import_libs` the layout of the modules is also a bit eschewed, eg `nest.lib.hl_api_info` could just be `nest.hl_api.info`, and `nest.hl_api.__init__` could just contain the required shortcut imports explicitly.

**Comment by jougs** [comment]
I fully agree with your analysis and the conclusions :smile_cat:

If you want, you can just go ahead and implement your proposal (either in the context of #2114 or as a standalone PR).

**Comment by Helveg** [comment]
I'm a bit afraid of the possible fallout. A completely clean solution would not be fully backwards compatible. Since none of the modules in the `nest` codebase are prefixed with an underscore it's a conventional promise to its Python users that they are stable and public APIs that they're allowed to use. e.g. there might be some users that use `nest.lib.hl_api_simulation.GetKernelStatus(...)` and their code would break if that is moved to `nest.hl_api._simulation.GetKernelStatus` (and is `hl_api` public, or should all public parts of it be accesible on `nest`, etc etc).

Maybe I can limit this PR to just statically importing the modules to their exact same locations, and the layout cleanup can be part of nest 4.0 ;p

**Comment by jougs** [comment]
> Maybe I can limit this PR to just statically importing the modules to their exact same locations, and the layout cleanup can be part of nest 4.0

:+1:

**Comment by Helveg** [comment]
I'll also remove as many import alls (`from ..ll_api import *`) as possible.

**Comment by clinssen** [comment]
@Helveg: kind ping about the status of this!

**Comment by Helveg** [comment]
Oh, I thought this was merged already?
