### ISSUE TITLE
Some PyNEST tests are not shown in the testsuite list

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#2139]
There are some PyNEST tests that are not shown in the testsuite list when running `installcheck`. The tests are run, but they have additional output, which leads to the test not being written to the list.

See for instance [test_pp_psc_delta_stdp.py](https://github.com/nest/nest-simulator/blob/8c16625f39737318fceb97989e37fe6ab2b01342/testsuite/pytests/test_pp_psc_delta_stdp.py), which produces the following warning:
```
ConnectionManager [Warning]: 
    New connections created, connection descriptors previously obtained using 
    'GetConnections' are now invalid.
```
The test is then not shown in the list, but is run. Adding `nest.set_verbosity('M_ERROR')` to the test make it show up.

As stated by @hakonsbm in #2131:

>  the problem is grep --line-buffered "\.\.\. ok\|fail\|skip\|error" in
> https://github.com/nest/nest-simulator/blob/8c16625f39737318fceb97989e37fe6ab2b01342/testsuite/do_tests.sh#L465
>If there is any output between the three dots following the test name (written when starting the test) and the result (written when the test is finished), the test output for that test is not written to the log.

**Comment by heplesser** [comment]
This will be solved by #2127.
