### ISSUE TITLE
hard coded decay of vacant elements in structural plasticity

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#214]
in e.g., https://github.com/nest/nest-simulator/blob/ff2bdbb/nestkernel/simulation_manager.cpp#L489 the amount for the decay of vacant elements is hardcoded to be 10%. should this not be a parameter that the user can change? and if not, it would be better to define it as a global constant? @sdiazpier

**Comment by sdiazpier** [comment]
Yes this is right @jakobj , I have already done the changes and will submit the PR asap.
Thanks for pointing it out.
