### ISSUE TITLE
Inconsistency between _cond_ and _cond_multisynapse implementations

### ISSUE THREAD

**Issue by tfardet** [nest/nest-simulator#2146]
I think the problem has been discussed before but I could not find it and I run into this issue just now so I thought I would create a new issue to discuss it: *the implementation of conductance weights is inconsistent between ``_cond_`` and ``_cond_multisynapse`` models.*

This is because simple ``_cond_`` models (e.g. ``iaf_cond_alpha`` or ``aeif_cond_alpha``) expect *signed* conductances to tell apart excitatory and inhibitory spikes.
On the other hand, multisynapse models use the receptor ports to tell spikes apart and they expect *positive* conductances (which seems like the most reasonable option).

The problem is that positivity is not enforced when setting weights with multisynapse models, so one can set negative conductances, but the simulation with crash and burn as soon as a spike is delivered with a negative conductance (kernel throws a uncaught BadProperty, then calls terminate recursively and dies).

So my questions are:
- do we want to make all models to behave the same? (I think it would be better)
- should that wait for the models to be moved to NESTML?
- if so, should we at least check the conductance sign in multisynaptic models in the meantime?

**Comment by clinssen** [comment]
I would suggest not to change the semantics of existing models. Does any use case exist for negative conductance signs in multisynapse models? Why does NEST crash and burn so dramatically here? Note that the check you describe seems to already be implemented in some models:
https://github.com/nest/nest-simulator/blob/a947d3a417500c7ec3393ed94377d7f6c82e7029/models/aeif_cond_alpha_multisynapse.cpp#L587

My preferred course of action would be to add this check to all multisynapse models in a consistent manner, and, for all models where this applies, document the use of negative sign to route incoming spikes into the inhibitory spike buffer.

But then we should also find out why throwing a BadProperty() here apparently results in such a panicked way of terminating the process.

**Comment by heplesser** [comment]
I agree with @clinssen to not change this. Negative conductances are a strange thing, but we discussed their use in NEST as ex/inh distinguishing mechanism long ago and decided to keep it, esp for consistency with psc neurons. But better error handling would be good, but I fear we do not get reliable weight information when creating connections, and weights could always be changed later (in the most extreme case, a plasticity rule could change the sign of a weight). So except for a more expressive error message when a negative weight is received, we cannot do much.
