### ISSUE TITLE
Type mismatch between the volume transmitter and synaptic property

### ISSUE THREAD

**Issue by YounesBouhadjar** [nest/nest-simulator#2152]
In NEST3, the `volume_transmitter` is of type NodeCollection, but in the synaptic specification it's required to provide only a node ID of the `vt`, For example when running: 

```
import nest
vt = nest.Create("volume_transmitter")
nest.CopyModel("stdp_dopamine_synapse", "stdp_dopa", {"vt": vt})
```
You get a type mismatch error. A workaround for this is to convert the NodeColletion to a list of node IDs :

```
import nest
vt = nest.Create("volume_transmitter")
nest.CopyModel("stdp_dopamine_synapse", "stdp_dopa", {"vt": vt.tolist()[0]})
```

I think it would be cleaner if the synaptic property "vt" can accept a NodeCollection.

**Comment by heplesser** [comment]
@YounesBouhadjar Thanks for pointing this out. In the testsuite, I found the following two approaches, the first if `vol` contains only a single volume transmitter, the second if it contains several:
```python
{'vt': vol_single.get('global_id')}
{'vt': vol_multi.get('global_id')[0]}
```
I agree with you that it should be possible to pass a single-element node collection here, i.e., that 
```python
{'vt': vol_single}
```
should work. Would you want to try to implement this?

I noticed two more things when looking at your issue
1. While we have a few tests for the volume transmitter, there is not at single example, apparently. Would you want to add one?
2. The `vt` label is little informative. If think it should be `volume_transmitter` for clarity, even though that requires a little more typing. This would break existing code, so we may want to allow both for a period and add a deprecation warning for `vt`.

**Comment by YounesBouhadjar** [comment]
Something else I stumbled upon is that I get an error when connecting a `spike_generator` to the `volume_transmitter`:

```
import nest
sg = nest.Create("spike_generator")
vt = nest.Create("volume_transmitter") 
nest.Connect(sg, vt)
```
It says that: We do not allow connection of a device to a global receiver at the moment. Any thought about that?

**Comment by heplesser** [comment]
@YounesBouhadjar  You need to put a `parrot_neuron` in between generator and transmitter. That should be mentioned in the documentation and shown in an example.

**Comment by YounesBouhadjar** [comment]
Thanks @heplesser, I was not able to find documentation about that.

> I agree with you that it should be possible to pass a single-element node collection here

In case we modify this, how a volume transmitter containing multiple `vt` (`vol_multi` in your example above) will be handled in the synapse model?

> 1. While we have a few tests for the volume transmitter, there is not at single example, apparently. Would you want to add one?

Sure I can add one, I guess this should include also the `stdp_dopamine_synapse`?

**Comment by heplesser** [comment]
> > I agree with you that it should be possible to pass a single-element node collection here
> 
> In case we modify this, how a volume transmitter containing multiple `vt` (`vol_multi` in your example above) will be handled in the synapse model?

I believe (needs to be checked with volume-transmitter experts) that it only makes sense to connect a single VT to a synapse. Therefore, I would raise a `ValueError` exception if a user passes a node collection with several elements. In the test example with `vol_multi`, one would have to pass `vol_multi[0]`, `vol_multi[1]`, etc.

> > 1. While we have a few tests for the volume transmitter, there is not at single example, apparently. Would you want to add one?
> 
> Sure I can add one, I guess this should include also the `stdp_dopamine_synapse`?

Yes, it should be a fully working example of the type of plasticity enabled by VT.
