### ISSUE TITLE
Installation Path

### ISSUE THREAD

**Issue by med-ayssar** [nest/nest-simulator#2153]
**Describe the bug**
Calling the cmake command with "DCMake_INSTALL_PREFIX:PATH" flag containing an empty string (space) at the beginning of the path, results in installing the "nest-simulator" in the "/bin" and "/lib" folders, as well as setting the prefix to an empty string (i.e NEST_SIMULATOR_INSTALL_LOCATION = nest.ll_api.sli_func("statusdict/prefix ::")  will best set to empty).

**To Reproduce**
 cmake -DCMAKE_INSTALL_PREFIX:PATH= ../../nest_src

**Expected behavior**
warning to continue or stop the execution of the command

**Comment by gtrensch** [comment]
@med-ayssar many thanks for you contribution! :+1:. The pull request is merged!
