### ISSUE TITLE
Review coding style in do_tests.sh

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2154]
As commented by @terhorstd [here](https://github.com/nest/nest-simulator/pull/2148#discussion_r703342693), we use very complex shell constructs in parts of our test setup, e.g.

https://github.com/nest/nest-simulator/blob/099a962f3ca1b19f40058d8290746b2413a3ed5c/testsuite/do_tests.sh#L487-L489

We should see if this can be simplified.

**Comment by terhorstd** [comment]
@heplesser, can this issue be closed? You merged #2148, but this one is apparently not automatically linked.

**Comment by heplesser** [comment]
@terhorstd This is actually a follow-up to #2148, see the discussion starting here: https://github.com/nest/nest-simulator/pull/2148#discussion_r703342693.

**Comment by heplesser** [comment]
I will close this issue for now. The code works, and once we revise our MPI testing setup we anyways will need a thorough re-write.
