### ISSUE TITLE
No online documentation for synaptic elements

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#217]
It seems to me that synaptic elements and their parameters are not documented for our online user documentation (SLI-style). I think the best place would be above the `SynapticElements` class declaration, as well as ahead of the different `GrowthCurve` subclasses.

**Comment by sdiazpier** [comment]
Dear @heplesser, thanks for detecting this, I will work on it right away.

**Comment by sanjayankur31** [comment]
I think this issue should now be closed :)

**Comment by heplesser** [comment]
Fixed by #217.
