### ISSUE TITLE
How to use nest to encode the image？

### ISSUE THREAD

**Issue by kaia-li** [nest/nest-simulator#2171]
I’m working on the SNN, and I want to use the DoG filter for the on/off center, then encode the DoG image to spike image and generate the spike train.
But I don’t understand how to use NEST to do it.
1. Is there any example or explanation?
2. Is the spike train always poisson?

Thank you.

**Comment by stinebuu** [comment]
@kaia-li I think this question is better suited for the [NEST User Mailing list](https://www.nest-simulator.org/community/). I would suggest you send your question there, as more users of NEST will be able to see your question and can help you answer it.

I will close your issue for now.
