### ISSUE TITLE
nest package not installed: Docker nestsim/nest container

### ISSUE THREAD

**Issue by Ninontwik** [nest/nest-simulator#2177]
I am using docker to use pyNEST on my windows computer. I have successfully installed NEST using the instructions mentioned here for installing on docker: https://nest-simulator.readthedocs.io/en/v2.20.1/installation/index.html. 
If I am in the container, I have python version 3.8.10. If I run python and then try to "import nest it" says there is no module named nest. Importing other python packages works perfectly in this way. But indeed, when I look at all the installed packages using pip list, there is no package called "nest". There is however "nest-desktop        3.0.3" there. So I guess nest is not installed. However, I also don't know how to install it. If I use pip install nest, another package called nest is installed that is not the nest simulator (according to: https://github.com/nest/nest-simulator/issues/754). 

Also, I don't know whether this problem is related or totally unrelated but it might give some insight: when I am in VScode in the nestsim/nest container and I click on python: select interpreter, nothing happens, I cannot select a python interpreter/no window opens. So maybe there is something wrong with the python installations or the used path?

I hope the problem is clear and thanks in advance for the help!

**Comment by steffengraber** [comment]
@Ninontwik Sorry for not coming up to this. Does the problem still persists?

**Comment by Ninontwik** [comment]
Yes @steffengraber, after not getting a response here I decided to use the nest mailinglist on which I got great help! Sorry for not closing the issue.
