### ISSUE TITLE
Please describe dependencies in README

### ISSUE THREAD

**Issue by yurivict** [nest/nest-simulator#2182]
I found that libneurosim comes from this repository: https://github.com/INCF/libneurosim

What about "misic" and "SIONlib"?

Could you please add information about dependencies in README?

**Comment by jougs** [comment]
Neither MUSIC, nor libneurosim, SIONlib, GSL, or MPI are hard dependencies of NEST. They are optional libraries that "unlock" additional features. The flags to enable or disable them are described in the section about [CMake options](https://nest-simulator.readthedocs.io/en/v3.3/installation/cmake_options.html#external-libraries) of our documentation.

We don't think that the README fie is the right place to explain them, as that would open a rabbit hole. That said, we are currently thinking about ways to explain better what these external libraries enable the user to do and why a user might want to enable their use in NEST. As that is an effort far beyond explaining the libraries, I'm closing this one.
