### ISSUE TITLE
Error when importing nest in ipython

### ISSUE THREAD

**Issue by JiaweiShen1116** [nest/nest-simulator#2184]
Hello,

I installed nest via conda, along with ipython in my environment. However, when I open ipython and type "import nest", it reports an error as following:

```
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import nest
<frozen importlib._bootstrap>:228: RuntimeWarning: compiletime version 3.8 of module 'pynestkernel' does not match runtime version 3.9

Oct 10 23:58:31 stop [Error]: 
    No stopped context was found! 


Oct 10 23:58:32 stop [Error]: 
    No stopped context was found! 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d0a3dc3bba7c> in <module>
----> 1 import nest

~/opt/miniconda3/envs/NEST/lib/python3.8/site-packages/nest/__init__.py in <module>
     43 _original_module_attrs = globals().copy()
     44 
---> 45 from .ll_api import KernelAttribute  # noqa
     46 import sys                           # noqa
     47 import types                         # noqa

~/opt/miniconda3/envs/NEST/lib/python3.8/site-packages/nest/ll_api.py in <module>
    408 
    409 
--> 410 init(sys.argv)

~/opt/miniconda3/envs/NEST/lib/python3.8/site-packages/nest/ll_api.py in init(argv)
    400                 import keyword
    401                 from .lib.hl_api_models import Models           # noqa
--> 402                 keyword.kwlist += Models()
    403             except ImportError:
    404                 pass

~/opt/miniconda3/envs/NEST/lib/python3.8/site-packages/nest/ll_api.py in stack_checker_func(*args, **kwargs)
    225     def stack_checker_func(*args, **kwargs):
    226         if not get_debug():
--> 227             return f(*args, **kwargs)
    228         else:
    229             sr('count')

~/opt/miniconda3/envs/NEST/lib/python3.8/site-packages/nest/lib/hl_api_models.py in Models(mtype, sel)
     80     if mtype in ("all", "nodes"):
     81         sr("modeldict")
---> 82         models += spp().keys()
     83 
     84     if mtype in ("all", "synapses"):

AttributeError: 'str' object has no attribute 'keys'
```

I don't know how to fix this issue and it is not listed on the troubleshoot page. Please help. Thank you very much.

**Comment by SimonSenn** [comment]
Has anyone managed to resolve the issue?

**Comment by heplesser** [comment]
In both cases reported above, there seems to be a mix-up between running a Python 3.9 interpreter and a NEST module built for Python 3.8. Conda should handle this properly in its dependency tracking.

Currently, NEST 3.3 is available on conda-forge in versions build for Python 3.8, 3.9 and 3.10. Could you please try again in a new, clean conda environment and report if this solves the problem?

**Comment by SimonSenn** [comment]
Thanks for the answer. Indeed, I have tried multiple times to install nest-simulator in a new and clean environment (nest_project2) but I always receive an import error as shown here:

Traceback (most recent call last):
  File "/Users/Simon/PycharmProjects/nest_project2/Try_5.py", line 1, in <module>
    import nest
  File "/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/__init__.py", line 53, in <module>
    from .ll_api import KernelAttribute  # noqa
  File "/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/ll_api.py", line 51, in <module>
    from . import pynestkernel as kernel      # noqa
ImportError: dlopen(/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/pynestkernel.so, 0x000A): Library not loaded: @rpath/libgsl.25.dylib
  Referenced from: /Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/libmodels.dylib
  Reason: tried: '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../../../nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../../../nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../../nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../../libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../../nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../../libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/bin/../lib/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/bin/../lib/libgsl.25.dylib' (no such file), '/usr/local/lib/libgsl.25.dylib' (no such file), '/usr/lib/libgsl.25.dylib' (no such file)Library not loaded: @rpath/libgsl.25.dylib
  Referenced from: /Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/libsli.dylib
  Reason: tried: '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../../../nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../../../nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/nest/../libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../../nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../../libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../lib/nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../../nest/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/python3.10/site-packages/nest/../../../libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/bin/../lib/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/lib/libgsl.25.dylib' (no such file), '/Users/Simon/opt/anaconda3/envs/nest_project2/bin/../lib/libgsl.25.dylib' (no such file), '/usr/local/lib/libgsl.25.dylib' (no such file), '/usr/lib/libgsl.25.dylib' (no such file)

Process finished with exit code 1

I figured that it is looking for the gsl package version 2.5. However, in the newest available nest library, gsl 2.7 is installed. I finally managed to import nest successfully by installing an old version (namely 2.18.0) in a new environment (nest_project). However, when I want to run a simple single-neuron simulation on PyCharm, it somehow does not seem to find the models.

May 12 15:12:28 stop [Error]: 
    No stopped context was found! 

Traceback (most recent call last):
  File "/Users/Simon/PycharmProjects/nest_project/Try_3.py", line 4, in <module>
    neuron = nest.Create("iaf_psc_alpha")
  File "/Users/Simon/opt/anaconda3/envs/nest_project/lib/python3.8/site-packages/nest/ll_api.py", line 246, in stack_checker_func
    return f(*args, **kwargs)
  File "/Users/Simon/opt/anaconda3/envs/nest_project/lib/python3.8/site-packages/nest/lib/hl_api_nodes.py", line 83, in Create
    gids = tuple(range(last_gid - n + 1, last_gid + 1))
TypeError: unsupported operand type(s) for -: 'str' and 'int'

Process finished with exit code 1


Thanks in advance for any help.

**Comment by heplesser** [comment]
@SimonSenn Based on the log, I assume that you are working on a Mac. Does you machine have AppleSilicon or an Intel CPU?

**Comment by SimonSenn** [comment]
Correct. My Mac has an Intel CPU.

**Comment by heplesser** [comment]
I just tested on my Mac with macOS 12.3, Intel CPU. I have version 4.12.0 with Python 3.8 in the base conda environment (miniconda, not full anaconda). I then executed (in base)
```
conda create --name nest_test -c conda-forge nest-simulator ipython jupyterlab
```
Conda then created an environment with Python 3.10 and GSL 2.7. After activating it, running `nest` directly and importing `nest` from `python` and `ipython` worked for me. My paths with `nest_test` activated look like this
```
PATH: /Users/plesser/opt/miniconda3/envs/nest_test/bin:/Users/plesser/bin:/Users/plesser/opt/miniconda3/envs/nest_test/bin:/Users/plesser/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin
PYTHONPATH: /Users/plesser/opt/miniconda3/envs/nest_test/lib/python3.10/site-packages
```
Could you compare with your setup?

**Comment by SimonSenn** [comment]
Thank you very much! It did not work in the beginning. Then, I uninstalled anaconda and all connected files and reinstalled miniconda. I then followed your steps and it works now. I don't know if it was a mismatch between different versions or if my paths were not set correctly. Anyway, thanks for your help!

**Comment by SimonSenn** [comment]
Sorry for bothering again. I encountered another problem it seems. I can import nest and all but when I try to apply commands like nest.Create() or nest.Connect(), PyCharm gives me a warning saying:

Cannot find reference 'Create' in '__init__.py'

Does anyone have a solution?

**Comment by heplesser** [comment]
NEST imports its components in an indirect way. This may confuse PyCharms code completion scheme and other features.

- In PyCharm, do you get the warning when running the code or is it a warning from the PyCharm editor? Could  you maybe post a screen shot?
- Could you test in a python or ipython shell that runs in the terminal, outside PyCharm?

**Comment by steffengraber** [comment]
@SimonSenn Do you still have the problem in PyCharm?

**Comment by steffengraber** [comment]
@roopa-pai , @JiaweiShen1116  Are your difficulties with the import of NEST solved with the advice given so far?

**Comment by steffengraber** [comment]
Closed. Seems to be solved.
