### ISSUE TITLE
Installing nest on Windows or WSL

### ISSUE THREAD

**Issue by appukuttan-shailesh** [nest/nest-simulator#2185]
We are currently in the process of preparing a tutorial for setting up PyNN and various simulators in various environments (Linux, Mac OS, Windows, EBRAINS Jupyterlab). The tutorial is intended for beginner to intermediate users, and thereore we wish to avoid more involved installation techniques. With this in mind:

1) Is it possible to currently install nest on Windows 10? If yes, are there any docs or instructions to follow?
A related ticket I found was [this](https://github.com/nest/nest-simulator/issues/889), but that link is no longer accessible (also potentially outdated now?).

2) Is using the Windows subsystem for Linux (WSL) an option worth considering? Are there are known issues/limitations to this approach? Would it be as simple as doing `sudo apt-get install nest` or similar?

Using a VirtualBox with Linux OS is a possible approach (and we already have such a tutorial created for Ubuntu), but was curious if there is any way of achieving this on Windows itself. Thanks.

**Comment by JanVogelsang** [comment]
I was not able to install Nest from source using WSL a couple of weeks ago. I can't remember the exact issue, but I know that I tried resolving the issue for quite some time and could not manage to get it running. If necessary I can see if I can provide more details about the issue after reactivating my Windows machine.

**Comment by heplesser** [comment]
Closing as we do not support Windows at present.

**Comment by Sobhan-Nili** [comment]
It is appreciated if you could remove the windows logo on the [installation page](https://nest-simulator.readthedocs.io/en/v3.4/installation/user.html#cross-platform-macos-linux-windows) as it is false claim and misleading. Providing WSL support isn't the same as running on windows.
