### ISSUE TITLE
Update documentation on gap junctions

### ISSUE THREAD

**Issue by jessica-mitchell** [nest/nest-simulator#2189]
**Describe the flaw**
The documentation for the gap junctions guide specifically refers to NEST 2.x .
https://nest-simulator.readthedocs.io/en/v3.1/guides/simulations_with_gap_junctions.html

**Suggest an improvement**
Ensure that the example works in NEST 3.x and update the text if anything is no longer relevant

**Comment by heplesser** [comment]
@jessica-mitchell Ping!
