### ISSUE TITLE
Remove DoubleDataEvent

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2199]
Type `DoubleDataEvent` is not used anywhere in NEST. It should be removed.

**Comment by clinssen** [comment]
Could I invoke Chesteron's fence here and ask what this was used for in the past?

**Comment by heplesser** [comment]
Chesterton's fence? Very long ago, we used the event to transport images to retinal filter modules. But that may have been before NEST 1.

**Comment by clinssen** [comment]
https://en.wikipedia.org/wiki/Chesterton%27s_fence#Chesterton's_fence

**Comment by heplesser** [comment]
After some reflection, since `DoubleDataEvent` works and may be of use again, I think we can leave it in the code. I thus close.
