### ISSUE TITLE
Incomplete documentation of 'noise_generator'

### ISSUE THREAD

**Issue by jschuecker** [nest/nest-simulator#22]
If the noise generator is connected to a neuron, the relation between its standard deviation 'std' and the actual fluctuations seen in the membrane potential of the neuron is not clear from the documentation.

**Comment by jschuecker** [comment]
Solved by @heplesser #50

**Comment by heplesser** [comment]
@apeyser I am a bit surprised that you closed the issue before #50 has been merged?

**Comment by apeyser** [comment]
My apologies --- I thought it had been merged.

**Comment by jougs** [comment]
#50 was merged, so I'm closing this for real now.
