### ISSUE TITLE
Problems with `Development.Module` change

### ISSUE THREAD

**Issue by ackurth** [nest/nest-simulator#2209]
**Describe the bug**
After the merge of #2195 I am not able to configure the current NEST master branch via cmake anymore.

**To Reproduce**
Python 3.9.7 (from Conda, python=3.9.7=hb7a2778_3_cpython )
Cmake 3.21.3 (from Conda, cmake=3.21.3=h8897547_0)

**Desktop/Environment (please complete the following information):**
 - OS: NAME="Ubuntu" VERSION="20.04.3 LTS (Focal Fossa)"
 - Shell: bash
 - NEST-Version: master

**Additional context**
cmake -DCMAKE_INSTALL_PREFIX:PATH=$install_dir -Dwith-python=ON -Dwith-ltdl=OFF -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc $nest_dir
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Host triple: x86_64-pc-linux
-- Target triple: x86_64-pc-linux
CMake Error at /home/kurth/miniconda3/envs/nest_dev/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python (missing: Development.Module) (found suitable version
  "3.9.7", minimum required is "3.8")
Call Stack (most recent call first):
  /home/kurth/miniconda3/envs/nest_dev/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/kurth/miniconda3/envs/nest_dev/share/cmake-3.21/Modules/FindPython/Support.cmake:3166 (find_package_handle_standard_args)
  /home/kurth/miniconda3/envs/nest_dev/share/cmake-3.21/Modules/FindPython.cmake:514 (include)
  cmake/ProcessOptions.cmake:399 (find_package)
  CMakeLists.txt:130 (nest_process_with_python)

-- Configuring incomplete, errors occurred!

**Comment by Helveg** [comment]
I'll restructure the piece of code to first do a non-required `Development.Module` search, then fall back to `Development` if `Python_FOUND` is not true, that should preserve default behavior in all cases.

**Comment by jougs** [comment]
@ackurth: I observed a similar problem in a build of mine, which went away after I deleted my `CMakeCache.txt` and reran CMake anew. Could you please check if this also solves the problem for you? Thanks!

**Comment by Helveg** [comment]
I can also confirm that I encountered the problem with a stale build folder, I just removed it and reran CMake from scratch, that solved the issue. https://github.com/nest/nest-simulator/pull/2210 lists these issues in a warning if `Development` components are found but `Development.Module` isn't.

**Comment by ackurth** [comment]
@jougs: This solves the issue for me as well.

**Comment by jougs** [comment]
Great!

**Comment by terhorstd** [comment]
amazingly fast resolution! Great work everyone! :rocket:
