### ISSUE TITLE
Use WSGI provider that is available on Mac M1 

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#2211]
**Is your feature request related to a problem? Please describe.**
Appearantly the webserver we depend on for NEST server - `uwsgi` - can not be installed on Mac M1 machines. There appears to be no specific feature we require other than [WSGI, a PEP333 spec,](https://www.python.org/dev/peps/pep-0333/) that is also implemented by many other alternatives.

**Describe the solution you'd like**
Let's check if there's any alternative implementations that support Mac M1 such as [`gunicorn`](https://gunicorn.org/), [`eventlet`](https://eventlet.net/doc/modules/wsgi.html) or [`tornado`](https://www.tornadoweb.org/en/stable/wsgi.html)

**Comment by heplesser** [comment]
All three (tornado, eventlet, gunicorn) are available on conda-forge for M1, eventlet under "no-arch" and the other two under "osx-arm64". So any of the three should do. So capabilities and the size of the community around a package (as proxy for likelihood of long-term support) should be guiding which one to choose.

**Comment by Helveg** [comment]
1. [`tornado`](https://github.com/tornadoweb/tornado) 20.3k stars, 5k forks
1. [`gunicorn`](https://github.com/benoitc/gunicorn) 8k, 1.5k forks
1. [`eventlet`](https://github.com/eventlet/eventlet) 1.1k stars, 300 forks

I personally have experience with `gunicorn` as being very easy to use. Basically just `gunicorn --workers=4 my:wsgi_module`. 
I can look into `tornado`, looks like it needs a tiny bit of WSGI wrapping boilerplate.

**Comment by Helveg** [comment]
The `tornado` [documentation main page](https://www.tornadoweb.org/en/stable/#threads-and-wsgi) mentions that WSGI is not a main focus of the project:

> While some support of WSGI is available in the tornado.wsgi module, it is not a focus of development and most applications should be written to use Tornado’s own interfaces (such as tornado.web) directly instead of using WSGI.

Compared to the clear [landing page](https://gunicorn.org/#quickstart) of `gunicorn` with complete quick-start and deployment guide including `nginx`-plug-and-play config I think we should pick `gunicorn`.

**Comment by heplesser** [comment]
Maybe a topic for the next NEST Open Developer VC @terhorstd. @Helveg Could you present the issue there?

**Comment by terhorstd** [comment]
@babsey , could you comment on this?
