### ISSUE TITLE
Enable autapses for structural plasticity in NEST 3

### ISSUE THREAD

**Issue by sdiazpier** [nest/nest-simulator#2212]
**Describe the bug**
When migrating to NEST 3, a set of valid parameters have been specified to be provided to SetKernelStatus which does not include all parameters which were supported before by SetStructuralPlasticityStatus in previous versions of NEST 2. This has as a consequence that the connection builder generated with plastic synapses can not include the autapses parameter.

**To Reproduce**
nest.SetKernelStatus({
    'structural_plasticity_synapses': {
        'syn1': {
            'model': 'copied_synapse_model',
            'post_synaptic_element': 'Den_exc',
            'pre_synaptic_element': 'Axon_exc',
        }
    },
     'autapses': False,
})

In NEST 3.1 produces: Error: "`autapses` is not a valid kernel parameter, valid parameters are: ..."

**Expected behavior**
autapses should still be supported for structural plasticity. Probably the connection parameters need to be sent through the structural_plasticity_synapses parameter.

**Comment by stinebuu** [comment]
@sdiazpier `autapses` has been renamed to `allow_autapses` with NEST 3. It is also not possible to set the parameter with the kernel status, it needs to be sent with the connection dictionary:
```
nest.Connect(nrns, nrns, {'rule': 'fixed_indegree', 'indegree': 3, 'allow_autapses': False})
```

**Comment by neuroady** [comment]
@stinebuu with structural plasticity, connections are not explicitly defined via `nest.Connect(nrns, nrns, conn_dict, syn_dict)`. Rather neurons are given synaptic elements which establish connections based on some rule (`nest.EnableSturcturalPlasticity()`). Therefore, which connections are created cannot (and should not) be explicitly defined, rather it's the Structural Plasticity module which creates them. In NESTv3.1 all connections so made have autapses and multapses by default. And there is no way to switch them off. Well, because there is no way to access these parameters when using structural plasticity. Meanwhile, this behavior could be controlled in NESTv2.20.x via `SetKernelStatus` as @sdiazpier has mentioned above.

**Comment by sdiazpier** [comment]
It is possible to enable or disable autapses for the specific connection builder. The solution is to send this information in the structural_plasticity_synapses parameter and enable this at the moment of creation of the builder. I am working on a prototype, should be available soon.

**Comment by ErbB4** [comment]
Hey, I had the same issue with moving from NEST2.x to NEST3.1 concerning structural plasticity. I am using this line to assign synaptic elements to my synapse with structural plasticity:

nest.SetKernelStatus({    
    "structural_plasticity_synapses":{
                                'syn_exc':{
                                'model':                 'msp_excitatory',
                                'post_synaptic_element': 'Den_exc',
                                'pre_synaptic_element':  'Axon_exc',
                                }
    }
})

Even I removed autapses as described above, I still got this error:

BadProperty in SLI function SetKernelStatus: Synapse spec must contain synapse model.

Besides, I used to set min_delay and max_delay using the same SetKernelStatus here, I got an error message too. To debug it, I have removed it.

Do you perhaps have an example code on how to use structural plasticity in NEST 3.1? 

Thanks a lot!

**Comment by stinebuu** [comment]
@sdiazpier Any updates on this? :)

**Comment by sdiazpier** [comment]
Dear @swathianil I have generated a new branch with the modification to specify if atuapses are to be allowed or not with SP connections. The PR is currently in a test phase, once it has passed all CI tests I would ask you to please test it and validate that the functionality you are looking for is covered. 
I am very sorry for the long time this took. If you have further questions about moving to Nest3 pleae contact me and we can look at them together.

**Comment by swathianil** [comment]
> Hey, I had the same issue with moving from NEST2.x to NEST3.1 concerning structural plasticity. I am using this line to assign synaptic elements to my synapse with structural plasticity:
> 
> nest.SetKernelStatus({ "structural_plasticity_synapses":{ 'syn_exc':{ 'model': 'msp_excitatory', 'post_synaptic_element': 'Den_exc', 'pre_synaptic_element': 'Axon_exc', } } })
> 
> Even I removed autapses as described above, I still got this error:
> 
> BadProperty in SLI function SetKernelStatus: Synapse spec must contain synapse model.
> 
> Besides, I used to set min_delay and max_delay using the same SetKernelStatus here, I got an error message too. To debug it, I have removed it.
> 
> Do you perhaps have an example code on how to use structural plasticity in NEST 3.1?
> 
> Thanks a lot!

@ErbB4 'model' within nest.SetKernelStatus is deprecated in Nest3, its renamed 'synapse_model'. So in your case, this should work:

nest.SetKernelStatus({
"structural_plasticity_synapses":{
'syn_exc':{
'synapse_model': 'msp_excitatory',
'post_synaptic_element': 'Den_exc',
'pre_synaptic_element': 'Axon_exc',
}
}
})

**Comment by swathianil** [comment]
> Dear @swathianil I have generated a new branch with the modification to specify if atuapses are to be allowed or not with SP connections. The PR is currently in a test phase, once it has passed all CI tests I would ask you to please test it and validate that the functionality you are looking for is covered. I am very sorry for the long time this took. If you have further questions about moving to Nest3 pleae contact me and we can look at them together.

@sdiazpier Sorry for the delay, I tested the functionality using nest installation built from the sp_autapses branch. Unfortunately, still doesn't seem to accept autapses as a feature:

> nest.SetKernelStatus({
	    'structural_plasticity_synapses': {
		'synapse_ex': {
		    'synapse_model': 'msp_excitatory',
		    'post_synaptic_element': 'Den_ex',
		    'pre_synaptic_element': 'Axon_ex',
		    'allow_autapses': False,
		}
	    }
	})

-----------------------------------------------------------------------------------------------------------------------------------------------
NESTErrors.DictError: DictError in SLI function SetKernelStatus: Unused dictionary items:  structural_plasticity_synapses::synapse_ex::allow_autapses
------------------------------------------------------------------------------------------------------------------------------------------------

Hope this helps!
