### ISSUE TITLE
Rename typedef variables in NEST

### ISSUE THREAD

**Issue by pnbabu** [nest/nest-simulator#2215]
The typedef variables present in `nest_types.h` should be renamed to names with an appropriate prefix or suffix.

Currently, NESTML synapse models cannot use a variable named `delay` to identify the dendritic delay because it conflicts with the NEST typedef of the same name. The typedefs could possibly be renamed with a suffix `_t` (but is generally not recommended as mentioned [here](https://stackoverflow.com/questions/231760/what-does-a-type-followed-by-t-underscore-t-represent)) or with a prefix with `nest_`. Any suggestions?

**Comment by heplesser** [comment]
We consciously decided not to use type-suffixes in NEST code. We will review the use of names such as `delay` for types.

**Comment by clinssen** [comment]
Note that it would be a possibility to use namespaces to isolate the typedefs, e.g.
```C++
namespace nest_types {
    typedef std::vector< size_t > foobar;
}

void f(nest_types::foobar& x) {
   ...
}
```
