### ISSUE TITLE
Learning rules available in NEST

### ISSUE THREAD

**Issue by Dola47** [nest/nest-simulator#2217]
Dear All,

I am about to use NEST,  I found that we have plenty of neuron models and a lot of synaptic types.

The question is are we able to use NEST to train our spiking models end to end in the spiking domain? I mean do we have some learning rules available like STDP or Surrogate gradient descent or others available as well in NEST? Or, NEST just can be used to define the network (neurons and synapses)

Thanks.

**Comment by stinebuu** [comment]
Dear @Dola47, this is a good question for our [mailing list](https://nest-simulator.readthedocs.io/en/latest/contribute/mailing_list_guidelines.html). It has a lot of active users that can help you. I am therefore closing this here.
