### ISSUE TITLE
Build and push docker images with Githubactions.

### ISSUE THREAD

**Issue by lekshmideepu** [nest/nest-simulator#2224]
In order to automate the tasks, I think it would be nice to have the feature of building and pushing docker images using githubactions.

**Comment by lekshmideepu** [comment]
Just now had a discussion with @steffengraber  He gave more insights into this from his experiences.

**Comment by clinssen** [comment]
I would suggest to trigger a build by a new versioned release of either NEST, NESTML, NEST Desktop, or any of the other tools in the NEST ecosystem and hosted on github.com/nest.

**Comment by steffengraber** [comment]
I think in addition, timed based builds should always keep the images up to date to avoid vulnerabilities. 

As already discussed with @lekshmideepu, here is a first approach for these automated builds https://github.com/steffengraber/nest-docker/blob/master/.github/workflows/docker-image-latest.yml.

Is this the right place to discuss, or should this happen under https://github.com/nest/nest-docker?

**Comment by heplesser** [comment]
@steffengraber Don't we have this in place already?

**Comment by steffengraber** [comment]
We moved to gitlab pipelines. This is done and therefore closed.
