### ISSUE TITLE
Error creating conda-forge packages for NEST 3.x

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#2237]
Since NEST 3.0 the conda packages are created incorrectly in the conda-forge workflow.

Whether with version 3.1 or the current version from master, the following error occurs when testing the package:

    scanner.cc:581: bool Scanner::operator()(Token&): Assertion `in->good()' failed.

Here is the entire build log for a NEST 3.1 build with python 3.8:

https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/424587/logs/24

@terhorstd @jessica-mitchell

**Comment by heplesser** [comment]
This seems related to a similar issue (with a docker container?) that we had a longer debug session on about two months ago, where somehow paths went badly wrong. Is there any way to activate C++-level and SLI-level debugging for this "import nest" on the conda-forge build machine?

**Comment by heplesser** [comment]
Any chance to run this with Valgrind or so to check if there are some incorrect memory accesses messing up path strings?

**Comment by steffengraber** [comment]
> Any chance to run this with Valgrind or so to check if there are some incorrect memory accesses messing up path strings?

@heplesser Will be possible. But I need your expertise to integrate it correctly.

**Comment by heplesser** [comment]
@hakonsbm Could you help @steffengraber? I think you have more debugging experience, esp with valgrind.

**Comment by heplesser** [comment]
The build-log link above does not longer work for me. 

At an earlier point of exploring this problem, we found that spurious zero-bytes in `slistartupfile` caused this problem. Could you insert [at the beginning of SLIStartup::SLIStartup()](https://github.com/nest/nest-simulator/blob/5f427cdc87f3120aaa6367c49c7dd77140829971/sli/slistartup.cc#L190) the following debugging output
```c++
  std::cout << "sliprefix: ]" << sliprefix << "[" << std::endl;
  std::cout << "sliprefix cstr: ]" << std::string(sliprefix.c_str()) << "[" << std::endl;
  std::cout << "sliprefix bytes: ";
  for ( auto i = 0 ; i < sliprefix.size() ; ++i )
    std::cout << int(sliprefix[i]) << " ";
  std::cout << std::endl << std::endl;

  std::cout << "startupfile: ]" << startupfile << "[" << std::endl;
  std::cout << "startupfile cstr: ]" << std::string(startupfile.c_str()) << "[" << std::endl;
  std::cout << "startupfile bytes: ";
  for ( auto i = 0 ; i < startupfile.size() ; ++i )
    std::cout << int(startupfile[i]) << " ";
  std::cout << std::endl;
```
It should reveal if spurious zero-bytes appear in the middle of a string and thus block the startup process.

**Comment by terhorstd** [comment]
Since this is a deeper issue, we would do the release now for all other deployment formats and add a patch to the 3.x releases later – potentially even only in the conda packaging step.
Removing from milestone.

**Comment by steffengraber** [comment]
Conda package for NEST v3.3 is available again. https://github.com/nest/nest-simulator/commit/05539ffdbe13affc3b8bed6de2095dffed1b4a16 has solved the problem.
