### ISSUE TITLE
Lazy loading modules for PyNEST

### ISSUE THREAD

**Issue by babsey** [nest/nest-simulator#2241]
On initializing (`import nest`) nest doesn't import modules like `spatial`, `visualization`, `raster_plot` and `voltage trace`.
Instead it uses lazy loading approach but the first call of one of these modules shows `AttributeError`.

To solve this issue I added the lines to re-import called module in `/pynest/nest/__init__.py` (#2239, line 470).
I think this solution is not optimal. Maybe anyone can find a better approach.

1. Just call `nest.spatial` in Python Interpreter.

It raises `AttributeError` which disturbs the construction approach.

![image](https://user-images.githubusercontent.com/620984/145681994-82f9b437-1e90-49cd-a17f-66fae9a69168.png)

**Comment by Helveg** [comment]
I can't reproduce your issue on current master 8315aec1b8d9387882b655144d62bb0b3cd6242f

```
(nest-dev) robin@neurocomp:~/nest-simulator$ python
Python 3.9.9 (main, Dec  5 2021, 20:57:59) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nest
              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: master@8315aec1b
 Built: Dec 11 2021 20:46:31

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.

>>> nest.spatial
<module 'nest.spatial' from '/home/robin/.pyenv/versions/nest-dev/lib/python3.9/site-packages/nest/spatial/__init__.py'>
```

I'm not sure unit tests could ever pass if the entirety of `nest.spatial` is unavailable either. Could there be other conditions for this problem to occur? Can you try regular `python` instead of `ipython` for example?

**Comment by babsey** [comment]
I also tested in python3 and it shows the same error:

```
spreizer@Latitude-5300:~$ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nest

              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: master@8315aec1b
 Built: Dec 11 2021 16:20:51

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.

>>> nest.spatial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'nest' has no attribute 'spatial'
>>> 
```

**Comment by babsey** [comment]
And also tested in docker image of nest (`https://github.com/nest/nest-docker/tree/master/src/latest`)
```
root@b2c3d6b2fe84:/# python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nest

              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: UNKNOWN
 Built: Dec 12 2021 09:11:16

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.

>>> nest.spatial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'nest' has no attribute 'spatial'
```

**Comment by Helveg** [comment]
I can reproduce it on Python 3.8 .. Interesting :roll_eyes:

**Comment by Helveg** [comment]
Ok, so the problem is that since #2220 the import machinery can't set attributes on `nest`.
