### ISSUE TITLE
C-make options and other references to Bluegene and K-computer still exists

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#2249]
It is still possible to build NEST with Bluegeene and the K-computer, even though the machines do not exist anymore. See for instance

https://github.com/nest/nest-simulator/blob/06f9276ecef401b0e5cf2cfef8a6f028470ba1c1/cmake/ProcessOptions.cmake#L143-L146

When searching through the code base for `bluegene` and `k-computer` quite a lot of references show up. All the references to the machines should probably be removed.

**Comment by gtrensch** [comment]
Resolved with #2306.
