### ISSUE TITLE
refractory_input property cannot be set on iaf_psc_delta_canon

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#225]
The `refractory_input` property cannot be set on `iaf_psc_delta_canon`. The corresponding data member `with_refr_input_` exists, but is incorrectly placed in `S_`; it should be in `P_`. A getter for the property exists.

Before fixing this, create a test that verifies that input during the refractory period is handled correctly for `refractory_input` set to `true` and `false`.

**Comment by heplesser** [comment]
I am seriously wondering if we should pursue this matter. Registering input arriving at a delta-synapse neuron during the refractory time should lead to loss of that input. Due to user needs, `iaf_psc_delta` provide a possibility of registering such input, but I now wonder if we should really propagate this to other models.

**Comment by jougs** [comment]
I agree that we should not currently do this and am thus closing.
