### ISSUE TITLE
Missing `model` name in NodeCollection

### ISSUE THREAD

**Issue by med-ayssar** [nest/nest-simulator#2255]
**Describe the bug**
Calling `NodeCollection.get("model")` or `nest.GetStatus(NodeCollection, "model")` returns a string containing `UnknownNode`.
The following problem happens only if we create a `NodeCollection` instance from an external model.
**To Reproduce**
1. Call `to_nest` and `install_nest` from `PyNestml` module
2. Install the module
3. Create a population with any arbitrary size
4. Call `NodeCollection.get("model")` or `nest.GetStatus(NodeCollection, "model")`

**Expected behavior**
Although the `NodeCollection` instance shows the correct name of the model when we call the `__str__` method, but retrieving the model's name returns an `UnknownNode`.

Desktop/Environment (please complete the following information):

OS: Ubuntu-20.04
NEST-Version: v3.1

**Comment by hakonsbm** [comment]
@med-ayssar Looks like there is something wrong with the `model_id_`, see below:

https://github.com/nest/nest-simulator/blob/cb61289cc5751f68eb42f5eaf6564acc03823252/nestkernel/node.cpp#L107-L116

**Comment by jougs** [comment]
This should also be checked and possibly solved with the module system refactoring.
