### ISSUE TITLE
Documentation and behavior differ concerning CurrentEvent input to some precise models

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#226]
Documentation for `iaf_psc_delta_canon` and `iaf_psc_alpha_canon` states that these models do not accept `CurrentEvent` input, even though the neurons do so (as do the other precise neurons). Current input is handled as piecewise constant input that can only change at points in the time grid.

The comments need to be reviewed and we need to check whether tests for current input to precise neurons exists.

Documentation for all precise models should point out that input currents are piecewise constant and can change only a grid points.

**Comment by jessica-mitchell** [comment]
@heplesser It looks like the documentation in ` iaf_psc_delta_canon` has been corrected: 

> The iaf_psc_delta_canon neuron accepts CurrentEvent connections.    However, the present method for transmitting CurrentEvents in  NEST (sending the current to be applied) is not compatible with off-grid  currents, if more than one CurrentEvent-connection exists. Once CurrentEvents are changed to transmit change-of-current-strength, this problem will disappear and the canonical neuron will also be able to handle CurrentEvent

Compared to `iaf_psc_alpha_canon` :

> The iaf_psc_delta_canon neuron does not accept CurrentEvent connections. This is because the present method for transmitting CurrentEvents in NEST (sending the current to be applied) is not compatible with off-grid currents, if more than one CurrentEvent-connection exists

Is this statement in the `iaf_psc_delta_canon`  accurate? Should the same text be used for `iaf_psc_alpha_canon`?
