### ISSUE TITLE
Using `pmr::vector` alters the `hpc_benchmark.sli` results

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#2264]
Using my branch, `pmr` at: https://github.com/ikitayama/nest-simulator,

the results are:
```
Total number of entries: 54
0 10.148 # average rate
0 11250 # num_neurons
0 126574750 # num_connections
0 1.5 # min_delay
0 1.5 # max_delay
0 24416 # local_spike_counter
```

The average rate is low, and spike numbers are also low, compared to the `master` branch. At least in GCC,
this is not experimental anymore, thus I believe the implementation is solid, I wonder if there might be part of
the NEST code causing this.

**Comment by ikitayama** [comment]
I built NEST `master` with homebrew g++-11 on M1 Max.

**Comment by ikitayama** [comment]
If I switch to `homebrew` `clang-13` on M1 Max, the nest binary built from the pmr branch produces the same results.

**Comment by heplesser** [comment]
Do you get low firing rates for different random number generator seeds?

The Notes section in CPPReference's article on polymorphic allocators points to some limitations, including cases of undefined behaviour, see https://en.cppreference.com/w/cpp/memory/polymorphic_allocator. Could that explain the different behaviour you see?

I am also curious why you want to introduce polymorphic allocators to NEST?

**Comment by ikitayama** [comment]
Because I'd like to use the unified shared memory scheme for OpenMP based
offloading; and secondly, the C++17 scheme is
easier for implementing a custom allocator (just by inheriting from the
memory_resource class).

**Comment by ikitayama** [comment]
I read the Notes as an incompatibility between those normal vector whose
allocator is std::alloc and std::pmt::vector, no? If the same polymorphic
allocator is used throughout the codebase, problem might not occur.

**Comment by ikitayama** [comment]
> Do you get low firing rates for different random number generator seeds?
> 
> The Notes section in CPPReference's article on polymorphic allocators points to some limitations, including cases of undefined behaviour, see https://en.cppreference.com/w/cpp/memory/polymorphic_allocator. Could that explain the different behaviour you see?

I asked the GCC community and was told as long as I use the same Polymorphic Allocator for all the vector, ie `std::pmr::vector` no problem. Mixing the use of `std::vector` and `std::pmr::vector` is problematic, as swap() does not expand the allocator. In my experience, libstdc++ is implemented so that it detects at build time rather than at run time.

**Comment by heplesser** [comment]
@ikitayama Can this issue be closed?

**Comment by ikitayama** [comment]
Sure.
