### ISSUE TITLE
Examples and tests without code duplication

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#2265]
Although examples and tests are written with different purposes and audiences in mind, they often share a lot of the same code, for instance for setting up the network and taking recordings. The tests then additionally do some assertions on the recordings, whereas the examples would typically plot them instead.

We should come up with an organisation that prevents code duplication, and allows as many examples (what are now often tests) as possible to be included in the documentation.

**Comment by heplesser** [comment]
Closing this as it is not an directly actionable issue.
