### ISSUE TITLE
Add tools to developer environment

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#2271]
**Describe the flaw**
In the [developer documentation](https://nest-simulator.readthedocs.io/en/latest/contribute/index.html) currently the [coding-guidelines](https://nest-simulator.readthedocs.io/en/latest/contribute/coding_guidelines_cpp.html#code-style-cpp) describe many separate tool requirements and give usage instructions, but only some have installation details. Additionally, the process of setting up a development environment with many different tools seems lengthy and intricate (though it not necessarily is). There is no "do-this-and-you're-set" solution.

**Suggest an improvement**
Add all required developer tools to the `environment.yml` and explicitly mention the conda environment setup also in the *coding-guidelines* document. This would be *additionally* to the tool usage details.

The [documentation workflow](https://nest-simulator.readthedocs.io/en/latest/documentation_workflow/user_documentation_workflow.html) has a suggested conda environment with most tools installed. Also for the coding workflows and scripts in `build_support/` most packages are already installed or could be added. Especially the static checks like `clang-format` would be very interesting to have in the environment locally as most developers would reduce turn-around time when running specific checks already before pushing. With the switch to a more recent clang version in [#2235](https://github.com/nest/nest-simulator/pull/2235) it is possible to have clang-format installed into the conda environment by default.

**Supporting materials**

* clang-format via conda env

  Either directly via conda-forge channel (currently provides only very recent versions, but not 9.x)
  ```
  $ conda search -c conda-forge clang-format
  Loading channels: done
  # Name                       Version           Build  Channel             
  clang-format                  12.0.1 default_ha53f305_3  conda-forge         
  clang-format                  12.0.1 default_ha53f305_4  conda-forge         
  clang-format                  13.0.0 default_hc23dcda_0  conda-forge  
  ```
  Or, indirectly via `pip`
  PyPI has more clang-format versions available, see [here](https://pypi.org/project/clang-format/#history)

* cppcheck via conda env
  ```
  conda search cppcheck -c conda-forge
  Loading channels: done
  # Name                       Version           Build  Channel             
  cppcheck                        1.80               0  conda-forge         
  cppcheck                        1.84               0  conda-forge         
  cppcheck                        1.84   hf484d3e_1000  conda-forge  
  …
  cppcheck                       2.6.2  py37h683f61f_0  conda-forge         
  cppcheck                       2.6.2  py37hc0f4ff5_0  conda-forge         
  cppcheck                       2.6.2  py38hbffb2f6_0  conda-forge         
  cppcheck                       2.6.2  py39hdb17a17_0  conda-forge  
  ```
* python tools for PEP8 checking are also available

etc.

**Comment by jessica-mitchell** [comment]
@terhorstd I was looking at including `cppcheck` to the `environment.yml` but the version mentioned in the code is an older version (1.69) and it is not available in conda or pip.

`pycodestyle` is what we use for pep8 and is already mentioned in the `environment.yml` file. However, it seems to be ignored, when running the static_code_analysis locally.
