### ISSUE TITLE
release note shows 3.2.1, but the tag is 3.2

### ISSUE THREAD

**Issue by chenrui333** [nest/nest-simulator#2275]
👋  it is bit weird that the release note shows 3.2.1, but the tag is actually 3.2, just raise this issue to confirm if that is intended. Thanks!!
![image](https://user-images.githubusercontent.com/1580956/150659482-722eda48-c280-43fb-80aa-569e5c2eb3b5.png)

- relates to https://github.com/Homebrew/homebrew-core/pull/93618

**Comment by terhorstd** [comment]
That was only temporary. Is not an issue anymore.
