### ISSUE TITLE
Dependency between `nest.CopyModel` and `nest.Install`

### ISSUE THREAD

**Issue by med-ayssar** [nest/nest-simulator#2287]
**Describe the bug**
Once the function`nest.CopyModel` is called, it prevents from installing further modules, and I don't see any necessary dependencies between copying an existing model and installing a new one.  
**To Reproduce**
1.  Install an existing synapse model `synapsemodule.so`
2. Call `nest.CopyModel("installed_synapse_name, "new_synapse_name")`
3. Install an existing neuron model `neuronmodule.so`
4. After the call in the third step, SLI throws the following:
     * `DynamicModuleManagementError in SLI function Install: Modules cannot be installed after CopyModel has been called` 

**Expected behavior**
`nest.CopyModel` and `nest.Install` must be decoupled.

**Comment by stinebuu** [comment]
@jougs Do you think this will be fixed with the module system refactoring?

**Comment by med-ayssar** [comment]
I have tested this again with the current NEST version, and it seems that it has been already fixed!
