### ISSUE TITLE
make installcheck fail (3 Errors)

### ISSUE THREAD

**Issue by higain** [nest/nest-simulator#230]
Hi, after a few failed attempts of installing & google research I gave up and now hope you can help me.

I'm on a VM running Ubuntu 14.04.3 64 bit, trying to install a freshly downloaded nest 2.10.0 with python 2.7.
I've narrowed it down to 3 tests:
- unittests/test_iaf_1to2_ex.sli
- unittests/test_iaf_min_delay_set.sli
- unittests/test_iaf_min_delay_simblocks.sli

report is attached.
[nesttests.zip](https://github.com/nest/nest-simulator/files/134605/nesttests.zip)

Hopefully you can tell me how to fix this!

Cheers

**Comment by tammoippen** [comment]
Hello @higain,

It seems that `nesttests.zip` contains an empty folder `reports`. Can you please attach the `config.log` as well?

Best, Tammo

**Comment by higain** [comment]
Hi @tammoippen, 

sorry, my bad. Here's the zip again.

Cheers
[logs.zip](https://github.com/nest/nest-simulator/files/137982/logs.zip)

**Comment by heplesser** [comment]
@higain I compiled a freshly downloaded nest-2.10.0 on a Ubuntu 14.04 LTS 64 bit virtual box with gcc 4.8.4 and GSL 1.16. All 729 tests passed, so I am not sure what may go wrong on you machine.

**Comment by heplesser** [comment]
Closed due to inactivity.
