### ISSUE TITLE
`make install` unconditionally tries to install python dependencies via pip

### ISSUE THREAD

**Issue by StefanBruens** [nest/nest-simulator#2300]
`make install` should install nest, but should not try to install all its python dependencies.

Build hosts in general do not have an internet connection, but are often isolated hosts for security and reproducibility reasons. 

**To Reproduce**
cd build; cmake --prefix=/usr ..
make
make DESTDIR=/tmp/staging install

**Expected behavior**
All files belonging to `nest` should be installed into `/tmp/staging/usr`. No extra files should be installed.

**Desktop/Environment (please complete the following information):**
 - OS: openSUSE Tumbleweed, openSUSE Leap
 - Python-Version: 3.8
 - NEST-Version: 3.2
 - Installation: rpm

**Comment by terhorstd** [comment]
Hi @StefanBruens , my apologies for the delay.
Would the `-Dwith-python=OFF` flag help in your case? Then `make install` will not build the PyNEST interface.

**Comment by StefanBruens** [comment]
Previously I have been informed the Python interface is the only official, stable API of nest, and API compatibility is not a concern for the C++ interface.

> So far, we have never promised a stable C++ API. The closest we have come to an explicit API is the set of functions defined in `nest.h`. We rather focus on stability of the user interface at the Python level.

_Originally posted by @heplesser in https://github.com/nest/nest-simulator/issues/2376#issuecomment-1105825821_

So disabling the Python API would create a package without any stable, external interface. Obviously this is not viable.

**Comment by StefanBruens** [comment]
This issue is still current (3.3).

**Comment by terhorstd** [comment]
Yes, I completely agree. I don't recall why that should be necessary, @Helveg was this related to the wheel?

**Comment by terhorstd** [comment]
Hey, thanks @Helveg for the fast reply! @StefanBruens would you be interested in joining this effort from the MacOS side?

**Comment by Helveg** [comment]
FWIW: "being a proper binary extension to Python" boils down to having NEST's CMake setup successfully executed by `scikit-build`.

**Comment by StefanBruens** [comment]
I haven't touched a Mac for over 10 years ...

**Comment by terhorstd** [comment]
My appologies @StefanBruens, I wrongly implied this from the `if ( APPLE )` changes in PR 2439 and we're notoriously short in developers on mac, so my hopes went up a bit too much…

**Comment by heplesser** [comment]
@Helveg Will this get fixed with the wheel-based installation approach?

**Comment by Helveg** [comment]
@StefanBruens during the hackathon @terhorstd and I discussed the responsibilities of the build systems some more and our current proposal is that CMake is in charge of building the NEST library, and the Python build systems will invoke the CMake build and pick it up as a binary extension module. By default CMake will also invoke pip as a build frontend to install NEST as a valid Python package.

This later part will be togglable with `-Dwith-python-package=OFF`. In that case no Python related steps will be ran during the CMake build, other than building against its ABI. If you do want this Python package to be produced, then I'm sure we can find a way to pass the proper `--root` argument to the pip command.

The timeline on this is that it will land together with the next-generation PyNEST in NEST 4.0.
