### ISSUE TITLE
Exception when specying synapse models as list in Connect()

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#2301]
An exception happens when connecting with a given list of synapse models. This is (probably?) a rather obscure use case, and we could possibly deprecate this feature, which would amount to allowing only one single synapse type (such as "stdp_synapse") to be instantiated during one single Connect() call.

Minimal reproducer:
```python
import nest
n = nest.Create("iaf_psc_exp", 20)
nest.Connect(n[:10], n[10:], "one_to_one", syn_spec={"synapse_model": 42*["static_synapse"]})
--> NESTError: 'synapse_model' has to be an array of dimension 10, a scalar or a dictionary.
```
OK, so we can specify the synapse models as a list, but we need to give a list with the correct length!
```python
nest.Connect(n[:10], n[10:], "one_to_one", syn_spec={"synapse_model": 10*["static_synapse"]})
```
However, when doing this, we get:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-4f099322e6b2> in <module>
----> 1 nest.Connect(n[:10], n[10:], "one_to_one", syn_spec={"synapse_model": 10*["static_synapse"]})

~/julich/nest-simulator-install/lib/python3.9/site-packages/nest/ll_api.py in stack_checker_func(*args, **kwargs)
    225     def stack_checker_func(*args, **kwargs):
    226         if not get_debug():
--> 227             return f(*args, **kwargs)
    228         else:
    229             sr('count')

~/julich/nest-simulator-install/lib/python3.9/site-packages/nest/lib/hl_api_connections.py in Connect(pre, post, conn_spec, syn_spec, return_synapsecollection)
    281         sps(processed_conn_spec)
    282         if processed_syn_spec is not None:
--> 283             sps(processed_syn_spec)
    284         sr('Connect')
    285 

pynestkernel.pyx in pynestkernel.NESTEngine.push()

pynestkernel.pyx in pynestkernel.python_object_to_datum()

pynestkernel.pyx in pynestkernel.python_object_to_datum()

AttributeError: type object 'NESTError' has no attribute 'PyNESTError'
```

**Comment by heplesser** [comment]
I believe this was never intended to be possible. It could also create trouble with parameters, as different synapse models have different parameters. So we should forbid `syn_spec` from being anything but a string or a [CollocatedSynapse](https://nest-simulator.readthedocs.io/en/latest/release_notes/v3.0/features/handling_connections.html#collocated-synapses) object. I think we can prohibit this right away without deprecation, as it has never worked.

And we should find out about the error in the error handler.
