### ISSUE TITLE
404 Site not found on nest-simulator.org

### ISSUE THREAD

**Issue by JanVogelsang** [nest/nest-simulator#2308]
In the [contributing section of the community page of nest-simulator.org](https://www.nest-simulator.org/community/#contributing) there is a dead link in the second paragraph:
"Please see the _NEST developer space_ for information"
The "NEST developer space" leads to the nest's github.io page which does not seem to exist (anymore?).
The correct page might be:
https://nest-simulator.readthedocs.io/en/latest/contribute/index.html

**Comment by jessica-mitchell** [comment]
Thanks for pointing this out. @steffengraber can you update the link?

**Comment by steffengraber** [comment]
The link is updated. Should we continue to call it "NEST developer space"?

**Comment by jessica-mitchell** [comment]
I think for now we can leave the name as is. Closing issue as link is fixed.
