### ISSUE TITLE
undefined symbol: __kmpc_end_critical

### ISSUE THREAD

**Issue by antolikjan** [nest/nest-simulator#231]
We are attempting to install nest 2.10.0 on a cluster with intel compiler suite.

The configure command is:
CXX=mpiicpc configure --with-mpi --with-debug="-DMPICH_IGNORE_CXX_SEEK"

The configuration and compilation doesn't indicate any problems. 

After installation nest command start with no problem. But when we start python and do 'import nest' we get:

ImportError: .../lib/python2.7/site-packages/nest/pynestkernel.so: undefined symbol: __kmpc_end_critical

Furthermore when running make installcheck the process hangs at the 'test_dcgen_versus_I_e.sli' test.

**Comment by JanneM** [comment]
On K we get a very similar-looking error unless we build and link against a Python built with OpenMP(1) or manually add a couple of OMP-related system libraries. To test if that is the case, could you try building without OpenMP and see if the error persists?

(1) Python doesn't use it; it just ensures it gets the needed library linked.

**Comment by antolikjan** [comment]
Thanks for help.

After disabling OpenMP by running following configure command we avoid the import error and are able to perform 'import nest' from python:
CXX=mpiicpc /workgpfs/rech/nyi/commun/sources/nest-2.10.0/configure --with-mpi --disable-openmp --without-openmp --prefix=/workgpfs/rech/nyi/commun/venvs/nest-test-py2.7.9 --with-debug="-DMPICH_IGNORE_CXX_SEEK"

However, 'make installcheck' still hangs at at the 'test_dcgen_versus_I_e.sli' test!

**Comment by antolikjan** [comment]
@JanneM Since one of our issues seems to be related to the open-mp, similar to your experience on K, would you mind sharing the list of OMP-related libraries that makes it work for you?

Thanks in advance

**Comment by JanneM** [comment]
@antolikjan, the libraries in our case was "fj90i" and "fj90f" - but as those are Fujitsu-specific libraries that's unlikely to actually help you very much. 

The root issue is that you still need to build with OpenMP enabled when building the Python bindings. In our case - and perhaps also in yours - this means having to build against a version of the Python libraries that are already configured with OpenMP. I did do a workaround at first where I manually inserted the missing libraries into the link commands at the end of the build, but that is obviously not a sustainable solution.

**Comment by antolikjan** [comment]
We managed to solve the problem thanks to the assistance of the cluster admin team (Sylvie Therond). I am not sure to what extent this is down to the idiosyncrasies of the system, but I am posting below the configure options we had to use, in case it is of help to future users, or for developers to make the configuration system more robust:

configure CC=mpiicc CFLAGS="-openmp -mt_mpi -O3" CXX=mpiicpc CXXFLAGS="-openmp -mt_mpi -O3" LDFLAGS="-L/.../mkl/lib/intel64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -L/.../compiler/lib/intel64 -liomp5"
