### ISSUE TITLE
Inconsistent returned type in `nest.GetConnections().get()`

### ISSUE THREAD

**Issue by med-ayssar** [nest/nest-simulator#2318]
**Describe the bug**
Once the network is built by calling the connect function in nest, the user can inspect the connection by calling `nest.GetConnections().get()`. The return type of this function is a dictionary, so in case of calling `nest.GetConnections().get()` without previously making any connections, we should expect to get any empty dictionary, but instead an empty `tuple` is returned.

**Comment by hakonsbm** [comment]
@med-ayssar Which version of NEST are you using? Since NEST 3.0 `GetConnections()` should return a `SynapseCollection`, also if there are no connections.

**Comment by med-ayssar** [comment]
Sorry, I mean here after calling `nest.GetConnections().get()`, and yeah I am using NEST 3.0.
