### ISSUE TITLE
`nest.Disconnect` isn't working

### ISSUE THREAD

**Issue by med-ayssar** [nest/nest-simulator#2320]
**Describe the bug**
Trying to delete any existing connection in nest seems to always fail.
**To Reproduce**
```
# create network
pre = nest.Create("spike_generator") 
post = nest.Create("aeif_psc_alpha")
nest.Connect(pre, post)

# check the correctness of setting the network
connections = nest.GetConnections().get()
assert connections["source"] == pre.tolist()[0], " spike_generator wasn't set as source in this connection"
assert connections["target"] == post.tolist()[0], " aeif_psc_alpha wasn't set as target in this connection"

# delete the only connection/edge in the network
nest.Disconnect(pre, post, conn_spec="one_to_one")
```
Reaching the last line in the script, we get the following error: `NESTErrors.The connection does not exist: The connection does not exist in SLI function Disconnect_g_g_D_D: Deletion of connection is not possible.`

**Expected behavior**
A message indicating the successful deletion of edges

**Desktop/Environment (please complete the following information):**
- OS: Ubuntu-20.04
- NEST-Version: v3.1

**Additional context**
In the Documentation, `nest.Connect` has the argument `conn_spec` set to `all_to_all` as default, and in the `nest.Disconnect` function is set to `one_to_one`, however in the description in the `ǹest.Diconnect` function; the user should use the same  connectivity specs  as in the `connect` function. Doesn't this restriction force both functions to set the `conn_spec` to the same default value? (i.e. either both `all_to_all` or `one_to_one`)

**Comment by clinssen** [comment]
@sdiazpier: is it the case that ``Disconnect()`` is only intended for use with structural plasticity?

**Comment by heplesser** [comment]
Solved, this closing.
