### ISSUE TITLE
Change default port for NEST Server to avoid conflicts on MacOS

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2321]
On MacOS, port 5000 is used by the system for the AirTunes service. Since `localhost` is mapped to `127.0.0.1` (IPv4) and `::1` (IPv6) and AirTunes is running on both, starting NEST Server with the current default port 5000 leads to the situation that that port offers NEST if accessed via IPv4 and AirTunes via IPv6. In particular, `http://localhost:5000` will resolve to AirTunes, as IPv6 takes precedence. Any attempt to use NEST Server via `localhost` thus fail silently, while access via `http://127.0.0.1:5000` works.

To avoid this problem, I suggest to choose a different default port for NEST Server, e.g., `5001`.

**Comment by heplesser** [comment]
@babsey Have you had a chance to take a look at this issue?

**Comment by babsey** [comment]
No, I did not look at this issue. But I think it is not a big deal to change it. 
A new default port would be very uncommon one like 5813 (Fibonacci) or do you have a better number?

When the default port changed in next release, we need to inform associated projects which use NEST Server.
Here, I list projects using NEST Server:
- [NEST Docker](https://github.com/nest/nest-docker)
- [NEST Desktop](https://github.com/nest-desktop/nest-desktop)
- [Insite](https://github.com/VRGroupRWTH/insite)
- [NRP](https://bitbucket.org/hbpneurorobotics/nrp-core)

**Comment by heplesser** [comment]
I have no previous experience in assigning port numbers, but after a quick search its seems that there is an [official IANA table mapping ports to services](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) and a [protocol for assigning ports to services](https://www.rfc-editor.org/rfc/rfc6335.html). It seems to me that we should not use a port (below 41952) without IANA approval. This is especially important, I believe, when offering NEST server remotely. We might need to discuss with more knowledgable colleagues.

**Comment by babsey** [comment]
See https://stackoverflow.com/questions/2200199/how-do-you-decide-what-port-to-use

**Comment by babsey** [comment]
Ping to remind this issue.

**Comment by babsey** [comment]
My suggestions for NEST Server would be: 

- [ ] 17969 - amount of Ås inhabitans
- [ ] 52428 - postal code of Jülich
- [ ] 59863 - (S)erver of (N)ine (E)ight (S)ix (T)hree
- [ ] 59873 - (S)erver of (N)ine (E)ight (S)even (T)hree

**Comment by heplesser** [comment]
I suppose we are limited to 16 bits for port numbers, so 79104 will not work, even though it would be yet more fitting. Given those limitations, I'd suggest 52428.

@jougs @terhorstd @gtrensch Any comments or objections?

**Comment by jougs** [comment]
52425 is the postal code of Forschungszentrum Jülich for mail delivery and nicely symmetric.

**Comment by babsey** [comment]
@jougs: You are right! The postal code of FZJ is palindromic. I also like the number 52425.

**Comment by heplesser** [comment]
> @jougs: You are right! The postal code of FZJ is palindromic. I also like the number 52425.
> I am waiting for opinion of others, then I will work on changing the default port.

Go 52425, go!
