### ISSUE TITLE
clang-format 9.0.0 not available from PyPi for macOS

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2344]
Recently, `clang-format >= 9.0.0` was added to `environment.yml`.  This leads to failure on macOS, since PyPi provides clang-format wheels for macOS only from 10.0.1 onwards.

So we either need to take this out of the environment.yml file again or hike the clang-format version.

**Comment by heplesser** [comment]
@jougs clang-format is pip-installable for all newer versions on a wide range of systems (https://pypi.org/project/clang-format/13.0.1/#files), so do you see any reason not to jump to the most recent version per today, 13.0.1?

**Comment by terhorstd** [comment]
Formatting the code on MacOS is not release critical. The code is tested against clang-format-9 on the CI, which does not influence running NEST on MacOS. Only developers that are only on MacOS have to rely on CI, instead of testing locally.
Removing from milestone.

**Comment by heplesser** [comment]
@terhorstd The problem is that creating a conda environment from environment.yml (pip part) fails when clang-format 9 cannot be installed. This would also irritate advanced users.

--
Prof. Dr. Hans Ekkehard Plesser
Head, Data Science Section
Faculty of Science and Technology
Norwegian University of Life Sciences
PO Box 5003, 1432 Aas, Norway
Phone +47 6723 1560
Email ***@***.***
Home http://arken.nmbu.no/~plesser


________________________________

**Comment by jougs** [comment]
Removed in ed45e471f on the 3.3. release branch. For master, we're going to hike the requirement to the latest available version after the release.
