### ISSUE TITLE
Save and load SNN_model

### ISSUE THREAD

**Issue by yourssmile** [nest/nest-simulator#2369]
When I create a random SNN_model, and I want to save this model, I must save the neuron population and connection parameters to my files.
When I want to create the SNN_model, I created last time, I must load parameters from my files.
The work is rather tedious.

Is it possible to do a function of exporting model and loading model?

**Comment by heplesser** [comment]
You may want to take a look at this PyNEST example: https://github.com/nest/nest-simulator/blob/master/pynest/examples/store_restore_network.py

Generally, the best place to ask questions about how to use NEST is the NEST User Mailing List: https://www.nest-simulator.org/community/

@jessica-mitchell It seems that the store-restore example is not listed in our list of PyNEST examples at  https://nest-simulator.readthedocs.io/en/v3.3/examples/index.html. Could you check that?

**Comment by yourssmile** [comment]
Thank you for your answer, which is very helpful to me. I haven't been around NEST for long, so I haven't noticed the community forums， I am very sorry.

**Comment by jessica-mitchell** [comment]
@heplesser yes, it is indeed missing. I created a PR to include the missing examples
