### ISSUE TITLE
Prevent NEST from running under mpirun-control if not built with MPI

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2381]
If NEST is built without MPI support, invoking NEST with `mpirun -np N` will create N independent NEST instances. This is a behaviour the user most likely does not desire. When writing to files, there is considerable risk that these instances will write to the same output files simultaneously, creating a mess at best. 

Therefore, it would be good if an MPI-free NEST could report an error if it is run from `mpirun` or similar.

Unfortunately, [this discussion on StackOverflow](https://stackoverflow.com/questions/12678337/how-can-my-program-detect-whether-it-was-launch-via-mpirun) suggest this might not be solvable in general.

I still suggest we explore and close this issue if we conclude that there is no possibility to implement this feature.

**Comment by med-ayssar** [comment]
Won't be feasible to check the number of processes (`MPI_num`) and have a flag `HAS_MPI` that either set to true or false during the compilation.

During execution and on kernel startup, we can check if `MPI_num > 1 and not HAS_MPI => exit with error`, else continue execution, or is it a too naive solution?
