### ISSUE TITLE
Music continuous out ports

### ISSUE THREAD

**Issue by uahic** [nest/nest-simulator#239]
Since there is currently not possibility to get currents or other continuous values out of a parallel NEST simulation via music I would like to propose that I implement the proxy for NEST. 

Usecase:

In the HBP neurorobotics subproject we want to run NEST and the Gazebo simulator in a closed-loop whereas the actuators of the (simulated) robots are driven by currents (V_m property of the neurons) rather than spikes. Integrating spikes on the receiver side is no option (this would be like doing a part of the simulation on the receiver side). 

I've had a look into the music and corresponding NEST code, here are some suggestions but I would like to hear your opinions about that:

1) Implementing a new model 'music_cont_out_proxy': this would work very similar to the multimeter where the user can specify the desired target properties (recordables) of the target neurons. Technically I could either encapsulate a multimeter or inherit from that and set to_memory=true while all other options are=false (to_memory=true is important here because - at least in theory - the music port should read from that buffer directly, not sure if I can get a reliable access to  that though)

2) Extending the multimeter to have the option to record to 'to_music', this option would also be fine for me but since there is a 'music_cont_in_proxy' it would be somehow unintuitive to have the out_proxy implemented in the multimeter.

Please let me know your opinions and suggestions on that;

**Comment by heplesser** [comment]
@uahic I have never used Music in simulations myself, so please take my advice with a pinch of salt.

In principle, your approaches should work, but using the `multimeter` will lead to some overhead.

Biologically, my interpretation would be that muscle fibres receive spike input from motor neurons that then translate into transmitter concentrations/membrane potentials in the muscle fibres that lead to contraction.

For a robotic system, I would translate this (naively, I haven't worked with robots either) into output neurons that receive spiking input from a network of neurons, integrate that information to a membrane potential, and use that potential to control actuators.

Could you create `music_cont_out_proxy` that receives input spikes, integrates them and then communicates the resulting membrane potential via Music?

@jougs @mdjurfeldt Do you have any suggestions?

**Comment by uahic** [comment]
@heplesser Our first idea was to simply integrate the spikes on the receiver side (in terms of music: the other simulator) but that requires knowledge of which integrator has to be used (=reimplementing neuron internals) and we dropped that idea for this reason.

Your suggestion is what we want to do except that I like to query other motor neurons for their potentials instead of integrating it in the proxy (for the same reasons as above). After some more code analysis I simply  copied some code (update() ) from the multimeter but did not use the RecordingDevice. 

Right now I struggle with putting the data + time stamps (not sure if we need timestamps in this case at all since we just use the 'most recent' value on the receiver side but of course for NEST it should be somehow general) into a MUSIC::ArrayData map and sending them out at specific music ports.
