### ISSUE TITLE
Improve the flexibility of the "Izhikevich neuron model"

### ISSUE THREAD

**Issue by gergogomori** [nest/nest-simulator#2397]
**Target**
Currently the "Izhikevich neuron model" has several hard-coded parameters, the model is not as flexible as it could be. With slight modifications to the current code, more types of neurons could be properly modelled.

**Solution**
The following equations could be implemented as in Izhikevich (2007), chapter 8.1.4:
![equation](https://latex.codecogs.com/svg.image?C\dot{v}=k(v-v_r)(v-v_t)-u&plus;I)
![equation](https://latex.codecogs.com/svg.image?\dot{u}=a[b(v-v_r)-u])

if ![equation](https://latex.codecogs.com/svg.image?v\geq{v_{peak}}), then:
![equation](https://latex.codecogs.com/svg.image?v\leftarrow&space;c)
![equation](https://latex.codecogs.com/svg.image?u\leftarrow&space;u&plus;d)

Practically, compared to the current implementation, this would mean adding the following parameters: 
- "C" membrane capacitance, 
- "k" rheobase and input resistance related parameter,
- "![equation](https://latex.codecogs.com/svg.image?v_r)" resting membrane potential,
- "![equation](https://latex.codecogs.com/svg.image?v_t)" instantaneous threshold potential.

In addition, renaming the current "![equation](https://latex.codecogs.com/svg.image?v_{th})" to "![equation](https://latex.codecogs.com/svg.image?v_{peak})".

I really appreciate your support.

**References**
Izhikevich, E.M. (2007) Dynamical systems in neuroscience [electronic resource] : the geometry of excitability and bursting. Cambridge, Mass.: MIT Press.

**Comment by clinssen** [comment]
@gergogomori: thanks for your suggestion! Could it be an option for you to implement this model using NESTML?

See for example: https://github.com/nest/nestml/blob/master/models/neurons/izhikevich.nestml

**Comment by gergogomori** [comment]
It seems like this is already implemented:
https://nestml.readthedocs.io/en/latest/models_library/izhikevich_psc_alpha.html

Next time I will keep in mind to check the models in NestML as well.
