### ISSUE TITLE
Doc doesn't mention `t_ref` of `hh_psc_alpha`

### ISSUE THREAD

**Issue by babsey** [nest/nest-simulator#2405]
**Describe the flaw**
The user documentation doesn't mention `t_ref` of `hh_psc_alpha` (See the code https://github.com/nest/nest-simulator/blob/master/models/hh_psc_alpha.h#L91).

The question is, can the user set the value of `t_ref`?

**Suggest an improvement**
Add a line in doc for the parameter `t_ref` or remove the parameter from the model.
However the parameter `t_ref` seems to be used in the code (https://github.com/nest/nest-simulator/blob/master/models/hh_psc_alpha.cpp#L380).

**Comment by heplesser** [comment]
@babsey Could you create a PR?

**Comment by babsey** [comment]
Rather not, because I do not know which one is the preferred choice.

To remove the mentioned doc or to add the parameter instance?

**Comment by heplesser** [comment]
@babsey The user can set `t_ref`, so there should be documentation, the same as for other models with that parameter. Could you create a PR and also check the other `hh_*` models if they need documentation for this parameter as well?
