### ISSUE TITLE
When selecting one neuron from a spatial population (using an index), maintain the spatial position only of the selected neuron

### ISSUE THREAD

**Issue by marcobiasizzo** [nest/nest-simulator#2428]
**Is your feature request related to a problem? Please describe.**
I tried to implement a complex spatial connection. I wanted to define a custom logic connection for each of the input neurons. Iterating in a for loop, I selected the input neurons singularly and put them in the Connection function. Since they maintained the "spatial" metadata of the entire source population, the implementation failed.

**Describe the solution you'd like**
When selecting one neuron from a spatial population source_pop:
```
input = source_pop[5]
```
The returned value should contain only the spatial information of the 5th neuron. 

**Describe alternatives you've considered**
I solved my problem by computing the indexes of the target neurons an proceeding with a 'all_to_all' connection. This was possible in my situation, but in more complex scenario the feature could be necessary.

**Comment by hakonsbm** [comment]
@marcobiasizzo Is this the same problem as in #2414?

**Comment by marcobiasizzo** [comment]
@hakonsbm Yes, it is. Thank you very much.
