### ISSUE TITLE
Replace the Python imaging library `PIL` with `matplotlib` in the Sudoku example

### ISSUE THREAD

**Issue by gtrensch** [nest/nest-simulator#2441]
**Problem Description**

The Sudoku example introduced with #2384 makes use of the Python imaging library `PIL`. Since we want to keep Python dependencies as low as possible, we would like to replace `PLI` with a `matplotlib` solution. An example for drawing a Sudoku field using `matplotlib` can be found [here](https://github.com/ipower2/Sudoku-Solver).

**Comment by jessica-mitchell** [comment]
@krachbumm3nte Can you take a look at this when you get a chance?

**Comment by krachbumm3nte** [comment]
Yes, I can take care of it. As far as I can tell I'm not a Collaborator yet, so I can't self-assign. Could you do that for me @jessica-mitchell ?

**Comment by jessica-mitchell** [comment]
Closing issue as it is resolved with PR #2467
