### ISSUE TITLE
Installation issue (ImportError: libgsl.so.25: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by Dola47** [nest/nest-simulator#2446]
**Describe the bug**
I'm attempting to set up NEST in a Python virtual environment. I followed the instructions [here](https://nest-simulator.readthedocs.io/en/stable/installation/index.html) (Conda/MacOS) to install NEST on a conda environment.

Conda 4.13.0, ipython 8.4.0, nest-simulator 3.3, jupyterlab 3.4.4, and python 3.9.13 are currently installed. 

I just run python in the terminal after activating my conda environment, and then I type "import nest," and I get the following errors:

```
>>> import nest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/spiking/virtualenvs/LSM/lib/python3.9/site-packages/nest/__init__.py", line 53, in <module>
    from .ll_api import KernelAttribute  # noqa
  File "/home/spiking/virtualenvs/LSM/lib/python3.9/site-packages/nest/ll_api.py", line 51, in <module>
    from . import pynestkernel as kernel      # noqa
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. conda create --name LSM -c conda-forge nest-simulator jupyterlab seaborn
2. Go to the main folder where the environment is installed
3. LSM/bin/python -m venv LSM
4. source /home/spiking/virtualenvs/LSM/bin/activate.csh
5. python
6. import nest
7. Error!!

**Desktop/Environment (please complete the following information):**
 - Linux server

@heplesser Can you kindly have a look here?

**Comment by heplesser** [comment]
@Dola47 I have no experience combining Conda environments with virtualenvs (why stack one kind of virtual environment on top of another?). From your description above, it seems that you did not activate the conda environment after creating it (`conda activate LSM`). Then, can you try if `import nest` works after activating the Conda environment, without activating the virtualenv? Finally, I am not sure it is a good idea to use the same name for the Conda and the virtualenv environments.
