### ISSUE TITLE
Revise random generator interface in NEST

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#245]
The interface to the random number generators in NEST, both in the kernel and at the SLI level, is clumsy and should be updated for NEST 3. Specifically, we should
- provide an easy way to seed all kernel RNGs using a single master seed
- provide an easy way to change the type of RNG used in the kernel
- make changing and seeding kernel RNGs easy from the Python level
- consider changing the default RNG type from Knuth to MersenneTwister
- review the algorithms used for non-uniform random deviate generation
- review whether buffering random numbers really makes sense wrt performance
- simplify the way RNG creation is handled on the SLI level (eliminate RNG and RDV factory objects)

This is a follow-up to trac.146, trac.437 and trac.669.

**Comment by ikitayama** [comment]
@heplesser Is there a work-in-progress branch to give it a try?

**Comment by jougs** [comment]
@ikitayama: I only have a preliminary prototype at the moment and definitely won't be able to finish it before the end of May. You can watch out for the corresponding pull request here and just chime in if you experience any problems on K then.
