### ISSUE TITLE
mpirun error when executing according to nest-simulator-3.3/pynest/examples/Potjans_2014/README.rst

### ISSUE THREAD

**Issue by yingmuying** [nest/nest-simulator#2450]
nest-3.3: mpirun -n 2 python3 run_microcircuit.py, error
![nest3 3-mpi error](https://user-images.githubusercontent.com/16082632/185295124-da1509e6-d89b-4dd3-be12-af3b2ccde64a.jpg)
nest-3.2: mpirun -n 2 python3 run_microcircuit.py, OK
cmake with the same settings: cmake .. -Dwith-mpi=ON -Dwith-python=ON

**Desktop/Environment (please complete the following information):**
 - OS: Ubuntu-18.04
 - Browser: chrome
 - Shell: bash
 - Python-Version: Python 3.8
 - NEST-Version: nest-3.3
 - Installation: cmake with MPI

**Comment by heplesser** [comment]
1. Could you post the full cmake invocation and its full output?
2. Have you run `make installcheck`? Did that pass?

**Comment by yingmuying** [comment]
By comparing "nest-simulator-3.3/pynest/examples/Potjans_2014/network.py" and "nest-simulator-3.2/pynest/examples/Potjans_2014/network.py", I found that this problem may be caused by the difference of "__setup_nest()"

**Comment by heplesser** [comment]
So the Potjans network works for you with NEST 3.2, but not with NEST 3.3? Could you still answer my questions from before to allow us to analyse the problem better?

**Comment by heplesser** [comment]
@yingmuying I am closing since I haven't heard back from you. Feel free to re-open if you have news.
