### ISSUE TITLE
Make help and helpdesk more robust

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#246]
Currently, the NEST `help` and `helpdesk` commands can be rather difficult to use. In particular, they won't work if NEST has been compiled with MPI support, since both require spawning subprocesses.
- From Python, display of help information and opening of the helpdesk should bypass the NEST kernel completely, thus avoiding any problems with spawning
- It should not be necessary to specify the command to use for opening the helpdesk in `.nestrc`, the default browser should be used unless the user specifies a different browser explicitly.

This is a follow-up to trac.963.

**Comment by heplesser** [comment]
There is an additional issue here: The help system does not work properly with Jupyter notebooks. Calling `nest.help('iaf_psc_alpha')` will use `more` (or whichever pager is defined in `.nestrc` to display the help in the terminal in which `jupyter` was started and the notebook will hang until the user closes the pager. This is confusing at best and completely useless on web-based systems such as the HBP Collab.

I would suggest a solution along the following lines:
- From the SLI level
    - without MPI: current solution
    - with MPI: dump help to screen directly (opening hlp file in sli and print line-by-line
- From Python
    - print hlp file to screen directly at the Python level without going through SLI `help`
- From Jupyter notebook
    - As for Python, but display in subwindow, just as the help magic in Jupyter does
Concerning `nest.helpdesk()` from a Jupyter window, can we open a new tab with the NEST helpdesk without spawning a new browser process? After all, we are already in a browser. This would avoid the problem that we cannot spawn when NEST is compiled with MPI.

**Comment by heplesser** [comment]
@steffengraber Would the new help generator of #464 be useful to address this?

**Comment by steffengraber** [comment]
@heplesser Do you have an example how the help should look like for Jupyter?

**Comment by heplesser** [comment]
@steffengraber It can look just as when displayed in a terminal, the problem is where it is displayed. Currently, `nest.help()` calls SLI `help`, which calls `page`, which in turn invokes the pager specified by the user (`more` or `less`). The pager then outputs directly to `stdout`, but in the terminal in which the user invoked `jupyter notebook`, not in the notebook window in the browser.

Ideally, the help text should be displayed just as Python help is displayed in the notebook window, e.g., by creating a sub-window at the bottom of the window. In any case, we need a help function at the SLI level that returns the help text as string to Python instead of paging it. The same is true for `PrintNetwork`.

**Comment by steffengraber** [comment]
@heplesser jupyter runs in an other environment than python. This could be matched. I have created a (very) first example:
https://github.com/steffengraber/nest-simulator/blob/help_notebook/pynest/nest/lib/hl_api_info.py#L90

**Comment by heplesser** [comment]
I wanted to try it, but after a clean install of master, `install/share/nest` only contains
```
extras		help_generator	sli
```
How do I build the help files?

**Comment by steffengraber** [comment]
@heplesser The files must be in '.../share/doc/nest/help'.

**Comment by heplesser** [comment]
Sorry for mixing that up, but in `share/doc/nest` I just have
```
ConnPlotter	README.md	doc_header.txt	logos		mpi_selftests	quickref.html	selftests
LICENSE		bibliography	examples	manualtests	mpitests	regressiontests	topology
NEWS		conngen		index.html	model_details	musictests	run_examples.sh	unittests
```
Which part of the build or install process should generate the help?

**Comment by steffengraber** [comment]
Go to `extras/help_generator`

    python parse_help.py <source_dir> <build_dir> <install_dir>

source_dir: the root auf the nest-simulator path
build_dir: where you want to build the files
install_dir: path to ... share/doc/nest

**Comment by heplesser** [comment]
Works, displaying the help text as normal output. Just a few comments:
- For Py3 compatibility, it must be `print(hlptxt)`
- The `if hlptxt == ''` text crashes, because if we didn't find a help file, the variable is undefined when we get here.

**Comment by steffengraber** [comment]
Yes, using Python for printing the text in Python make sense. But using a pager on plain Python make sense, too. In NEST there is the mechanism choosing a pager with the `.nestrc`. I think, it is possible to use this.
Or is there a good pager for Python?

**Comment by heplesser** [comment]
Here two links from a quick google search:
- http://stackoverflow.com/questions/13227494/paging-output-from-print-statement
- https://pypi.python.org/pypi/pager

**Comment by steffengraber** [comment]
Yes,` Pager` is a terminal/console pager module. With `pydoc.pager` pydoc works like a pager program. There are some more intersting pydoc extensions.
In a first test both looks like `less` - what is good.
But, why to change a good and flexible (choice of: `less`, `more`, `emacs`, `xemacs`,...)
way to present the docs?
Only to see if - and how - it works I have integrated a few lines in `hl_api_info.py`  in my branch `help_notebook` to go through the `.nestrc `and start the desired pager inside the python session. It works.

**Comment by heplesser** [comment]
@steffengraber Besides the display issue in Jupyter notebooks, the other problem is NEST compiled with MPI. In that case, we cannot spawn a pager process and therefore NEST help is not available at all. If we used Python to do the paging, we would avoid this limitation.

**Comment by steffengraber** [comment]
I have tested it with `-Dwith-mpi:BOOL=ON`. It worked.

**Comment by heplesser** [comment]
@steffengraber If I understand the discussion above correctly, you had gotten most things to work towards the end of last year. Do you think we could pick this issue up again an move towards a pull request?

**Comment by steffengraber** [comment]
@heplesser Yes I can do this.

**Comment by steffengraber** [comment]
@heplesser @jougs Can we close it?

**Comment by ginkobab** [comment]
Hello, I think there is another issue with help:
calling `nest.helpdesk` will try to open `NEST_DOC_DIR/help/helpindex.html` while in my installation there is only `/NEST_DOC_DIR/help/index.html`.

Furthermore, selecting _quickreference_ and than for example _Simulate_, and then trying to go back on _Command Index_ will point on `NEST_DOC_DIR/help/`**`help`**`/helpindex.html`, and it will go on adding every time a _help_ to the path.

It could be that I messed up with something, if that is the case I apologize preventively.

**Comment by jougs** [comment]
@ginkobab: We are currently completely redoing the whole documentation infrastructure and the helpdesk will be replaced with something more reliable and more centered around the PyNEST API instead of expecting users to transfer information from SLI to PyNEST themselves.

That said, commenting on closed issues is usually rather ineffective, as we don't track their activity in a systematic manner and your concerns might go unheard.
