### ISSUE TITLE
Clarify difference between compartmental models and multi-compartment model

### ISSUE THREAD

**Issue by jessica-mitchell** [nest/nest-simulator#2461]
**Describe the flaw**

There are two types of models that use compartments in very different ways. It is difficult to distinguish based on names.

https://nest-simulator.readthedocs.io/en/latest/models/iaf_cond_alpha_mc.html and associated example: https://nest-simulator.readthedocs.io/en/latest/auto_examples/mc_neuron.html

And 

https://nest-simulator.readthedocs.io/en/latest/models/cm_default.html and associated examples: 
https://nest-simulator.readthedocs.io/en/latest/auto_examples/compartmental_model/receptors_and_current.html
https://nest-simulator.readthedocs.io/en/latest/auto_examples/compartmental_model/two_comps.html

**Suggest an improvement**

Is the multi_compartment model still useful in light of the new compartmental models from @WillemWybo 

Or can we rename and describe the older multi-compartment model to something more distinct? 

@JoshuaBoettcher

**Comment by terhorstd** [comment]
@heplesser, could you have a look at this? Do we still need the `mc` if we have the `cm`? Also with respect to NESTML the code and docs maybe need a look-over, right?
