### ISSUE TITLE
Document local_spike_counter resetting behavior

### ISSUE THREAD

**Issue by jessica-mitchell** [nest/nest-simulator#2465]
**Describe the flaw**

`local_spike_counter` will reset in repeated calls to simulate(), which is not documented
The assumed behavior is that it would reset after resetting the kernel.

**Suggest an improvement**
Add text to describe this behavior in PyNEST API.

@JoseJVS let me know if this isn't quite correct

**Comment by heplesser** [comment]
The behavior is documented with respect to `Simulate()`, even in two places:

- https://github.com/nest/nest-simulator/blob/ff0ac34eb3eccc0e519efb629a808841d5b60d90/pynest/nest/__init__.py#L362-L371
- https://github.com/nest/nest-simulator/blob/master/doc/htmldoc/nest_behavior/built-in_timers.rst

What is missing is information that the counter is also reset each time one calls `Run()`.
