### ISSUE TITLE
Make hpc_benchmark.sli example invariant under mpi/thread splits

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#247]
The `hpc_benchmark.sli` example is currently not invariant under different MPI/Thread-splits of a fixed number of virtual processes. This has historic reasons and is not a problem in itself, but I think it would make much sense to revise the example to be invariant.

The key issues are
- Recording from a fixed number of neurons per _mpi process_. The total number of recorded neurons should be fixed.
- Membrane potential randomization based on _mpi processes_. Randomization should be based on virtual processes.

[This Gist](https://gist.github.com/heplesser/e78bed61478c25f7047c) is a modified version of the benchmark as a first step (cf #237). In that version, membrane potential is not randomized.

**Comment by heplesser** [comment]
Since `hpc_benchmark.sli` has been used in many publications, we should keep it as constant as possible. But we should create a new version implementing the ideas above as well as being fully NEST3-style.

**Comment by terhorstd** [comment]
That sounds good! We are happy to see a PR for this!
