### ISSUE TITLE
Sender node ID not stored in SpikeEvent

### ISSUE THREAD

**Issue by zbarni** [nest/nest-simulator#2470]
In specific cases, it would be useful to have access to the ID of the presynaptic neuron when handling an incoming spike on the postsynaptic side. However, in the handle function, `e.get_sender_node_id()` fails on ` > 0 ` assertion because when the spike is emitted by a neuron (and not a device), this (and all other sender-related) information is not set / lost along the way. I realize that this may be the intended behavior and probably only affects very very few users, in which case the issue can be closed. 

If, on the other hand, this is something like a bug, a solution could be to set the ID explicitly in `event_delivery_manager.cpp:deliver_events_(...)`:

```
        if ( spike_data.get_tid() == tid )
        {
          const index syn_id = spike_data.get_syn_id();
          const index lcid = spike_data.get_lcid();

          // non-local sender -> receiver retrieves ID of sender Node from SourceTable based on tid, syn_id, lcid
          // only if needed, as this is computationally costly
          se.set_sender_node_id_info( tid, syn_id, lcid );

          se.set_sender_node_id(se.retrieve_sender_node_id_from_source_table());  // workaround / solution

          kernel().connection_manager.send( tid, syn_id, lcid, cm, se );
        }
```

**Comment by JanVogelsang** [comment]
Setting this information for every event would be quite costly (as this would result in another random jump in memory, therefore clearing at least parts of the cache), so from a performance perspective we would want to prevent this at all costs.  
In which case would you need the presynaptic id on the postsynaptic side?

**Comment by heplesser** [comment]
@zbarni Could you say more about the use cases for this? As Jan pointed out, a straightforward solution risks performance penalties and an efficient solution may be demanding to develop. If a neuron needs to map incoming spikes to senders, you can use the `rport`. I am quite certain that during connection creation the target neurons gets the gid of the sending neuron in the test event sent. If it then just returns the sender gid as rport, it will get this gid sent with every incoming spike as rport number. This will not work with `_hpc` synapses because they ignore rport to save space.

**Comment by zbarni** [comment]
Thanks for this info, I was not aware that the solution in the kernel would come at a significant performance cost. We needed the mapping of spikes to senders in a replication study (Klampfl and Maass, 2013), which involved a more complicated learning rule that required some of the synapse logic to be implemented in the postsynaptic neuron. I haven't thought about the `rport` solution (which looks really clean), so we ended up storing the source node id in the synapse (available during `check_connection`) and setting it for each spike event using `e.set_sender_node_id(...)`. This works, and makes the id available in the postsynaptic neuron via the said `e.get_sender_node_id()`. I just found it confusing that the function is there and callable but the information is somehow missing. 

Given that it's possible to use `rport` for such scenarios, I think the issue can be closed.

**Comment by JanVogelsang** [comment]
I have to admit, I don't like the current solution and if we find that there would be multiple use cases for this, we should consider implementing a more elegant solution. For now, you can probably just stick with your solution, unless performance/scalability is crucial for your use case.
