### ISSUE TITLE
Make GetStatus and SetStatus compatible

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#248]
`GetStatus` and `SetStatus` are complementary functions and it is reasonable to expect that the result of `GetStatus` can be used as input to `SetStatus`:

```
nest.SetStatus(nodes, nest.GetStatus(nodes))
nest.SetDefaults(model, nest.GetDefaults(model))
```

should work. Currently, it does not work (for almost all models). One reason for this is that `GetStatus` returns a number of read-only values; when these are sent to `SetStatus`, they are not read out and an `UnaccessedDictionaryItem` exception is raised.

The same should also apply to getting and setting status on connections.

**Note:** `SetStatus` does not provide a full reset!

```
old_status = nest.GetStatus(nodes)
... do something ...
nest.SetStatus(nodes, old_status)
```

will not fully reset the nodes, since `SetStatus` does not change the contents of buffers for incoming spikes and possibly other variables representing the history of the neuron.

This is one part of a follow-up of trac.577.

**Comment by heplesser** [comment]
Solving this would require knowing which entries in status dicts are read-only.  This can be solved once all models are generated using NESTML.

**Comment by jougs** [comment]
Closing here as this is now a NESTML issue. Please go there for updates and discussion.
