### ISSUE TITLE
Cannot set membrane voltage to random values for several models

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2480]
**Describe the bug**
A `TypeMismatch` error is raised when trying to set `V_m` with a distribution from `nest.random` on neurons of the following types:

- iaf_psc_alpha_canon
- iaf_psc_alpha_ps
- iaf_psc_delta_ps
- glif_psc
- hh_cond_beta_gap_traub
- glif_cond

Setting `V_m` to a fixed value works.

**To Reproduce**
```python
n = nest.Create('iaf_psc_alpha_ps')
n.V_m = nest.random.uniform(0.0, 1.0)
```

**Desktop/Environment (please complete the following information):**
 - NEST-Version: master@66255beb5 

**Additional context**

Here is a reproducer testing all models, trying both setting a fixed value and a random value. It may be useful as starting point for a regression test.

```python
import nest

nest.set_verbosity('M_FATAL')
for m in nest.node_models:
    n = nest.Create(m)
    try:
        n.get('V_m')
    except KeyError:
        continue

    try:
        n.V_m = 0.5
    except nest.NESTError:
        print(f'Constant Failed: {m}')

    try:
        n.V_m = nest.random.uniform(0., 1.)
    except nest.NESTError:
        print(f'Random Failed : {m}')
```

**Comment by clinssen** [comment]
This affects NESTML too. Traceback snippet:

```
NESTErrors.TypeMismatch: TypeMismatch in SLI function SetStatus_id: Expected datatype: doubletype
Provided datatype: parametertype
```
