### ISSUE TITLE
Add search bar to main page of documentation

### ISSUE THREAD

**Issue by jens-br** [nest/nest-simulator#2481]
**Describe the flaw**
The start page of the documentation misses a search bar in the new theme.

**Suggest an improvement**
There should be a search bar on the documentation start page - ideally on the upper part of the page, since one often simply visits the page to search for a specific keyword (-> easy and instant access without scrolling or clicking would be very helpful).

**Supporting materials**
![grafik](https://user-images.githubusercontent.com/53972736/192293604-9c4851a1-9fde-4311-83fd-e06c62a4741e.png)

**Desktop/Environment**
system-independent issue

**Additional context**
n/a

**Comment by jessica-mitchell** [comment]
@jens-br just fyi, I have started to look into this. Ideally I'm trying to get a search bar that matches the rest of the webpages. 
Also just for the future, please write a more descriptive title, it's easy to overlook issues when scrolling :) 
I dont know if you can add projects, but if possible, selecting the documentation project in the sidebar is also helpful. Or you can  mention me, if its documentation related. Thanks!

**Comment by jens-br** [comment]
@jessica-mitchell Thanks a lot! I am not sure how to represent the content more accurately in the title, but maybe you have some standards which I am not aware of?
Indeed, selecting the documentation project seems to be impossible, as the required buttons are not visible for a normal user:
![grafik](https://user-images.githubusercontent.com/53972736/203610555-3ee4d174-7ade-458c-a7c7-355aecd4efd3.png)
However, I try to mention you in such issues in the future. :) Thanks!
