### ISSUE TITLE
Error handling for synapse models and synapses

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#249]
Currently, `SetStatus` and `SetDefaults` when used on synapse models or connections does not throw exceptions when invalid parameter values are given.

For neurons, `SetStatus` and `SetDefaults` are handled in a way that ensures that no parameters are changed unless it is certain that all parameters values a legal. This is done by first making all changes on a temporary copy of the parameter object and then copying this object back.

Solving this ticket will require a discussion of expected behavior in case of failure. The easiest solution would be to simply declare the network to be in an undefined state after `SetStatus` has failed on a connection and suggest that the user starts all over again. This would be a problem in interactive work, but should not be problematic for scripted simulations.

This is a partial follow-up of trac.577.

**Comment by clinssen** [comment]
Synapse (Connection) classes are organised differently from the neuron (Node) classes: the latter typically have a private Parameters_ (and State_) struct, that can be quickly copied and restored to the original if an exception was thrown while updating the values. Synapse classes currently lack this organisation, but when synapses are generated using NESTML, they will follow the neuron class layout.

Hence, this issue will be automatically solved for any synapses generated using NESTML. However, the solution may not be backported to existing synapse models, which are not NESTML-generated—the NESTML versions may simply ultimately replace them.

If you disagree, please respond! What will be the criteria for closing this issue—only when full NESTML integration has been achieved?

**Comment by terhorstd** [comment]
@clinssen , I agree, and currently do not see a point why this should be kept open. If @heplesser agrees, I'd close it.

**Comment by heplesser** [comment]
Would it not make more sense to keep it open until the NESTML-generated synapses are here integrated? Maybe add a "Waits for NESTML" tag?

**Comment by jougs** [comment]
I suggest to create a corresponding issue on the NESTML issue tracker with all the relevant information and close this one wontfix with a link to the new issue.

**Comment by heplesser** [comment]
Sounds good to me. @clinssen Could you create the issue in the NESTML tracker, reference it from here and then close this as wontfix?
