### ISSUE TITLE
Review parameter names relating to synapse models

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#250]
At present, different parts of NEST use different terms to refer to synapse models:
- In the `syn_spec` dictionary passed to `Connect`, the synapse model is passed as `model`
- `GetConnections` uses `synapse_model` 
- `DataConnect` uses `synapsemodel` according to documentation
- `GetDefaults` returns an entry `synapsemodel`
  We should try to find a way to systematize this. Unfortunately, this may break a lot of existing code.

This is a follow-up to trac.876.

**Comment by hakonsbm** [comment]
Fixed with 41c4071cd5ed8746a0a1175aaef6332b9197dddc in https://github.com/compneuronmbu/nest-simulator/tree/nest-3
