### ISSUE TITLE
"Simulation time" dependent parameters

### ISSUE THREAD

**Issue by gergogomori** [nest/nest-simulator#2509]
Dear NEST Developer Team,

I am wondering whether it is possible to run a simulation in which some of the parameters of individual neurons (e. g. the synaptic strength) are a function of the simulation time.

I am currently trying to run a simulation with a population connected via basic "static_synapse", and a function that could tell the synaptic weights of the neurons based on the simulation time. (The computation of which is done with a different simulator.) The values for the weights for the whole length of the simulation are available in advance.

What would be a suitable way to run such a simulation?

I assume one solution might be to use RunManager(), Run() and SetStatus(). My intention is to change only the "weight" parameter. Would this behave properly? 

Is there any additional, perhaps more convenient way to execute such a simulation?

I really appreciate your support.

Have a nice day,
Gergő

**Comment by clinssen** [comment]
Hi Gergő, thanks for writing in!

In general there would be two approaches to this:
- If your weights are only changing infrequently, you could simulate in chunks of time, e.g. simulating for 100 ms, changing the weights, then simulating another 100 ms, etc. This could be done from within your (Python) simulation script, where you are calling ``nest.Simulate()``.
- If your weights are changing more frequently, you could possibly store the values of the weight across time as a vector inside a NESTML model. For an example neuron model that uses this mechanism, please see https://github.com/nest/nestml/blob/master/tests/nest_tests/resources/iaf_cond_exp_Istep.nestml and https://github.com/nest/nestml/blob/master/tests/nest_tests/test_iaf_exp_istep.py. This could probably be adapted to work on the synapse as well.

Please let us know which of these approaches might work best for you, and we'd be happy to assist further.
