### ISSUE TITLE
There is no way to create a Security Advisory

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#2511]
**Describe the bug**
I've found XSS vulnerabilities in the NEST server, resulting in arbitrary code execution on the target machine, but there's no way to create any Security Advisories to report this problem. The UI looks like this to me:

![image](https://user-images.githubusercontent.com/28923979/197516383-6ba833c3-e53a-4514-a395-76451c367b95.png)

The security policy says that NEST runs in well protected environments (user desktops?), but this is completely irrelevant because even/especially these well-protected environments have usually unrestricted internet access and can send information back to the attacker's servers with ease, I would remove the note as it promotes a dismissive attitude towards security and offers no security information.

**Comment by lekshmideepu** [comment]
![Screenshot 2024-03-20 at 13 00 15](https://github.com/nest/nest-simulator/assets/7138338/32d92dda-ab61-4d37-8b36-1bd8492a2744)

You should be able to create one by clicking on the "Report a vulnerability" option

**Comment by lekshmideepu** [comment]
![Screenshot 2024-03-20 at 12 59 57](https://github.com/nest/nest-simulator/assets/7138338/ca90c234-d695-4bcc-ae9f-27e57ba259b0)

Then you should get the above screen where you can fill in the details.

**Comment by Helveg** [comment]
Yes, now the `Report a vulnerability` button is visible :)
