### ISSUE TITLE
Repeating creating nodes of same structure causes growing memory consumption and creation time

### ISSUE THREAD

**Issue by ChenK19** [nest/nest-simulator#2512]
Hello, I hope to create the same nest structure and adjust some connection weight in the structure for simulation, i accomplish that in a loop, for every iteration, create the nodes and connect them with newly weight, which  shows **growing memory consumption and creation time for nodes**. 

maybe i need some help to solve the problem.

The problem is similar to  the pynest example in 
[https://nest-simulator.readthedocs.io/en/v3.3/auto_examples/brunel_alpha_evolution_strategies.html](url)

replace the 'N' with 2000 in simulation_parameters and 'max_generation' to 100 in optimization_parameters at the start of main function

`    simulation_parameters = {
        'seed': 123,
        'dt': 0.1,            # (ms) simulation resolution
        'sim_time': 1000.,    # (ms) simulation duration
        'warmup_time': 300.,  # (ms) duration ignored during analysis
        'delay': 1.5,         # (ms) synaptic delay
        'g': None,            # relative ratio of excitation and inhibition
        'eta': None,          # relative strength of external drive
        'epsilon': 0.1,       # average connectivity of network
        'N': 400,             # number of neurons in network
        'gamma': 0.8,         # relative size of excitatory and
                              # inhibitory population
        'N_rec': 40,          # number of neurons to record activity from
    }

    optimization_parameters = {
        'verbosity': 1,             # print progress over generations
        'max_generations': 20,      # maximal number of generations
        'target_rate': 1.89,        # (spikes/s) target rate
        'target_corr': 0.0,         # target correlation
        'target_cv': 1.,            # target coefficient of variation
        'mu': [1., 3.],             # initial mean for search distribution
                                    # (mu(g), mu(eta))
        'sigma': [0.15, 0.05],      # initial sigma for search
                                    # distribution (sigma(g), sigma(eta))

        # hyperparameters of the fitness function; these are used to
        # compensate for the different typical scales of the
        # individual measures, rate ~ O(1), cv ~ (0.1), corr ~ O(0.01)
        'fitness_weight_rate': 1.,    # relative weight of rate deviation
        'fitness_weight_cv': 10.,     # relative weight of cv deviation
        'fitness_weight_corr': 100.,  # relative weight of corr deviation
    }`

my environment is:
 - OS: Ubuntu 22.04
 - Python-Version: 3.10.5
 - NEST-Version: 3.3
 - Installation: conda without MPI

**Comment by heplesser** [comment]
Closing as fix is merged.
