### ISSUE TITLE
Missing spatial user documentation

### ISSUE THREAD

**Issue by nicolossus** [nest/nest-simulator#2513]
In both the [3.3 release](https://nest-simulator.readthedocs.io/en/v3.3/ref_material/pynest_apis.html#module-nest.spatial_distributions.hl_api_spatial_distributions) and [latest](https://nest-simulator.readthedocs.io/en/latest/ref_material/pynest_apis.html#module-nest.spatial_distributions.hl_api_spatial_distributions) (as of writing) documentation on `Functions related to spatial distributions`, the documentation from [pynest/nest/spatial/hl_api_spatial.py](https://github.com/nest/nest-simulator/blob/master/pynest/nest/spatial/hl_api_spatial.py) is missing. The module is listed in [pynest_apis.rst](https://github.com/nest/nest-simulator/blob/master/doc/htmldoc/ref_material/pynest_apis.rst#functions-related-to-spatial-distributions), so the origin of the bug is not immediately obvious to me.

Note that the missing documentation also means that the references to `spatial.grid` and `spatial.free` in [`Create`](https://nest-simulator.readthedocs.io/en/latest/ref_material/pynest_apis.html#nest.lib.hl_api_nodes.Create) do not lead anywhere.

**Comment by jessica-mitchell** [comment]
@nicolossus Just an update that I'm looking into this issue, but the solution doesn't seem to be straightforward. I thought since this spatial/hl_api_spatial.py contains classes, we would need to use `autoclass` rather than `automodule` but this doesnt work. 
I'll continue to look into it.

**Comment by heplesser** [comment]
Could this be related to the fact that we have two different `hl_api_spatial.py` files, once in `lib` and once in `spatial`. It should work, but .... I also noticed that at least sometimes `automodule` only works if the module file itself has a module docstring. But that does not seem to cause problems for `hl_api_spatial_distributions.py`, e.g..

Also note that spatial documentation is collected under two different headers in the rst-file. Maybe sensible to combine, or at least have them next to each other?
