### ISSUE TITLE
Preserve newlines in command index documentation

### ISSUE THREAD

**Issue by sanjayankur31** [nest/nest-simulator#254]
I'm not entirely sure how the nest command index is generated, but it seems newlines are stripped out? The description seems to be one long line - this makes it quite difficult to read, especially when you're looking for various parameters. Take this page for example: http://www.nest-simulator.org/cc/spike_generator/ The example here isn't formatted either. Could the formatting and things be preserved - it would really improve the readability of the documents. 

If someone could point me to how the docs are generated, I can look into it and hopefully open a pull request. Cheers!

**Comment by heplesser** [comment]
Seems fixed by #464.
