### ISSUE TITLE
Replace typedef'ed types with C++ PODs

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2541]
This issue is a follow-up to #2215.

After a thorough discussion during the Hackathon we came to the following conclusions:

1. Typedefs (except `weight` and partially `delay`) are only used to index into containers. Therefore, `size_t` is the suitable POD where currently `typedef`s  `index`, `thread`, `port`, `rport`, ... are used.
2. Typedefs do not provide any type safety in C++.
3. Where we use signed types through `typedef`s today (`int`,  `long`), we only use value -1 from the negative range, wasting value range. Use of `size_t` would avoid this.
4. [Named type solutions](https://embeddedartistry.com/blog/2018/04/23/namedtype-the-easy-way-to-use-strong-types-in-c/) seem too complicated, as do implementing our own classes for, e.g., `Thread`, `Delay`, ....
5. We therefore concluded that we will explore replacing all `typedef`ed types with PODs, using unsigned PODs throughout.
6. For marking invalid values, three approaches can be used, as suitable in the situation
    1. Return a `std::pair<>` combining the value and a boolean flag indicating validity.
    2. Use `std::numeric_limits<POD>::max()` as the invalid value.
    3. Raise exceptions instead of returning invalid values. 
7. Certain quantities have implicitly limited value ranges because they need to be transmitted in bitfields of limited size in MPI communication (https://github.com/nest/nest-simulator/blob/e49be2ae64b92b6b6d7c451b2ed8027c0975e480/nestkernel/nest_types.h#L81-L105). Where these values are set (e.g., when the number of threads is changed or new synapse models are created), we need to check if new values are in the permissible range.

**Comment by JanVogelsang** [comment]
As an addition: `port` and `rport` are currently of type `long`, although I feel `size_t` would be more fitting. However, I would even suggest to not use `size_t`, but use `int` instead, just to make sure we never reserve 8 Bytes per port on any architecture and `rport` is used within the `Connection` class, thus contributing a lot to the overall memory consumption.
