### ISSUE TITLE
Remove SLI documentation generation

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#2546]
#2544 introduces modular documentation building, and keeps the legacy SLI doc code in a [`BUILD_SLI_DOC` block](https://github.com/Helveg/nest-simulator/blob/fb43757b3d5a71aabbdfb187bc119bd64181d77c/doc/CMakeLists.txt#L27-L60). This block should be removed once the SLI interface has been removed.

**Comment by jougs** [comment]
Already removed in 67fbce1ed00de6abb10c49c268026ee2a0ee74cd on branch [jougs:new-pynest](https://github.com/jougs/nest-simulator/tree/new-pynest). Should we keep this open, or just close?

**Comment by Helveg** [comment]
#2544 touched that, if you merge that in I'd say we can close this.

**Comment by heplesser** [comment]
You could create a draft PR from jougs:new-pynest and then link this issue from there.

**Comment by jougs** [comment]
> You could create a draft PR from jougs:new-pynest and then link this issue from there.

Not sure. [jougs:new-pynest](https://github.com/jougs/nest-simulator/tree/new-pynest) is a massive code breaker that has to be integrated with other branches before being merged ti the main repository. Thinking about it, we might as well call that branch `main`, work towards NEST 4.0 from there, and delete `master` once we are confident that everything is good...

Given that the PR that @Helveg [mentioned](https://github.com/nest/nest-simulator/issues/2546#issuecomment-1334056533) is merged now and the journey is clear, I will close this issue as completed.
