### ISSUE TITLE
User doc workflow doc lacks `pandoc` as dependency

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#2547]
**Describe the flaw**
The user docs have a dependency on the `pandoc` executable, but this isn't mentioned here: https://nest-simulator.readthedocs.io/en/v3.3/documentation_workflow/user_documentation_workflow.html#setting-up-your-environment

**Comment by jessica-mitchell** [comment]
I think this is actually dealt with in one of the currently open PRs, or at least partially is. I can take a look

**Comment by Helveg** [comment]
My PR #2544 makes users error out in CMake if they toggle on the doc build and don't have it, but still we ought to specify where to get it in the doc workflow

**Comment by jessica-mitchell** [comment]
@helveg Closing this issue as #2544 adds instruction to install pandoc in the userdoc workflow
