### ISSUE TITLE
`NEST` failed to import submodule `spatial`

### ISSUE THREAD

**Issue by babsey** [nest/nest-simulator#2561]
**Describe the bug**
Using the latest master commit (`master@e6c35a12b`), `NEST` failed to import submodule `spatial`.

Maybe the source of the bug lies in the decorator:
```
~/opt/nest-master/lib/python3.8/site-packages/nest/spatial/__init__.py in <module>
     25 
     26 
---> 27 @_functools.cache
     28 def __getattr__(name):
     29     if name == "distance":

AttributeError: module 'functools' has no attribute 'cache'
```

**To Reproduce**
1. Compile and install nest `master@e6c35a12b`.
2. `from nest import spatial`

**Expected behavior**
It should import spatial submodule.

**Comment by babsey** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1626

**Comment by Helveg** [comment]
Ah, my bad, I recommend @med-ayssar to use that, but it was added in Python 3.9, we can suppor Python 3.8 by monkey patching the `functools` module:

```
try:
  _functools.cache
except AttributeError:
  _functools.cache = _functools.lru_cache
```

**Comment by babsey** [comment]
Friendly ping. What is the current status?
