### ISSUE TITLE
Improve model directory listing in Read the Docs

### ISSUE THREAD

**Issue by jessica-mitchell** [nest/nest-simulator#2563]
**Describe the flaw**
The current model directory is a mix of category-based lists with a ton of duplication of models, since the models fit into several categories. (Each model is tagged with several key terms that are used to generate the different lists). 

**Suggest an improvement**
Provide two options to view directory
1. An A-Z list of all models
2. A list of categories (neuron, synsapses, integrate-and-fire, stimulators etc) when clicked on, it will provide a list of relevant models for that category

@jhnnsnk If you have any suggestions please comment :)

**Comment by babsey** [comment]
I would suggest to add search field and several filter tags (e.g. neuron, simulator, recorder, synapse) in the top of the alphabetical list.

By changing of search query or any filter tag it would be render list dynamically and fast.
