### ISSUE TITLE
Autogenerate PyNEST reference documentation

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#257]
Currently the Python bindings for NEST are not really well documented. There is the [pynest introduction](http://www.nest-simulator.org/introduction-to-pynest/) and many example, but I personally often find myself lacking an API reference. Further, changes in the API are not automatically reflected in the pynest introduction.

Since most of the API is documented, an easy solution would be to autogenerate a reference documentation, to which we could also link from the introduction for further reference on function calls etc.

Setting this up would involve some of the below:
- choose a build system (sphinx-doc.org is a common choice)
- rewrite/format the python docstrings to adhere to a standard that the build system can format ([google style](http://google.github.io/styleguide/pyguide.html#Comments) for example)
- add hooks to the repository that include automatic rebuilding and deployment of the documentation 

I've tried around a little with Nest 2.10, and sphinx, the results of which you can find here: http://flinz.github.io/nest-simulator-apidoc

Is this something that is generally desired? I could look into reformatting the docstrings, which would probably also go hand in hand with https://github.com/nest/nest-simulator/issues/188

**Comment by steffengraber** [comment]
Hi @flinz 
I am currently working on a new build system for the documentation. For the python part the decision is to use docstrings according to the NumPy/SciPy documentation standard.
From my side reformatting the docstrings would be helpful.

**Comment by flinz** [comment]
@steffengraber nice - do you have a little more details on what you're doing?

Regarding the docstring reformatting: I will do that.

------------

**Here is a little sidenote on autogeneration of the python documentation, maybe its helpful if you're working on this**

PyNEST widely uses decorators and thus the autogenerated docs showed all decorated functions with the universal signature ``function(*args, **kwargs)``. 

Since this is not really informative about possible arguments, I introduced a little workaround for the decorators that disables them if a documentation build imports nest: [code is available here](https://github.com/flinz/nest-simulator/commit/56ad76686e6c7888cf81a5c891df4e7887bc4f6d). This was used to build the docs at http://flinz.github.io/nest-simulator-apidoc.

A nice side-effect is that you can [inject deprecation warnings into the docstrings](https://github.com/flinz/nest-simulator/commit/56ad76686e6c7888cf81a5c891df4e7887bc4f6d#diff-b99cd7631a894577890292d8f67cf420R89) for deprecation decorated classes (see [here for example](http://flinz.github.io/nest-simulator-apidoc/modules/nest.lib.html#nest.lib.hl_api_connections.ConvergentConnect)).

**Comment by apeyser** [comment]
@flinz: Is the problem that the decorators don't use @wrap inside to raise the function information up to the final function?

**Comment by flinz** [comment]
@apeyser decorators already use this actually, as: ``@functools.wraps(func)``(e.g. https://github.com/nest/nest-simulator/blob/master/pynest/nest/lib/hl_api_helper.py#L135)

I did a little research on this, and it seems to be a common problem. Some workarounds involve [hacking the ``wraps`` decorator](http://stackoverflow.com/questions/28366818/preserve-default-arguments-of-wrapped-decorated-python-function-in-sphinx-docume). 

I chose to resort to the documentation flag.

**Comment by apeyser** [comment]
@flinz: So it's a bug in sphinx: https://github.com/sphinx-doc/sphinx/issues/1711 which apparently no one has become interested in fixing. Sphinx should look at __wrapped__ for wrapped functions to get the original signature, but it doesn't, and @wraps doesn't lift parameters (it wouldn't make sense, since you can use them for partials and other operations).

**Comment by flinz** [comment]
@apeyser interesting, thanks! 

But, before we delve deeper, it would be useful to know which build system @steffengraber has in mind. If it is sphinx indeed, this would be worth a closer look. This would also help me write the docstrings (e.g., sphinx offers some extra syntax).

**Comment by flinz** [comment]
Working on both pep8 compliance and doc reformatting on https://github.com/flinz/nest-simulator/tree/pynest-docs.

**Comment by flinz** [comment]
@steffengraber any updates on the documentation build system?

**Comment by steffengraber** [comment]
@flinz as a first step, there is now a new pull request #464.
It would be nice if you could have a look on it. This is then also part of the build system for the user documentation.

**Comment by steffengraber** [comment]
Just a short update: I am currently working on a complete setup for the user documentation on readthedocs. Part of this work is a complete build process for the website.
The PyNEST reference will then be part of it.

**Comment by jougs** [comment]
@steffengraber: can we close this? I think the main points (pep8 conformity and documentation reformatting) have been solved by #263.

**Comment by steffengraber** [comment]
@jougs Yes, close it.

**Comment by jougs** [comment]
Thanks!
