### ISSUE TITLE
Inconsistent OpenMP runtime environments results in bad performance

### ISSUE THREAD

**Issue by ackurth** [nest/nest-simulator#2573]
**Describe the flaw**
Joint effort with @JoseJVS, @gtrensch @diesmann
When trying to pin threads via OpenMP variables using NEST, one might run into inconsistencies in the OpenMP runtime environment. This might results in the  pinning not working as expected
This problem might frequently occur when using a Numpy which is compiled with MKL (Math Kernel Library), since this library create it's own OpenMP runtime environment.

One can solve this problem by disabling the runtime environment of the MKL by exporting
```
MKL_THREADING_LAYER=GNU
```

**Suggest an improvement**
Explain the problem and add the solution to the documentation.

**Additional context**
Especially relevant for HPC users

**Comment by jessica-mitchell** [comment]
This issue was handled in  #2401
