### ISSUE TITLE
Nest initialization in Jupyter Notebook not working

### ISSUE THREAD

**Issue by tinotil** [nest/nest-simulator#2577]
**Describe the bug**
Nest initialization fails with following error message:

```
Jan 06 11:45:30 sli-init [Fatal]: 
    While executing module initializer: 
    {(/home/lib/python3.11/site-packages/nest/pynest-init.sli) 
    run}

Jan 06 11:45:30 run [Error]: ArgumentType
    The type of one or more parameters did not match the argument(s) of this 
    function.
    
    Candidates for +run+ are:
    stringtype     calls <procedurety

File ~/lib/python3.11/site-packages/nest/lib/hl_api_simulation.py:288, in GetKernelStatus(keys)
    286     return status_root
    287 elif is_literal(keys):
--> 288     return status_root[keys]
    289 elif is_iterable(keys):
    290     return tuple(status_root[k] for k in keys)

TypeError: string indices must be integers, not 'str'
```

**To Reproduce**
1. Just initializing Nest with "import nest"

**Desktop/Environment:**
 - Python-Version: 3.11
 - NEST-Version: 3.3
 - Installation: conda packet

**Comment by terhorstd** [comment]
Hi @tinotil , thanks for bringing this up!
Could you try with a Python 3.10 or Python 3.9? – Since Python 3.11 was released after NEST 3.3 the compatibility was obviously not tested and changes in the Python world are sometimes quite "effectful".

**Comment by med-ayssar** [comment]
Hey @tinotil, could you please also check which **Cython** version do you have in your python environment.

**Comment by atiye-nejad** [comment]
Hi I have Microsoft windows. I used nest image in ova format in oracle virtual machine to run Nest. Do I have to install anything else like Python to be able to work with Nest? If so, I have to install it in Windows or python image in VM? 
I appreciate you to help me.

**Comment by med-ayssar** [comment]
Hey @atiye-nejad, The NEST image should have all required dependencies installed, including NEST itself.

Did you face any specific problems after starting the NEST image?

**Comment by atiye-nejad** [comment]
> 
I don't know whether I have Nest or not?I mean if I installed it correctly or not. I wrote a code like it:
neuron = nest.Create('iaf_psc_exp') exactly this . but give me syntax error.

**Comment by med-ayssar** [comment]
Could you please give me more details:

1. Where did you call this instruction?
2. what was exactly the syntax error?

**Comment by atiye-nejad** [comment]
> Could you please give me more details:
> 
> 1. Where did you call this instruction?
> 2. what was exactly the syntax error?
From Nest Site:    https://nest-simulator.readthedocs.io/en/v3.3/getting_started.html
bash:syntax error near unexpected token ('

**Comment by med-ayssar** [comment]
I am afraid that I might need more context here. Could you maybe post a screenshot here?

**Comment by atiye-nejad** [comment]
> > 
> 
> I don't know whether I have Nest or not?I mean if I installed it correctly or not. I wrote a code like it: neuron = nest.Create('iaf_psc_exp') exactly this . but give me syntax error.
![3](https://user-images.githubusercontent.com/124899759/221225473-8f153a78-636d-480f-87c7-62dfa0dbd262.jpg)

**Comment by med-ayssar** [comment]
I am assuming that you are calling this instruction directly after opening the terminal.

You should firstly type `python` and press enter, and then you can import `nest`

**Comment by atiye-nejad** [comment]
> The NEST image should have all required dependencies installed

yes, It works :) thank you so much. can I write all my codes here? Do I have Nest correctly now?

**Comment by atiye-nejad** [comment]
> Yeah, you should have NEST available there after calling `python`. Try `import nest` and you should get a textual output.

Thanks a lot.the first mentioned code is working now. thanks. Do copy and paste work in Nest?

**Comment by clinssen** [comment]
Closing as the issue is solved and confirmed!
