### ISSUE TITLE
PyNEST: Parameters for GetStructuralPlasticityStatus 

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#260]
This is probably for @sdiazpier:

The function [`GetStructuralPlasticityStatus`](https://github.com/nest/nest-simulator/blob/master/pynest/nest/lib/hl_api_simulation.py#L134) currently takes one neccessary parameter `params`. 

I can however neither pass a string, a list of strings, only an empty dictionary works for me so far. 

Perhaps this should be a optional parameter?
E.g., `GetKernelStatus` takes both strs and list of strs, and all of them are optional.

**Comment by sdiazpier** [comment]
Hi @flinz 
Yes you are right, for the moment a dictionary is expected in this function which is not used and it is not optional. Thank you noticing this. I will reformulate the call format of the function.

**Comment by jougs** [comment]
@sdiazpier: can you please update us on the status? If this was fixed by #775, I'd like to close this issue.

**Comment by heplesser** [comment]
Solved by #775, thus closing.
