### ISSUE TITLE
`nest.Connect()` error using array indexing with numpy >=1.20*

### ISSUE THREAD

**Issue by Hugo-Mu** [nest/nest-simulator#2624]
**Describe the bug**
Connecting populations together using array indexing (as described in [https://nest-simulator.readthedocs.io/en/v3.3/guides/connection_management.html?highlight=post%20%3D%20target.cells%5Bnonzero_indices%5D#connecting-sparse-matrices-with-array-indexing](url)) prompts an error message because of a deprecation in numpy since v1.20 (see [https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations](url))
The error arises when trying to select a subset of any population using a list (or array) of indices (i.e. `cells[1,3,5,12]`, or `cells[np.array([1,3,5,12])]`
No error arises when using i.e. `cells[1,2,3,4,5]` or `cells[:5]`

**To Reproduce**
Executing the code from the link above (Connecting sparse matrices with array indexing) produces the error.
```
W = np.array([[0.5,  0.0, 1.5],
              [1.3,  0.2, 0.0],
              [0.0, 1.25, 1.3]])
A = nest.Create('iaf_psc_alpha', 3)
B = nest.Create('iaf_psc_alpha', 3)
for i, pre in enumerate(A):
    weights = W[:, i]
    nonzero_indices = numpy.where(weights != 0)[0]
    weights = weights[nonzero_indices]
    post = B[nonzero_indices]
    pre_array = numpy.ones(len(nonzero_indices), dtype=numpy.int64) * pre.get('global_id')
    nest.Connect(pre_array, post, conn_spec='one_to_one', syn_spec={'weight': weights})
```
(as a side note, I also suggest modifying the above code in the documentation for _very_ sparses matrices to include the cases where some postsynaptic neurons have _no_ presynaptic partners (i.e. by nesting another if statement such as `if len(nonzero_indices) != 0:`), otherwise the code provided in the odcumentation will lead to an error.)

**Expected behavior**
Being able to select a slice of a node collection without necessarily using successive indices
All the pre- and post-synaptic partners get connected correctly.

**Screenshots**
![Screenshot from 2023-03-01 13-20-43](https://user-images.githubusercontent.com/77761031/222044097-693158c1-0013-4186-ae8e-df2540161b49.png)

**Desktop/Environment (please complete the following information):**
 - OS: Ubuntu 22.04 (and 20.04)
 - Python-Version: 3.8 and 3.11 both have that issue
 - NEST-Version: 3.3
 - Installation: conda and apt installs of nest both lead to this issue

**Comment by nicolossus** [comment]
@Hugo-Mu Thanks for reporting this issue. We are aware of the compatibility issue between PyNEST and newer versions of NumPy, and it should already have been fixed by https://github.com/nest/nest-simulator/pull/2571. The fix is included in the recently released NEST 3.4. For NEST 3.3, one needs to use NumPy < 1.24. I have tested your bug reproducer with both {NEST 3.4, NumPy 1.24} and {NEST 3.3, NumPy < 1.24}, and both setups works as expected.

**Comment by terhorstd** [comment]
@nicolossus, just to confirm: "numpy < 1.24" not "numpy <= 1.24", right?

**Comment by nicolossus** [comment]
@terhorstd Yes, NEST 3.3 does **not** work with numpy = 1.24, so {NEST 3.3, numpy < 1.24}

**Comment by terhorstd** [comment]
Thanks, for the clarification!
