### ISSUE TITLE
Link from 3.3 to 3.4 documentation fails with 404

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2645]
The page 

https://nest-simulator.readthedocs.io/en/v3.3/guides/weight_normalization.html

has a link to documentation v3.4. That link leads to a 404 error. 

We should check that all links in the docs work. Where parts of documentation have been removed or moved so they need more complex redirection, at the very least the user should get a nice message than "page not found".

**Comment by med-ayssar** [comment]
Some of those links are not under `/guides` anymore, and that one in particular is under `/synapses`: [https://nest-simulator.readthedocs.io/en/v3.4/synapses/weight_normalization.html](https://nest-simulator.readthedocs.io/en/v3.4/synapses/weight_normalization.html)
