### ISSUE TITLE
Convert rST links to Markdown in autogenerated Notebooks

### ISSUE THREAD

**Issue by nicolossus** [nest/nest-simulator#2653]
**Describe the flaw**
Links are not rendered properly in the Notebooks autogenerated from the example scripts. For example, the link to the [One neuron example](https://nest-simulator.readthedocs.io/en/latest/auto_examples/one_neuron.html) in the [Two neuron example](https://nest-simulator.readthedocs.io/en/latest/auto_examples/twoneurons.html) Notebook is displayed as the raw rST `` :doc:`one_neuron` ``.

**Suggest an improvement**
Based on the ``sphinx-gallery`` documentation (https://sphinx-gallery.github.io/stable/configuration.html#using-pypandoc-to-convert-rst-to-markdown), it seems like ``pypandoc`` can be used to automatically convert rST to Markdown:

```Python
sphinx_gallery_conf = {
    ...
    'pypandoc': True,
}
```

**Comment by jessica-mitchell** [comment]
@nicolossus I have experimented with this option and a couple of other things, but I have yet to actually manage to get the conversion to work properly. Up to now, I only get markup that looks like `{.interpreted-text role="doc"}` in the final notebook.

**Comment by jessica-mitchell** [comment]
Closing issue; no adequate solution was found
