### ISSUE TITLE
gidcollections are not iterable in SLI

### ISSUE THREAD

**Issue by mschmidt87** [nest/nest-simulator#266]
Currently, is is not possible to loop over a `gidcollection` in SLI, i.e. the following code

```
/iaf_neuron 2 Create
1 2 cvgidcollection
{} 
forall 
```

produces the error:

```
Candidates for +forall+ are:
arraytype      proceduretype  calls -forall_a-
stringtype     proceduretype  calls -forall_s-
iteratortype   proceduretype  calls -forall_iter-
dictionarytype proceduretype  calls <proceduretype>
doublevectortypeproceduretype  calls -forall_dv-
intvectortype  proceduretype  calls -forall_iv-
```

I think that we should implement the possibility to loop over a `gidcollection`. I will take a look at this.

**Comment by heplesser** [comment]
I am working on this in connection with #455, I have a working prototype and will create a PR in the not too far future. I close this issue to keep issue-clutter down.
