### ISSUE TITLE
Small documentation bug in comment reg. structural plasticity

### ISSUE THREAD

**Issue by wschenck** [nest/nest-simulator#267]
@sdiazpier:
I think I have found a small documentation bug in one of the comments reg. structural plasticity. Please look [here](https://github.com/nest/nest-simulator/blob/57a27c9c766f2e4642ae1381980ec2ce84c03ff6/nestkernel/nestmodule.cpp#L1785).

"Name: EnableStructuralPlasticity" in the comment does not fit to the functions which follow directly afterwards.

**Comment by sdiazpier** [comment]
Dear @wschenck thanks for noticing that. I will fix it as soon as possible.
