### ISSUE TITLE
postscript-sli-mode in emacs leads to unusable keys

### ISSUE THREAD

**Issue by mschmidt87** [nest/nest-simulator#268]
When using postscript-sli-mode with the provided lisp files in emacs, some keys are no longer usable.
In particular, typing 'd', '[', and ']' leads to the same error, which reads
`Symbol's value as variable is void: last-command-char`.

Produced with Emacs 24.4.1.

**Comment by heplesser** [comment]
We suggest using the standard `postscript-mode`, which is regularly maintained by an active external community.

**Comment by ruedigerkupper** [comment]
Ohmygod!!! SLI-mode is gone??? Shame, shame, shame!!!
(Go ahead, cheers, Rüdiger)
