### ISSUE TITLE
Why is giving the install prefix mandatory?

### ISSUE THREAD

**Issue by tammoippen** [nest/nest-simulator#270]
This is an issue, which came to our attention while working on the build system #213: with master, we fail loudly, when the user does not supply a value to `--prefix` during configure:

```
Please supply a valid installation prefix, for example ./configure --prefix=\$HOME/opt/nest !
```

With `cmake` I 'copied' the behavior, but it is not clear whether we should keep the bahavior.

**Comment by heplesser** [comment]
If I remember correctly, `prefix` defaults to `/usr/local`. This may have been introduced to protect users from configuring for directories requiring root privileges for installation, and to encourage them to install NEST in places where it can easily be uninstalled by deleting an entire directory.

If we permit configure without `--prefix`, we should adhere to the "default default" (`/usr/local`, I guess). If we still require `--prefix`, we might want to provide a more detailed error message.
