### ISSUE TITLE
Create a glossary of terms and abbreviations

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#274]
#273 makes me wonder if and where we should create a glossary of terms used in NEST. `wfr` makes sense, but it is not immediately comprehensible as "waveform relaxation", it is simply not an abbreviation widely known in the relevant community (in contrast to, e.g., `iaf` and `hh`). What would be a good place for such a glossary?

@jougs @steffengraber Any ideas?

**Comment by steffengraber** [comment]
Hi @heplesser 
I translated all static documentation to standard markdown:
https://github.com/steffengraber/nest-simulator/tree/static-markdown-doc/extras/userdoc/md/documentation

Maybe we can integrate it there.

**Comment by jougs** [comment]
I agree with @steffengraber. @heplesser, can you create a pull request against Steffen's repository?

**Comment by jougs** [comment]
Just mentioning @jessica-mitchell to make her aware of this.

**Comment by jessica-mitchell** [comment]
I've been compiling a list of terms; I still need to format list into some order. Here's what I have so far: 
https://github.com/jessica-mitchell/nest-simulator/blob/doc-doc/doc/glossary.rst

Suggestions welcome :)

**Comment by heplesser** [comment]
Glossary is available in master, thus closing.

**Comment by jougs** [comment]
This is now on read-the-docs: https://nest-simulator.readthedocs.io/en/latest/glossary.html
