### ISSUE TITLE
Design question of music channel indexing

### ISSUE THREAD

**Issue by uahic** [nest/nest-simulator#275]
I finished a first working music_cont_out_proxy but there is a last issue (design question) that needs to be resolved.

After some discussion with Mikael Djurfeldt we have the following possibilities for the mapping of neurons to global music indice:

1. The user passes a list of neuron GIDs to the proxy, each process finds via NEST c++ api the neuron which are locally available and acesses them directly or performs an automatical nest.Connect(proxy, neuron_xzy) under the hood. 

Possible issues: the list can be very large and how does the user know the list? Sure he can perform GetStatus(neurons) but on each local process this will just return a subset of the (process-local) gids.

 2. The user draws synapses just like for a multimeter (this is how the proxy is implemented right now and not working). The proxy can not do the mapping correctly  as it does not know which global music indices are occupied from other processes.  To resolve this we could derive a new synapse from static_connection and add a datum "music_channel". Note: since the connection direction of the synapses is reversed compared to the spike output neuron it is not possible to misuse receptor_types for the music_channel.

Possible issues: New synapse type must be created and used (which is a bit unintuitive) and maybe its not possible(?) for the proxy to refuse other synapse types (note: the connection is outgoing from the proxy)

 3. Let the proxy do the mapping automatically. This requires information  exchange between all processes and could work as follows:  First, the proxy on each process counts the number of its connected target neurons. Second, it performs an MPI_ALLGATHER to share the integer with all other MPI ranks (= each process holds #ranks integers which should be feasible). Third, each process sums up the numbers from rank 0 until its own rank to compute its offset in  the global music indice list. Example for rank 4:  offset_rank4 = Sum( #neurons_rank0, #neurons_rank1 ....). Finally it maps its neurons to  IndexMap[ offset + i ] whereas i is the port number of outgoing connections in the proxy (goes from 0 - #connections).  It would also be possible to map them in the Index Array sorted by the neuron GID to make it independent of the connection order. 

Possible issues: How does the music-receiver know which neuron maps to which channel?

**Comment by mdjurfeldt** [comment]
Just to clarify my position on this:

The most important question we need to settle is how the user interface for mapping a set of neurons to a MUSIC port should look like. Once we have decided this, we'll certainly find a good way to implement it.

I think we should re-use as much as possible of the existing concepts in the NEST world. For example, there will always be ways in NEST to specify a set of neurons for the NEST connection primitives.  Currently, the official way to do it is a list of Global ID:s. In the future, it may be ranges.

Then, we could either choose to 1. directly use the same way of specifying a set of neurons to export their values through a MUSIC output port (saying: "I want to export values of these neurons"), or we could 2. choose to make use of the NEST connection primitives and introduce a population of proxy objects, one for each "channel" in the port, such that we can make a structured projection to the port, just the way we can make a structured projection to another population of neurons.

I tend to prefer 1.

**Comment by apeyser** [comment]
Why does this mapping need to be done via MUSIC? What I mean is if we define a bag of neurons through some other mechanism at network creation time, then we can simple make a 0..n id for the music mapping without knowing what the underlying gid's are. So m maps to collection[m], which was created on construction without the allgather.

For this we just need a population object or device that does the mapping.

**Comment by uahic** [comment]
The problem is that each process has to do its own mapping and must know which global music id (range) to use to prevent overlapping with other processes. Think about a single global array outside of NEST and now you need to map neurons ids or mapped neuron ids to this array.

**Comment by mdjurfeldt** [comment]
This is not done via MUSIC. This is about deciding how it should look like for the user to export a set of neurons through a MUSIC port from within NEST.

Yes, what you describe sounds like my alternative 1.

Do you have "population objects" now in NEST?  What alternatives do we have to specify the bag of neurons except for a list of gids (as specified in the NEST manual for the connection primitives)?

**Comment by mdjurfeldt** [comment]
@uahic The cont proxy should use NEST infrastructure to determine which of the gids are local in one process. The intersection of the bag of local neurons and the bag to be exported through the port is what makes the music index map (which is an implementation detail which the user should not see).

**Comment by JanneM** [comment]
As a user, my main concern is being absolutely certain that I know which neuron maps to which output channel, then to which input channel. Typically, you'd have an explicit array with a set of GIDs or a reference to a structure such as a subnet or a topological network. You expect the mapping to be consistent: a subnet or topology surface is mapped in GID (row) order to MUSIC channels. For an array of GIDs then of course map them to channels in array order. Then you do the reverse mapping on the recipient side.

**Comment by uahic** [comment]
I would prefer to specify the channel on the  synapse just as it is the case for the spike output proxy. This would satisfy full control in which output channel the information goes and the user does not have to worry about GIDs. Maybe we can solve this without a new synapse model if we put some logic in one of the base classes (I dont know how they work yet) and if the user sets music_channel ids then it is put into the music_manager object

**Comment by mdjurfeldt** [comment]
@uahic 1. Why do you prefer to specify the channel on the synapse? You should not use the event output proxy as a model or try to align to it, because we have for long talked about changing this interface. At least, we should now try to figure out what is most convenient. Specifying a list of gids *does* give you full control over which values are mapped to which channels in th port.

2. The GID list approach is not complicated. What I'm saying is that we should use the same way to specify neurons as when we call Connect on two populations to connect them using some rule. Typically, the gid list is what you obtain form Create when the population is created. Also, the computation of the music index map should be done at the C++ level *inside* the proxy object.  The user script should not be bothered with what neurons are process local. The proxy should obtain the entire, global, list of GIDs.

The computation of the index map inside the proxy object implementation, in a local process goes like this:

We iterate through the list of GIDs. The index of the GID in the list is the MUSIC global index. For each gid, we ask NEST if it is local.  If so, it goes into the local MUSIC index map.

No communication is required.

**Comment by uahic** [comment]
It is clear that this happens inside c++,  okay I didnt thought about that the position is inherently included in the gid list, I could code this. The remaining problem is: should the user really specify the GID list manually? As I said before, asking NEST for GIDs via GetStatus returns NOT the entire list of GIDs, just the local GIDs

Example script for 4 MPI ranks:
neurons = nest.Create('iaf_neuron', 4)
print( neurons )
Executed on rank1:
>> (1,)-
Executed on rank 2:
>> (2,)
Executed on rank3:
>> (3,)

**Comment by mdjurfeldt** [comment]
@uahic Good.

Regarding Gid list and Create: 

Some of the rules for Connect require knowledge about the corresponding neurons in other ranks, so somehow information about the full set of neurons must be there.  I'm talking about, for example:

pop1 = nest.Create (...)
pop2 = nest.Create (...)
conn_dict = {'rule': 'fixed_outdegree', 'outdegree': N}
nest.Connect (pop1, pop2, conn_dict)

Can a real NEST developer chip in here? How can Connect above know what to do with a neuron in pop1 if it *only* knows about the local subset of pop1?

The relevance for this discussion is that we intend the user to give the result of Create (...) as a representation of the rank global population to the MUSIC cont proxy in a local rank.

**Comment by uahic** [comment]
@mdjurfeldt Would you argue against using your approach but once the list is set, the proxy connects itself (via c++) against the target neurons via synapses?  this would simplify to retrieve the desired cont values alot and fits in the pipeline nicely. In the current state Objects

**Comment by mdjurfeldt** [comment]
@uahic This is a question for the NEST developers. I can't argue against it.

**Comment by uahic** [comment]
Okay I tried to run Nest with 2 MPI ranks on different machines and both of them return all created global ids

**Comment by mdjurfeldt** [comment]
Great! Everything clear, then?
Den 11 mar 2016 17:40 skrev "Martin Schulze" <notifications@github.com>:

**Comment by uahic** [comment]
Absolutely! 

@Nestdevelopers
I had a look over the current repository code what I would like to know is if the music interface (for the user) will in the future still involving neuron representations or be purely go via Get/SetKernelStatus?

**Comment by uahic** [comment]
Okay the music_con_out_proxy neuron seems to work properly now

**Comment by jougs** [comment]
Sorry to step in only so late. I've been quite busy recently. Here's some clarifications:

- `Create` in SLI only returns the last (global) GID it created. This means the whole range can be re-creaetd using the returned value and the number of nodes created
- `Create` in PyNEST does exactly this. It returns `tuple(range(last_gid - n + 1, last_gid + 1))`
- Since [NewConnect](https://github.com/nest/nest-simulator/releases/tag/v2.6.0), we use [`gidcollection`](https://github.com/nest/nest-simulator/blob/v2.6.0/nestkernel/gid_collection.h) objects to specify lists of nodes for `Connect`. They can either contain an explicit list of GIDs or a range represented by first and last gid. `gidcollections` provide convenient C++ iterators that either count or really iterate and do not know about local and global nodes

I hope this helps.

**Comment by uahic** [comment]
This is excellent!, is the other way around also supported that the user is able to pass ranges into SetStatus and it is then converted into GIDCollections?

**Comment by jougs** [comment]
Currently only `Connect` supports `gidcollection`. The plan is to make `Create` return a `gidcollection` and convert all functions that operate on GIDs or lists of GIDs use them. Ideally, we'd also have a wrapper for Python so one can use them as normal iterables there as well. See also #266.

Also, I'm happy to review a pull request if you want to start converting functions to `gidcollection`.
