### ISSUE TITLE
Should the CI fail again when the NEST build raises warnings?

### ISSUE THREAD

**Issue by nicolossus** [nest/nest-simulator#2779]
Before the merge of https://github.com/nest/nest-simulator/pull/2590 with the new CI setup, the CI would fail if any warnings were raised in the building of NEST. Known warnings could be excluded in the now removed `parse_build_log.py`. 

Currently, the CI passes even though warnings are raised. Do we want this new behavior or should the old behavior be reinstated?

**Comment by nicolossus** [comment]
@heplesser @jougs @terhorstd Any opinions?

**Comment by jougs** [comment]
Generally, I think we should strive for zero warnings during the build.

Can you have a look at how to get the old behavior back? I assume this is not so easy now that we don't write the logs to our own files anymore, or is there a way to programmatically look at the output that GitHub Actions caches?
