### ISSUE TITLE
Question about multi-rate of adaptive stepping 

### ISSUE THREAD

**Issue by brunomaga** [nest/nest-simulator#278]
Hi there.

I have a question concerning the interpolation methods: Is it possible to use multi-rate or adaptive time stepping (e.g. VODE, LSODE) in nest? If yes, can you point me to a tutorial or documentation?

Also, I was under the impression that you use Euler methods for fixed step interpolation, yet the features page says "Each neuron model is assigned an appropriate solver". What other solvers do you apply and how do you decide on which solver is assigned to a given neuron?

Thank you

**Comment by heplesser** [comment]
@brunomaga Please address general questions about NEST to the NEST User Mailing List (http://www.nest-simulator.org/community/). Github issues should address bugs in the code or errors in the documentation. I am therefore closing this issue.
