### ISSUE TITLE
Docs landing page should showcase examples

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#2783]
This is just a suggestion based on user feedback.

The landing page of the docs (https://nest-simulator.readthedocs.org/) could showcase our coolest examples ("applications") from https://nest-simulator.readthedocs.io/en/v3.4/examples/index.html#pynest-examples, rather than a little script snippet which is typically glossed over (too much technical detail for a landing page). Applications are much more telling about what you can do with NEST (what it can do for you!)

**Comment by jessica-mitchell** [comment]
We are looking at modifying the main page, so thanks for  sharing the feedback :)
