### ISSUE TITLE
import mathematics equation in a DA model

### ISSUE THREAD

**Issue by atiye-nejad** [nest/nest-simulator#2799]
Hi, I am not sure if I am writing in a right place, Just  I have a question. Can I use mathematical equations in a mathematical modeling for my synapse and neuron model in Nest? if yes, how? By Nestml? 
Thanks

**Comment by pnbabu** [comment]
@atiye-nejad you could use NESTML to model your mathematical equations. In a typical NESTML model file, you could define these equations in the `equations` block as described [here](https://nestml.readthedocs.io/en/v5.2.0/nestml_language/nestml_language_concepts.html#equations).

To get an overview of how a NESTML model looks like, you could take a look at the [models library](https://nestml.readthedocs.io/en/v5.2.0/models_library/index.html) and the [tutorials](https://nestml.readthedocs.io/en/v5.2.0/tutorials/index.html) we have on our docs page. We have both neuron and synapse models there. 

Hope this helps. If you have more specific questions on NESTML, you could write to the [NEST mailing list](https://nest-simulator.readthedocs.io/en/latest/developer_space/guidelines/mailing_list_guidelines.html#mail-guidelines) or create an issue on the [NESTML repository](https://github.com/nest/nestml).
