### ISSUE TITLE
Regressiontest `ticket-77.sli` fails

### ISSUE THREAD

**Issue by weidel-p** [nest/nest-simulator#285]
The regressiontest `ticket-77.sli` fails if NEST is configured with MUSIC.
I think this test handles the `music_event_out_proxy` as a neuron model and therefore fails.

**Comment by heplesser** [comment]
@weidel-p When NEST is compiled with MUSIC, `music_event_out_proxy` appears as a model in `modeldict`, doesn't it? Clearly, the test in `ticket-77.sli` makes no sense for the music proxy. Could you add the proxy to the `skip_list` (l 57-62)? Then the test will ignore it.

Could you at the same time rename the test from `ticket-77.sli` to `issue-77.sli` (Github: issues, old trac: tickets)?

**Comment by weidel-p** [comment]
fixed by #312
