### ISSUE TITLE
conda-forge installation of nest-simulator not working

### ISSUE THREAD

**Issue by giuliaboiani** [nest/nest-simulator#2863]
conda install conda-forge nest-simulator not working: stacked at solving environment

just created a new conda environment and run installation

![nest_error](https://github.com/nest/nest-simulator/assets/100765050/db264af6-d5ba-44a5-bb20-ee0b72c08844)

 - Ubuntu-Version: 20.04
 - Python-Version: 3.8

This happened also for other ubuntu versions and python versions, too.
We were able to install nest only with cmake.
(_conda install -c "conda-forge/label/cf202003" nest-simulator_ worked, but nest 2 was installed )

Thanks for your help!

**Comment by steffengraber** [comment]
I have tested it within a clean system. It took a bit longer, but the installation went through and NEST 3.5 could be executed. Does the installation simply abort, or is there a more specific error message? The assumption is that a problem with a pre-installed package exists.
To install an older version of NEST use for example:
    
    conda install -c conda-forge nest-simulator=3.4

I'm trying to reduce the dependencies in the package so conda will install faster.

**Comment by steffengraber** [comment]
@giuliaboiani Maybe mamba will help you. a one-to-one replacement for conda, which solves some problems with creating conda environments.
For installation, see here: https://mamba.readthedocs.io/en/latest/
NEST installation:

    maba install -c conda-forge nest-simulator

**Comment by steffengraber** [comment]
Appears to be resolved, so can be closed.
