### ISSUE TITLE
Remove assimulo dependency?

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2868]
Currently, the conda environment file for NEST specifies a dependency on Assimulo. This is only required to be able to run the doc/htmldoc/model_details/aeif_models_impementation.ipynb notebook.

I introduced the assimulo dependence with the aeif_models notebook, but now seriously wonder if it makes sense to have it. It has considerable dependencies of its own and is almost entirely tangential to NEST. One could rather then include a clear message in the notebook for those who want to run it—a tiny fraction of NEST users, presumably.

@jessica-mitchell Would you be concerned about this change form a documentation point of view (out-of-the-box runnability of notebooks)?

One hiccup could be that the aeif-notebook then might not be runnable on EBRAINS, although I am not sure how dependencies are handled there. Any comment, @terhorstd ? 

Assigning to the doc team since it primarily relates to automatic runnability of a documentation notebook.

**Comment by heplesser** [comment]
@jessica-mitchell As far as I can see, this notebook does not come with a "try it on ebrains" button (https://nest-simulator.readthedocs.io/en/latest/model_details/aeif_models_implementation.html). I also only found it via the search function, not under https://nest-simulator.readthedocs.io/en/latest/understand_index.html.

Getting this to run on EBRAINS would be challenging. Assimulo is not currently installed on EBRAINS (and this notebook would likely be the only need, so I don't think it would be worth it), and Assimulo can only be installed via conda, which is not available on EBRAINS. The pip version of Assimulo is so outdated it is unusable with modern Python versions.

So I think I should just put some extra information about Assimulo installation into the notebook and then remove the dependency. The notebook should then never get a "Try it" button—can that be done in a reasonable way?

**Comment by jessica-mitchell** [comment]
@heplesser Sorry, if I wasn't clear - the `model_details `notebooks have not been set up to use the 'Try it on EBRAINS' button. I just meant if you wanted to open and run the notebook in EBRAINS then we could add the dependency.  
As for finding the notebooks, we discussed a while ago that the model_details should only be added as links to the relevant models they pertain to. So they don't exist in any table of contents or anything. We could certainly change this if they should be more visible.

**Comment by heplesser** [comment]
@jessica-mitchell I created a PR.
