### ISSUE TITLE
Remove vera++ from coding guidelines

### ISSUE THREAD

**Issue by akorgor** [nest/nest-simulator#2870]
The documentation in the developer space lists checks with Vera++ even though these checks are not part of the check workflow anymore, and the software is outdated.

Removing all text related to Vera++ in the following two files would fix the issue.

https://github.com/nest/nest-simulator/blob/master/doc/htmldoc/developer_space/guidelines/coding_guidelines_cpp.rst
https://github.com/nest/nest-simulator/blob/master/doc/htmldoc/developer_space/guidelines/coding_guidelines_check.rst

**Comment by jessica-mitchell** [comment]
@terhorst or @jougs There are several specific vera checks mentioned in the documentation (for example:  Do not use TAB character in any source file (vera++:L002). Always use braces around blocks of code (vera++:T019)). 
If we do not use vera++, are these not checked anymore or are they taken over by clang-format or something else?

**Comment by jougs** [comment]
We're not using `vera++` anymore and all documentation pertaining to it should go.

In general, I think that such specificities should anyway not be listed in the documentation, as they probably will be outdated most of the time and a link to the corresponding location in the code or tool configuration file would be much preferred from my point of view.
