### ISSUE TITLE
DictError in SLI function SetStatus_id: Unused dictionary items:  record from

### ISSUE THREAD

**Issue by atiye-nejad** [nest/nest-simulator#2898]
Hi All, 
when I run this code:
`_multimeter = nest.Create("multimeter", params={'record from':['V_m'],'interval': .1})_`
I face with this error: 
`nest.lib.hl_api_exceptions.NESTErrors.DictError: DictError in SLI function SetStatus_id: Unused dictionary items:  record from`
can you help me what the problem is?
thanks

**Comment by heplesser** [comment]
Hi @atiye-nejad!

It should be `'record_from'` with an underscore, not a space.

For questions like these, the NEST User Mailing List (https://www.nest-simulator.org/community/) is usually a better place than Github.

**Comment by atiye-nejad** [comment]
thanks. 
is it possible to help me in these two questions:
1. how can I record and show I_e  that I inject into the neuron? I face with this error:
`nest.lib.hl_api_exceptions.NESTErrors.IllegalConnection: IllegalConnection in SLI function Connect_g_g_D_D: Creation of connection is not possible because:
Cannot connect with unknown recordable I_e`
2. sometimes when I run a code, I face with this 
 ` Not using MPI`  and nothing happens. what is the problem im this case?
thanks

**Comment by heplesser** [comment]
Please ask these questions about how to use NEST on the NEST User mailing list. The issue tracker is for managing bugs and feature requests.

When asking questions, especially about errors you experience, please include minimal reproducers for the problem, i.e., the shortest piece of Python code that leads from `import nest` to the error message you encouter.

**Comment by heplesser** [comment]
I will close this issue here and look forward to continuing the discussion on the NEST User mailing list.
