### ISSUE TITLE
Problem updating connections with structural plasticity and multiple threads

### ISSUE THREAD

**Issue by sdiazpier** [nest/nest-simulator#290]
Unwanted behaviour is observed when updating the connectivity of the network using structural plasticity with multiple threads. This is not the case when multiple MPI processes are used. It seems like it is a problem with the structural plasticity manager while updating the number of deleted synapses.

**Comment by heplesser** [comment]
@sdiazpier Could you add a script reproducing this problem? It should be as compact as possible and preferably written in SLI so we can develop a regression test from it.

**Comment by heplesser** [comment]
@sdiazpier What is the status on this?

**Comment by heplesser** [comment]
Per 2.12, NEST should at least prohibit simulations with structural plasticity and multiple threads, if we cannot solve this issue properly by then.

**Comment by sanjayankur31** [comment]
@sdiazpier - can you please expand on "unwanted behaviour"? I'm using SP with MPI but I haven't really been analysing the data yet. If you can give us more information, I can narrow down the issue. Either a test case or a data dump from a test case would be most helpful?

**Comment by heplesser** [comment]
@sdiazpier Could you create a follow-up issue to remind us to check whether and how structural plasticity can be enabled in multi-threaded simulations?

**Comment by heplesser** [comment]
Using structural plasticity is now blocked when using multiple threads (see #629) and #633 is created as a follow-up issue. Thus closing this issue.
