### ISSUE TITLE
Superfluous clearing of containers

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2991]
As noticed by @diesmann and @mlober, the `(*it)->clear()` calls in the code below are most likely superfluous, since the vector pointed to by `it` is deleted immediately afterwards:

https://github.com/nest/nest-simulator/blob/d70928ec687942dc2fc548f47b18b1fc7644501d/nestkernel/event_delivery_manager.cpp#L119-L131

The loops would also become simpler and more robust using C++11-style container iteration.

**Comment by terhorstd** [comment]
The explicit `clear()` is necessary, because the vector contains explicit pointers to inner vectors. The delete removes all elements of the outer vector (*pointers!*), but the inner vector *instances* need to have their elements removed before the pointer is deleted.
Note that the `clear()` call does a double "dereferencing": `it` is the iterator, `*it` is a pointer and `->` dereferences to the `vector<>`.

**Comment by heplesser** [comment]
@terhorstd I don't quite agree with your analysis. We have
```c++
std::vector< std::vector< SpikeDataWithRank >* > emitted_spikes_register_;
```
and
```c++
auto it = emitted_spikes_register_.begin();
```
so `*it` gives us the first element of the outer vector, i.e., a pointer to an `std::vector<SpikeDataWithRank>` object. The entries in this vector are non-pointer entries, and `(*it)->clear()` clears these entries. Afterwards, 
```c++
delete (*it);
```
destroys the `std::vector<SpikeDataWithRank>` object that `*it` points to. In my understanding of C++ containers, deleting a container that contains only non-pointer objects, will properly delete all objects contained in the container, i.e., call their destructors, before deleting the container itself. Therefore, the `(*it)->clear()` is superfluous. Afterwards,
```c++
emitted_spikes_register_.clear(); 
```
removes the now invalid pointers.

**Comment by terhorstd** [comment]
After our discussion we concluded that indeed this should also do:
```cpp
 for ( auto vec_spikedata_ptr : emitted_spikes_register_ ) 
 { 
   delete vec_spikedata_ptr; 
 } 
 emitted_spikes_register_.clear(); // remove stale pointers
 ```
