### ISSUE TITLE
MAC INSTALLATION

### ISSUE THREAD

**Issue by avramidou** [nest/nest-simulator#2995]
I tried to install nest using "brew install nest" (I already have homebrew)

1. Open the terminal and run "brew install nest" 
2. Open jupyter notebook from the terminal
3. Create a jupyter notebook and run "import nest"
5. This gives the error: 
"nest: python package requires root access
An exception has occurred, use %tb to see the full traceback.
SystemExit: 1"

**Desktop/Environment:**
 - OS: macOS sonoma
 - Python-Version: Python 3.12
 - NEST-Version: nest-3.6

**Comment by heplesser** [comment]
Hi @avramidou,

To test, I did the following on macOS Sonoma (Intel silicon):
1. Uninstalled old homebrew
2. Installed homebrew anew
3. Ran
    1. `brew install nest`
    2. `brew install ipython`
    3. `brew install jupyterlab`

I then tested the following

1. Start `python3.12` from the command line and then `import nest`
2. Start `ipython` from the command line and then `import nest` 
3. Start `jupyter lab` from the command line, launch a notebook, then `import nest`

In all three cases importing worked. Your problem may be related to different Python versions installed by Homebrew. Could you post more context for the error output?

**Comment by gtrensch** [comment]
Closing this issue for now because of inactivity.
