### ISSUE TITLE
Dead link to 'Overview of scheduling and update strategies' on homepage index.md

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#30]
In the [index.md](https://github.com/nest/nest-simulator/blob/gh-pages/index.md) there is a dead link to [Overview of scheduling and update strategies](https://github.com/nest/nest-simulator/blob/gh-pages/simulation_loop_mindelay). 

I assume this will include a overview of the internal simulation loop, i.e. when which node/connection functions are called by the simulator. Comparable slides were shown at the Nest User Workshop, and I guess these would be a great help for people to start in development. 

One idea would be to make available the pdf of the slides under this link instead, while the page is not yet finished or published.

**Comment by tammoippen** [comment]
The dead link is removed with #78. 
General information about the *scheduling and simulation* can be found at [http://www.nest-simulator.org/scheduling-and-simulation-flow/](http://www.nest-simulator.org/scheduling-and-simulation-flow/). 
General information about the *connection creation* can be found at [http://www.nest-simulator.org/connection_management/](http://www.nest-simulator.org/connection_management/).

I agree that more detailed information about the internal implementation are useful and I will look into this.

**Comment by flinz** [comment]
Great, thanks for picking up on this! I'll close the issue.
