### ISSUE TITLE
The reset of after-spike currents in GLIF model does not seem to conform with the original equations

### ISSUE THREAD

**Issue by CloudyDory** [nest/nest-simulator#3009]
**Describe the bug**
The GLIF3 model described in [Teeter et al., Nature Communications, 2018](https://www.nature.com/articles/s41467-017-02717-4) is given by:

```
dV/dt = (I_input(t) + I_asc_1(t) + I_asc_2(t) - (V(t) - E_L)/R) / C
dI_asc_1/dt = -k1 * I_asc_1(t)
dI_asc_2/dt = -k2 * I_asc_2(t)
Spike(t) = V(t) > V_threshold
```

Importantly, when a spike is generated, after a refractory period, δt, the state variables are updated with a linear dependence **on the state before the spike** (page 12 of Teeter et al., 2018):

```
V(t+) <-- V_reset
I_asc_1(t+) <-- f1 * I_asc_1(t+) + I_asc_reset_1
I_asc_2(t+) <-- f2 * I_asc_2(t+) + I_asc_reset_2
```
where  `t+` and `t−` represent the time just after and before a spike, respectively. If the refractory period `δt > 0`, then I assume that `t+` should realy be `spike_time + δt`. Besides, in NEST, the default values of `f1` and `f2` are all `1`.

The above description means that after a spike, the sum of change of after-spike currents should be a constant value: `I_asc_reset_1 + I_asc_reset_2`. However, when checking the NEST simulation result, I found that this is not true.

**To Reproduce**
Run the following python code:
```python
import numpy as np
import matplotlib.pyplot as plt
import nest

nest.ResetKernel()
resolution = 0.05
nest.resolution = resolution

#%% Initialize the network components
neuron = nest.Create(
    "glif_psc",
    params={
        "spike_dependent_threshold": False,
        "after_spike_currents": True,
        "adapting_threshold": False,
    },
)

cg = nest.Create(
    "step_current_generator",
    params={
        "amplitude_values": [400.0],
        "amplitude_times": [100.0],
        "start": 100.0,
        "stop": 300.0,
    },
)

mm = nest.Create(
    "multimeter",
    params={
        "interval": resolution,
        "record_from": ["V_m", "I", "I_syn", "threshold", "threshold_spike", "threshold_voltage", "ASCurrents_sum"],
    },
)

sr = nest.Create("spike_recorder")

nest.Connect(cg, neuron, syn_spec={"delay": resolution})
nest.Connect(mm, neuron)
nest.Connect(neuron, sr)

#%% Run the simulation
nest.Simulate(400.0)
data = mm.events
spikes = sr.events["times"]

t = data["times"]
asc_reset_sum = sum(neuron.get('asc_amps'))

#%% Plot the results
plt.figure(figsize=(12,8))
plt.subplot(2,1,1)
plt.plot(t, data["ASCurrents_sum"], label='currents')
plt.plot(spikes, np.zeros_like(spikes)+data["ASCurrents_sum"].min(), marker='.', linestyle='', color='r', label='spike')
plt.xlabel('Time (ms)')
plt.ylabel('ASCurrents_sum')
plt.legend()

plt.subplot(2,1,2)
plt.plot(t[:-1], np.diff(data["ASCurrents_sum"]), label='diff(currents)')
plt.axhline(y=asc_reset_sum, xmin=t[0], xmax=t[-2], linestyle='--', color='k', label='reset amplitude')
plt.xlabel('Time (ms)')
plt.ylabel('diff(ASCurrents_sum)')
plt.legend()

plt.tight_layout()
plt.show()
```

**Expected behavior**
In the lower panel of produced figure, the change of after-spike currents should peak at the sum of `I_asc_reset_1 + I_asc_reset_2`, which is the black dashed line.

**Actual behavior**
The peaks of the change of after-spike currents are not a constant, mostly fall short of `I_asc_reset_1 + I_asc_reset_2`. Only the first peak seems to be correct.

![Figure_1](https://github.com/nest/nest-simulator/assets/38786521/aa376ff1-ffc9-45d6-a664-b8e468d884e8)

**Desktop/Environment (please complete the following information):**
 - OS: Ubuntu-22.04
 - Shell: bash
 - Python-Version: Python 3.10
 - NEST-Version: `nest.__version__ = 3.6.0`
 - Installation: apt, with MPI

**Comment by clinssen** [comment]
Thanks for your report! I am not an expert on the model, but could it be that the difference you are seeing between the actual and expected values is due to the decay of the after-spike currents during the refractory period? That is, perhaps the variable "ASCurrents_sum" does not just contain the instantaneous update due to the spike, but that plus the amount of decay since the start of the refractory period.

If you set the refractory period to a very small value (0.0001), the actual and expected values match almost exactly. 

Does this help?

**Comment by CloudyDory** [comment]
@clinssen Thanks for the reply! Yes, setting the refractory period to a very small value solves the issue. But it's a little bit strange, as the sum of the after-spike currents is flat during the refractory. It seems like NEST still updating the after-spike currents in the background, yet the actual recorded values are clamped.

I have one more question: Allen institute has release [GLIF model parameters fitted to mouse V1 neuron data](http://celltypes.brain-map.org/), and judging from the [source code of GLIF neuron in allensdk](https://allensdk.readthedocs.io/en/latest/_modules/allensdk/model/glif/glif_neuron.html#GlifNeuron), it seems that their GLIF model does not silently update after-spike currents during the refractory period. So the behavior of GLIF model in NEST and allensdk is different. It is still valid to use Allen's published GLIF parameters in NEST? I know some fitted parameters has longer refractory period. The default one in NEST is 3.75 ms, but some neuron's is 6.7 ms.

**Comment by CloudyDory** [comment]
@clinssen I can verify the behavior of GLIF neuron model in allensdk with the following code:

```python
import numpy as np
import matplotlib.pyplot as plt
from allensdk.model.glif.glif_neuron import GlifNeuron

#%% Neuron parameters
neuron_config = {
  "El_reference": -0.07139990234375,
  "C": 8.587009771685807e-11,
  "asc_amp_array": [-7.383464366961142e-11, -4.496828542736005e-10],  # <---- after-spike current reset values
  "init_threshold": 0.023089253057717987,
  "threshold_reset_method": {
    "params": {},
    "name": "inf"
  },
  "th_inf": 0.023089253057717987,
  "spike_cut_length": 134,  # <---------- refractory period in timesteps
  "init_AScurrents": [0.0, 0.0],
  "init_voltage": 0.0,
  "threshold_dynamics_method": {
    "params": {},
    "name": "inf"
  },
  "voltage_reset_method": {
    "params": {},
    "name": "zero"
  },
  "extrapolation_method_name": "endpoints",
  "dt": 5e-05,
  "voltage_dynamics_method": {
    "params": {},
    "name": "linear_forward_euler"
  },
  "El": 0.0,
  "asc_tau_array": [0.03333333333333334, 0.0033333333333333335],
  "R_input": 340045253.17350113,
  "AScurrent_dynamics_method": {
    "params": {},
    "name": "exp"
  },
  "AScurrent_reset_method": {
    "params": {"r": [1.0, 1.0]},
    "name": "sum"
  },
  "dt_multiplier": 10,
  "th_adapt": None,
  "coeffs": {
    "a": 1,
    "C": 1,
    "b": 1,
    "G": 1,
    "th_inf": 0.9713141567566914,
    "asc_amp_array": [1.0, 1.0],
  },
  "type": "GLIF"
}

#%% Initialize the neuron and stimulus
srate = 50000.0  # Hz

neuron = GlifNeuron.from_dict(neuron_config)
neuron.dt = 1.0 / srate

stimulus = np.zeros(100000)
stimulus[25000:75000] = 1.0e-10

#%%
output = neuron.run(stimulus)
time = np.arange(len(stimulus)) * neuron.dt

non_nanidx = np.any(np.logical_not(np.isnan(output['AScurrents'])),axis=1)
after_spike_currents_nonan_sum = output['AScurrents'][non_nanidx,:].sum(axis=1)
after_spike_currents_nonan_sum_diff = np.diff(after_spike_currents_nonan_sum)

#%% Plot the results
plt.figure(figsize=(10, 10))

plt.subplot(4,1,1)
plt.plot(time, stimulus)
plt.xlabel('time (s)')
plt.ylabel('current (A)')
plt.title('Stimulus')

plt.subplot(4,1,2)
plt.plot(time, output['voltage'], label='voltage')
plt.plot(time, output['threshold'], label='threshold', linestyle='--')
if (output['spike_time_steps'] is not None) and len(output['spike_time_steps'])>0:
    plt.plot(output['interpolated_spike_times'], output['interpolated_spike_voltage'], marker='.', color='r', linestyle='', label='spike')
plt.xlabel('time (s)')
plt.ylabel('voltage (V)')
plt.legend(frameon=False)
plt.title('Model Response')

plt.subplot(4,1,3)
plt.plot(time, output['AScurrents'].sum(axis=1))
plt.xlabel('time (s)')
plt.ylabel('current (A)')
plt.title('After Spike Currents (sum)')

plt.subplot(4,1,4)
plt.plot(time[non_nanidx][:-1], after_spike_currents_nonan_sum_diff)
plt.axhline(y=neuron.asc_amp_array.sum(), color='k', linestyle='--')
plt.xlabel('time (s)')
plt.ylabel('diff(current) (A)')
plt.title('diff(After Spike Currents)')

plt.tight_layout()
plt.show()
```

![Figure_1](https://github.com/nest/nest-simulator/assets/38786521/6aff745b-d16c-4afd-93d4-e0ab1bc747e9)

As one can see in the last panel, the peak of the change of after-spike currents is always exactly the same as the sum of after-spike spike current reset values.

**Comment by CloudyDory** [comment]
I have checked the code in allensdk further.It turns out that they are also updating the after-spike currents during the refractory period. So the behavior is the same as NEST. Thanks!
