### ISSUE TITLE
NEST build system does not respect --docdir

### ISSUE THREAD

**Issue by tammoippen** [nest/nest-simulator#303]
(from trac.781)

On SUSE (and maybe other Linux) they have different install directories for `doc` and `data` than `$(datadir)/doc/$(pkgname)`. With autotools you could set the datadir with `--datadir`, but NEST did not respect this. With cmake this is still not implemented, but could be with little efford by using [`GNUInstallDirs`](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html).

**Comment by sanjayankur31** [comment]
Looks like this is fixed. @tammoippen - please close if fixed?
