### ISSUE TITLE
Review Examples

### ISSUE THREAD

**Issue by tammoippen** [nest/nest-simulator#304]
(from trac.904)

With cmake all examples are installed. The task of this issue is to review all examples, fix them if they are outdated or remove them if they are not needed anymore. See also #291 which will effect installed examples as well.

**Comment by heplesser** [comment]
Added 3.0 Milestone, since all examples will require review as we transit to GIDCollections and remove subnets, see #480 .

**Comment by jougs** [comment]
I have reviewed and fixed all examples in the course of the work for the [subnet-free Topology](https://github.com/compneuronmbu/nest-simulator/tree/fix-481-SubnetFreeTopology) and thus consider this fixed.
