### ISSUE TITLE
cmake -Dwith-libneurosim=ON failed

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#307]
`cmake -DCMAKE_INSTALL_PREFIX=/home/steffen/work/opt/nest -Dwith-optimize=ON -Dwith-warning=ON -Dwith-mpi=OFF -Dwith-python=ON -Dwith-gsl=OFF -Dwith-libneurosim=ON

make
`
Failed with:

`/home/steffen/Downloads/nest-simulator-master/conngen/conngendatum.h:27:43: fatal error: 

neurosim/connection_generator.h: Datei oder Verzeichnis nicht gefunden

compilation terminated.
nest/CMakeFiles/nest.dir/build.make:77: recipe for target 'nest/CMakeFiles/nest.dir/neststartup.cpp.o' failed

make[2]: **\* [nest/CMakeFiles/nest.dir/neststartup.cpp.o] Error 1

CMakeFiles/Makefile2:595: recipe for target 'nest/CMakeFiles/nest.dir/all' failed

make[1]: **\* [nest/CMakeFiles/nest.dir/all] Error 2

Makefile:146: recipe for target 'all' failed

make: **\* [all] Error 2
`

Where can I find the libneurosim?

**Comment by tammoippen** [comment]
Hi @steffengraber ,

You can find the sources [here](http://software.incf.org/software/libneurosim/code_repository). After installing them, you can give the install path to `with-libneurosim`, if the install dir is not found automatically:

```
... -Dwith-libneurosim=/path/to/installdir/libneurosim ...
```

But you should not get the error... When `cmake` did not find the libneurosim, it should build without it. I will investigate.

**Comment by steffengraber** [comment]
Hi @tammoippen 

works.

Thank you.

**Comment by steffengraber** [comment]
Have you tried `-Dwith-libneurosim=/home/ulianych/PycharmProjects/other/libneurosim/build/`?

**Comment by dizcza** [comment]
> Have you tried `-Dwith-libneurosim=/home/ulianych/PycharmProjects/other/libneurosim/build/`?

Yes, I tried this. No luck.

**Comment by steffengraber** [comment]
That's supposed to work. It does for me.
Can you tell me how you build `libneurosim` and `NEST`? Especially the `configure` line (`libneurosim`) and the `cmake` line (`NEST`).

**Comment by dizcza** [comment]
libneurosim (github master branch):
```
$ ./configure --prefix=/home/ulianych/PycharmProjects/other/libneurosim/build
$ make install -j4
...
Libraries have been installed in:
   /home/ulianych/PycharmProjects/other/libneurosim/build/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'
```

The output of building `libneurosim` suggests using some flags, but I'm not that confident about which ones and how exactly should I use them. I thought `-Dwith-libneurosim` handles it.

NEST (v2.18.0):
```
$ mkdir build; cd build
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=. -Dwith-libneurosim=/home/ulianych/PycharmProjects/other/libneurosim/build ..

--------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Build type          : 
Target System       : Linux
Cross Compiling     : FALSE
C compiler          : /usr/bin/cc
C compiler flags    :  -O2 -Wall -fopenmp -fdiagnostics-color=auto
C++ compiler        : /usr/bin/c++
C++ compiler flags  :  -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto
Build dynamic       : ON

Built-in modules    : models;precise;topology
User modules        : None
Python bindings     : Yes (Python 3.7.3: /home/ulianych/anaconda3/envs/nest-compiled/bin/python)
       Includes     : /home/ulianych/anaconda3/envs/nest-compiled/include/python3.7m
       Libraries    : /home/ulianych/anaconda3/envs/nest-compiled/lib/libpython3.7m.so

Cython bindings     : Yes (Cython 0.29.10: /home/ulianych/anaconda3/envs/nest-compiled/bin/cython)
Use threading       : Yes (OpenMP: -fopenmp)
Use GSL             : Yes (GSL 2.4)
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libgsl.so;/usr/lib/x86_64-linux-gnu/libgslcblas.so

Use Readline        : Yes (GNU Readline 7.0)
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libreadline.so;/usr/lib/x86_64-linux-gnu/libncurses.so

Use libltdl         : Yes (LTDL )
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libltdl.so

Use doxygen         : Yes (/usr/bin/doxygen)
                    : target `doc` available
Use MPI             : No
Use MUSIC           : No
Use libneurosim     : No
Use Boost           : No


```

**Comment by steffengraber** [comment]
hi @dizcza 
in `cmake` you can set the paths explicitly:

```
      -Dwith-libneurosim:BOOL=ON \
      -DNEUROSIM_LIBRARY=$BUILDPATH/install-libneurosim/lib/libneurosim.so.0 \
      -DPYNEUROSIM_LIBRARY=$BUILDPATH/install-libneurosim/lib/libpy3neurosim.so.0 \
      -DLIBNEUROSIM_INCLUDE_DIR=$BUILDPATH/install-libneurosim/include \
```

Here you can find a sample script which installs `NEST` together with `libneurosim`:
https://gist.github.com/steffengraber/c35411829e24f99365792090f595bb05

For the `MPI`-Setup see here: https://nest-simulator.readthedocs.io/en/latest/installation/install_options.html#configuring-nest-for-distributed-simulation-with-mpi

Can you show me the full `cmake` output? Maybe there's a clue to what's going on.

**Comment by steffengraber** [comment]
I have reopened the issue, as the discussion can be of interest to others as well.

**Comment by dizcza** [comment]
But then, during the `make` of NEST,
```
[ 51%] Building CXX object conngen/CMakeFiles/conngen.dir/conngenmodule.cpp.o
In file included from /home/dizcza/PycharmProjects/other/nest-simulator/conngen/conngenmodule.h:30:0,
                 from /home/dizcza/PycharmProjects/other/nest-simulator/conngen/conngenmodule.cpp:23:
/home/dizcza/PycharmProjects/other/nest-simulator/conngen/conngendatum.h:27:10: fatal error: neurosim/connection_generator.h: No such file or directory
 #include <neurosim/connection_generator.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
conngen/CMakeFiles/conngen.dir/build.make:62: recipe for target 'conngen/CMakeFiles/conngen.dir/conngenmodule.cpp.o' failed
make[2]: *** [conngen/CMakeFiles/conngen.dir/conngenmodule.cpp.o] Error 1
CMakeFiles/Makefile2:152: recipe for target 'conngen/CMakeFiles/conngen.dir/all' failed
make[1]: *** [conngen/CMakeFiles/conngen.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
even though I see this file in `$LIBNEURO/include/neurosim/connection_generator.h`
