### ISSUE TITLE
Documentation for recording spike times is obtuse

### ISSUE THREAD

**Issue by WillemWybo** [nest/nest-simulator#3070]
**Describe the flaw**
The main `spike_recorder` [documentation page](https://nest-simulator.readthedocs.io/en/latest/models/spike_recorder.html) doesn't mention that there is an 'events' attribute containing the spike times. I had to click through two times to backends to [find it here](https://nest-simulator.readthedocs.io/en/latest/models/recording_backend_memory.html). 

**Suggest an improvement**
Describe the attribute on the main docs page

**Supporting materials**
[https://nest-simulator.readthedocs.io/en/latest/models/spike_recorder.html](https://nest-simulator.readthedocs.io/en/latest/models/spike_recorder.html)

**Comment by heplesser** [comment]
In context withe readers for our file output, I created some documentation of the file format here:
https://github.com/NeuralEnsemble/python-neo/pull/1097#pullrequestreview-1854562335

It applies correspondingly to the entries of the `events` dictionary and may be useful as a starting point for better documentation.
