### ISSUE TITLE
make installcheck errors for PyNEST Testsuite

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#309]
Hi,

that's it what I did:

```
cmake -DCMAKE_INSTALL_PREFIX=/home/steffen/work/opt/nest 
      -Dwith-optimize=ON 
      -Dwith-warning=ON 
      -Dwith-mpi=OFF 
      -Dwith-python=ON 
      -Dwith-gsl=ON 
      -Dwith-libneurosim=ON
make
make install
make installcheck
```

Everything looks nice, but at the end of the checks:

```
ERROR: One-to-one connectivity with id ranges
  NameError: global name 'GetChildren' is not defined
  ERROR: One-to-one connectivity
  NameError: global name 'GetChildren' is not defined
  ERROR: One-to-one connectivity with 1-dim subnets
  NameError: global name 'GetChildren' is not defined
  ERROR: One-to-one connectivity with n-dim subnets
      self.assertRaisesRegex(nest.NESTError, "BadProperty", nest.CGConnect, pop0, pop1, cg)
  NameError: global name 'GetChildren' is not defined
  ERROR: cgnext
  NESTError: unknown Python type: <class 'csa.connset.ConnectionSet'>
  FAILED (SKIP=6, errors=5)

  PyNEST tests: 524
     Passed: 519
     Failed: 5

NEST Testsuite Summary
----------------------
  NEST Executable: /home/steffen/work/opt/nest/bin/nest
  SLI Executable : /home/steffen/work/opt/nest/bin/sli
  Total number of tests: 732
     Passed: 727
     Failed: 5 (5 PyNEST)
```

Looks like a problem with the libneuronsim. But cmake says:

```
Use libneurosim     : Yes (LibNeurosim 1.0.0)
    Includes        : /usr/local/include
    Libraries       : /usr/local/lib/libneurosim.so;/usr/local/lib/libpyneurosim.so
```

**Comment by heplesser** [comment]
@steffengraber Any news on this one with more recent versions?

**Comment by steffengraber** [comment]
I've tried it with the nest live media, installed the libneurosim and downloaded the newest master. 
The same problems as above.

**Comment by jougs** [comment]
This is related to and fixed by #483. See #206 for a similar problem when using CSA.

**Comment by heplesser** [comment]
@jougs @steffengraber  Can we close this issue in view of @jougs  last comment?

**Comment by jougs** [comment]
I guess not until #483 is merged. I try to work on updating that asap and report back.

**Comment by jougs** [comment]
Fixed by the merge of #483.

**Comment by xdzhangxuejun** [comment]
Hi @steffengraber . Can you give me a linker to download  Libneuronsim.  Thank you very much.

**Comment by jougs** [comment]
https://github.com/INCF/libneurosim

**Comment by xdzhangxuejun** [comment]
Thank you for your help. I have got some trouble when I install  libneuronsim. First, i can't find configure in "libneurosim-master". Second , when i use autoconf to compile the configure.ac failed. It give me information as such:
"configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:4: error: possibly undefined macro: AM_CONFIG_HEADER
configure.ac:5: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:31: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:158: error: possibly undefined macro: AM_PATH_PYTHON
configure.ac:185: error: possibly undefined macro: AC_PROG_LIBTOOL
".I do not know what to do next.






在 2018-06-11 23:31:20，"Jochen Martin Eppler" <notifications@github.com> 写道：


https://github.com/INCF/libneurosim

**Comment by heplesser** [comment]
@xdzhangxuejun Please ask questions about libneurosim in forums for libneurosim, not in the NEST issue tracker. The problems you see look like generic problems with your autotools installation.
