### ISSUE TITLE
Formatting errors in online model documentation

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#310]
Documentation generated for the website from SLI-style docstrings are incorrectly formatted. In particular, it seems that all paragraph breaks and line breaks in bullet list and similarly tabulated text are ignored. This renders the documentation quite illegible, see e.g. the "Parameters" section of  http://www.nest-simulator.org/cc/iaf_psc_alpha/.

@steffengraber Could you take a look at this?

**Comment by steffengraber** [comment]
hi @heplesser 
I have integrated a new version of the command index coming from the SLI-style docstrings. It recognizes now the paragraphs and line breaks. There is still something missing but better readable. More is coming soon.

**Comment by heplesser** [comment]
@steffengraber Has the recent merge of #464 maybe solved this issue?

**Comment by steffengraber** [comment]
Yes, it is solved.
