### ISSUE TITLE
Nest-simulator 3.4 - installation on MAC - sli

### ISSUE THREAD

**Issue by olympiaGallos** [nest/nest-simulator#3131]
**Describe the bug**
I'm trying to install the nest-simulator version 3.4 on my MAC, but I'm getting issues after cmake with sli during installation.

**Screenshots*
<img width="945" alt="Screenshot 2024-03-03 at 13 05 01" src="https://github.com/nest/nest-simulator/assets/44085061/a5da28a3-a852-425b-aa46-6adf7d04d11f">

**Desktop/Environment (please complete the following information):**
 - OS: macOS Sonoma  
 - Shell: [e.g. bash, zsh]
 - Python-Version: python 3.12
 - NEST-Version: nest 3.4 
 - Installation: [e.g. conda packet, apt, with/out MPI, ...]
   (in case you compiled the source code manually, provide the
    "Installation Summary" that you see at the end of the 
    cmake step)
(lab2024) olympiagallou@Olympias-MacBook-Pro nest-simulator-3.4 % 
cmake -DCMAKE_INSTALL_PREFIX:PATH=/Users/olympiagallou/Documents/LAB1_NI2024/nest-simulator-3.4 -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_CXX_COMPILER=g++-13 /Users/olympiagallou/Documents/LAB1_NI2024/nest-simulator-3.4

-- The CXX compiler identification is GNU 13.2.0
-- The C compiler identification is GNU 13.2.0
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/bin/g++-13 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/bin/gcc-13 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file mach-o/dyld.h
-- Looking for include file mach-o/dyld.h - found
-- Looking for include file mach/mach.h
-- Looking for include file mach/mach.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for C++ include istream
-- Looking for C++ include istream - found
-- Looking for C++ include ostream
-- Looking for C++ include ostream - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of u_int64_t
-- Check size of u_int64_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Looking for NAN
-- Looking for NAN - found
-- Looking for isnan
-- Looking for isnan - found
-- Looking for M_E
-- Looking for M_E - found
-- Looking for M_PI
-- Looking for M_PI - found
-- Looking for expm1
-- Looking for expm1 - found
-- Info: Host triple: arm64-apple-darwin 
-- Info: Target triple: arm64-apple-darwin 
-- Found Python: /Users/olympiagallou/anaconda3/envs/lab2024/bin/python3.12 (found suitable version "3.12.2", minimum required is "3.8") found components: Interpreter Development.Module 
-- Found Cython: /Users/olympiagallou/anaconda3/envs/lab2024/bin/cython (found suitable version "3.0.8", minimum required is "0.28.3") 
-- Found LTDL: /opt/homebrew/lib/libltdl.dylib (found version "2.4.7") 
-- Found Readline: /Users/olympiagallou/anaconda3/envs/lab2024/lib/libreadline.dylib (found version "4.2") 
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2") 
-- Found GSL: /opt/homebrew/Cellar/gsl/2.7.1/include (found version "2.7.1") 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR) (Required is at least version "1.69.0")
-- Info: Check the abort exitcode. 
-- Info: Check the abort exitcode. Permission denied 
-- Info: Check the segmentation fault exitcode. 
-- Info: Check the segmentation fault exitcode. Permission denied 
-- Info: Check whether the compiler ignores cmath makros. 
-- Info: Check whether the compiler ignores cmath makros. OFF 
-- Info: Check whether the compiler does NOT include <*.h> headers ISO conformant. 
-- Info: Check whether the compiler does NOT include <*.h> headers ISO conformant. OFF 
-- Info: Check whether the compiler respects symbolic signal names in signal.h. 
-- Info: Check whether the compiler respects symbolic signal names in signal.h. OFF 
-- Info: Check static template member declaration. 
-- Info: Check static template member declaration. OFF 
-- Info: Check for STL vector capacity base unity. 
-- Info: Check for STL vector capacity base unity. ON 
-- Info: Check for STL vector capacity doubling strategy. 
-- Info: Check for STL vector capacity doubling strategy. ON 
-- Info: Check whether the compiler fails with ICE. 
-- Info: Check whether the compiler fails with ICE. OFF 
-- Info: Check if ::nan is available from cmath. 
-- Info: Check if ::nan is available from cmath. ON 
-- Info: Check if ::isnan is available from cmath. 
-- Info: Check if ::isnan is available from cmath. ON 
-- Info: Check if Random123 generators work. 
-- Info: terminate called after throwing an instance of 'std::runtime_error'
  what():  MicroURNG: c0, does not have high bits clear
4 test vectors of type aesni4x32 skipped
3 test vectors of type ars4x32 skipped
Perform 60 tests.
Subprocess aborted 
-- Info: Check if Random123 generators work. OFF 
-- Info: -- NEST version: 3.4 

--------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Target System       : Darwin
Cross Compiling     : FALSE
C compiler          : GNU 13.2.0 (/opt/homebrew/bin/gcc-13)
C compiler flags    :  -Wall -fopenmp -O2 -fdiagnostics-color=auto
C++ compiler        : GNU 13.2.0 (/opt/homebrew/bin/g++-13)
C++ compiler flags  :  -std=c++11 -Wall -fopenmp -O2 -fdiagnostics-color=auto
Build dynamic       : ON

Built-in modules    : models
User modules        : None

Python bindings     : Yes (Python 3.12.2: /Users/olympiagallou/anaconda3/envs/lab2024/bin/python3.12)
    Includes        : /Users/olympiagallou/anaconda3/envs/lab2024/include/python3.12
    Libraries       : 
    Cython          : Yes (Cython 3.0.8: /Users/olympiagallou/anaconda3/envs/lab2024/bin/cython)
    MPI4Py          : No 

Documentation       : No

Use threading       : Yes (OpenMP: -fopenmp)

Use GSL             : Yes (GSL 2.7.1)
    Includes        : /opt/homebrew/Cellar/gsl/2.7.1/include
    Libraries       : /opt/homebrew/Cellar/gsl/2.7.1/lib/libgsl.dylib;/opt/homebrew/Cellar/gsl/2.7.1/lib/libgslcblas.dylib

Use Readline        : Yes (GNU Readline 4.2)
    Includes        : /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/include
    Libraries       : /Users/olympiagallou/anaconda3/envs/lab2024/lib/libreadline.dylib;/Users/olympiagallou/anaconda3/envs/lab2024/lib/libncurses.dylib

Use libltdl         : Yes (LTDL 2.4.7)
    Includes        : /opt/homebrew/include
    Libraries       : /opt/homebrew/lib/libltdl.dylib

Use MPI             : No

Detailed timers     : No

Use MUSIC           : No

Use libneurosim     : No

Use Boost           : No

Use SIONlib         : No

**Comment by heplesser** [comment]
Hello @olympiaGallos!

Thank you for the detailed report. The problem seems to be that some small test programs executed by CMake do not execute properly and then leave garbage in `config.h`. We should probably change CMake to fail if this happens.

To fix  the problem for your case, we need to find out why the test program does not compile or run on your computer. It may be a permissions issue.

The two programs in question are `assert_value.c` and `segfault_value.c` in the `cmake/CheckFiles` directory in the NEST source code directory. Could you try to compile and run them with your C compiler (not C++)? I assume that will work, it is just an extra test.

Then, in an empty build directory run CMake with the extra options `--debug-trycompile --debug-output`. Could you afterwards send me the complete output as well as a compressed version of the entire build directory? Since that may reveal details of your computer, I suggest you send it by email directly to me or a link to a download location (you should find my university email address easily).

**Comment by heplesser** [comment]
After tracing this problem to missing execute permission for `<source_dir>/cmake/CheckFiles/check_return_val.sh` I close this issue as solved.
