### ISSUE TITLE
Make NEST installation independant from source & build directory

### ISSUE THREAD

**Issue by tammoippen** [nest/nest-simulator#314]
In NEST [`config.h`](https://github.com/nest/nest-simulator/blob/master/libnestutil/config.h.in#L45) we set the source and build directory and use it within NEST (`#define NEST_SOURCEDIR "@PKGSRCDIR@"` and `#define NEST_BUILDDIR "@PKGBUILDDIR@"`). When we want to create pre-build binaries for different platforms, e.g. for [OS X](https://github.com/Homebrew/homebrew-science/pull/3331) or for [Debian](https://github.com/nest/nest-simulator/issues/116), we cannot rely on the presence of our sources or build directory. The aim of this issue is to gather all dependancies of the installed NEST on the source / build directory and have them removed. As a start one could remove these two defines, work through all the compile errors and see, if `make installcheck` is still good with NEST.

Errors, I already observe with `installcheck`: with an installed NEST, this should work as expected, but at least two tests will fail, when the sources are not present:

* `regressiontests/ticket-659-copyright.py` as its want to check all sources for correct copyright notice
* `unittests/test_round_validate.sli`: the sli function [`validate`](https://github.com/nest/nest-simulator/blob/master/lib/sli/helpinit.sli#L1472) goes through all the help files and looks for examples, which it executes and compares to the expected result in the example. But, before it [regenerates the help](https://github.com/nest/nest-simulator/blob/master/lib/sli/helpinit.sli#L1504) from the `Source:` file stated in the help file, which will fail when no sources are available.

**Comment by heplesser** [comment]
This was addressed by #318.
