### ISSUE TITLE
Download NEST for working with Python

### ISSUE THREAD

**Issue by Wiss** [nest/nest-simulator#3143]
**Describe the flaw**
I think a lot of people would like to download NEST to use it with Python. However, many users may face difficulty linking NEST to Python after installing it on Ubuntu due to unclear instructions in the installation guide.

**Suggest an improvement**
When installing NEST, the `/bin/nest_vars.sh` containing all the required PATHs for using NEST with Python is installed.
My suggestion is the following: 
In the [installation instructions for downloading NEST ](https://nest-simulator.readthedocs.io/en/stable/installation/user.html#user-install), it would be nice to have an extra note for the ubuntu installation, saying:
**Using NEST with Python:**
After installing NEST, locate the `/bin/nest_vars.sh` file, which contains essential PATHs for Python integration. To use NEST with Python, run the following command:
```bash
source /bin/nest_vars.sh
```  
Alternatively, you can add it to your `.bashrc` file directly:
```bash
echo 'source /bin/nest_vars.sh' >> ~/.bashrc
```
And remember to restart your terminal or run source ~/.bashrc after making changes to apply them.

**Comment by jessica-mitchell** [comment]
Hi @Wiss thanks for your contribution. 

Installing NEST with the conda package or docker should not require you to set the environment variables. This should only be necessary if you are installing NEST from source, and in that case, the documentation does include the instructions: https://nest-simulator.readthedocs.io/en/latest/installation/condaenv_install.html

But perhaps there is some confusion here in the documentation differentiating between the conda package of NEST and installing NEST from source in a conda environment?

Please let us know if you have any further comments or questions.

**Comment by Wiss** [comment]
I understand now. I've been discussing the local installation of NEST on Linux, excluding Docker or Conda setups. It seems I referred to the installation instructions for the stable version of NEST on Linux (the original link I included), rather than those for the latest version (the link you sent). The link you provided offers clear instructions. Unfortunately, the one that I used (for the stable version) its not that clear in my opinion; at least the instruction for setting the environment variables is missing. I realized that when you enter the [download link in NEST webpage](https://www.nest-simulator.org/download/), and then click `user documentation` you arrive to the `stable` version of the documentation. Maybe that's why other people are facing a similar confusion. In fact, I talked with some colleagues about their NEST installation process and they said that they spent more time than expected trying to locate those instructions.

**Comment by jessica-mitchell** [comment]
@Wiss the stable version is tied with the most recent version of NEST whereas latest is tied with master, and is subject to change at any time- so I'm sorry if I confused you there. But I'm glad to hear the most recent changes are clearer. When we release the next version of NEST the stable documentation will be closer to what you see in latest. 

And thanks for sharing your and your colleagues experiences; we are always trying to make the documentation easier to access and understand, and the feedback is very valuable.

**Comment by jessica-mitchell** [comment]
Closing this issue as no further discussion.
