### ISSUE TITLE
did 3.7 get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [nest/nest-simulator#3211]
👋 While [regression testing the 0.3.7 build](https://github.com/Homebrew/homebrew-core/pull/172854), found the checksum got changed? Raise this issue to confirm if there was a re-tagging. Thanks!

**Comment by chenrui333** [comment]
cc @terhorstd

**Comment by terhorstd** [comment]
There was no change in tag since the day of the release.
The correct tar.gz hash is
```
    version('3.7',    sha256='b313e03aa05a0d8053b895a1d14ea42e75805393c6daa0cbc62f9398d0dacd8b')
```
The tag is correct on commit https://github.com/nest/nest-simulator/commit/0b6aea80b83023e8e778587c6a00cd6cce5cb403
