### ISSUE TITLE
izhikevich model has broken equation

### ISSUE THREAD

**Issue by jessica-mitchell** [nest/nest-simulator#3219]
The first equation in the model docs for the izhikevich model does not render due to incorrect syntax

**Comment by PrabhuUdurg** [comment]
Hi, I am new here. Do you mean problem is there https://nest-simulator.readthedocs.io/en/latest/models/izhikevich.html ?

**Comment by jessica-mitchell** [comment]
Hi @PrabhuUdurg, welcome to the NEST Simulator project :)  
Yes, that  is the page I mean; the source file is here: https://github.com/nest/nest-simulator/blob/master/models/izhikevich.h (The equation begins at line 50)
If you are interested in investigating this issue, you'll also need to be able to render the documentation into HTML to check if any fix worked. You can find some info [here](https://nest-simulator.readthedocs.io/en/latest/developer_space/workflows/documentation_workflow/user_documentation_workflow.html) on how to do that.

**Comment by PrabhuUdurg** [comment]
@jessica-mitchell Thank you so much!!! I will work on it.

**Comment by PrabhuUdurg** [comment]
I submitted pull request with solution

**Comment by jessica-mitchell** [comment]
fixed by #3220
