### ISSUE TITLE
Failed to set  `V_m` in `iaf_psc_alpha`

### ISSUE THREAD

**Issue by babsey** [nest/nest-simulator#3248]
**Describe the bug**
In aspect to set initial membrane potential 'V_m' in 'iaf_psc_alpha' model, I registered not expected simulation output.
It remains at value `-70`.

**To Reproduce**
```
import nest
n = nest.Create('iaf_psc_alpha', params={'V_m': 0})
vm = nest.Create('voltmeter')
nest.Connect(vm, n)
nest.Simulate(10)
vm.events
```

The output shows
```
{'senders': array([1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'times': array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 'V_m': array([-70., -70., -70., -70., -70., -70., -70., -70., -70.])}
```

**Expected behavior**
```
{'senders': array([1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'times': array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 'V_m': array([0., 0., 0., 0., 0., 0., 0., 0., 0.])}
```

**Desktop/Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Shell: IPython
 - Python-Version: 3.12
 - NEST-Version: 3.7.0
 - Installation:. conda packet

**Additional context**

**Comment by med-ayssar** [comment]
The `params={'V_m': 0}` is only considered for initialization, and the value emitted by the neuron to the  `voltmeter` is the sum of two others variables.
```cpp
  inline double
  get_V_m_() const
  {
    return S_.y3_ + P_.E_L_;
  }
```
In the update function, `S_.y3` is always zero, and thus you get only the value in `P_.E_L_`, which is `-70`.

**Comment by babsey** [comment]
@med-ayssar my mistake. The V_m is driven by `E_L`. However, the first `V_m` value should be closed to `0` because of the time constant. Please correct me if I am wrong.

**Comment by babsey** [comment]
My mistake again, I should set `V_m` below spike threshold `Vth`. Now I can see initial value of Vm. :+1:
