### ISSUE TITLE
Tests failing for NEST 2.10.0 on MBP

### ISSUE THREAD

**Issue by wvangeit** [nest/nest-simulator#325]
I ran nest.test() from a python prompt, and the tests below failed.
Nest was installed on my MacBook Pro (Retina, 13-inch, Early 2015) using the tarball from the website (configure/make/make install), numpy version was 1.11.0
# 
## FAIL: test_gaussian_growth_curve (nest.tests.test_sp.test_growth_curves.TestGrowthCurve)

Traceback (most recent call last):
  File "/Users/werner/local/nest/lib/python2.7/site-packages/nest/tests/test_sp/test_growth_curves.py", line 345, in test_gaussian_growth_curve
    decimal=5)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 533, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 5 decimals
 ACTUAL: 0.10048801003551636
 DESIRED: 0.10044035
# 
## FAIL: test_linear_growth_curve (nest.tests.test_sp.test_growth_curves.TestGrowthCurve)

Traceback (most recent call last):
  File "/Users/werner/local/nest/lib/python2.7/site-packages/nest/tests/test_sp/test_growth_curves.py", line 319, in test_linear_growth_curve
    decimal=8)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 533, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 8 decimals
 ACTUAL: 0.083736047058004096
 DESIRED: 0.083762630000000005

---

Ran 220 tests in 38.241s

FAILED (failures=2, skipped=9)

**Comment by tammoippen** [comment]
Hallo @wvangeit 

What compiler did you use? The gcc/clang from xcode/apple? If yes, NEST is unstable with this compiler, see #74. Please use a GCC from homebrew/macports/fink for building NEST and follow the instructions [here](http://www.nest-simulator.org/installation/) at "mac os x".

**Comment by wvangeit** [comment]
It seems nest used the /usr/bin/gcc compiler (clang) for the compilation. Now forced the use of the /usr/local/bin/gcc-5 compiler (homebrew).
Did a clean install (removed build directory, and installation directory).
Still get exactly the same results. Have attached the config.log

[config.log.zip](https://github.com/nest/nest-simulator/files/241910/config.log.zip)

**Comment by heplesser** [comment]
@wvangeit Could you check if you still have this problem with the current master version from Github? I am also using Mac, and the tests work for me. Do you have any special numerical libraries installed that would replace glibc math functions such as `exp()`? I the problem has dissappeared, would you close the issue?

**Comment by wvangeit** [comment]
@heplesser sure, will look at this in the coming week

**Comment by wvangeit** [comment]
@heplesser I tried to install from the master using CMake. However, it seems that for some reason it doesn't install the Python module. (At least the import fails after I execute the nest_vars.sh script). 
I'm also getting failed tests when running 'make test'. I've attached the log and the build script.
(I don't have any special math libraries installed that I know of)
Am running on Mac OS Sierra now.
Cheers.

[scripts.zip](https://github.com/nest/nest-simulator/files/642395/scripts.zip)

**Comment by heplesser** [comment]
@wvangeit There are unfortunately some problems on Mac, see #74 (related to the failing tests) and #484 (Python problems). Your log shows that CMake gets confused by a mix of 2.7.10 and 2.7.12.

@henriklinden recently provided a description for installing under macOS 10.12, see https://github.com/nest/nest-simulator/issues/484#issuecomment-258427350 .

Updating the installation instructions for Mac is high on my todo list.

**Comment by heplesser** [comment]
Closing as we now have released NEST 2.12.0.
