### ISSUE TITLE
spike_detector --> spike_recorder

### ISSUE THREAD

**Issue by ErbB4** [nest/nest-simulator#3298]
**Describe the flaw**
Hi there, I am running NEST code again recently. I found the name spike_detector has been changed to spike_recorder. Some of the cod pieces in the documentation haven't been updated yet.

**Suggest an improvement**
A quick fix might be helpful to new and old users hehe.

**Supporting materials**
Like here: https://www.nest-simulator.org/py_sample/hh_psc_alpha/

**Desktop/Environment**
Doesn't apply but I am using NEST 3.7 

**Additional context**
NA.

**Comment by terhorstd** [comment]
Interesting you found this, it seems there are still ancient files on the server. The current documentation can always be found on https://nest-simulator.org/documentation and you have a little switch button at the bottom right to select the documentation for the exact version you are using.

We will delete the old files, so they are not found by search engines anymore.
Thanks for noticing. :+1:

**Comment by terhorstd** [comment]
Additionally, for users that have not looked into nest for a while we prepare a [What's new](https://nest-simulator.readthedocs.io/en/stable/whats_new/index.html) guide for each release, and we have a generic [Transition Guide](https://nest-simulator.readthedocs.io/en/stable/whats_new/v3.0/refguide_nest2_nest3.html#refguide-2-3) when coming from 2.x releases.

**Comment by ErbB4** [comment]
Thank you Dennis! Yes, I was digging around and found it randomly.
