### ISSUE TITLE
Refractoriness causes output spikes being dropped in hh_cond_exp_traub

### ISSUE THREAD

**Issue by astoeckel** [nest/nest-simulator#330]
The constant 2ms refractoriness in the `hh_cond_exp_traub` model causes output spikes to be discarded once the output inter-spike-interval drops below 2ms.

For example, this simulation [1] results in the following voltage trace
![nest_hh_trace](https://cloud.githubusercontent.com/assets/1783545/14955622/82ec818c-107b-11e6-9046-ccb176126501.png)
where spikes are produced with approximately an 2ms ISI, causing the spike at 209ms (the second from the right) to be skipped in the output.

As already suggested in #329, the refractoriness condition in `hh_cond_exp_traub.cpp` should not be time based, but voltage based.

[1] https://github.com/hbp-sanncs/cinder/blob/f0c3f62f2fc8917139114fd0d85853c6e985a599/test/models/neurons/test_hodgkin_huxley_pynn.py

**Comment by heplesser** [comment]
@astoeckel Thank you for reporting this. While it is a slightly different issue than #329, both issues are closely related as they expose weaknesses in the current implementation of the Traub model in NEST. I would suggest that we combine the two issues and have all further discussion in #329.

**Comment by heplesser** [comment]
See also #473 .

**Comment by terhorstd** [comment]
discussion moved to #329.
