### ISSUE TITLE
Eliminate duplicity between build.sh and check_code_style.sh

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#338]
Currently, developers use `check_code_style.sh` to check style compliance on their own computers, while Travis checks style compliance with different code in `build.sh`. This risks that checks differ. `build.sh` should use `check_code_style.sh`, or both should use the same helper script to do the work.

We should also consider to terminate building if the style check fails for faster turn-around and lower Travis load.

**Comment by jougs** [comment]
This was fixed by #546 and #789.
