### ISSUE TITLE
NEST simulation time limited to 59 hours, change communication from uint_t to ulong_t?

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#346]
NEST can currently not simulate for more than 59 hours, since all communication of time stamps between MPI processes is done using the `uint_t` data type, which is 32 bit even on (many) 64 bit systems. 

Even when not using MPI, simulation running to more than 1.1e9 ms will trigger an assertion in `Scheduler::advance_time_()`, when steps (type `long_t`) and delays (type `uint_t`) are compared in a dangerous way. Alexander reported a seg fault in a very long running simulation recently, which most likely was a result of a mix-up created in `slice_ring_buffer` due `delay` being `uint_t`.

So I would propose to change `delay` to `ulong_t` and to use `ulong_t` for all MPI communication of spike times. Obviously, this would double the bandwidth demands on communication, so I would like to ask for your input on this before making the change. 

I marked this ticket as "critical" because all hell may break loose in an MPI simulation running to more than 59 hours.

An easy way out would be to limit all simulations to at most 2^31-1 steps.

@apeyser added two years ago:
Currently, Time is limited by the tic_t type, which is long or long long depending on availability, and the step type which is a long_t, which is a long. Bit fixed types such as int64_t would be much better here. If the only reason for the macro check is earlier lack of stdint.h on some platforms, then I'll put that in the Time class before it gets checked in.

Also, the division by 8 is larger than needed. Addition can give only a 1 bit extension, and if you need to allocate MAX and MIN bit patterns, that would give you cases where you could get a two bit overflow. Any other cases come to mind? More problematic operations are too problematic without having a int128_t guaranteed to be available, or limiting operations to 53 bits so that you could use lossless double operations, which is a much more severe reduction.

This was known as trac408.

**Comment by heplesser** [comment]
Leave 59 hour limit for now, but add overflow check.

**Comment by clinssen** [comment]
@jougs: just a small clarification question: what exactly is the data that is being put into the uint_t field—is it the tic count, or the delay steps? The maximum value of a signed 32-bit int is 2**32-1, which would imply a maximum simulation time of (2**32-1)/60/60/1E4 = 119 hours, whereas if the data type is signed (32-bit int_t), it would come out as half that, i.e. 59 hours. This is assuming 1E4 delay steps per second.

**Comment by jougs** [comment]
I'm closing this now as it is more than stale. We can re-open it in case anyone ever complains. RIP.
