### ISSUE TITLE
 Write tests for the MUSIC interface 

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#347]
Currently, MUSIC is not covered by any tests. This should be changed.

**Comment by weidel-p** [comment]
We could start by including MUSIC in the Travis CI test matrix. As MUSIC is based on MPI, it only makes sense to compile and test NEST with MUSIC for cases including MPI. 
I know our time on Travis is limited and I'm not sure if we can afford compiling and testing MUSIC in the given time. Did someone think about (or test) that already?

To test the functionality of MUSIC we could convert the MUSIC examples to Python tests.

**Comment by heplesser** [comment]
One aspect to test is whether MUSIC respects spike multiplicity, i.e., whether the MUSIC out proxy generates n spikes when receiving a SpikeEvent with multiplicity n.

**Comment by jougs** [comment]
@weidel-p: with #409 merged, the build time is not a big problem anymore and adding MUSIC to the maximal job is high on my agenda. You're welcome to help!

Basically we need three things in place for this:
- Installation of MUSIC in Travis and addition of the corresponding flags to the configuration (easy)
- A test harness to run jobs via the `music` launcher (medium)
- Tests!

I'm also adding @mdjurfeldt, so he is aware of this.

**Comment by jougs** [comment]
This was fixed by the merge of https://github.com/nest/nest-simulator/pull/471. I'm thus closing.
