### ISSUE TITLE
 Improve tests for randomized generators 

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#348]
- From `manualtests`, `test_sinusoidal_poisson_generator_{5,6}.sli` should be made to work as automated MPI tests.
- We currently have no tests of the statistical properties of spike trains generated by randomized generators. That should be fixed.

**Comment by hakonsbm** [comment]
As these points are pretty different tasks, I am creating a PR regarding your first point, and I have created a separate issue, #773, for your second point.

**Comment by heplesser** [comment]
I am closing this one since follow-up issues have been created, and part of the issue has been addressed.
