### ISSUE TITLE
Run test_connect_all_patterns.py with mpirun

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#353]
The test pynest/nest/tests/test_connect_all_patterns.py is explicitly written to be run MPI parallel (i.e. using `mpirun -np 2 python test_connect_all_patterns.py`). The testsuite does not allow this at the moment. The task is to modify the testsuite harness to allow this.

See also #302.

**Comment by heplesser** [comment]
@hakonsbm Could you take a look at this one? It may be related to the work you did on #302.

**Comment by hakonsbm** [comment]
I'll take a look.
