### ISSUE TITLE
Review and clean up classes for handling of ranges of gids

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#355]
Over time, we have grown quite a zoo of different ways to handle boring lists of nodes, i.e. those containing only a bunch of contiguous sorted GIDs. The main motivation has always been to save memory when e.g. representing the GIDs 1 to 10,000 in a call to a `Connect` function.

This ticket collects all approaches related to this attempt and tries to put them in a historic perspective. The task for this ticket is to review the current implementations and if possible combine the different approaches into a common class for a compressed representation of lists of GIDs.
### IteratorDatum

The first implementation for this purpose was added in r9324 and r9325 under the name `IteratorDatum`. This version of the solution was never really used, as none of the SLI functions implemented in C++ supported it. Support for it was, however, added to the function `Map` and the new function `RangeIterator`.
### Range finding algorithm

As part of r9384 an algorithm to find contiguous ranges in monotonically increasing lists was added (see `conngen` module). Internally, the ranges were stored as closed intervals to be used as masks in the ConnectionGenerator interface. The algorithm was meant to be generic enough to be reused in other parts of NEST. Its code was moved from the NestModule to the new file `connect_cg.cpp` in r9847 and actually made working in r9848 and documented in r10581.
### Multirange

The `Multirange` committed in r9801 by Håkon Enger was not written with a usage on the SLI level in mind, but to allow a compressed representation of the remote nodes in `subnets` to allow a full retrieval of nodes without the need for MPI communication.
### GIDCollection

To ease the handling of GIDs in the NewConnect framework and allow to have a unified interface for all variants, r11059 added the `GIDCollection`, which is (unknowingly at that time) very similar to the `Multirange`.

This was trac897.

**Comment by heplesser** [comment]
Proper support for iterating and slicing over GIDCollections will be provided by the PR addressing #455. A prototype exists, a PR should be ready soon. I keep this issue alive as it indicates some code that is superfluous and can be removed once #455 is fixed.

**Comment by jougs** [comment]
@stinebuu, @hakonsbm: this is the issue I was talking about the other day. Can you please comment on what is fixed by your recent work on `GIDCollections`? If most of these things are fixed, we could finally close this long-standing issue.

It could also be good to revisit  #455 and comment there on what's actually still missing.

Thanks a lot!

**Comment by hakonsbm** [comment]
`GIDCollections` should indeed be able to replace the functionality of these things now.

- It has its own iterator, replacing the functionality of `IteratorDatum` for GIDs.
- `GIDCollections` are already used in the conngen module. And with the recent enhancements to it, `GIDCollection` stores the GIDs in contiguous ranges.
- `GIDCollections` completely replace the usage of `Multirange`.

**Comment by jougs** [comment]
I've removed the obsolete `multirange` class from the repository in 181e7b5b0.

**Comment by jougs** [comment]
The `IteratorDatum` was removed in 60c273738e4573047 and a7d1b1809285a96 together with all pertaining classes and functions.

With this removal, I consider this issue fixed and thus close it.
