### ISSUE TITLE
Remove all uses of FindConnections

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#360]
`FindConnections` has long been deprecated, but is still used in some 70 places in NEST. It has to be replaced by `GetConnections` everywhere and removed.

**Comment by jakobj** [comment]
I think this is partly addresses by #221 (we removed the pynest FindConnections function). Should we make sure to remove all references to FindConnections in that PR or wait until the merge and create a new one?

**Comment by jougs** [comment]
Cool! You can just do this in the aforementioned PR. I'll happily review it then. Many thanks.

**Comment by heplesser** [comment]
@jougs #221 started out as a bug fix and has grown steadily; it has now been pending for four months. I think I would not burden it with even more things to do. Could you look it over and merge, assuming you are happy? Then @jakobj can work on this issue with #221 already merged.

**Comment by jougs** [comment]
Solved by #221.
