### ISSUE TITLE
Extend the help extractor to understand conditional compilation

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#363]
Currently, the help extractor reads all source files and extracts the documentation, no matter if the function is enclosed in a #ifdef block or not. This means that the helpdesk may contain documentation for functions or models that have not been compiled, which frequently confuses users.

This is a follow-up to trac 713.

**Comment by steffengraber** [comment]
Please label this with 'documentation'.

**Comment by steffengraber** [comment]
This is solved with pr #464.

The help generator adds a new "Require:" section to the documentation.

**Comment by heplesser** [comment]
@steffengraber Ok, would you then close the issue?!
