### ISSUE TITLE
Connect does not accept any iterable (e.g. numpy.array)

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#369]
The following code should (IMO) work with nest:

``` python
import numpy as np
import nest
num_neurons = 1000
gids = np.array(nest.Create("aeif_cond_alpha", num_neurons))
sd = nest.Create('spike_detector')
nest.Connect(gids, sd)
```

However, it does not: `nest.Connect(gids.tolist(), sd)` is instead required. Furthermore, the error message is `pynestkernel.NESTError: ArgumentType in Connect: The type of the second parameter did not match the argument(s) of this function.` which confuses people seeing it for the first time.

I think adding a conversion for any iterable to a list in [hl_api_connections.py](https://github.com/nest/nest-simulator/blob/master/pynest/nest/lib/hl_api_connections.py#L615) just before `sps(pre)` should be enough, e.g.

``` python
pre = [ i for i in pre ]
post = [ i for i in post ]
```

Of course it might be better if any iterable could be passed to SLI...

**Comment by heplesser** [comment]
@Silmathoron You are basically right, and we are working on it, especially @jougs. Some time ago, we introduced `GidCollections`, which represent sequences of GIDs in compact form, so that the `Create()` call could return a very compact representation of the GIDs created instead of a full list. In Python, `GidCollections` will behave like iterables, and any functions currently expecting lists of GIDs should then accept any (or at least a sensible range of) iterables. We just haven't gotten around to putting it all in place yet.

**Comment by Silmathoron** [comment]
Ok, thanks, it's just that since it came up several times in the mailing list and I wasn't seeing anything on the issue tracker, I wanted to make sure everybody knew about it. Good luck with the update!

**Comment by heplesser** [comment]
This can be addressed as an add-on once #455 is fixed.

**Comment by jougs** [comment]
@hakonsbm: Is the requested behavior possible (even with an explicit conversion to a GIDCollection) with the current code in [our branch](https://github.com/compneuronmbu/nest-simulator/tree/fix-481-SubnetFreeTopology)? If yes, can you please close this? Thanks!

**Comment by hakonsbm** [comment]
@jougs Didn't we decide that `Create` should only take `GIDCollection`s as input? It is possible, however, to create  `GIDCollections` from both lists and Numpy arrays using `nest.GIDCollection(gid_list_or_array)`.

Also, I don't have the right authorization to close issues I haven't created.

**Comment by jougs** [comment]
Thanks for the heads up. I also seem to remember that we decided to only support `GIDCollection`s in calls to `Connect`. The explicit conversion to those also makes sure the nodes actually exist, which is a good thing. In summary, I consider this issue fixed and thus close it.

**Comment by Silmathoron** [comment]
Hey, sorry to break the mood but I am not in favour of this ;P
Forcing the user to convert to ``GIDCollection``s will add a reason why some old codes will break + it forces the user to add a line.
I thik it would be much better to allow any iterator, then convert it inside ``Connect``. It is still safe but more universal.

**Comment by heplesser** [comment]
@Silmathoron This change will be part of NEST3, which will come with a considerable number of UI changes, so users will need to fix code anyways.
