### ISSUE TITLE
Create iaf_psc_alpha_ps

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#370]
We currently have models `iaf_psc_exp_ps` and `iaf_psc_delta_ps`, which are direct precise equivalents of their normal counterparts. Create `iaf_psc_alpha_ps` as direct counterpart to `iaf_psc_alpha`. Currently, we only have `iaf_psc_alpha_canon`, which only has a single synaptic time constant, while `iaf_psc_alpha` has different time constants for E and I synapses. The `_canon` and `_presc` models are counterparts to `iaf_neuron`, not `iaf_psc_alpha`.

**Comment by Silmathoron** [comment]
It's in my [PR](https://github.com/nest/nest-simulator/pull/229), but it's a GSL version...

**Comment by heplesser** [comment]
Since #229 was not merged, we are still lacking these models. See also #368 .

**Comment by Silmathoron** [comment]
Right x)
I completely forgot that... but I guess we should discuss the implementation anyway... I'm usually in favor of GSL but maybe this model is solvable exactly and should be implemented differently...

Btw @heplesser, is there a document somewhere explaining the new labels? The "C", "I", P" letters are not very explicit to me...

**Comment by heplesser** [comment]
@Silmathoron I will post an explanation of the labels on the Wiki shortly. C: Component, I: Interface, P: Progress, S: Severity, T: Type. The main point of having these letters in front is to make sure that the labels for the different "dimensions" always are in the same (alphabetical) order.

**Comment by heplesser** [comment]
@Silmathoron Any news on this?

**Comment by heplesser** [comment]
@Silmathoron Ping!

**Comment by Silmathoron** [comment]
@heplesser I assume this means that we go for the GSL version then ;) I'll try to do that tomorrow

**Comment by Silmathoron** [comment]
Ok, I ended up wasting my day and actually did the propagator version... cheers!

**Comment by stinebuu** [comment]
Fixed by #1169.
