### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#375]
The [installation instructions on nest-simulator.org](http://www.nest-simulator.org/installation/) are \ outdated or about to become outdated (CMake transition) and lack a table of contents, so that it, e.g., would be clear that OSX instructions come further down on the page.

The page should be revised completely.

**Comment by heplesser** [comment]
@steffengraber As a first step, could you add the following right at the beginning of the installing on OSX section:

The easiest way to install NEST on a Mac is to install it via the Homebrew package manager:

1. To install homebrew, follow the instructions here: http://brew.sh/
1. Then, in a terminal
    1. Add the homebrew/science tap: execute `brew tap homebrew/science`
    1. For information on what options NEST has and what will be installed, execute `brew info nest`
    1. To install nest, execute `brew install nest`

Options have to be appended, e.g. to install NEST with PyNEST execute `brew install nest --with-python`.

And then mark the entire rest as outdated (but may be keep it there). In a next step, we can then write more detailed up-to-date instructions for installation on OSX. An important point is that Clang and NEST currently clash, see #74.

**Comment by steffengraber** [comment]
@heplesser 
I have added the text into the website and grayed the following text about OSX. 
http://www.nest-simulator.org/installation/

and integrate it in my pull request #371
