### ISSUE TITLE
Importing NEST into Python modifies sys.argv 

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#377]
Importing NEST into Python modifies the content of `sys.argv`. It does not matter whether NEST is imported before or after `sys`.

To reproduce, save the following code into a file:
```
import sys
print "Before:", sys.argv
import nest
print "After :", sys.argv
```
Then run with varying number of command line arguments, e.g.:
```
python st.py A
Before: ['st.py', 'A']
After : ['pynest', 'A']   # (almost) OK

python st.py A B
Before: ['st.py', 'A', 'B']
After : ['pynest', 'A', 'B']  # (almost) OK

python st.py A B C
Before: ['st.py', 'A', 'B', 'C']
After : ['pynest', 'C', 'C', 'C']  # BAD

python st.py A B C D
Before: ['st.py', 'A', 'B', 'C', 'D']
After : ['pynest', 'C', 'D', 'C', 'D']  # BAD
```

Note that the first entry is changed (`pynest` instead of `st.py`) and, for more than two command line arguments, also subsequent arguments.

This bug is **not** present in 2.8.0.

**Comment by heplesser** [comment]
This was probably introduced by db73559, see also issue #163 and PR #164.

@apeyser and @mdjurfeldt : You wrote or reviewed the PR, could you take a look? I am wondering how to write a good, automatic test for this.

**Comment by apeyser** [comment]
@heplesser 
Does this happen with and without MUSIC, only with MUSIC or only without MUSIC? And how was this found --- does someone have a particular problem arising from this?

**Comment by heplesser** [comment]
@apeyser I have only tested this without MUSIC. I noticed the problem when running a Python script that receives simulation parameters on the command line, see the toy example below. The problem is that this script will see the modified command line arguments unless I move `import nest` after the point where I read out the command line arguments. Scripts should not depend on such ordering

 ```
import nest
import sys

rate = float(sys.argv[1])
weight = float(sys.argv[2])
seed = int(sys.argv[3])

print rate, weight, seed

nest.ResetKernel()
nest.SetKernelStatus({'grng_seed': seed, 'rng_seeds': [seed+1]})
pg = nest.Create('poisson_generator', params={'rate': rate})
nrn = nest.Create('iaf_psc_alpha')
sd = nest.Create('spike_detector')
nest.Connect(pg, nrn, syn_spec={'weight': weight})
nest.Connect(nrn, sd)

nest.Simulate(1000)

print nest.GetStatus(sd, 'n_events')[0]
```

**Comment by apeyser** [comment]
Command line parameters have been liable to corruption since pynest was written. The exact symptoms depend on python version, cython version and compiler. 

Pull #393 should fix it.
