### ISSUE TITLE
Feature request: Script for checking coding style compliance

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#38]
The C++ code style guidelines suggest running three tools (clang-format, vera++, cppcheck) to verify code formatting. The build.sh for Travis script can run these automatically (although there seems to be some trouble).

I would very much appreciate a small script that I could use myself locally to run all code style checks in one go, something like `check_code_style.sh`.

@tammoippen you are maybe the ideal candidate to implement this?

**Comment by tammoippen** [comment]
The script is merged: #95 #96 
Hence closing this issue.
