### ISSUE TITLE
PDF Tutorial and IPython Notebook based examples

### ISSUE THREAD

**Issue by zuoxingdong** [nest/nest-simulator#394]
Is there a possibility to maintain a set of PDFs of the tutorials (i.e. Introduction to PyNest on the web) for easier update and review. 

In addition, it might be very interesting to have IPython notebooks of either exercises to practice basic usage of NEST or examples of networks both with usage of APIs and corresponding visualizations.

**Comment by abigailm** [comment]
The tutorials are here: http://www.nest-simulator.org/introduction-to-pynest/
They have some formatting errors which we will take care of soon.
