### ISSUE TITLE
Dynamic normalization of activity

### ISSUE THREAD

**Issue by ManuNeuro** [nest/nest-simulator#396]
Hi everyone,

I'm new in the nest developpement, and I had questions about how to develop neuron models.

Following Abigail advise in a thread to the mailing list, I'm posting my issue here, hopping that you could help me !
http://mail.nest-initiative.org/cgi-bin/mailman/private/nest_user/2016/004678.html

So, I'd like to implement a dynamic normalization over activity, the principle is the following one : 
Implementation of a saturation function, which ponder the membrane potential
by dividing it, the saruation function is an exponential decay of time, and is incremented each time a spikes is received within a dynamical time window dependent of a given time constant

In practise, this saturation function s(t), named Sat is defined by the following
differential equation :

dSat/dt = - Sat/tau_N,

When a spike arrives, Sat is incremented by S_i constant (1 by default),
so that :

Sat = Sat + S_i, 

s(t) is then clipped between 1 and S_Max value, Smax being by default
enoughly high to have no impact on s(t)

So, I've implemented that in Spiking NN simulator 'brian2', because it's more easy to implement our own equations, testing the behavior with a simple network of 3 inputs neurons which project to one target neuron, results are given with S_i = 0 (No normalization) and S_i = 1 (Default normalization)
https://drive.google.com/folderview?id=0B3TC7CjK55RDYVlqYklqQmYyVlE&usp=drive_web

##########################
So, now I've tried to implement that on a neuron model, It compiled without problem, but it apparently doesn't work when I tested it, since I can't see any no noticeable change ...

So, voilà, I've created a struct State, so that I have all the state variable contained in my object State S_, and the same for parameters P_, internal variable V_, and buffer B_.

So first thing is the creation of my new variables and parameters... 
trying to be consistent with how things seems to work, I've created a new internal variable which I call P00_

NB : each modification I've done on the model is marked by a #ADD comment.

(mymodel.h)
```
struct Variables_
  {
    /** Amplitude of the synaptic current.
              This value is chosen such that a post-synaptic potential with
              weight one has an amplitude of 1 mV.
     */
	  nest::double_t PSCInitialValue_;
	  nest::int_t RefractoryCounts_; //!< refractory time in steps

	  nest::double_t P11_;
	  nest::double_t P21_;
	  nest::double_t P22_;
	  nest::double_t P31_;
	  nest::double_t P32_;
	  nest::double_t P30_;
	  nest::double_t P33_;
	  nest::double_t P00_; // #ADD

	  librandom::PoissonRandomDev poisson_dev_; //!< Random deviate generator
  };

```

Then adding a new State variable, s0 : 

(mymodel.h)
```
  struct State_
  {
	  nest::double_t y0_; //!< Constant current
	  nest::double_t y1_;
          nest::double_t y1_;	  
          nest::double_t y2_;
	  nest::double_t y3_; //!< This is the membrane potential RELATIVE TO RESTING POTENTIAL
	  nest::double_t s0_; // Saturation variable, for normalization #ADD
	  nest::double_t rate_;
	  nest::long_t 	 rate_n_;
	  nest::double_t t_rate_ref_;
	  nest::double_t t_lastspike_;


    nest::int_t r_; //!< number of refractory steps remaining

    State_(); //!< Default initialization

    void get( DictionaryDatum&, const Parameters_& ) const;

    /** Set values from dictionary.
     * @param dictionary to take data from
     * @param current parameters
     * @param Change in reversal potential E_L specified by this dict
     */
    void set( const DictionaryDatum&, const Parameters_&, double );
  };

```
After that, I think I have to use the calibrate() function to define the equation of s0 :

(mymodel.cpp)
```

mynest::niaf_neuron::calibrate()
{
  B_.logger_.init();

  const double h = nest::Time::get_resolution().get_ms();

  // these P are independent
  V_.P11_ = V_.P22_ = std::exp( -h / P_.tau_syn_ );
  V_.P33_ = std::exp( -h / P_.Tau_ );
  V_.P21_ = h * V_.P11_;
  V_.P00_ = std::exp( - h / P_.tauN_); // #ADD	 	
[...]
}
```
Is it okay to define my variable like that ?

Then, come the update() function

(mymodel.cpp)

```
void
mynest::niaf_neuron::update( nest::Time const& origin, const nest::long_t from, const nest::long_t to )
{
  assert( to >= 0 && ( nest::delay ) from < nest::Scheduler::get_min_delay() );
  assert( from < to );

  for ( nest::long_t lag = from; lag < to; ++lag )
  {
    if ( S_.r_ == 0 )
    {
      // neuron not refractory
      S_.y3_ =
        V_.P30_ * ( S_.y0_ + P_.I_e_ ) + V_.P31_ * S_.y1_ + V_.P32_ * S_.y2_ + V_.P33_ * S_.y3_;
      S_.y3_ /= clip(S_.s0_, P_.SMin_, P_.SMax_); // Normalize over saturation function #ADD
[...]
```
Is it correct to modify the y3 membrane potential here ? 

Here I'm using a clip function defined as followed : (SMin >= 1, SMax > Smin)
```
template <typename T>
T clip(const T& n, const T& lower, const T& upper) {
  return std::max(lower, std::min(n, upper));
}
```

```
[...]
     }
    else // neuron is absolute refractory
      --S_.r_;
	
    // saturation function
    S_.s0_ = V_.P00_; // #ADD
```
Here,  is it correct to define s0 like that ?
```
    // alpha shape PSCs
    S_.y2_ = V_.P21_ * S_.y1_ + V_.P22_ * S_.y2_;
    S_.y1_ *= V_.P11_;

    // Apply spikes delivered in this step: The spikes arriving at T+1 have an
    // immediate effect on the state of the neuron
    S_.y1_ += V_.PSCInitialValue_ * B_.spikes_.get_value( lag );
    
    S_.s0_ += P_.S_i_; // When spike arrives, increment Sat by S_i #ADD
[...]
```
I'm not sure if it's correct, and if the saturation function is really updated when a spike occures ?	
```
[...]
    // threshold crossing
    if ( S_.y3_ >= P_.Theta_ )
    {
      S_.r_ = V_.RefractoryCounts_;
      S_.y3_ = P_.V_reset_;

	  // A supra-threshold membrane potential should never be observable.
	  // The reset at the time of threshold crossing enables accurate integration
	  // independent of the computation step size, see [2,3] for details.

      nest::Time t_spike = nest::Time::step( origin.get_steps() + lag + 1 );
      update_rate(t_spike.get_ms());
      set_spiketime( t_spike );
	  nest::SpikeEvent se;
	  network()->send( *this, se, lag );
    }
```

Thanks you for your help,

Emmanuel

**Comment by heplesser** [comment]
@ManuNeuro 
- ` S_.s0_ = V_.P00_;` should be ` S_.s0_ *= V_.P00_;` to implement the exponential decay of the saturation variable.
- Spike input is handled incorrectly:

    ```
    S_.y1_ += V_.PSCInitialValue_ * B_.spikes_.get_value( lag );
    S_.s0_ += P_.S_i_; // When spike arrives, increment Sat by S_i #ADD
    ```

   These lines are executed during every update step, so you hike `S_.s0_` on each step, independent on whether a spike has arrived or not. What you probably want is 

    ```
    S_.s0_ += P_.S_i_ * B_.unweighted_spikes_.get_value( lag );
    ```

    where `unweighted_spikes_` is a ring buffer like `spikes_`,  except that spikes are not multiplied by    the connection weight when they are registered. If you want to handle incoming excitatory and inhibitory spikes separately, you will need two such buffers, one for spikes with positive and one for spikes with negative weight.
- Normalization is incorrect

    ```
    S_.y3_ /= clip(S_.s0_, P_.SMin_, P_.SMax_); 
    ```

    This line will be executed on every time step. Assume membrane potential is 10 and s0 2, those values do not change and clipping plays no role, then you would have membrane potentials 10, 5, 2.5, 1.25, ... in subsequent time steps. I think that is not what you want. Furthermore, if you change the length of the time step, this would change how fast membrane potential drops and that must be incorrect. I think you need to think again about how, precisely, you want to apply normalization. If you want to normalize the effect of input on the neuron, then you should rather normalize arriving input:

    ```
    S_.y1_ += V_.PSCInitialValue_ / S_.s0_ * B_.spikes_.get_value( lag );
    ```

**Comment by ManuNeuro** [comment]
Okay, first, thank you very much, this helped a lot, 

Indeed I want to apply normalization to input spikes.

So now that I understand better, I created separated buffer like that : 

```
  struct Buffers_
  {
[...]
	nest::RingBuffer ex_spikes_; // #ADD
	nest::RingBuffer in_spikes_; // #ADD
        nest::RingBuffer ex_unweighted_spikes_; // #ADD
        nest::RingBuffer in_unweighted_spikes_; // #ADD
        nest::RingBuffer currents_;
[...]
```

So according to the iaf_psc_alpha model, 
https://github.com/nest/nest-simulator/blob/7537a6b68a693eefe375176e2eac31276f08ee77/models/iaf_psc_alpha.cpp

I've implemented the buffers in handle() like that : 

```
void
mynest::niaf_neuron::handle( nest::SpikeEvent& e )
{
// unweighted_spikes is a buffer which counts the number of arriving spikes #ADD
// In order to normalize we have to separate excitatory and inhibitory spikes

  assert( e.get_delay() > 0.0 );
  
  const double_t w = e.get_weight() 
  const double_t m = e.get_multiplicity();
  
  if ( e.get_weight() > 0.0 ){
    B_.ex_spikes_.add_value( e.get_rel_delivery_steps( network()->get_slice_origin() ),
      w * m );  
    B_.ex_unweighted_spikes_.add_value( e.get_rel_delivery_steps( network()->get_slice_origin() ),
      m );  
  }
  else{
    B_.in_spikes_.add_value( e.get_rel_delivery_steps( network()->get_slice_origin() ),
      w * m );  
    B_.in_unweighted_spikes_.add_value( e.get_rel_delivery_steps( network()->get_slice_origin() ),
      m );   	
  }


}
```
Since y1_ is my input, I also created two state variable y1_ex_ and y1_in_, and so i have tsaturation functions,  s0_ and s1_ to control excitatory and inhibitory input
with two internal variables P00_ and P01, which I implement like before in calibrate()

```
  V_.P01_ = std::exp( -h / P_.tauN_ ); // #ADD
  V_.P00_ = std::exp( -h / P_.tauN_ ); // #ADD
```

So now in update, my two saturation functions are implemented like you told me :

```
    // saturation functions, excitatory and inhibitory 
    S_.s1_ *= V_.P01_; // #ADD
    S_.s0_ *= V_.P00_; // #ADD
```
 
And now I normalized my excitatory and inhibitory input sikes separatly, and then sum it.
```

    // When inhibitory spike occurs, increment inhibitory saturation function
	S_.s1_ += P_.S_i_* B_.in_unweighted_spikes_.get_value( lag ); // #ADD
	S_.y1_in_ = V_.PSCInitialValue_ / S_.s1 *    B_.in_spikes_.get_value( lag ); // #ADD

    // When excitatory spike occurs, increment excitatory saturation function
	S_.s0_ += P_.S_i_* B_.ex_unweighted_spikes_.get_value( lag ); // #ADD
	S_.y1_ex_ = V_.PSCInitialValue_ / S_.s0_ * B_.ex_spikes_.get_value( lag ); // #ADD
	
	// sums normalized excitatory and inhibitory input
	S_.y1_ += S_.y1_ex_ + S_.y1_in_; // #ADD
```

Okay first thing, I've tried to test it, with a neuron targeted by a poisson generator, 
Here, it seems that the membrane potential is not affected 
![noisylifneurongroup - 80-20hz input](https://cloud.githubusercontent.com/assets/11985689/16272051/4eb781e8-386a-11e6-812b-55e4669e3b06.png)

So I thought that I should maybe keep the clipping, since it may happe, that y1_ex_ and y1_in_ are divied by zero if there is no spikes ?

So I added back the clipping and I've done a couple testing with different conditions.

Firstly, I comparated the excitatory spiking effect only, with a 80Hz input :

without normalization :
![noisylifneurongroup- 80hz input](https://cloud.githubusercontent.com/assets/11985689/16273266/ef70755a-386e-11e6-9412-3080696d1a9c.png)

with normalization :
![noisylifneurongroup - 80hz input](https://cloud.githubusercontent.com/assets/11985689/16273293/0961a736-386f-11e6-9775-f1dc5bce6e4a.png)

So it seems to work, I also tried  with high frequency inputs, which give a pretty much decrease in firing rate of target neuron. 

Then I try the effect of normalization on inhibitory, as you can see in this example, with a 40Hz inhibitory input

without normalization : 
![noisylifneurongroup](https://cloud.githubusercontent.com/assets/11985689/16274736/e176c4b2-3874-11e6-8858-c14481e5a12b.png)

with normalization, 
![noisylifneurongroup - 40hz](https://cloud.githubusercontent.com/assets/11985689/16273534/03571fc8-3870-11e6-971b-3cd879140fd7.png)

So the effect is indeed reduce !

So it seem's to work, now I have to try on a bigger scale with my model, in order to validate that this is what I wanted to implement.

Thank you again !

Emmanuel

**Comment by heplesser** [comment]
@ManuNeuro Fine that it works! Would you close the issue then?

**Comment by ManuNeuro** [comment]
Yeah sure thanks !

In the meantime I was able to train my model with that kind of normalization, which lead to bad results, so I'm going to create another thread to implement static normalization !
