### ISSUE TITLE
multi-threading issue with volume transmitter/stdp dopamine synapse

### ISSUE THREAD

**Issue by nash169** [nest/nest-simulator#410]
Hi there,
I got a weird problem using the volume transmitter and the stdp dopamine synapse implemented in NEST. Monitoring the variable 'n' of the stdp dopamine synapse (the firing rate of the dopaminergic neurons) I noticed that his behavior changes depending on the number of threads I'm using. I wrote a small script to test the problem: two neurons are connected each other using a stdp dopamine synapse. Besides those there's a bunch of 100 neurons (whose C_m and V_th are randomized) working as dopaminergic neurons stimulated by a poisson generator with a constant rate.  A volume transmitter 'connects' the stdp dopamine synapse to the dopaminergic neurons. Using 1 threads the output is ok; with 2 threads it is completely wrong (figures attached). My NEST release is 1 month old more or less; a NEST user just told me that things got better with the latest release but the issue is not solved yet.

Thanks a lot,
Bernardo 
![1-thread](https://cloud.githubusercontent.com/assets/17858965/16411141/e87fc898-3d25-11e6-9dd9-cd4a8db53b4c.png)
![2-threads](https://cloud.githubusercontent.com/assets/17858965/16411150/f28789ac-3d25-11e6-9d66-693348f2303e.png)

**Comment by Silmathoron** [comment]
Ok, just to show that this does not go away with the latest git source

with 1 thread
![1-thread](https://cloud.githubusercontent.com/assets/8523051/16417976/40829fd0-3d48-11e6-81ee-4be02f744baa.png)

with 2
![2-threads](https://cloud.githubusercontent.com/assets/8523051/16417981/45fd9ffa-3d48-11e6-9100-d375dbea8407.png)

And here is an input from David Kappel on the mailing list regarding a possible origin for the problem:

> Hi,
> 
> I think I came across a related problem recently. I was digging into the code a bit and the problem seems to be related to the call to "trigger_update_weight" inside the volume transmitter. It seems that this function is not meant to be used in a multi-threading environment, because it does not make sure that each synapse is updated within its own thread (as it ought to be with the rest of the NEST software design - at least that is what I got from looking at the code).
> 
> If that is true, it could break many things, since race conditions may occur in each synaptic update. In my case I was developing a stochastic synapse model and when I tried to update the synapses using "trigger_update_weight" I got weird effects and sometimes segfaults in the random number generators. My only solution so far was to either not using multi-threading or to write a version of the volume transmitter that can work without "trigger_update_weight". Both are not very practical solutions for you I guess, but a nice fix for this problem would require to really dig into the core of the NEST event scheduling and I did not have the time (or expertise) to do that so far.
> 
> I hope this helps to track down the issue (although I must emphasize that I'm not 100% sure that what I outlined above is really the problem here).
> 
> Best regards,
> David

**Comment by tillschumann** [comment]
What we understood from a short look at the code:
Besides the race condition issue, volume_transmitter doesn’t have proxies (like spike detectors), which means they are available on all virtual processes. But which also means that the volume_transmitters only receive spikes from neurons on the same virtual process.

We just came up with following workaround:
 - change in function has_proxies “return false” to “return true” in volume_transmitter.h (give it proxies)
 - replace "for ( thread t = 0; t < net_.get_num_threads(); ++t )” by "thread t = net_.get_thread_id()” in (network.h or connection_manager.h) (get rid of race condition)
 - create as many volume transmitter as you have threads (create volume transmitter for all virtual processes)

Best regards,
Till

**Comment by abigailm** [comment]
This analysis can't be quite right. The whole point of the volume transmitter is that it receives from everywhere, but only acts on local synapses. And whereas it may not be thread safe, it certainly was tested on distributed set-ups. So it indeed does not have proxies, but crucially local_receiver() returns false (unlike a spike_detector), meaning each instance receives spikes from all sources, not just the local ones.

**Comment by tillschumann** [comment]
Thanks for the clarification. I was not aware of the local_receiver functionality.
We will try out if the second step is already sufficient than.

**Comment by alberto-antonietti** [comment]
Dear all,
I tried partially the solution proposed by Till.
I worked not on the release 2.10.0, but on the current master branch.

In nestkernel/connection_manager.h

in the function nest::ConnectionManager::get_connections

I have changed the arguments of the for loop (line 1092) in this way:

`for ( thread t = 0; t < kernel().vp_manager.get_num_threads(); ++t )`
      ^^^^^^^^^^^^
became: 
`for ( thread t = kernel().vp_manager.get_thread_id(); t < kernel().vp_manager.get_num_threads(); ++t )`

same in line 1137 and 1191.

This solved my problem with the use of volume transmitter with multiple threads (OPENMP, not MPI), maybe this would also solve the issue.

Alberto

**Comment by heplesser** [comment]
Closing as this was fixed by #429.

**Comment by gui-miotto** [comment]
Was this issue really fixed?
I'm using nest 2.16.0 and I'm having a very similar problem.
For example, the code bellow results in totally different dopamine concentrations if running with 1 or 2 threads:

```python
import nest
import numpy as np
import matplotlib.pyplot as plt

def mwe(n_threads):
    # kernel configuration    
    nest.ResetKernel()
    nest.SetKernelStatus({'local_num_threads' : n_threads })

    # create nodes
    neurons = nest.Create('iaf_psc_delta', 2)
    vt = nest.Create('volume_transmitter')
    DA_spikes = nest.Create('spike_generator', params={'spike_times' : [999.]})

    # Connections
    nest.CopyModel('stdp_dopamine_synapse', 'dopa_syn', params={
        'n' : .005, 
        'vt' : vt[0]},
        )
    nest.Connect(DA_spikes, vt)
    nest.Connect(neurons, neurons, syn_spec='dopa_syn')
    synapse = nest.GetConnections(neurons[:1], neurons[1:])

    # Simulate and store dopamine concentration
    delta_t = 5.
    time = np.arange(0., 2000., delta_t)
    DA_n = []
    for _ in time:
        DA_n.append(nest.GetStatus(synapse, 'n'))
        nest.Simulate(delta_t)
    
    # plot dopamine concentration
    plt.plot(time, DA_n)
    plt.suptitle(f'Running with {n_threads} local thread(s)')
    plt.ylabel('dopamine concentration')
    plt.xlabel('time (ms)')
    plt.show()

mwe(1)
mwe(2)
```
![1thread](https://user-images.githubusercontent.com/9371512/60118983-baab3780-977d-11e9-9ac8-5bbf2a8a81d9.png)
![2threads](https://user-images.githubusercontent.com/9371512/60118984-bb43ce00-977d-11e9-8a68-823c8601016f.png)

**Comment by heplesser** [comment]
@gui-miotto Thank you for pointing this problem out. May I ask you to create a new issue about this with a reference back to this one? Comments added to close issues will often be overlooked.

**Comment by gui-miotto** [comment]
@heplesser , thank you for the reply. 
Done, check #1242 .
