### ISSUE TITLE
CLI: Setting verbosity does not work

### ISSUE THREAD

**Issue by astoeckel** [nest/nest-simulator#415]
According to `nest --help` the command line switch `--verbosity=QUIET` turns off all messages. However, executing

```
echo "(Hello World) =" | nest --verbosity=QUIET -
```

yields

```
[INFO] [2016.6.30 21:54:48 /home/andreas/source/nest-simulator/nestkernel/rng_manager.cpp:226 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2016.6.30 21:54:48 /home/andreas/source/nest-simulator/nestkernel/rng_manager.cpp:221 @ Network::create_rngs_] : Deleting existing random number generators
[INFO] [2016.6.30 21:54:48 /home/andreas/source/nest-simulator/nestkernel/rng_manager.cpp:226 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2016.6.30 21:54:48 /home/andreas/source/nest-simulator/nestkernel/rng_manager.cpp:272 @ Network::create_grng_] : Creating new default global RNG
Hello World
```

Note the log messages with severity "INFO".  The same happens when trying to set the verbosity to "FATAL". Tested with the current git version.

**Comment by heplesser** [comment]
@astoeckel The messages above are issued when the `RNGManager` is first created during startup, before any command line arguments are read in `SLIStartup`. The code checking for verbosity settings in that constructor is rather weak, actually. So we probably need to re-organize handling of command-line arguments. This is not trivial, especially when interacting with PyNEST and/or Music.

**Comment by astoeckel** [comment]
@heplesser This sounds like an understandable limitation. Wouldn't it be sufficient to just cache the log messages in the logger until a verbosity level has been set?

I stumbled across this while interfacing with NEST via SLI and stdin/stdout. While it surely isn't hard to ignore log messages in the output, it adds another parsing step. So alternatively, it would be sufficient for me if log messages were written to stderr, where they are put by most UNIX programs.

**Comment by heplesser** [comment]
@jougs Could you take a look?

**Comment by heplesser** [comment]
I am closing this in favour of #700, which came with an offer of a fix.
