### ISSUE TITLE
NEST 3.0 Release Meta-Issue

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#417]
This issue is a meta-issue to collect a to-do list for the NEST 3.0 release. Consider the list of items below a proposal, based on face-to-face discussions between @jougs and me recently. I suggest to discuss it in the next open developer video conference (including the question whether this should be an issue or rather a wiki post). This list contains ideas for changes that will have a significant effect on the user interface.
1. Create a 2.12 release with deprecation warnings for all functionality that will disappear or change in NEST 3.
2. Convert all functions working with nodes to use `GidCollection` as return and input arguments.
3. Adapt the topology module to manage layer metadata without using `Subnet`.
4. Remove `Subnet` entirely. Structure representation will be handled in a compact form by `GidCollection` on the script level.
5. Remove remaining deprecated functions.

**Comment by uahic** [comment]
An optional feature which could be though of (in principal) is to use music input/output message ports for steering the simulator remotely ("Nest as a service"). This could work by sending/receiving SLI commands. An issue here might be the output handling, the input should be straight forward. In combination with the the other existing ports altogether this would be sufficient to build/enhance remote interfaces.

**Comment by jougs** [comment]
@heplesser: do we still need this issue? My impression is that is more or less obvious what will be in NEST 3. Moreover this issue seems to be an inappropriate way to track progress and will be out of synch with the actual development most of the time. I would simply close it.

**Comment by jougs** [comment]
To my mind this issue does not contain much valuable information. I'm thus closing it for the sake of less clutter in the tracker. @heplesser: feel free to re-open if you think differently.
