### ISSUE TITLE
Suggestion: Create structured Travis log output

### ISSUE THREAD

**Issue by wschenck** [nest/nest-simulator#42]
Right now, the content written to stdout (and maybe stderr?) during the whole build and test process on Travis is just put into a single log file. Access to separate build artifacts is only possible by asking our GitHub team for a special build with output to S3.

Maybe life could be made a little bit easier by structuring the output to stdout during Travis builds in a more explicit way. This would require changes in ".travis.yml" and in "build.sh".

Variation 1: Introduce markers in stdout which contain file paths and names and provide in addition a post-processing script which can parse such a log and convert it into a directory structure with separate files.

Variation 2: Redirect all output to stdout and stderr (if possible?) during the build process to temporary files; from these files a structured tar file is created at the end of the build process and then written to stdout to get its contents into the Travis build log.

Additional suggestions are welcome... :-)

**Comment by lekshmideepu** [comment]
Currently, I'm doing some testing on how to upload artifacts to S3 per build and per job id basis. Recently, they had some changes in their setup. Hope to resolve this issue soon.
Once it's set, you will be able to access the artifacts separately for each build.

**Comment by lekshmideepu** [comment]
Refer the issue: https://github.com/travis-ci/travis-ci/issues/3432

**Comment by wschenck** [comment]
My suggestion was just meant as a supplement to the S3 setup.

A better structured Travis build log output could help on one's own GitHub repo for which the connection to S3 does not exist and is not planned (at least as far as I know).

**Comment by apeyser** [comment]
We could use base64 to make a tar.bz2 into something dumpable that could be cut as a single object.

**Comment by jougs** [comment]
@lekshmideepu: Ping!

**Comment by lekshmideepu** [comment]
As the S3 deployment PR has been merged, I'm closing this issue.
