### ISSUE TITLE
Installcheck fails with custom python

### ISSUE THREAD

**Issue by hendrikrth** [nest/nest-simulator#424]
Hi everyone,
I have the following problem: 
I installed the current version of NEST on my local machine (running on Scientific Linux release 7.2 (Nitrogen)) with a self compiled Python (2.7.12) and Openmpi (2.0.0). I had to do this because the python of our institut which is installed in /usr/bin has no openmpi. Configuring NEST with the needed prefixes (custom path, custom python, openmpi) works but when running make installcheck the PyNEST tests fail. Nevertheless I am able to run NEST by its own, with ipython, with python and with mpirun.

When I install NEST without openmpi and link it to our standard python installation (/usr/bin/python) everything works out fine and no test fails.

Kind regards
Hendrik

[nest_report.tar.gz](https://github.com/nest/nest-simulator/files/373569/nest_report.tar.gz)

**Comment by sanjayankur31** [comment]
This is the error in the test suite:

```
----------------------------------------
Failure: ImportError (/home/hendrik/opt/local/nest/lib/python2.7/site-packages/nest/pynestkernel.so: undefined symbol: PyUnicodeUCS2_DecodeASCII) ... ERROR

======================================================================
ERROR: Failure: ImportError (/home/hendrik/opt/local/nest/lib/python2.7/site-packages/nest/pynestkernel.so: undefined symbol: PyUnicodeUCS2_DecodeASCII)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/hendrik/opt/local/nest/lib/python2.7/site-packages/nest/__init__.py", line 52, in <module>
    from . import pynestkernel as _kernel
ImportError: /home/hendrik/opt/local/nest/lib/python2.7/site-packages/nest/pynestkernel.so: undefined symbol: PyUnicodeUCS2_DecodeASCII
```

According to [this post](http://stackoverflow.com/questions/2584198/undefined-symbol-pyunicodeucs2-decode-whilst-trying-to-install-psycopg2), you need to use an additional flag while building Python from source. Can you please try it out and see if that fixes the issue?

**Comment by hendrikrth** [comment]
Yes it fixed the issue. Thank you very much.
