### ISSUE TITLE
Installcheck fails 1 test

### ISSUE THREAD

**Issue by MarkoFil** [nest/nest-simulator#425]
When running installcheck after fresh installation of NEST 2.10., there is one failed test somewhere.
[reports.zip](https://github.com/nest/nest-simulator/files/374084/reports.zip)

**Comment by sanjayankur31** [comment]
From the logs, this is the failed test:

```
Running test 'unittests/test_round_validate.sli'... 
   > Running  /home/markof/opt/nest/bin/nest /home/markof/opt/nest/share/doc/nest/unittests/test_round_validate.sli
   > NEST v2.10.0 (C) 2004 The NEST Initiative
   > 
   > Jul 20 17:30:31 file [Error]: FileOpenError
   >     Could not open the following file for writing: 
   >     "/home/markof/opt/nest/share/doc/nest/help/sli/array.hlp".
-> 126 (Failed: error in test script)
```

Can you please check that the reported file `/home/markof/opt/nest/share/doc/nest/help/sli/array.hlp` exists to begin with?

**Comment by MarkoFil** [comment]
It does, please find it attached.

Cheers,
Marko

**Comment by sanjayankur31** [comment]
Can you check the permissions on the file then? The error says that the file could not be opened for writing. It's one of these tiny things.

**Comment by MarkoFil** [comment]
Since I had to use sudo in order to make/make install, the file belongs to
root. I didn't use sudo to perform make installcheck though.

-rw-r--r-- 1 root root  224 Jul 20 17:29 array.hlp

**Comment by sanjayankur31** [comment]
That may be it actually - if you're installing in your own user's home directory, you needn't use run `make install` with `sudo`. If you run the `installcheck` with sudo, it should work.

**Comment by MarkoFil** [comment]
Ah, I see! I can try to reinstall it without sudo and see what happens.
When reinstalling, is it enough just to delete $HOME/opt/nest, or do I have
to delete something more?

**Comment by sanjayankur31** [comment]
Just deleting the existing installation directory should be enough (you'll have to use `sudo` to delete it at the moment, of course). Please do `source <path to nest_vars.sh>` before running `installcheck` so that nest knows where the files are at.

**Comment by MarkoFil** [comment]
Alright, I've now done it without sudo (and in another location, as it
turned out there is already an "opt" folder on root - I'm still a Linux
noob), and installcheck returned no errors. Thank you for the help!

Cheers,
Marko

**Comment by sanjayankur31** [comment]
You can use the `/opt` folder or any other location that works for you - as long as you source `nest_vars.sh`, it should work. Please close this issue :)
