### ISSUE TITLE
CMake broken on BGQ (or CMake considered harmful)

### ISSUE THREAD

**Issue by apeyser** [nest/nest-simulator#427]
CMakes design is broken for a) mpi and b) BGQ. For MPI, the cmake authors seem to believe that they can in general write a program that can extract all the necessary information from the mpi wrappers for all machines in all cases, and then use that information to directly construct the actions needed to reproduce that behavior. 

This would ultimately imply P==NP :astonished: 

For BGQ with sionlib, the combination of things that cmake can't handle because of its improper concept of abstraction leads to a failure (can't find MPI_send and such errors)

The way around this would be to set CMAKE_{C,CXX}_COMPILER to the proper wrapper, but that's unfortunately not possible, because the cmake community sets those unconditionally in the platform files without marking them as CACHE.

I'll go ahead and fix this, but this will lead in the future to updates of the cmake platform files that revert the changes made here by mistake.

**Comment by abigailm** [comment]
Is this an issue that we can raise with the CMake developers, such that there is a possibility that things would be less harmful in the future?
