### ISSUE TITLE
gh-pages/coding_guidelines_c++.md is broken

### ISSUE THREAD

**Issue by wschenck** [nest/nest-simulator#433]
The two source code text boxes at the end of the page (reg. vera++ and clang-format configuration) are merged into one (see attached screenshot).
![screenshot_20160729_123225](https://cloud.githubusercontent.com/assets/11649523/17245801/934f1042-5588-11e6-8259-020a743aa92a.png)

**Comment by jougs** [comment]
@wschenck: thanks for spotting this!
