### ISSUE TITLE
nest website: balanced network

### ISSUE THREAD

**Issue by apeyser** [nest/nest-simulator#435]
At: http://www.nest-simulator.org/py_sample/random-balanced-network-exp-synapses-multiple-time-constants/

I see the following line:
num_synapses = nest.GetDefaults("excitatory")["num_connections"]+

which is a syntax error.

**Comment by heplesser** [comment]
This is due to a line break probably introduced when rendering for the website. The correct code is

```
num_synapses = (nest.GetDefaults("excitatory")["num_connections"] +
                nest.GetDefaults("inhibitory")["num_connections"])
```

and that is directly cut and pasted from Master. 

@steffengraber Is there any chance that the parenthesis around the addition disappeared when converting the code for the website?

**Comment by apeyser** [comment]
Now I see -- it's a python indent thing + paren thing. I didn't even look at the next line, because it lines up at position 0, so it can't syntactically be part of the same unit, and without the parens, the plus at line end is an incomplete statement, since newline is python-syntactic.

Is the code in the scroll-down box pulled directly from the source tree, or is there some "massaging" that goes on in the process? If so, we may need to check the script and recreate those scroll-down boxes. 

@jougs ?

**Comment by jougs** [comment]
@steffengraber knows all about this. If the file in the repository differs from the one on the homepage, there's probably a bug in the conversion script.

**Comment by steffengraber** [comment]
The website displays NEST v2.10.0.
In 
https://github.com/nest/nest-simulator/blob/v2.10.0/pynest/examples/brunel_alpha_numpy.py
line 328 I found:

    num_synapses = nest.GetDefaults("excitatory")["num_connections"]+\
    nest.GetDefaults("inhibitory")["num_connections"]

In master:
https://github.com/nest/nest-simulator/blob/master/pynest/examples/brunel_alpha_numpy.py
everything is ok (line 338):
 
    num_synapses = (nest.GetDefaults("excitatory")["num_connections"] +
                    nest.GetDefaults("inhibitory")["num_connections"])

**Comment by jougs** [comment]
Thanks for investigating @steffengraber. The fix was pushed to master when @heplesser PEP8ified the file in 6d331cf.

@steffengraber can you please fix on the homepage and then close this issue?

**Comment by steffengraber** [comment]
Changed in:

- http://www.nest-simulator.org/py_sample/random-balanced-network-exp-synapses-multiple-time-constants/
- http://www.nest-simulator.org/py_sample/random-balanced-network-delta-synapses/
- http://www.nest-simulator.org/py_sample/random-balanced-network-alpha-synapses-connected-with-nest/
- http://www.nest-simulator.org/py_sample/random-balanced-network-alpha-synapses-connected-with-numpy/

**Comment by steffengraber** [comment]
@jougs I have no rights to close this issue.

**Comment by jougs** [comment]
Thanks for fixing.
