### ISSUE TITLE
Multisynaptic neuron model with independent synaptic rise times and decay times

### ISSUE THREAD

**Issue by golosio** [nest/nest-simulator#438]
The multisynaptic neuron models that are currently available do not allow one to define independent synaptic rise times and decay times. The alpha function depends on a single time constants, and it is not always suitable for modeling synaptic conductance. On the other end, the time course of most synaptic conductances can be well described by the sum of two exponentials (see A. Roth and M.C.W. van Rossum in Computational Modeling Methods for Neuroscientists, MIT Press 2013, Chapter 6). It would be important to have a multisynaptic neuron model with synaptic conductance modeled by a double exponential function, with independent synaptic rise times and decay times

**Comment by DimitriPlotnikov** [comment]
@golosio You pull request still doesn't pass through CI. It would be very helpful, if you would get all tests pass.

@abigailm @heplesser aeif_cond_exp_multisynapse is an example of a neuron model, that currently doesn't integrate well with NESTML approach. Generally, it is not an issues to deal with in NESTML. Here is an example of model with 2 constants implemented: ( cf. https://github.com/nest/nestml/blob/master/models/iaf_cond_beta.nestml ).

**Comment by golosio** [comment]
@DimitriPlotnikov Thank you. The build process and the install check work fine in my machine. I'm new with nest development and I still have to understand how the Travis check works.

**Comment by DimitriPlotnikov** [comment]
@heplesser What is the general policy regarding including new models into NEST?

**Comment by golosio** [comment]
@DimitriPlotnikov accordind to the guidelines in the developer space: http://nest.github.io/nest-simulator/code_review_guidelines, concerning new models, "each pull request needs an OK from the CI platform and at least two reviewers to be merged". Meanwhile, my pull request passed through the CI. It was blocked by very little formatting problems, the rules for formatting are very strict.

**Comment by DimitriPlotnikov** [comment]
@golosio @heplesser 
Cf. my latest comment in the pull request.

**Comment by DimitriPlotnikov** [comment]
Since there is already an active pull request solving this issues and this issue being quite  non-informative, from my point of view we can close it.

**Comment by golosio** [comment]
ok
