### ISSUE TITLE
Add warning when two-way connections are created without symmetric=true

### ISSUE THREAD

**Issue by janhahne** [nest/nest-simulator#440]
PR #315 added a symmetric flag to the `conn_dict` in order to be able to create symmetric connections ( a->b , b->a ) with a single call to `nest.Connect`. Two-way connections like `gap_junction` demand this flag to be set to `true` in order to create accurate connections. 

The default setting for `symmetric` is however `false`. Therefore it would be desirable to add a warning to NEST that is displayed whenever a two-way connection type is called with `symmetric = false`. This warning should remind the user, that the `Connect`-call does not create an accurate connection and that the other direction of the connection needs to be created with either a second call to `Connect` or by setting `symmetric = true` first.

**Comment by heplesser** [comment]
@janhahne I wonder if we shouldn't throw an exception instead of just issuing a warning. My experience is that warnings tend to be overlooked.

Would you create a PR for this?

**Comment by janhahne** [comment]
@heplesser I agree with you. An exception is the better choice. There is however one tricky case: All-to-all connections are symmetric by default. So we need to allow the creation of all-to-all connections with `symmetric=false`.

I created a PR (#524) which implements this and hopefully resolves this issue.

**Comment by heplesser** [comment]
This was fixed by #524, therefore closing.
