### ISSUE TITLE
C++ 11

### ISSUE THREAD

**Issue by apeyser** [nest/nest-simulator#453]
Following #344, we should consider transitioning towards C++11.

All HPC machines currently support at least C++ 11, except possibly for K, which is in the process of porting their gcc-based compiler to gcc-4.8.2 at some point this year.

STLs are usable, curly brace constructors remove narrowing, constructors and converters are vastly improved, templates are vastly improved...

In fact given that most machines will have llvm compilers going forward, an even more aggressive position is tenable.

**Comment by jougs** [comment]
At the NEST Conference 2017 we officially announced that C++11 is allowed in NEST from now on. I'm thus closing this issue.
