### ISSUE TITLE
Consistent information on how to cite NEST

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#456]
On the homepage (http://www.nest-simulator.org under **'please cite nest and tell us about your work'**) the instruction is to generally cite the reference:
```
Gewaltig M-O & Diesmann M (2007) NEST (Neural Simulation Tool) Scholarpedia 2(4):1430.
```

On the [NEST github Readme.md](https://github.com/nest/nest-simulator#citing-nest) we have 
* a link to the most recent Zenodo entry for 2.10 
* the instructions to cite this instead for NEST versions above 2.8

I guess both versions should contain the same instructions w.r.t citing Zenodo for NEST > 2.8?

**Comment by heplesser** [comment]
@flinz Thanks for noticing this!
@steffengraber Could you adapt the text on the website to the text in the README?

**Comment by apeyser** [comment]
That should be NEST >= 2.8.
2.8 has doi:10.5281/zenodo.32969
2.10 had doi:10.5281/zenodo.44222

**Comment by steffengraber** [comment]
I have adapted the text in the README and in the index.md. 
See pull request #461.

**Comment by flinz** [comment]
This is addressed in the merged PR https://github.com/nest/nest-simulator/pull/461
