### ISSUE TITLE
Shutdown of Jenkins at qa.nest-initiative.org

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#460]
Since our move to GitHub, we're using Travis CI for continuous integration of the NEST source code. This means that from our point of view, the old Jenkins installation at https://qa.nest-initiative.org/ is not needed anymore.

However, back at the time, we offered the CI service also to other projects. This issue is mainly created to get some kind of written agreement of all people hosting projects on the machine before shutting it down. We might be able to help with the transition to another solution if that is required.

**Comment by jougs** [comment]
* @ctrueden ([Fiji](https://qa.nest-initiative.org/view/Fiji)): gave OK via email
* @apdavison ([PyNN](https://qa.nest-initiative.org/view/PyNN), [Sumatra](https://qa.nest-initiative.org/view/Sumatra)): gave OK via email
* @jbednar ([Topographica](https://qa.nest-initiative.org/view/Topographica)): gave OK via email

**Comment by jougs** [comment]
@mdjurfeldt: do you still need the MUSIC job on the system?

**Comment by ctrueden** [comment]
Just for public record, here is a (slightly cleaned up) version of my email:

> As maintainer, I do not use the NEST Jenkins for anything. The Fiji job was originally added by Yury Zaytsev as one of a diverse set of projects to demonstrate the utility of NEST; see the [IRC logs](http://code.imagej.net/chatlogs/fiji-devel?search=&start-date=2011-11-09&end-date=2011-11-09&format=html&columns=78&times=sparse&submit=search) for details.
>
> If the job is no longer useful on your end, then feel free to remove it.

**Comment by mdjurfeldt** [comment]
@jougs Due to the move to Travis CI, the MUSIC job at qa.nest-initiative.org, is not needed.

Thanks!
Mikael

**Comment by jougs** [comment]
The machine has finally been shut down and I have just now removed the DNS entry, which was redirecting `qa.nest-initiative.org` to 132.230.177.10.
