### ISSUE TITLE
Parameter arrays cannot be used in connections with rules fixed_indegree and fixed_outdegree in Python

### ISSUE THREAD

**Issue by golosio** [nest/nest-simulator#463]
Two-dimensional parameter arrays can only be used in conjunction with rule 'all_to_all'.
Apparently, there is no reason to apply this restriction for connection rules 'fixed_indegree' and 'fixed_outdegree', because with such rules there is a fixed number of connections, which can easily be matched to the elements of a two-dimensional array. Having the possibility to use parameter arrays with such rules would make the users able to use user-defined distributions with those two rules without using loops for connecting populations of neurons.

**Comment by heplesser** [comment]
Closing as this was fixed by #465 .

**Comment by ikitayama** [comment]
This test fails on JURON with the following messages:
```
Running test 'unittests/issue-463.sli'...
   > Running  /p/project/cpcp0/pcp0151/opt/nest-clang-normal/bin/nest /p/project/cpcp0/pcp0151/opt/nest-clang-normal/share/doc/nest/unittests/issue-463.sli
   > [INFO] [2019.1.17 8:6:7 /p/project/cpcp0/pcp0151/projects/nest-simulator/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
   > [INFO] [2019.1.17 8:6:7 /p/project/cpcp0/pcp0151/projects/nest-simulator/nestkernel/rng_manager.cpp:284 @ Network::create_grng_] : Creating new default global RNG
   > NEST gpus@35514c3 (C) 2004 The NEST Initiative
   >
   > Jan 17 08:06:07 MapThread_a [Error]: RangeCheck
-> 126 (Failed: error in test script)
```

I'd happy to provide more information if needed.

**Comment by ikitayama** [comment]
@heplesser could you re-open this Issue? Thanks.
