### ISSUE TITLE
Revise SLI doctesting

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#470]
We currently have an essentially unused method for doctest in SLI, the `validate` function. It is only used to test the `round` SLI function, and even that causes problems, see #464.

We should revise our approach to doctesting, especially since #464 moves help extraction and generation to Python.

**Comment by jougs** [comment]
@heplesser, @diesmann: any update on this? Are you OK with #464 removing the pertaining test and fixing this later?

**Comment by heplesser** [comment]
@jougs @steffengraber I just added a suggestion to #464 (too busy today to make it via a PR to @steffengraber ). With that in place I think #464 can go ahead.

**Comment by jougs** [comment]
Many thanks!

**Comment by heplesser** [comment]
Closing as this will be superseded by new documentation under development.
