### ISSUE TITLE
Building a generic base class for all multisynapse neuron models

### ISSUE THREAD

**Issue by golosio** [nest/nest-simulator#477]
There is a significant superposition in the code of all multisynapse neuron models. For code revision, maintenance, introduction of new models, a more efficient solution would be to have a generic base class (or maybe a template class) multisynapse_neuron, which contains the common code and from which all multisynapse neuron models could be derived.
Also, there is probably no reason to bind an instance of this model to a single conductance/psc model: in principle one could have in the same neuron, for example, one port for conductance-based synapses modeled by alpha function, another for psc_exp synapses, etc. This could be achieved by separating the code for synaptic current from that for generic multisynapse neuron.

**Comment by golosio** [comment]
See also issue #472 and comment https://github.com/nest/nest-simulator/pull/439#discussion_r78281957

**Comment by heplesser** [comment]
@golosio Would you consider closing this issue, since NESTML will provide a much more general solution?

**Comment by golosio** [comment]
Sure...
