### ISSUE TITLE
Make topology independent of subnets

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#481]
Removal of subnets (#480) requires that topology becomes independent of subnets in maintaining its metadata. Instead, the metadata should be attached to the GIDCollection representing a layer.

**Comment by heplesser** [comment]
## User interface changes

### Current
```Python
lyr = nest.CreateLayer(...)
nest.GetStatus(lyr)
```
displays layer-specification dictionary

### Future
```Python
lyr = nest.CreateLayer(...)
nest.GetStatus(lyr)
nest.GetLayerStatus(lyr)
```
- First returns status of all nodes in layer
- Second returns layer-specification dictionary

## Implementation

- `AbstractLayer` no longer inherits from `Subnet`
- Metadata in class derived from `GIDCollectionMetadata`, contains
    - pointer to layer object
    - dictionary datum with layer-specification dictionary

**Comment by apeyser** [comment]
@heplesser : Have you considered using the 'with' grammatical construction with topology?
So:
````
a = createLayer(...)
with a as clayer:
   make stuff belong to the layer
````

**Comment by heplesser** [comment]
@apeyser Your suggestion seems a bit like a step back into the subnet approach we want to leave behind. In #455, we propose that GIDCollections (as returned by CreateLayer) would be immutable, so you could not put anything into them once they are created. Also, I would like to retain the declarative approach of topology, where all information required to specify a layer is passed to CreateLayer in a dictionary.

**Comment by apeyser** [comment]
@heplesser: So you want them built bottom up rather than top bottom?

In the end, it's an api detail -- we could build the data structures in any direction, if we found it handy, and then interface to the bottom up approach.

**Comment by stinebuu** [comment]
@heplesser As this is fixed in the [nest-3 branch](https://github.com/compneuronmbu/nest-simulator/tree/nest-3) do we want to close this issue to be able to close the [Remove subnets](https://github.com/nest/nest-simulator/projects/2#card-2069522) project?

**Comment by heplesser** [comment]
Closing as this is implemented in the NEST 3 branch.
