### ISSUE TITLE
Support for advanced dry-run mode

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#482]
Future advanced dry-run modes will require that we can associate a network node to a group (population) based on its GID. Currently, this is done using subnets, but this will disappear with subnets (#480).

An alternative solution could be implemented as follows:
1. Each call to `Create` creates a group (population) of nodes.
2. Each such group is numbered uniquely, and the group number is stored in the `Node` (taking the place of the `parent` pointer, no additional memory required).
3. Each process stores a vector of all groups, represented by first and last GID (as in a plain GIDCollection).

The memory required to store all groups on each process would be limited. Assuming a total of 10.000 groups for a massive multi-area simulation, it would require 20.000 `long` or about 160 kB.

@wschenck @suku248 for info.

**Comment by jougs** [comment]
To my mind this issue does not contain much valuable information and we will have to see how to go about when the dry-run mode is actually integrated. I'm thus closing it. @heplesser: feel free to re-open if you think differently.
