### ISSUE TITLE
OSX & XCode 8: Endless stream of warnings when compiling

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#486]
Compiling NEST after installing XCode 8 will lead to an endless stream of warnings when compiling with gcc (from homebrew):

```
/var/folders/93/z61g0__j1p7cq0gtl3kbzq6r0000gn/T//ccmOKzB3.s:289765:11: warning: section "__textcoal_nt" is deprecated
       .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                ^      ~~~~~~~~~~~~~
/var/folders/93/z61g0__j1p7cq0gtl3kbzq6r0000gn/T//ccmOKzB3.s:289765:11: note: change section name to "__text"
       .section __TEXT,__textcoal_nt,coalesced,pure_instructions
```

This is a known problem, see 
- http://stackoverflow.com/questions/39502921/warning-section-const-coal-is-deprecated-error-after-updating-xcode-to-la
- https://github.com/Homebrew/homebrew-core/issues/4812

From Stackoverflow, it seems the best work around is to run

```
sudo xcode-select -s /Library/Developer/CommandLineTools
```

The CommandLineTools contain the tools from XCode 7, and NEST will compile without problems and link properly.

**Comment by heplesser** [comment]
I discovered a little problem with the fix above: FileMerge disappears from the Path. So if you try to resolve merge conflicts using FileMerge (eg using SourceTree), nothing will happen (FileMerge won't start and OSX won't give you an error message). You need to switch back to XCode 8 with
```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/
```
For a proper solution, we need to wait for the underlying bugs in GCC and Clang to be fixed, see Homebrew/homebrew-core#4812.

**Comment by heplesser** [comment]
The work-around does not seem to work if you have XCode 8 command-line tools installed. This is a GCC/LLVM bug:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71767
- https://llvm.org/bugs/show_bug.cgi?id=28427
At least the GCC bug seems to have been fixed recently, we'll have to wait until the fixed propagate to the GCCs distributed by Homebrew and Macports.

**Comment by heplesser** [comment]
I have now updated my system (OSX El Capitan 10.11.6) to XCode 8.2.1 and gcc 6.3.0 from Homebrew. In that combination, the linker warnings disappear. Pending a test on macOS Sierra 10.12 (later today), I assume we can consider this solved.

**Comment by heplesser** [comment]
I have now tested under macOS Sierra 10.12 was well (XCode 8.2.1, gcc 6.3.0) and the warnings are gone. I am thus closing this issue.

**Comment by ghazalehsaghar** [comment]
hello
I used xcode 7 and gcc 4.2, then I update xcode 8.2.1 , then I faced the above error, As you said now I install gcc 6.3.0. But how can I make the gcc 6.3.0 as the default gcc. I mean it looks my mac is using the gcc 4.2. I want to make it to use gcc 6.3.0

**Comment by heplesser** [comment]
I assume that gcc 6.3.0 is installed on your computer so that it is invoked as `gcc-6` and `g++-6`. Then, you need to tell `cmake` about it:
```
 cmake -DCMAKE_INSTALL_PREFIX:PATH=</install/path> \
        -DCMAKE_C_COMPILER=gcc-6\
        -DCMAKE_CXX_COMPILER=g++-6 \
        </path/to/NEST/src>
```
See also the `INSTALL` file include with NEST and the [instructions on our website](http://www.nest-simulator.org/#mac-os-x).
