### ISSUE TITLE
Discussion: A new interface for parameterization and spatially structured networks in NEST

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#488]
## Background

NEST currently has two different interfaces for specifying parameters to NEST functions, one used by `Connect` and `Create`, the other used by `topology.ConnectLayers`. The latter is quite strongly based on concepts in the Topology module. This duplicity is unfortunate and should be removed.

Work on NEST optimization has shown that memory locality is crucial to excellent performance, especially in multithreaded code. Therefore, we have decided to remove `subnet`s from NEST. This will also affect the Topology Module, since it currently manages layers as subnets with metadata.

Both changes will lead to changes in the NEST User Interface. It therefore seems sensible to introduce them with NEST 3.
## The Purpose of Parameters

With parameters, in NEST I here mean quantities used to specify values in neuron models, synapses, connection, or that parameterize connection patterns:
- provide model parameters, such as time constants, conductances, ...
- provide initial values, such as membrane potentials, ...
- provide connection weights and delays
- provide connection probabilities 

Parameters may be given as
- fixed values
- random values
- arrays of values
- functions returning context-dependent values, e.g., weights depending on the distance of neurons

In the most general way, all these types of parameters can be considered as functions taking information about the network as input and returning values.
### Core NEST: `Create()` and `Connect()`

Currently,
- fixed scalars
- random scalars from a fixed set of distributions
- arrays

are supported. Parameters cannot depend on context (e.g., GID), and cannot be combined into expressions. Arrays are indexed sequentially, mapping array locations in the parameter array to corresponding arrays of GIDs.

Random scalars are specified as follows:

``` Python
{'distribution': 'uniform', 'low': 0.8, 'high': 2.5}
```
### Topology: `CreateLayers`

Currently,
- fixed scalars
- random scalars from a fixed set of distributions
- a fixed set of distance-dependent functions

are supported. Functions are specified in a topology-specific syntax, e.g.,

``` Python
{'gaussian': {'p_center': 1.0, 'sigma': 0.5}}
{'linear': {'c': 1.0, 'a': -0.05, 'cutoff': 0.0}}
{'uniform': {'min': 0.5, 'max': 2.0}}
```

Parameters in Topology can be combined to create composite parameters, e.g.,

``` Python
lin = topo.CreateParameter('linear', {'c': 1.0, 'a': -0.05, 'cutoff': 0.0})
uni = topo.CreateParameter('uniform', {'min': 0.5, 'max': 2.0})
p = lin * uni
```

This is currently not possible for core parameters. 

There are a number of problems with topology parameters:
- Syntaxes differ between core and topology, with a nested approach in topology and a flat approach in the core; see the uniform examples above.
- The function specifications are not intuitive. E.g., in `linear`, is `a` or `c` the slope? For `gaussian`, `p_center` makes sense if the values is interpreted as a probability, but not if it is used as, e.g., a weight.
- It is in no way obvious that `linear` and `gaussian` take a displacement vector between two neurons as input, while `uniform` does not take any input.
- This problem is compounded in composite expressions.

Furthermore, only functions provided through the topology module are available, which covers only a small subset of mathematical functions.
## Proposal

The key ideas of this proposal are
- to permit flexible specification and combination of parameters
- have a uniform syntax across all parts of NEST
- make dependencies on context explicit
- ensure that evaluation of parameter specifications can be implemented efficiently.

Work here will focus on Python syntax, since few end-users today use SLI. The CSA will be considered as a source of inspiration.

Roughly, we can consider the following kind of functions important:
- Functions of random deviates
- Distance-dependent functions (including displacement-dependent functions)
- General context-dependent functions (e.g. depending on density of surrounding neurons)
- Random deviates with parameters depending on, e.g., distance
- Indicator functions returning true/false

Formulations should be as close to standard mathematical notation as possible.

One way to achieve this would be for NEST to provide mathematical functions (as classes or objects???), with normal mathematical operators overloaded.

Then, one could write something like the following:

``` python
import nest as n

# V_m from uniform distribution, -75 .. -55 mV
n.Create('iaf_psc_alpha', n=10, params={'V_m': n.rdv.uniform(-75., -55.)})

# V_m from array of values
n.Create('iaf_psc_alpha', n=3, params={'V_m': [-75.0, -69.0, -73.4]})

# tau_m from Gaussian distribution, re-draw if value < 0.5 is chosen
n.Create('iaf_psc_alpha', n=10,
         params={'tau_m': n.rdv.gaussian(mu=10., sigma=5., min=0.5, redraw=True)})

# V_m from modified exponential distribution: p(V) = H(V+80) * exp(-0.1*(V+80))
n.Create('iaf_psc_alpha', n=10,
         params={'V_m': -80.0 + n.rdv.exponential(lam=0.1)})

# Connections with negative, lognormally distributed values
n.Connect(inh, exc, conn_rule={'rule': 'fixed_indegree', 'indegree': 1000},
          syn_spec={'weight': -n.rdv.lognormal(mu=100., sigma=20.)})

# Nodes with spatial placement from quasi-random number sequence
# and phase from x coordinate
n.Create('sinusoidal_poisson_generator',
         n=400,
         spatial={'position': (n.qrng(-1, 1).x, n.qrng(-1, 1).y)},
         params= {'rate': 100.,
                  'amplitude': 100.,
                  'frequency': 10.,
                  'phase': 180. * n.node.pos.x})

# Connectivity taking space into account:
#  - requires populations with spatial information
#  - here: fixed in-degree 500, only neurons within 0.5 with
#          exponentially dropping probability, linearly dropping weights
#          and uniformly distributed delays
n.Connect(src, tgt,
          conn_spec={'rule': 'fixed_indegree',
                     'indegree': 500,
                     'mask': n.distance < 0.5,
                     'kernel': n.exponential(n.distance, lam=0.2)},
          syn_spec={'weight': 10. - 0.1 * n.distance,
                    'delay': n.rdv.uniform(0.5, 2.5)})

# Pairwise Bernoulli connectivity with p=0.7 for all neurons within 0.5 distance,
# but target.x > source.x + 0.1, uniform delays and weights increasing linearly
# with distance, slower along y-axis.
n.Connect(src, tgt,
          conn_spec={'rule': 'pairwise_bernoulli',
                     'mask': (n.distance < 0.5) & (n.displacement.x > 0.1),
                     'kernel': 0.7},
          syn_spec={'weight': 0.7 * (n.displacement.x / 2 + n.displacement.y),
                    'delay': n.rdv.uniform(0.5, 2.5)})

# Alternative notations:
- n.distance(n.source, n.target)
- n.displacement(n.source, n.target)
- n.norm(n.target-n.source)     # distance
- n.target.pos - n.source.pos   # displacement
```

**Comment by jougs** [comment]
I'm closing this in favor of https://github.com/compneuronmbu/nest-simulator/issues/4.
