### ISSUE TITLE
Remove aeif_cond_alpha_RK5 model

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#494]
As @Silmathoron [has pointed out earlier](https://github.com/nest/nest-simulator/pull/35#issuecomment-186309378), the explicit RK5 implementation appears significantly slower than the one based on GSL. Having two implementations of the same model is confusing to the user and increases maintenance efforts.

I therefore propose to remove the RK5-version of the model.

@gewaltig I hope this is okay for you?

**Comment by Silmathoron** [comment]
In fact, this would save me a lot of time because I was designing the test for PR #474 and I can't get the RK5 version to get close enough to the LSODAR reference solution.
So if everyone is okay with it, I can remove it in my PR...

**Comment by gewaltig** [comment]
This is strange, in all of our tests, the RK5 version was faster and more accurate than the GSL version (I think the tests are in the examples)

**Comment by gewaltig** [comment]
I commented on the other thread. I would prefer to first see where the speed differences come from.

In any case, I'll dig out the old benchmarking scripts.

**Comment by gewaltig** [comment]
Dear all,

the comparison between the two implementations is done by the script
evaluate_aeif_cond_alpha_RK5.py  in the pynest examples.

On my mac, I get the following output:
`Runtime GSL: 0.0493731832504
Test: 0.0436501979828
Ratio: 0.884087172613
Spike Times GSL - Reference:[ 0.082  0.02   0.053  0.153  0.163  0.165  0.167  0.169  0.171  0.173
  0.275  0.277  0.279  0.281  0.283  0.385  0.387]
Spike Times Test - Reference: [ 0.082  0.02   0.053  0.053  0.063  0.065  0.067  0.069  0.071  0.073
  0.075  0.077  0.079  0.081  0.083  0.085  0.087]
L2-Error (per s) GSL - Reference: 34.4949607855
L2-Error (per s) Test - Reference: 3.97167314363
L2-Error ratio: 0.115137778191`

The first part compares the runtime. a ratio of 0.88 means that the RK5 implementation is about 12 percent faster that the GSL implementation.
At the same time, the error of the GSL implementation is almost 10 times larger!

What remains to be tested is why the RK5 implementation in a network is so much slower.

**Comment by heplesser** [comment]
We have discussed the numerics of the AEIF model in detail in #229 (several Jupyter notebooks attached there), and #474 includes a notebook with a reference solution based on the LSODAR solver. We should create a reference solution using that notebook as a basis for implementation comparisons.

**Comment by gewaltig** [comment]
Sorry, can you send me the link to the notebook? I cannot find it in #474 
anyway that all does not invalidate the comparison between the two implementations....

**Comment by Silmathoron** [comment]
Notebook is [here](https://github.com/Silmathoron/nest-simulator/blob/06f65c5ab450d0a2b4db3c9e0f721be621eff158/doc/model_details/aeif_models_implementation.ipynb).
It describes the problem of binding the exponential argument.

**Comment by gewaltig** [comment]
Thanks. I had a master student who did the RK5 implementation and we did a lot of testing and analysis. I'll look for his thesis where the work is documented.
Also, I still would like to know why the RK5 implementation is slower only in the network case.
I suspect an issue in the synapse handling.

**Comment by Silmathoron** [comment]
If you can, try to have a look at the behaviour of the RK5 implementation, comparing it to the reference LSODAR solution included in #474.
Personally, I can't make the behaviour match as closely as the GSL implementation, and, more specifically, I cannot remove the boundary on the argument of the exponential without leading to either numerical instabilities or parasitic jumps in ``w`` at spike time...

**Comment by heplesser** [comment]
We keep this model for now and revisit the issue of the aeif-implementation when we replace hand-written model code by NESTML-generated model code.
