### ISSUE TITLE
cmake ignores pynest on MacOS with MacPorts

### ISSUE THREAD

**Issue by gewaltig** [nest/nest-simulator#495]
When compiling a fresh checkout, pynest is ignored.

OS: 10.11.6 (El Capitain)
cmake 3.6.1 (macports)

The issue seems to be related to
https://github.com/pybind/pybind11/issues/99

The same fix indicated there solves the problem.

**Comment by gewaltig** [comment]
Basically, call cmake like this:
cmake -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.dylib  -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python2.7 .

**Comment by heplesser** [comment]
Possibly relevant info from NEST User from @gtrensch :

NEST requires the Python interpreter and the Python libraries to be of exact same version. The CMake configure process tries to find a matching pair and runs some checks. If this is not successful an error is raised.
You always may overwrite following CMake variables to set the Python environment:  
 
PYTHON_EXECUTABLE ..... path to the Python interpreter
PYTHON_LIBRARY ............. path to libpython
PYTHON_INCLUDE_DIR ..... two include ...
PYTHON_INCLUDE_DIR2 ... directories
 
A more detailed description  can be found in the install instructions: https://github.com/nest/nest-simulator/blob/master/INSTALL  see section ‘Python3 Binding (PyNEST)’
I don’t know if the mix 2.7.10/12 introduced by ‘homebrew’ will work properly. But you may give it a try by setting the variables mentioned above accordingly.

**Comment by heplesser** [comment]
Closing this as there is a work-around given by @gewaltig above, and we do not have capacity to support Macports explicitly at present (homebrew is supported).
