### ISSUE TITLE
Wrong variable recorded for iaf_psc_alpha and 'input_currents_ex/in'

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#499]
The synaptic current recorded for the ``iaf_psc_alpha`` model is wrong: we get the derivative (exponential shape) and not the current, which is contained in ``S_.y2_ex_`` or ``S_.y2_ex_``.
 ``S_.y1_ex_``/``S_.y1_ex_`` are returned instead.

See attached notebook.
[iaf_psc_alpha_error_record.ipynb.zip](https://github.com/nest/nest-simulator/files/500328/iaf_psc_alpha_error_record.ipynb.zip)

**Comment by heplesser** [comment]
@Silmathoron I think you are right. Could you prepare a PR to fix this? Do you know if the same problem applies to other models?

**Comment by Silmathoron** [comment]
I don't know about other models but I'm just waiting for Travis to finish checking that everything's alright before clicking on the PR button ;)

**Comment by jougs** [comment]
Closing now that #500 is merged
