### ISSUE TITLE
Various names for synaptic current

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#501]
In ``nest_names``, there are several variables defined to designate the synaptic currents.
I'll give only the examples for the excitatory current:
* ``"I_syn_ex"`` for [``iaf_tum2000``](https://github.com/nest/nest-simulator/blob/0d58accc82b6b44801c82e502976889e3c37d80b/models/iaf_tum_2000.cpp#L59)
* ``"I_ex"`` for [`hh_psc_alpha``](https://github.com/nest/nest-simulator/blob/0d58accc82b6b44801c82e502976889e3c37d80b/models/hh_psc_alpha.cpp#L64) and [``hh_psc_alpha_gap``](https://github.com/nest/nest-simulator/blob/0d58accc82b6b44801c82e502976889e3c37d80b/models/hh_psc_alpha_gap.cpp#L63)
* ``"input_currents_ex"`` for [``iaf_psc_alpha``](https://github.com/nest/nest-simulator/blob/0d58accc82b6b44801c82e502976889e3c37d80b/models/iaf_psc_alpha.cpp#L61) and [``iaf_psc_exp``](https://github.com/nest/nest-simulator/blob/0d58accc82b6b44801c82e502976889e3c37d80b/models/iaf_psc_exp.cpp#L62)

This makes it very complicated to interact with or compare different models.
I understand this might break some codes, but since the changes are relatively simple, and, on the whole, should make the code more coherent, I suggest only one variable be kept.

To me ``"I_syn_ex"`` seems the better choice, since it is the most explicit...

[Disclaimer]I intend to submit psc implementations for the aEIF models so there should be new models using one of those, I'd rather pick the most coherent and make it the same for all models[/Disclaimer]

**Comment by Silmathoron** [comment]
@heplesser we did not discuss it in the VC, but I guess I should remove ``"I_ex"`` and ``"input_currents_ex"`` from ``nest_names``, right?

**Comment by heplesser** [comment]
@Silmathoron Yes, and if they have any "in" siblings those as well.
