### ISSUE TITLE
Improved windowing for devices

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#505]
This is a follow-up to discussions in #497, which raised the issue of windowing recordings.

We should think through approaches, syntax and semantics before committing to a solution. Windowing will probably be useful for many types of recordings, so we should aim for a more general solution. It also needs to be compatible (reasonably) with existing solutions to ensure a consistent user experience across recorders. 

We currently have the possibility to define "one-time" windows using `start` and `stop`, which can then be shifted during simulation breaks by changing `origin`. I have no data on how much this is used, but I think this approach may be a bit more dated.

Then we have, for `multimeter`, the sampling `interval`: data is recorded only at time steps that are a multiple of `interval`.  For continuous signals that can be sampled at any time, this is a sensible approach. If combined with a `start`-`stop` window, only multiples of `interval` inside the window are recorded.

I would suggest to extend this approach in two directions. For all devices (include stimulation devices) we should support flexible, repeated windowing (extending what @weidel-p suggested in #497). Ideally, we should provide both regular windowing with a fixed window width repeated at fixed intervals, and user-defined windowing based on an explicit list of window start times and durations. This could be implemented in the `Device`/`RecordingDevice`/`StimulatingDevice` classes. I would suggest `window_width` and `window_repeat` (or `window_interval`) as names, and `windows` for the user-defined case. In that case, the argument should be a nested list or 2D array with `start time`-`width` pairs.

**Comment by SepehrMN** [comment]
@heplesser @weidel-p @abigailm I have implemented a similar mechanism in my new device #436. There are multiple start and stop times, and one interval can be specified. Those should not ideally be in the device,  but in the recording device.

**Comment by SepehrMN** [comment]
Hi,
Is there a timetable for merging the new windowing system?

**Comment by heplesser** [comment]
@SepehrMN At present, the new windowing system is a proposal waiting for a volunteer to implement it. Many core developers are currently busy with major changes behind the scenes (subnet removal, improved output), so it will probably be a while until we get around to this one.

**Comment by SepehrMN** [comment]
Many thanks. I think what I wrote can be very easily be turned into how your `windows` suggestion would work. Furthermore, it would work with a `window_stop` as well.

**Comment by sepehrmn** [comment]
I personally do not need this feature anymore. I have an old pull request that has an implementation inside the class. I hope to reopen it for merging soon. 

This issue can be closed.

**Comment by heplesser** [comment]
Closing this issue due to lack of demand. Streaming solutions under development will handle this case in a different way.
