### ISSUE TITLE
Misleading documentation on random number generators

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#508]
On http://www.nest-simulator.org/random_numbers/, most relevant information in seeding RNGs is given under the "random numbers in parallel simulations" heading. This is misleading, since users need to seed the grng and the thread-0 rng in serial simulations.

**Comment by mschmidt87** [comment]
Actually, I was just looking something up in the documentation on random numbers and realized that it is outdated. It still uses the old function names for creation of connections, such as `RandomDivergentConnect`, so this should be updated as well.

**Comment by terhorstd** [comment]
@heplesser, could you give some updates on the status of this?

**Comment by heplesser** [comment]
Fixing the documentation guide on random numbers as part of #1549 is very high on my agenda, hope to get to it later this week.
