### ISSUE TITLE
Check whether SiblingContainers can also be removed

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#512]
This relates to #480, subnet removal.

I have a hunch that with subnets, we can also drop `SiblingContainer`s. Nodes would be entirely managed by `SparseNodeArray`s and `ModelrangeManager`s on a per-thread basis. Nodes with siblings are simply identified via their type.

**Comment by jougs** [comment]
SiblingContainers have been removed in https://github.com/compneuronmbu/nest-simulator/tree/fix-481-SubnetFreeTopology. I'm thus closing this.
