### ISSUE TITLE
Update aeif_cond_beta_multisynapse to new aeif numerics approach

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#514]
`aeif_cond_beta_multisynapse` should be updated to the same voltage-limiting scheme introduced for the `aeif_cond_alpha_*` models (except `RK5` variant) with #474.

@golosio Could you take care of this, maybe together with #510 ?

**Comment by golosio** [comment]
ok, if you agree I'll put the changes together in a single PR

2016-10-07 7:18 GMT+02:00 Hans Ekkehard Plesser <notifications@github.com>:

**Comment by golosio** [comment]
@Silmathoron I was taking care of this issue and I was wondering if it is really necessary to have two aeif_cond_alpha_dynamics functions in aeif_cond models, one for Delta_t>0 and the other for Delta_t=0, but very similar to each other. I tried to modify your version of aeif_cond_alpha using only one  aeif_cond_alpha_dynamics function with a check on Delta_t:
  if ( node.P_.Delta_T > 0. )
  {
    I_spike =
      node.P_.Delta_T * std::exp( ( V - node.P_.V_th ) / node.P_.Delta_T );
  }
  else
  {
    I_spike = 0;
  }
See: https://github.com/golosio/nest-simulator/blob/aeif_DT0/models/aeif_cond_alpha.cpp
and the corresponding header file.
I run simulations with Delta_t = 0 and != 0, using the same parameters that you used for comparing this model with lsodar (see the attached files) and the results are identical. Also, I run a long simulation to evaluate the simulation time, but there are no significant differences.

[aeif.py.txt](https://github.com/nest/nest-simulator/files/517723/aeif.py.txt)
[aeif_DT0.py.txt](https://github.com/nest/nest-simulator/files/517724/aeif_DT0.py.txt)

**Comment by Silmathoron** [comment]
Well, I'm not expert enough to know whether the memory/speed gain will have any influence... maybe @heplesser can help on that or knows someone who might tell us. In the meantime I'll try to run some tests on a cluster to compare the runtimes, but this might take time because this week schedule is rather tight...
I agree, though, that having redundant code might not be the best option; yet it might make the distinction between the two situations clearer.

**Comment by golosio** [comment]
It's true. However, as you know, redundant code makes code maintenance more difficult. In the past in other collaborative projects I had a lot of problems with that. There is always the possibility that someone modifies properly one part and not the other. Personally I always prefer to avoid redundant code.someone modifies properly one part and not the other. Personally I always prefer to avoid redundant code.

**Comment by Silmathoron** [comment]
I added the question to the VC so a decision can be made with everyone ;)

**Comment by golosio** [comment]
ok, but maybe it was not necessary. Your opinion and that of @heplesser is importanr for me, because you took care of this part of the code, and if my arguments did not convince you, I would use two separate functions, even though I have a different opinion.

**Comment by heplesser** [comment]
@golosio @Silmathoron "Das Bessere ist der Feind des Guten", as we say in German ("The better is the enemy of the good"). Avoiding code duplication is generally a good idea, and here we can do it in a very straightforward way, so I think it is a good idea. Indeed, you can make it even more compact:
```C++
const double I_spike = node.P_.Delta_T == 0. ? 0 : node.P_.Delta_T * std::exp( ( V - node.P_.V_th ) / node.P_.Delta_T );
```
Since `node.P_.Delta_T` is constant during simulation, compiler and CPU will be able to do branch prediction very well here and I would not expect any negative effect on performance.

**Comment by Silmathoron** [comment]
Ok, fine for me, I'll make a PR to update this.
