### ISSUE TITLE
NEST connection infrastructure improvements

### ISSUE THREAD

**Issue by alexeyshusharin** [nest/nest-simulator#523]
## 1. Introduction

Information about connections between neurons is a major memory consumer in neural simulations. This makes the effective connection memory management one of the most important aspects of neural simulation software. NEST simulator has quite effective memory management. [The great work](http://journal.frontiersin.org/article/10.3389/fninf.2014.00078/full) was done to reduce the connection memory footprint in NEST 2.6 release. At the same time, some problems of connection management still exists. In particular, the memory reallocation problem and the capacity overhead of std::vector container. This document describes the improvements of NEST connection infrastructure that allow to solve this problems.
## 2. Goals

The main goals of the changes described in this document are:
- Reduce memory consumption mostly by reducing overhead of connection data structures
- Improve connection creation performance by avoiding memory reallocations
- Add ability to iterate through connections of post-synaptic node
## 3. High-level design

According to the NEST object distribution scheme, the number of source node connections that belong to the same virtual process (VP) depends on number of VPs. In large scale simulation it can be just a single connection of source node per VP. If the connections are stored on source node side the optimization of connection memory management is complicated since it should satisfy all possible simulation conditions – from a single connection to thousands of connections of the source node per VP.
From the other side it’s guaranteed that all incoming connections of a particular target node are always local to each other and this rule doesn't depend on simulation scale. Usually there are hundreds or even thousands of incoming connections per target. It's still possible that target has a single digit number of incoming connections but this is very rare and biologically not plausible. So if the connections are stored on target node side it’s much easier to optimize connection memory management since number of local connections is relatively stable and predictable.
The main idea of this proposal is to move the connection storage to the target node side and optimize memory management algorithms to reduce memory overhead and avoid reallocations. The amount of connection data stored on source node side is minimized as much as possible. Following diagram describes the proposed connection infrastructure model.

![newconnectionmodel](https://cloud.githubusercontent.com/assets/22319467/19460870/820e5d8e-94e8-11e6-8929-4ee535bd6488.png)
### 3.1. TargetConnector

TargetConnector is a central part of this design. It's responsible for storing incoming connections of a particular target node. Since it's guaranteed that number of these connections is relatively high the connection data can be divided into the chunks with fixed size. Each TargetConnector owns one chunk of data. All TargetConnector's related to the same target node are connected by double linked list and the target node has a pointer to the first element in this list.
Initially target connector list is empty so the target pointer to the list is null. When first connection needs to be added the ConnectorModel creates new TargetConnector and Connection is stored in it. When the first TargetConnector is full the next one is created and placed at the beginning of the list. This process repeats until all connections are created.

![targetconnectorlist](https://cloud.githubusercontent.com/assets/22319467/19460886/a24aa800-94e8-11e6-8055-c6e74e217a38.png)

Allocating connection data by chunks allows to avoid both problems of std::vector: preallocated capacity and memory reallocation. Obviously this approach has its own overhead: a fullness of the last chunk of data and an auxiliary data of TargetConnector. In random network the average fullness of last chunk is 50%. The overhead of auxiliary data is constant and about 64 bytes per TargetConnector. So the number of connections in one chunk should be big enough to minimize overhead of auxiliary data and relatively small to support models with hundreds of incoming connections. The current proposal is to store 64 connections per chunk. But this can be discussed and other approach can be chosen, for example, this value can depend on size of connection object.
Since incoming connections of target node are placed in chunks the common properties of connections can be stored in TargetConnector object. These properties are synapse model id, pointer to target node and receiver port.
The synapse model id and receiver port are also used to find the appropriate TargetConnector of the target node to store the connection. To optimize this process TargetConnector's are maintained in the sorted order – chunks with free slots are always placed at the beginning of the double linked list. The new TargetConnector is always placed as a first element. If TargetConnector is full it is moved forward up to the first element without free slots. If some connections are removed from TargetConnector it is placed as a first element. This approach guarantees that algorithm complexity of searching the right TargetConnector is close to O(1).
The implementation of TargetConnector is represented an interface class TargetConnectorBase and concrete template implementation TargetConnector<ConnectionT>.
### 3.2. ConnectorModel

The double linked list of TargetConnector is useful when we want to add a new connection or to iterate through all connections of target node. But it doesn't help with fast access to the connection that is required for sending events. To achieve this we need an index of TargetConnector's. This is responsibility of ConnectorModel.
ConnectorModel maintains an array (can be implemented as deque or vector) of pointers to TargetConnector's. So TargetConnector object can be retrieved from this array by the index. Since index of TargetConnector cannot be changed ConnectorModel also supports additional array with free indexes. It is used when TargetConnector is deleted. To avoid searching free slot in connector array ConnectorModel remembers free indexes and uses them for new TargetConnector creation.
### 3.3. ConnectionHandle

ConnectionHandle identifies the connection in the particular virtual process. It consists of three indexes:
- synapse model identifier (1 byte) identifies the ConnectorModel
- target connector index (6 bytes) identifies TargetConnector for particular ConnectorModel
- connection index (1 byte) identifies the connection inside TargetConnector

The total size of ConnectionHandle is 8 bytes. This is enough to address any reasonable number of connections and at the same time small enough to not introduce significant memory overhead.
ConnectionHandle has two reserved values to identify empty connection slot in TargetConnector and identify the end of single linked list of connections.
### 3.4. SourceConnector

SourceConnector is a simple structure that contains last spike time value and ConnectionHandle of the first connection of the source node. Other connections of the source node are accessible via single linked list of Connection objects (see next section). SourceConnector is stored in sparse table by value so it doesn't require dynamic memory allocation.
### 3.5. Connection

In the proposed model there is no need to store target identifier inside Connection object. The target and the receiver port are part of TargetConnector data structure. Instead of this Connection objects are organized into a single linked list of source node connections. Each Connection has ConnectionHandle value that points to the next Connection of the source node. The last connection has a special value that means the end of the list. ConnectionHandle of the first source node connection is stored in SourceConnector.
This approach allows easily iterate through all connections of the source node starting from SourceConnector so it is used for sending event from source node. The diagram below describes the relationship between nodes, connectors and connections.

![connectionhandle](https://cloud.githubusercontent.com/assets/22319467/19460915/f7d9d3a4-94e8-11e6-8f5a-f6b8a9402102.png)
### 4.1. Create connection
- Get pointer to target node
- Look up first appropriate (syn_id + port) TargetConnector with free connection slot
  - It's not required to iterate through all TargetConnector's. The first TargetConnector without free slot means that all others are also full.
  - If there are no TargetConnector's with free slots ConnectorModel should create a new one and add it as a first element of the target connector list.
- Add new Connection into TargetConnector
  - If TargetConnector is full move it forward in the list up to first full connector. So only TargetConnector's with free slots are placed at the beginning of the list.
- Form ConnectionHandle (syn_id + connector_idx + conn_idx) and save it as a first element in the source connection list.
### 4.2. Send event
- Get SourceConnector from sparse table
- Iterate through the list of connections and send event for each connection
  - Get ConnectionHandle
  - Extract syn_id, blob_idx and conn_idx from ConnectionHandle
  - Get ConnectionModel for current thread by syn_id
  - Get TargetConnector by target_conn_idx
  - Send event for Connection (conn_idx)
  - Get next ConnectionHandle from Connection object
### 4.3. Get connections

For each thread iterate through sparse table and for each SourceConnector repeat:
- Iterate through the list of connections
  - Get ConnectionHandle
  - Extract syn_id, blob_idx and conn_idx from ConnectionHandle
  - Check if the syn_id satisfies requested parameters
  - Get ConnectorModel for current thread by syn_id
  - Get TargetConnector
  - Check if the it satisfies requested parameters
  - Push back ConnectionID to the result
  - Get next ConnectionHandle from Connection object
### 4.4. Get number of connections
- Iterate through TargetConnectors for requested ConnectorModel
  - Sum up sizes of each TargetConnector
### 4.5. Get/Set connection status
- Extract syn_id, blob_idx and conn_idx from ConnectionHandle
- Get ConnectorModel for specified thread by syn_id
- Get TargetConnector
- Get/set Connection (conn_idx) status
### 4.6. Delete connection
- Get SourceConnector from sparse table
- Iterate through the list of connections and find required connection
  - Get ConnectionHandle
  - Extract syn_id, blob_idx and conn_idx from ConnectionHandle
  - Check if syn_id satisfies requested parameters
  - Get ConnectorModel for current thread by syn_id
  - Get TargetConnector
  - Check if the target satisfies requested parameters
- Delete connection
  - Remove ConnectionHandle from SourceConnector list
  - Mark connection slot in TargetConnector as empty
  - Move TargetConnector to the beginning of target connector list
  - If TargerConnector is empty remove it
  - Remove TargetConnector from target connector list
  - Add target_conn_idx to the free index list in ConnectorModel object
  - Delete C++ object
### 4.7. Iterate through connections of target node
- Get pointer to target node
- Iterate through all TargetConnector's and perform required action on each connection
## 5. Memory consumption

Some notes about memory consumption calculations:
- All calculations are done for 64-bit system.
- Calculations are done for
  - two different connection model with TargetIdentifierPtrRport specialization: static_connection and stdp_connection.
  - two different number of target node incoming connections: 1000 and 6000.
  - three different number of virtual processes and so different number of source node connections: K = 1, K = 10 and K = 100.
- Memory overhead of std::vector is taken as 33%. GCC implementation if std::vector doubles capacity each time when it needs to extend. For random networks the only half of this newly allocated space will be used.
- Memory overhead of TargetConnector is taken as 50% of one connection chunk. For random networks the only half of the last TargetConnector will be used.
- Allocator overhead is usually hidden but it's significant in the software with intensive memory allocation. Let's take simple case and account allocator overhead as 8 bytes per allocation.
- Another hidden element of memory consumption is vtable of C++ objects with virtual functions. It's accounted as 8 bytes per object.
- sparsetable overhead and lastspike value are not accounted in this calculation since their memory consumption is static and doesn't change a lot with this proposal.

Memory consumption of current connection infrastructure for K < 3 is:
`M = (A + P + VT) * N / K + CC * N`

Memory consumption of current connection infrastructure for K >= 3 is:
`M = (A + P + VT + V + VA) * N / K + CC * N * (1 + VO)`

Memory consumption of proposed connection model is:
`M = CH * N / K + (A + P + VT + TC) * N / TN + CP * (N + TN * TO)`

where

```
M – memory required to store connections of a single target node
A – allocation overhead of Connector object: 8 bytes
P – pointer to Connector object: 8 bytes
VT – vtable of Connector object: 8 bytes
V – size of std::vector: 24 bytes
VA – allocation overhead of vector storage: 8 bytes
VO – overhead of std::vector preallocation: 0.33
CH – size of ConnectionHandle: 8 bytes
TN – number of connections per TargetConnector: 64
TC – size of TargetConnector (without a connection array): 40 bytes
TO – overhead of TargetConnector: 0.5
CC – size of Connection in current model: 32 (static) or 88 (stdp) bytes;
CP – size of Connection in proposed model: 24 (static) or 80 (stdp) bytes
N – number of target incoming connections: 1000 or 6000
K – number of connection per source node: 1, 10 or 100
```

The results are:

Synapse model: static

```
N = 1000.0  K = 1.0     CM = 54.69kB    PM = 32.98kB    Savings = 39.70%
N = 6000.0  K = 1.0     CM = 328.12kB   PM = 194.11kB   Savings = 40.84%
N = 1000.0  K = 10.0    CM = 47.03kB    PM = 25.95kB    Savings = 44.83%
N = 6000.0  K = 10.0    CM = 282.19kB   PM = 151.92kB   Savings = 46.16%
N = 1000.0  K = 100.0   CM = 42.11kB    PM = 25.24kB    Savings = 40.06%
N = 6000.0  K = 100.0   CM = 252.66kB   PM = 147.70kB   Savings = 41.54%

```

Synapse model: stdp

```
N = 1000.0  K = 1.0     CM = 109.38kB   PM = 89.41kB    Savings = 18.25%
N = 6000.0  K = 1.0     CM = 656.25kB   PM = 523.98kB   Savings = 20.15%
N = 1000.0  K = 10.0    CM = 119.77kB   PM = 82.38kB    Savings = 31.21%
N = 6000.0  K = 10.0    CM = 718.59kB   PM = 481.80kB   Savings = 32.95%
N = 1000.0  K = 100.0   CM = 114.84kB   PM = 81.68kB    Savings = 28.88%
N = 6000.0  K = 100.0   CM = 689.06kB   PM = 477.58kB   Savings = 30.69%
```

where

```
N – number of target incoming connections
K – number of connection per source node
CM – current memory consumption per target
PM – proposed memory consumption per target
```
## 6. Performance considerations

The main goal of this proposal is to avoid std::vector reallocation and memory copying. That should improve performance of creating connections. Unfortunately it's hard to do the math here so the implementation will show the results.

From the complexity stand point the performance of connection management algorithms are the same or better:
- create connection - O(1)
- send event - O(1)
- get connections - O(N)
- get/set connection status – O(1) [was O(N)]
- delete connections - O(N)

## 7. Auxiliary improvements

- Since connections are stored on target side it makes possible to iterate through connections of target node. It can be useful for some models, for example, to implement weight normalization.
- Two different connection template instantiations are not required anymore. Overhead of specifying port for each connection is negligible with the proposed improvements.

## 8. Drawbacks

The proposed model is based on assumption that target node has a significant number of incoming connections. Only in this case memory consumption is reduced. But if this assumption is not true the memory consumption will be increased. The worst case is if target node has only one incoming connection.

For example, memory consumption of 1000 static connections (one connection per target and K = 10) will be 47.03kB for the current model and 1563.28kB for the proposed model. Looks horrible! But this can be optimized if we decide that this case is important.

The trick with template implementation of Connector can be applied to TargetConnector. The first TargetConnector can be created with small size of connection chunk, for example just 1 connection instead of 64. When a new connection is added the TargetConnector is reallocated with increased size of chunk. Such approach leads to reallocations that we want to avoid but it can be done just several times per target node. Then the connection chunk size can be as usual – 64 connections.

With this improvement the memory consumption for 1000 static connections (one connection per target and K = 10) will be 86.72kB versus  47.03kB for the current model. Not so bad.

## 9. Open questions

The proposed connection model has a number of open questions that need to be answered:
- What is the most common use case for connection? Is the number of incoming target connection always significant?
- How important is the case with small number of incoming target connections?
- What is the most common use case for target port? This proposal stores port value in TargetConnector object. So if there are use cases for many different port values this is not very efficient and the approach with port value should be reconsidered.

**Comment by Silmathoron** [comment]
Hi Alexey,
thanks a lot for the extensive proposal, this looks really interesting.
Some of it went a bit over my head, though, so I have a few questions:

## TargetConnector

> Initially target connector list is empty so the target pointer to the list is null. When first connection needs to be added the ConnectorModel creates new TargetConnector and Connection is stored in it.
Since ``TargetConnector`` has not been created yet, what is the "target pointer to the list" you're referring to?

I'll let you discuss with people that are more knowledgeable than me about the default number of ``Connection``s per ``TargetConnector``.

## Source nodes
The question might be stupid, but how do we get the source node from a ``Connection``?

## Optimization

Are there cases where the design would be less efficient than the existing architecture?
For instance for 50 connections with 5 types of synapses (e.g. there could be 5 different groups of neurons and each inter-group connection would be modeled differently), there would be 5 ``TargetConnectors`` containing 10 ``Connections`` each.
I know this example is a bit extreme, but it's just to have an idea. This is not a trick question, I'm just curious about the point at which this implementation would become less efficient than the actual: for what kind of configuration would it happen? This would help compare the benefits and drawbacks of both.

**Comment by alexeyshusharin** [comment]
@Silmathoron, Thanks for feedback!
Please see answers below.

> Since TargetConnector has not been created yet, what is the "target pointer to the list" you're referring to?

Probably I should change a description a little bit to make it more clear.
Each Node has a pointer to the first TargetConnector object. This is actually a pointer to the linked list of TargetConnector's. When the connections are not created, the list is empty and so this pointer is null.

> The question might be stupid, but how do we get the source node from a Connection?

The question is reasonable.
If we have only pointer to Connection object this is not possible. We should iterate through all connections to find the source node. If we have ConnectionID (that is returned from getConnections()) it has source_gid_ property that points to source node.
The behavior is the same in current implementation and this is not changed. Actually getting source node from Connection doesn't have a lot of sense since most probably it belongs to another virtual process and we cannot do anything with it.

> Are there cases where the design would be less efficient than the existing architecture?

Yes, definitely this proposal has some drawbacks. I tried to optimize the connection infrastructure for most common cases when a node has significant number of incoming connections of a particular synapse type. If this is not common case the optimization will not work. :)

The worst case is when Node have a single incoming connection of a particular synapse type. In real models it can happen with incoming connections from devices (e.g. spike_generator). It's a good idea to add Drawbacks section into proposal. I will try to do some math to compare current and proposed implementations for these use cases. Also we can try to find a solution to cover these cases in some specific way.

**Comment by heplesser** [comment]
@suku248 @jakobj Could you take a look at this proposal and see if it is still relevant/applicable now that we have the 5G kernel (https://doi.org/10.3389/fninf.2018.00002)?

**Comment by heplesser** [comment]
Many thanks for the proposal, but closing as there is currently no realistic pathway to implementation.
