### ISSUE TITLE
 Define what ResetNetwork is expected to do 

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#525]
Resetting a simulation mid-flight is a complex task. The function `ResetNetwork` is meant to do this, but the implementation is incomplete.

We thus decided to investigate what cannot be done explicitly without the function (e.g. resetting the internal spike buffers in neurons) and add corresponding functions. Once we have these functions in place, we deprecate `ResetNetwork` for the next release and advise users to use explicit calls to SetStatus for resetting neurons and synapses and the new functions for clearing the buffers.

After some time we remove `ResetNetwork` from all code and examples.

**Comment by Silmathoron** [comment]
Hi @jougs!
I'm not sure I understand what you would replace ``ResetNetwork`` with...
What I expect from this function is that it resets everything as it was before my **very first** call to ``Simulate``, i.e.:

- all network structure (neurons, synapses, devices...) is unchanged
- time is reset to 0
- all nodes' status are reset to their initial values at object creation.

**Comment by heplesser** [comment]
- Deprecate in NEST 2.18
- Remove in NEST 3

**Comment by Silmathoron** [comment]
@jougs @heplesser so what are the functions that will replace it?
