### ISSUE TITLE
Segmentation fault with DataConnect and Multithreading

### ISSUE THREAD

**Issue by alberto-antonietti** [nest/nest-simulator#527]
I was trying DataConnect with multiple threads, and I got a segmentation fault if the number of threads was >1.

I have compiled the current Github version of NEST on Linux Ubuntu 14.04, with gcc-4.8.

This is the pynest script that I have used to reproduce the issue:

```
import numpy as np
import nest

CORES = 1

nest.set_verbosity('M_WARNING')
nest.ResetKernel()
nest.SetKernelStatus({'local_num_threads' : CORES,
                      'total_num_virtual_procs' : CORES})

A=nest.Create('iaf_neuron',1)
B=nest.Create('iaf_neuron',1000)

nest.DataConnect(A,[{'target':np.float64(B),
                         'delay':1.0*np.ones(1000, np.float64),
                         'weight':1.0*np.ones(1000, np.float64) }],'static_synapse')

AB_conn = nest.GetConnections(A,B)
print "Number of A-B synapses: " + str(len(AB_conn))

```

If I set "CORES" to 2, 4 or 8, I get a segmentation fault error, sometimes without any information, sometime with a little more:

> [alberto:28834] **\* Process received signal ***
> [alberto:28834] Signal: Segmentation fault (11)
> [alberto:28834] Signal code: Address not mapped (1)
> ## [alberto:28834] Failing at address: (nil)
> 
> mpirun noticed that process rank 0 with PID 28834 on node alberto exited on signal 11 (Segmentation fault).

I have seen that there are similar problems with deprecated functions as Convergent/Divergent connect, maybe this is related.

Do you suggest to avoid using DataConnect and use something else instead?

**Comment by heplesser** [comment]
I can confirm this on master on OSX 10.11 with gcc 6.2.1.

**Comment by heplesser** [comment]
@alberto-antonietti I would recommend that you use the `Connect` function, which also accepts explicit parameter arrays. I have rewritten your example with `Connect` below. It uses the default all-to-all connection rule and parameters are given asa 2D matrix, with one column per source and one row per target neuron. Alternatively, you could use the `one-to-one` rule with 1D arrays. You can also mix arrays for some parameters with fixed or random values for others.

This code works with multiple threads and is on a single thread about three times faster than `DataConnect`.

```Python
import numpy as np
import nest

CORES = 8

nest.set_verbosity('M_WARNING')
nest.ResetKernel()
nest.SetKernelStatus({'local_num_threads' : CORES})

A = nest.Create('iaf_neuron', 1)
B = nest.Create('iaf_neuron', 1000)

nest.Connect(A, B, syn_spec={'model': 'static_synapse',
                             'delay': np.ones((1000, 1), np.float64),
                             'weight': np.ones((1000, 1), np.float64)})

AB_conn = nest.GetConnections(A, B)
print("Number of A-B synapses: " + str(len(AB_conn)))
```

**Comment by alberto-antonietti** [comment]
Thank you @heplesser! I will avoid using `DataConnect` in the future, thanks for the two alternatives!

**Comment by heplesser** [comment]
Since we have the work-around listed above, we should just prohibit `DataConnect()` when in Multithreaded mode (SLI and PyNEST).
