### ISSUE TITLE
NEST install error

### ISSUE THREAD

**Issue by esternwar** [nest/nest-simulator#528]
OS - Kubuntu 16.10 Yakkety Yak Release
Error text: 
/home/****/soft/nest/nest-2.10.0/sli/slistartup.cc: In member function 'bool SLIStartup::checkpath(const string&, std::__cxx11::string&) const':
/home/****/soft/nest/nest-2.10.0/sli/slistartup.cc:75:15: error: cannot convert 'std::ifstream {aka std::basic_ifstream<char>}' to 'bool' in return
   return ( in );

**Comment by jougs** [comment]
Duplicate of issue #220, fixed by pull request #389.

You can either update to latest git master or merge the changes from the linked pull request.
