### ISSUE TITLE
GetStatus should (be able to) return a structured NumPy array

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#538]
`GetStatus` currently returns a plain tuple of tuples then called with parameter names. Some Python acrobatics are required to turn this into a structure NumPy array that can be used easily, as in this example from #537:
```Python
c_data = np.array(list(nest.GetStatus(nest.GetConnections(), 
                                     ['source', 'target', 'weight', 'delay', 'alpha'])),
                   dtype=[('source', 'i'), ('target', 'i'), 
                          ('weight', 'f'), ('delay', 'f'), ('alpha', 'f')])

nest.ResetKernel()

nn = nest.Create('iaf_psc_alpha', N)
nest.Connect(c_data['source'], c_data['target'], conn_spec='one_to_one',
                 syn_spec={'model': 'stdp_synapse', 'weight': c_data['weight'],
                           'delay': c_data['delay'], 'alpha': c_data['alpha']})
```
It would be much cleaner, safer and probably more efficient if `GetStatus` returned a structure NumPy array right away, at least as an option.

**Comment by jougs** [comment]
@stinebuu: isn't this what is now possible with the `get()` function in [our branch](https://github.com/compneuronmbu/nest-simulator/tree/fix-481-SubnetFreeTopology)? If yes, I guess we can close this.

**Comment by stinebuu** [comment]
@jougs: It does not return a NumPy array, but yes. It returns a dictionary with lists (or integers), which makes it really easy to extract data. We could add an option for returning a NumPy array if that is desirable,  we already have an option for Pandas. We would just have to convert what is returned on the Python level to a NumPy array, and that doesn't sound too difficult to me.

**Comment by jougs** [comment]
Thanks for your quick reply. I guess the main point in this issue is resolved and Pandas sounds like a good way of handling this. We can always extend to NumPy arrays once a real use case turns up.
