### ISSUE TITLE
error make command in cygwin windows

### ISSUE THREAD

**Issue by thisroot** [nest/nest-simulator#543]
Hi, i got an error message when  runing "make" command.
I try to install Nest to Cygwin in Windows.
May be is missing library. Did anybody passed this step?

```In file included from ../../nest-2.10.0/nestkernel/archiving_node.h:34:0,
                 from ../../nest-2.10.0/nestkernel/archiving_node.cpp:30:
../../nest-2.10.0/nestkernel/nest.h:88:25: error: 'LONG_LONG_MAX' was not declared in this scope
 const tic_t tic_t_max = LONG_LONG_MAX;
                         ^
../../nest-2.10.0/nestkernel/nest.h:89:25: error: 'LONG_LONG_MIN' was not declared in this scope
 const tic_t tic_t_min = LONG_LONG_MIN;```
```

nest.h
```
#ifndef NEST_H
#define NEST_H

#include <cstddef>
#include <climits>
#include <cfloat>
#include <limits>
#include "config.h"
.......
#ifdef HAVE_LONG_LONG
typedef long long tic_t;
#ifdef IS_K
const tic_t tic_t_max = LLONG_MAX;
const tic_t tic_t_min = LLONG_MIN;
#else
const tic_t tic_t_max = LONG_LONG_MAX;
const tic_t tic_t_min = LONG_LONG_MIN;
#endif
#else
typedef long tic_t;
const tic_t tic_t_max = LONG_MAX;
const tic_t tic_t_min = LONG_MIN;
#endif
```

**Comment by Silmathoron** [comment]
Hi @thisroot, could you give us some specifics on your install: what compiler are you using? which version?
In fact if you could give the result of configure, it would be best.
I'm not sure many people tried to install NEST on windows (I sure didn't), and I'm pretty sure we make no guarantee it is possible... but it would be interesting to know!

**Comment by thisroot** [comment]
Hi @Silmathoron, into the "limits" library which supply with sygwin not have LONG_LONG_MAX type, I changed this type on a LLONG_MAX, and this step has been continued, and i got a new errors, but this is a other story.

**Comment by Silmathoron** [comment]
Ok, good!
If you run into other errors, you'll probably get answers more quickly if you post on the mailing list.
Also if you manage to get NEST running on widows, please give us a feedback on what you did so we can add a tutorial on the website ;)
Good luck!
