### ISSUE TITLE
Enhancement of NEST input/output devices for interactive purposes (e.g. for MUSIC)

### ISSUE THREAD

**Issue by uahic** [nest/nest-simulator#550]
I would like to open a discussion about some enhancements to the NEST C++ level to improve interactive remote-control and since it requires modifications to existing code I would like to hear others opinions first. 

Issues:

- Phillip Weidel has built a very useful weight-recorder but as all the other devices it does not allow streaming the buffer values out via MUSIC. 

- Spike/Current,... generators cannot be steered in an efficient way (you basically have to go over Python/SLI to change the spike-rate)

Proposed solution (very roughly):

For example the recording_device class could offer a /to_music flag and either the music_cont_out_proxy and the recording_device are referring to the same underlying implementation or they duplicate it; The specific recorder has to require some more properties (MUSIC related channel name,...) if this flag is set by the user

Input devices seem to be more tricky, here the user should specify which of the float values are to be steered and the device then requests the NEST API to setup a continuous input port with the matching channel width. 

Potential use cases:
- Visualization (weight recorder)
- Neurorobotics applications/research/Master theses

**Comment by heplesser** [comment]
Superseded by NESTio project, therefore closing.
