### ISSUE TITLE
Add deprecation warnings for features that will disappear with NEST 3.

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#552]
NEST 2.12 should issue deprecation warnings for any functions or models that will not be part of NEST 3 and suggest alternatives. Warnings are limited to PyNEST, since few people write SLI these days except for tests.

The critical change in NEST 3 is that subnets will disappear and thus all functions based on subnets. For more on `GIDCollection`s, see #455. Below is a list of model and functions that I suggest to be deprecated.

## Models
- `subnet`: work with `GIDCollection`s instead
- `aeif_cond_alpha_RK5`: we need to converge on one implementation for this model

## PyNEST functions
- `BeginSubnet`: no longer needed, work with `GIDCollection`s
- `EndSubnet`: no longer needed, work with `GIDCollection`s
- `CurrentSubnet`: irrelevant without subnets
- `GetChildren`: irrelevant without subnets, work with `GIDCollection`s 
- `GetLID`: LIDs disappear with subnets; used index into `GIDCollection`
- `GetLeaves`: elements of `GIDCollection`s are leaves
- `GetNetwork`: irrelevant without subnets, script is responsible for retaining structure information if needed
- `GetNodes`: you have them in `GIDCollection`s
- `LayoutNetwork`: use `Create(<model>, n=<number>)` and get a `GIDCollection`
- `DataConnect`: use `Connect()` with `one_to_one` rule.

## Notes
- `PrintNetwork` in its current form depends on subnets. I suggest we let it print information from `ModelRangeManager` instead, i.e., list showing GID ranges and pertaining models.

**Comment by Silmathoron** [comment]
@heplesser preparing the PR for the correct ``t_ref`` implementation in the AEIF models, I just remembered that ``aeif_cond_alpha_multisynapse`` is also based on ``aeif_cond_alpha_RK5``... shall we switch it to GSL?

**Comment by heplesser** [comment]
@Silmathoron Would you have time to do this this week?

**Comment by Silmathoron** [comment]
Maybe... but I've got the NESTML workshop so probably more like this week-end
