### ISSUE TITLE
Bug in NEST-INSTALLATION-SYSTEM

### ISSUE THREAD

**Issue by priyankarroychowdhury3** [nest/nest-simulator#561]
If absolute path is not used during cmake, message will be displayed that NEST is correctly installed but in reality when you want to call NEST by some Python file, import Python error is obtained. On further analysis, it is found that most of the necessary files in /install/lib/python2.7/site-packages are missing.

Only when absolute path is used in cmake, the installation is done accurately.

**Comment by heplesser** [comment]
@jougs Could you take a look? Maybe we should ensure that CMake requires and absolute path?

**Comment by heplesser** [comment]
As far as I understand the [CMake docs](https://cmake.org/cmake/help/latest/command/set.html), CMake should convert the relative path to an absolute one, at least in CMake 3.8. I will make explicit in our documentation that one should provide absolute paths.
