### ISSUE TITLE
Autocomplete for PyNEST API functions in editors

### ISSUE THREAD

**Issue by zbarni** [nest/nest-simulator#564]
Currently autocomplete features are not possibly with PyNEST in editors such as PyCharm. Reason for this are the dynamic imports in __init.py__:

    for name in os.listdir(os.path.join(os.path.dirname(__file__), "lib")):
        if name.endswith(".py") and not name.startswith('__'):
            exec("from lib.{0} import *".format(name[:-3]))`

One solution is to add imports manually, possibly also after the loop,

    from lib.hl_api_connections import *
    from lib.hl_api_helper import *
etc.
Future modules would require manual addition in the script, but at least the base functions are there.

**Comment by heplesser** [comment]
@apeyser Could you take a look at this?

**Comment by apeyser** [comment]
It shouldn't be exec, but it shouldn't be static either, but  should use importlib module (which probably doesn't fix PyCharm, but it's still cleaner than this).

**Comment by heplesser** [comment]
Closing, the work in #1150 goes a way to addressing this, a perfect solution is not possible.
