### ISSUE TITLE
makeallhelp does not exist in dictionary

### ISSUE THREAD

**Issue by maharjun** [nest/nest-simulator#570]
The following command 

    sli --userargs=$NEST_SRC_DIR/examples/MyModule/:$NEST_SRC_DIR/examples/MyModule/sli/ \
    $NEST_INSTALL_DIR/share/nest/sli/install-help.sli

results in the following error
    
    SLI v2.11.0 (C) 2004 The NEST Initiative
    Generating on-line help pages for NEST ...
   
    Nov 29 14:09:23 SLIInterpreter::execute [Error]: DictError
        Key '/:makeallhelp' does not exist in dictionary.

This results in a error (`ERROR: 126` as gven by the CMake script) while compiling help for MyModule and consequently, any other user defined module. This has occured somewhere in the changes made to install-help.sli

**Comment by heplesser** [comment]
@maharjun In NEST Master, we recently moved help generation from SLI to Python. This is also changed in [`examples/MyModule/CMakeLists.txt:270ff](https://github.com/nest/nest-simulator/blob/782d30a6dccb5452250d2289423c812f3e8947bb/examples/MyModule/CMakeLists.txt#L270). If you create your own module before this change was merged into master, you need to update the `CMakeLists.txt` file in you module's directory.

Let me know if this helps and please close the issue if it does.

**Comment by maharjun** [comment]
@heplesser Yup this seems to work fine. Thanks for the clarification
