### ISSUE TITLE
NEST master (92d53f9) does not compile on K

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#581]
The current master branch does not compile on K due to the following error:

```bash
"/home/ra000024/a03303/opt/nest-simulator/nestkernel/connection_manager.cpp", line 1141: error: no operator "<<" matches these operands
            operand types are: std::deque<nest::ConnectionID, std::allocator<nest::ConnectionID>> << std::deque<nest::ConnectionID, std::allocator<nest::ConnectionID>>
          connectome << conns_in_thread;
                     ^

"/home/ra000024/a03303/opt/nest-simulator/nestkernel/connection_manager.cpp", line 1182: error: no operator "<<" matches these operands
            operand types are: std::deque<nest::ConnectionID, std::allocator<nest::ConnectionID>> << std::deque<nest::ConnectionID, std::allocator<nest::ConnectionID>>
          connectome << conns_in_thread;
                     ^

"/home/ra000024/a03303/opt/nest-simulator/nestkernel/connection_manager.cpp", line 1233: error: no operator "<<" matches these operands
            operand types are: std::deque<nest::ConnectionID, std::allocator<nest::ConnectionID>> << std::deque<nest::ConnectionID, std::allocator<nest::ConnectionID>>
          connectome << conns_in_thread;
```
However, a few lines below it complains, that exactly that function is not referenced from anywhere (modulo the `&`, changing the function definition to pass-by-value also doesn't work, and in any case would not be a desirable change ):

```bash
"/home/ra000024/a03303/opt/nest-simulator/nestkernel/connection_manager.cpp", line 1090: warning: function "operator<<(std::deque<nest::ConnectionID, std::allocator<nest::ConnectionID>> &, std::deque<nest::ConnectionID, std::allocator<nest::ConnectionID>> &)" was declared but never r
eferenced
  static inline std::deque< nest::ConnectionID >& operator<<(
```

Can anyone explain this imho rather strange behaviour of the compiler? It does not appear on JUQUEEN, our local cluster, or my laptop.

Here's my cmake line
```bash
cmake -DCMAKE_TOOLCHAIN_FILE=Platform/Fujitsu-Sparc64 -DCMAKE_INSTALL_PREFIX:PATH=/home/ra000024/a03303/opt/nest-simulator.install/ -Dwith-gsl=OFF -Dwith-optimize="-Kfast -x1" -Dwith-defines="-DUSE_PMA" -Dwith-python=OFF -Dwith-warning=OFF ../nest-simulator
```
@JanneM @jougs @suku248 @janhahne

**Comment by heplesser** [comment]
@jakobj For some reason, `operator<<()` is defined with the `static` keyword
```C++
static inline std::deque< nest::ConnectionID >& operator<<(...
```
I do not even know what `static` means when applied to a function that is not a member of a class. But I noticed  that Eclipse also tells me that the function is never used, and that removing `static` removes that warning.

**Comment by jakobj** [comment]
Yes, you are right. I was wondering about that as well. Apparently this lets you define functions with the same name and signature but different behaviour across different .cpp files (see for example [this discussion on stackoverflow](https://stackoverflow.com/questions/10876930/should-one-never-use-static-inline-function)). however, removing the static keyword does not help in this particular case. the compiler still complains that no operator matches these operands.

**Comment by JanneM** [comment]
When we built NEST 2.6(?) on K some years ago, the Fujitsu compiler choked on overloading the << operator. We ended up patching the code to change them into regular methods and method calls instead.

**Comment by janhahne** [comment]
We had a similar problem with the gap-junction implementation and the K compiler. In the end we replaced the operator by functions (see https://github.com/nest/nest-simulator/pull/122/commits/af7632297d947f86e143eea405753e4e65f46ebd)

**Comment by jakobj** [comment]
thanks for you comments! I will create a PR soon to replace `operator<<` with a regular function, to make sure NEST stays K compatible.
