### ISSUE TITLE
Convention for neurons and connections named after modelers?

### ISSUE THREAD

**Issue by SepehrMN** [nest/nest-simulator#585]
Greetings,

Is there some form of a convention for neurons and connections named after the authors of publications?

I observed the following discrepancies:
ht_neuron and ht_connection (HTConnection)
but elsewhere we have mcculloch_pitts_neuron

I'll create a new model and I'm hoping to use kay_phillips_neuron and kay_phillips_connection

**Comment by heplesser** [comment]
@SepehrMN We have not been 100% consistent, but the general rule is to use build the name as 
```
<model category>_<initials>_year
```
Examples are
- `iaf_chs_2007`
- `iaf_chxk_2008`
- `iaf_tum_2000`
We haven't applied these rules completely consistently, but for neuron models that are mainly known from a single paper and that have not been given a more general name in the publications that introduced them (e.g. `aeif` and `amat` models), one should stick to this rule.

**Comment by SepehrMN** [comment]
@heplesser Many thanks! could not find this here: https://nest.github.io/nest-simulator/neuron_model_naming

I suppose `binary` <category> would suffice for both stochastic and threshold types.

**Comment by jougs** [comment]
Fixed by #611.
