### ISSUE TITLE
Wrong units of the structural_plasticity_update_interval variable

### ISSUE THREAD

**Issue by sdiazpier** [nest/nest-simulator#588]
Currently, the structural_plasticity_update_interval variable, which defines the time between changes in the connections of the network (creation and deletion of synapses), is defined in number of simulation steps. This should be changed to ms so that it is more intuitive to the user and standardized to the other time variables in NEST.

**Comment by hakonsbm** [comment]
Fixed with f98057a5a5add2fa08b2a0a062a63ae196e9e658, now in https://github.com/compneuronmbu/nest-simulator/tree/nest-3.
