### ISSUE TITLE
Problem installing NEST on macOS Sierra

### ISSUE THREAD

**Issue by LeRyc** [nest/nest-simulator#591]
I tried to install NEST the following way:
- cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/opt/nest -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ../nest-simulator/
- make
- make install
- make installcheck

When running 'make installcheck' all tests are successful except for the PyNEST tests (Phase 7). The following error message is printed:

Phase 7: Running PyNEST tests.
------------------------------

  Using nosetests.

  Failure: ImportError (dlopen(/anaconda/envs/env27neuro/nest/nest-simulator/opt/lib/python2.7/site-packages/nest/pynestkernel.so, 8): Symbol not found: _PyBaseString_Type
   in /anaconda/envs/env27neuro/nest/nest-simulator/opt/lib/python2.7/site-packages/nest/pynestkernel.so) ... ERROR
  ERROR: Failure: ImportError (dlopen(/anaconda/envs/env27neuro/nest/nest-simulator/opt/lib/python2.7/site-packages/nest/pynestkernel.so, 8): Symbol not found: _PyBaseString_Type
    File "//anaconda/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
  ImportError: dlopen(/anaconda/envs/env27neuro/nest/nest-simulator/opt/lib/python2.7/site-packages/nest/pynestkernel.so, 8): Symbol not found: _PyBaseString_Type
  FAILED (errors=1)

  PyNEST tests: 1
     Passed: 0
     Failed: 1

NEST Testsuite Summary
----------------------
  NEST Executable: /anaconda/envs/env27neuro/nest/nest-simulator/opt/bin/nest
  SLI Executable : /anaconda/envs/env27neuro/nest/nest-simulator/opt/bin/sli
  Total number of tests: 221
     Passed: 220
     Failed: 1 (1 PyNEST)

***
*** There were errors detected during the run of the NEST test suite!
***
*** Please report the problem at
***     https://github.com/nest/nest-simulator/issues
***
*** To help us diagnose the problem, please attach the archived content
*** of these directories to the issue:
***     - '/anaconda/envs/env27neuro/nest/nest-build/reports'
***     - '/var/folders/76/dgsf315n67b6r0xn02xy0c7c0000gn/T//nest.SmHhd'
***

make[3]: *** [CMakeFiles/installcheck] Error 1
make[2]: *** [CMakeFiles/installcheck.dir/all] Error 2
make[1]: *** [CMakeFiles/installcheck.dir/rule] Error 2
make: *** [installcheck] Error 2

[reports.zip](https://github.com/nest/nest-simulator/files/649103/reports.zip)
[nest.SmHhd.zip](https://github.com/nest/nest-simulator/files/649111/nest.SmHhd.zip)

**Comment by SepehrMN** [comment]
Not sure but it may be that the testsuite is using system python instead of the one used by you. Try using NEST and see if it works. You can try adding path of your python to your .bashrc / .bash_profile.

**Comment by heplesser** [comment]
Indeed, it seems there is a mix of Python 2.7 and 3.5 here. You may want to take a look at [macOS suggstions by Henrik Lindén](https://github.com/nest/nest-simulator/issues/484#issuecomment-258427350).

**Comment by LeRyc** [comment]
Thank you guys! Everything works fine now.

It somehow was not enough to create a conda environment with version 2.7 when anaconda was version 3.5. I now installed anaconda 2.7 and all problems solved.

**Comment by heplesser** [comment]
Closing as @LeRyc reported that all works well now.
