### ISSUE TITLE
Incorrect linking in helpindex.html

### ISSUE THREAD

**Issue by janhahne** [nest/nest-simulator#592]
The links in `$INSTALLDIR/share/doc/nest/help/helpindex.html` now link to 

`$INSTALLDIR/share/doc/nest/help/$BASEDIR?/$NAME.html` instead of `$INSTALLDIR/share/doc/nest/help/sli/$NAME.html` or `$INSTALLDIR/share/doc/nest/help/cc/$NAME.html` depending on `$NAME`

I did a quick search but failed to find the corresponding code to fix this. @steffengraber could you have a look at this (maybe this was introduced with PR #464)?

**Comment by steffengraber** [comment]
@janhahne Thanks for debugging. 
There is a pull request to fix it: #593.
