### ISSUE TITLE
Structural plasticity disables heterogeneous connectors

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#596]
Structural plasticity currently disables connectors when deleting a connection from a heterogenenous connector (no, this is not a duplicate of #565 ). In `disconnect`, the connector is validated, which clears the `has_primary` and `has_secondary` flags (https://github.com/nest/nest-simulator/blob/master/nestkernel/connection_manager.cpp#L645). After calling `delete_connection`, however, these values are supposed to be read (https://github.com/nest/nest-simulator/blob/master/nestkernel/connector_model_impl.h#L522), which always leads to these flags being `false`. Upon packing the pointer again (https://github.com/nest/nest-simulator/blob/master/nestkernel/connector_model_impl.h#L595), these flags are hence set to `false`, effectively disabling the connector.
The following sli script demonstrate the issue:
```postscript
/BuildNetwork
{
  ResetKernel

  /iaf_psc_delta 2 Create
  /spike_detector 1 Create /sd Set

  1 << /I_e 600. >> SetStatus
  [1] [2] << /rule /all_to_all >> << /weight 0. /model /static_synapse >> Connect
  [1] [2] << /rule /all_to_all >> << /weight 0. /model /stdp_synapse >> Connect
  [1] [sd] Connect
} def

BuildNetwork

100 Simulate

sd GetStatus /n_events get /n_events_target Set

BuildNetwork

[1] cvgidcollection [2] cvgidcollection << /rule /all_to_all >>
  << /model /static_synapse >> Disconnect_g_g_D_D

100 Simulate

sd GetStatus /n_events get == n_events_target ==
```

I have implemented a fix, by avoiding unpacking the pointer in `disconnect` (https://github.com/nest/nest-simulator/blob/master/nestkernel/connection_manager.cpp#L645) and will create a PR tomorrow.
I am wondering in how far this relates to #589 @sanjayankur31 ?
@sdiazpier, could you have a look at this?

**Comment by sdiazpier** [comment]
Hi dear @jakobj, your analysis sounds correct. Thank you for taking a deep look into this. :+1:
