### ISSUE TITLE
How to record free elements in structural plasticity

### ISSUE THREAD

**Issue by ErbB4** [nest/nest-simulator#598]
Hi everyone,
I want to record the number of free axonal/dendritical elements with time during simulation in structural plasticity to check the synaptic dynamics. But I didn't find it in the sample code. Could someone please help me with it? Thanks in advance!
Best,
ErbB4

**Comment by heplesser** [comment]
@ErbB4 The best place for questions regarding the use of NEST is the NEST User mailing list, see http://www.nest-simulator.org/community/ for information on how to subscribe and post. We use Github issues to manage errors and concrete enhancement proposals. I will close this issue and look forward to your post on NEST User.
