### ISSUE TITLE
Wrong import in hl_api from python 3

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#617]
After merging #580, an incorrect import for python 3 was included, this make ``import nest`` lead to

    /home/tfardet/.nest-2.10.0-install/lib64/python3.5/site-packages/nest/lib/hl_api_connections.py in <module>()
         29 from .hl_api_simulation import GetKernelStatus, SetKernelStatus
         30 from .hl_api_subnets import GetChildren
    ---> 31 import hl_api_helper as hlh
         32 import numpy
         33 
    
    ImportError: No module named 'hl_api_helper'

**Comment by heplesser** [comment]
Fixed by merge of #620.
