### ISSUE TITLE
lib/sli/rcsinfo.sli

### ISSUE THREAD

**Issue by apeyser** [nest/nest-simulator#63]
Ok, I have this file in the tree, and it gets updated to:
```
statusdict /rcsinfo (no_rcsinfo_available) put
```

without which, tests fail. Is this thing still necessary?

@jougs

**Comment by jougs** [comment]
We want to have a unique identifier for the builds and to put into documentation and such.

The `/rcsinfo` value is updated by `extras/create_rcsinfo.sh`, which uses `svnversion` and of course does not work anymore now.

My plan was to update the script to use a combination of `git rev-parse --short HEAD` and `git rev-parse --abbrev-ref HEAD`. Feel free to address this issue if you have a better idea!

**Comment by apeyser** [comment]
The sha is useful to get back to git when you've lost the connection with git --- so, embedding it during the production of the distribution tar ball. If you're working in the tree, you can just call git rev-parse, right? If the goal is to put something in the install tree to check when you get confused, I guess it could be part of make install.

It's a bit of a pain, so it shouldn't be in many places. Probably requires looking at automake and cleaning that up for make install & make dist

**Comment by jougs** [comment]
With #109 merged, the file you mention above gets updated to something like
```
statusdict /rcsinfo (master@4dd1cb6) put
```
which should be more useful.
