### ISSUE TITLE
Can't import nest from python on macOS Sierra

### ISSUE THREAD

**Issue by TomBugnon** [nest/nest-simulator#636]
Hi all,

I am having difficulty launching nest from python on macOS...

I have been installing nest from a python2.7 conda virtual environment on macOS using homebrew according to the instructions given on your website ( `brew install nest --with-python` ). The package installs correctly in /usr/local/Cellar/nest/2.10.0_3
I add the pynest folder to the python path 
`export PYTHONPATH=/usr/local/Cellar/nest/2.10.0_3/lib/python2.7/site-packages:PYTHONPATH`

When launching python and trying to import nest, python crashes:
`> python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import nest
Assertion failed: (out != NULL), function execute, file ../../sli/sli_io.cc, line 401.
[1]    21088 abort      python`

I uninstalled nest (`brew uninstall nest`) and repeated the same process this time in a python3 conda environment. This time I change the python path using `export PYTHONPATH=/usr/local/Cellar/nest/2.10.0_3/lib/python3.5/site-packages:PYTHONPATH`.
When trying to import nest I obtain the following error : 
`Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/nest/2.10.0_3/lib/python3.5/site-packages/nest/__init__.py", line 53, in <module>
    import lib.hl_api_helper as hl_api
ImportError: No module named 'lib.hl_api_helper'`

This looks like a python3 syntax problem that should have been resolved in the later versions as I understand from digging the issue section. It seems the version installed by brew isn't the same as the current git master.
I also tried the manual compilation but receive a number of errors,.
Would you have any guidance on how I could get this working on mac?
 Thank you so much for your help.
Tom

**Comment by heplesser** [comment]
See also #484

**Comment by heplesser** [comment]
@TomBugnon Could you try (in the Python 2.7 environment) to install the newest version of NEST using
```
brew install nest --with-python --HEAD
```

**Comment by TomBugnon** [comment]
Installing the HEAD in the python 2.7 solved it. It works nicely, many thanks.
