### ISSUE TITLE
GetKernelStatus causes MPI communication of delay extrema

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#637]
As mentioned in #628, `0 GetStatus` leads to an update of delay extrema across all MPI processes via a call to `MPIAllgather` (https://github.com/nest/nest-simulator/blob/master/nestkernel/connection_manager.cpp#L331 ff). As this is also done prior to simulating in `prepare_simulation_` (https://github.com/nest/nest-simulator/blob/master/nestkernel/simulation_manager.cpp#L526), and hence is not required in `0 GetStatus` calls to allow correct simulation. It is merely a convenience, that `0 GetStatus` returns the correct global min/max values across different MPI ranks. However, this causes significant overhead for a large number of processes for every call to `0 GetStatus`, which is for example used to determine ranges of GIDs when creating nodes.
I propose to remove `update_delay_extrema_` from the `GetKernelStatus` calls and to return an "invalid" value, in case `prepare_simulation` was not called before. We can add an additional (SLI) function, that allows the user to update delay extrema across all MPI processes.
@heplesser @suku248 @jougs

**Comment by jougs** [comment]
From my perspective, `0 GetStatus`/`GetKernelStatus` are meant to inform the user. Providing correct values only _after_ the simulation is thus not a good thing IMO. I think it's useful for users to be able to retrieve the correct delay extrema to quickly check delay distributions (by querying the synapse model''s extrema) and possibly also to get a feeling for buffer sizes and communication intervals. I also dislike breaking with our *One interface to rule them all` philosophy by introducing an extra function for this specific functionality. 

I thus oppose changes to the current behavior.

Looking at [hpc_benchmark.sli](https://github.com/nest/nest-simulator/blob/master/examples/nest/hpc_benchmark.sli), which was referenced in #628, I realized that two of three uses of `GetStatus` there are indeed suboptimal, but also not needed at all. `/E_to E_from NE add def` and `/I_to I_from NI add def`should do the trick without any expensive function calls. **This should be fixed**.

Moreover, I suggest to update the documentation of all functions that involve communication to point out prominently that they do this and that their run time might depend on the number of processes.

**Comment by heplesser** [comment]
@jakobj I agree with @jougs in this matter. The main problematic point you mention, calling `0 GetStatus` to obtain GID information is bad script design today, and will become obsolete when `Create` returns `GIDCollection` in NEST3.  Global delay information may, on the other hand be interesting during the network construction phase, in particular if networks are built with randomized delays. We should therefore *not* change the behavior of `0 GetStatus`.

Would you close the issue?

**Comment by jakobj** [comment]
Yes, I see your point and am happy to close this. I will create a PR soon to fix the hpc_benchmark script, avoiding the `0 GetStatus` calls.
