### ISSUE TITLE
pynest tests fails when GSL is OFF and Python is ON

### ISSUE THREAD

**Issue by lekshmideepu** [nest/nest-simulator#638]
On JURECA, the following tests failed when tested  with Python and without GSL

ERROR: test_targets (nest.tests.test_sp.test_issue_578_sp.TestIssue578)
      raise _kernel.NESTError(encode(errorstring))
  pynestkernel.NESTError: UnknownModelName in SetDefaults_l_D: /iaf_cond_exp is not a known model name. Please check the modeldict for a list of available models. A frequent cause for this error is that NEST was compiled without the GNU Scientific Library, which is required for the conductance-based neuron models.
  ERROR: Weight Recorder rports
      raise _kernel.NESTError(encode(errorstring))
  pynestkernel.NESTError: UnknownModelName in GetDefaults_l: /aeif_cond_alpha_multisynapse is not a known model name. Please check the modeldict for a list of available models. A frequent cause for this error is that NEST was compiled without the GNU Scientific Library, which is required for the conductance-based neuron models.
  FAIL: test_gaussian_growth_curve (nest.tests.test_sp.test_growth_curves.TestGrowthCurve)
      raise AssertionError(_build_err_msg())
  AssertionError: 
  FAIL: test_linear_growth_curve (nest.tests.test_sp.test_growth_curves.TestGrowthCurve)
      raise AssertionError(_build_err_msg())
  AssertionError: 
  FAILED (SKIP=23, errors=2, failures=2)

  PyNEST tests: 547
     Passed: 543
     Failed: 4

**Comment by lekshmideepu** [comment]
Informed @sdiazpier about it as it is related to Structural plasticity

**Comment by lekshmideepu** [comment]
I am working on a PR to include this job (Python: ON and all others: OFF) with Travis

**Comment by heplesser** [comment]
Closing as this is fixed by #640.
