### ISSUE TITLE
 Travis build jobs on multiple OSs(OSX,Linux)

### ISSUE THREAD

**Issue by lekshmideepu** [nest/nest-simulator#639]
Currently, Travis jobs are building only on Linux worker machines. Working on adding the feature of building jobs also on OSX

**Comment by heplesser** [comment]
@lekshmideepu Any news on this one?

**Comment by lekshmideepu** [comment]
Will continue to work on this once the PR  #1057 is merged. Otherwise it would be a bit complex as it will affect the same .yml file.

**Comment by heplesser** [comment]
@lekshmideepu Ping!
