### ISSUE TITLE
git diff --name-only $TRAVIS_COMMIT_RANGE

### ISSUE THREAD

**Issue by apeyser** [nest/nest-simulator#64]
@tammoippen: in build.sh, we do
```
file_names=`git diff --name-only $TRAVIS_COMMIT_RANGE`
```
Inside my repo on some pushes, this seems to return incorrect/unreachable references. I haven't yet identified the cause, or a travis bug report on this, but it may be a problem with history rewrites on pushes that it may end up referencing old, non-existent commits.

**Comment by tammoippen** [comment]
Hi @apeyser ,
TRAVIS_COMMIT_RANGE has some problems with history rewrites. I am working on correcting this with  the github api: https://developer.github.com/v3/pulls/#list-pull-requests-files

**Comment by tammoippen** [comment]
I am closing this issue as PR #75 is closed. @apeyser please reopen if the issue persists.
