### ISSUE TITLE
Add c++ unit tests

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#649]
In order to expand our testsuite with standardized unittest for c++ functions (see, e.g., librandom), we need to include a c++ testing framework into NEST's tests. Currently, we consider [ctest](https://cmake.org/Wiki/CMake/Testing_With_CTest) and [google test](https://github.com/google/googletest/). Both have compatible licenses (BSD like). We need to make sure that the testsuite can run on many differeny systems, since NEST is run on laptops, a variety of clusters and supercomputers. I will investige the two framework mentioned above and report back here. Any advice, suggestsions etc are welcome.

**Comment by heplesser** [comment]
Adding C++ tests is a good idea. We should evaluate carefully existing options. [Boost.test](http://www.boost.org/doc/libs/1_63_0/libs/test/doc/html/index.html) also appears to be quite popular, as well as [Catch](https://github.com/philsquared/Catch). I found some relevant discussion here: 
- http://alexott.net/en/cpp/CppTestingIntro.html
- https://www.reddit.com/r/cpp/comments/36pru0/best_way_to_do_unit_testing_in_c/

Several discussion contributions point out that good mocking support is equally important as good test support.
My impression from a first look is the Ctest is not a test framework, but rather a mechanism for running tests from Eclipse.

**Comment by jakobj** [comment]
I've started working on including boost.test, which seems like a good solution. For mocking there is [turtle](http://turtle.sourceforge.net/), apparently working great with boost. you can find the current progress in my fork under the [feature/cpptest](https://github.com/jakobj/nest-simulator/tree/feature/cpptest) branch. let me know what you think and what a good demonstration would look like. should we port the librandom test to the new framework?

**Comment by heplesser** [comment]
This is in place with NEST 2.16.0.
