### ISSUE TITLE
NEST runs into assertion when gap junctions are used without wfr

### ISSUE THREAD

**Issue by janhahne** [nest/nest-simulator#655]
NEST runs into an assertion (event.h, line 978) when gap junctions are used without waveform relaxation. The error was introduced with PR #607 - the `GapJunctionEvent` `coeff_length_` parameter is only set when wfr is used, but needs to be set anyway (also without wfr use). The fix is a one liner, i will submit a PR shortly.

**Comment by heplesser** [comment]
Fixed by #656
