### ISSUE TITLE
Compile NEST on JUQUEEN with jemalloc and gsl

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#657]
I am trying to compile NEST on JUQUEEN with jemalloc as the allocator. I have successfully compiled jemalloc and NEST without gsl. However, neuron models supporting gap junctions need NEST to be compiled with gsl. When loading the gsl module and changing my cmake line to
```bash
cmake -DCMAKE_TOOLCHAIN_FILE=Platform/BlueGeneQ_GCC -DCMAKE_INSTALL_PREFIX:PATH=/homea/jinb33/jinb3317/opt/nest-simulator_exp.install/ -Dwith-python=OFF -Dstatic-libraries=ON -Dwith-optimize=-O2 -Dwith-mpi=ON -Dwith-libraries=/homea/jinb33/jinb3317/opt/jemalloc-4.4.0.install/lib/libjemalloc.a -Dwith-gsl=ON /homea/jinb33/jinb3317/opt/nest-simulator_exp
```
 I get the following error while compiling:
```bash
/bgsys/local/gsl/2.1_strict/lib/libgsl.a(zuf.o): In function `zuf_set': 
/homea/software/mathprod/JUQUEEN/GSL/gsl-2.1/rng/zuf.c:128: undefined reference to `__f64tou64rz'
/bgsys/local/gsl/2.1_strict/lib/libgsl.a(ranlxd.o): In function `ranlxd_get':
/homea/software/mathprod/JUQUEEN/GSL/gsl-2.1/rng/ranlxd.c:152: undefined reference to `__f64tou64rz'
/bgsys/local/gsl/2.1_strict/lib/libgsl.a(ranlxs.o): In function `ranlxs_get':
/homea/software/mathprod/JUQUEEN/GSL/gsl-2.1/rng/ranlxs.c:202: undefined reference to `__f64tou64rz'
```
I guess this could be an issue of using gcc for jemalloc and NEST, while gsl was probably compiled with the xlc compiler. I hence tried to compile gsl 2.1 myself using gcc, but I get the following error:
```bash
/bgsys/drivers/toolchain/V1R2M4_base/gnu-linux/lib/gcc/powerpc64-bgq-linux/4.4.7/../../../../powerpc64-bgq-linux/bin/ld: attempted static link of dynamic object `./.libs/libgsl.so'
```
Has anyone already solved this before?
@apeyser @tammoippen @sdiazpier @terhorstd @mschmidt87

**Comment by heplesser** [comment]
It looks like (i) make is still trying to link gsl from a system directory and (ii) is trying to link `libgsl.so`, i.e., a dynamic library version. Do you have `libgsl.a` installed in your own installation of GSL? You may want to try to specify the path to your GSL installation as argument to `-Dwith-gsl`.

**Comment by apeyser** [comment]
I agree with hep - I think you're running into the pain of BGQ incorrectly remapping dynamic links to static links. You may also need to hack the gsl CMake instructions to get a proper link line.

**Comment by heplesser** [comment]
@jakobj Any progress on this?

**Comment by jakobj** [comment]
No, not so much. I finally decided that gap junction simulations are typically so small that they don't really need jemalloc. This is of course not true for other network simulations the require gsl for the neuron models. Unfortunately I don't have too much time to look into this further.

**Comment by jougs** [comment]
With the imminent end of life of JUQUEEN, I am not sure if we can/should actually fix this. I'm thus closing this. If anyone thinks otherwise (or has the resources to fix this), feel free to re-open.
