### ISSUE TITLE
Implement recording of signals provided by stimulating devices

### ISSUE THREAD

**Issue by appukuttan-shailesh** [nest/nest-simulator#658]
This query was originally intended towards the development of the PyNN-NEST interface, but has a more general application within NEST. The objective was to record the profile of injected current, but:
1) the 'multimeter' object in NEST does not appear to allow recording from stimulating devices, and seems to be restricted to neurons. It doesn't throw errors, but returns empty (similar to issue #578 )
2) the alternative approach was to attempt to record the currents from the neurons. But different cell types have different sets of 'recordables' and the injected current doesn't seem to be one of them. 

@heplesser informed me that this would require small additions to the model, but could be achieved. I plan to look into this, and shall update here if I make any progress.

**Comment by appukuttan-shailesh** [comment]
I think I have managed to implement the record feature for the AC current source. The modified files are here (not yet ready for a pull):
[ac_generator.h](https://github.com/appukuttan-shailesh/PyNN_testData/blob/master/ac_generator_record.h)
[ac_generator.cpp](https://github.com/appukuttan-shailesh/PyNN_testData/blob/master/ac_generator_record.cpp)

A sample output for the code [here](https://github.com/appukuttan-shailesh/PyNN_testData/blob/master/test_AC.py):
![ac_output](https://cloud.githubusercontent.com/assets/24866517/23031309/d1dcda4c-f470-11e6-9bfe-4a6ff9eb5450.png)

@heplesser : It would be great if you could take a look before I move on to the other models.
_The lines/blocks that have been added have been tagged issue #658 for a quick look_

Some of the queries I had were:
1) I found that I wasn't allowed to give any arbitrary name for the parameter being recorded:
``` c++
insert_( Name( names::amplitude ), &ac_generator::get_inj_ );
```
and had to use one of the existing names in the context (e.g. amplitude, phase). I went ahead with 'amplitude' here, but a different name (such as i_inj) would be more appropriate.

2) As this code is based on that for _sinusoidal_poisson_generator_, do let me know if I have accidentally added bits which are not relevant to the recording feature and can thus be removed.

3) I see that for both the voltage and current traces (in the above figure), values are not obtained for t = t_stop. Is there some workaround for this, or do I simply make a corresponding increment to the simulation runtime?

_This is the first time I have used the nest simulator in any capacity, and so apologies if I have made any noobie mistakes._

**Comment by appukuttan-shailesh** [comment]
I think I have solved my first query by adding:
`extern const Name I_inj;      //!< Current from StimulatingDevice`
to [nest_names.h](https://github.com/nest/nest-simulator/blob/master/nestkernel/nest_names.h), and adding
`const Name I_inj( "I_inj" );`
to [nest_names.cpp](https://github.com/nest/nest-simulator/blob/master/nestkernel/nest_names.cpp)

Changes would accordingly be made in _ac_generator_ files, such as:
``` python
insert_( Name( names::amplitude ), &ac_generator::get_inj_ );
```
changed to:
``` python
insert_( Name( names::I_inj ), &ac_generator::get_I_inj_ );
```
and renaming the earlier variable inj_ with I_inj_ throughout (for better readability)

**Comment by heplesser** [comment]
@appukuttan-shailesh Your code looks quite fine, but it seems you are working on the basis of NEST 2.10. Please use the most recent code from Github as the basis of any development to minimize the risk of merge conflicts later. You don't seem to have added unnecessary code.

Names are a complex matter. One purpose of the `names` system is to keep some consistency in naming across models. Also, from the perspective of the current generator, the current is *not* an injected current---that is the perspective of the neuron. I think the best name to choose would simply be `I`, also avoiding `inj` in the code, i.e.,
```c++
insert_( names::I ), &ac_generator::get_I_ ):
```
The comment "specific to Mirollo-Strogatz" on `I` in `nest_names.h` should then be removed.

Data is first buffered in the `UniversalDataLogger` instance of the model and then collected from there by `multimeter` and written to file (or memory) during the next minimum-delay interval. Therefore, some data will be missing at then end.

**Comment by appukuttan-shailesh** [comment]
Thanks for pointing that out. I have now updated my repository to the latest version, and made the necessary changes. I have implemented the record feature for the following models:
1) ac_generator
2) dc_generator
3) step_generator
4) noise_generator

A sample output for the above ([code](https://github.com/appukuttan-shailesh/PyNN_testData/blob/master/nest_test_record_all.py)):
![output_all](https://cloud.githubusercontent.com/assets/24866517/23131353/f7cfac22-f789-11e6-9671-0b288fca80e1.png)

Shall initiate a pull request so that you can review the changes.

**Comment by appukuttan-shailesh** [comment]
@heplesser : I was running the tests (_make installcheck_) and got the following output:

ERROR: test_synapse_deletion_one_to_one_no_sp (nest.tests.test_sp.test_disconnect.TestDisconnectSingle)
  TypeError: allgather() takes exactly 1 positional argument (2 given)
  FAILED (SKIP=11, errors=1)

  PyNEST tests: 548
     Passed: 547
     Failed: 1

NEST Testsuite Summary
----------------------
  NEST Executable: /home/shailesh/opt/nest/bin/nest
  SLI Executable : /home/shailesh/opt/nest/bin/sli
  Total number of tests: 772
     Passed: 771
     Failed: 1 (1 PyNEST)
 
The link to the [reports archive](https://github.com/appukuttan-shailesh/PyNN_testData/blob/master/reports.tar.gz)
