### ISSUE TITLE
Wrong "Monkeypatch" in warnings.showwarning

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#662]
In [``hl_api_helper.py``](https://github.com/nest/nest-simulator/blob/32fdfd8eab48499cfea33b9cd5832f3b00f1e5f1/pynest/nest/lib/hl_api_helper.py#L39), a python builtin function has been replaced with a custom one which has:

* a wrong number of arguments
* wrong argument names

This causes crash in scripts using both ``nest`` and the ``warnings`` module.

I'm not sure replacing builtin functions is a good idea, so the question is: **Is this really necessary?**
If so, I can make a PR to replace it (it is really easy); otherwise I would be in favor of suppressing lines 37 to 41 (for which I can also make a PR, which will be even easier ^^).

**Comment by physicalist** [comment]
I've run into the same issue when testing my NEST installation with `do_python.py`. Interestingly, only with Python3. Here's one of the error messages for reference:
```
======================================================================
ERROR: test_FindElements (nest.topology.tests.test_basics.BasicsTestCase)
Interface and result check for finding nearest element.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nest/topology/tests/test_basics.py", line 219, in test_FindElements
    n = topo.FindNearestElement(l, (0., 0.))
  File "/usr/local/lib/python3.6/site-packages/nest/topology/hl_api.py", line 1122, in FindNearestElement
    els = nest.GetChildren((lyr, ))[0]
  File "/usr/local/lib/python3.6/site-packages/nest/lib/hl_api_helper.py", line 230, in stack_checker_func
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nest/lib/hl_api_helper.py", line 120, in new_func
    show_deprecation_warning(func.__name__, alt_func_name, text=text)
  File "/usr/local/lib/python3.6/site-packages/nest/lib/hl_api_helper.py", line 91, in show_deprecation_warning
    warnings.warn('\n' + text)   # add LF so text starts on new line
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/warnings.py", line 99, in _showwarnmsg
    msg.file, msg.line)
TypeError: _warning() takes from 1 to 4 positional arguments but 6 were given

----------------------------------------------------------------------
```

The code section with the Monkey patch stems from 8d8b19cf53ae83981eb64d890aec5634365978e7 and even contains a [comment](https://github.com/nest/nest-simulator/blame/master/pynest/nest/lib/hl_api_helper.py#L44) that the functions would be removed in 2.6 - I guess that didn't happen?

**Comment by wmayner** [comment]
I've had the same issue—so far, it seems that this is the only incompatibility with Python 3.
