### ISSUE TITLE
ConnectLayers does not connect to thread siblings of devices

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#665]
In multithreaded simulations, `ConnectLayers` does not connect to thread siblings of devices. The following code:
```
0 << /local_num_threads 4 >> SetStatus

/nrns << /elements /iaf_psc_alpha /rows 2 /columns 2 >> CreateLayer def
/det << /elements /spike_detector /rows 1 /columns 1 >> CreateLayer def
nrns det  << /connection_type /convergent >> ConnectLayers

<< >> GetConnections ==
```
will connect only the neuron managed by thread 0 (neuron with GID 4) to the spike detector (instance on thread 0):
```
[<4,7,0,0,0>]
```
The other neurons should be connected to the thread-siblings of the spike detector on their respective threads. This is a regression from NEST 2.10, which created all connections:
```
[<5,7,1,0,0> <3,7,3,0,0> <2,7,2,0,0> <4,7,0,0,0>]
```

Originally reported by Elena Pastorelli on NEST User 20 Feb 2017.

**Comment by terhorstd** [comment]
closed by merge of #666
