### ISSUE TITLE
Replacement needed for PrintNetwork

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#679]
With subnets about to be removed by #480, the old `PrintNetwork` function needs replacement. There are three issues:

1. Since the simulator no longer represents network hierarchy, we need another way to present the network. 
1. The name `PrintNetwork` was always a bit of a misnomer, since it prints only the nodes.
1. `PrintNetwork` is hard-coded to write to `cout`, which breaks at the very latest when calling the command from Python.

Here is a proposal for a replacement for PrintNetwork.

## Content
Output should present the network information available from Modelrange Manager, i.e., GID ranges for different models. I would propose an output format like this:
```
  1 .. 100 iaf_psc_alpha
101 .. 102 poisson_generator
103        spike_detector
```
One could debate if 
- the last line should be `103 .. 103`
- model ID should be shown
- there should be a table header (similar to the format of dictionary output)
Column width is chosen based on the maximum GID in the network

## Command Name
The command name should reflect that the command prints node information only. Also, we want a command without any arguments for immediate output, but we may need one taking an output stream for redirecting output (see Python below). I would suggest (in SLI)
- `PrintNodes` as command without arguments
- `PrintNodesToStream` as command with ostream  argument
I think we cannot safely overload these two with a trie.

## Python
In Python, we have only `PrintNodes()`. This calls `PrintNodesToStream` with an `ostringstream` argument and then uses Python `print()` to output the result. This ensures that the command also works properly in Jupyter Notebooks.

**Comment by stinebuu** [comment]
The changes for this is implemented in the [compneuronmbu SubnetFreeTopology](https://github.com/compneuronmbu/nest-simulator/tree/fix-481-SubnetFreeTopology) branch.

**Comment by stinebuu** [comment]
@heplesser As this is implemented in the [nest-3 branch](https://github.com/compneuronmbu/nest-simulator/tree/nest-3) do we want to close this issue to be able to close the [Remove subnets](https://github.com/nest/nest-simulator/projects/2#card-2069522) project?

**Comment by heplesser** [comment]
Closing as this is fixed in the NEST 3 branch.
