### ISSUE TITLE
Version of dependencies/tools used by Travis

### ISSUE THREAD

**Issue by mschmidt87** [nest/nest-simulator#682]
This is a follow-up issue from the discussion in #680 suggested by @heplesser .

The initial reason to open this was the numpy version used by travis, which was not the latest release version of numpy (1.12.0) and so travis did not detect the but reported in #680.
As @heplesser noted, we should discuss which version of packages travis should take into account for the tests. 

Travis should test for the latest versions of packages, but also take older versions into account. The reason is that people might use e.g. the LTS version of Ubuntu and clusters/supercomputers tend to follow a more conservative strategy in updating packages. 
So, we should agree on a vector of versions for the principal dependencies of NEST.

**Comment by heplesser** [comment]
To keep complexity limited, I would propose that we have
- one test case with the oldest versions of tools we support
- one test case with "cutting edge" versions of tools, updated as least once a month
- possibly a test case with coming versions (release candidates) to be prepared
These cases should only be run for the "all included" variant, for all other cases in our test matrix we run one configuration only.

**Comment by heplesser** [comment]
Closing since problems of this type are exceedingly rare.
