### ISSUE TITLE
NEST built via Homebrew with Python{2,3} support misses Cython dependency

### ISSUE THREAD

**Issue by physicalist** [nest/nest-simulator#684]
In the current nest.rb Formula the Cython :build dependency prevents the build process.
This might be due to a recent change in how Homebrew checks external Python dependencies, but at least for me the Formula would not install due to unsatisfied dependency Cython,
despite having installed Cython with pip/pip3. This is on brew'ed Python2.7 & -3.6.
````
~ #> brew install nest --with-python
==> Installing nest from homebrew/science
nest: Unsatisfied dependency: cython
Homebrew does not provide special Python dependencies; install with:
  `pip install cython`
Error: An unsatisfied requirement failed this build.

~ #> pip list
appdirs (1.4.3)
cycler (0.10.0)
Cython (0.25.2)
functools32 (3.2.3.post2)
matplotlib (2.0.0)
nose (1.3.7)
numpy (1.12.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
python-dateutil (2.6.0)
pytz (2016.10)
scipy (0.19.0)
setuptools (34.3.1)
six (1.10.0)
subprocess32 (3.2.7)
wheel (0.29.0)
~ #>
````
I could fix this with adding Cython as a resource during build as done in other Formulae;
I submitted a [pull request](https://github.com/Homebrew/homebrew-science/pull/5280) at homebrew-science. However, I'm not sure this solves all problems as I couldn't complete all the tests but received an error for PyNEST, similar to [#591](https://github.com/nest/nest-simulator/issues/591).

Additionally, when building with Python3, I have to manually ensure that the numpy, scipy & matplotlib deps are also built with 3.x support. I'll look into that this weekend.

**Comment by heplesser** [comment]
See also @382

**Comment by physicalist** [comment]
I'm not sure I see the relevance of #382 in this case.

As for the Python3 requirement in the dependencies, @tammoippen has in the meantime submitted the relevant [PR](https://github.com/Homebrew/homebrew-science/pull/5293).

**Comment by heplesser** [comment]
I added the reference to #382 here because that issue also relates to problems when installing via homebrew.

**Comment by physicalist** [comment]
OK. I didn't see @tammoippen had replied as well over there, that clarified the connection to the Python3 dependency issue. Apologies.

It seems we're on a good path regarding the Cython Homebrew issue, though. Hopefully it'll be accepted "real soon now", after I made some requested changes.

**Comment by tammoippen** [comment]
I think this can be closed as https://github.com/Homebrew/homebrew-science/pull/5280 is merged.

**Comment by heplesser** [comment]
@physicalist Could you confirm that this issues if fixed by the Homebrew-fix and then close the issue?

**Comment by physicalist** [comment]
Confirmed to compile with both `--with-python` and `--with-python3`.
