### ISSUE TITLE
Malformed SLI command crashes NEST

### ISSUE THREAD

**Issue by wschenck** [nest/nest-simulator#697]
An interactive nest session at SLI level can be crashed (seg.fault) by commands of the following form:
<tt>0 << /test >> GetStatus</tt>
Of course, this is "crazy" SLI usage, but nest should not crash even in this case.
Tested under Ubuntu 16.04.

**Comment by heplesser** [comment]
@wschenck I can confirm this. Actually
```
0 << /a >>
```
is enough to cause the seg.fault, so it is a SLI problem.
```
0 << >>
```
passes (as it should, this is well-formed SLI code),
```
<< /a >>
```
leads to a SLI error message (a slightly confusing one, though).

Running the `sli` executable in using lldb, I get the following
```
SLI ] 0 << /a >>

Mar 29 15:53:50 DictConstruct [Error]: 
    Literal expected. Maybe initializer list is in the wrong order.
sli(71070,0x7fff77720000) malloc: *** error for object 0x1017005d0: pointer being freed was not allocated
```
but no sensible stack trace. Would need to re-compile with `-Dwith-debug` to find out more.

**Comment by gtrensch** [comment]
@jougs 
`DictconstructFunction::execute()` expects a key value pair on the SLI stack regadless the fact that there might be just one data item. Following line causes a "SLI stack underflow" in that case: 
https://github.com/nest/nest-simulator/blob/49d917723e743188a48f187ab07ca8ccc8679b3a/sli/slidict.cc#L691

Please can you have look at the following hack? It introduces a boundary check. It is perhaps not the best place to do this, but I had no better idea. Also no warranty that this has no negative side effects. 

```
while ( ( n < load ) && not( i->OStack.pick( n ) == mark ) )
  {
    Token& val = ( i->OStack.pick( n ) );
    key == NULL;
    if(not(i->OStack.pick(n + 1) == mark)) {
        key = dynamic_cast<LiteralDatum*>(i->OStack.pick(n + 1).datum());
    }
    if ( key == NULL )  {
      i->message( 30,
        "DictConstruct",
        "Literal expected. Maybe initializer list is in the wrong order." );
      i->raiseerror( i->ArgumentTypeError );
      delete dictd;
      return;
    }
    ( *dictd )->insert_move( *key, val );
    n += 2; // count number of elements
  }
```

**Comment by heplesser** [comment]
@gtrensch Thanks for your detective work! Your proposal looks good, but I would write the test as
```c++
LiteralDatum* key = 0;
if ( i->OStack.pick(n + 1) != mark )
{
  key = ...
}
if ( not key ) 
{
  ...
```
The declaration of `key` should be as local as possible, and `NULL` is for C, in C++ `0` works perfectly fine and is recommended by Bjarne S.

When creating a PR, could you also replace the "magic" 30 values by `SLIInterpreter::M_ERROR`?

**Comment by gtrensch** [comment]
@heplesser Many thanks for the feedback. It was a quick hack after midnight :), and there is also a typo in the 4th line. Regarding NULL, I would use nullptr instead. 0 should be used for numbers. I will create the PR.

**Comment by heplesser** [comment]
@gtrensch "Because of C++'s tighter type checking, the use of plain 0, rather than any suggested NULL macro, leads to fewer problems." Bjarne Stroustrup, The C++ Programming Language, 3rd ed, §5.1.1. Therefore, I would prefer a plain an simple `0`.

**Comment by jougs** [comment]
@gtrensch: any news on this? To me this looks as it should not be too much work to fix. I'll happily review a PR to fix this. Many thanks!

**Comment by heplesser** [comment]
Won't fix as this problem never seems to occur in practice and is easily detected if it should.
