### ISSUE TITLE
Spin_detector problems

### ISSUE THREAD

**Issue by SepehrMN** [nest/nest-simulator#698]
I looked at the code and I see two problems with the spin_detector:

1. The documentation is for the spike_detector
2. The precision setting does not conform to #446. After the cpp file changes, this will require additional tests.

I could potentially fix both.

**Comment by heplesser** [comment]
@SepehrMN I would be great if you could provide a PR fixing this!

**Comment by SepehrMN** [comment]
The fix has been merged. So this can be closed.

**Comment by SepehrMN** [comment]
@jougs I closed this. It was part of a milestone so I hope it is OK.

**Comment by jougs** [comment]
Yes. Thanks!
