### ISSUE TITLE
Improve error handling in Connect

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#703]
When `Connect` in the list/gidcollection-based variant is called and the user forgets to specify a connection rule or spec, e.g.,
```
srcs tgts << /weight 0.5 >> Connect
```
a rather confusing
```
Apr 05 13:10:25 Connect_g_g_D_D [Error]: DictError
    Unused dictionary items:  weight
```
We should make this more informative: If an error occurs, we could inspect the dictionary and check if it contains `/rule`. If not, we can explicitly tell the user that the conn spec is missing.

**Comment by stinebuu** [comment]
@heplesser I am not sure if checking for `/rule` will work. As far as I can tell, when calling `Connect` in this manner, SLI interprets it as a parameter in conn spec, and fills in missing defaults:

`/conn_spec :Connect_complete_dict % fill in missing defaults` (line 456 in nest-init.sli)

The dictionary will then contain a `/rule`, namely `all_to_all`.

**Comment by heplesser** [comment]
@stinebuu This indeed makes things more complicated. The problem is that it would be difficult to identify a dictionary that is a syndict in all generality. So I will close this for now.
