### ISSUE TITLE
Inconsistent initialization and reset of EventDeliveryManager

### ISSUE THREAD

**Issue by suku248** [nest/nest-simulator#717]
In PR #716 @heplesser noticed that 

> initialization and reset of EventDeliveryManager appears to be implemented inconsistently:
> 
> * `secondary_event_buffer_` are not initialized in the constructor
> * `secondary_event_buffer_`, `spike_register_`, `offgrid_spike_register_`, `displacements_` and `comm_marker_` are neither reset in `finalize()` or `initialize()`
> * All of those except `comm_marker_` are cleared by `cofigure_spike_buffers()`, but that is called directly only from `reset_network()`, `prepare_simulation()` and `set_status()`.

This needs to be checked and if we do not need to reset those members explicitly, a comment is required that explains why.

**Comment by heplesser** [comment]
These data structures change significantly in https://github.com/jakobj/nest-simulator/tree/5g.
We need to check if the problems still exist there. We therefore do not proceed on this issue in master for now.

**Comment by heplesser** [comment]
@suku248 Any news on this one?

**Comment by stinebuu** [comment]
I have gone through 5G's `EventDeliveryManager` to check if all is initialized and cleared and made a PR towards the 5G branch to fix what I found. When going though the code I found that
- `secondary_event_buffer` and `displacements_` are gone, so we don't need to worry about them
- `comm_marker` is not used anywhere, so I have removed it
- there were some variables not initialized in the constructor, so I have added them
- there were some variables not cleared in `initialize()` or `finalize()`, so  I cleared them.

**Comment by heplesser** [comment]
For reference: @stinebuu's PR towards the 5G branch was 
https://github.com/jakobj/nest-simulator/pull/113. This issue was thus successfully addressed when that PR was merged and I will close it.
