### ISSUE TITLE
Error when calling set_synapse_defaults with multiple threads

### ISSUE THREAD

**Issue by hakonsbm** [nest/nest-simulator#719]
After PR #704 a bug has been found with setting defaults for synapse models using multiple threads, making NEST crash. Because of this, the test test_connect_parameters.py causes a segmentation fault somewhat reliably on multi-core systems.

The problem arises because we are setting defaults in parallel using OpenMP. Using parallelization here is not necessary, and removing it will fix the issue.

**Comment by jougs** [comment]
Is this problems fixed with the merge of #724? If yes, please close it. Otherwise please comment on what is still needed. Thanks!

**Comment by hakonsbm** [comment]
It turns out it is necessary to use parallelization after all, and the bug has been fixed by #724, so I'm closing this.
