### ISSUE TITLE
Communicator accessibility

### ISSUE THREAD

**Issue by apeyser** [nest/nest-simulator#72]
Currently communicators are internal structures. It would be helpful to pull out the communicator, particularly for the case of MUSIC which uses a sub-communicator as part of putting as much of the machinery outside of NEST rather than buried in internal structures.

So either by integrating pymusic:
s = music.Setup()
s.getcomm()

or by adding a nest call:
nest.getcomm()

**Comment by jougs** [comment]
NEST Core came to the conclusion that this is too unspecific and should be closed.
