### ISSUE TITLE
Updates recording of currents provided by stimulating devices

### ISSUE THREAD

**Issue by appukuttan-shailesh** [nest/nest-simulator#720]
This is a continuation of the discussion towards the end of #663.

The following needs to be updated:
- Setting the recordables: GetDefaults('..._generator')['recordables']
- Appropriate updates to unit test to include above
- For noise generator, set current = 0, when no target neuron connected
- For noise generator, keep the current value constant for the duration of noise_generator's dt
(solutions for above discussed in #663)

One outstanding issue is possibly regarding the current generated by AC source. Consider the following:
ac = nest.Create('ac_generator', 1, params = {'amplitude': 550.0, 'offset': 1000.0, 'frequency': 100.0, 'phase' : 0.0, 'origin' : 2.5, 'start' : 2.5, 'stop' : 40.0})

The values that are computed are:
```
t (ms) <-> I (pA)
4.9    <-> 0.0
5.0    <-> 1034.53478574
5.1    <-> 1068.93327846
5.2    <-> 1103.05972302
```    
min_delay = 1.0
```
t (ms) <-> V (mV)
5.9    <-> -70.0
6.0    <-> -70.0
6.1    <-> -69.58756241
6.2    <-> -69.16415163
```
Shouldn't the value at t = 5.0, be I = 1000.00.... i.e. offset + sin(t=0). 
![ac_jump_v2](https://cloud.githubusercontent.com/assets/24866517/26061402/26583d08-3988-11e7-89c8-25f175749b97.png)
For Brian and NEURON, the current and voltage values are as follows:
(ignoring timestamps owing to differences in simulator execution)
```
Current:
0.0
1000.0
1034.53479
1068.93328
1103.05972

Voltage:
-70.0
-70.0
-69.90049751
-69.79805377
-69.69269695
-69.58446864
```
The absence of this value (1000.0) in NEST, I believe, causes a more abrupt change in both the current and voltage at the start of current injection as seen below, which is absent in the next cycle (starting at 15 ms). The change in Vm is more gradual in case of Brian and NEURON (as seen in the values above).

@heplesser , @gtrensch : Any thoughts on this? My current workaround for this is to compensate for the jump by adjusting the phase appropriately. But I believe there should be a more elegant fix, if this is infact considered an issue with the AC source.

**Comment by appukuttan-shailesh** [comment]
@gtrensch : I have pulled the changes from your repository and updated L348 here:
https://github.com/appukuttan-shailesh/nest-simulator/tree/record-stim

Once we decide on the AC source, I shall create a pull request.

**Comment by heplesser** [comment]
@appukuttan-shailesh @gtrensch I will try to work on this early next week.
