### ISSUE TITLE
`topology.PlotKernel` doesn't show periodic boundary conditions

### ISSUE THREAD

**Issue by wmayner** [nest/nest-simulator#728]
**Description of problem:**
When plotting the kernel for a given neuron in a layer with periodic boundary conditions, the boundary conditions are not reflected in the plot.

**Version-Release or Git commit:**
 2.12.0

**How reproducible: (Always/Sometimes/Unsure)**
Always

**Steps to Reproduce:**
Run this script and view the plot `p`:

```python
import nest
from nest import topology as tp

layer_spec = {
    'extent': [2.0, 2.0],
    'rows': 10,
    'columns': 10,
    'elements': 'iaf_psc_alpha',
    'edge_wrap': True,
}

layer1 = tp.CreateLayer(layer_spec)
layer2 = tp.CreateLayer(layer_spec)

conn = {
    'connection_type': 'divergent',
    'mask': {'circular': {'radius': 0.75}},
    'kernel': {'gaussian': {'p_center': 1.0, 'sigma': 0.2}},
    'allow_autapses': False,
}

elt = tp.GetElement(layer1, [0, 0])

p = tp.PlotLayer(layer1)

tp.PlotKernel(p.axes[0], elt, conn['mask'])

p
```

**Actual results:**
![kernel](https://cloud.githubusercontent.com/assets/1775632/26265107/5284f66c-3ca5-11e7-8a01-758c19100ab6.png)

**Expected results:**
A quadrant of the kernel should be shown at each corner, instead of just one.

**Comment by heplesser** [comment]
@wmayner The online documentation and the user manual explicitly state that `PlotKernel()` ignores periodic boundary conditions, so the behavior you report is correct wrt documentation. 

Thus, I consider this a feature request, which raises the question of how important this use case is.

**Comment by wmayner** [comment]
Ah, I see—I was following [the `topology` tutorial](http://www.nest-simulator.org/part-4-topologically-structured-networks/) and hadn't actually read the full documentation for that function. Sorry for the unnecessary issue.

It would be nice to show the boundary conditions, but that's certainly a very low-priority feature.

**Comment by lemontree561** [comment]
@wmayner why I run the demo of the topology tutorial ,I can't find the result picture,I also use your code to try but I also can't find the result picture.How to get the result picture?
Thanks!

**Comment by lemontree561** [comment]
I solve the problem ,thanks

**Comment by heplesser** [comment]
@stinebuu Could you take a look at how difficult it would be to solve this? A solution would need to work for all supported mask/kernel types.
