### ISSUE TITLE
Incorrect Parameter Name String in conn_builder.cpp

### ISSUE THREAD

**Issue by maharjun** [nest/nest-simulator#735]
As of the latest master commit `15b63f2` (master branch), the file `conn_builder.cpp` at line '340' appears to mistakenly contain a space after the `"` in the parameter string `" A_minus"`

**Comment by heplesser** [comment]
@maharjun Thanks for reporting! That space seems to have been there for a while already, and it appears that that test is never executed. I have now removed the test entirely (see #736 for reasons) and added a regression test.
