### ISSUE TITLE
The Draw problem in Raster_plot.py

### ISSUE THREAD

**Issue by Tigeraus** [nest/nest-simulator#743]
in line 293 of raster_plot.py:

`pylab.draw()`

This can not show the figure. I suggest that replace it with `pylab.show()`

**Comment by heplesser** [comment]
@Tigeraus The methods in `nest.raster_plot` call `pylab.draw()` intentionally: on many backends, `pylab.show()` would block the simulation until the figure window is closed. `nest.raster_plot` provides `show()` to force showing the figure. If plotting from a loop, it may be necessary to insert `pylab.pause(0.001)` to briefly surrender control to the GUI loop to allow it to update a figure.
