### ISSUE TITLE
Error when nest.helpdesk() is called with Python < 2.7.8

### ISSUE THREAD

**Issue by janhahne** [nest/nest-simulator#748]
When I install NEST with Python 2.7.6 and then call `nest.helpdesk()` in python I get an error that the file helpindex.html does not exist. If I call `nest.help('iaf_psc_alpha')` (or any other NEST object) i get the - of course somehow right - answer `Sorry, there is no help for 'iaf_psc_alpha'!`

I assume this behavior results from the combination of PR #688 and #715.

When I call `nest.helpdesk()` or `nest.help(object)` with Python 2.7.6 I would expect an information as `The NEST help is not available due to a Python version older than 2.7.8`. Otherwise it is unclear to the user what is going wrong - there is no message at all, neither when the help is accessed via python nor while cmake (which might be useful as well?)

**Comment by heplesser** [comment]
@steffengraber Could you take a look at this? I think @janhahne's suggestion to print 
```
NEST Help is not available on Python 2.7.7 and earlier.
```

**Comment by steffengraber** [comment]
@janhahne @heplesser There is a little fix: #751.
Please test and review it.
