### ISSUE TITLE
Broken NEST installation, fatal SLIStartup [resolved]

### ISSUE THREAD

**Issue by rpgowers** [nest/nest-simulator#749]
**[Issue probably resolved]**
**Description**
Consistently achieving broken NEST installation.

**Version**
I am trying to install NEST 2.12.0 on Ubuntu 16.04 with Python 2.7.11 (anaconda version 4.3.21)

**Steps**
I installed NEST with the following steps,
`cmake -DCMAKE_INSTALL_PREFIX:PATH=../nest-install -Dwith-mpi=ON -Dwith-readline=OFF -DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=c++ -DMPI_C_COMPILER=mpicc -DMPI_CXX_COMPILER=mpicxx ../nest-simulator`
`make`
`make install`

**Results**
`installcheck` is mostly successful, except for one SLI failure and being unable to run PyNEST tests.  These errors read as follows,
```
Running  ../nest-install/bin/sli ../nest-install/share/doc/nest/mpitests/issue-281.sli
SLI v2.12.0 (C) 2004 The NEST Initiative
N_MPI: 1
N_MPI: 2
N_MPI: 4

Jun 12 09:24:31 unittest::assert_or_die [Fatal]: 
    Assertion failed: unittest::distributed_pass_or_die: collected results.

Jun 12 09:24:31 unittest::assert_or_die [Fatal]: 
    Exiting with code 1
```

```
Traceback (most recent call last):
  File "/home/robert/anaconda/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/robert/anaconda/lib/python2.7/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /home/robert/repositories/nest-install/lib/python2.7/site-packages/nest/tests


```
However, when I try to run `nest` I am given the following error message (full output here:
[output.txt](https://github.com/nest/nest-simulator/files/1067479/output.txt))

```
Jun 12 09:33:34 SLIStartup [Fatal]: 
    Your NEST installation seems broken. 
```
**Additional Info**
Sometimes when I have reinstalled NEST this error message does not appear at first, but appears later when trying to run `nest` later. Furthermore, attempting to `import nest` in Python results in "no module named nest".  I am not sure if this is part of the same problem or a separate issue.

**EDIT**
Issue seems to be resolved by using absolute rather than relative paths in the cmake step, ie
`cmake -DCMAKE_INSTALL_PREFIX:PATH=~/repositories/nest-install -Dwith-mpi=ON -Dwith-readline=OFF -DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=c++ -DMPI_C_COMPILER=mpicc -DMPI_CXX_COMPILER=mpicxx ~/repositories/nest-simulator`

**Comment by muffgaga** [comment]
IMHO the path provided to `CMAKE_INSTALL_PREFIX:PATH` should be automatically canonicalized to a absolute path (using `realpath` or similar); it's a quite common "mistake" to provide relative installation paths.

**Comment by heplesser** [comment]
@muffgaga Your suggestion is plausible, but as a comment to a closed issue, there is a high risk it will get lost. Could you open a new issue or, even better, create a pull request implementing your suggestion?

**Comment by muffgaga** [comment]
Done, cf. #783.
