### ISSUE TITLE
"isinstance" bug in nest.py

### ISSUE THREAD

**Issue by dohmatob** [nest/nest-simulator#754]
#### Description

Running the example http://www.nest-simulator.org/py_sample/twoneurons/ yields the following error traceback 

```
...
  File "/home/elvis/anaconda2/envs/py3k/lib/python3.6/site-packages/nest.py", line 4
    if isinstance(each_item, indent = False ,list):
                                            ^
SyntaxError: positional argument follows keyword argument
```

**Comment by heplesser** [comment]
@dohmatob This looks strange. There should not be any file nest.py in a NEST installation, and the line `if isinstance(each_item...` is not in NEST code.

**Comment by nosratullah** [comment]
I have this error too!

**Comment by nosratullah** [comment]
It seems there is another nest library which is not nest-simulator. and you installed it with this command : 
`pip install nest`
simply uninstall it:
`pip uninstall nest`
and follow the installation from the nest documentaion.
