### ISSUE TITLE
tau_minus_triplet defined but no triplet STDP

### ISSUE THREAD

**Issue by hannahbos** [nest/nest-simulator#76]
[This is a summary of things discussed in trac.766]
Neurons have the property tau_minus_triplet, but this does not seem to be used, which may be confusing for users. In the ticket triage session on August 27, 2014, we came to the conclusion that triplet STDP from the developer module should be made available in the public NEST version.

**Comment by flinz** [comment]
Following up on this:Is the developer module triplet model  available on somebody's branch?

**Comment by jougs** [comment]
@abigailm @mhelias

**Comment by abigailm** [comment]
@flinz I have a version of this and I will update it to be mergeable with the current release. A test would be very nice though - do you think you can lend a hand here, to get the model available as soon as possible? There is a SLI test for the basic STDP synapse (tests/unittests/test_stdp_synapse.sli) that could serve as a basis, or you could write a PyNEST test along the same principles - expose the synapse to some pre- and post-synaptic activity, measure the weight, calculate the what the weight should be, compare. Or something else reasonable if you have a better idea.

**Comment by flinz** [comment]
@abigailm sure, we can take care of testing..

To mention this, a student (@zifeo) is currently reimplementing the Pfister (2006) triplet rule himself, based off the stdp_synapse, which is the reason why i wanted to have a look at the existing implementation, to prevent redundancy.

We'll end up writing tests anyways, which will be equally applicable.

**Comment by abigailm** [comment]
@flinz OK, then perhaps it would be easiest if I get the synapse running with the current release and then send you the source, and you and/or your student make the corresponding PR when you are happy with the testing?

**Comment by flinz** [comment]
@abigailm sure, this will work!

**Comment by abigailm** [comment]
@flinz I'm on it.

**Comment by flinz** [comment]
We've opened a PR including the triplet model. https://github.com/nest/nest-simulator/pull/150

**Comment by jougs** [comment]
Closing, as #150 was merged.
