### ISSUE TITLE
Decide on one Python test approach for NEST

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#761]
NEST currently has two ways of running Python tests: `nosetests` and the `unittest` test runner. The latter is used if the former is not available, but runs far fewer tests and may run into problems that our CI testing does not pick up (because it uses `nosetests`), see #677. 

Maintaining two different test setups requires extra efforts and risks that things are not tested as well as we believe. Running Python tests in multiple ways on our CI system would also be a waste of resources.

Therefore, we should commit to one way of running Python tests in NEST. But which one?

- [PythonTestingTools](https://wiki.python.org/moin/PythonTestingToolsTaxonomy) provides an overview of available tools.
- [Unittest](https://docs.python.org/3/library/unittest.html) is part of the Python Standard Library and is thus mostl likely to be available in the long run. We already have many tests using it. The downside is that tests need to be added manually.
- [Nose](https://nose.readthedocs.io/en/latest/) and [Nose2](http://nose2.readthedocs.io/en/latest/) are popular and we use Nose at present, but development seems to have ceased (https://github.com/nose-devs).
- [Py.test](https://docs.pytest.org/en/latest/) is under [active development](https://github.com/pytest-dev/pytest/graphs/contributors), but I have no experience with it.

**Comment by Silmathoron** [comment]
As a note, Unittest implements the discovery [from version 3.2 on](https://docs.python.org/3/library/unittest.html#test-discovery) and apparently also in [2.7](https://docs.python.org/2.7/library/unittest.html#test-discovery).

**Comment by mschmidt87** [comment]
Hi, I have made only good experiences with py.test. We are using it in the [h5py_wrapper](https://github.com/INM-6/h5py_wrapper) as well as [python-dicthash](https://github.com/INM-6/python-dicthash) library. These are admittedly much smaller projects than NEST, but even here, moving from unittest to py.test saved us overhead code and made the code more readable, in my opinion.

As far as I can see, this is the major advantage of py.test. It does not need the class architecture of unittest and uses only the standard `assert` command, but still prints useful assertion output to the user.

**Comment by heplesser** [comment]
@mschmidt87 Is py.test compatible with existing tests based on unittests, or would we have to adapt all existing tests?

**Comment by mschmidt87** [comment]
py.test is compatible with testsuites based on unittest and nosetest, see the Documentation on [unittest](https://docs.pytest.org/en/latest/unittest.html) and [nosetest](https://docs.pytest.org/en/latest/nose.html).
In principle, you just execute `pytest` in the folder (or a parent folder) containing your tests and . (I tried this with nest, but it complains about some import issues in the test scripts)
py.test will automatically find the tests and also run implemented setup/teardown code.

However, as stated in the pytest documentation, this is meant as an intermediate step on the way to transforming to pytest. In my experience, this essentially boils down to:

- removing all code related to the class structure of unittest
- replacing all special assert statements by a simple `assert` (where the particular statements might have to be slightly changed/simplified)
- converting test-specific code, such as skipping commands or setup/teardown code.

For the mentioned libraries, this was actually very easy, but as I said, these projects are somewhat smaller than NEST and have less complex testsuites. But I don't see any principal obstacles and you'll definitely get easier code.

**Comment by Silmathoron** [comment]
@heplesser do you have some pideas about how to assess the various possibilities?

Also, could you edit your message to clarify your remark about Nose? From the way to said it I thought that development of Nose had ceased, but it's only the first version which is (obviously) no longer developed; Nose2, which is now the current release, is still very much active.

**Comment by gtrensch** [comment]
I looked at the nose2 plugins and their documentation. It seems that nose2 comes with such a built-in plugin which can be configured to also capture stderr. 
Please see: http://nose2.readthedocs.io/en/latest/plugins/buffer.html

**Comment by mschmidt87** [comment]
py.test has similar functionality: [https://docs.pytest.org/en/latest/capture.html](https://docs.pytest.org/en/latest/capture.html)

**Comment by heplesser** [comment]
@Silmathoron I edited my statement on nose and nose2 development, but looking at the [commit frequency in the nose2 repo](https://github.com/nose-devs/nose2/graphs/contributors), I am not optimistic concerning nose2.

**Comment by Silmathoron** [comment]
Right... py.test does look a lot more active!

**Comment by gtrensch** [comment]
... and comes with a basic support for running tests written for nose:  https://docs.pytest.org/en/latest/nose.html

**Comment by tammoippen** [comment]
I can also support pytest! We are using it a lot and the plugin support is awesome:

* `pytest-cov` give coverage reports
* `pytest-flake8` pep8 and more static code analysis for python

pytest fixtures is a very nice alternative for setup/teardown code.

**Comment by heplesser** [comment]
I have also made very good experiences with PyTest in the last round of my Advanced Programming course, where I previously used nosetest. Here a few examples of features that PyTest provides (see [course repo for complete example code](https://bitbucket.org/heplesser/nmbu_inf200_h17/src/90bfa4257b602d09a54a47eced8b9bb2f7c1afe5/Project/SampleProjects/biolab_project/?at=master):
```python
@pytest.fixture
def set_params(request):
    Bacteria.set_params(request.param)
    yield
    Bacteria.set_params(Bacteria.default_params)
```

Define a fixture that runs up to `yield` before each test equipped with the feature, and runs the part after the `yield` once the test is complete, no matter whether the test passed or failed. You can thus reliably reset system status between tests. You use it like this:
```python
@pytest.mark.parametrize('set_params', [{'p_death': 1.0}], indirect=True)
def test_bact_certain_death(set_params):
    b = Bacteria()
    for _ in range(100):
        assert b.dies()
```
This runs the test once with the given parameter dictionary passed to the `set_params` fixture.

You can also run the same test code multiple times with different parameter values:
```python
@pytest.mark.parametrize("n_a, n_b, p_death",
                         [[100, 200, 0.1],
                          [100, 200, 0.9],
                          [10, 20, 0.5]])
def test_death(n_a, n_b, p_death):
    Bacteria.set_params({'p_death': p_death})
    dish = Dish(n_a, n_b)
    dish.death()
    died_a = n_a - dish.get_num_a()
    died_b = n_b - dish.get_num_b()
    Bacteria.set_params(Bacteria.default_params)
    
    assert binom_test(died_a, n_a, p_death) > ALPHA
    assert binom_test(died_b, n_b, p_death) > ALPHA
```

You can define fixtures at the module, class and maybe even other levels. Adding `autouse=True` ensures that the fixture is run for every test in the scope:
```python
class TestDeathDivision:
    @pytest.fixture(autouse=True)
    def create_dish(self):
        self.n_a = 10
        self.n_b = 20
        self.dish = Dish(self.n_a, self.n_b)
```

PyTest also has extensions supporting mocking, allowing you to easily check on function calls made
```python
    def test_dish_ages(self, mocker):
        mocker.spy(Bacteria, 'ages')

        n_a, n_b = 10, 20
        d = Dish(n_a, n_b)
        d.aging()

        assert Bacteria.ages.call_count == n_a + n_b
```
or to control the return value of functions ([complete example](https://bitbucket.org/heplesser/nmbu_inf200_h17/src/90bfa4257b602d09a54a47eced8b9bb2f7c1afe5/Project/SampleProjects/chutes_project_var2/?at=master))
```python
def test_single_step_one(mocker):
    mocker.patch('random.randint', return_value=1)
    b = Board(chutes=[], ladders=[])
    pl = Player(b)
    pl.move()
    assert pl.position == 1
```

**Comment by heplesser** [comment]
The [Open NEST Developer VC on 16 April](https://github.com/nest/nest-simulator/wiki/2018-04-16-Open-NEST-Developer-Video-Conference) decided to move to `py.test`, thus closing.
