### ISSUE TITLE
Testing on multiple python versions.

### ISSUE THREAD

**Issue by lekshmideepu** [nest/nest-simulator#763]
For some time ago, there was a discussion on testing multiple python versions. I tried the matrix [build ](https://travis-ci.org/lekshmideepu/nest-simulator/builds/245277036)for two different versions (2.x and 3.x) of python.  (issue with the pythonlibs has to be fixed in the build. I am working on this.)
I think testing the latest version of builds from both 2 and 3 series is enough. Could you please add your thoughts here. 
Also, testing could be done in two ways, either using a [tox](https://tox.readthedocs.io/en/latest/) plugin (or [tox-travis](https://github.com/ryanhiebert/tox-travis)) or by using the travis python images.

**Comment by heplesser** [comment]
@lekshmideepu I agree that using the latest from the 2 and the 3 series, respectively, gives a reasonable balance between resources used and coverage.

I know too little about tox or travis images, so I would leave that to you.

**Comment by terhorstd** [comment]
I would agree to testing the last versions only.

**Comment by heplesser** [comment]
Closed since testing with Py2 and Py3 has been introduced with #789.
