### ISSUE TITLE
Enable passing a random number generator to the Connect function

### ISSUE THREAD

**Issue by mschmidt87** [nest/nest-simulator#771]
This issue is a follow-up of the discussion on the NEST USER mailing list involving @heplesser  (Subject of the original mail was "Controlling random connectivity and stochastic input independently").

**Use case**
In a simulation of a network with random connectivity, the user wants to control the random network structure and random input given to the network independently. 

**Current workaround / solution**
Since both are based on random numbers drawn from the thread-local RNGs, a workaround is necessary. One can re-seed the thread-local RNGs just before calling `Simulate`. 

**Suggestion**
Another possibility would be to enable the user to pass his/her self-created RNG to the Connect function to cleanly separate RNGs for network creation and simulation from each other. As it was discussed on the mailing list, there should be no principal technical obstacle to do this. 
However, there is the risk that the user might reuse the same RNG seed for both RNGs or overlapping RNGs between threads and thereby introduce spurious correlations in the network simulation.

The questions is then whether we should leave it to the user to deal with this or if we can build in a mechanism in NEST to check whether there are overlapping RNGs in the system.

For instance, currently a warning is given when the user defines the same RNG seeds for different thread-local RNGs, like so
`nest.SetKernelStatus({'total_num_virtual_procs': 2,
                      'rng_seeds': [1, 1]})`
which would trigger
`RNGManager::set_status [Warning]: 
    Seeds are not unique across threads!` .

This is related to #245 .

**Comment by jougs** [comment]
I'm currently working on a complete refactoring of *librandom* (see #245).  This will bring a great simplification of the code as the new version will be based off C++11's `random` header. In addition, a master-seed mechanism will ensure that re-seeding becomes easy. 

I thus propose that the way to go should be making your proposed workaround the standard procedure for this kind of problem and we're not changing anything about the `Connect` calls and I think I should include a sentence about this in the new documentation.

**Comment by ikitayama** [comment]
@jougs Do you implement the new librandom in NEST 3 also for the toolchains that don't have
C++11's `random` header? In my quick testing with -std=c++11, FCC doesn't seem to have it.

**Comment by ikitayama** [comment]
@jougs I was told in the latest Fujitsu toolchain it's included as part of numerics library. Please ignore the above and go ahead implement the new librandom.
