### ISSUE TITLE
More comprehensive set of tests for Topology

### ISSUE THREAD

**Issue by hakonsbm** [nest/nest-simulator#772]
With PR #705 tests that previously had to be run manually are converted to be run with `installcheck`. However, this set of tests lacks tests for much of the functionality in Topology, such as 

- Kernels
- Parameters
- Prescribed number of connections
- Multapses/autapses
- Visualization functions

These tests should be added.

**Comment by heplesser** [comment]
#929 adds some tests for spatial kernels. This is a first step.

**Comment by heplesser** [comment]
We should create these tests in preparation of the NEST-3 interface for spatial connections.
