### ISSUE TITLE
Include structural plasticity status information in kernel status

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#777]
This is a follow-up to #260 and #775. Since it involves an UI change, it targets NEST 3.0.

Currently, status information on kernel parameters for structural plasticity are managed using `Get/SetStructuralPlasticityStatus`.  These parameters should be managed using `Get/SetKernelStatus` instead. In order to retain the grouping of parameters, they should be included in a sub-dictionary of the overall status dictionary.

**Comment by sdiazpier** [comment]
This issue has been solved already in commit 624623a7 (Tammo Ippen        2016-01-06 17:56:58 +0100 202) 

The functions SetStructuralPlasticityStatus and GetStructuralPlasticityStatus still exist. Dear @heplesser. should these be removed?

**Comment by heplesser** [comment]
@sdiazpier Yes, the functions should be removed at the SLI and Python level and examples updated accordingly. We also need to make sure that the documentation for Get/SetKernelStatus covers the sp-related entries (see also #1373 in this context).

Currently, the value of `structural_plasticity_update_interval` must be given as an integer. This seems somewhat confusing, because it is a time in ms, isn't it? So I would expect `double` as the data type.
