### ISSUE TITLE
Writing extension module

### ISSUE THREAD

**Issue by wangsihao** [nest/nest-simulator#780]
Hi, I am a beginner in nest, I just follow the guidance to create my own module. When I run nest.Install("mymodule"), there is a error showed as follow.

pynestkernel.NESTError: DynamicModuleManagementError in Install: Module 'mymodule' could not be opened.
The dynamic loader returned the following error: 'file not found'.

Please check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!

I modified the directory of  DYLD_LIBRARY_PATH to make it contain mymodule.so, the error still exist. How to solve this error? Thanks

**Comment by jougs** [comment]
Can you please be more specific on what you set the `DYLD_LIBRARY_PATH` to and how?

**Comment by wangsihao** [comment]
Hi, I tried all of the following ways, none of them works


export DYLD_LIBRARY_PATH=/Users/myusername/Downloads/neuron/nest/bld/lib/nest:$DYLD_LIBRARY_PATH


export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$/Users/myusername/Downloads/neuron/nest/bld/lib/nest:$/Users/myusername/Downloads/neuron/nest/bld/bin


export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$/Users/myusername/Downloads/neuron/nest/bld/lib/nest

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$/Users/myusername/Downloads/neuron/nest/bld/lib

**Comment by lekshmideepu** [comment]
Could you please echo the current value of your _DYLD_LIBRARY_PATH_
echo $DYLD_LIBRARY_PATH

**Comment by wangsihao** [comment]
Sihaos-MacBook-Air:Sihao_Test sihaowang$ echo DYLD_LIBRARY_PATH
DYLD_LIBRARY_PATH

**Comment by jougs** [comment]
@wangsihao: You're missing a `$` sign in front of `DYLD_LIBRARY_PATH`. Can you please also send the output of `echo $PYTHONPATH` and `for x in $(echo $DYLD_LIBRARY_PATH | tr : " "); do ls -l $x; done`

**Comment by wangsihao** [comment]
@jougs   Hi, the result is as follow

Sihaos-MacBook-Air:~ sihaowang$ echo $DYLD_LIBRARY_PATH
/Users/sihaowang/Downloads/neuron/nest/bld/lib/nest::$/Users/sihaowang/Downloads/neuron/nest/bld/lib/nest:$/Users/sihaowang/Downloads/neuron/nest/bld/bin:$/Users/sihaowang/Downloads/neuron/nest/bld/lib/nest:$/Users/sihaowang/Downloads/neuron/nest/bld/lib


Sihaos-MacBook-Air:~ sihaowang$ echo $PYTHONPATH
/Users/sihaowang/Downloads/neuron/nest/bld/lib/python2.7/site-packages:


Sihaos-MacBook-Air:~ sihaowang$ for x in $(echo $DYLD_LIBRARY_PATH | tr : " "); do ls -l $x; done
total 1520
-rwxr-xr-x  1 sihaowang  staff  387448 Jul 10 09:38 libmymodule.dylib
-rwxr-xr-x  1 sihaowang  staff  387280 Jul 10 09:38 mymodule.so
ls: $/Users/sihaowang/Downloads/neuron/nest/bld/lib/nest: No such file or directory
ls: $/Users/sihaowang/Downloads/neuron/nest/bld/bin: No such file or directory
ls: $/Users/sihaowang/Downloads/neuron/nest/bld/lib/nest: No such file or directory
ls: $/Users/sihaowang/Downloads/neuron/nest/bld/lib: No such file or directory

**Comment by jougs** [comment]
It seems that your `DYLD_LIBRARY_PATH` is a bit messed up after your experiments. Can you please run `export DYLD_LIBRARY_PATH=/Users/sihaowang/Downloads/neuron/nest/bld/lib/nest` and try again if loading the module works?

**Comment by wangsihao** [comment]
@jougs  Hi, it still does not work, shows the same error. 

Sihaos-MacBook-Air:Sihao_Test sihaowang$ echo $DYLD_LIBRARY_PATH
/Users/sihaowang/Downloads/neuron/nest/bld/lib/nest
Sihaos-MacBook-Air:Sihao_Test sihaowang$ for x in $(echo $DYLD_LIBRARY_PATH | tr : " "); do ls -l $x; done
total 1520
-rwxr-xr-x  1 sihaowang  staff  387448 Jul 10 11:08 libmymodule.dylib
-rwxr-xr-x  1 sihaowang  staff  387280 Jul 10 11:09 mymodule.so

**Comment by jougs** [comment]
Sorry for that. Does it work if you run `nest.Install("libmymodule")` instead of `nest.Install("mymodule")`?

**Comment by wangsihao** [comment]
@jougs   Sorry, the problem still exist

pynestkernel.NESTError: DynamicModuleManagementError in Install: Module 'libmymodule' could not be opened.
The dynamic loader returned the following error: 'file not found'.

Please check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!

**Comment by wangsihao** [comment]
@jougs  I already fixed that problem, thanks for your help

**Comment by jougs** [comment]
@wangsihao Can you please tell us how you solved the problem? This might possibly help other users with the same problem. I'm now closing this.
