### ISSUE TITLE
Broken link in documentation (NEST/SLI Quick Reference)

### ISSUE THREAD

**Issue by ricardomurphy** [nest/nest-simulator#781]
Description of problem:
When I use the "NEST/SLI Quick Reference", select a topic such as
"Models and nodes", and then click on a link to, say, "Node", I get an
error message:

"Not Found
The requested URL /helpindex/s/Node was not found on this server.
Apache/2.2.22 (Debian) Server at www.nest-simulator.org Port 80"

How reproducible: It happens a lot. 

Steps to Reproduce: See description.

Actual results:: See description.

**Comment by steffengraber** [comment]
@ricardomurphy 
Thank you for reporting this issue. For a first step I repaired all the broken links by hand. 
Next we need to update the [quickref.md](https://github.com/nest/nest-simulator/blob/master/extras/userdoc/md/documentation/quickref.md).

**Comment by ricardomurphy** [comment]
Thank you for your prompt response.
Ricardo Murphy

___________________________________

Dr. Ricardo Murphy,
University of Oslo,
Department of Molecular Medicine,
Physiology Section,
Pb. 1103, Blindern,
0317 Oslo

Tel:   95333157
Fax: 22851249
Email: ricardo.murphy@medisin.uio.no


On Mon, Jul 10, 2017, at 14:10, graber wrote:
> @ricardomurphy[1]
>  Thank you for reporting this issue. For a first step I repaired all the broken links by hand.>  Next we need to update the quickref.md[2].


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[3], or mute the thread[4]. > 

Links:

  1. https://github.com/ricardomurphy
  2. https://github.com/nest/nest-simulator/blob/master/extras/userdoc/md/documentation/quickref.md
  3. https://github.com/nest/nest-simulator/issues/781#issuecomment-314087113

**Comment by terhorstd** [comment]
forgotten to close this long fixed issue.
