### ISSUE TITLE
Index of user contributed modules/extensions (MyModule)

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#782]
As far as I can see it there is currently no index for user contributed modules hosted on the nest website or the github wiki (https://github.com/nest/nest-simulator/wiki).

As more specialized modules are contributed I think it would make sense to maintain a list (possibly sorted by use-case) to point the community to available modules.

**Comment by heplesser** [comment]
@flinz We now have a [page for external modules](https://github.com/nest/nest-simulator/wiki/NEST-Modules) and will shortly create links to it from nest-simulator.org and other wiki pages.

@terhorstd I think we should also link from the top-level README.md here and provide instructions to module writers on how to ensure that we detect their modules.

**Comment by terhorstd** [comment]
So, have a look into the [wiki](../wiki/NEST-Modules), I just added the short repository descriptions that are shown in the search results and the comment, that the page is autogenerated (i.e. will be overwritten if someone edits it online).

**Comment by flinz** [comment]
That looks great @terhorstd! Thanks for the efforts. Should i leave the issue open until the corresponding entries on the homepage, readme, and others are done?

**Comment by jougs** [comment]
@steffengraber, @jessica-mitchell: can you please add a link to user supplied modules to the documentation page and close this issue once you are done? Many thanks!

**Comment by heplesser** [comment]
The links to external modules are here: https://github.com/nest/nest-simulator/wiki/NEST-Modules
