### ISSUE TITLE
CGConnect crashes when showing debug information

### ISSUE THREAD

**Issue by pherbers** [nest/nest-simulator#784]
When CGConnect is used with libneurosim and csa, and a debug flag is active, NEST crashes.
This is not really critical, but I usually use debug flags for my own python code for the logger.

`cgconnect_debuglog_failure.py`

    # Execute this file using `python cgconnect_debuglog_failure.py --debug`
    # When the --debug or -d flag is active, nest.CGConnect() will crash (line 17)
    # 
    # NEST at commit 2a0f2388d89b58ed851f584818f306b55c465bb7
    # compiled with python2.7 and libneurosim
    # csa at commit d517596b9481ebf2fbd0e36fd3a5a351610c7be1

    import nest
    import csa

    pop_a = nest.Create('iaf_psc_alpha', 10)
    pop_b = nest.Create('iaf_psc_alpha', 10)

    cs = csa.random(0.5)

    nest.CGConnect(pop_a, pop_b, cs)

    print(nest.GetConnections())

    # Error log:
    In procedure:
          {
             cvx
    -->      stopped
             {
                handleerror
             }
             if
          }
    While executing: ::stopped
    In procedure:
          {
             {
                sli_func_litconv
             }
    -->      runprotected
          }
    In procedure:
          {
    -->      -stopped-
             -dup-
             {
                errordict
                newerror
                +get+
                {
                   errordict
                   message
                   +known+
                   {
                      : 
                      errordict
                      message
                      +get+
                      +join+
                      errordict
                      message
                      -undef-
                   }
                   {
                      
                   }
                   -ifelse-
                   errordict
                   errorname
                   +get+
                   cvs
                   3
                   2
                   -roll-
                   errordict
                   newerror
                   false
                   +put+
                }
                {
                   Software Interrupt
                }
                -ifelse-
             }
             -if-
             +not+
          }
    While executing: ::stopped
    In procedure:
          {
    -->      sli_func_litconv
          }
    In procedure:
          {
             <<
             >>
             begin
             mark
             rollu
             cvx
             {
                {
                   StringQ
                   {
                      dup
                      First
                      47
                      eq
                      {
                         Rest
                         cvlit
                      }
                      if
                   }
                   if
                }
                Map
                arrayload
                pop
             }
             prepend
    -->      exec
             counttomark
             arraystore
             exch
             pop
             end
          }
    In procedure:
          {
             {
                {
                   StringQ
                   {
                      dup
                      First
                      47
                      eq
                      {
                         Rest
                         cvlit
                      }
                      if
                   }
                   if
                }
                Map
                arrayload
                pop
             }
             props
             Set
             {
                props
                GetGlobalChildren
             }
    -->      Map
          }
    python: /home/patrick/Documents/nest-simulator/sli/sliarray.cc:952: virtual void SLIArrayModule::IMapFunction::backtrace(SLIInterpreter*, int) const: Assertion `count == NULL' failed.
    Aborted (core dumped)

**Comment by jougs** [comment]
This behavior is caused because NEST also handles the `-d` and `--debug` flags. The easy solution would be to ignore them if the NEST kernel is executed by PyNEST. A fix for this should probably also fix #779.
