### ISSUE TITLE
PyNEST tests occur problem "python: can't open file 'test_sp/mpitest_issue_578_sp.py' "waitting for solution

### ISSUE THREAD

**Issue by lemontree561** [nest/nest-simulator#791]
make installcheck 
Phase 7: Running PyNEST tests.
------------------------------

  Nosetests unavailable. Using fallback test harness.
  Fewer tests will be excuted.
python: can't open file 'test_sp/mpitest_issue_578_sp.py': [Errno 2] No such file or directory
python: can't open file 'test_sp/mpitest_issue_578_sp.py': [Errno 2] No such file or directory

**Comment by lemontree561** [comment]
but the test_sp/mpitest_issue_578_sp.py existed

**Comment by jougs** [comment]
@lemontree561 Thanks for the report. The issue should be fixed in #799. Please follow the discussion there for further information.
