### ISSUE TITLE
Systematic unit testing for external modules (MyModule) 

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#797]
After having put together an external module recently (https://github.com/nest/nest-simulator/pull/544#issuecomment-319948176), i have noticed that unit testing of these is still a little tricky. 

Currently i am (https://github.com/flinz/nest-module-STDPStructplast/blob/master/.travis.yml) building NEST in travis, then executing my python unit tests via cmake (inspired by https://github.com/IGITUGraz/spore-nest-module). This works, but it currently only checks one possible NEST configuration and does neither run vera++ nor cppcheck, since i am not calling build.sh (i dont want to unit test NEST itself).

It would be for example very helpful to provide a skeleton .travis.yml together with MyModule, that could be used for CI according to the current NEST standards, with given matrices of NEST configurations and optional vera and cppcheck flags. Changes in NEST master (or releases) could also propagate a rebuild of external modules to ensure they still work.

**Comment by jougs** [comment]
This will be solved by https://github.com/nest/nest-simulator/issues/1028.
