### ISSUE TITLE
Add test that neuron models heed event multiplicity

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#80]
Events, in particular `SpikeEvent`s can include a multiplicity: one event object represents several spikes emitted by a single sender in a single time step. The `handle()` method of the receiving neuron must read out this information and apply it, typically by multiplying the weight with the multiplicity. I think this only makes sense for `SpikeEvent`s, for all other event types this should lead to an error.

We currently have no test checking that all models heed multiplicity information. Add a test for this.

**Comment by flinz** [comment]
@heplesser would it make sense to attempt writing this in pynest at all, or is there a straightforward way of testing this in SLI?

In pynest one could compare the effect of a single spike with multiplicity 1 against a single spike with higher multiplicity on the state variable of all neuron models, and assert there is a difference. However, this seems a little indirect..

**Comment by heplesser** [comment]
@flinz Our basic strategy so far has been to write tests in SLI where possible. A lot of connectivity tests are probabilistic and need statistical analysis, so they are written in Python to be able to use tools from SciPy etc. But in this case, tests in SLI would be better, so the tests can run even when Python is not available. 

The basic approach here would be the same as I implemented in `ParrotNeuronPoissonTestCase`: create a high-rate Poisson generator that will emit spikes with multiplicity > 1 and look at the effect on the membrane potential of the receiving neuron. I we want to apply this to all neuron types, though, it will be difficult to come up with an expectation of what the membrane potential should look like if everything is ok. We need a test that does not require manual specification of the expectation for each neuron model.

**Comment by heplesser** [comment]
See the work on #82, especially test_parrot_neuron.py for test strategies.

**Comment by jougs** [comment]
@heplesser What is the status of this? Thanks!

**Comment by heplesser** [comment]
@jougs Thanks for reminding me about this one. I will try to get around to it shortly. Actually, I now think that one can set up a test reasonably easily: `parrot_neuron` always emits spikes with multiplicity. Thus, if we in one case send spikes at identical times from two spike generators via two parrot neurons, and once via a single parrot, then in one case we get two input spikes of multiplicity one, in the other case one spike with multiplicity two. The membrane potential after the input must be identical.
