### ISSUE TITLE
Record conductance from cond_*_multisynapse models

### ISSUE THREAD

**Issue by lucianopaz** [nest/nest-simulator#800]
Request
===
I wanted to request an enhancement to nest. In the latest stable release 2.12, it is not possible to connect a multimeter to record from the synaptic conductances of any `cond_*_multisynapse` models. At present, the only way to work around this problem is to simulate chunks of time and call GetStatus for the neurons to manually record `g`. In many situations, it is important to record the synaptic channels evolution over time to understand what drives neurons to fire (for example [decision making with attractor dynamics](http://www.ncbi.nlm.nih.gov/pubmed/16436619)) and not having a built-in method is a serious limitation.

----

Proposal
===

I want to help in any way I can to contribute to solve this issue. I have just started to use nest, so I am not entirely familiar with the source. I know a bit of c++ so I looked through the way data is logged, starting from the `aeif_cond_beta_multisynapse` model, which I am interested in using. From there I saw that the `RecordablesMap` static instance inside the neuron is used for logging data. This class inserts a pointer to a valid function that is a member of the `HostNode` and returns `double`, using template SFINAE. The way in which multiple member functions were instantiated was with templates in the `RecordablesMap::create` function.  This leads to the problem that the number of recordables needs to be known at compile time, and will be static. So apparently, in order to get to record `g` from multisynapse neurons, it will be necessary to rewrite a potentially large part of the kernel.

As I said before, I am not really familiar with nest's source, so I'm putting up for discussion what I think could be done to get to record `g`.

From what I understood (which can be fundamentally wrong, so I would appreciate if any of you point out my mistakes), the minimal list of places to apply changes to be able to record synaptic conductance in multisynapse models are:

[recordables_map.h](https://github.com/nest/nest-simulator/blob/master/nestkernel/recordables_map.h)
 The `RecordablesMap` must be changed at runtime in multisynapse models. This entails many problems. For one, the current template class uses a `DataAccessFct` which is defined as a valid `HostNode` member function that returns double, and is resolved at compile time with template SFINAE. I propose to add a functor at the neuron model level which will be treated as the new DataAccess function. This functor would get the information about the index of the `State.y_` vector to get data from at its construction time. This internal value could then remain `const` for the rest of the functor's lifecycle. The functor's `operator()` would return the recordable's state value. To remain compatible with the rest of nest, we must not touch the standard `RecordablesMap` class template.
  1) There must be a new template class like `RecordablesMap` that uses a host node's `DataAccessFunctor` class. This class could be named `DynamicRecordablesMap`. It could rely on c++11 standard's `enable_if<std::is_class<HostNode::DataAccessFunctor>::value, HostNode::DataAccessFunctor>::type &HostNode::DataAccessFunctor` to compile properly using SFINAE even for models which do not define this functor.
  2) This new class must have its insert method as public, because it will no longer be a static member of the neuron model, and its elements must be modifiable at runtime.
  3) This new class could use the base map's erase member or implement erase another one itself.

[universal_data_logger.h](https://github.com/nest/nest-simulator/blob/master/nestkernel/universal_data_logger.h)
 The `UniversalDataLogger` class must be made aware of the existance of the new dynamic `RecordablesMap` class. This means:
  1) Private class `DataLogger_` must have a constructor that takes the new dynamic `RecordablesMap` class as input.
  2) Something has to be done with the `DataLogger_`'s `node_access_` vector. Currently it is a vector of `RecordablesMap< HostNode >::DataAccessFct` instances. Maybe this could be left in place for backward compatibility and build a separate `node_access_` vector for dynamic `RecordablesMap`. At construction time, the `DataLogger_` instance would keep an internal value that tells it from which vector to get the accessors.
  3) A separate `connect_logging_device` must be implemented with the dynamic `RecordablesMap` class as input.

[universal_data_logger_impl.h](https://github.com/nest/nest-simulator/blob/master/nestkernel/universal_data_logger_impl.h)
  1) `template < typename HostNode > void nest::UniversalDataLogger< HostNode >::DataLogger_::record_data` function must be adapted. Currently, `dest.data[j]` is set by calling a `HostNode`'s function pointer that returns a double: `((host).*(node_access_[j]))()`. This must now depend on whether the `DataLogger` was constructed with the regular `RecordablesMap` or the new dynamic version of `RecordablesMap`.

Change the particular neuron model. This could be any conductance multisynapse model from which we wanted to extract runtime setted synaptic conductances. I will focus on `aeif_cond_beta_multisynapse`

[aeif_cond_beta_multisynapse.h](https://github.com/nest/nest-simulator/blob/master/models/aeif_cond_beta_multisynapse.h)
  1) `recordablesMap_` can no longer be static.
  2) `recordablesMap_` must be an instance of the new dynamic `RecordablesMap` class.
  3) The double `double get_y_elem()` function must be replaced with a functor class `DataAccessFunctor` whose `operator()` gets an element from the `State` member `S_.y_`.
  4) Check whether something has to be done to `inline port aeif_cond_beta_multisynapse::handles_test_event( DataLoggingRequest& dlr,
  rport receptor_type )`, because at that point, the `Buffer`'s `logger_` gets connected to the `recordablesMap_` instance.

[aeif_cond_beta_multisynapse.cpp](https://github.com/nest/nest-simulator/blob/master/models/aeif_cond_beta_multisynapse.cpp)
  1) `RecordablesMap::create` must be replaced with a create function for the new dynamic `RecordablesMap` class. It should be aware of the default number of synaptic receptor channels.
  2) Change the `aeif_cond_beta_multisynapse` copy constructor to get a copy of the dynamic `recordablesMap_` instance.
  3) In `aeif_cond_beta_multisynapse::Parameters_::set`, the `recordablesMap_` of the outer `aeif_cond_beta_multisynapse` class should somehow be changed if changes were done to `E_rev`, `tau_rise` and `tau_decay`. I have no idea how to do this because I don't know at which point this gets called inside the kernel.

A separate issue would be how to name the synaptic conductances. I think that they could be named "g_1", "g_2", ..., "g_(n_receptors)". I think that wont conflict with existing nest names and is completely generic.

**Comment by heplesser** [comment]
@lucianopaz Thank you for your detailed description. As you point out, the extension you need would require significant changes to the simulator kernel. Before discussing that at all, I would therefore rather like to consider your use case in more detail. 
The Wong & Wang (2006) paper you cite uses a model with four conductance based synapses, of which three are "plain" conductance-based synapses, while the NMDA-synapse has an additional voltage dependence. Thus, in this case I would propose to create a new neuron model based on an existing conductance-based model with just these conductances and then make those conductances recordable; see `ht_neuron` for a model with multiple recordable conductances.
I think this approach could be extended to cases with a moderate number of conductances; only if you would want to create models with large numbers of conductances one would need to think about different solutions. But in that case, other simulators might be better suited than NEST.
NESTML (work in progress) may make it even easier to create new NEST models with recordable conductances. Any comments, @DimitriPlotnikov ?

**Comment by lucianopaz** [comment]
@heplesser, you are right. For the particular use case that I mentioned, it is preferable to create a new neuron model based on the `ht_neuron`. However, I still think that being able to record multiple `g`'s in the builtin multisynapse models would be an important gain. I started to work on a [fork](https://github.com/lucianopaz/nest-simulator) to implement this, and I am currently writing the tests for the new recordables. Once I get that [running](https://travis-ci.org/lucianopaz/nest-simulator) I'll post a pull request and link it to this issue.

**Comment by heplesser** [comment]
Closed by merging #812.
