### ISSUE TITLE
Pushing ConnectionGenerator objects from Python to SLI fails

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#821]
As reported in [a comment in #483](https://github.com/nest/nest-simulator/pull/483#issuecomment-327026285), pushing ConnectionGenerator objects (e.g. created using [CSA](http://github.com/INCF/csa)) from Python to SLI fails with the following error message:

```
--> 165     sli_push(args)       # push array of arguments on SLI stack
    166     sli_push(s)          # push command string
    167     sli_run(slifun)      # SLI support code to execute s on args

pynestkernel.pyx in pynestkernel.NESTEngine.push (/Users/plesser/NEST/code/bld_csa_27/pynest/pynestkernel.cxx:4498)()
pynestkernel.pyx in pynestkernel.python_object_to_datum (/Users/plesser/NEST/code/bld_csa_27/pynest/pynestkernel.cxx:5590)()
pynestkernel.pyx in pynestkernel.python_object_to_datum (/Users/plesser/NEST/code/bld_csa_27/pynest/pynestkernel.cxx:6889)()
NESTError: unknown Python type: <class 'csa._elementary.OneToOne'>
```

This is probably caused by an erroneous implementation of `unpackConnectionGeneratorDatum( x )` in `nest/neststartup.h`, which results in a `null` object. However, more investigation is required to resolve the issue.

@heplesser: should we make this a 2.14.0 issue? With this bug present the CSA interface is not usable at all.

**Comment by heplesser** [comment]
@jougs Since this completely breaks CSA support in PyNEST, we should include it in 2.14.0. I will set the milestone---I suppose you are investigating already?

**Comment by jougs** [comment]
I've investigated this a bit more and consulted with @mdjurfeldt. We came to the conclusion that this is an issue in the Connection Set Algebra that needs fixing there. The corresponding issue is https://github.com/INCF/csa/issues/6. Please add further comments there.
