### ISSUE TITLE
Phase 7: PyNEST test failed with python 2.7.12

### ISSUE THREAD

**Issue by Aamanen** [nest/nest-simulator#824]
Phase 7: Running PyNEST tests.
------------------------------

  Using nosetests.

  Failure: OSError (No such file /usr/local/lib/python2.7/site-packages/nest/tests) ... ERROR
  ERROR: Failure: OSError (No such file /usr/local/lib/python2.7/site-packages/nest/tests)
    File "/home/martin/.local/lib/python2.7/site-packages/nose/failure.py", line 42, in runTest
  OSError: No such file /usr/local/lib/python2.7/site-packages/nest/tests
  FAILED (errors=1)

  PyNEST tests: 1
     Passed: 0
     Failed: 1
__________________________________________________________
Running ubuntu 16.04.03 LTS
with Configuration command: /usr/local/nest-2.12.0-build$ sudo cmake -DCMAKE_INSTALL_PREFIX:PATH=../ ../nest-2.12.0 -Dwith-python=2

Report folder

[reports1.zip](https://github.com/nest/nest-simulator/files/1295755/reports1.zip)

**Comment by Aamanen** [comment]
Here comes an update:
I tried copying the "tests" folder which is mentioned in the error, from the source directory into the directory in which the test was looking. After doing that I receive another error: 

Phase 7: Running PyNEST tests.
------------------------------

  Using nosetests.

  Failure: ImportError (No module named nest) ... ERROR
  ERROR: Failure: ImportError (No module named nest)
  ImportError: No module named nest
  FAILED (errors=1)

  PyNEST tests: 1
     Passed: 0
     Failed: 1

NEST Testsuite Summary
----------------------
  NEST Executable: ../bin/nest
  SLI Executable : ../bin/sli
  Total number of tests: 226
     Passed: 225
     Failed: 1 (1 PyNEST)
___________________________________________________________

updated report folder:
[reports2.zip](https://github.com/nest/nest-simulator/files/1314138/reports2.zip)

**Comment by gtrensch** [comment]
@Aamanen I can confirm that this is a bug in the NEST CMake scripts. We do not properly handle relative paths. A pull request is in preparation. 
The following should bypass the issue:
`/usr/local/nest-2.12.0-build$ sudo cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/nest-2.12.0 -Dwith-python=2`
Note: Do not forget to delete the old installation to remove the CMake cache.

**Comment by gtrensch** [comment]
Discussed this issue with @jougs. PR has been created #828.

**Comment by Aamanen** [comment]
@gtrensch Thank you for your reply!
It seems that it did some of the trick. At least now I am able to start the nosetest, but I get an error from the test_disconnect.py. The test gives the summary: 

  ERROR: test_synapse_deletion_one_to_one_no_sp (nest.tests.test_sp.test_disconnect.TestDisconnectSingle)
  TypeError: allgather() takes exactly 1 positional argument (2 given)
  FAILED (SKIP=11, errors=1)

  PyNEST tests: 549
     Passed: 548
     Failed: 1

And the Pynest test fails. 

I deleted the old installation folder and tried the install command with absolute paths instead. 
Here is the Reports folder 
[reports3.zip](https://github.com/nest/nest-simulator/files/1317754/reports3.zip)

**Comment by jougs** [comment]
Thanks for testing.

The exact error you are receiving is
```
ERROR: test_synapse_deletion_one_to_one_no_sp (nest.tests.test_sp.test_disconnect.TestDisconnectSingle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/nest-2.12.0-build/lib/python2.7/site-packages/nest/tests/test_sp/test_disconnect.py", line 79, in test_synapse_deletion_one_to_one_no_sp
    conns = self.comm.allgather(conns, connstotal)
  File "MPI/Comm.pyx", line 1288, in mpi4py.MPI.Comm.allgather (src/mpi4py.MPI.c:109152)
TypeError: allgather() takes exactly 1 positional argument (2 given)
```
@sdiazpier, @lekshmideepu: I seem to remember you investigated this one earlier, haven't you? Can you please comment? Thanks!

**Comment by sdiazpier** [comment]
Hi dear @Aamanen and @jougs , this is already solved in a PR from Lekshmi #789. This will be solved when the PR gets merged.

**Comment by lekshmideepu** [comment]
@jougs : I would try to address the review comments in my PR #789 as fast as possible

**Comment by Aamanen** [comment]
Thanks you so much for you quick reply and the changes to the test_disconnect.py did the trick!

I am all new to Ubuntu and the environment, so I have a related question, which I hope you can help me with:

When running python (v2.7.12) I try to import the Nest module by running :
`import nest`
and I get the error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named nest
```
I have an idea that the reference to my nest installation within my python is wrong (I probably didn't remove all the files from the earlier NEST installation), but I don't know how to inspect the depencies of python.

**Comment by jougs** [comment]
@Aamanen: thanks for testing and for the confirmation that the changes from #828 and #789 do the trick. We will make these fixes available in the upcoming NEST 2.14.0 release.

Regarding the `import` of PyNEST: you have to tell Python about the non-standard location of your modules by setting the environment variable `PYTHONPATH`. In your case, something like
```bash
export PYTHONPATH=/opt/nest-2.12.0-build/lib/python2.7/site-packages:$PYTHONPATH
```
should do the trick. The exact line was printed in the summary at the end of your `cmake` run. You can inspect the current setting by running
```bash
echo $PYTHONPATH
```

One additional remark: GitHub is merely used for hosting the code and issue tracker of NEST. Please consider subscribing to the [NEST User Mailing List](http://www.nest-simulator.org/community/) for further questions about the usage of NEST.

**Comment by Aamanen** [comment]
@jougs Thank you so much for you help - now it seems to be running smoothly! 

I was not aware of the Mailing list, but I have now subscribed. 
Thanks again!

**Comment by gtrensch** [comment]
Status update: This issue is waiting for PR #789 to be merged.

**Comment by lekshmideepu** [comment]
@gtrensch  PR #789 is already merged.
