### ISSUE TITLE
Can't build an exponential distribution of inhibitory synaptic weights

### ISSUE THREAD

**Issue by luis-rr** [nest/nest-simulator#835]
Hi!

Not sure if this is a bug, a missing feature, by design or me misunderstanding. If I should direct this somewhere else, don't hesitate to let me know and close the issue.

Some models rely on the synaptic weight being negative in order to consider the synapse inhibitory (see [here](https://github.com/nest/nest-simulator/blob/49d917723e743188a48f187ab07ca8ccc8679b3a/models/aeif_cond_exp.cpp#L558)) but the exponential distribution doesn't allow a negative lambda value (see [here](https://github.com/nest/nest-simulator/blob/15ac89b24fd08e9323dcdfe06061193bb3a6c11b/librandom/exp_randomdev.cpp#L38)). So, how can then an exponential distribution of inhibitory synaptic weights be achieved?

From the documentation ([here](http://www.nest-simulator.org/connection-management/)) I expected to be able to do:
```python
nest.Connect(
    nodes_in, nodes_ex,
    {'rule': 'fixed_indegree', 'indegree': N},
    {'model': 'static_synapse', 'weight': {'distribution': 'exponential', 'lambda': -J}})
```

Cheers,
Luis

**Comment by heplesser** [comment]
@luis-rr Right now, this is unfortunately not possible. I suppose it would be quite straightforward to implement by interpreting negative lambda as meaning a distribution with parameter |lambda| and values drawn multiplied with -1.

**Comment by luis-rr** [comment]
I've submitted a pull request.

Alternative, a work around would be:

```python
nest.Connect(
    nodes_in, nodes_ex,
    {'rule': 'fixed_indegree', 'indegree': N},
    {'model': 'static_synapse', 'weight': {'distribution': 'exponential', 'lambda': J}})

conns_in = nest.GetConnections(source=nodes_in)
weights_in = nest.GetStatus(conns_in, keys='weight')
nest.SetStatus(conns_in, [{'weight': -w} for w in weights_in])
```
