### ISSUE TITLE
Allow for RecordingBackend being a module

### ISSUE THREAD

**Issue by tomvierjahn** [nest/nest-simulator#843]
As discussed with @apeyser during this year's HBP summit, we would like to provide a separate nestio-based `RecordingDevice` via a nest module. 

Currently, we have to compile it into nest, since we have to hard-code its entry in `IOManager::recording_backends_`, and hard-code its parameters in `nest_names.*`. 

We would appreciate very much if a new `RecordingDevice` provided as a nest module could register itself to all the required places, prior to releasing a new version of nest that includes nestio.

**Comment by jougs** [comment]
This is now possible in the current [HEAD of the development branch](https://github.com/apeyser/nest-private/tree/nestio). I'm thus closing. Thanks for the request!
