### ISSUE TITLE
 CMakeLists.txt file for the extension module ignores DCMAKE_INSTALL_PREFIX flag 

### ISSUE THREAD

**Issue by mickelindahl** [nest/nest-simulator#847]
**Description of problem:**
CMakeLists.txt file for the extension module  seems to strictly uses the installation directory for NEST and ignores the DCMAKE_INSTALL_PREFIX variable  whilte running cmake.

Background
I am trying to compile my module on an supercomputer  (https://www.pdc.kth.se/resources/computers/beskow) that already has nest 2.12.0 installed. I need to install the module in an other directory than the default  in nest install path. Here (https://nest.github.io/nest-simulator/extension_modules) I read  that I should set the cmake flag DCMAKE_INSTALL_PREFIX to set a different installation directory. Unfortunately this does not seem to work for me.

**Version-Release or Git commit:** 

nest-2.12.0

**How reproducible: (Always/Sometimes/Unsure)**

Always

**Steps to Reproduce:**

1. Open attached archive with module source 
2. Compile module

installDir={module installation directory}
NEST_INSTALL_DIR={nest installation directory}

cmake -DCMAKE_INSTALL_PREFIX=$installDir -Dwith-nest=${NEST_INSTALL_DIR}/bin/nest-config
      ../$MODULE_NAME  

make 
make install

**Actual results:**
Scanning dependencies of target generate_help
Extracting help information; this may take a litte while.
[  0%] Built target generate_help
Scanning dependencies of target ml_module_module
Scanning dependencies of target ml_module_lib
[  6%] [ 18%] [ 18%] [ 31%] [ 31%] [ 43%] [ 50%] [ 50%] [ 62%] [ 62%] [ 81%] [ 87%] [ 87%] [100%] [100%] [100%] Building CXX object CMakeFiles/ml_module_module.dir/ml_module.cpp.o
Building CXX object CMakeFiles/ml_module_lib.dir/pif_psc_alpha.cpp.o
Building CXX object CMakeFiles/ml_module_module.dir/poisson_generator_periodic.cpp.o
Building CXX object CMakeFiles/ml_module_lib.dir/step_pattern_builder.cpp.o
Building CXX object CMakeFiles/ml_module_lib.dir/my_poisson_generator.cpp.o
Building CXX object CMakeFiles/ml_module_module.dir/poisson_generator_dynamic.cpp.o
Building CXX object CMakeFiles/ml_module_module.dir/my_aeif_cond_exp.cpp.o
Building CXX object CMakeFiles/ml_module_lib.dir/my_aeif_cond_exp.cpp.o
Building CXX object CMakeFiles/ml_module_lib.dir/izhik_cond_exp.cpp.o
Building CXX object CMakeFiles/ml_module_module.dir/pif_psc_alpha.cpp.o
Building CXX object CMakeFiles/ml_module_lib.dir/ml_module.cpp.o
Building CXX object CMakeFiles/ml_module_module.dir/step_pattern_builder.cpp.o
Building CXX object CMakeFiles/ml_module_module.dir/izhik_cond_exp.cpp.o
Building CXX object CMakeFiles/ml_module_lib.dir/poisson_generator_dynamic.cpp.o
Building CXX object CMakeFiles/ml_module_module.dir/my_poisson_generator.cpp.o
Building CXX object CMakeFiles/ml_module_lib.dir/poisson_generator_periodic.cpp.o
Linking CXX shared library libml_module.so
Linking CXX shared module ml_module.so
[100%] Built target ml_module_lib
[100%] Built target ml_module_module

Extracting help information; this may take a litte while.
[ 68%] [100%] Built target ml_module_module
Built target ml_module_lib
[100%] Built target generate_help
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:42 (FILE):
  file cannot create directory: /pdc/vol/nest/2.12.0-py27/lib64/nest.  Maybe
  need administrative privileges.

make: *** [install] Error 1

**Expected results:**

Succesfull compilation

**Additional info:**

I have attached and archive with my module,  compilation script and log files

[mymodule-issue.tar.gz](https://github.com/nest/nest-simulator/files/1426942/mymodule-issue.tar.gz)

**Comment by tammoippen** [comment]
This is correct. See #844 : this also changes the behavior with handling the `CMAKE_INSTALL_PREFIX` for user modules. Also have a look at `NEST_MODULE_PATH` and `SLI_PATH` env variables, that should be set when modules are not installed in the default directory. You can take the CMakeList.txt from #844 as a sample and should get your module working with nest 2.12 as well.

**Comment by terhorstd** [comment]
this is fixed in NEST 2.14.
