### ISSUE TITLE
neststartup.cpp:(.text+0x18): undefined reference to `nest::ModelsModule::ModelsModule()'

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#851]
This is seen on while building nest on the K computer:

```
[ 99%] Linking CXX static library libnest.a
[100%] Linking CXX executable nest
[100%] Built target nest_lib
CMakeFiles/nest.dir/neststartup.cpp.o: In function `add_static_modules(SLIInterpreter&)':
neststartup.cpp:(.text+0x18): undefined reference to `nest::ModelsModule::ModelsModule()'
make[2]: *** [nest/nest] Error 1
make[1]: *** [nest/CMakeFiles/nest.dir/all] Error 2
make: *** [all] Error 2
```
CMake options are below:
```
$ cmake -DCMAKE_TOOLCHAIN_FILE=Platform/Fujitsu-Sparc64 -DCMAKE_INSTALL_PREFIX:PATH=/data/share035/opt/nest-simulator -Dwith-gsl=OFF -Dwith-optimize="-Kfast,openmp -x1" -Dwith-defines="-DUSE_PMA" -Dwith-python=OFF -Dwith-warning=OFF /data/share035_new/src/nest-simulator
```

**Comment by heplesser** [comment]
@ikitayama Which version of NEST were you building? If it is a recent version, do you know an older version that could be built successfully?

**Comment by ikitayama** [comment]
I'm at currently HEAD. Don't know the version last worked, sorry.

**Comment by ikitayama** [comment]
@heplesser I think I am almost the only one I can reproduce the issue, what's the next step to
resolve this issue?

**Comment by heplesser** [comment]
@ikitayama I would try two approaches. One would be to use tools to inspect the object code generated for symbols defined and expected. That may give some hint where things may go wrong. The other approach would be to try to install older versions of NEST (e.g. the 2.12 and 2.14 releases) and once you have found a version that works use bisectioning to find the change that introduced the error.

@jakobj Could you assist in solving this problem? I do not have any personal experience with K.

**Comment by ikitayama** [comment]
v2.12.0 does build cleanly, but v2.14.0 does not on the K computer frontend.

**Comment by sreeramsharma** [comment]
JtagCli.cpp:(.text+0x31f): undefined reference to `ZiiDiag::JtagTarget::JtagTarget()'
 How to avoid that error during compilation .....

**Comment by heplesser** [comment]
@sreeramsharma Are you quite sure you posted you question in the right place? This does not look like anything in the NEST (Neural Simulation Tool) code base.

**Comment by heplesser** [comment]
Problems are fixed in master, thus closing.
