### ISSUE TITLE
Are you interested in `pip install pynest` ?

### ISSUE THREAD

**Issue by tammoippen** [nest/nest-simulator#853]
After working on #844, I was wondering, if I could decouple NEST and PyNEST even further and had some interesting hacking hours. Now, I have a [prove of concept](https://github.com/tammoippen/nest-simulator/tree/pynest) to make NEST and PyNEST two independent projects, with NEST completely dependancy-free from PyNEST or Python installations and PyNEST installs with setup.py using `nest-config`. This gives:

* No python / cython discovery and handling in CMakefiles, except for `docs` generation. 
* NEST does not need to link to the python lib, not even with `conngen` enabled.
* `pip install nest` ! One could think about deploying PyNEST to http://pypi.python.org/ ?
* Parallel installation of PyNEST for Python2 and Python3 with only one installation of NEST.
* Possibly have PyNEST in a separate repository?
* pytest (unrelated)

On the other hand, this would require to install NEST and PyNEST separately, something like:

```sh
cmake ...
make
make install
pip install pynest/
```

And two build chains have to be maintained!

There are still some TODO's regarding documentation and testing, and maybe some questions regarding the design decisions. I would like to know, whether there is interest in this refactoring and if i should continue? Addressing the missing parts will require some effort on my side and I am unsure if I should invest. I am happy to do so, if there is consent.

What changed in detail so far:

* Remove most Python/Cython related stuff from CMakefiles
* Extend `pynest/setup.py` to compile the cython extension, build and install PyNEST. `pip install pynest/`  will install pynest to default python `site-packages` directories.
* Put the python extension from the `topology` module also into PyNEST. Right now, it is not possible, to install nest without topology, hence the python extension will also always be installed. To reflect this in this changes, I moved the topology python files.
* Remove `cythonize-pynest` option from CMakefiles: the setup.py excepts options to use rebuild python extensions. Crosscompiling still has to be tested.
* Remove libneurosim / python parts from `neststartup.h/.cpp` and put them into a new header file in PyNEST: `pynestkernel.h`
* move `pynestkernel.pyx/pxd` into the `nest` folder of pynest.
* install python examples twice: once for nest / once for the pynest installation.
* have `do_tests.sh.in` discover, whether there is a pynest installation and do tests, if they are found. (Use `pytest` instead of `nose` see #761. One could also think about putting that part into a separate PR; accept both `nose` or `pytest`; stick to `pytest` and also remove `do_tests.py.in` support altogether.)
* there is also `extras/ConnPlotter/` python package ... I did not put this into pynest, because I am not sure, how both relate. Maybe this could also be a separate package / project / repository?
* changed travis ci to reflect the install procedures. TravisCI works, but finds one python test failing ... I have to investigate: https://travis-ci.org/tammoippen/nest-simulator/builds/298469055
* The code is still not PR ready, has some debug stuff, and a ugly git history...

TODOs:
* Documentation.
* Code cleanup.
* Pytest fixing.
* git history fixing.
* cross compiling testing and documenting. see http://spscicomp.org/wordpress/wp-content/uploads/2014/05/BertrandBrelier_PythonBGQ.pdf slide 17ff)
* unforeseeables ...

**Comment by Silmathoron** [comment]
Thanks @tammoippen this indeed looks quite interesting and makes sense to me

**Comment by tclose** [comment]
This would be nice as it would allow you to keep a single NEST install and multiple pyNEST installations for different Python versions.

**Comment by heplesser** [comment]
@tammoippen We discussed this PR in the [NEST Developer VC last Monday](https://github.com/nest/nest-simulator/wiki/2017-11-13-Open-NEST-Developer-Video-Conference) and concluded that such a separation is probably not a good idea at the moment. 

The main problem is that NEST currently does not have a well-defined C++ API, even less a precisely defined SLI command interface, which is essential for PyNEST's communication with the NEST kernel.  Changes on the kernel or SLI level frequently need corresponding adaptations in the PyNEST hl_api and keeping both NEST and PyNEST in sync when installing via two different channels will be challenging and may result in difficult to debug installation problems.

Furthermore, the most difficult part of the installation is probably building NEST itself, rather than installing PyNEST, so the gain for users who struggle with installing NEST would be limited.

@tclose has a good point, since supporting different Python versions on the same computer certainly is a valid use case. Building NEST completely for each Python version is necessary now and more tedious than necessary. But I wonder if we could not solve this by changes to the build mechanism (building multiple PyNESTs in one build directory), while sticking with monolithic distribution.

**Comment by tammoippen** [comment]
@heplesser I agree. Keeping NEST and PyNEST in sync would be quite difficult, when PyNEST is distributed via pypi. Especially, when you want to install different versions of NEST/PyNEST. This is only a minor suggestion in this issue. Also putting PyNEST into a seperate repository is a minor suggestion.

> Furthermore, the most difficult part of the installation is probably building NEST itself, rather than installing PyNEST, so the gain for users who struggle with installing NEST would be limited.

I agree, that building NEST itself is the difficult part. Having to build the PyNEST wrapper along NEST creates some of these difficulties:
- no / wrong python detected
- no / wrong cython detected
- many issues related to building, installing, running PyNEST

The main changes I suggestion in this issue is to untie NEST and PyNEST building steps:
- NEST does not need to know abould python to do its simulation tasks. One can remove almost all Python related discovery / handling from the cmake build files (except for docs creation), change the `neststartup` a little and have NEST free from Python. NEST building would have no `with-python` and `cythonize-pynest` options anymore.
- PyNEST's `setup.py` would be a little more involved (130 lines vs 37 lines):
    - discover NEST installation via `nest-config`
    - handle cythonize, if requested
    - build the extension to communicate with NEST the way it does right now

  Some minor changes to pynestkernel.pyx/.pxd/.h. No changes to PyNEST code.

Installation would look something like this:
```sh
» git clone https://github.com/nest/nest-simulator.git
» mkdir build
» cd build install

# build install NEST
# make sure NEST deps are installed: libtool, gcc, g++, cmake, gsl, readline
» cmake ../nest-simulator -DCMAKE_INSTALL_PREFIX=../install ... (other NEST options)
» make install -j8
» source ../install/bin/nest_vars.sh
# NEST installation is finished

# build / install PyNEST
# may be create a virtualenv for python: `virtualenv --python=python3.6 venv`
# and use that virtualenv: `source venv/bin/activate`
# maybe think about using pipenv...
# make sure python deps are installed: `pip install matplotlib numpy scipy cython`
» pip install --editable ../nest-simulator/pynest
» python -c 'import pynest'

# if you do not want to cythonize:
» cd ../nest-simulator/pynest
» python setup.py install --no-cythonize
```
(this workflow already works with this [feature-branch](https://github.com/tammoippen/nest-simulator/tree/pynest))

You can install multiple PyNEST versions for Python2/3, pypy (not tried), ... and this would keep the monolithic distribution.

I think this simplifies PyNEST development a lot and helps supporting 2/3 compatibility, as testing is more or less a switch of virtualenv's.

**Comment by tclose** [comment]
FWIW This seems like a good idea to me. Being able to install multiple Python bindings for the same NEST install would be nice.

**Comment by heplesser** [comment]
@tammoippen I like your idea in principle. It would lead to a nice separation of concerns and would allow the combination of one NEST with multiple Pythons as @tclose suggested.

But I am wondering a little about the future. We are busily planning for and working on NEST3 and that will probably bring a closer integration of NEST and Python in particular in two areas:

- Passing data into/out of the NEST kernel
- Passing JIT-compiled Python functions to the NEST kernel for evaluation during parameter initialization and connection creation.

This may lead to dependencies between the NEST kernel and Python in the future. Therefore, I would suggest to wait a little to see what precisely we come up with for NEST 3.

**Comment by terhorstd** [comment]
@jougs, do you have a comment on this?

**Comment by Silmathoron** [comment]
Just to say that, even if say Cython was to be used to couple the kernel and PyNEST, as long as we make sure that the sources are accessible (copy them in a ~/.nest file?) and that we can find the path to where the libraries are installed (idem), then it is theoretically possible to uncouple both and make PyNEST pip installable.
As an example, the [igraph](http://igraph.org/redirect.html) library does something like this (no idea how strong the py/c coupling is, though).

**Comment by jougs** [comment]
I have a feeling that at the moment this causes more trouble than good. People would still have to have a compiler, the GSL and some other libraries around and we would have to define and manage the dependencies different versions of NEST and PyNEST.

I thus think that building PyNEST alongside NEST is just the easiest option for both us and the users. For absolute beginners, I'd rather have packages for the main operating systems available.

**Comment by jougs** [comment]
I will close this due to clear undecidedness on the issue.
