### ISSUE TITLE
Formatting in py_sample examples on website

### ISSUE THREAD

**Issue by tmchartrand** [nest/nest-simulator#854]
Not sure this is the right place to post this, but since they seem to be generated from the python examples I figured I'd post here.

Description of problem:
The inline code blocks in the py_sample examples on the website are getting formatted essentially as multiline code blocks, making it hard to read these examples. See screenshot (from [gap_junctions_inhibitory_network](http://www.nest-simulator.org/py_sample/gap_junctions_inhibitory_network/)):
![image](https://user-images.githubusercontent.com/12821536/32510984-4dd80c2e-c3a7-11e7-8bbc-c7b333a4a9d9.png)

**Comment by steffengraber** [comment]
@tmchartrand Thank you for finding out (and reporting it). There is now a newer version of the example online. See: http://www.nest-simulator.org/py_sample/gap_junctions_inhibitory_network/
