### ISSUE TITLE
Nest installation with python

### ISSUE THREAD

**Issue by Tigerji** [nest/nest-simulator#866]
Hi Guys,

It has been fixed, but dont know how to mark this issue as closed.

Trying to install a nest simulator (2-14-0) on Ubuntu for research propose, always get errors and looking for any advice for next direction:

OS: Ubuntu 16.04
python version: 2.7.12 & 3.5.2 (both has -dev installed)
cmake version: 3.5.1
cython version: 0.27.3
pip version: 9.0.1

steps taken:
1. download and extract nest installation files(/home/users/programs/nes-simulator-2.14.0)
2. make new folder and move to new directory(/home/users/programs/nest)
3. make both directory readable(sudo chown users -R ~/programs/*)
4. sudo cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/users/programs/nest -Dwith-python=2 /home/users/programs/nest-simulator-2.14.0

terminal summary:
Build type          : 
Target System       : Linux
Cross Compiling     : FALSE
C compiler          : /usr/bin/cc
C compiler flags    :  -O2 -Wall -fopenmp -fdiagnostics-color=auto
C++ compiler        : /usr/bin/c++
C++ compiler flags  :  -O2 -Wall -fopenmp -fdiagnostics-color=auto
Build dynamic       : ON

Built-in modules    : models;precise;topology
User modules        : None
Python bindings     : Yes (Python 2.7: /usr/bin/python2)
       Includes     : /usr/include/python2.7
       Libraries    : /usr/lib/x86_64-linux-gnu/libpython2.7.so

Cython bindings     : Yes (Cython 0.27.3: /usr/local/bin/cython)
Use threading       : Yes (OpenMP: -fopenmp)
Use GSL             : Yes (GSL 2.4)
    Includes        : /usr/local/include
    Libraries       : /usr/local/lib/libgsl.so;/usr/local/lib/libgslcblas.so

Use Readline        : Yes (GNU Readline 6.3)
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libreadline.so;/usr/lib/x86_64-linux-gnu/libncurses.so

Use libltdl         : Yes (LTDL )
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libltdl.so

Use doxygen         : No
Use MPI             : No
Use MUSIC           : No
Use libneurosim     : No

--------------------------------------------------------------------------------

The NEST executable will be installed to:
/home/users/programs/nest/bin/

Documentation and examples will be installed to:
/home/users/programs/nest/share/doc/nest/

PyNEST will be installed to:
/home/users/programs/nest/lib/python2.7/site-packages

To set necessary environment variables, add the following line
to your ~/.bashrc :
/home/users/programs/nest/bin/nest_vars.sh

-- Configuring done
-- Generating done
-- Build files have been written to: /home/users

5. sudo make
...
[ 99%] Built target nest
[ 99%] Compiling Cython CXX source for pynestkernel...
warning: /home/users/programs/nest-simulator-2.14.0/pynest/pynestkernel.pyx:496:10: Unreachable code

then there is a long list of warnings.

for example: /usr/include/python2.7/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)

6. installed nest several times to associate with python2 and python 3, (-Dwith-python=2/3), after installation when trying to access nest in python (import nest as sim), it failed to find the respective files. When executed from the directory it will work and the header files as following:
              -- N E S T --
  Copyright (C) 2004 The NEST Initiative
  Version 2.14.0 Dec  7 2017 19:24:20

Any test/cmake error logs will be provided for further clarification, thanks for the help.

# problems spotted and solved:
1. Previously countered a problem 'python.h' not found, even when python-dev is installed. changed 'python.h' to 'python2.7/python.h' and 'python3.5/python.h' will get rid of the error, but after installation python still cannot link to nest.

**Comment by mschmidt87** [comment]
This sounds to me as if you have not added the path to the pynest installation to your system's PYTHONPATH. You can either do this manually or by executing `nest_vars.sh` in your `bashrc` file. This is what's meant by the output of the cmake configuration:

> To set necessary environment variables, add the following line
> to your ~/.bashrc :
> /home/users/programs/nest/bin/nest_vars.sh

**Comment by Tigerji** [comment]
Hi, thanks for replying.

The bashrc file has been updated. Both the bashrc file inside nest folder
and the bash file under /home (sourced)

Regards,
Tiger

**Comment by mschmidt87** [comment]
If I understand your problem correctly, this should be unrelated to the NEST installation itself.
So, you can import pynest when you're in the folder of the NEST installation, but outside of it you get an import error, such as
`ImportError: No module named 'nest'`. Is that correct?

Then there has to be something wrong with your python path. Can you typing 
`echo $PYTHONPATH` or
within a python/ipython shell:
```
import sys
print(sys.path)

```
and verify that the path to pynest is in the path? According to the cmake output you posted above, this should be `/home/users/programs/nest/lib/python2.7/site-packages`.

**Comment by Tigerji** [comment]
Hi, when I cd to nest folder and use python in shell, *import nest* it gave
the same error.

I have re-installed nest under *:/var/local/lib/python2.7/dist-packages*

the feedback from shell for *echo $PATHONPATH* is also

*:/var/local/lib/python2.7/dist-packages*
​


Regards,
Tiger

**Comment by mschmidt87** [comment]
So, let me try to get that clear. When you do move to the directory that contains the pynest installation (`/home/users/programs/nest/lib/python2.7/site-packages` or now after your new installation `var/local/lib/python2.7/dist-packages`), you get an import error? Is there a folder called `nest`? 

If yes, then it should be possible to import nest. If not, then something went wrong with the installation.

**Comment by Tigerji** [comment]
Hi,

The new installation is under var/local/lib/python2.7/dist-packages, it is
not only a new installation of nest, but also a clean reinstall of ubuntu.

There is a folder called nest-2.14.0

The error is same as previous cases: nest executable can run directly
from terminal,
but python cannot find nest (even if cd to var/local/lib/python2.7/dist-
packages).



Regards,
Tiger

**Comment by mschmidt87** [comment]
When you say "The new installation is under var/local/lib/python2.7/dist-packages", does this mean that the pynest package is in this path oder the nest directory? What I mean is the following;

After executing the configure line, you get the output as the one shown above, which contains a line like:

> PyNEST will be installed to:
> /home/users/programs/nest/lib/python2.7/site-packages
> 

This is the folder that contains the PyNEST installation. So in your case, did cmake say that it installed PyNEST to` var/local/lib/python2.7/dist- packages`? Or what did it say?
Can you please post two things:

- The output of the configuration (like you posted in the first post)
- the contents of the folder that cmake said will be the location of PyNEST ("PyNEST will be installed to...")

**Comment by Tigerji** [comment]
Hi,

Thanks for the help, it worked. As for this question, It has been several
rounds of re-install of ubuntu and nest since the last time I posted. The
output of configuration is no longer accessible. If it is not wrong, the
folder nest installed to is: /var/local/lib/python2.7/dist-packages.
However, it should be installed to (var/local/lib/python2.7/site-packages)

Will edit the profile and include any changes made along the way.

Regards,
Tiger

**Comment by Tigerji** [comment]
close as problem solved.

**Comment by jougs** [comment]
Is this issue fixed?

**Comment by Tigerji** [comment]
It has been fixed

Regards,
Tiger

**Comment by piewchee** [comment]
hi, 
I am facing similar error with "no module named nest" 
however the error is slightly different.
OS: Ubuntu 16.04
python version: 2.7.12 
cmake version: 3.5.1

in virtualenv:venv

I am using the command:   cmake -DCMAKE_INSTALL_PREFIX:PATH=</install/path> </path/to/NEST/src> 

After the installation, i checked under venv/lib/python2.7/site-packages; there is no "nest" installed.

May I know what is wrong?

Best Regards
Del
