### ISSUE TITLE
User module not linked with NEST in recent GCC versions

### ISSUE THREAD

**Issue by jgarridoalcazar** [nest/nest-simulator#869]
**Description of problem:**
GCC (versions 4.6 and above) does not link user modules when building NEST with such an option. By default, recent GCC versions do not link against libraries that are not used at compile time (i.e. if no symbols are imported from them, as it is the case of user modules). It is reported [here](https://stackoverflow.com/questions/11631161/force-to-link-against-unused-shared-library). This issue has been reported in the NEST user mailing list.

**Version-Release or Git commit:**
I have reproduced this issue on NEST 2.10, 2.12 and 2.14 (current master branch 3d4d2bad93dd424b29304e56bd2a85bbecc441d1)
Compiler and OS: gcc 5.4.0, cmake 3.5.1, Ubuntu 16.4

**How reproducible: (Always/Sometimes/Unsure)**
Always.

**Steps** to Reproduce:
1. Install NEST as usual: cmake -DCMAKE_INSTALL_PREFIX:PATH=<NEST_PREFIX> <nest_source>; make; make install
2. Compile and install myModule example: cmake; make; make install.
3. Recompile NEST with external module: cmake -DCMAKE_INSTALL_PREFIX:PATH=<NEST_PREFIX> -Dexternal-modules=my <nest_source>
4. Check linked libraries in NEST executable. ldd <NEST_PREFIX>/bin/nest

**Actual results:**
A long list of libraries but not including libmymodule.so.

**Expected results:**
The same list adding libmymodule.so

**Additional info:**
Due to this bug the node and synapsis models including in that module are not available in the list on NEST startup.

**Comment by heplesser** [comment]
Fixed by merging #871.
