### ISSUE TITLE
MPI tests for connect fail locally

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#874]
When trying to execute `test_connect_all_patterns.py` locally, I always receive the following error:

```bash
$ nosetests /home/jordan/opt/nest-simulator/install/lib/python3.5/site-packages/nest/tests/test_connect_all_patterns.py

======================================================================
FAIL: testWithMPI (nest.tests.test_connect_all_patterns.TestConnectAllPatterns)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jordan/opt/nest-simulator/install/lib/python3.5/site-packages/nest/tests/test_connect_all_patterns.py", line 60, in testWithMPI
    ", ".join(failing_tests))
AssertionError: False is not true : The following tests failed when executing with "mpirun -np 2 nosetests [script]": test_connect_all_to_all.py, test_connect_one_to_one.py, test_connect_fixed_indegree.py, test_connect_fixed_outdegree.py, test_connect_fixed_total_number.py, test_connect_pairwise_bernoulli.py
```

Am I running the MPI tests wrong or is this a bug? @hannahbos @heplesser @jougs 

My setup is Debian 9.0, Python 3.5.2, NEST master revision 3d4d2bad, compiled with OpenMP and MPI

**Comment by hakonsbm** [comment]
The error message you get means that the tests listed in the assertion error message fail when trying to run them with `mpirun`. However, I can't seem to reproduce it on my machine. Please try running some or all of the tests with
```
mpirun -np 2 nosetests [script]
```
where `[script]` is one of the scripts that are failing, and post the output or error message.

**Comment by jakobj** [comment]
As it turns out, this problem disappears on my new machine, where I've reinstalled everything from scratch. As far as I remember the strange thing about this was that I was able to run all individual tests, also with `mpirun`, only the test that uses `mpirun` itself (`test_connect_all_patterns.py`) failed. In any case, this issue can be closed.
