### ISSUE TITLE
Evaluate the use of the hypothesis test framework

### ISSUE THREAD

**Issue by jougs** [nest/nest-simulator#877]
[Hypothesis](http://hypothesis.readthedocs.io/en/latest/) is a framework that allows to specify test cases in the form of intents rather than writing the full code for the tests. The framework should be evaluated on the course of the [Project about evaluating new Python test frameworks](https://github.com/nest/nest-simulator/projects/3).

**Comment by terhorstd** [comment]
The [Open NEST Developer VC on 16 April](https://github.com/nest/nest-simulator/wiki/2018-04-16-Open-NEST-Developer-Video-Conference) decided to move to `py.test`, thus closing.
