### ISSUE TITLE
nest-simulator on windows.

### ISSUE THREAD

**Issue by j143** [nest/nest-simulator#889]
Hi, is it possible to build nest-simulator on windows.

windows 10, visual studio 2017 is available. 
Is there any step-by-step instruction available?. Thanks a lot.

**Comment by jougs** [comment]
@j143: There was a mail by @w-klijn about compiling NEST using Bash on Ubuntu on Windows10 [here](http://mail.nest-initiative.org/cgi-bin/mailman/private/nest_user/2017/005006.html). To access the mail in the archive, you have to subscribe to the [mailing list](http://www.nest-simulator.org/community/).

I'm closing this, but please feel welcome to discuss this issue on the mailing list.
