### ISSUE TITLE
Direct comparison of floating point numbers in STDP

### ISSUE THREAD

**Issue by suku248** [nest/nest-simulator#894]
Floating point numbers are tested for equality without using an error margin in `ArchivingNode` and all STDP models, which results in spikes being included/excluded by mistake in the STDP update.

The problem is shown [in this commit](https://github.com/suku248/nest-simulator/commit/76f7f82bb8fa13a7b63321739e40bd75e3007e9e) when running `hpc_benchmark.sli`.

In the long run, we need to use NEST's standard way of representing spike times as integer time stamps (and double offsets in case of off-grid spiking). This needs testing of possible implementations. For example, we need to check whether storing spikes as integer time stamps and double offsets in `ArchivingNode` instead of just storing double spike times results in performance penalties.
I am working on this but, for now, we might want to incorporate this [temporary fix](https://github.com/suku248/nest-simulator/commit/c0d88698b440f6492644aa37434f101fb2b3ccea).

**Comment by heplesser** [comment]
@suku248 Your "temporary fix" seems sensible, but how robust would it be when precise neurons are combined with STDP? Would you create a PR based on the fix?

**Comment by heplesser** [comment]
@suku248 I will close this as we have a fix per #924. Would you create a follow-up issue for a more thorough solution to the underlying problem?
