### ISSUE TITLE
Missing third rotation angle when rotating masks in 3D

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#899]
With PRs #664 and #845 we added the possibility to rotate the rectangle/box and elliptical/ellipsoidal topology masks. However, in 3D we are missing one of the rotation angles, namely rotation from the y-axis to the z-axis (the &#947; [here](https://en.wikipedia.org/wiki/Euler_angles#/media/File:Eulerangles.svg)). The third rotation angle should be added for completeness.

**Comment by heplesser** [comment]
Closing since there is no user demand for this feature.
