### ISSUE TITLE
[feature request] Create multiple synapses among neuron pairs with a single tp.ConnectLayers

### ISSUE THREAD

**Issue by TomBugnon** [nest/nest-simulator#904]
Dear all,

I would like to connect the neurons in two layers according to a given spatial profile and using multiple receptors (GABA_A & GABA_B, or AMPA & NMDA in my case). That is to say, I would like to use nest.Topology to draw the pre/post-synaptic neuron pairs, and connect each of those pairs multiple times with different types of synapses (one for each receptor type in my case). This seems rather natural to have this feature since this is what happens in the brain.
 
However, as of today I couldn't think of a way to do so easily using `tp.ConnectLayers`. If I were to call `tp.ConnectLayers()` multiple times with different synapse models, the pre/post-synaptic pairs would be different between the two calls. The only option I can think of right now would be to gather the connections with `nest.GetConnections()` and connect each pair another time with a different synapse model. This is certainly doable but...
Wouldn't it be great if the `synapse_model` value in the connection parameters could be a list of synapse models. ConnectLayers() could then create a single synapse for each model in that list between each of the drawn neuron pairs.

There might be a good reason why this is not already an option that I am not aware of, but is this a feature that you would otherwise consider incorporating in future versions? 
Thanks!

**Comment by heplesser** [comment]
@TomBugnon This is indeed a very relevant use case and the only reason that this is not supported at the moment is that this use case has only come to our attention very recently. The most crucial point would be to define a clear semantics that integrates well with remaining `Connect()` semantics.

**Comment by TomBugnon** [comment]
I'm not so familiar with c++ nor with the details of the simulator so let me just put out there a possibly naive solution:

How about allowing the `synapse_model` parameter in `ConnectionCreator` to be either a model name or an iterable (eg of the form `['model_1', 'num_syn_1', 'model_2', 'num_syn_2', ...]`, or `['model_1', 'model_2', ...]`, as for the layer's `elements` specification). That could be done by defining a union type that would keep track of the original type. ?
All the `ConnectionCreator`'s `connect_` functions in `connection_creator_impl.cpp`and `connection_creator.h` could then check the original type of `synapse_model_` before each `kernel().connection_manager.connect` call and possibly loop those call if `synapse_model` is an iterable.

**Comment by heplesser** [comment]
@TomBugnon I was first of all thinking about the semantics at the Python level. The most straightforward approach there would be to allow a a container for the `syn_spec` argument, with one model name or dictionary per synapse to be created for each connection. 

There is a complication, though, since we at present also are thinking about finding a way to reduce the number of `Connect()` calls (which have quite a bit of overhead), by allowing lists of source and target populations to be passed to `Connect()`. This creates some risk of confusion. I will try to prepare an integrated proposal within a few weeks.

**Comment by TomBugnon** [comment]
That would be great. Please let me know if there is anything I could do to help you out with this.

**Comment by heplesser** [comment]
@TomBugnon Until we have proper support for co-located synapses, I have realised that there is a reasonably efficient work-around. You can first create one type of synapses as usual, but label them using NEST's labeled synapse model variants. For almost all synapse models in NEST, there is a `_lbl` variant, which allows you to set an integer synapse label on the connection. If you use a different label for each `ConnectLayers()`  call, you can later use `GetConnections()` to retrieve all connections made and then use plain `Connect()` with the `one_to_one` rule to add the second synapse. Here is an example:
```
l = topo.CreateLayer({'rows': 2, 'columns': 3, 'elements': 'iaf_psc_exp'})

for proj in range(3):
    nest.SetDefaults('static_synapse_lbl', {'synapse_label': proj})
    topo.ConnectLayers(l, l, {'connection_type': 'convergent',
                              'mask': {'circular': {'radius': 0.2 * (proj + 1)}},
                              'synapse_model': 'static_synapse_lbl'})

# Add additional connection only for those connections created with proj==1
conns_p1 = nest.GetConnections(source=nest.GetChildren(l)[0], synapse_label=1)
srcs, tgts, _, _, _ = zip(*conns_p1)
nest.Connect(srcs, tgts, 'one_to_one', {'model': 'stdp_synapse'})
```

**Comment by TomBugnon** [comment]
Thank you for your return. I implemented this workaround in the front-end I use to run simulations. It works but is quite slow (with my network, 1-2sec for each regular `ConnectLayer` call, as opposed to 15-20sec for querying and duplicating each of the >50  projections for which I need multiple receptors), so it would be great to eventually have proper support for this feature. Cheers

**Comment by terhorstd** [comment]
This is still being worked on.
