### ISSUE TITLE
How am I supposed to run SLI file? 

### ISSUE THREAD

**Issue by Vafa-Andalibi** [nest/nest-simulator#908]
There is not a single example/tutorial whatsoever about how to run a .sli file. All the examples in the websites are for PyNest which I'm not using. I'm trying to run a sli file in SLI environment, after reading help I found the "run" command I intuitively tried this as like in every command line environment anywhere: 
`SLI ]  run coba.sli `
and I get this:
```
Mar 11 18:34:00 run [Error]: StackUnderflow
    Command needs (at least) 1 argument(s).
    
    Candidates for +run+ are:
    stringtype     calls <proceduretype>
```
No information about how to even use a command. I dug through the whole Internet and could remotely find an example for another command , and apparently the argument is going to be before the command. So I try this: 
 `SLI ]  coba.sli run `
and I get 
```
Mar 11 18:38:30 SLIInterpreter::execute [Error]: DictError
    Key '/coba.sli' does not exist in dictionary.
```
Please teach me how to run a .sli file.

**Comment by heplesser** [comment]
@Vafa-Andalibi Questions like this are more suitable for the NEST User Mailing list (http://www.nest-simulator.org/community/). SLI is based on Postscript, so arguments always come first. To run a SLI file, use
```
(coba.sli) run
```
Unless there are very specific reasons for why you need to avoid Python, I would suggest using the PyNEST interface.
