### ISSUE TITLE
Proposal: NEST web API

### ISSUE THREAD

**Issue by babsey** [nest/nest-simulator#910]
Hello,

I want to intoduce NEST web API which is simular to pyNEST. Thus, this API takes GET or POST requests for methods existing in pyNEST e.g. Create, Connect, GetStatus, SetStatus, Simulate ...
and the arguments are data of the AJAX request (the data can be formated in JSON).
However, I did not test it with NEST Topology but I assume it could also work with it.

I like the idea that NEST with NEST web API running inside of the Docker container. Then, any apps from host or other machine can communicate with this container via specific port.
Recently, I was able to create Docker image with NEST 2.14 (without MUSIC and GSL, I apologize for excluding these) and NEST web API. The docker image is able to run on any host OS.
Interestingly, this docker image needs only approx. 600 MB (very small, compared to VBox image which takes approx. 8 GB).

Please feel free to post ideas, suggestion and feedback for NEST web API.

If you like to use it on your machine: https://github.com/babsey/nest-web-api

**Comment by aserenko** [comment]
Maybe it might be easier to transmit requests in SLI, handling the python-to-SLI translation on the client side?
