### ISSUE TITLE
regressiontests/ticket-659-copyright.py fails if NEST build directory is in source directory

### ISSUE THREAD

**Issue by alberto-antonietti** [nest/nest-simulator#911]
I noticed that if NEST is built in a folder inside the source directory (e.g. nest-simulator/b ), the test done by ticket-659-copyright fails because of the headers that are not correctly ignored.

`Running test 'regressiontests/ticket-659-copyright.py'... 
   > Incorrect copyright header in '/home/alberto/nest-simulator/b/include/nest/libc_allocator_with_realloc.h':
   >     expected -> '/*', actual -> '// Copyright (c) 2010, Google Inc.'
   > 
   > Incorrect copyright header in '/home/alberto/nest-simulator/b/include/nest/mt19937.h':
   >     expected -> '/*', actual -> '#ifndef MT19937_H'
   > 
   > Incorrect copyright header in '/home/alberto/nest-simulator/b/include/nest/type_traits.h':
   >     expected -> '/*', actual -> '// Copyright (c) 2006, Google Inc.'
   > 
   > Incorrect copyright header in '/home/alberto/nest-simulator/b/include/nest/template_util.h':
   >     expected -> '/*', actual -> '// Copyright 2005 Google Inc.'
   > 
   > Incorrect copyright header in '/home/alberto/nest-simulator/b/include/nest/hashtable-common.h':
   >     expected -> '/*', actual -> '// Copyright (c) 2010, Google Inc.'
   > 
   > Incorrect copyright header in '/home/alberto/nest-simulator/b/include/nest/knuthlfg.h':
   >     expected -> '/*', actual -> '#ifndef KNUTHLFG_H'
   > 
   > Incorrect copyright header in '/home/alberto/nest-simulator/b/include/nest/sparseconfig.h':
   >     expected -> '*  sparseconfig.h', actual -> '* NOTE: This file is for internal use only.'
   > 
   > Incorrect copyright header in '/home/alberto/nest-simulator/b/include/nest/sparsetable.h':
   >     expected -> '/*', actual -> '// Copyright (c) 2005, Google Inc.'
   > 
   > Files with errors '8' out of '2122'!
-> 20 (Failed: inconsistent copyright header(s))`

This is a minor issue, but I can easily fix the code of ticket-659-copyright to avoid the failure in case someone builds NEST inside the nest source directory.

**Comment by heplesser** [comment]
@alberto-antonietti We generally recommend against building NEST in the source directory, but since we do not explicitly prevent it, building should work correctly. It would be great if you could provide a pull request to fix this.

**Comment by jougs** [comment]
Closed by #914.
