### ISSUE TITLE
Installation on mac: homebrew/science deprecated

### ISSUE THREAD

**Issue by AlexVanMeegen** [nest/nest-simulator#916]
Dear all,

installing NEST on a macOS High Sierra using Homebrew didn't work because `brew tap homebrew/science` returns `Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.`

In the [announcement of Homebrew 1.5.0](https://brew.sh/2018/01/19/homebrew-1.5.0/) is a bit of additional information:

> The Homebrew/science tap has been archived (for the reasons explained above) as noted previously. This does not represent an adversarial relationship between Homebrew and the science community (as we have imported the widely used formulae from this tap) but an inability to maintain an acceptable level of quality in this tap and differences of opinion on contributor experience (this tap aimed to work on Homebrew and Linuxbrew which made contribution difficult).

**Comment by heplesser** [comment]
@AlexVanMeegen Please use `brew tap brewsci/science`.
@steffengraber Could you re-generate the help webpages so the corrections made in #897?

**Comment by heplesser** [comment]
@steffengraber Thank you!
