### ISSUE TITLE
How can I record the changes of the synapse's weight during the simulation ?

### ISSUE THREAD

**Issue by nchr9** [nest/nest-simulator#919]
I use a custom synapse . Is there any way to keep track of the weight change ?

**Comment by heplesser** [comment]
@nchr9 Questions such as this are better asked on the NEST User mailing list, where you usually will get answers sooner.

You can use the `weight_recorder` to record synapse weights every time a spike passes through a synapse (weights are not well-defined in between spikes). Here is a small example:
```
        wr = nest.Create('weight_recorder')
        nest.CopyModel("stdp_synapse", "stdp_synapse_rec",
                       {"weight_recorder": wr[0], "weight": 1.})

        sg = nest.Create("spike_generator",
                         params={"spike_times": [10., 15., 55., 70.]})
        pre = nest.Create("parrot_neuron", 5)
        post = nest.Create("parrot_neuron", 5)

        nest.Connect(pre, post, syn_spec="stdp_synapse_rec")
        nest.Connect(sg, pre)

        connections = nest.GetConnections(pre, post)

        nest.Simulate(100)

        wr_weights = nest.GetStatus(wr, "events")[0]["weights"]
```
Note that the weight recorder is not connected to a neuron but specified in the synapse model.

**Comment by nchr9** [comment]
I am new NEST-user. Even though I made a subscription to nest-community I can't post anything yet to the mailing list.  
Thanks for your answer.  I am using nest 2.4.2! 
when I run <<wr = nest.Create('weight_recorder')>> 
it yields me an error which says  :
NESTError: UnknownModelName in Create_l_i: /weight_recorder is not a known model name.
Can I add it to my models ?

**Comment by alberto-antonietti** [comment]
@nchr9 the weight_recorder device has been made available from NEST 2.12.0. Are you able to use a more recent version of NEST?

**Comment by nchr9** [comment]
@alberto-antonietti  The BCPNN module I use is only compatible with nest 2.2.2 and 2.4.2 !  That's why I installed 2.4.2 before importing the module. But now, after installing the module, if I upgrade nest to a newer version, will that cause me problems anew ?

**Comment by jougs** [comment]
I'm afraid that you either have to update your module to a newer NEST version or back-port the `weight_recorder` to your version (which I reckon is much harder).

However, although it might be possible to back-port the `weight_recorder` in theory, I really recommend you to upgrade. Your version 2.4.2 was released on August 19, 2014 and we have fixed numerous smaller and bigger bugs in the recent 3½ years and no one can tell that you are not bitten by one of them. In addition to the `weight_recorder` there were numeours improvements and new models you might even find useful. See the [release notes](https://github.com/nest/nest-simulator/releases) for details.

**Comment by heplesser** [comment]
@nchr9 I believe the BCPNN model is implemented using PyNN, not NEST directly. Therefore, there is a good chance that PyNN insulates you from underlying changes in NEST, although you may need the newest version of PyNN to work with NEST 2.14.0.

Concerning the mailing list, I do not see any pending subscriptions requests. Please contact me by email if you do not receive mail from the list or cannot post to it.
