### ISSUE TITLE
Problem with NEST 2.14.0 installation (cmake)

### ISSUE THREAD

**Issue by Vaurien96** [nest/nest-simulator#922]
Hi folks !

Description of problem: I am trying to install NEST 2.14.0 on Ubuntu 16.04 to run it with Python.
Therefore I try these steps : http://www.nest-simulator.org/installation/ (introduction)

But when I try the cmake line I get the the following output and cannot run "make" :

`cmake -DCMAKE_INSTALL_PREFIX:PATH='/home/ubuntu/Téléchargements/nest' '/home/ubuntu/Téléchargements/nest-simulator-2.14.0' 
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file mach-o/dyld.h
-- Looking for include file mach-o/dyld.h - not found
-- Looking for include file mach/mach.h
-- Looking for include file mach/mach.h - not found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for C++ include istream
-- Looking for C++ include istream - found
-- Looking for C++ include ostream
-- Looking for C++ include ostream - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Check size of u_int16_t
-- Check size of u_int16_t - failed
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Looking for NAN
-- Looking for NAN - found
-- Looking for isnan
-- Looking for isnan - found
-- Looking for M_E
-- Looking for M_E - found
-- Looking for M_PI
-- Looking for M_PI - found
-- Looking for expm1
-- Looking for expm1 - not found
-- Host triple: x86_64-pc-linux
-- Target triple: x86_64-pc-linux
-- Could NOT find LTDL (missing:  LTDL_LIBRARIES LTDL_INCLUDE_DIRS) 
-- Could NOT find Readline (missing:  READLINE_LIBRARY READLINE_INCLUDE_DIRS) 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Could NOT find GSL (missing:  GSL_INCLUDE_DIR GSL_LIBRARY GSL_CBLAS_LIBRARY) 
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "2.7.12")
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Check the abort exitcode.
-- Check the abort exitcode. 134
-- Check the segmentation fault exitcode.
-- Check the segmentation fault exitcode. 139
-- Check whether the compiler ignores cmath makros.
-- Check whether the compiler ignores cmath makros. OFF
-- Check whether the compiler does NOT include <*.h> headers ISO conformant.
-- Check whether the compiler does NOT include <*.h> headers ISO conformant. OFF
-- Check whether the compiler respects symbolic signal names in signal.h.
-- Check whether the compiler respects symbolic signal names in signal.h. OFF
-- Check static template member declaration.
-- Check static template member declaration. OFF
-- Check for STL vector capacity base unity.
-- Check for STL vector capacity base unity. ON
-- Check for STL vector capacity doubling strategy.
-- Check for STL vector capacity doubling strategy. ON
-- Check whether the compiler fails with ICE.
-- Check whether the compiler fails with ICE. OFF
-- Check if ::nan is available from cmath.
-- Check if ::nan is available from cmath. ON
-- Check if ::isnan is available from cmath.
-- Check if ::isnan is available from cmath. ON
v2.14.0

--------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Build type          : 
Target System       : Linux
Cross Compiling     : FALSE
C compiler          : /usr/bin/cc
C compiler flags    :  -O2 -Wall -fopenmp -fdiagnostics-color=auto
C++ compiler        : /usr/bin/c++
C++ compiler flags  :  -O2 -Wall -fopenmp -fdiagnostics-color=auto
Build dynamic       : ON

Built-in modules    : models;precise;topology
User modules        : None
Python bindings     : No
Use threading       : Yes (OpenMP: -fopenmp)
Use GSL             : No
Use Readline        : No
Use libltdl         : No
Use doxygen         : No
Use MPI             : No
Use MUSIC           : No
Use libneurosim     : No

--------------------------------------------------------------------------------

The NEST executable will be installed to:
  /home/ubuntu/Téléchargements/nest/bin/

Documentation and examples will be installed to:
  /home/ubuntu/Téléchargements/nest/share/doc/nest/

To set necessary environment variables, add the following line
to your ~/.bashrc :
  source /home/ubuntu/Téléchargements/nest/bin/nest_vars.sh

--------------------------------------------------------------------------------

ATTENTION!
You are about to compile NEST without the GNU Scientific
Library or your GSL is to old (before v1.11). This means
that conductance-based neuron models and some random number
generators will not be available.

--------------------------------------------------------------------------------

You can now build and install NEST with
  make
  make install
  make installcheck

If you experience problems with the installation or the use of NEST,
please see http://www.nest-simulator.org/frequently_asked_questions
or go to http://www.nest-simulator.org/community to find out how to
join the user mailing list.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LTDL_LIBRARIES (ADVANCED)
    linked by target "nestkernel" in directory /home/ubuntu/Téléchargements/nest-simulator-2.14.0/nestkernel

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/Téléchargements/nest-simulator-2.14.0-build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/Téléchargements/nest-simulator-2.14.0-build/CMakeFiles/CMakeError.log".`

Could you please help me ?

**Comment by jougs** [comment]
You have to install the development package for libltdl. The command line (given on the [installation page](http://www.nest-simulator.org/installation/) you linked to) should get you everything you need:
```
sudo apt-get install -y build-essential cmake libltdl7-dev libreadline6-dev \
    libncurses5-dev libgsl0-dev python-all-dev python-numpy python-scipy \ 
    python-matplotlib ipython openmpi-bin libopenmpi-dev python-nose
```

Feel free to re-open if that does not help.

**Comment by Vaurien96** [comment]
Ok that worked. Thank you and sorry for how trivial that was.
