### ISSUE TITLE
poisson generator- same output

### ISSUE THREAD

**Issue by nchr9** [nest/nest-simulator#925]
Hi, 
Because I have an issue with posting at mailing list I am writing my problem here. I use a poisson generator but each time it creates the same membrane potential to the neurons. 
Do you know how the generator can produce random values without changing firing rates ?

**Comment by mschmidt87** [comment]
In NEST, the creation of random number is controlled by setting the seeds for the global and local random number generators. By default, the seed of the global random number generator is set to 0, the seeds for the local random number generators (one generator per thread) are set to 1, 2, 3, etc. .

You can see this by typing:
```
nest.GetKernelStatus()['grng_seed'])
nest.GetKernelStatus()['rng_seeds'])
```

If you want to obtain different spikes from your Poisson generator, you thus have to set the seed of the local random number generator(s) manually, by doing e.g.
`nest.SetKernelStatus({'rng_seeds': [1231241]})`

A full explanation of random number in NEST can be found here: http://www.nest-simulator.org/random-numbers/

**Comment by nchr9** [comment]
Thank you very much. Now It works properly.

**Comment by mschmidt87** [comment]
Great, this can be closed.
