### ISSUE TITLE
inconsistent documentation of inhomogeneous_poisson_generator

### ISSUE THREAD

**Issue by mschmidt87** [nest/nest-simulator#926]
I am trying to use the `inhomogeneous_poisson_generator` (introduced in #671 ) and the help page of this model mentions a parameter `individual_spike_trains`:

>   Individual spike trains vs single spike train: by default, the generator  
  sends a different spike train to each of its targets.  If  
  /individual_spike_trains is set to false using either SetDefaults or  
  CopyModel before a generator node is created, the generator will send the  
  same spike train to all of its targets.  

However, this property does not seem to exist in the model. 
`nest.GetDefaults('inhomogeneous_poisson_generator')` gives

> {'allow_offgrid_times': False,
 'available': (999,),
 'capacity': (1000,),
 'element_type': <SLILiteral: stimulator>,
 'elementsize': 352,
 'frozen': False,
 'global_id': 0,
 'instantiations': (1,),
 'local': True,
 'model': <SLILiteral: inhomogeneous_poisson_generator>,
 'node_uses_wfr': False,
 'origin': 0.0,
 'rate_times': array([], dtype=float64),
 'rate_values': array([], dtype=float64),
 'start': 0.0,
 'stop': 1.7976931348623157e+308,
 'supports_precise_spikes': False,
 'thread': 0,
 'thread_local_id': -1,
 'type_id': <SLILiteral: inhomogeneous_poisson_generator>,
 'vp': -1}

Is this remark in the help a relict from an earlier version of the model?

I know that the desired behavior can be easily achieved by connecting the generator to a `parrot_neuron` so it seems that this functionality is not present in the model but the help should be fixed. Or did I miss something?

**Comment by heplesser** [comment]
@mschmidt87 The `individual_spike_trains` property seems to have entered the documentation by copy-paste from `sinusoidal_poisson_generator`. `inhomogeneous_poisson_generator` has always only supported individual spike trains. Could you take a look at the discussion for the PR that merged this model into master to see if there was an explicit decision not to support identical spike trains and then adapt comment or code?

**Comment by mschmidt87** [comment]
I just found these two related issues: #279 and #505 . It seems that there is a proposal on how to reform the windowing system but this was never implemented.

**Comment by heplesser** [comment]
@mschmidt87 Thanks for the detective work! I would suggest for now a minimally invasive procedure: delete the misleading documentation and leave everything else as is. #505 will revise windowing in a general fashion and we have a separate effort ongoing to overhaul documentation (@jessica-mitchell).
