### ISSUE TITLE
Assertion failed: (std::strlen( argv[ 0 ] ) > 0), function SLIStartup / MacOSX 

### ISSUE THREAD

**Issue by theuema** [nest/nest-simulator#933]
I installed nest using homebrew as described on our homepage! 

After realising that the nest module got installed in python2 per default i used 
brew reinstall nest --with-python3 --HEAD 

I do have a site-package "nest" present in /usr/local/lib/python3.6/site-packages/nest/ right now and finally, after exporting all the env variables in my .zshrc (from /usr/local/Cellar/nest/HEAD-e38d0c7_1/bin/nest_vars.sh) i felt that it might have to run now... 

But i run into the following assertion:

```
~ » python                           
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nest
[INFO] [2018.4.20 12:30:0 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.4.20 12:30:0 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:233 @ Network::create_rngs_] : Deleting existing random number generators
[INFO] [2018.4.20 12:30:0 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.4.20 12:30:0 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:284 @ Network::create_grng_] : Creating new default global RNG
Assertion failed: (std::strlen( argv[ 0 ] ) > 0), function SLIStartup, file /tmp/nest-20180420-7658-1fbhpmy/sli/slistartup.cc, line 280.
[1]    14263 abort      python 
```
slistartup.cc says: 

```
  // argv[0] is the name of the program that was given to the shell.
  // This name must be given to SLI, otherwise initialization fails.
  // To catch accidental removal, e.g. in pyNEST, we explicitly assert
  // that argv[0] is a non-empty string.
  assert( std::strlen( argv[ 0 ] ) > 0 );
```
Ok, but how can i provide argv[0] when just trying to import this module in python?
I am kind of stuck right now and i already read a lot of issues on this but i am not able to really fix it. 
Am i doing something wrong here? 

I also performed brew test nest: 

```
» brew test nest    
Testing brewsci/science/nest
==> /usr/local/Cellar/nest/HEAD-e38d0c7_1/bin/nest --version
==> /usr/local/Cellar/nest/HEAD-e38d0c7_1/share/nest/extras/do_tests.sh --test-pynest
Last 15 lines from /Users/theuema/Library/Logs/Homebrew/nest/test.02.do_tests.sh:
     Skipped: 8 (8 PyNEST)
     Failed: 1 (0 PyNEST)

***
*** There were errors detected during the run of the NEST test suite!
***
*** Please report the problem at
***     https://github.com/nest/nest-simulator/issues
***
*** To help us diagnose the problem, please attach the archived content
*** of these directories to the issue:
***     - '/private/tmp/nest-test-20180420-26439-1n1mcz9/reports'
***     - '/tmp/nest.s8Qgz'
***

Error: brewsci/science/nest: failed
Failed executing: /usr/local/Cellar/nest/HEAD-e38d0c7_1/share/nest/extras/do_tests.sh --test-pynest
/usr/local/Homebrew/Library/Homebrew/formula.rb:1792:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1730:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1730:in `system'
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/nest.rb:152:in `block in <class:Nest>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1636:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1635:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:837:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1634:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1628:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

Thanks in advance for any help!

**Comment by alberto-antonietti** [comment]
@theuema, if you run a python script instead of an interactive python session, do you obtain the same error?

Can you try to run this very simple script, just to check if the import succeeds?

[simple_check.zip](https://github.com/nest/nest-simulator/files/1939249/simple_check.zip)

**Comment by heplesser** [comment]
@theuema What happens if you start `nest` from the command line, without using Python? Quit with `Ctrl-D`.

**Comment by theuema** [comment]
@alberto-antonietti thanks for your suggestion: the import WORKS?.. 

`python3 simple_check.py                                                     
[INFO] [2018.5.1 11:26:42 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.5.1 11:26:42 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:233 @ Network::create_rngs_] : Deleting existing random number generators
[INFO] [2018.5.1 11:26:42 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.5.1 11:26:42 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:284 @ Network::create_grng_] : Creating new default global RNG

              -- N E S T --

  Copyright (C) 2004 The NEST Initiative
  Version 2.14.0 Apr 20 2018 11:40:53

This program is provided AS IS and comes with
NO WARRANTY. See the file LICENSE for details.

Problems or suggestions?
  Visit http://www.nest-simulator.org

Type 'nest.help()' to find out more about NEST.
**NEST imported**`


@heplesser thanks for this suggestion: nest starts correctly.. 

`~ » nest                                                                                                                     
[INFO] [2018.5.1 11:21:10 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.5.1 11:21:10 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:233 @ Network::create_rngs_] : Deleting existing random number generators
[INFO] [2018.5.1 11:21:10 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.5.1 11:21:10 /tmp/nest-20180420-7658-1fbhpmy/nestkernel/rng_manager.cpp:284 @ Network::create_grng_] : Creating new default global RNG

              -- N E S T --

  Copyright (C) 2004 The NEST Initiative
  Version 2.14.0 Apr 20 2018 11:40:53

This program is provided AS IS and comes with
NO WARRANTY. See the file LICENSE for details.

Problems or suggestions?
  Visit http://www.nest-simulator.org

Type 'help' to get more information.
Type 'quit' or CTRL-D to quit NEST.

SLI ] 
`

So it seems that just an interactive python session wont work? I still run in that same assertion..

**Comment by heplesser** [comment]
@theuema I can reproduce this problem under OSX, and a colleague could reproduce it under Linux.
Interestingly, everything works fine under OSX and Linux if one runs NEST from `ipython` instead of `python`. So you can have interactive sessions using `ipython`.

We will investigate. This is probably some library issue. Since the problem occurs only for interactive sessions, not while executing scripts, my first guess would be `readline`. We may also need to check Anaconda vs non-Ancona Pythons.

**Comment by heplesser** [comment]
- The assertion does not trigger for NEST 2.14.0 under OSX, neither using Anaconda Python 3.6.5 or 2.7.12.
- The assertion triggers with master (ad52581ce) and with the 5g-branch (e760d1d9611da99aa0b459c9122ce428f0b02631) using Anaconda Python 3.6.5.
I wonder if this could have something to do with changes in argument handling in PyNEST.

**Comment by alberto-antonietti** [comment]
@heplesser I get the same error with Linux and non-Anaconda Python 2.7.12.

**Comment by heplesser** [comment]
@theuema @alberto-antonietti The problem should be fixed in the newest master (
689190009a285b4404873590acac676ff9e04fce).
