### ISSUE TITLE
[feature request] Support gap junctions in tp.ConnectLayers

### ISSUE THREAD

**Issue by TomBugnon** [nest/nest-simulator#939]
Hi all,

I am noticing that gap junctions currently can't be created via the topology module's `ConnectLayers` function.  It would make sense to have support for this as gap junctions -like any other connection- are topologically organized in the brain, so I thought I would just raise the issue... (also, it would help me in my research :) )

Two immediate problems are that ConnectLayers doesn't seem to support the `make_symmetric` flag (this would be a very nice upgrade in itself as well, by the way) and uses a default value for the `delays` parameter although gap junctions don't have any. Are there more fundamental reasons why this is not supported?

In the meantime, the workaround proposed by Hans [in this issue](https://github.com/nest/nest-simulator/issues/904) of connecting layers with ConnectLayers using labelled synapses, querying the connections by label and reconnecting with `nest.Connect` does the trick here as well (although very inefficiently): 

```
l = topo.CreateLayer({'rows': 2, 'columns': 3, 'elements': 'hh_psc_alpha_gap'})

# Create dummy topological connections with labels and null weights
nest.SetDefaults('static_synapse_lbl', {'synapse_label': 1})
topo.ConnectLayers(l, l, {'connection_type': 'convergent',
                              'mask': {'circular': {'radius': 0.2 }},
                              'synapse_model': 'static_synapse_lbl',
                              'weights': 0.})

# Create gap junctions between the units connected by the dummy ConnectLayers call
conns = nest.GetConnections(source=nest.GetChildren(l)[0], synapse_label=1)
srcs, tgts, _, _, _ = zip(*conns)
nest.Connect(srcs, tgts, {'rule': 'one_to_one', 'make_symmetric': True}, {'model': 'gap_junction', 'weight': 1.0})
```

Cheers,
Tom

**Comment by terhorstd** [comment]
@hakonsbm, @stinebuu, could you comment on the status of this?

**Comment by stinebuu** [comment]
Unfortunately `make_symmetric` is still not allowed when connecting with a mask or a kernel. We also haven't made any changes so that gap junctions can be supported when masks or other spatial connectivity patterns are used, I don't know if this will be easier with the new setup or not.

**Comment by heplesser** [comment]
The implementation would be challenging and demand appears limited, therefore closing. @TomBugnon, please re-open if this is still important for you.
