### ISSUE TITLE
Pre-release: Test all examples and documentation

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#940]
Test that all the following work:

## Examples
- examples/nest
- pynest/examples
- topology/examples

## Documentation
- doc/model_details
- doc/nest_by_example
- topology/doc (run `make_manual.sh` to re-build manual and check)

**Comment by heplesser** [comment]
See also https://github.com/jakobj/nest-simulator/issues/73 for tests done on the 5g branch.

**Comment by hakonsbm** [comment]
I have run and verified that all examples work with the current master (b69389b).

**Comment by hakonsbm** [comment]
All documentation scripts except one run without problems with the current master. I have created PR #1004 fixing the one that didn't run (this is however not a new problem).

**Comment by hakonsbm** [comment]
#1004 is merged now, so this can be closed.
