### ISSUE TITLE
Pre-release: Ensure external modules build

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#941]
Test that
- MyModule builds and runs
- User modules listed on https://github.com/nest/nest-simulator/wiki/NEST-Modules build and run; inform module developers in case of problems.

**Comment by heplesser** [comment]
See also https://github.com/jakobj/nest-simulator/issues/74

**Comment by hakonsbm** [comment]
I have verified that user modules in https://github.com/nest/nest-simulator/wiki/NEST-Modules work (or at least are unchanged compared to jakobj#74). MyModule will work when #1003 is merged.

**Comment by heplesser** [comment]
@hakonsbm With #1002 solved by #1003, can this issue be closed?

**Comment by hakonsbm** [comment]
@heplesser Yes, I have verified that MyModule works now, so this issue can be closed.
