### ISSUE TITLE
SecondaryEvent data type smaller than unsigned int

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#955]
It looks like the logic in `write_to_comm_buffer` and `read_from_comm_buffer` (https://github.com/nest/nest-simulator/blob/master/nestkernel/event.h#L885 ff) for secondary events assumes that the events which will be written/read need to be larger than or of equal size as unsigned ints (`c + i * sizeof( unsigned int )`). Otherwise one might run into unallocated memory. @janhahne is that correct and if so, how would you introduce secondary events which are smaller than 4bytes?

**Comment by janhahne** [comment]
@jakobj Do we really assume this here? For data types smaller than unsigned int `number_of_uints_covered( void )` returns 1 (the integer division gives 0, but the following if statement increases the return value). Thus we definitely allocate (more than) enough memory. Additionally the `memcpy` statement in `write_to_comm_buffer`

```cpp
memcpy( &( *( pos + i ) ),
      c + i * sizeof( unsigned int ),
      std::min( left_to_copy, sizeof( unsigned int ) ) );
```

only copies the range of the original data type (see the `std::min`) into the allocated area (which is larger). The corresponding part in `read_from_comm_buffer` then also only copies this part to recover the original value.

Is there any argument which I miss here? Have you observed any unwanted behavior in such a case?

**Comment by jakobj** [comment]
yes, you are right, the `min` should take care of not running into unallocated memory. i've run into issues when defining a new secondary event that carries `bool` values, where I ended up with segmentation faults. will try to reproduce the bug and update this description

**Comment by heplesser** [comment]
@janhahne Anything new on this one?

**Comment by janhahne** [comment]
@heplesser @jakobj I think I found the very nasty error here. 

It is best explained by a small example
```cpp
#include <iostream>
#include <vector>


template < typename T >
size_t
size_of( T d )
{
  return sizeof( T );
}


int main(void)
{
  std::vector< bool > vec( 1, false );
  std::vector< bool >::iterator i = vec.begin();
  bool elem=false;
  
  std::cout << "Size with the use of the single element: " << size_of(elem) << std::endl;
  std::cout << "Size with the use of the iterator: "<< size_of(*i) << std::endl;
  
}
```

This gives the output
```
Size with the use of the single element: 1
Size with the use of the iterator: 16
```

In `operator>>` in  `event.h` there is one call with `*i` instead of with an actual variable. So the fix is a two-liner. Will create a PR right now.
