### ISSUE TITLE
tsodyks2_connection first PSP already depressed

### ISSUE THREAD

**Issue by MatthiasKohler** [nest/nest-simulator#957]
The tsodyks2_connection models short time synaptic depression. The depression depends on the time since the last spike. But for the first spike transmitted over the connection, there is no previous spike and the time of the last spike is given to the send function as zero. If the time of the first spike is very close to zero a high synaptic depression is observed, even if the connection was never used. 
Intuitively, if the connection is never used there should be no depression.

**Comment by heplesser** [comment]
@MatthiasKohler Could you post a brief script reproducing the effect?

@Silmathoron suggests to add an additional internal flag to suppress plasticity when the first spike passes a synapse. We should also check if this affects other plasticity models and whether the solution should be implemented in a base class.

**Comment by MatthiasKohler** [comment]
`#In this script two neurons connected with one tsodyks2_synapse
#are simulated. The presynaptic neuron is stimulated which in turn
#generates PSPs in the postsynaptic neuron. When the stimulation 
#is directly applied at the start of the simulation the first PSP
#is already depressed. When simulation is run for some time before
#stimulation is applied no depression is observed.
#
#Matthias Kohler

from matplotlib import pyplot as plt
import nest

spike_detectorParams = {"withgid": True, "withtime": True}
time_resolution = 0.01
multimeterParams = {'interval': time_resolution, "withtime":True, "record_from":["V_m"]}

def shortTimeDepressionCalibrate(simtime, prerun, 
                                          amp = 400.0,
                                          ExtWeight = 200.0,
                                          tau_syn_ex = 2.0,
                                          U = 1.0,
                                          u = 1.0,
                                          x = 1.0,
                                          tau_rec = 100.0,
                                          tau_fac = 0.0):
    
    nest.ResetKernel()
    nest.SetKernelStatus({"resolution": time_resolution})

    syn_spec = {"model": "tsodyks2_synapse", "U": U, "u": u, 'x': x, "tau_rec": tau_rec,
                "tau_fac": tau_fac, 'weight': ExtWeight}

    pop1 = nest.Create('iaf_psc_alpha', 1, params = {'tau_syn_ex': tau_syn_ex})
    pop2 = nest.Create('iaf_psc_alpha', 1, params = {'tau_syn_ex': tau_syn_ex})
    nest.Connect(pop1, pop2, 'all_to_all', syn_spec = syn_spec)

    multimeter1 = nest.Create("multimeter", 1)
    multimeter2 = nest.Create("multimeter", 1)

    nest.SetStatus(multimeter1 + multimeter2, multimeterParams)
    nest.Connect(multimeter1, pop1, "one_to_one")
    nest.Connect(multimeter2, pop2, "one_to_one")

    nest.Simulate(prerun)
    nest.SetStatus(pop1, {'I_e': amp})
    nest.Simulate(simtime)

    recording = nest.GetStatus(multimeter2)[0]
    V = recording['events']['V_m']
    t = recording['events']['times']

    return V, t

V1, t1 = shortTimeDepressionCalibrate(1000.0, 0.01)
V2, t2 = shortTimeDepressionCalibrate(1000.0, 1000.0)

fig, ax = plt.subplots()
ax.plot(t1, V1)
ax.plot(t2, V2)

plt.show()`

**Comment by MatthiasKohler** [comment]
``
`<#In this script two neurons connected with one tsodyks2_synapse
#are simulated. The presynaptic neuron is stimulated which in turn
#generates PSPs in the postsynaptic neuron. When the stimulation 
#is directly applied at the start of the simulation the first PSP
#is already depressed. When simulation is run for some time before
#stimulation is applied no depression is observed.
#
#Matthias Kohler

from matplotlib import pyplot as plt
import nest

spike_detectorParams = {"withgid": True, "withtime": True}
time_resolution = 0.01
multimeterParams = {'interval': time_resolution, "withtime":True, "record_from":["V_m"]}

def shortTimeDepressionCalibrate(simtime, prerun, 
                                          amp = 400.0,
                                          ExtWeight = 200.0,
                                          tau_syn_ex = 2.0,
                                          U = 1.0,
                                          u = 1.0,
                                          x = 1.0,
                                          tau_rec = 100.0,
                                          tau_fac = 0.0):
    
    nest.ResetKernel()
    nest.SetKernelStatus({"resolution": time_resolution})

    syn_spec = {"model": "tsodyks2_synapse", "U": U, "u": u, 'x': x, "tau_rec": tau_rec,
                "tau_fac": tau_fac, 'weight': ExtWeight}

    pop1 = nest.Create('iaf_psc_alpha', 1, params = {'tau_syn_ex': tau_syn_ex})
    pop2 = nest.Create('iaf_psc_alpha', 1, params = {'tau_syn_ex': tau_syn_ex})
    nest.Connect(pop1, pop2, 'all_to_all', syn_spec = syn_spec)

    multimeter1 = nest.Create("multimeter", 1)
    multimeter2 = nest.Create("multimeter", 1)

    nest.SetStatus(multimeter1 + multimeter2, multimeterParams)
    nest.Connect(multimeter1, pop1, "one_to_one")
    nest.Connect(multimeter2, pop2, "one_to_one")

    nest.Simulate(prerun)
    nest.SetStatus(pop1, {'I_e': amp})
    nest.Simulate(simtime)

    recording = nest.GetStatus(multimeter2)[0]
    V = recording['events']['V_m']
    t = recording['events']['times']

    return V, t

V1, t1 = shortTimeDepressionCalibrate(1000.0, 0.01)
V2, t2 = shortTimeDepressionCalibrate(1000.0, 1000.0)

fig, ax = plt.subplots()
ax.plot(t1, V1)
ax.plot(t2, V2)

plt.show()`
``

**Comment by MatthiasKohler** [comment]
```
#In this script two neurons connected with one tsodyks2_synapse
#are simulated. The presynaptic neuron is stimulated which in turn
#generates PSPs in the postsynaptic neuron. When the stimulation 
#is directly applied at the start of the simulation the first PSP
#is already depressed. When simulation is run for some time before
#stimulation is applied no depression is observed.
#
#Matthias Kohler

from matplotlib import pyplot as plt
import nest

spike_detectorParams = {"withgid": True, "withtime": True}
time_resolution = 0.01
multimeterParams = {"interval": time_resolution, "withtime":True, "record_from":["V_m"]}

def shortTimeDepressionCalibrate(simtime, prerun, 
                                          amp = 400.0,
                                          ExtWeight = 200.0,
                                          tau_syn_ex = 2.0,
                                          U = 1.0,
                                          u = 1.0,
                                          x = 1.0,
                                          tau_rec = 100.0,
                                          tau_fac = 0.0):
    
    nest.ResetKernel()
    nest.SetKernelStatus({"resolution": time_resolution})

    syn_spec = {"model": "tsodyks2_synapse", "U": U, "u": u, "x": x, "tau_rec": tau_rec,
                "tau_fac": tau_fac, "weight": ExtWeight}

    pop1 = nest.Create("iaf_psc_alpha", 1, params = {"tau_syn_ex": tau_syn_ex})
    pop2 = nest.Create("iaf_psc_alpha", 1, params = {"tau_syn_ex": tau_syn_ex})
    nest.Connect(pop1, pop2, "all_to_all", syn_spec = syn_spec)

    multimeter1 = nest.Create("multimeter", 1)
    multimeter2 = nest.Create("multimeter", 1)

    nest.SetStatus(multimeter1 + multimeter2, multimeterParams)
    nest.Connect(multimeter1, pop1, "one_to_one")
    nest.Connect(multimeter2, pop2, "one_to_one")

    nest.Simulate(prerun)
    nest.SetStatus(pop1, {"I_e": amp})
    nest.Simulate(simtime)

    recording = nest.GetStatus(multimeter2)[0]
    V = recording["events"]["V_m"]
    t = recording["events"]["times"]

    return V, t

V1, t1 = shortTimeDepressionCalibrate(1000.0, 0.01)
V2, t2 = shortTimeDepressionCalibrate(1000.0, 1000.0)

fig, ax = plt.subplots()
ax.plot(t1, V1)
ax.plot(t2, V2)

plt.show()

```
