### ISSUE TITLE
Assertion error during ConnectLayers execution

### ISSUE THREAD

**Issue by keiko-fujii** [nest/nest-simulator#961]
When I call topology.ConnectLayers(), I got an assertion error.

> python: /home/MY_PATH/nest-simulator/topology/ntree_impl.h:523:
> nest::Ntree<D, T, max_capacity, max_depth>::iterator nest::Ntree<D, T,
max_capacity, max_depth>::insert(nest::Position<D, double>, const T&) [with
int D = 3, T = long unsigned int, int max_capacity = 100, int max_depth =
10]: Assertion `( pos >= lower_left_ ) && ( pos < lower_left_ + extent_ )'
failed.

I inserted printf() in ntree_impl.h to get 'pos', 'lower_left_', and 'extent_' values.
- pos = [-27.783000, -26.453000, 13.511000]
- lower_left_= [-28.775250, -26.535305, 12.565406]
- extent_ = [0.992250, 1.263586, 1.047117]
(In this case, x-value of (lower_left_+extent_) is equal to pos.)

I generated a simplified code, which replicates the error.
The file 'neuron_pos.dat'  is generated by Matlab and contains 350220 x 3 double data (I don't know how to share it). I tried to replicate the error with smaller XYZ position data, but so far I couldn't.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import nest
import nest.topology as tp
import numpy as np

nest.ResetKernel()
nest.ResetNetwork()

# --- Load neuron position data, and get brain size
# --- Matrix size = [N x 3]. 1st_col=x, 2nd_col=y, 3rd_col=z. N = num of XYZ positions
pos_filename = 'neuron_pos.dat'
pos = np.loadtxt(open(pos_filename, 'r'))
size_x = np.max(pos, axis=0)[0] - np.min(pos, axis=0)[0]
size_y = np.max(pos, axis=0)[1] - np.min(pos, axis=0)[1]
size_z = np.max(pos, axis=0)[2] - np.min(pos, axis=0)[2]

# --- Create a layer
num_overlap = 30
layer_property = {
    'positions': pos.tolist(),
    'extent': [size_x*2, size_y*2, size_z*2],  # I guess brain_size*2 is wide enough
    'elements': ['ht_neuron', num_overlap],  # 30 neurons share one XYZ position
    'edge_wrap': False
}
cortex_layer = tp.CreateLayer(layer_property)

# --- Create connections
receptors = nest.GetDefaults('ht_neuron')['receptor_types']
nest.CopyModel('ht_synapse', 'AMPA_synapse', {'receptor_type': receptors['AMPA']})
connection_property = {
    'connection_type': 'divergent',
    'synapse_model': 'AMPA_synapse',
    'mask': {'spherical': {'radius': 2.7}},
    'kernel': {'gaussian': {'p_center': 0.625, 'sigma': 1.69}},
    'weights': 1.0,
    'delays': {'uniform': {'min': 1.75, 'max': 2.25}},
    'allow_autapses': False,
    'allow_multapses': False
}
tp.ConnectLayers(cortex_layer, cortex_layer, connection_property)  # This causes assertion error.
```

**Comment by heplesser** [comment]
@keiko-fujii I suspect that this is a numerical issue due to, see my comments on NEST User today. As a first attempt at a work-around, could you use `np.ceil(size_x)` instead of `size_x * 2` in `extent` and correspondingly for the other dimensions? That will minimize rounding problems for boundaries of the ntree octants.

Maybe you could send me the position data by direct mail in compressed form or post it on Dropbox or similar where I could pick it up? It would help us to diagnose the problem thoroughly.

**Comment by keiko-fujii** [comment]
@heplesser  As you mentioned, using 
`'extent': [np.ceil(size_x*2), np.ceil(size_y*2), np.ceil(size_z*2)]`
didn't cause the assertion error.

I ran twice for each 'extent' condition (i.e. with /without np.ceil()), 
I got 2 sucesess with np.ceil(), whereas 2 fails without np.ceil().

Now I understood better what you kindly explained about subcube and rounding error in one previous e-mail.
I quote your explanation here to gather information in one place:
> The ntree divides the entire extent of the layer into cubes, and each cube is subdivided further once it contains more than max_capacity neurons. This allows for efficient spatial search after neurons. Each of those cubes is defined as a left-closed, right-open interval along each of the three coordinate axes. The assertion that fails in your case is meant to ensure that the neuron at position pos is inserted into the correct subcube.

I have questions.
(1) If I set unnecessarily wide extent, like 
`'extent': [np.ceil(size_x*10), np.ceil(size_y*10), np.ceil(size_z*10)]`
Is this result in the same neural network structure output as using size*2? Is subcube division the same?
(I understand that processing time can be longer, but how about network & neural activity?)

(2) I think 'extent' setting is required when a user doesn't design neuron positions explicitly. On the other hand, if neuron positions are directly set by a user, a safe and near-optimal 'extent' can be determined automatically from the positions (i.e. a user doesn't need to set 'extent'). Am I correct?

**Comment by keiko-fujii** [comment]
@heplesser Thank you so much for your kind answer.
I feel all of my questions are clear now.
Is it better if I close this issue, or keep this open?

**Comment by heplesser** [comment]
@keiko-fujii Excellent! I would suggest to close this issue. I will add a sentence to the Topology documentation to make clear that the extent should have sizes that are representable as fractions in binary.

**Comment by keiko-fujii** [comment]
@heplesser Thank you again for all your help!
