### ISSUE TITLE
mpirun has detected an attempt to run as root.

### ISSUE THREAD

**Issue by xdzhangxuejun** [nest/nest-simulator#968]
Running at root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

**Comment by heplesser** [comment]
@xdzhangxuejun This is not a NEST problem. If NEST is built in a normal user account and started from a normal user account, it should never run as root. The error message you see must be due to some problem on you system. I am therefore closing this issue.

**Comment by xdzhangxuejun** [comment]
Ok. Thank for your information.






在 2018-06-11 14:54:52，"Hans Ekkehard Plesser" <notifications@github.com> 写道：


Closed #968.

**Comment by xdzhangxuejun** [comment]
Ok. Thank for your help.




At 2018-06-11 14:54:52, "Hans Ekkehard Plesser" <notifications@github.com> wrote:


@xdzhangxuejun This is not a NEST problem. If NEST is built in a normal user account and started from a normal user account, it should never run as root. The error message you see must be due to some problem on you system. I am therefore closing this issue.
