### ISSUE TITLE
can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by xdzhangxuejun** [nest/nest-simulator#969]
/usr/bin/ld: /usr/local/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC

**Comment by heplesser** [comment]
@xdzhangxuejun Cryptic error messages do not make issues. If you run into a problem installing or running NEST and would like help, please provide a detailed description of what you are trying to do, on what kind of system (OS, compiler, Python version, ...). For this type of inquiry, the NEST User Mailing List (http://www.nest-simulator.org/community/) is a better forum than Github issues. I am therefore closing this issue for now.

**Comment by xdzhangxuejun** [comment]
OK !Thank you very much.






At 2018-06-11 14:57:47, "Hans Ekkehard Plesser" <notifications@github.com> wrote:


@xdzhangxuejun Cryptic error messages do not make issues. If you run into a problem installing or running NEST and would like help, please provide a detailed description of what you are trying to do, on what kind of system (OS, compiler, Python version, ...). For this type of inquiry, the NEST User Mailing List (http://www.nest-simulator.org/community/) is a better forum than Github issues. I am therefore closing this issue for now.

**Comment by xdzhangxuejun** [comment]
Ok! thank you for your advice.



在 2018-06-11 14:57:47，"Hans Ekkehard Plesser" <notifications@github.com> 写道：


Closed #969.
