### ISSUE TITLE
allow_offgrid_times vs allow_offgrid_spikes

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#971]
This is a follow-up to #967.

`spike_generator` has parameter `allow_offgrid_spikes` that controls if spike times can be set to times not multiples of the step; such times are rounded up to the next step.

`inhomogeneous_poisson_generator` and `step_current_generator` have parameter `allow_offgrid_times` that similarly control the setting of times at which poisson rate or output current are changed to new values.

Does it really make sense to have these two almost equal names? Should we standardize to one, which in this case would have to be `allow_offgrid_times`, since `..._spikes` makes no sense for the current generator and would be misleading for the poisson generator.

**Comment by abigailm** [comment]
It doesn't make sense. We should standardize to `allow_offgrid_times` or simply `allow_offgrid`

**Comment by heplesser** [comment]
@stinebu Ping!

**Comment by stinebuu** [comment]
@heplesser  I have just fixed this in the nest-3 branch, see f2242bc2576863bb5e514af07f275da6c84f1634. Should I close this, or are we waiting for the branch to be merged into master?

**Comment by heplesser** [comment]
@stinebuu I think we decided to leave the issues open until NEST-3 is merged.
