### ISSUE TITLE
negative conductance in gif_cond_exp model

### ISSUE THREAD

**Issue by yan1982** [nest/nest-simulator#975]
Hello,
I notice that conductance of inhibitory synapses recorded from gif_cond_exp model is always negative. The problem seems to come from line 617 of the gif_cond_exp.cpp file. Apparently the minus sign has been forgotten.

**Comment by heplesser** [comment]
@yan1982 Thanks for noticing this! Could you create a pull request with a fix, and preferably a regression test?
