### ISSUE TITLE
Proposal: Explicit index of pyNEST package

### ISSUE THREAD

**Issue by babsey** [nest/nest-simulator#981]
Hello all,

as I mentioned at the NEST conference I would like to decrease security risks in NEST. Here, I propose to explicit index in NEST. I was able to reduce from 113 to 50 indices in NEST packages.

Moreover, I exclude imported packages, e.g. sys, os, numpy... as well as some SLI functions.
If anyone disagree with it, I can modify `__all__` list in `_main.py` file.
If anyone like to import sli function, use `from nest.lib.hl_api_helper import sli_func, sr, spp, sps`.

This proposal has no high priority. Thus, I prepare it for NEST 3.
I modified the codes in forked version from stinebuu/merge-GIDColl-5g.

You can check it yourself in the branch `explicit_index` of my forked version.
https://github.com/babsey/nest-simulator/tree/explicit_index

**Comment by terhorstd** [comment]
this is a good point! would you be able to provide a PR against master for this?
