### ISSUE TITLE
outdated example `/topology/examples/hill_tononi_Vp.py`

### ISSUE THREAD

**Issue by espenhgn** [nest/nest-simulator#982]
Some of the description(s) in this example file is out of data. Accd. to a note it's supposed to produce 5Hz oscillations, but connecting a spike recorder to the system reveals fast oscillations:
![image](https://user-images.githubusercontent.com/2492641/42296980-65e66b84-8036-11e8-97a2-ce025605d716.png)

Now that the Hill&Tononi neuron model (`ht_neuron`) is built into NEST, I think the script should probably use that model as well, instead of the presently used `iaf_cond_alpha` neuron

On a related note, @andresni is working on reproducing the model from the paper in detail and has set up model generation from YAML in NEST at https://github.com/andresni/NYP, but the corresponding paper(s) have not been published. Maybe in some future version of NEST his model setup could be integrated closer...

**Comment by stinebuu** [comment]
Decision from NEST 3.0 issue sorting session: @heplesser will check with `ht_neuron` users for more up to date examples, the Hill Tononi example could then be removed from the NEST source code.

**Comment by sarakonradi** [comment]
@stinebuu @heplesser Are there any updates on this?

**Comment by stinebuu** [comment]
@sarakonradi Not from my side.

**Comment by heplesser** [comment]
I suggest to remove this example from NEST. There is now a publicly available NEST-implementation of the complete Hill-Tononi model with carefully checked dynamics (https://github.com/ricardomurphy/Multiarea-Hill-Tononi-thalamocortical-network-model) for those interested in the model itself. Another aspect of the example was to show how to integrate documentation and Python code for a model, but here Jupyter notebooks have become quite standard and for very complex models one has the MAM as example (https://inm-6.github.io/multi-area-model/).
