### ISSUE TITLE
WeightRecorderEvent::receiver_gid initialized with invalid value

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#989]
`WeightRecorderEvent::receiver_gid` is of unsigned integer type but initialized with `-1`. This does not lead to problems in practice, but is not good practice either. 

We need to choose a valid value marking the absence of a receiver. `0` may be a suitable choice, since 0 can never be the GID of a recorder.

**Comment by weidel-p** [comment]
Thanks for spotting this issue, I will create a PR fixing this.
