### ISSUE TITLE
Multiple definition of nest::names::sigma and ::theta

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#992]
At c808ff03bedeb9974d38da420a1b72b244225443, building NEST on JURON I get:
```
[ 99%] Linking CXX executable nest
../topology/libtopology.a(topology_names.cpp.o):(.bss+0x180): multiple definition of `nest::names::sigma'
../nestkernel/libnestkernel.a(nest_names.cpp.o):(.bss+0x988): first defined here
/usr/bin/ld: Disabling relaxation: it will not work with multiple definitions
../topology/libtopology.a(topology_names.cpp.o):(.bss+0x1a8): multiple definition of `nest::names::theta'
../nestkernel/libnestkernel.a(nest_names.cpp.o):(.bss+0xc28): first defined here
make[2]: *** [nest/nest] Error 1
make[1]: *** [nest/CMakeFiles/nest.dir/all] Error 2
make: *** [all] Error 2
```
While the lazy fix is simple, but I'll let the maintainers decide how to fix this.

**Comment by heplesser** [comment]
@ikitayama This is fixed in the 5G branch already, so it will be solved once #920 is merged.

**Comment by ikitayama** [comment]
@heplesser Ok, are we close enough to do that, or can you cherry-pick the specific fix?

**Comment by heplesser** [comment]
@ikitayama I think we will be ready to merge 5G into Master very, very soon now (tomorrow, maybe even today), so I would prefer to avoid cherry-picking to master at this late point. Is that okay with you?

**Comment by ikitayama** [comment]
@heplesser no problem, sir!

**Comment by ikitayama** [comment]
Closing.
